//HPCC Systems KEL Compiler Version 1.2.1-dev
IMPORT KEL12 AS KEL;
IMPORT B_Person_4,B_Person_Vehicle_4,B_Person_Vehicle_5,B_Vehicle_4,CFG_Compile,E_Person,E_Person_Vehicle,E_Vehicle FROM ProfileBooster.ProfileBoosterV2_KEL;
IMPORT * FROM KEL12.Null;
EXPORT B_Person_3(CFG_Compile __cfg = CFG_Compile) := MODULE
  SHARED VIRTUAL TYPEOF(B_Person_4(__cfg).__ENH_Person_4) __ENH_Person_4 := B_Person_4(__cfg).__ENH_Person_4;
  SHARED VIRTUAL TYPEOF(B_Person_Vehicle_4(__cfg).__ENH_Person_Vehicle_4) __ENH_Person_Vehicle_4 := B_Person_Vehicle_4(__cfg).__ENH_Person_Vehicle_4;
  SHARED VIRTUAL TYPEOF(B_Vehicle_4(__cfg).__ENH_Vehicle_4) __ENH_Vehicle_4 := B_Vehicle_4(__cfg).__ENH_Vehicle_4;
  SHARED __EE47080 := __ENH_Person_4;
  SHARED __EE47136 := __ENH_Vehicle_4;
  SHARED __EE51472 := __EE47136;
  SHARED __EE53160 := __EE51472(__T(__AND(__EE51472.Flag_Auto_,__CN(__EE51472.Flag_Vina_Make_Desc_ = (KEL.typ.str)1))));
  SHARED __EE47134 := __ENH_Person_Vehicle_4;
  SHARED __EE50958 := __EE47134(__NN(__EE47134.Subject_) AND __NN(__EE47134.Automobile_));
  SHARED __EE51475 := __EE50958;
  SHARED __ST44865_Layout := RECORD
    KEL.typ.nuid UID;
    KEL.typ.nstr Vehicle_Key_;
    KEL.typ.nstr State_Of_Origin_;
    KEL.typ.nstr Original_Vin_;
    KEL.typ.nint Original_Year_Make_;
    KEL.typ.nstr Original_Make_;
    KEL.typ.nstr Original_Make_Description_;
    KEL.typ.nstr Original_Series_;
    KEL.typ.nstr Original_Series_Description_;
    KEL.typ.nstr Original_Model_;
    KEL.typ.nstr Original_Model_Description_;
    KEL.typ.nstr Original_Body_;
    KEL.typ.nstr Original_Body_Description_;
    KEL.typ.nint Original_Net_Weight_;
    KEL.typ.nint Original_Gross_Weight_;
    KEL.typ.nint Original_Number_Axles_;
    KEL.typ.nstr Original_Vehicle_Use_;
    KEL.typ.nstr Original_Vehicle_Use_Description_;
    KEL.typ.nstr Original_Vehicle_Type_;
    KEL.typ.nstr Original_Vehicle_Type_Description_;
    KEL.typ.nstr Original_Major_Color_;
    KEL.typ.nstr Original_Major_Color_Description_;
    KEL.typ.nstr Original_Minor_Color_;
    KEL.typ.nstr Original_Minor_Color_Description_;
    KEL.typ.nstr Vina_Vin_;
    KEL.typ.nstr Vina_Vin_Pattern_;
    KEL.typ.nstr Vina_Bypass_Code_;
    KEL.typ.nstr Vina_Vehicle_Type_;
    KEL.typ.nstr Vina_N_C_I_C_Make_;
    KEL.typ.nint Vina_Model_Year_Y_Y_;
    KEL.typ.nstr Vina_Restraint_;
    KEL.typ.nstr Vina_Make_Name_;
    KEL.typ.nint Vina_Year_;
    KEL.typ.nstr Vina_Vp_Series_;
    KEL.typ.nstr Vina_Vp_Model_;
    KEL.typ.nstr Vina_Air_Conditioning_;
    KEL.typ.nstr Vina_Power_Steering_;
    KEL.typ.nstr Vina_Power_Brakes_;
    KEL.typ.nstr Vina_Power_Windows_;
    KEL.typ.nstr Vina_Tilt_Wheel_;
    KEL.typ.nint Vina_Roof_;
    KEL.typ.nint Vina_Optional_Roof1_;
    KEL.typ.nint Vina_Optional_Roof2_;
    KEL.typ.nstr Vina_Radio_;
    KEL.typ.nstr Vina_Optional_Radio1_;
    KEL.typ.nstr Vina_Optional_Radio2_;
    KEL.typ.nstr Vina_Transmission_;
    KEL.typ.nstr Vina_Optional_Transmission1_;
    KEL.typ.nstr Vina_Optional_Transmission2_;
    KEL.typ.nint Vina_A_L_B_;
    KEL.typ.nstr Vina_Front_W_D_;
    KEL.typ.nstr Vina_Four_W_D_;
    KEL.typ.nstr Vina_Security_System_;
    KEL.typ.nstr Vina_D_R_L_;
    KEL.typ.nstr Vina_Series_Name_;
    KEL.typ.nint Vina_Model_Year_;
    KEL.typ.nstr Vina_Series_;
    KEL.typ.nstr Vina_Model_;
    KEL.typ.nstr Vina_Body_Style_;
    KEL.typ.nstr Vina_Make_Description_;
    KEL.typ.nstr Vina_Model_Description_;
    KEL.typ.nstr Vina_Series_Description_;
    KEL.typ.nstr Vina_Body_Style_Description_;
    KEL.typ.nint Vina_Cylinders_;
    KEL.typ.nint Vina_Engine_Size_;
    KEL.typ.nstr Vina_Fuel_Code_;
    KEL.typ.nint Vina_Price_;
    KEL.typ.nstr Best_Make_Code_;
    KEL.typ.nstr Best_Series_Code_;
    KEL.typ.nstr Best_Model_Code_;
    KEL.typ.nstr Best_Body_Code_;
    KEL.typ.nint Best_Model_Year_;
    KEL.typ.nstr Best_Major_Color_;
    KEL.typ.nstr Best_Minor_Color_;
    KEL.typ.nstr Branded_Title_Flag_;
    KEL.typ.nstr Brand_Code1_;
    KEL.typ.nkdate Brand_Date1_;
    KEL.typ.nstr Brand_State1_;
    KEL.typ.nstr Brand_Code2_;
    KEL.typ.nkdate Brand_Date2_;
    KEL.typ.nstr Brand_Sate2_;
    KEL.typ.nstr Brand_Code3_;
    KEL.typ.nkdate Brand_Date3_;
    KEL.typ.nstr Brand_Sate3_;
    KEL.typ.nstr Brand_Code4_;
    KEL.typ.nkdate Brand_Date4_;
    KEL.typ.nstr Brand_Sate4_;
    KEL.typ.nstr Brand_Code5_;
    KEL.typ.nkdate Brand_Date5_;
    KEL.typ.nstr Brand_Sate5_;
    KEL.typ.nstr Safety_Type_;
    KEL.typ.nstr Airbag_Driver_;
    KEL.typ.nstr Airbag_Front_Driver_Side_;
    KEL.typ.nstr Airbag_Front_Head_Curtain_;
    KEL.typ.nstr Airbag_Front_Passanger_;
    KEL.typ.nstr Airbag_Front_Passanger_Side_;
    KEL.typ.nstr Airbags_;
    KEL.typ.nstr Tod_Flag_;
    KEL.typ.nstr Model_Class_Code_;
    KEL.typ.nstr Model_Class_;
    KEL.typ.nstr Min_Door_Count_;
    KEL.typ.nstr Latest_Vehicle_Flag_;
    KEL.typ.nstr Latest_Vehicle_Iteration_Flag_;
    KEL.typ.nkdate Date_Vendor_First_Reported_;
    KEL.typ.nkdate Date_Vendor_Last_Reported_;
    KEL.typ.nstr Standard_Lienholder_Name_;
    KEL.typ.nkdate Source_First_Date_;
    KEL.typ.nkdate Source_Last_Date_;
    KEL.typ.ndataset(E_Vehicle(__cfg).Data_Sources_Layout) Data_Sources_;
    KEL.typ.nbool Flag_Auto_;
    KEL.typ.nbool Flag_Other_;
    KEL.typ.str Flag_Vina_Make_Desc_ := '';
    KEL.typ.nstr Vehicle_Type_;
    KEL.typ.nstr Vina_Body_Style_Vehicle_Type_;
    KEL.typ.nstr Vina_Model_Date_;
    KEL.typ.ntyp(E_Person().Typ) Subject_;
    KEL.typ.ntyp(E_Vehicle().Typ) Automobile_;
    KEL.typ.ndataset(E_Person_Vehicle(__cfg).Registration_Layout) Registration_;
    KEL.typ.ndataset(E_Person_Vehicle(__cfg).Title_Layout) Title_;
    KEL.typ.ndataset(E_Person_Vehicle(__cfg).Counts_Model_Layout) Counts_Model_;
    KEL.typ.ndataset(E_Person_Vehicle(__cfg).Data_Sources_Layout) Data_Sources__1_;
    KEL.typ.nint Age_At_First_Seen_;
    KEL.typ.nfloat Age_Year_At_First_Seen_;
    KEL.typ.nkdate Current_Date_;
    KEL.typ.nkdate Date_First_Seen_Capped_;
    KEL.typ.nint Depreciated_Price_;
    KEL.typ.nbool Flag_Depreciated_Price_;
    KEL.typ.nstr Vehicle_Min_Date_;
    KEL.typ.epoch Date_First_Seen_ := 0;
    KEL.typ.epoch Date_Last_Seen_ := 0;
    KEL.typ.int __RecordCount := 0;
    UNSIGNED4 __Part := 0;
  END;
  __JC53166(B_Vehicle_4(__cfg).__ST9866_Layout __EE53160, B_Person_Vehicle_5(__cfg).__ST10168_Layout __EE51475) := __EEQP(__EE51475.Automobile_,__EE53160.UID) AND __EE53160.__Part = __EE51475.__Part;
  __ST44865_Layout __JT53166(B_Vehicle_4(__cfg).__ST9866_Layout __l, B_Person_Vehicle_5(__cfg).__ST10168_Layout __r) := TRANSFORM
    SELF.Data_Sources__1_ := __r.Data_Sources_;
    SELF := __l;
    SELF := __r;
  END;
  SHARED __EE53335 := JOIN(__EE51475,__EE53160,__JC53166(RIGHT,LEFT),__JT53166(RIGHT,LEFT),INNER,HASH);
  SHARED __ST40599_Layout := RECORD
    KEL.typ.ntyp(E_Person().Typ) Subject_;
    KEL.typ.ntyp(E_Vehicle().Typ) Automobile_;
    KEL.typ.ndataset(E_Person_Vehicle(__cfg).Registration_Layout) Registration_;
    KEL.typ.ndataset(E_Person_Vehicle(__cfg).Title_Layout) Title_;
    KEL.typ.ndataset(E_Person_Vehicle(__cfg).Counts_Model_Layout) Counts_Model_;
    KEL.typ.ndataset(E_Person_Vehicle(__cfg).Data_Sources_Layout) Data_Sources_;
    KEL.typ.nint Age_At_First_Seen_;
    KEL.typ.nfloat Age_Year_At_First_Seen_;
    KEL.typ.nkdate Current_Date_;
    KEL.typ.nkdate Date_First_Seen_Capped_;
    KEL.typ.nint Depreciated_Price_;
    KEL.typ.nbool Flag_Depreciated_Price_;
    KEL.typ.nstr Vehicle_Min_Date_;
    KEL.typ.nuid UID;
    KEL.typ.nstr Vehicle_Key_;
    KEL.typ.nstr State_Of_Origin_;
    KEL.typ.nstr Original_Vin_;
    KEL.typ.nint Original_Year_Make_;
    KEL.typ.nstr Original_Make_;
    KEL.typ.nstr Original_Make_Description_;
    KEL.typ.nstr Original_Series_;
    KEL.typ.nstr Original_Series_Description_;
    KEL.typ.nstr Original_Model_;
    KEL.typ.nstr Original_Model_Description_;
    KEL.typ.nstr Original_Body_;
    KEL.typ.nstr Original_Body_Description_;
    KEL.typ.nint Original_Net_Weight_;
    KEL.typ.nint Original_Gross_Weight_;
    KEL.typ.nint Original_Number_Axles_;
    KEL.typ.nstr Original_Vehicle_Use_;
    KEL.typ.nstr Original_Vehicle_Use_Description_;
    KEL.typ.nstr Original_Vehicle_Type_;
    KEL.typ.nstr Original_Vehicle_Type_Description_;
    KEL.typ.nstr Original_Major_Color_;
    KEL.typ.nstr Original_Major_Color_Description_;
    KEL.typ.nstr Original_Minor_Color_;
    KEL.typ.nstr Original_Minor_Color_Description_;
    KEL.typ.nstr Vina_Vin_;
    KEL.typ.nstr Vina_Vin_Pattern_;
    KEL.typ.nstr Vina_Bypass_Code_;
    KEL.typ.nstr Vina_Vehicle_Type_;
    KEL.typ.nstr Vina_N_C_I_C_Make_;
    KEL.typ.nint Vina_Model_Year_Y_Y_;
    KEL.typ.nstr Vina_Restraint_;
    KEL.typ.nstr Vina_Make_Name_;
    KEL.typ.nint Vina_Year_;
    KEL.typ.nstr Vina_Vp_Series_;
    KEL.typ.nstr Vina_Vp_Model_;
    KEL.typ.nstr Vina_Air_Conditioning_;
    KEL.typ.nstr Vina_Power_Steering_;
    KEL.typ.nstr Vina_Power_Brakes_;
    KEL.typ.nstr Vina_Power_Windows_;
    KEL.typ.nstr Vina_Tilt_Wheel_;
    KEL.typ.nint Vina_Roof_;
    KEL.typ.nint Vina_Optional_Roof1_;
    KEL.typ.nint Vina_Optional_Roof2_;
    KEL.typ.nstr Vina_Radio_;
    KEL.typ.nstr Vina_Optional_Radio1_;
    KEL.typ.nstr Vina_Optional_Radio2_;
    KEL.typ.nstr Vina_Transmission_;
    KEL.typ.nstr Vina_Optional_Transmission1_;
    KEL.typ.nstr Vina_Optional_Transmission2_;
    KEL.typ.nint Vina_A_L_B_;
    KEL.typ.nstr Vina_Front_W_D_;
    KEL.typ.nstr Vina_Four_W_D_;
    KEL.typ.nstr Vina_Security_System_;
    KEL.typ.nstr Vina_D_R_L_;
    KEL.typ.nstr Vina_Series_Name_;
    KEL.typ.nint Vina_Model_Year_;
    KEL.typ.nstr Vina_Series_;
    KEL.typ.nstr Vina_Model_;
    KEL.typ.nstr Vina_Body_Style_;
    KEL.typ.nstr Vina_Make_Description_;
    KEL.typ.nstr Vina_Model_Description_;
    KEL.typ.nstr Vina_Series_Description_;
    KEL.typ.nstr Vina_Body_Style_Description_;
    KEL.typ.nint Vina_Cylinders_;
    KEL.typ.nint Vina_Engine_Size_;
    KEL.typ.nstr Vina_Fuel_Code_;
    KEL.typ.nint Vina_Price_;
    KEL.typ.nstr Best_Make_Code_;
    KEL.typ.nstr Best_Series_Code_;
    KEL.typ.nstr Best_Model_Code_;
    KEL.typ.nstr Best_Body_Code_;
    KEL.typ.nint Best_Model_Year_;
    KEL.typ.nstr Best_Major_Color_;
    KEL.typ.nstr Best_Minor_Color_;
    KEL.typ.nstr Branded_Title_Flag_;
    KEL.typ.nstr Brand_Code1_;
    KEL.typ.nkdate Brand_Date1_;
    KEL.typ.nstr Brand_State1_;
    KEL.typ.nstr Brand_Code2_;
    KEL.typ.nkdate Brand_Date2_;
    KEL.typ.nstr Brand_Sate2_;
    KEL.typ.nstr Brand_Code3_;
    KEL.typ.nkdate Brand_Date3_;
    KEL.typ.nstr Brand_Sate3_;
    KEL.typ.nstr Brand_Code4_;
    KEL.typ.nkdate Brand_Date4_;
    KEL.typ.nstr Brand_Sate4_;
    KEL.typ.nstr Brand_Code5_;
    KEL.typ.nkdate Brand_Date5_;
    KEL.typ.nstr Brand_Sate5_;
    KEL.typ.nstr Safety_Type_;
    KEL.typ.nstr Airbag_Driver_;
    KEL.typ.nstr Airbag_Front_Driver_Side_;
    KEL.typ.nstr Airbag_Front_Head_Curtain_;
    KEL.typ.nstr Airbag_Front_Passanger_;
    KEL.typ.nstr Airbag_Front_Passanger_Side_;
    KEL.typ.nstr Airbags_;
    KEL.typ.nstr Tod_Flag_;
    KEL.typ.nstr Model_Class_Code_;
    KEL.typ.nstr Model_Class_;
    KEL.typ.nstr Min_Door_Count_;
    KEL.typ.nstr Latest_Vehicle_Flag_;
    KEL.typ.nstr Latest_Vehicle_Iteration_Flag_;
    KEL.typ.nkdate Date_Vendor_First_Reported_;
    KEL.typ.nkdate Date_Vendor_Last_Reported_;
    KEL.typ.nstr Standard_Lienholder_Name_;
    KEL.typ.nkdate Source_First_Date_;
    KEL.typ.nkdate Source_Last_Date_;
    KEL.typ.ndataset(E_Vehicle(__cfg).Data_Sources_Layout) Data_Sources__1_;
    KEL.typ.nbool Flag_Auto_;
    KEL.typ.nbool Flag_Other_;
    KEL.typ.str Flag_Vina_Make_Desc_ := '';
    KEL.typ.nstr Vehicle_Type_;
    KEL.typ.nstr Vina_Body_Style_Vehicle_Type_;
    KEL.typ.nstr Vina_Model_Date_;
    KEL.typ.ntyp(E_Person().Typ) U_I_D__1_;
    KEL.typ.epoch Date_First_Seen_ := 0;
    KEL.typ.epoch Date_Last_Seen_ := 0;
    KEL.typ.int __RecordCount := 0;
    UNSIGNED4 __Part := 0;
  END;
  SHARED __ST40599_Layout __ND53340__Project(__ST44865_Layout __PP53336) := TRANSFORM
    SELF.Data_Sources_ := __PP53336.Data_Sources__1_;
    SELF.Data_Sources__1_ := __PP53336.Data_Sources_;
    SELF.U_I_D__1_ := __PP53336.Subject_;
    SELF := __PP53336;
  END;
  SHARED __EE53931 := PROJECT(__EE53335,__ND53340__Project(LEFT));
  SHARED __ST41096_Layout := RECORD
    KEL.typ.int C_O_U_N_T___Vehicle_ := 0;
    KEL.typ.ntyp(E_Person().Typ) U_I_D__1_;
    KEL.typ.nstr Vina_Make_Description_;
    KEL.typ.epoch Date_First_Seen_ := 0;
    KEL.typ.epoch Date_Last_Seen_ := 0;
    KEL.typ.int __RecordCount := 0;
    UNSIGNED4 __Part := 0;
  END;
  SHARED __EE53948 := PROJECT(__CLEANANDDO(__EE53931,TABLE(__EE53931,{KEL.typ.int __RecordCount := SUM(GROUP,__RecordCount),KEL.typ.epoch Date_First_Seen_ := KEL.era.SimpleRoll(GROUP,Date_First_Seen_,MIN,FALSE),KEL.typ.epoch Date_Last_Seen_ := KEL.era.SimpleRoll(GROUP,Date_Last_Seen_,MAX,FALSE),KEL.typ.int C_O_U_N_T___Vehicle_ := COUNT(GROUP),U_I_D__1_,Vina_Make_Description_,__Part},U_I_D__1_,Vina_Make_Description_,__Part,MERGE)),__ST41096_Layout);
  SHARED __EE47342 := __EE47080;
  SHARED __EE47386 := __EE47342;
  __JC53954(__ST41096_Layout __EE53948, B_Person_4(__cfg).__ST30906_Layout __EE47386) := __EEQP(__EE47386.UID,__EE53948.U_I_D__1_) AND __EE53948.__Part = __EE47386.__Part;
  SHARED __EE53959 := JOIN(__EE53948,__EE47386,__JC53954(LEFT,RIGHT),TRANSFORM(__ST41096_Layout,SELF:=LEFT),HASH,KEEP(1));
  SHARED __ST43643_Layout := RECORD
    KEL.typ.ntyp(E_Person().Typ) ____grp___U_I_D_;
    KEL.typ.nstr Vina_Make_Description_;
    KEL.typ.int Vina_Make_Count_ := 0;
    KEL.typ.epoch Date_First_Seen_ := 0;
    KEL.typ.epoch Date_Last_Seen_ := 0;
    KEL.typ.int __RecordCount := 0;
    UNSIGNED4 __Part := 0;
  END;
  SHARED __ST43643_Layout __ND53964__Project(__ST41096_Layout __PP53960) := TRANSFORM
    SELF.____grp___U_I_D_ := __PP53960.U_I_D__1_;
    SELF.Vina_Make_Count_ := __PP53960.C_O_U_N_T___Vehicle_;
    SELF := __PP53960;
  END;
  SHARED __EE53977 := PROJECT(__EE53959,__ND53964__Project(LEFT));
  SHARED __EE53986 := GROUP(__EE53977,____grp___U_I_D_,__Part,ALL);
  SHARED __EE53996 := TOPN(__EE53986,1, -(__EE53986.Vina_Make_Count_),__T(____grp___U_I_D_),__T(Vina_Make_Description_));
  __JC54002(__ST43643_Layout __EE53996, B_Person_4(__cfg).__ST30906_Layout __EE47342) := __EEQP(__EE47342.UID,__EE53996.____grp___U_I_D_) AND __EE53996.__Part = __EE47342.__Part;
  SHARED __EE54007 := JOIN(__EE53996,__EE47342,__JC54002(LEFT,RIGHT),TRANSFORM(__ST43643_Layout,SELF:=LEFT),HASH,KEEP(1));
  SHARED __ST43302_Layout := RECORD
    KEL.typ.nuid UID;
    KEL.typ.nstr Vina_Make_Description_;
    KEL.typ.int Vina_Make_Count_ := 0;
    KEL.typ.epoch Date_First_Seen_ := 0;
    KEL.typ.epoch Date_Last_Seen_ := 0;
    UNSIGNED4 __Part := 0;
  END;
  SHARED __EE54025 := PROJECT(__EE54007,TRANSFORM(__ST43302_Layout,SELF.UID := LEFT.____grp___U_I_D_,SELF := LEFT));
  SHARED __ST43322_Layout := RECORD
    KEL.typ.nuid UID;
    KEL.typ.nstr Vina_Make_Description_;
    KEL.typ.epoch Date_First_Seen_ := 0;
    KEL.typ.epoch Date_Last_Seen_ := 0;
    UNSIGNED4 __Part := 0;
  END;
  SHARED __EE54039 := PROJECT(__EE54025,__ST43322_Layout);
  SHARED __ST43351_Layout := RECORD
    KEL.typ.nuid UID;
    KEL.typ.nstr O_N_L_Y___Vina_Make_Description_;
    KEL.typ.epoch Date_First_Seen_ := 0;
    KEL.typ.epoch Date_Last_Seen_ := 0;
    UNSIGNED4 __Part := 0;
  END;
  SHARED __EE54053 := PROJECT(__EE54039,TRANSFORM(__ST43351_Layout,SELF.O_N_L_Y___Vina_Make_Description_ := LEFT.Vina_Make_Description_,SELF := LEFT));
  SHARED __ST45780_Layout := RECORD
    KEL.typ.nuid UID;
    KEL.typ.nstr Gender_;
    KEL.typ.nstr Lex_I_D_Segment_;
    KEL.typ.ndataset(E_Person(__cfg).Full_Name_Layout) Full_Name_;
    KEL.typ.ndataset(E_Person(__cfg).Reported_Dates_Of_Birth_Layout) Reported_Dates_Of_Birth_;
    KEL.typ.ndataset(E_Person(__cfg).Reported_Dates_Of_Death_Layout) Reported_Dates_Of_Death_;
    KEL.typ.nstr Race_;
    KEL.typ.nstr Race_Description_;
    KEL.typ.ndataset(E_Person(__cfg).Data_Sources_Layout) Data_Sources_;
    KEL.typ.ndataset(E_Person(__cfg).Dunn_Data_Layout) Dunn_Data_;
    KEL.typ.ndataset(B_Person_4(__cfg).__ST4438_Layout) Ast_Veh_Auto_Emrg_Price_Set_;
    KEL.typ.bool Invalid_Vehicle_Auto_Min_Date_ := FALSE;
    KEL.typ.int P_L___Ast_Veh_Auto_Cnt_Ev_ := 0;
    KEL.typ.nstr P_L___Ast_Veh_Auto_Emrg_New_Dt_Ev_;
    KEL.typ.str P___Lex_I_D_Seen_Flag_ := '';
    KEL.typ.nuid U_I_D__1_;
    KEL.typ.nstr O_N_L_Y___Vina_Make_Description_;
    KEL.typ.epoch Date_First_Seen_ := 0;
    KEL.typ.epoch Date_Last_Seen_ := 0;
    KEL.typ.int __RecordCount := 0;
    UNSIGNED4 __Part := 0;
  END;
  __JC54059(B_Person_4(__cfg).__ST30906_Layout __EE47080, __ST43351_Layout __EE54053) := __EEQP(__EE47080.UID,__EE54053.UID) AND __EE47080.__Part = __EE54053.__Part;
  __ST45780_Layout __JT54059(B_Person_4(__cfg).__ST30906_Layout __l, __ST43351_Layout __r) := TRANSFORM
    SELF.U_I_D__1_ := __r.UID;
    SELF := __l;
    SELF := __r;
  END;
  SHARED __EE54109 := JOIN(__EE47080,__EE54053,__JC54059(LEFT,RIGHT),__JT54059(LEFT,RIGHT),LEFT OUTER,SMART,KEEP(1));
  SHARED __EE47142 := __EE47136(__T(__EE47136.Flag_Other_));
  __JC50976(B_Person_Vehicle_5(__cfg).__ST10168_Layout __EE50958, B_Vehicle_4(__cfg).__ST9866_Layout __EE47142) := __EEQP(__EE50958.Automobile_,__EE47142.UID) AND __EE50958.__Part = __EE47142.__Part;
  SHARED __EE50977 := JOIN(__EE50958,__EE47142,__JC50976(LEFT,RIGHT),TRANSFORM(B_Person_Vehicle_5(__cfg).__ST10168_Layout,SELF:=LEFT),HASH,KEEP(1));
  SHARED __ST41793_Layout := RECORD
    KEL.typ.ntyp(E_Person().Typ) UID;
    KEL.typ.nstr Vehicle_Min_Date_;
    KEL.typ.nint Age_At_First_Seen_;
    KEL.typ.nfloat Age_Year_At_First_Seen_;
    KEL.typ.ntyp(E_Vehicle().Typ) Automobile_;
    KEL.typ.ndataset(E_Person_Vehicle(__cfg).Counts_Model_Layout) Counts_Model_;
    KEL.typ.nkdate Current_Date_;
    KEL.typ.ndataset(E_Person_Vehicle(__cfg).Data_Sources_Layout) Data_Sources_;
    KEL.typ.nkdate Date_First_Seen_Capped_;
    KEL.typ.nint Depreciated_Price_;
    KEL.typ.nbool Flag_Depreciated_Price_;
    KEL.typ.ndataset(E_Person_Vehicle(__cfg).Registration_Layout) Registration_;
    KEL.typ.ntyp(E_Person().Typ) Subject_;
    KEL.typ.ndataset(E_Person_Vehicle(__cfg).Title_Layout) Title_;
    KEL.typ.epoch Date_First_Seen_ := 0;
    KEL.typ.epoch Date_Last_Seen_ := 0;
    UNSIGNED4 __Part := 0;
  END;
  SHARED __EE51158 := PROJECT(__EE50977,TRANSFORM(__ST41793_Layout,SELF.UID := LEFT.Subject_,SELF := LEFT));
  SHARED __ST41909_Layout := RECORD
    KEL.typ.ntyp(E_Person().Typ) UID;
    KEL.typ.nbool Exp1_;
    KEL.typ.epoch Date_First_Seen_ := 0;
    KEL.typ.epoch Date_Last_Seen_ := 0;
    UNSIGNED4 __Part := 0;
  END;
  SHARED __ST41909_Layout __ND54114__Project(__ST41793_Layout __PP51159) := TRANSFORM
    __CC1081 := '-99997';
    SELF.Exp1_ := __NOT(__OP2(__PP51159.Vehicle_Min_Date_,=,__CN(__CC1081)));
    SELF := __PP51159;
  END;
  SHARED __EE54118 := PROJECT(__EE51158,__ND54114__Project(LEFT));
  SHARED __ST41925_Layout := RECORD
    KEL.typ.int C_O_U_N_T___Person_Vehicle_ := 0;
    KEL.typ.int C_O_U_N_T___Person_Vehicle__1_ := 0;
    KEL.typ.ntyp(E_Person().Typ) UID;
    KEL.typ.epoch Date_First_Seen_ := 0;
    KEL.typ.epoch Date_Last_Seen_ := 0;
    UNSIGNED4 __Part := 0;
  END;
  SHARED __EE54137 := PROJECT(__CLEANANDDO(__EE54118,TABLE(__EE54118,{KEL.typ.epoch Date_First_Seen_ := KEL.era.SimpleRoll(GROUP,Date_First_Seen_,MIN,FALSE),KEL.typ.epoch Date_Last_Seen_ := KEL.era.SimpleRoll(GROUP,Date_Last_Seen_,MAX,FALSE),KEL.typ.int C_O_U_N_T___Person_Vehicle_ := COUNT(GROUP,__T(__EE54118.Exp1_)),KEL.typ.int C_O_U_N_T___Person_Vehicle__1_ := COUNT(GROUP),UID,__Part},UID,__Part,MERGE)),__ST41925_Layout);
  SHARED __ST46042_Layout := RECORD
    KEL.typ.nuid UID;
    KEL.typ.nstr Gender_;
    KEL.typ.nstr Lex_I_D_Segment_;
    KEL.typ.ndataset(E_Person(__cfg).Full_Name_Layout) Full_Name_;
    KEL.typ.ndataset(E_Person(__cfg).Reported_Dates_Of_Birth_Layout) Reported_Dates_Of_Birth_;
    KEL.typ.ndataset(E_Person(__cfg).Reported_Dates_Of_Death_Layout) Reported_Dates_Of_Death_;
    KEL.typ.nstr Race_;
    KEL.typ.nstr Race_Description_;
    KEL.typ.ndataset(E_Person(__cfg).Data_Sources_Layout) Data_Sources_;
    KEL.typ.ndataset(E_Person(__cfg).Dunn_Data_Layout) Dunn_Data_;
    KEL.typ.ndataset(B_Person_4(__cfg).__ST4438_Layout) Ast_Veh_Auto_Emrg_Price_Set_;
    KEL.typ.bool Invalid_Vehicle_Auto_Min_Date_ := FALSE;
    KEL.typ.int P_L___Ast_Veh_Auto_Cnt_Ev_ := 0;
    KEL.typ.nstr P_L___Ast_Veh_Auto_Emrg_New_Dt_Ev_;
    KEL.typ.str P___Lex_I_D_Seen_Flag_ := '';
    KEL.typ.nuid U_I_D__1_;
    KEL.typ.nstr O_N_L_Y___Vina_Make_Description_;
    KEL.typ.int C_O_U_N_T___Person_Vehicle_ := 0;
    KEL.typ.int C_O_U_N_T___Person_Vehicle__1_ := 0;
    KEL.typ.ntyp(E_Person().Typ) U_I_D__2_;
    KEL.typ.epoch Date_First_Seen_ := 0;
    KEL.typ.epoch Date_Last_Seen_ := 0;
    KEL.typ.int __RecordCount := 0;
    UNSIGNED4 __Part := 0;
  END;
  __JC54145(__ST45780_Layout __EE54109, __ST41925_Layout __EE54137) := __EEQP(__EE54109.UID,__EE54137.UID) AND __EE54109.__Part = __EE54137.__Part;
  __ST46042_Layout __JT54145(__ST45780_Layout __l, __ST41925_Layout __r) := TRANSFORM
    SELF.U_I_D__2_ := __r.UID;
    SELF := __l;
    SELF := __r;
  END;
  SHARED __EE54198 := JOIN(__EE54109,__EE54137,__JC54145(LEFT,RIGHT),__JT54145(LEFT,RIGHT),LEFT OUTER,HASH);
  EXPORT __ST12617_Layout := RECORD
    KEL.typ.nuid UID;
    KEL.typ.nstr Gender_;
    KEL.typ.nstr Lex_I_D_Segment_;
    KEL.typ.ndataset(E_Person(__cfg).Full_Name_Layout) Full_Name_;
    KEL.typ.ndataset(E_Person(__cfg).Reported_Dates_Of_Birth_Layout) Reported_Dates_Of_Birth_;
    KEL.typ.ndataset(E_Person(__cfg).Reported_Dates_Of_Death_Layout) Reported_Dates_Of_Death_;
    KEL.typ.nstr Race_;
    KEL.typ.nstr Race_Description_;
    KEL.typ.ndataset(E_Person(__cfg).Data_Sources_Layout) Data_Sources_;
    KEL.typ.ndataset(E_Person(__cfg).Dunn_Data_Layout) Dunn_Data_;
    KEL.typ.ndataset(B_Person_4(__cfg).__ST4438_Layout) Ast_Veh_Auto_Emrg_Price_Set_;
    KEL.typ.bool Invalid_Vehicle_Auto_Min_Date_ := FALSE;
    KEL.typ.bool Invalid_Vehicle_Other_Min_Date_ := FALSE;
    KEL.typ.nstr Most_Frequent_Vina_Make_;
    KEL.typ.int P_L___Ast_Veh_Auto_Cnt_Ev_ := 0;
    KEL.typ.nstr P_L___Ast_Veh_Auto_Emrg_New_Dt_Ev_;
    KEL.typ.nstr P_L___Ast_Veh_Auto_Emrg_Price1_Vin_;
    KEL.typ.int P_L___Ast_Veh_Other_Cnt_Ev_ := 0;
    KEL.typ.str P___Lex_I_D_Seen_Flag_ := '';
    KEL.typ.epoch Date_First_Seen_ := 0;
    KEL.typ.epoch Date_Last_Seen_ := 0;
    KEL.typ.int __RecordCount := 0;
    UNSIGNED4 __Part := 0;
  END;
  SHARED __ST12617_Layout __ND54203__Project(__ST46042_Layout __PP54199) := TRANSFORM
    SELF.Invalid_Vehicle_Other_Min_Date_ := NOT (__PP54199.C_O_U_N_T___Person_Vehicle_ <> 0);
    SELF.Most_Frequent_Vina_Make_ := __PP54199.O_N_L_Y___Vina_Make_Description_;
    __EE54287 := __PP54199.Ast_Veh_Auto_Emrg_Price_Set_;
    SELF.P_L___Ast_Veh_Auto_Emrg_Price1_Vin_ := (__T(__EE54287))[1].Vina_Vin_;
    __CC1054 := -99999;
    SELF.P_L___Ast_Veh_Other_Cnt_Ev_ := IF(__PP54199.P___Lex_I_D_Seen_Flag_ = '0',__CC1054,KEL.Routines.BoundsFold(__PP54199.C_O_U_N_T___Person_Vehicle__1_,0,99));
    SELF := __PP54199;
  END;
  EXPORT __ENH_Person_3 := PROJECT(__EE54198,__ND54203__Project(LEFT));
END;
