export layout_WV := 

record
string3	STATEABREV;
string22	REG_NUM;
string23	HULL_ID;
string15	PROP;
string15	VEH_TYPE;
string10	FUEL;
string10	HULL;
string15	USE_1;
string25	MAKE;
string5	TOTAL_INCH;
string8	REG_DATE;
string4	YEAR;
string100	NAME;
string50	FIRST_NAME;
string15	MID;
string50	LAST_NAME;
string75	ADDRESS_1;
string30	CITY;
string2	STATE;
string10	ZIP;
string50	COUNTY;
string5	FIPS;
string1	Class;
string2	Title_type;
string3	Plate_Class;
string10	Title_Num;
string1	Active;
string1	Category;
string1	Name_Code;
string20	Old_Title;
string2	Old_State;
string2	Num_Liens;
string2	Dealer_T;
string5	Dealer_Num;
string8	Title_Date;
string1	Status;
string8	Reg_Expire;
string10	Prev_Reg;
string9	SSN;
string1	WIP;
string1	OD_Code;
string1	Fire_Flood;
string1	Dup_Title;
string8	Upd_Oper;
string3	Weight;
string6	Plate_Wgt;
string6	Odometer;
string4	Model;
string2	lf;
end;

