//HPCC Systems KEL Compiler Version 0.11.6-2
IMPORT KEL011 AS KEL;
IMPORT B_Customer_1,B_Customer_4,B_Event_1,B_Internet_Protocol_1,E_Address,E_Bank,E_Bank_Account,E_Customer,E_Drivers_License,E_Email,E_Event,E_Internet_Protocol,E_Internet_Protocol_Event,E_Person,E_Person_Ip_Address,E_Phone,E_Social_Security_Number FROM FraudgovKEL;
IMPORT * FROM KEL011.Null;
EXPORT B_Internet_Protocol := MODULE
  SHARED VIRTUAL TYPEOF(B_Customer_1.__ENH_Customer_1) __ENH_Customer_1 := B_Customer_1.__ENH_Customer_1;
  SHARED VIRTUAL TYPEOF(B_Event_1.__ENH_Event_1) __ENH_Event_1 := B_Event_1.__ENH_Event_1;
  SHARED VIRTUAL TYPEOF(B_Internet_Protocol_1.__ENH_Internet_Protocol_1) __ENH_Internet_Protocol_1 := B_Internet_Protocol_1.__ENH_Internet_Protocol_1;
  SHARED VIRTUAL TYPEOF(E_Internet_Protocol_Event.__Result) __E_Internet_Protocol_Event := E_Internet_Protocol_Event.__Result;
  SHARED VIRTUAL TYPEOF(E_Person_Ip_Address.__Result) __E_Person_Ip_Address := E_Person_Ip_Address.__Result;
  SHARED __EE832674 := __ENH_Internet_Protocol_1;
  SHARED __EE885286 := __E_Person_Ip_Address;
  SHARED __EE885293 := __EE885286(__NN(__EE885286.Ip_));
  SHARED __ST875821_Layout := RECORD
    KEL.typ.ntyp(E_Internet_Protocol.Typ) UID;
    KEL.typ.ntyp(E_Person.Typ) Subject_;
    KEL.typ.epoch Date_First_Seen_ := 0;
    KEL.typ.epoch Date_Last_Seen_ := 0;
  END;
  SHARED __EE885307 := PROJECT(TABLE(PROJECT(__EE885293,TRANSFORM(__ST875821_Layout,SELF.UID := LEFT.Ip_,SELF := LEFT)),{KEL.typ.epoch Date_First_Seen_ := KEL.era.SimpleRoll(GROUP,Date_First_Seen_,MIN,TRUE),KEL.typ.epoch Date_Last_Seen_ := KEL.era.SimpleRoll(GROUP,Date_Last_Seen_,MAX,FALSE),UID,Subject_},UID,Subject_,MERGE),__ST875821_Layout);
  SHARED __ST875839_Layout := RECORD
    KEL.typ.int C_O_U_N_T___Person_Ip_Address_ := 0;
    KEL.typ.ntyp(E_Internet_Protocol.Typ) UID;
    KEL.typ.epoch Date_First_Seen_ := 0;
    KEL.typ.epoch Date_Last_Seen_ := 0;
  END;
  SHARED __EE885273 := PROJECT(__CLEANANDDO(__EE885307,TABLE(__EE885307,{KEL.typ.int C_O_U_N_T___Person_Ip_Address_ := COUNT(GROUP),UID},UID,MERGE)),__ST875839_Layout);
  SHARED __ST878325_Layout := RECORD
    KEL.typ.nuid UID;
    KEL.typ.ntyp(E_Customer.Typ) _r_Customer_;
    KEL.typ.ndataset(E_Internet_Protocol.Source_Customers_Layout) Source_Customers_;
    KEL.typ.nstr Ip_Address_;
    KEL.typ.nstr Otto_Ip_Address_Id_;
    KEL.typ.nstr _host_;
    KEL.typ.nstr _alias_;
    KEL.typ.nstr _location_;
    KEL.typ.nstr _ip__address_;
    KEL.typ.nstr _ip__address__date_;
    KEL.typ.nstr _version_;
    KEL.typ.nstr _class_;
    KEL.typ.nstr _subnet__mask_;
    KEL.typ.nstr _reserved_;
    KEL.typ.nstr _isp_;
    KEL.typ.nint _v2__validationipproblems_;
    KEL.typ.nstr _v2__ipstate_;
    KEL.typ.nstr _v2__ipcountry_;
    KEL.typ.nstr _v2__ipcontinent_;
    KEL.typ.nstr _iprngbeg_;
    KEL.typ.nstr _iprngend_;
    KEL.typ.nstr _edgecountry_;
    KEL.typ.nstr _edgeregion_;
    KEL.typ.nstr _edgecity_;
    KEL.typ.nstr _edgeconnspeed_;
    KEL.typ.nstr _edgemetrocode_;
    KEL.typ.nstr _edgelatitude_;
    KEL.typ.nstr _edgelongitude_;
    KEL.typ.nstr _edgepostalcode_;
    KEL.typ.nstr _edgecountrycode_;
    KEL.typ.nstr _edgeregioncode_;
    KEL.typ.nstr _edgecitycode_;
    KEL.typ.nstr _edgecontinentcode_;
    KEL.typ.nstr _edgetwolettercountry_;
    KEL.typ.nstr _edgeinternalcode_;
    KEL.typ.nstr _edgeareacodes_;
    KEL.typ.nstr _edgecountryconf_;
    KEL.typ.nstr _edgeregionconf_;
    KEL.typ.nstr _edgecitycong_;
    KEL.typ.nstr _edgepostalconf_;
    KEL.typ.nstr _edgegmtoffset_;
    KEL.typ.nstr _edgeindst_;
    KEL.typ.nstr _siccode_;
    KEL.typ.nstr _domainname_;
    KEL.typ.nstr _ispname_;
    KEL.typ.nstr _homebiztype_;
    KEL.typ.nstr _asn_;
    KEL.typ.nstr _asnname_;
    KEL.typ.nstr _primarylang_;
    KEL.typ.nstr _secondarylang_;
    KEL.typ.nstr _proxytype_;
    KEL.typ.nstr _proxydescription_;
    KEL.typ.nstr _isanisp_;
    KEL.typ.nstr _companyname_;
    KEL.typ.nstr _ranks_;
    KEL.typ.nstr _households_;
    KEL.typ.nstr _women_;
    KEL.typ.nstr _women18to34_;
    KEL.typ.nstr _women35to49_;
    KEL.typ.nstr _men_;
    KEL.typ.nstr _men18to34_;
    KEL.typ.nstr _men35to49_;
    KEL.typ.nstr _teens_;
    KEL.typ.nstr _kids_;
    KEL.typ.nstr _naicscode_;
    KEL.typ.nstr _cbsacode_;
    KEL.typ.nstr _cbsatitle_;
    KEL.typ.nstr _cbsatype_;
    KEL.typ.nstr _csacode_;
    KEL.typ.nstr _csatitle_;
    KEL.typ.nstr _mdcode_;
    KEL.typ.nstr _mdtitle_;
    KEL.typ.nstr _organizationname_;
    KEL.typ.nstr Entity_Context_Uid_;
    KEL.typ.int Kr_Event_After_Last_Known_Risk_Count_ := 0;
    KEL.typ.int Kr_Event_After_Last_Known_Risk_Flag_ := 0;
    KEL.typ.int Kr_Flag_ := 0;
    KEL.typ.nkdate Kr_Last_Event_Date_;
    KEL.typ.nstr Label_;
    KEL.typ.nint Last_Record_Id_;
    KEL.typ.int Vl_Event30_All_Day_Count_ := 0;
    KEL.typ.int Vl_Event30_Count_ := 0;
    KEL.typ.int Vl_Event365_Count_ := 0;
    KEL.typ.int Vl_Event7_All_Count_ := 0;
    KEL.typ.int Vl_Event7_Count_ := 0;
    KEL.typ.int C_O_U_N_T___Person_Ip_Address_ := 0;
    KEL.typ.ntyp(E_Internet_Protocol.Typ) U_I_D__1_;
    KEL.typ.epoch Date_First_Seen_ := 0;
    KEL.typ.epoch Date_Last_Seen_ := 0;
    KEL.typ.int __RecordCount := 0;
  END;
  __JC885316(B_Internet_Protocol_1.__ST36310_Layout __EE832674, __ST875839_Layout __EE885273) := __EEQP(__EE832674.UID,__EE885273.UID);
  __ST878325_Layout __JT885316(B_Internet_Protocol_1.__ST36310_Layout __l, __ST875839_Layout __r) := TRANSFORM
    SELF.U_I_D__1_ := __r.UID;
    SELF := __l;
    SELF := __r;
  END;
  SHARED __EE885317 := JOIN(__EE832674,__EE885273,__JC885316(LEFT,RIGHT),__JT885316(LEFT,RIGHT),LEFT OUTER,HASH);
  SHARED __EE885251 := __E_Internet_Protocol_Event;
  SHARED __EE885258 := __EE885251(__NN(__EE885251.Ip_));
  SHARED __ST875350_Layout := RECORD
    KEL.typ.int C_O_U_N_T___Internet_Protocol_Event_ := 0;
    KEL.typ.ntyp(E_Internet_Protocol.Typ) UID;
    KEL.typ.epoch Date_First_Seen_ := 0;
    KEL.typ.epoch Date_Last_Seen_ := 0;
  END;
  SHARED __EE885249 := PROJECT(__CLEANANDDO(__EE885258,TABLE(__EE885258,{KEL.typ.int C_O_U_N_T___Internet_Protocol_Event_ := COUNT(GROUP),KEL.typ.ntyp(E_Internet_Protocol.Typ) UID := __EE885258.Ip_},Ip_,MERGE)),__ST875350_Layout);
  SHARED __ST878924_Layout := RECORD
    KEL.typ.nuid UID;
    KEL.typ.ntyp(E_Customer.Typ) _r_Customer_;
    KEL.typ.ndataset(E_Internet_Protocol.Source_Customers_Layout) Source_Customers_;
    KEL.typ.nstr Ip_Address_;
    KEL.typ.nstr Otto_Ip_Address_Id_;
    KEL.typ.nstr _host_;
    KEL.typ.nstr _alias_;
    KEL.typ.nstr _location_;
    KEL.typ.nstr _ip__address_;
    KEL.typ.nstr _ip__address__date_;
    KEL.typ.nstr _version_;
    KEL.typ.nstr _class_;
    KEL.typ.nstr _subnet__mask_;
    KEL.typ.nstr _reserved_;
    KEL.typ.nstr _isp_;
    KEL.typ.nint _v2__validationipproblems_;
    KEL.typ.nstr _v2__ipstate_;
    KEL.typ.nstr _v2__ipcountry_;
    KEL.typ.nstr _v2__ipcontinent_;
    KEL.typ.nstr _iprngbeg_;
    KEL.typ.nstr _iprngend_;
    KEL.typ.nstr _edgecountry_;
    KEL.typ.nstr _edgeregion_;
    KEL.typ.nstr _edgecity_;
    KEL.typ.nstr _edgeconnspeed_;
    KEL.typ.nstr _edgemetrocode_;
    KEL.typ.nstr _edgelatitude_;
    KEL.typ.nstr _edgelongitude_;
    KEL.typ.nstr _edgepostalcode_;
    KEL.typ.nstr _edgecountrycode_;
    KEL.typ.nstr _edgeregioncode_;
    KEL.typ.nstr _edgecitycode_;
    KEL.typ.nstr _edgecontinentcode_;
    KEL.typ.nstr _edgetwolettercountry_;
    KEL.typ.nstr _edgeinternalcode_;
    KEL.typ.nstr _edgeareacodes_;
    KEL.typ.nstr _edgecountryconf_;
    KEL.typ.nstr _edgeregionconf_;
    KEL.typ.nstr _edgecitycong_;
    KEL.typ.nstr _edgepostalconf_;
    KEL.typ.nstr _edgegmtoffset_;
    KEL.typ.nstr _edgeindst_;
    KEL.typ.nstr _siccode_;
    KEL.typ.nstr _domainname_;
    KEL.typ.nstr _ispname_;
    KEL.typ.nstr _homebiztype_;
    KEL.typ.nstr _asn_;
    KEL.typ.nstr _asnname_;
    KEL.typ.nstr _primarylang_;
    KEL.typ.nstr _secondarylang_;
    KEL.typ.nstr _proxytype_;
    KEL.typ.nstr _proxydescription_;
    KEL.typ.nstr _isanisp_;
    KEL.typ.nstr _companyname_;
    KEL.typ.nstr _ranks_;
    KEL.typ.nstr _households_;
    KEL.typ.nstr _women_;
    KEL.typ.nstr _women18to34_;
    KEL.typ.nstr _women35to49_;
    KEL.typ.nstr _men_;
    KEL.typ.nstr _men18to34_;
    KEL.typ.nstr _men35to49_;
    KEL.typ.nstr _teens_;
    KEL.typ.nstr _kids_;
    KEL.typ.nstr _naicscode_;
    KEL.typ.nstr _cbsacode_;
    KEL.typ.nstr _cbsatitle_;
    KEL.typ.nstr _cbsatype_;
    KEL.typ.nstr _csacode_;
    KEL.typ.nstr _csatitle_;
    KEL.typ.nstr _mdcode_;
    KEL.typ.nstr _mdtitle_;
    KEL.typ.nstr _organizationname_;
    KEL.typ.nstr Entity_Context_Uid_;
    KEL.typ.int Kr_Event_After_Last_Known_Risk_Count_ := 0;
    KEL.typ.int Kr_Event_After_Last_Known_Risk_Flag_ := 0;
    KEL.typ.int Kr_Flag_ := 0;
    KEL.typ.nkdate Kr_Last_Event_Date_;
    KEL.typ.nstr Label_;
    KEL.typ.nint Last_Record_Id_;
    KEL.typ.int Vl_Event30_All_Day_Count_ := 0;
    KEL.typ.int Vl_Event30_Count_ := 0;
    KEL.typ.int Vl_Event365_Count_ := 0;
    KEL.typ.int Vl_Event7_All_Count_ := 0;
    KEL.typ.int Vl_Event7_Count_ := 0;
    KEL.typ.int C_O_U_N_T___Person_Ip_Address_ := 0;
    KEL.typ.ntyp(E_Internet_Protocol.Typ) U_I_D__1_;
    KEL.typ.int C_O_U_N_T___Internet_Protocol_Event_ := 0;
    KEL.typ.ntyp(E_Internet_Protocol.Typ) U_I_D__2_;
    KEL.typ.epoch Date_First_Seen_ := 0;
    KEL.typ.epoch Date_Last_Seen_ := 0;
    KEL.typ.int __RecordCount := 0;
  END;
  __JC885326(__ST878325_Layout __EE885317, __ST875350_Layout __EE885249) := __EEQP(__EE885317.UID,__EE885249.UID);
  __ST878924_Layout __JT885326(__ST878325_Layout __l, __ST875350_Layout __r) := TRANSFORM
    SELF.U_I_D__2_ := __r.UID;
    SELF := __l;
    SELF := __r;
  END;
  SHARED __EE885327 := JOIN(__EE885317,__EE885249,__JC885326(LEFT,RIGHT),__JT885326(LEFT,RIGHT),LEFT OUTER,HASH);
  SHARED __EE885277 := __ENH_Event_1;
  SHARED __EE890649 := __EE885251;
  SHARED __EE890662 := __EE890649(__NN(__EE890649.Ip_) AND __NN(__EE890649.Transaction_));
  SHARED __ST876391_Layout := RECORD
    KEL.typ.nuid UID;
    KEL.typ.ntyp(E_Customer.Typ) _r_Customer_;
    KEL.typ.ndataset(E_Event.Source_Customers_Layout) Source_Customers_;
    KEL.typ.ntyp(E_Person.Typ) Subject_;
    KEL.typ.ntyp(E_Address.Typ) Location_;
    KEL.typ.nint Record_Id_;
    KEL.typ.nkdate Event_Date_;
    KEL.typ.ndataset(E_Event.Event_Types_Layout) Event_Types_;
    KEL.typ.ntyp(E_Phone.Typ) _r_Phone_;
    KEL.typ.ntyp(E_Email.Typ) _r_Email_;
    KEL.typ.ntyp(E_Internet_Protocol.Typ) _r_Internet_Protocol_;
    KEL.typ.ntyp(E_Bank_Account.Typ) _r_Bank_Account_;
    KEL.typ.ntyp(E_Drivers_License.Typ) _r_Drivers_License_;
    KEL.typ.ntyp(E_Social_Security_Number.Typ) _r_Ssn_;
    KEL.typ.nint Lex_Id_;
    KEL.typ.nstr Otto_Address_Id_;
    KEL.typ.nkdate Date_Of_Birth_;
    KEL.typ.nkdate Deceased_Date_;
    KEL.typ.nkdate Deceased_Date_Of_Birth_;
    KEL.typ.nstr Deceased_First_;
    KEL.typ.nstr Deceased_Middle_;
    KEL.typ.nstr Deceased_Last_;
    KEL.typ.nstr Phone_Number_;
    KEL.typ.nstr Otto_Email_Id_;
    KEL.typ.nstr Otto_Ip_Address_Id_;
    KEL.typ.nstr Otto_S_S_N_Id_;
    KEL.typ.nstr Case_Id_;
    KEL.typ.nstr Otto_Drivers_License_Id_;
    KEL.typ.nstr Deceased_Match_Code_;
    KEL.typ.nbool _isdeepdive_;
    KEL.typ.nstr _county__death_;
    KEL.typ.nstr Deceased_Ssn_;
    KEL.typ.nstr _state__death__flag_;
    KEL.typ.nstr _death__rec__src_;
    KEL.typ.nstr _state__death__id_;
    KEL.typ.nstr _verfirst_;
    KEL.typ.nstr _verlast_;
    KEL.typ.nstr _veraddr_;
    KEL.typ.nstr _vercity_;
    KEL.typ.nstr _verstate_;
    KEL.typ.nstr _verzip_;
    KEL.typ.nstr _verzip4_;
    KEL.typ.nstr _verssn_;
    KEL.typ.nstr _verdob_;
    KEL.typ.nstr _verhphone_;
    KEL.typ.nstr _verify__addr_;
    KEL.typ.nstr _verify__dob_;
    KEL.typ.nstr _valid__ssn_;
    KEL.typ.nint _nas__summary_;
    KEL.typ.nint _nap__summary_;
    KEL.typ.nint _relativeaddressmatch_;
    KEL.typ.nstr _cvi_;
    KEL.typ.nstr _additional__fname__1_;
    KEL.typ.nstr _additional__lname__1_;
    KEL.typ.nstr _additional__lname__date__last__1_;
    KEL.typ.nstr _additional__fname__2_;
    KEL.typ.nstr _additional__lname__2_;
    KEL.typ.nstr _additional__lname__date__last__2_;
    KEL.typ.nstr _additional__fname__3_;
    KEL.typ.nstr _additional__lname__3_;
    KEL.typ.nstr _additional__lname__date__last__3_;
    KEL.typ.nint _subjectssncount_;
    KEL.typ.nstr _dobmatchlevel_;
    KEL.typ.nbool _ssnfoundforlexid_;
    KEL.typ.nstr _cvicustomscore_;
    KEL.typ.nint Subject_Ssn_Count_;
    KEL.typ.nint Date_Of_Birth_Match_Level_;
    KEL.typ.nint Stolen_Identity_Index_;
    KEL.typ.nint Synthetic_Identity_Index_;
    KEL.typ.nint Manipulated_Identity_Index_;
    KEL.typ.nint Vulnerable_Victim_Index_;
    KEL.typ.nint Friendlyfraud_Index_;
    KEL.typ.nint Suspicious_Activity_Index_;
    KEL.typ.nint _v2__sourcerisklevel_;
    KEL.typ.nint _v2__assocsuspicousidentitiescount_;
    KEL.typ.nint _v2__assoccreditbureauonlycount_;
    KEL.typ.nint _v2__validationaddrproblems_;
    KEL.typ.nint _v2__inputaddrageoldest_;
    KEL.typ.nstr _v2__inputaddrdwelltype_;
    KEL.typ.nstr _v2__divssnidentitycountnew_;
    KEL.typ.ndataset(E_Event.Hri_List_Layout) Hri_List_;
    KEL.typ.nstr _curr__incar__flag_;
    KEL.typ.nstr _off__cat__list_;
    KEL.typ.nint _name__ssn__dob__match_;
    KEL.typ.nstr Ip_Address_;
    KEL.typ.nstr _iprngbeg_;
    KEL.typ.nstr _iprngend_;
    KEL.typ.nstr _edgecountry_;
    KEL.typ.nstr _edgeregion_;
    KEL.typ.nstr _edgecity_;
    KEL.typ.nstr _edgeconnspeed_;
    KEL.typ.nstr _edgemetrocode_;
    KEL.typ.nstr _edgelatitude_;
    KEL.typ.nstr _edgelongitude_;
    KEL.typ.nstr _edgepostalcode_;
    KEL.typ.nstr _edgecountrycode_;
    KEL.typ.nstr _edgeregioncode_;
    KEL.typ.nstr _edgecitycode_;
    KEL.typ.nstr _edgecontinentcode_;
    KEL.typ.nstr _edgetwolettercountry_;
    KEL.typ.nstr _edgeinternalcode_;
    KEL.typ.nstr _edgeareacodes_;
    KEL.typ.nstr _edgecountryconf_;
    KEL.typ.nstr _edgeregionconf_;
    KEL.typ.nstr _edgecitycong_;
    KEL.typ.nstr _edgepostalconf_;
    KEL.typ.nstr _edgegmtoffset_;
    KEL.typ.nstr _edgeindst_;
    KEL.typ.nstr _siccode_;
    KEL.typ.nstr _domainname_;
    KEL.typ.nstr _ispname_;
    KEL.typ.nstr _homebiztype_;
    KEL.typ.nstr _asn_;
    KEL.typ.nstr _asnname_;
    KEL.typ.nstr _primarylang_;
    KEL.typ.nstr _secondarylang_;
    KEL.typ.nstr _proxytype_;
    KEL.typ.nstr _proxydescription_;
    KEL.typ.nstr _isanisp_;
    KEL.typ.nstr _companyname_;
    KEL.typ.nstr _ranks_;
    KEL.typ.nstr _households_;
    KEL.typ.nstr _women_;
    KEL.typ.nstr _women18to34_;
    KEL.typ.nstr _women35to49_;
    KEL.typ.nstr _men_;
    KEL.typ.nstr _men18to34_;
    KEL.typ.nstr _men35to49_;
    KEL.typ.nstr _teens_;
    KEL.typ.nstr _kids_;
    KEL.typ.nstr _naicscode_;
    KEL.typ.nstr _cbsacode_;
    KEL.typ.nstr _cbsatitle_;
    KEL.typ.nstr _cbsatype_;
    KEL.typ.nstr _csacode_;
    KEL.typ.nstr _csatitle_;
    KEL.typ.nstr _mdcode_;
    KEL.typ.nstr _mdtitle_;
    KEL.typ.nstr _organizationname_;
    KEL.typ.nint Confidence__that__activity__was__deceitful__id_;
    KEL.typ.nint _name__risk__code_;
    KEL.typ.nint _dob__risk__code_;
    KEL.typ.nint _ssn__risk__code_;
    KEL.typ.nint _drivers__license__risk__code_;
    KEL.typ.nint _physical__address__risk__code_;
    KEL.typ.nint _phone__risk__code_;
    KEL.typ.nint _cell__phone__risk__code_;
    KEL.typ.nint _work__phone__risk__code_;
    KEL.typ.nint _bank__account__1__risk__code_;
    KEL.typ.nint _bank__account__2__risk__code_;
    KEL.typ.nint _email__address__risk__code_;
    KEL.typ.nint _ip__address__fraud__code_;
    KEL.typ.nint _business__risk__code_;
    KEL.typ.nint _mailing__address__risk__code_;
    KEL.typ.nint _device__risk__code_;
    KEL.typ.nint _identity__risk__code_;
    KEL.typ.nstr _advo__hitflag_;
    KEL.typ.nstr _advo__vacancyindicator_;
    KEL.typ.nstr _advo__addressstyle_;
    KEL.typ.nstr _advo__dropindicator_;
    KEL.typ.nstr _advo__residentialorbusinessindicator_;
    KEL.typ.nstr _advo__addresstype_;
    KEL.typ.nstr _advo__addressusagetype_;
    KEL.typ.nstr A_C_E_Cleaner_Error_Code_;
    KEL.typ.int Address_Is_Cmra_ := 0;
    KEL.typ.int Address_Is_Po_Box_ := 0;
    KEL.typ.int Address_Is_Vacant_ := 0;
    KEL.typ.int Address_Out_Of_State_ := 0;
    KEL.typ.int Contributor_Safe_Flag_ := 0;
    KEL.typ.int Deceased_Prior_To_Event_ := 0;
    KEL.typ.nint Deceased_To_Event_Year_Diff_;
    KEL.typ.nbool Demo_Customer_;
    KEL.typ.nint Event_Age_;
    KEL.typ.int Flags_Known_Risk_Element_ := 0;
    KEL.typ.int Hri03_Flag_ := 0;
    KEL.typ.int Hri06_Flag_ := 0;
    KEL.typ.int Hri07_Flag_ := 0;
    KEL.typ.int Hri08_Flag_ := 0;
    KEL.typ.int Hri11_Flag_ := 0;
    KEL.typ.int Hri12_Flag_ := 0;
    KEL.typ.int Hri14_Flag_ := 0;
    KEL.typ.int Hri15_Flag_ := 0;
    KEL.typ.int Hri19_Flag_ := 0;
    KEL.typ.int Hri25_Flag_ := 0;
    KEL.typ.int Hri26_Flag_ := 0;
    KEL.typ.int Hri27_Flag_ := 0;
    KEL.typ.int Hri28_Flag_ := 0;
    KEL.typ.int Hri29_Flag_ := 0;
    KEL.typ.int Hri30_Flag_ := 0;
    KEL.typ.int Hri31_Flag_ := 0;
    KEL.typ.int Hri37_Flag_ := 0;
    KEL.typ.int Hri38_Flag_ := 0;
    KEL.typ.int Hri41_Flag_ := 0;
    KEL.typ.int Hri48_Flag_ := 0;
    KEL.typ.int Hri50_Flag_ := 0;
    KEL.typ.int Hri51_Flag_ := 0;
    KEL.typ.int Hri52_Flag_ := 0;
    KEL.typ.int Hri71_Flag_ := 0;
    KEL.typ.int Hri83_Flag_ := 0;
    KEL.typ.int Hri90_Flag_ := 0;
    KEL.typ.int Hri_Cl_Flag_ := 0;
    KEL.typ.int Hri_Co_Flag_ := 0;
    KEL.typ.int Hri_Dd_Flag_ := 0;
    KEL.typ.int Hri_Df_Flag_ := 0;
    KEL.typ.int Hri_It_Flag_ := 0;
    KEL.typ.int Hri_Iv_Flag_ := 0;
    KEL.typ.int Hri_Mi_Flag_ := 0;
    KEL.typ.int Hri_Mo_Flag_ := 0;
    KEL.typ.int Hri_Ms_Flag_ := 0;
    KEL.typ.int Hri_Nf_Flag_ := 0;
    KEL.typ.int Hri_Pa_Flag_ := 0;
    KEL.typ.int Hri_Po_Flag_ := 0;
    KEL.typ.int Hri_Va_Flag_ := 0;
    KEL.typ.nint Id_Age_;
    KEL.typ.int Id_Nas9_Flag_ := 0;
    KEL.typ.int In_Customer_Population_ := 0;
    KEL.typ.int Invalid_Address_ := 0;
    KEL.typ.int Ip_High_Risk_City_ := 0;
    KEL.typ.int Ip_Hosted_ := 0;
    KEL.typ.int Ip_Not_Us_ := 0;
    KEL.typ.int Ip_Tor_ := 0;
    KEL.typ.int Ip_Vpn_ := 0;
    KEL.typ.int Kr_Addr300_Flag_ := 0;
    KEL.typ.int Kr_Addr301_Flag_ := 0;
    KEL.typ.int Kr_Addr302_Flag_ := 0;
    KEL.typ.int Kr_Addr303_Flag_ := 0;
    KEL.typ.int Kr_Addr390_Flag_ := 0;
    KEL.typ.int Kr_Addr391_Flag_ := 0;
    KEL.typ.int Kr_Addr392_Flag_ := 0;
    KEL.typ.int Kr_Addr393_Flag_ := 0;
    KEL.typ.int Kr_Address_Flag_ := 0;
    KEL.typ.int Kr_Bank_Flag_ := 0;
    KEL.typ.int Kr_Bnk800_Flag_ := 0;
    KEL.typ.int Kr_Bnk801_Flag_ := 0;
    KEL.typ.int Kr_Bnk802_Flag_ := 0;
    KEL.typ.int Kr_Bnk890_Flag_ := 0;
    KEL.typ.int Kr_Bnk891_Flag_ := 0;
    KEL.typ.int Kr_Bnk892_Flag_ := 0;
    KEL.typ.int Kr_Bnk893_Flag_ := 0;
    KEL.typ.int Kr_Dl200_Flag_ := 0;
    KEL.typ.int Kr_Dl201_Flag_ := 0;
    KEL.typ.int Kr_Dl202_Flag_ := 0;
    KEL.typ.int Kr_Dl203_Flag_ := 0;
    KEL.typ.int Kr_Dl204_Flag_ := 0;
    KEL.typ.int Kr_Dl290_Flag_ := 0;
    KEL.typ.int Kr_Dl291_Flag_ := 0;
    KEL.typ.int Kr_Dl292_Flag_ := 0;
    KEL.typ.int Kr_Dl293_Flag_ := 0;
    KEL.typ.int Kr_Dl_Flag_ := 0;
    KEL.typ.int Kr_Email_Flag_ := 0;
    KEL.typ.int Kr_Eml500_Flag_ := 0;
    KEL.typ.int Kr_Eml501_Flag_ := 0;
    KEL.typ.int Kr_Eml502_Flag_ := 0;
    KEL.typ.int Kr_Eml590_Flag_ := 0;
    KEL.typ.int Kr_Eml591_Flag_ := 0;
    KEL.typ.int Kr_Eml592_Flag_ := 0;
    KEL.typ.int Kr_Eml593_Flag_ := 0;
    KEL.typ.int Kr_Event_After_Known_Risk_ := 0;
    KEL.typ.int Kr_High_Risk_Address_Flag_ := 0;
    KEL.typ.int Kr_High_Risk_Bank_Flag_ := 0;
    KEL.typ.int Kr_High_Risk_Dl_Flag_ := 0;
    KEL.typ.int Kr_High_Risk_Email_Flag_ := 0;
    KEL.typ.int Kr_High_Risk_Identity_Flag_ := 0;
    KEL.typ.int Kr_High_Risk_Ip_Address_Flag_ := 0;
    KEL.typ.int Kr_High_Risk_Phone_Flag_ := 0;
    KEL.typ.int Kr_High_Risk_Ssn_Flag_ := 0;
    KEL.typ.int Kr_Id10000_Flag_ := 0;
    KEL.typ.int Kr_Id10001_Flag_ := 0;
    KEL.typ.int Kr_Id10002_Flag_ := 0;
    KEL.typ.int Kr_Id10003_Flag_ := 0;
    KEL.typ.int Kr_Id10004_Flag_ := 0;
    KEL.typ.int Kr_Id10005_Flag_ := 0;
    KEL.typ.int Kr_Id10006_Flag_ := 0;
    KEL.typ.int Kr_Id10007_Flag_ := 0;
    KEL.typ.int Kr_Id1010_Flag_ := 0;
    KEL.typ.int Kr_Id11000_Flag_ := 0;
    KEL.typ.int Kr_Id11001_Flag_ := 0;
    KEL.typ.int Kr_Id11002_Flag_ := 0;
    KEL.typ.int Kr_Id11003_Flag_ := 0;
    KEL.typ.int Kr_Id11004_Flag_ := 0;
    KEL.typ.int Kr_Id11005_Flag_ := 0;
    KEL.typ.int Kr_Id11006_Flag_ := 0;
    KEL.typ.int Kr_Id11007_Flag_ := 0;
    KEL.typ.int Kr_Id11008_Flag_ := 0;
    KEL.typ.int Kr_Id11009_Flag_ := 0;
    KEL.typ.int Kr_Id11010_Flag_ := 0;
    KEL.typ.int Kr_Id11011_Flag_ := 0;
    KEL.typ.int Kr_Id11012_Flag_ := 0;
    KEL.typ.int Kr_Id11013_Flag_ := 0;
    KEL.typ.int Kr_Id11014_Flag_ := 0;
    KEL.typ.int Kr_Id11015_Flag_ := 0;
    KEL.typ.int Kr_Id11016_Flag_ := 0;
    KEL.typ.int Kr_Id11017_Flag_ := 0;
    KEL.typ.int Kr_Id11018_Flag_ := 0;
    KEL.typ.int Kr_Id11019_Flag_ := 0;
    KEL.typ.int Kr_Id12000_Flag_ := 0;
    KEL.typ.int Kr_Id12001_Flag_ := 0;
    KEL.typ.int Kr_Id12002_Flag_ := 0;
    KEL.typ.int Kr_Id12003_Flag_ := 0;
    KEL.typ.int Kr_Id12004_Flag_ := 0;
    KEL.typ.int Kr_Id12006_Flag_ := 0;
    KEL.typ.int Kr_Id12007_Flag_ := 0;
    KEL.typ.int Kr_Id13000_Flag_ := 0;
    KEL.typ.int Kr_Id13001_Flag_ := 0;
    KEL.typ.int Kr_Id13002_Flag_ := 0;
    KEL.typ.int Kr_Id13003_Flag_ := 0;
    KEL.typ.int Kr_Id13005_Flag_ := 0;
    KEL.typ.int Kr_Id13006_Flag_ := 0;
    KEL.typ.int Kr_Id13007_Flag_ := 0;
    KEL.typ.int Kr_Id14000_Flag_ := 0;
    KEL.typ.int Kr_Id14001_Flag_ := 0;
    KEL.typ.int Kr_Id14900_Flag_ := 0;
    KEL.typ.int Kr_Id14901_Flag_ := 0;
    KEL.typ.int Kr_Id14902_Flag_ := 0;
    KEL.typ.int Kr_Id14903_Flag_ := 0;
    KEL.typ.int Kr_Id2025_Flag_ := 0;
    KEL.typ.int Kr_Identity_Flag_ := 0;
    KEL.typ.int Kr_Identity_Risk_ := 0;
    KEL.typ.int Kr_Ip1000_Flag_ := 0;
    KEL.typ.int Kr_Ip1001_Flag_ := 0;
    KEL.typ.int Kr_Ip1090_Flag_ := 0;
    KEL.typ.int Kr_Ip1091_Flag_ := 0;
    KEL.typ.int Kr_Ip1092_Flag_ := 0;
    KEL.typ.int Kr_Ip1093_Flag_ := 0;
    KEL.typ.int Kr_Ip600_Flag_ := 0;
    KEL.typ.int Kr_Ip601_Flag_ := 0;
    KEL.typ.int Kr_Ip602_Flag_ := 0;
    KEL.typ.int Kr_Ip603_Flag_ := 0;
    KEL.typ.int Kr_Ip604_Flag_ := 0;
    KEL.typ.int Kr_Ip605_Flag_ := 0;
    KEL.typ.int Kr_Ip690_Flag_ := 0;
    KEL.typ.int Kr_Ip691_Flag_ := 0;
    KEL.typ.int Kr_Ip692_Flag_ := 0;
    KEL.typ.int Kr_Ip693_Flag_ := 0;
    KEL.typ.int Kr_Ip_Flag_ := 0;
    KEL.typ.int Kr_Low_Risk_Address_Flag_ := 0;
    KEL.typ.int Kr_Low_Risk_Bank_Flag_ := 0;
    KEL.typ.int Kr_Low_Risk_Dl_Flag_ := 0;
    KEL.typ.int Kr_Low_Risk_Email_Flag_ := 0;
    KEL.typ.int Kr_Low_Risk_Identity_Flag_ := 0;
    KEL.typ.int Kr_Low_Risk_Ip_Address_Flag_ := 0;
    KEL.typ.int Kr_Low_Risk_Phone_Flag_ := 0;
    KEL.typ.int Kr_Low_Risk_Ssn_Flag_ := 0;
    KEL.typ.int Kr_Medium_Risk_Address_Flag_ := 0;
    KEL.typ.int Kr_Medium_Risk_Bank_Flag_ := 0;
    KEL.typ.int Kr_Medium_Risk_Dl_Flag_ := 0;
    KEL.typ.int Kr_Medium_Risk_Email_Flag_ := 0;
    KEL.typ.int Kr_Medium_Risk_Identity_Flag_ := 0;
    KEL.typ.int Kr_Medium_Risk_Ip_Address_Flag_ := 0;
    KEL.typ.int Kr_Medium_Risk_Phone_Flag_ := 0;
    KEL.typ.int Kr_Medium_Risk_Ssn_Flag_ := 0;
    KEL.typ.int Kr_Phn400_Flag_ := 0;
    KEL.typ.int Kr_Phn401_Flag_ := 0;
    KEL.typ.int Kr_Phn402_Flag_ := 0;
    KEL.typ.int Kr_Phn490_Flag_ := 0;
    KEL.typ.int Kr_Phn491_Flag_ := 0;
    KEL.typ.int Kr_Phn492_Flag_ := 0;
    KEL.typ.int Kr_Phn493_Flag_ := 0;
    KEL.typ.int Kr_Phone_Flag_ := 0;
    KEL.typ.int Kr_Ssn100_Flag_ := 0;
    KEL.typ.int Kr_Ssn101_Flag_ := 0;
    KEL.typ.int Kr_Ssn103_Flag_ := 0;
    KEL.typ.int Kr_Ssn104_Flag_ := 0;
    KEL.typ.int Kr_Ssn105_Flag_ := 0;
    KEL.typ.int Kr_Ssn190_Flag_ := 0;
    KEL.typ.int Kr_Ssn191_Flag_ := 0;
    KEL.typ.int Kr_Ssn192_Flag_ := 0;
    KEL.typ.int Kr_Ssn193_Flag_ := 0;
    KEL.typ.int Kr_Ssn_Flag_ := 0;
    KEL.typ.nfloat Latitude_;
    KEL.typ.nfloat Longitude_;
    KEL.typ.int No_Lex_Id_ := 0;
    KEL.typ.int Safe_Flag_ := 0;
    KEL.typ.ntyp(E_Customer.Typ) _r_Customer__1_;
    KEL.typ.ntyp(E_Internet_Protocol.Typ) Ip_;
    KEL.typ.nkdate Event_Date__1_;
    KEL.typ.ntyp(E_Event.Typ) Transaction_;
    KEL.typ.epoch Date_First_Seen_ := 0;
    KEL.typ.epoch Date_Last_Seen_ := 0;
    KEL.typ.int __RecordCount := 0;
  END;
  __JC890668(B_Event_1.__ST35754_Layout __EE885277, E_Internet_Protocol_Event.Layout __EE890662) := __EEQP(__EE890662.Transaction_,__EE885277.UID);
  __ST876391_Layout __JT890668(B_Event_1.__ST35754_Layout __l, E_Internet_Protocol_Event.Layout __r) := TRANSFORM
    SELF._r_Customer__1_ := __r._r_Customer_;
    SELF.Event_Date__1_ := __r.Event_Date_;
    SELF := __l;
    SELF := __r;
  END;
  SHARED __EE890669 := JOIN(__EE890662,__EE885277,__JC890668(RIGHT,LEFT),__JT890668(RIGHT,LEFT),INNER,HASH);
  SHARED __ST872650_Layout := RECORD
    KEL.typ.ntyp(E_Internet_Protocol.Typ) UID;
    KEL.typ.ntyp(E_Customer.Typ) _r_Customer_;
    KEL.typ.ntyp(E_Internet_Protocol.Typ) Ip_;
    KEL.typ.nkdate Event_Date_;
    KEL.typ.ntyp(E_Event.Typ) Transaction_;
    KEL.typ.nuid U_I_D__1_;
    KEL.typ.int Contributor_Safe_Flag_ := 0;
    KEL.typ.nstr A_C_E_Cleaner_Error_Code_;
    KEL.typ.int Address_Is_Cmra_ := 0;
    KEL.typ.int Address_Is_Po_Box_ := 0;
    KEL.typ.int Address_Is_Vacant_ := 0;
    KEL.typ.int Address_Out_Of_State_ := 0;
    KEL.typ.nstr Case_Id_;
    KEL.typ.nint Confidence__that__activity__was__deceitful__id_;
    KEL.typ.nkdate Date_Of_Birth_;
    KEL.typ.nint Date_Of_Birth_Match_Level_;
    KEL.typ.nkdate Deceased_Date_;
    KEL.typ.nkdate Deceased_Date_Of_Birth_;
    KEL.typ.nstr Deceased_First_;
    KEL.typ.nstr Deceased_Last_;
    KEL.typ.nstr Deceased_Match_Code_;
    KEL.typ.nstr Deceased_Middle_;
    KEL.typ.int Deceased_Prior_To_Event_ := 0;
    KEL.typ.nstr Deceased_Ssn_;
    KEL.typ.nint Deceased_To_Event_Year_Diff_;
    KEL.typ.nbool Demo_Customer_;
    KEL.typ.nint Event_Age_;
    KEL.typ.nkdate Event_Date__1_;
    KEL.typ.ndataset(E_Event.Event_Types_Layout) Event_Types_;
    KEL.typ.int Flags_Known_Risk_Element_ := 0;
    KEL.typ.nint Friendlyfraud_Index_;
    KEL.typ.int Hri03_Flag_ := 0;
    KEL.typ.int Hri06_Flag_ := 0;
    KEL.typ.int Hri07_Flag_ := 0;
    KEL.typ.int Hri08_Flag_ := 0;
    KEL.typ.int Hri11_Flag_ := 0;
    KEL.typ.int Hri12_Flag_ := 0;
    KEL.typ.int Hri14_Flag_ := 0;
    KEL.typ.int Hri15_Flag_ := 0;
    KEL.typ.int Hri19_Flag_ := 0;
    KEL.typ.int Hri25_Flag_ := 0;
    KEL.typ.int Hri26_Flag_ := 0;
    KEL.typ.int Hri27_Flag_ := 0;
    KEL.typ.int Hri28_Flag_ := 0;
    KEL.typ.int Hri29_Flag_ := 0;
    KEL.typ.int Hri30_Flag_ := 0;
    KEL.typ.int Hri31_Flag_ := 0;
    KEL.typ.int Hri37_Flag_ := 0;
    KEL.typ.int Hri38_Flag_ := 0;
    KEL.typ.int Hri41_Flag_ := 0;
    KEL.typ.int Hri48_Flag_ := 0;
    KEL.typ.int Hri50_Flag_ := 0;
    KEL.typ.int Hri51_Flag_ := 0;
    KEL.typ.int Hri52_Flag_ := 0;
    KEL.typ.int Hri71_Flag_ := 0;
    KEL.typ.int Hri83_Flag_ := 0;
    KEL.typ.int Hri90_Flag_ := 0;
    KEL.typ.int Hri_Cl_Flag_ := 0;
    KEL.typ.int Hri_Co_Flag_ := 0;
    KEL.typ.int Hri_Dd_Flag_ := 0;
    KEL.typ.int Hri_Df_Flag_ := 0;
    KEL.typ.int Hri_It_Flag_ := 0;
    KEL.typ.int Hri_Iv_Flag_ := 0;
    KEL.typ.ndataset(E_Event.Hri_List_Layout) Hri_List_;
    KEL.typ.int Hri_Mi_Flag_ := 0;
    KEL.typ.int Hri_Mo_Flag_ := 0;
    KEL.typ.int Hri_Ms_Flag_ := 0;
    KEL.typ.int Hri_Nf_Flag_ := 0;
    KEL.typ.int Hri_Pa_Flag_ := 0;
    KEL.typ.int Hri_Po_Flag_ := 0;
    KEL.typ.int Hri_Va_Flag_ := 0;
    KEL.typ.nint Id_Age_;
    KEL.typ.int Id_Nas9_Flag_ := 0;
    KEL.typ.int In_Customer_Population_ := 0;
    KEL.typ.int Invalid_Address_ := 0;
    KEL.typ.nstr Ip_Address_;
    KEL.typ.int Ip_High_Risk_City_ := 0;
    KEL.typ.int Ip_Hosted_ := 0;
    KEL.typ.int Ip_Not_Us_ := 0;
    KEL.typ.int Ip_Tor_ := 0;
    KEL.typ.int Ip_Vpn_ := 0;
    KEL.typ.int Kr_Addr300_Flag_ := 0;
    KEL.typ.int Kr_Addr301_Flag_ := 0;
    KEL.typ.int Kr_Addr302_Flag_ := 0;
    KEL.typ.int Kr_Addr303_Flag_ := 0;
    KEL.typ.int Kr_Addr390_Flag_ := 0;
    KEL.typ.int Kr_Addr391_Flag_ := 0;
    KEL.typ.int Kr_Addr392_Flag_ := 0;
    KEL.typ.int Kr_Addr393_Flag_ := 0;
    KEL.typ.int Kr_Address_Flag_ := 0;
    KEL.typ.int Kr_Bank_Flag_ := 0;
    KEL.typ.int Kr_Bnk800_Flag_ := 0;
    KEL.typ.int Kr_Bnk801_Flag_ := 0;
    KEL.typ.int Kr_Bnk802_Flag_ := 0;
    KEL.typ.int Kr_Bnk890_Flag_ := 0;
    KEL.typ.int Kr_Bnk891_Flag_ := 0;
    KEL.typ.int Kr_Bnk892_Flag_ := 0;
    KEL.typ.int Kr_Bnk893_Flag_ := 0;
    KEL.typ.int Kr_Dl200_Flag_ := 0;
    KEL.typ.int Kr_Dl201_Flag_ := 0;
    KEL.typ.int Kr_Dl202_Flag_ := 0;
    KEL.typ.int Kr_Dl203_Flag_ := 0;
    KEL.typ.int Kr_Dl204_Flag_ := 0;
    KEL.typ.int Kr_Dl290_Flag_ := 0;
    KEL.typ.int Kr_Dl291_Flag_ := 0;
    KEL.typ.int Kr_Dl292_Flag_ := 0;
    KEL.typ.int Kr_Dl293_Flag_ := 0;
    KEL.typ.int Kr_Dl_Flag_ := 0;
    KEL.typ.int Kr_Email_Flag_ := 0;
    KEL.typ.int Kr_Eml500_Flag_ := 0;
    KEL.typ.int Kr_Eml501_Flag_ := 0;
    KEL.typ.int Kr_Eml502_Flag_ := 0;
    KEL.typ.int Kr_Eml590_Flag_ := 0;
    KEL.typ.int Kr_Eml591_Flag_ := 0;
    KEL.typ.int Kr_Eml592_Flag_ := 0;
    KEL.typ.int Kr_Eml593_Flag_ := 0;
    KEL.typ.int Kr_Event_After_Known_Risk_ := 0;
    KEL.typ.int Kr_High_Risk_Address_Flag_ := 0;
    KEL.typ.int Kr_High_Risk_Bank_Flag_ := 0;
    KEL.typ.int Kr_High_Risk_Dl_Flag_ := 0;
    KEL.typ.int Kr_High_Risk_Email_Flag_ := 0;
    KEL.typ.int Kr_High_Risk_Identity_Flag_ := 0;
    KEL.typ.int Kr_High_Risk_Ip_Address_Flag_ := 0;
    KEL.typ.int Kr_High_Risk_Phone_Flag_ := 0;
    KEL.typ.int Kr_High_Risk_Ssn_Flag_ := 0;
    KEL.typ.int Kr_Id10000_Flag_ := 0;
    KEL.typ.int Kr_Id10001_Flag_ := 0;
    KEL.typ.int Kr_Id10002_Flag_ := 0;
    KEL.typ.int Kr_Id10003_Flag_ := 0;
    KEL.typ.int Kr_Id10004_Flag_ := 0;
    KEL.typ.int Kr_Id10005_Flag_ := 0;
    KEL.typ.int Kr_Id10006_Flag_ := 0;
    KEL.typ.int Kr_Id10007_Flag_ := 0;
    KEL.typ.int Kr_Id1010_Flag_ := 0;
    KEL.typ.int Kr_Id11000_Flag_ := 0;
    KEL.typ.int Kr_Id11001_Flag_ := 0;
    KEL.typ.int Kr_Id11002_Flag_ := 0;
    KEL.typ.int Kr_Id11003_Flag_ := 0;
    KEL.typ.int Kr_Id11004_Flag_ := 0;
    KEL.typ.int Kr_Id11005_Flag_ := 0;
    KEL.typ.int Kr_Id11006_Flag_ := 0;
    KEL.typ.int Kr_Id11007_Flag_ := 0;
    KEL.typ.int Kr_Id11008_Flag_ := 0;
    KEL.typ.int Kr_Id11009_Flag_ := 0;
    KEL.typ.int Kr_Id11010_Flag_ := 0;
    KEL.typ.int Kr_Id11011_Flag_ := 0;
    KEL.typ.int Kr_Id11012_Flag_ := 0;
    KEL.typ.int Kr_Id11013_Flag_ := 0;
    KEL.typ.int Kr_Id11014_Flag_ := 0;
    KEL.typ.int Kr_Id11015_Flag_ := 0;
    KEL.typ.int Kr_Id11016_Flag_ := 0;
    KEL.typ.int Kr_Id11017_Flag_ := 0;
    KEL.typ.int Kr_Id11018_Flag_ := 0;
    KEL.typ.int Kr_Id11019_Flag_ := 0;
    KEL.typ.int Kr_Id12000_Flag_ := 0;
    KEL.typ.int Kr_Id12001_Flag_ := 0;
    KEL.typ.int Kr_Id12002_Flag_ := 0;
    KEL.typ.int Kr_Id12003_Flag_ := 0;
    KEL.typ.int Kr_Id12004_Flag_ := 0;
    KEL.typ.int Kr_Id12006_Flag_ := 0;
    KEL.typ.int Kr_Id12007_Flag_ := 0;
    KEL.typ.int Kr_Id13000_Flag_ := 0;
    KEL.typ.int Kr_Id13001_Flag_ := 0;
    KEL.typ.int Kr_Id13002_Flag_ := 0;
    KEL.typ.int Kr_Id13003_Flag_ := 0;
    KEL.typ.int Kr_Id13005_Flag_ := 0;
    KEL.typ.int Kr_Id13006_Flag_ := 0;
    KEL.typ.int Kr_Id13007_Flag_ := 0;
    KEL.typ.int Kr_Id14000_Flag_ := 0;
    KEL.typ.int Kr_Id14001_Flag_ := 0;
    KEL.typ.int Kr_Id14900_Flag_ := 0;
    KEL.typ.int Kr_Id14901_Flag_ := 0;
    KEL.typ.int Kr_Id14902_Flag_ := 0;
    KEL.typ.int Kr_Id14903_Flag_ := 0;
    KEL.typ.int Kr_Id2025_Flag_ := 0;
    KEL.typ.int Kr_Identity_Flag_ := 0;
    KEL.typ.int Kr_Identity_Risk_ := 0;
    KEL.typ.int Kr_Ip1000_Flag_ := 0;
    KEL.typ.int Kr_Ip1001_Flag_ := 0;
    KEL.typ.int Kr_Ip1090_Flag_ := 0;
    KEL.typ.int Kr_Ip1091_Flag_ := 0;
    KEL.typ.int Kr_Ip1092_Flag_ := 0;
    KEL.typ.int Kr_Ip1093_Flag_ := 0;
    KEL.typ.int Kr_Ip600_Flag_ := 0;
    KEL.typ.int Kr_Ip601_Flag_ := 0;
    KEL.typ.int Kr_Ip602_Flag_ := 0;
    KEL.typ.int Kr_Ip603_Flag_ := 0;
    KEL.typ.int Kr_Ip604_Flag_ := 0;
    KEL.typ.int Kr_Ip605_Flag_ := 0;
    KEL.typ.int Kr_Ip690_Flag_ := 0;
    KEL.typ.int Kr_Ip691_Flag_ := 0;
    KEL.typ.int Kr_Ip692_Flag_ := 0;
    KEL.typ.int Kr_Ip693_Flag_ := 0;
    KEL.typ.int Kr_Ip_Flag_ := 0;
    KEL.typ.int Kr_Low_Risk_Address_Flag_ := 0;
    KEL.typ.int Kr_Low_Risk_Bank_Flag_ := 0;
    KEL.typ.int Kr_Low_Risk_Dl_Flag_ := 0;
    KEL.typ.int Kr_Low_Risk_Email_Flag_ := 0;
    KEL.typ.int Kr_Low_Risk_Identity_Flag_ := 0;
    KEL.typ.int Kr_Low_Risk_Ip_Address_Flag_ := 0;
    KEL.typ.int Kr_Low_Risk_Phone_Flag_ := 0;
    KEL.typ.int Kr_Low_Risk_Ssn_Flag_ := 0;
    KEL.typ.int Kr_Medium_Risk_Address_Flag_ := 0;
    KEL.typ.int Kr_Medium_Risk_Bank_Flag_ := 0;
    KEL.typ.int Kr_Medium_Risk_Dl_Flag_ := 0;
    KEL.typ.int Kr_Medium_Risk_Email_Flag_ := 0;
    KEL.typ.int Kr_Medium_Risk_Identity_Flag_ := 0;
    KEL.typ.int Kr_Medium_Risk_Ip_Address_Flag_ := 0;
    KEL.typ.int Kr_Medium_Risk_Phone_Flag_ := 0;
    KEL.typ.int Kr_Medium_Risk_Ssn_Flag_ := 0;
    KEL.typ.int Kr_Phn400_Flag_ := 0;
    KEL.typ.int Kr_Phn401_Flag_ := 0;
    KEL.typ.int Kr_Phn402_Flag_ := 0;
    KEL.typ.int Kr_Phn490_Flag_ := 0;
    KEL.typ.int Kr_Phn491_Flag_ := 0;
    KEL.typ.int Kr_Phn492_Flag_ := 0;
    KEL.typ.int Kr_Phn493_Flag_ := 0;
    KEL.typ.int Kr_Phone_Flag_ := 0;
    KEL.typ.int Kr_Ssn100_Flag_ := 0;
    KEL.typ.int Kr_Ssn101_Flag_ := 0;
    KEL.typ.int Kr_Ssn103_Flag_ := 0;
    KEL.typ.int Kr_Ssn104_Flag_ := 0;
    KEL.typ.int Kr_Ssn105_Flag_ := 0;
    KEL.typ.int Kr_Ssn190_Flag_ := 0;
    KEL.typ.int Kr_Ssn191_Flag_ := 0;
    KEL.typ.int Kr_Ssn192_Flag_ := 0;
    KEL.typ.int Kr_Ssn193_Flag_ := 0;
    KEL.typ.int Kr_Ssn_Flag_ := 0;
    KEL.typ.nfloat Latitude_;
    KEL.typ.nint Lex_Id_;
    KEL.typ.ntyp(E_Address.Typ) Location_;
    KEL.typ.nfloat Longitude_;
    KEL.typ.nint Manipulated_Identity_Index_;
    KEL.typ.int No_Lex_Id_ := 0;
    KEL.typ.nstr Otto_Address_Id_;
    KEL.typ.nstr Otto_Drivers_License_Id_;
    KEL.typ.nstr Otto_Email_Id_;
    KEL.typ.nstr Otto_Ip_Address_Id_;
    KEL.typ.nstr Otto_S_S_N_Id_;
    KEL.typ.nstr Phone_Number_;
    KEL.typ.nint Record_Id_;
    KEL.typ.int Safe_Flag_ := 0;
    KEL.typ.ndataset(E_Event.Source_Customers_Layout) Source_Customers_;
    KEL.typ.nint Stolen_Identity_Index_;
    KEL.typ.ntyp(E_Person.Typ) Subject_;
    KEL.typ.nint Subject_Ssn_Count_;
    KEL.typ.nint Suspicious_Activity_Index_;
    KEL.typ.nint Synthetic_Identity_Index_;
    KEL.typ.nint Vulnerable_Victim_Index_;
    KEL.typ.nstr _additional__fname__1_;
    KEL.typ.nstr _additional__fname__2_;
    KEL.typ.nstr _additional__fname__3_;
    KEL.typ.nstr _additional__lname__1_;
    KEL.typ.nstr _additional__lname__2_;
    KEL.typ.nstr _additional__lname__3_;
    KEL.typ.nstr _additional__lname__date__last__1_;
    KEL.typ.nstr _additional__lname__date__last__2_;
    KEL.typ.nstr _additional__lname__date__last__3_;
    KEL.typ.nstr _advo__addressstyle_;
    KEL.typ.nstr _advo__addresstype_;
    KEL.typ.nstr _advo__addressusagetype_;
    KEL.typ.nstr _advo__dropindicator_;
    KEL.typ.nstr _advo__hitflag_;
    KEL.typ.nstr _advo__residentialorbusinessindicator_;
    KEL.typ.nstr _advo__vacancyindicator_;
    KEL.typ.nstr _asn_;
    KEL.typ.nstr _asnname_;
    KEL.typ.nint _bank__account__1__risk__code_;
    KEL.typ.nint _bank__account__2__risk__code_;
    KEL.typ.nint _business__risk__code_;
    KEL.typ.nstr _cbsacode_;
    KEL.typ.nstr _cbsatitle_;
    KEL.typ.nstr _cbsatype_;
    KEL.typ.nint _cell__phone__risk__code_;
    KEL.typ.nstr _companyname_;
    KEL.typ.nstr _county__death_;
    KEL.typ.nstr _csacode_;
    KEL.typ.nstr _csatitle_;
    KEL.typ.nstr _curr__incar__flag_;
    KEL.typ.nstr _cvi_;
    KEL.typ.nstr _cvicustomscore_;
    KEL.typ.nstr _death__rec__src_;
    KEL.typ.nint _device__risk__code_;
    KEL.typ.nint _dob__risk__code_;
    KEL.typ.nstr _dobmatchlevel_;
    KEL.typ.nstr _domainname_;
    KEL.typ.nint _drivers__license__risk__code_;
    KEL.typ.nstr _edgeareacodes_;
    KEL.typ.nstr _edgecity_;
    KEL.typ.nstr _edgecitycode_;
    KEL.typ.nstr _edgecitycong_;
    KEL.typ.nstr _edgeconnspeed_;
    KEL.typ.nstr _edgecontinentcode_;
    KEL.typ.nstr _edgecountry_;
    KEL.typ.nstr _edgecountrycode_;
    KEL.typ.nstr _edgecountryconf_;
    KEL.typ.nstr _edgegmtoffset_;
    KEL.typ.nstr _edgeindst_;
    KEL.typ.nstr _edgeinternalcode_;
    KEL.typ.nstr _edgelatitude_;
    KEL.typ.nstr _edgelongitude_;
    KEL.typ.nstr _edgemetrocode_;
    KEL.typ.nstr _edgepostalcode_;
    KEL.typ.nstr _edgepostalconf_;
    KEL.typ.nstr _edgeregion_;
    KEL.typ.nstr _edgeregioncode_;
    KEL.typ.nstr _edgeregionconf_;
    KEL.typ.nstr _edgetwolettercountry_;
    KEL.typ.nint _email__address__risk__code_;
    KEL.typ.nstr _homebiztype_;
    KEL.typ.nstr _households_;
    KEL.typ.nint _identity__risk__code_;
    KEL.typ.nint _ip__address__fraud__code_;
    KEL.typ.nstr _iprngbeg_;
    KEL.typ.nstr _iprngend_;
    KEL.typ.nstr _isanisp_;
    KEL.typ.nbool _isdeepdive_;
    KEL.typ.nstr _ispname_;
    KEL.typ.nstr _kids_;
    KEL.typ.nint _mailing__address__risk__code_;
    KEL.typ.nstr _mdcode_;
    KEL.typ.nstr _mdtitle_;
    KEL.typ.nstr _men_;
    KEL.typ.nstr _men18to34_;
    KEL.typ.nstr _men35to49_;
    KEL.typ.nstr _naicscode_;
    KEL.typ.nint _name__risk__code_;
    KEL.typ.nint _name__ssn__dob__match_;
    KEL.typ.nint _nap__summary_;
    KEL.typ.nint _nas__summary_;
    KEL.typ.nstr _off__cat__list_;
    KEL.typ.nstr _organizationname_;
    KEL.typ.nint _phone__risk__code_;
    KEL.typ.nint _physical__address__risk__code_;
    KEL.typ.nstr _primarylang_;
    KEL.typ.nstr _proxydescription_;
    KEL.typ.nstr _proxytype_;
    KEL.typ.ntyp(E_Bank_Account.Typ) _r_Bank_Account_;
    KEL.typ.ntyp(E_Customer.Typ) _r_Customer__1_;
    KEL.typ.ntyp(E_Drivers_License.Typ) _r_Drivers_License_;
    KEL.typ.ntyp(E_Email.Typ) _r_Email_;
    KEL.typ.ntyp(E_Internet_Protocol.Typ) _r_Internet_Protocol_;
    KEL.typ.ntyp(E_Phone.Typ) _r_Phone_;
    KEL.typ.ntyp(E_Social_Security_Number.Typ) _r_Ssn_;
    KEL.typ.nstr _ranks_;
    KEL.typ.nint _relativeaddressmatch_;
    KEL.typ.nstr _secondarylang_;
    KEL.typ.nstr _siccode_;
    KEL.typ.nint _ssn__risk__code_;
    KEL.typ.nbool _ssnfoundforlexid_;
    KEL.typ.nstr _state__death__flag_;
    KEL.typ.nstr _state__death__id_;
    KEL.typ.nint _subjectssncount_;
    KEL.typ.nstr _teens_;
    KEL.typ.nint _v2__assoccreditbureauonlycount_;
    KEL.typ.nint _v2__assocsuspicousidentitiescount_;
    KEL.typ.nstr _v2__divssnidentitycountnew_;
    KEL.typ.nint _v2__inputaddrageoldest_;
    KEL.typ.nstr _v2__inputaddrdwelltype_;
    KEL.typ.nint _v2__sourcerisklevel_;
    KEL.typ.nint _v2__validationaddrproblems_;
    KEL.typ.nstr _valid__ssn_;
    KEL.typ.nstr _veraddr_;
    KEL.typ.nstr _vercity_;
    KEL.typ.nstr _verdob_;
    KEL.typ.nstr _verfirst_;
    KEL.typ.nstr _verhphone_;
    KEL.typ.nstr _verify__addr_;
    KEL.typ.nstr _verify__dob_;
    KEL.typ.nstr _verlast_;
    KEL.typ.nstr _verssn_;
    KEL.typ.nstr _verstate_;
    KEL.typ.nstr _verzip_;
    KEL.typ.nstr _verzip4_;
    KEL.typ.nstr _women_;
    KEL.typ.nstr _women18to34_;
    KEL.typ.nstr _women35to49_;
    KEL.typ.nint _work__phone__risk__code_;
    KEL.typ.epoch Date_First_Seen_ := 0;
    KEL.typ.epoch Date_Last_Seen_ := 0;
  END;
  SHARED __ST872650_Layout __ND891062__Project(__ST876391_Layout __PP890670) := TRANSFORM
    SELF.UID := __PP890670.Ip_;
    SELF._r_Customer_ := __PP890670._r_Customer__1_;
    SELF.Event_Date_ := __PP890670.Event_Date__1_;
    SELF.U_I_D__1_ := __PP890670.UID;
    SELF.Event_Date__1_ := __PP890670.Event_Date_;
    SELF._r_Customer__1_ := __PP890670._r_Customer_;
    SELF := __PP890670;
  END;
  SHARED __EE892587 := PROJECT(__EE890669,__ND891062__Project(LEFT));
  SHARED __ST873533_Layout := RECORD
    KEL.typ.ntyp(E_Internet_Protocol.Typ) UID;
    KEL.typ.bool Exp1_ := FALSE;
    KEL.typ.nkdate Event_Date__1_;
    KEL.typ.bool Exp2_ := FALSE;
    KEL.typ.bool Exp3_ := FALSE;
    KEL.typ.bool Exp4_ := FALSE;
    KEL.typ.bool Exp5_ := FALSE;
    KEL.typ.bool Exp6_ := FALSE;
    KEL.typ.bool Exp7_ := FALSE;
    KEL.typ.bool Exp8_ := FALSE;
    KEL.typ.bool Exp9_ := FALSE;
    KEL.typ.bool Exp10_ := FALSE;
    KEL.typ.bool Exp11_ := FALSE;
    KEL.typ.bool Exp12_ := FALSE;
    KEL.typ.bool Exp13_ := FALSE;
    KEL.typ.bool Exp14_ := FALSE;
    KEL.typ.bool Exp15_ := FALSE;
    KEL.typ.bool Exp16_ := FALSE;
    KEL.typ.bool Exp17_ := FALSE;
    KEL.typ.bool Exp18_ := FALSE;
    KEL.typ.bool Exp19_ := FALSE;
    KEL.typ.bool Exp20_ := FALSE;
    KEL.typ.bool Exp21_ := FALSE;
    KEL.typ.bool Exp22_ := FALSE;
    KEL.typ.bool Exp23_ := FALSE;
    KEL.typ.bool Exp24_ := FALSE;
    KEL.typ.bool Exp25_ := FALSE;
    KEL.typ.bool Exp26_ := FALSE;
    KEL.typ.nbool Exp27_;
    KEL.typ.nbool Exp28_;
    KEL.typ.nbool Exp29_;
    KEL.typ.epoch Date_First_Seen_ := 0;
    KEL.typ.epoch Date_Last_Seen_ := 0;
  END;
  SHARED __ST873533_Layout __ND893806__Project(__ST872650_Layout __PP892588) := TRANSFORM
    SELF.Exp1_ := __PP892588.Contributor_Safe_Flag_ = 1;
    SELF.Exp2_ := __PP892588.Ip_High_Risk_City_ = 1;
    SELF.Exp3_ := __PP892588.Ip_Hosted_ = 1;
    SELF.Exp4_ := __PP892588.Ip_Not_Us_ = 1;
    SELF.Exp5_ := __PP892588.Ip_Tor_ = 1;
    SELF.Exp6_ := __PP892588.Ip_Vpn_ = 1;
    SELF.Exp7_ := __PP892588.Kr_High_Risk_Ip_Address_Flag_ = 1;
    SELF.Exp8_ := __PP892588.Kr_Ip1000_Flag_ = 1;
    SELF.Exp9_ := __PP892588.Kr_Ip1001_Flag_ = 1;
    SELF.Exp10_ := __PP892588.Kr_Ip1090_Flag_ = 1;
    SELF.Exp11_ := __PP892588.Kr_Ip1091_Flag_ = 1;
    SELF.Exp12_ := __PP892588.Kr_Ip1092_Flag_ = 1;
    SELF.Exp13_ := __PP892588.Kr_Ip1093_Flag_ = 1;
    SELF.Exp14_ := __PP892588.Kr_Ip600_Flag_ = 1;
    SELF.Exp15_ := __PP892588.Kr_Ip601_Flag_ = 1;
    SELF.Exp16_ := __PP892588.Kr_Ip602_Flag_ = 1;
    SELF.Exp17_ := __PP892588.Kr_Ip603_Flag_ = 1;
    SELF.Exp18_ := __PP892588.Kr_Ip604_Flag_ = 1;
    SELF.Exp19_ := __PP892588.Kr_Ip605_Flag_ = 1;
    SELF.Exp20_ := __PP892588.Kr_Ip690_Flag_ = 1;
    SELF.Exp21_ := __PP892588.Kr_Ip691_Flag_ = 1;
    SELF.Exp22_ := __PP892588.Kr_Ip692_Flag_ = 1;
    SELF.Exp23_ := __PP892588.Kr_Ip693_Flag_ = 1;
    SELF.Exp24_ := __PP892588.Kr_Low_Risk_Ip_Address_Flag_ = 1;
    SELF.Exp25_ := __PP892588.Kr_Medium_Risk_Ip_Address_Flag_ = 1;
    SELF.Exp26_ := __PP892588.Safe_Flag_ = 1;
    SELF.Exp27_ := __OP2(__PP892588.Event_Age_,<,__CN(2));
    SELF.Exp28_ := __AND(__OP2(__PP892588.Event_Age_,<,__CN(2)),__CN(__PP892588.In_Customer_Population_ = 1));
    SELF.Exp29_ := __OP2(__PP892588.Event_Age_,<,__CN(366));
    SELF := __PP892588;
  END;
  SHARED __EE893845 := PROJECT(__EE892587,__ND893806__Project(LEFT));
  SHARED __ST873699_Layout := RECORD
    KEL.typ.int C_O_U_N_T___Exp1_ := 0;
    KEL.typ.nkdate M_I_N___Event_Date__1_;
    KEL.typ.nkdate M_A_X___Event_Date__1_;
    KEL.typ.int C_O_U_N_T___Exp1__1_ := 0;
    KEL.typ.int C_O_U_N_T___Exp1__2_ := 0;
    KEL.typ.int C_O_U_N_T___Exp1__3_ := 0;
    KEL.typ.int C_O_U_N_T___Exp1__4_ := 0;
    KEL.typ.int C_O_U_N_T___Exp1__5_ := 0;
    KEL.typ.int C_O_U_N_T___Exp1__6_ := 0;
    KEL.typ.int C_O_U_N_T___Exp1__7_ := 0;
    KEL.typ.int C_O_U_N_T___Exp1__8_ := 0;
    KEL.typ.int C_O_U_N_T___Exp1__9_ := 0;
    KEL.typ.int C_O_U_N_T___Exp1__10_ := 0;
    KEL.typ.int C_O_U_N_T___Exp1__11_ := 0;
    KEL.typ.int C_O_U_N_T___Exp1__12_ := 0;
    KEL.typ.int C_O_U_N_T___Exp1__13_ := 0;
    KEL.typ.int C_O_U_N_T___Exp1__14_ := 0;
    KEL.typ.int C_O_U_N_T___Exp1__15_ := 0;
    KEL.typ.int C_O_U_N_T___Exp1__16_ := 0;
    KEL.typ.int C_O_U_N_T___Exp1__17_ := 0;
    KEL.typ.int C_O_U_N_T___Exp1__18_ := 0;
    KEL.typ.int C_O_U_N_T___Exp1__19_ := 0;
    KEL.typ.int C_O_U_N_T___Exp1__20_ := 0;
    KEL.typ.int C_O_U_N_T___Exp1__21_ := 0;
    KEL.typ.int C_O_U_N_T___Exp1__22_ := 0;
    KEL.typ.int C_O_U_N_T___Exp1__23_ := 0;
    KEL.typ.int C_O_U_N_T___Exp1__24_ := 0;
    KEL.typ.nkdate M_A_X___Event_Date__2_;
    KEL.typ.int C_O_U_N_T___Exp1__25_ := 0;
    KEL.typ.int C_O_U_N_T___Exp1__26_ := 0;
    KEL.typ.int C_O_U_N_T___Exp1__27_ := 0;
    KEL.typ.int C_O_U_N_T___Exp1__28_ := 0;
    KEL.typ.ntyp(E_Internet_Protocol.Typ) UID;
    KEL.typ.epoch Date_First_Seen_ := 0;
    KEL.typ.epoch Date_Last_Seen_ := 0;
  END;
  SHARED __EE894019 := PROJECT(__CLEANANDDO(__EE893845,TABLE(__EE893845,{KEL.typ.int C_O_U_N_T___Exp1_ := COUNT(GROUP,__EE893845.Exp1_),KEL.Aggregates.MinNG(__EE893845.Event_Date__1_) M_I_N___Event_Date__1_,KEL.Aggregates.MaxNG(__EE893845.Event_Date__1_) M_A_X___Event_Date__1_,KEL.typ.int C_O_U_N_T___Exp1__1_ := COUNT(GROUP,__EE893845.Exp2_),KEL.typ.int C_O_U_N_T___Exp1__2_ := COUNT(GROUP,__EE893845.Exp3_),KEL.typ.int C_O_U_N_T___Exp1__3_ := COUNT(GROUP,__EE893845.Exp4_),KEL.typ.int C_O_U_N_T___Exp1__4_ := COUNT(GROUP,__EE893845.Exp5_),KEL.typ.int C_O_U_N_T___Exp1__5_ := COUNT(GROUP,__EE893845.Exp6_),KEL.typ.int C_O_U_N_T___Exp1__6_ := COUNT(GROUP,__EE893845.Exp7_),KEL.typ.int C_O_U_N_T___Exp1__7_ := COUNT(GROUP,__EE893845.Exp8_),KEL.typ.int C_O_U_N_T___Exp1__8_ := COUNT(GROUP,__EE893845.Exp9_),KEL.typ.int C_O_U_N_T___Exp1__9_ := COUNT(GROUP,__EE893845.Exp10_),KEL.typ.int C_O_U_N_T___Exp1__10_ := COUNT(GROUP,__EE893845.Exp11_),KEL.typ.int C_O_U_N_T___Exp1__11_ := COUNT(GROUP,__EE893845.Exp12_),KEL.typ.int C_O_U_N_T___Exp1__12_ := COUNT(GROUP,__EE893845.Exp13_),KEL.typ.int C_O_U_N_T___Exp1__13_ := COUNT(GROUP,__EE893845.Exp14_),KEL.typ.int C_O_U_N_T___Exp1__14_ := COUNT(GROUP,__EE893845.Exp15_),KEL.typ.int C_O_U_N_T___Exp1__15_ := COUNT(GROUP,__EE893845.Exp16_),KEL.typ.int C_O_U_N_T___Exp1__16_ := COUNT(GROUP,__EE893845.Exp17_),KEL.typ.int C_O_U_N_T___Exp1__17_ := COUNT(GROUP,__EE893845.Exp18_),KEL.typ.int C_O_U_N_T___Exp1__18_ := COUNT(GROUP,__EE893845.Exp19_),KEL.typ.int C_O_U_N_T___Exp1__19_ := COUNT(GROUP,__EE893845.Exp20_),KEL.typ.int C_O_U_N_T___Exp1__20_ := COUNT(GROUP,__EE893845.Exp21_),KEL.typ.int C_O_U_N_T___Exp1__21_ := COUNT(GROUP,__EE893845.Exp22_),KEL.typ.int C_O_U_N_T___Exp1__22_ := COUNT(GROUP,__EE893845.Exp23_),KEL.typ.int C_O_U_N_T___Exp1__23_ := COUNT(GROUP,__EE893845.Exp24_),KEL.typ.int C_O_U_N_T___Exp1__24_ := COUNT(GROUP,__EE893845.Exp25_),KEL.Aggregates.MaxNG(__EE893845.Event_Date__1_) M_A_X___Event_Date__2_,KEL.typ.int C_O_U_N_T___Exp1__25_ := COUNT(GROUP,__EE893845.Exp26_),KEL.typ.int C_O_U_N_T___Exp1__26_ := COUNT(GROUP,__T(__EE893845.Exp27_)),KEL.typ.int C_O_U_N_T___Exp1__27_ := COUNT(GROUP,__T(__EE893845.Exp28_)),KEL.typ.int C_O_U_N_T___Exp1__28_ := COUNT(GROUP,__T(__EE893845.Exp29_)),UID},UID,MERGE)),__ST873699_Layout);
  SHARED __ST879522_Layout := RECORD
    KEL.typ.nuid UID;
    KEL.typ.ntyp(E_Customer.Typ) _r_Customer_;
    KEL.typ.ndataset(E_Internet_Protocol.Source_Customers_Layout) Source_Customers_;
    KEL.typ.nstr Ip_Address_;
    KEL.typ.nstr Otto_Ip_Address_Id_;
    KEL.typ.nstr _host_;
    KEL.typ.nstr _alias_;
    KEL.typ.nstr _location_;
    KEL.typ.nstr _ip__address_;
    KEL.typ.nstr _ip__address__date_;
    KEL.typ.nstr _version_;
    KEL.typ.nstr _class_;
    KEL.typ.nstr _subnet__mask_;
    KEL.typ.nstr _reserved_;
    KEL.typ.nstr _isp_;
    KEL.typ.nint _v2__validationipproblems_;
    KEL.typ.nstr _v2__ipstate_;
    KEL.typ.nstr _v2__ipcountry_;
    KEL.typ.nstr _v2__ipcontinent_;
    KEL.typ.nstr _iprngbeg_;
    KEL.typ.nstr _iprngend_;
    KEL.typ.nstr _edgecountry_;
    KEL.typ.nstr _edgeregion_;
    KEL.typ.nstr _edgecity_;
    KEL.typ.nstr _edgeconnspeed_;
    KEL.typ.nstr _edgemetrocode_;
    KEL.typ.nstr _edgelatitude_;
    KEL.typ.nstr _edgelongitude_;
    KEL.typ.nstr _edgepostalcode_;
    KEL.typ.nstr _edgecountrycode_;
    KEL.typ.nstr _edgeregioncode_;
    KEL.typ.nstr _edgecitycode_;
    KEL.typ.nstr _edgecontinentcode_;
    KEL.typ.nstr _edgetwolettercountry_;
    KEL.typ.nstr _edgeinternalcode_;
    KEL.typ.nstr _edgeareacodes_;
    KEL.typ.nstr _edgecountryconf_;
    KEL.typ.nstr _edgeregionconf_;
    KEL.typ.nstr _edgecitycong_;
    KEL.typ.nstr _edgepostalconf_;
    KEL.typ.nstr _edgegmtoffset_;
    KEL.typ.nstr _edgeindst_;
    KEL.typ.nstr _siccode_;
    KEL.typ.nstr _domainname_;
    KEL.typ.nstr _ispname_;
    KEL.typ.nstr _homebiztype_;
    KEL.typ.nstr _asn_;
    KEL.typ.nstr _asnname_;
    KEL.typ.nstr _primarylang_;
    KEL.typ.nstr _secondarylang_;
    KEL.typ.nstr _proxytype_;
    KEL.typ.nstr _proxydescription_;
    KEL.typ.nstr _isanisp_;
    KEL.typ.nstr _companyname_;
    KEL.typ.nstr _ranks_;
    KEL.typ.nstr _households_;
    KEL.typ.nstr _women_;
    KEL.typ.nstr _women18to34_;
    KEL.typ.nstr _women35to49_;
    KEL.typ.nstr _men_;
    KEL.typ.nstr _men18to34_;
    KEL.typ.nstr _men35to49_;
    KEL.typ.nstr _teens_;
    KEL.typ.nstr _kids_;
    KEL.typ.nstr _naicscode_;
    KEL.typ.nstr _cbsacode_;
    KEL.typ.nstr _cbsatitle_;
    KEL.typ.nstr _cbsatype_;
    KEL.typ.nstr _csacode_;
    KEL.typ.nstr _csatitle_;
    KEL.typ.nstr _mdcode_;
    KEL.typ.nstr _mdtitle_;
    KEL.typ.nstr _organizationname_;
    KEL.typ.nstr Entity_Context_Uid_;
    KEL.typ.int Kr_Event_After_Last_Known_Risk_Count_ := 0;
    KEL.typ.int Kr_Event_After_Last_Known_Risk_Flag_ := 0;
    KEL.typ.int Kr_Flag_ := 0;
    KEL.typ.nkdate Kr_Last_Event_Date_;
    KEL.typ.nstr Label_;
    KEL.typ.nint Last_Record_Id_;
    KEL.typ.int Vl_Event30_All_Day_Count_ := 0;
    KEL.typ.int Vl_Event30_Count_ := 0;
    KEL.typ.int Vl_Event365_Count_ := 0;
    KEL.typ.int Vl_Event7_All_Count_ := 0;
    KEL.typ.int Vl_Event7_Count_ := 0;
    KEL.typ.int C_O_U_N_T___Person_Ip_Address_ := 0;
    KEL.typ.ntyp(E_Internet_Protocol.Typ) U_I_D__1_;
    KEL.typ.int C_O_U_N_T___Internet_Protocol_Event_ := 0;
    KEL.typ.ntyp(E_Internet_Protocol.Typ) U_I_D__2_;
    KEL.typ.int C_O_U_N_T___Exp1_ := 0;
    KEL.typ.nkdate M_I_N___Event_Date__1_;
    KEL.typ.nkdate M_A_X___Event_Date__1_;
    KEL.typ.int C_O_U_N_T___Exp1__1_ := 0;
    KEL.typ.int C_O_U_N_T___Exp1__2_ := 0;
    KEL.typ.int C_O_U_N_T___Exp1__3_ := 0;
    KEL.typ.int C_O_U_N_T___Exp1__4_ := 0;
    KEL.typ.int C_O_U_N_T___Exp1__5_ := 0;
    KEL.typ.int C_O_U_N_T___Exp1__6_ := 0;
    KEL.typ.int C_O_U_N_T___Exp1__7_ := 0;
    KEL.typ.int C_O_U_N_T___Exp1__8_ := 0;
    KEL.typ.int C_O_U_N_T___Exp1__9_ := 0;
    KEL.typ.int C_O_U_N_T___Exp1__10_ := 0;
    KEL.typ.int C_O_U_N_T___Exp1__11_ := 0;
    KEL.typ.int C_O_U_N_T___Exp1__12_ := 0;
    KEL.typ.int C_O_U_N_T___Exp1__13_ := 0;
    KEL.typ.int C_O_U_N_T___Exp1__14_ := 0;
    KEL.typ.int C_O_U_N_T___Exp1__15_ := 0;
    KEL.typ.int C_O_U_N_T___Exp1__16_ := 0;
    KEL.typ.int C_O_U_N_T___Exp1__17_ := 0;
    KEL.typ.int C_O_U_N_T___Exp1__18_ := 0;
    KEL.typ.int C_O_U_N_T___Exp1__19_ := 0;
    KEL.typ.int C_O_U_N_T___Exp1__20_ := 0;
    KEL.typ.int C_O_U_N_T___Exp1__21_ := 0;
    KEL.typ.int C_O_U_N_T___Exp1__22_ := 0;
    KEL.typ.int C_O_U_N_T___Exp1__23_ := 0;
    KEL.typ.int C_O_U_N_T___Exp1__24_ := 0;
    KEL.typ.nkdate M_A_X___Event_Date__2_;
    KEL.typ.int C_O_U_N_T___Exp1__25_ := 0;
    KEL.typ.int C_O_U_N_T___Exp1__26_ := 0;
    KEL.typ.int C_O_U_N_T___Exp1__27_ := 0;
    KEL.typ.int C_O_U_N_T___Exp1__28_ := 0;
    KEL.typ.ntyp(E_Internet_Protocol.Typ) U_I_D__3_;
    KEL.typ.epoch Date_First_Seen_ := 0;
    KEL.typ.epoch Date_Last_Seen_ := 0;
    KEL.typ.int __RecordCount := 0;
  END;
  __JC894025(__ST878924_Layout __EE885327, __ST873699_Layout __EE894019) := __EEQP(__EE885327.UID,__EE894019.UID);
  __ST879522_Layout __JT894025(__ST878924_Layout __l, __ST873699_Layout __r) := TRANSFORM
    SELF.U_I_D__3_ := __r.UID;
    SELF := __l;
    SELF := __r;
  END;
  SHARED __EE894153 := JOIN(__EE885327,__EE894019,__JC894025(LEFT,RIGHT),__JT894025(LEFT,RIGHT),LEFT OUTER,HASH);
  SHARED __EE820445 := __ENH_Customer_1;
  SHARED __ST880264_Layout := RECORD
    KEL.typ.nuid UID;
    KEL.typ.ntyp(E_Customer.Typ) _r_Customer_;
    KEL.typ.ndataset(E_Internet_Protocol.Source_Customers_Layout) Source_Customers_;
    KEL.typ.nstr Ip_Address_;
    KEL.typ.nstr Otto_Ip_Address_Id_;
    KEL.typ.nstr _host_;
    KEL.typ.nstr _alias_;
    KEL.typ.nstr _location_;
    KEL.typ.nstr _ip__address_;
    KEL.typ.nstr _ip__address__date_;
    KEL.typ.nstr _version_;
    KEL.typ.nstr _class_;
    KEL.typ.nstr _subnet__mask_;
    KEL.typ.nstr _reserved_;
    KEL.typ.nstr _isp_;
    KEL.typ.nint _v2__validationipproblems_;
    KEL.typ.nstr _v2__ipstate_;
    KEL.typ.nstr _v2__ipcountry_;
    KEL.typ.nstr _v2__ipcontinent_;
    KEL.typ.nstr _iprngbeg_;
    KEL.typ.nstr _iprngend_;
    KEL.typ.nstr _edgecountry_;
    KEL.typ.nstr _edgeregion_;
    KEL.typ.nstr _edgecity_;
    KEL.typ.nstr _edgeconnspeed_;
    KEL.typ.nstr _edgemetrocode_;
    KEL.typ.nstr _edgelatitude_;
    KEL.typ.nstr _edgelongitude_;
    KEL.typ.nstr _edgepostalcode_;
    KEL.typ.nstr _edgecountrycode_;
    KEL.typ.nstr _edgeregioncode_;
    KEL.typ.nstr _edgecitycode_;
    KEL.typ.nstr _edgecontinentcode_;
    KEL.typ.nstr _edgetwolettercountry_;
    KEL.typ.nstr _edgeinternalcode_;
    KEL.typ.nstr _edgeareacodes_;
    KEL.typ.nstr _edgecountryconf_;
    KEL.typ.nstr _edgeregionconf_;
    KEL.typ.nstr _edgecitycong_;
    KEL.typ.nstr _edgepostalconf_;
    KEL.typ.nstr _edgegmtoffset_;
    KEL.typ.nstr _edgeindst_;
    KEL.typ.nstr _siccode_;
    KEL.typ.nstr _domainname_;
    KEL.typ.nstr _ispname_;
    KEL.typ.nstr _homebiztype_;
    KEL.typ.nstr _asn_;
    KEL.typ.nstr _asnname_;
    KEL.typ.nstr _primarylang_;
    KEL.typ.nstr _secondarylang_;
    KEL.typ.nstr _proxytype_;
    KEL.typ.nstr _proxydescription_;
    KEL.typ.nstr _isanisp_;
    KEL.typ.nstr _companyname_;
    KEL.typ.nstr _ranks_;
    KEL.typ.nstr _households_;
    KEL.typ.nstr _women_;
    KEL.typ.nstr _women18to34_;
    KEL.typ.nstr _women35to49_;
    KEL.typ.nstr _men_;
    KEL.typ.nstr _men18to34_;
    KEL.typ.nstr _men35to49_;
    KEL.typ.nstr _teens_;
    KEL.typ.nstr _kids_;
    KEL.typ.nstr _naicscode_;
    KEL.typ.nstr _cbsacode_;
    KEL.typ.nstr _cbsatitle_;
    KEL.typ.nstr _cbsatype_;
    KEL.typ.nstr _csacode_;
    KEL.typ.nstr _csatitle_;
    KEL.typ.nstr _mdcode_;
    KEL.typ.nstr _mdtitle_;
    KEL.typ.nstr _organizationname_;
    KEL.typ.nstr Entity_Context_Uid_;
    KEL.typ.int Kr_Event_After_Last_Known_Risk_Count_ := 0;
    KEL.typ.int Kr_Event_After_Last_Known_Risk_Flag_ := 0;
    KEL.typ.int Kr_Flag_ := 0;
    KEL.typ.nkdate Kr_Last_Event_Date_;
    KEL.typ.nstr Label_;
    KEL.typ.nint Last_Record_Id_;
    KEL.typ.int Vl_Event30_All_Day_Count_ := 0;
    KEL.typ.int Vl_Event30_Count_ := 0;
    KEL.typ.int Vl_Event365_Count_ := 0;
    KEL.typ.int Vl_Event7_All_Count_ := 0;
    KEL.typ.int Vl_Event7_Count_ := 0;
    KEL.typ.int C_O_U_N_T___Person_Ip_Address_ := 0;
    KEL.typ.ntyp(E_Internet_Protocol.Typ) U_I_D__1_;
    KEL.typ.int C_O_U_N_T___Internet_Protocol_Event_ := 0;
    KEL.typ.ntyp(E_Internet_Protocol.Typ) U_I_D__2_;
    KEL.typ.int C_O_U_N_T___Exp1_ := 0;
    KEL.typ.nkdate M_I_N___Event_Date__1_;
    KEL.typ.nkdate M_A_X___Event_Date__1_;
    KEL.typ.int C_O_U_N_T___Exp1__1_ := 0;
    KEL.typ.int C_O_U_N_T___Exp1__2_ := 0;
    KEL.typ.int C_O_U_N_T___Exp1__3_ := 0;
    KEL.typ.int C_O_U_N_T___Exp1__4_ := 0;
    KEL.typ.int C_O_U_N_T___Exp1__5_ := 0;
    KEL.typ.int C_O_U_N_T___Exp1__6_ := 0;
    KEL.typ.int C_O_U_N_T___Exp1__7_ := 0;
    KEL.typ.int C_O_U_N_T___Exp1__8_ := 0;
    KEL.typ.int C_O_U_N_T___Exp1__9_ := 0;
    KEL.typ.int C_O_U_N_T___Exp1__10_ := 0;
    KEL.typ.int C_O_U_N_T___Exp1__11_ := 0;
    KEL.typ.int C_O_U_N_T___Exp1__12_ := 0;
    KEL.typ.int C_O_U_N_T___Exp1__13_ := 0;
    KEL.typ.int C_O_U_N_T___Exp1__14_ := 0;
    KEL.typ.int C_O_U_N_T___Exp1__15_ := 0;
    KEL.typ.int C_O_U_N_T___Exp1__16_ := 0;
    KEL.typ.int C_O_U_N_T___Exp1__17_ := 0;
    KEL.typ.int C_O_U_N_T___Exp1__18_ := 0;
    KEL.typ.int C_O_U_N_T___Exp1__19_ := 0;
    KEL.typ.int C_O_U_N_T___Exp1__20_ := 0;
    KEL.typ.int C_O_U_N_T___Exp1__21_ := 0;
    KEL.typ.int C_O_U_N_T___Exp1__22_ := 0;
    KEL.typ.int C_O_U_N_T___Exp1__23_ := 0;
    KEL.typ.int C_O_U_N_T___Exp1__24_ := 0;
    KEL.typ.nkdate M_A_X___Event_Date__2_;
    KEL.typ.int C_O_U_N_T___Exp1__25_ := 0;
    KEL.typ.int C_O_U_N_T___Exp1__26_ := 0;
    KEL.typ.int C_O_U_N_T___Exp1__27_ := 0;
    KEL.typ.int C_O_U_N_T___Exp1__28_ := 0;
    KEL.typ.ntyp(E_Internet_Protocol.Typ) U_I_D__3_;
    KEL.typ.nuid U_I_D__4_;
    KEL.typ.nint Customer_Id_;
    KEL.typ.nint Industry_Type_;
    KEL.typ.ndataset(E_Customer.States_Layout) States_;
    KEL.typ.int Address_Count_ := 0;
    KEL.typ.int All_Address_Count_ := 0;
    KEL.typ.int All_Deceased_Matched_Person_Count_ := 0;
    KEL.typ.int All_Deceased_Person_Count_ := 0;
    KEL.typ.int All_High_Frequency_Address_Count_ := 0;
    KEL.typ.int All_Person_Count_ := 0;
    KEL.typ.int Deceased_Person_Count_ := 0;
    KEL.typ.nkdate Event_Date_Max_;
    KEL.typ.int High_Frequency_Address_Count_ := 0;
    KEL.typ.nstr Jurisdiction_State_;
    B_Customer_4.__NS96526_Layout Jurisdiction_State_Top_;
    KEL.typ.int Person_Count_ := 0;
    KEL.typ.epoch Date_First_Seen_ := 0;
    KEL.typ.epoch Date_Last_Seen_ := 0;
    KEL.typ.int __RecordCount := 0;
  END;
  __JC894159(__ST879522_Layout __EE894153, B_Customer_1.__ST32738_Layout __EE820445) := __EEQP(__EE894153._r_Customer_,__EE820445.UID);
  __ST880264_Layout __JT894159(__ST879522_Layout __l, B_Customer_1.__ST32738_Layout __r) := TRANSFORM
    SELF.U_I_D__4_ := __r.UID;
    SELF := __l;
    SELF := __r;
  END;
  SHARED __EE894309 := JOIN(__EE894153,__EE820445,__JC894159(LEFT,RIGHT),__JT894159(LEFT,RIGHT),LEFT OUTER,HASH);
  EXPORT __ST28558_Layout := RECORD
    KEL.typ.nuid UID;
    KEL.typ.ntyp(E_Customer.Typ) _r_Customer_;
    KEL.typ.ndataset(E_Internet_Protocol.Source_Customers_Layout) Source_Customers_;
    KEL.typ.nstr Ip_Address_;
    KEL.typ.nstr Otto_Ip_Address_Id_;
    KEL.typ.nstr _host_;
    KEL.typ.nstr _alias_;
    KEL.typ.nstr _location_;
    KEL.typ.nstr _ip__address_;
    KEL.typ.nstr _ip__address__date_;
    KEL.typ.nstr _version_;
    KEL.typ.nstr _class_;
    KEL.typ.nstr _subnet__mask_;
    KEL.typ.nstr _reserved_;
    KEL.typ.nstr _isp_;
    KEL.typ.nint _v2__validationipproblems_;
    KEL.typ.nstr _v2__ipstate_;
    KEL.typ.nstr _v2__ipcountry_;
    KEL.typ.nstr _v2__ipcontinent_;
    KEL.typ.nstr _iprngbeg_;
    KEL.typ.nstr _iprngend_;
    KEL.typ.nstr _edgecountry_;
    KEL.typ.nstr _edgeregion_;
    KEL.typ.nstr _edgecity_;
    KEL.typ.nstr _edgeconnspeed_;
    KEL.typ.nstr _edgemetrocode_;
    KEL.typ.nstr _edgelatitude_;
    KEL.typ.nstr _edgelongitude_;
    KEL.typ.nstr _edgepostalcode_;
    KEL.typ.nstr _edgecountrycode_;
    KEL.typ.nstr _edgeregioncode_;
    KEL.typ.nstr _edgecitycode_;
    KEL.typ.nstr _edgecontinentcode_;
    KEL.typ.nstr _edgetwolettercountry_;
    KEL.typ.nstr _edgeinternalcode_;
    KEL.typ.nstr _edgeareacodes_;
    KEL.typ.nstr _edgecountryconf_;
    KEL.typ.nstr _edgeregionconf_;
    KEL.typ.nstr _edgecitycong_;
    KEL.typ.nstr _edgepostalconf_;
    KEL.typ.nstr _edgegmtoffset_;
    KEL.typ.nstr _edgeindst_;
    KEL.typ.nstr _siccode_;
    KEL.typ.nstr _domainname_;
    KEL.typ.nstr _ispname_;
    KEL.typ.nstr _homebiztype_;
    KEL.typ.nstr _asn_;
    KEL.typ.nstr _asnname_;
    KEL.typ.nstr _primarylang_;
    KEL.typ.nstr _secondarylang_;
    KEL.typ.nstr _proxytype_;
    KEL.typ.nstr _proxydescription_;
    KEL.typ.nstr _isanisp_;
    KEL.typ.nstr _companyname_;
    KEL.typ.nstr _ranks_;
    KEL.typ.nstr _households_;
    KEL.typ.nstr _women_;
    KEL.typ.nstr _women18to34_;
    KEL.typ.nstr _women35to49_;
    KEL.typ.nstr _men_;
    KEL.typ.nstr _men18to34_;
    KEL.typ.nstr _men35to49_;
    KEL.typ.nstr _teens_;
    KEL.typ.nstr _kids_;
    KEL.typ.nstr _naicscode_;
    KEL.typ.nstr _cbsacode_;
    KEL.typ.nstr _cbsatitle_;
    KEL.typ.nstr _cbsatype_;
    KEL.typ.nstr _csacode_;
    KEL.typ.nstr _csatitle_;
    KEL.typ.nstr _mdcode_;
    KEL.typ.nstr _mdtitle_;
    KEL.typ.nstr _organizationname_;
    KEL.typ.int Contributor_Safe_Flag_ := 0;
    KEL.typ.nint Customer_Id_;
    KEL.typ.nkdate Dt_First_Seen_;
    KEL.typ.nkdate Dt_Last_Seen_;
    KEL.typ.nstr Entity_Context_Uid_;
    KEL.typ.int Entity_Type_ := 0;
    KEL.typ.int Event_Count_ := 0;
    KEL.typ.int Identity_Count_ := 0;
    KEL.typ.int In_Customer_Population_ := 0;
    KEL.typ.nint Industry_Type_;
    KEL.typ.int Ip_High_Risk_City_ := 0;
    KEL.typ.int Ip_Hosted_ := 0;
    KEL.typ.int Ip_Not_Us_ := 0;
    KEL.typ.int Ip_Tor_ := 0;
    KEL.typ.int Ip_Vpn_ := 0;
    KEL.typ.int Kr_Event_After_Last_Known_Risk_Count_ := 0;
    KEL.typ.int Kr_Event_After_Last_Known_Risk_Flag_ := 0;
    KEL.typ.int Kr_Flag_ := 0;
    KEL.typ.int Kr_High_Risk_Flag_ := 0;
    KEL.typ.int Kr_Ip1000_Flag_ := 0;
    KEL.typ.int Kr_Ip1001_Flag_ := 0;
    KEL.typ.int Kr_Ip1090_Flag_ := 0;
    KEL.typ.int Kr_Ip1091_Flag_ := 0;
    KEL.typ.int Kr_Ip1092_Flag_ := 0;
    KEL.typ.int Kr_Ip1093_Flag_ := 0;
    KEL.typ.int Kr_Ip600_Flag_ := 0;
    KEL.typ.int Kr_Ip601_Flag_ := 0;
    KEL.typ.int Kr_Ip602_Flag_ := 0;
    KEL.typ.int Kr_Ip603_Flag_ := 0;
    KEL.typ.int Kr_Ip604_Flag_ := 0;
    KEL.typ.int Kr_Ip605_Flag_ := 0;
    KEL.typ.int Kr_Ip690_Flag_ := 0;
    KEL.typ.int Kr_Ip691_Flag_ := 0;
    KEL.typ.int Kr_Ip692_Flag_ := 0;
    KEL.typ.int Kr_Ip693_Flag_ := 0;
    KEL.typ.nkdate Kr_Last_Event_Date_;
    KEL.typ.int Kr_Low_Risk_Flag_ := 0;
    KEL.typ.int Kr_Medium_Risk_Flag_ := 0;
    KEL.typ.nstr Label_;
    KEL.typ.nkdate Last_Event_Date_;
    KEL.typ.nint Last_Record_Id_;
    KEL.typ.int Safe_Flag_ := 0;
    KEL.typ.nint Source_Customer_Count_;
    KEL.typ.int Vl_Event1_All_Count_ := 0;
    KEL.typ.int Vl_Event1_Count_ := 0;
    KEL.typ.int Vl_Event30_Active_Flag_ := 0;
    KEL.typ.int Vl_Event30_All_Active_Flag_ := 0;
    KEL.typ.int Vl_Event30_All_Day_Count_ := 0;
    KEL.typ.int Vl_Event30_Count_ := 0;
    KEL.typ.int Vl_Event365_All_Day_Count_ := 0;
    KEL.typ.int Vl_Event365_Count_ := 0;
    KEL.typ.int Vl_Event7_Active_Flag_ := 0;
    KEL.typ.int Vl_Event7_All_Active_Flag_ := 0;
    KEL.typ.int Vl_Event7_All_Count_ := 0;
    KEL.typ.int Vl_Event7_Count_ := 0;
    KEL.typ.epoch Date_First_Seen_ := 0;
    KEL.typ.epoch Date_Last_Seen_ := 0;
    KEL.typ.int __RecordCount := 0;
  END;
  SHARED __ST28558_Layout __ND894314__Project(__ST880264_Layout __PP894310) := TRANSFORM
    SELF.Contributor_Safe_Flag_ := MAP(__PP894310.C_O_U_N_T___Exp1_ <> 0=>1,0);
    SELF.Dt_First_Seen_ := __PP894310.M_I_N___Event_Date__1_;
    SELF.Dt_Last_Seen_ := __PP894310.M_A_X___Event_Date__1_;
    SELF.Entity_Type_ := 18;
    SELF.Event_Count_ := __PP894310.C_O_U_N_T___Internet_Protocol_Event_;
    SELF.Identity_Count_ := __PP894310.C_O_U_N_T___Person_Ip_Address_;
    __BS894607 := __T(__PP894310.Source_Customers_);
    SELF.In_Customer_Population_ := MAP(EXISTS(__BS894607(__T(__OP2(__T(__PP894310.Source_Customers_)._r_Source_Customer_,=,__PP894310._r_Customer_))))=>1,0);
    SELF.Ip_High_Risk_City_ := MAP(__PP894310.C_O_U_N_T___Exp1__1_ <> 0=>1,0);
    SELF.Ip_Hosted_ := MAP(__PP894310.C_O_U_N_T___Exp1__2_ <> 0=>1,0);
    SELF.Ip_Not_Us_ := MAP(__PP894310.C_O_U_N_T___Exp1__3_ <> 0=>1,0);
    SELF.Ip_Tor_ := MAP(__PP894310.C_O_U_N_T___Exp1__4_ <> 0=>1,0);
    SELF.Ip_Vpn_ := MAP(__PP894310.C_O_U_N_T___Exp1__5_ <> 0=>1,0);
    SELF.Kr_High_Risk_Flag_ := MAP(__PP894310.C_O_U_N_T___Exp1__6_ <> 0=>1,0);
    SELF.Kr_Ip1000_Flag_ := MAP(__PP894310.C_O_U_N_T___Exp1__7_ <> 0=>1,0);
    SELF.Kr_Ip1001_Flag_ := MAP(__PP894310.C_O_U_N_T___Exp1__8_ <> 0=>1,0);
    SELF.Kr_Ip1090_Flag_ := MAP(__PP894310.C_O_U_N_T___Exp1__9_ <> 0=>1,0);
    SELF.Kr_Ip1091_Flag_ := MAP(__PP894310.C_O_U_N_T___Exp1__10_ <> 0=>1,0);
    SELF.Kr_Ip1092_Flag_ := MAP(__PP894310.C_O_U_N_T___Exp1__11_ <> 0=>1,0);
    SELF.Kr_Ip1093_Flag_ := MAP(__PP894310.C_O_U_N_T___Exp1__12_ <> 0=>1,0);
    SELF.Kr_Ip600_Flag_ := MAP(__PP894310.C_O_U_N_T___Exp1__13_ <> 0=>1,0);
    SELF.Kr_Ip601_Flag_ := MAP(__PP894310.C_O_U_N_T___Exp1__14_ <> 0=>1,0);
    SELF.Kr_Ip602_Flag_ := MAP(__PP894310.C_O_U_N_T___Exp1__15_ <> 0=>1,0);
    SELF.Kr_Ip603_Flag_ := MAP(__PP894310.C_O_U_N_T___Exp1__16_ <> 0=>1,0);
    SELF.Kr_Ip604_Flag_ := MAP(__PP894310.C_O_U_N_T___Exp1__17_ <> 0=>1,0);
    SELF.Kr_Ip605_Flag_ := MAP(__PP894310.C_O_U_N_T___Exp1__18_ <> 0=>1,0);
    SELF.Kr_Ip690_Flag_ := MAP(__PP894310.C_O_U_N_T___Exp1__19_ <> 0=>1,0);
    SELF.Kr_Ip691_Flag_ := MAP(__PP894310.C_O_U_N_T___Exp1__20_ <> 0=>1,0);
    SELF.Kr_Ip692_Flag_ := MAP(__PP894310.C_O_U_N_T___Exp1__21_ <> 0=>1,0);
    SELF.Kr_Ip693_Flag_ := MAP(__PP894310.C_O_U_N_T___Exp1__22_ <> 0=>1,0);
    SELF.Kr_Low_Risk_Flag_ := MAP(__PP894310.C_O_U_N_T___Exp1__23_ <> 0=>1,0);
    SELF.Kr_Medium_Risk_Flag_ := MAP(__PP894310.C_O_U_N_T___Exp1__24_ <> 0=>1,0);
    SELF.Last_Event_Date_ := __PP894310.M_A_X___Event_Date__2_;
    SELF.Safe_Flag_ := MAP(__PP894310.C_O_U_N_T___Exp1__25_ <> 0=>1,0);
    SELF.Source_Customer_Count_ := KEL.Aggregates.CountN(__PP894310.Source_Customers_);
    SELF.Vl_Event1_All_Count_ := __PP894310.C_O_U_N_T___Exp1__26_;
    SELF.Vl_Event1_Count_ := __PP894310.C_O_U_N_T___Exp1__27_;
    SELF.Vl_Event30_Active_Flag_ := MAP(__PP894310.Vl_Event30_Count_ > 0=>1,0);
    SELF.Vl_Event30_All_Active_Flag_ := MAP(__PP894310.Vl_Event30_All_Day_Count_ > 0=>1,0);
    SELF.Vl_Event365_All_Day_Count_ := __PP894310.C_O_U_N_T___Exp1__28_;
    SELF.Vl_Event7_Active_Flag_ := MAP(__PP894310.Vl_Event7_Count_ > 0=>1,0);
    SELF.Vl_Event7_All_Active_Flag_ := MAP(__PP894310.Vl_Event7_All_Count_ > 0=>1,0);
    SELF := __PP894310;
  END;
  EXPORT __ENH_Internet_Protocol := PROJECT(__EE894309,__ND894314__Project(LEFT)) : PERSIST('~temp::KEL::FraudgovKEL::Internet_Protocol::Annotated',EXPIRE(7));
  SHARED __EE1379374 := __ENH_Internet_Protocol;
  SHARED IDX_Internet_Protocol_UID_Layout := RECORD
    KEL.typ.uid UID;
    __EE1379374._r_Customer_;
    __EE1379374.Source_Customers_;
    __EE1379374.Ip_Address_;
    __EE1379374.Otto_Ip_Address_Id_;
    __EE1379374._host_;
    __EE1379374._alias_;
    __EE1379374._location_;
    __EE1379374._ip__address_;
    __EE1379374._ip__address__date_;
    __EE1379374._version_;
    __EE1379374._class_;
    __EE1379374._subnet__mask_;
    __EE1379374._reserved_;
    __EE1379374._isp_;
    __EE1379374._v2__validationipproblems_;
    __EE1379374._v2__ipstate_;
    __EE1379374._v2__ipcountry_;
    __EE1379374._v2__ipcontinent_;
    __EE1379374._iprngbeg_;
    __EE1379374._iprngend_;
    __EE1379374._edgecountry_;
    __EE1379374._edgeregion_;
    __EE1379374._edgecity_;
    __EE1379374._edgeconnspeed_;
    __EE1379374._edgemetrocode_;
    __EE1379374._edgelatitude_;
    __EE1379374._edgelongitude_;
    __EE1379374._edgepostalcode_;
    __EE1379374._edgecountrycode_;
    __EE1379374._edgeregioncode_;
    __EE1379374._edgecitycode_;
    __EE1379374._edgecontinentcode_;
    __EE1379374._edgetwolettercountry_;
    __EE1379374._edgeinternalcode_;
    __EE1379374._edgeareacodes_;
    __EE1379374._edgecountryconf_;
    __EE1379374._edgeregionconf_;
    __EE1379374._edgecitycong_;
    __EE1379374._edgepostalconf_;
    __EE1379374._edgegmtoffset_;
    __EE1379374._edgeindst_;
    __EE1379374._siccode_;
    __EE1379374._domainname_;
    __EE1379374._ispname_;
    __EE1379374._homebiztype_;
    __EE1379374._asn_;
    __EE1379374._asnname_;
    __EE1379374._primarylang_;
    __EE1379374._secondarylang_;
    __EE1379374._proxytype_;
    __EE1379374._proxydescription_;
    __EE1379374._isanisp_;
    __EE1379374._companyname_;
    __EE1379374._ranks_;
    __EE1379374._households_;
    __EE1379374._women_;
    __EE1379374._women18to34_;
    __EE1379374._women35to49_;
    __EE1379374._men_;
    __EE1379374._men18to34_;
    __EE1379374._men35to49_;
    __EE1379374._teens_;
    __EE1379374._kids_;
    __EE1379374._naicscode_;
    __EE1379374._cbsacode_;
    __EE1379374._cbsatitle_;
    __EE1379374._cbsatype_;
    __EE1379374._csacode_;
    __EE1379374._csatitle_;
    __EE1379374._mdcode_;
    __EE1379374._mdtitle_;
    __EE1379374._organizationname_;
    __EE1379374.Customer_Id_;
    __EE1379374.Industry_Type_;
    __EE1379374.Source_Customer_Count_;
    __EE1379374.Entity_Context_Uid_;
    __EE1379374.Label_;
    __EE1379374.Entity_Type_;
    __EE1379374.In_Customer_Population_;
    __EE1379374.Dt_First_Seen_;
    __EE1379374.Dt_Last_Seen_;
    __EE1379374.Last_Record_Id_;
    __EE1379374.Identity_Count_;
    __EE1379374.Event_Count_;
    __EE1379374.Ip_Not_Us_;
    __EE1379374.Ip_Vpn_;
    __EE1379374.Ip_High_Risk_City_;
    __EE1379374.Ip_Hosted_;
    __EE1379374.Ip_Tor_;
    __EE1379374.Kr_High_Risk_Flag_;
    __EE1379374.Kr_Medium_Risk_Flag_;
    __EE1379374.Kr_Low_Risk_Flag_;
    __EE1379374.Kr_Flag_;
    __EE1379374.Safe_Flag_;
    __EE1379374.Contributor_Safe_Flag_;
    __EE1379374.Kr_Ip600_Flag_;
    __EE1379374.Kr_Ip601_Flag_;
    __EE1379374.Kr_Ip602_Flag_;
    __EE1379374.Kr_Ip603_Flag_;
    __EE1379374.Kr_Ip604_Flag_;
    __EE1379374.Kr_Ip605_Flag_;
    __EE1379374.Kr_Ip690_Flag_;
    __EE1379374.Kr_Ip691_Flag_;
    __EE1379374.Kr_Ip692_Flag_;
    __EE1379374.Kr_Ip693_Flag_;
    __EE1379374.Kr_Ip1000_Flag_;
    __EE1379374.Kr_Ip1001_Flag_;
    __EE1379374.Kr_Ip1090_Flag_;
    __EE1379374.Kr_Ip1091_Flag_;
    __EE1379374.Kr_Ip1092_Flag_;
    __EE1379374.Kr_Ip1093_Flag_;
    __EE1379374.Last_Event_Date_;
    __EE1379374.Kr_Last_Event_Date_;
    __EE1379374.Kr_Event_After_Last_Known_Risk_Count_;
    __EE1379374.Kr_Event_After_Last_Known_Risk_Flag_;
    __EE1379374.Vl_Event1_All_Count_;
    __EE1379374.Vl_Event7_All_Count_;
    __EE1379374.Vl_Event30_All_Day_Count_;
    __EE1379374.Vl_Event365_All_Day_Count_;
    __EE1379374.Vl_Event7_All_Active_Flag_;
    __EE1379374.Vl_Event30_All_Active_Flag_;
    __EE1379374.Vl_Event1_Count_;
    __EE1379374.Vl_Event7_Count_;
    __EE1379374.Vl_Event30_Count_;
    __EE1379374.Vl_Event365_Count_;
    __EE1379374.Vl_Event7_Active_Flag_;
    __EE1379374.Vl_Event30_Active_Flag_;
    __EE1379374.Date_First_Seen_;
    __EE1379374.Date_Last_Seen_;
    __EE1379374.__RecordCount;
  END;
  SHARED IDX_Internet_Protocol_UID_Projected := PROJECT(__EE1379374,TRANSFORM(IDX_Internet_Protocol_UID_Layout,SELF.UID:=__T(LEFT.UID),SELF:=LEFT));
  EXPORT IDX_Internet_Protocol_UID_Name := '~key::KEL::FraudgovKEL::Internet_Protocol::UID';
  EXPORT IDX_Internet_Protocol_UID := INDEX(IDX_Internet_Protocol_UID_Projected,{UID},{IDX_Internet_Protocol_UID_Projected},IDX_Internet_Protocol_UID_Name);
  EXPORT IDX_Internet_Protocol_UID_Build := BUILD(IDX_Internet_Protocol_UID,OVERWRITE);
  EXPORT __ST1379376_Layout := RECORDOF(IDX_Internet_Protocol_UID);
  EXPORT IDX_Internet_Protocol_UID_Wrapped := PROJECT(IDX_Internet_Protocol_UID,TRANSFORM(__ST28558_Layout,SELF.UID := __CN(LEFT.UID),SELF:=LEFT));
  EXPORT BuildAll := PARALLEL(IDX_Internet_Protocol_UID_Build);
END;
