Generated by SALT V3.5.3
Command line options: -MScrubs_DL_MI -eC:\Users\wolfkg\AppData\Local\Temp\TFR2DB1.tmp 
File being processed :-
OPTIONS:-gh
MODULE:Scrubs_DL_MI
FILENAME:In_MI
// Uncomment up to NINES for internal or external adl
// IDFIELD:EXISTS:<NameOfIDField>
// RIDFIELD:<NameOfRidField>
// RECORDS:<NumberOfRecordsInDataFile>
// POPULATION:<ExpectedNumberOfEntitiesInDataFile>
// NINES:<Precision required 3 = 99.9%, 2 = 99% etc>
// Uncomment Process if doing external adl
// PROCESS:<ProcessName>
// FIELDTYPE statements can be used to clean up (or check the cleaning) of individual fields
// BESTTYPE statements declare methods of generating the best value for a given cluster; this can also improve linking
// FUZZY can be used to create new types of FUZZY linking
// Remember to generate specificities and update the 0,0 placeholders below before running any sort of linking.
// If the actual specificity for a field is <1, round it up to 1 rather than down to 0.  If your cluster is running
// a shared repository, calling SALTTOOLS30.mac_Patch_SPC from the bottom of BWR_Specificities may be a convenience.
 
//FIELDTYPE DEFINITIONS
FIELDTYPE:invalid_mandatory:LENGTHS(1..)
FIELDTYPE:invalid_alpha:ALLOW(ABCDEFGHIJKLMNOPQRSTUVWXYZ)
FIELDTYPE:invalid_alpha_specials:ALLOW(ABCDEFGHIJKLMNOPQRSTUVWXYZ @-.,#)
FIELDTYPE:invalid_numeric:ALLOW(0123456789)
FIELDTYPE:invalid_numeric_nonblank:ALLOW(0123456789)
FIELDTYPE:invalid_alpha_num:ALLOW(0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ)
FIELDTYPE:invalid_empty:LENGTHS(0)
FIELDTYPE:invalid_wordbag:CAPS:ALLOW(ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789):SPACES( <>{}[]()-^=!+&,./#*'\|")
FIELDTYPE:invalid_8pastdate:LENGTHS(8):CUSTOM(Scrubs.fn_valid_pastDate>0)
 
FIELDTYPE:invalid_orig_reccode:ENUM(A|C|D)
FIELDTYPE:invalid_orig_clientidnum:LENGTHS(10):LIKE(invalid_numeric)
FIELDTYPE:invalid_dlnum_pid:LENGTHS(0,13):CUSTOM(Scrubs_DL_MI.Functions.fn_check_dl_number>0)
FIELDTYPE:invalid_orig_name:LENGTHS(1..)
FIELDTYPE:invalid_state:CUSTOM(Scrubs_DL_MI.Functions.fn_verify_state>0)
FIELDTYPE:invalid_zip:LENGTHS(5):LIKE(invalid_numeric)
FIELDTYPE:invalid_orig_dob:LENGTHS(8):CUSTOM(Scrubs_DL_MI.Functions.fn_valid_past_date>0)
FIELDTYPE:invalid_orig_sex:ENUM(F|M)
FIELDTYPE:invalid_orig_county:LENGTHS(2):CUSTOM(Scrubs_DL_MI.Functions.fn_verify_county>0)
FIELDTYPE:invalid_orig_dlnorpidindicator:CUSTOM(Scrubs_DL_MI.Functions.fn_verify_indicator>0,orig_dlnum,orig_personalidnum)
FIELDTYPE:invalid_clean_name:CUSTOM(Scrubs_DL_MI.Functions.fn_valid_name>0,clean_name_first,clean_name_middle)
FIELDTYPE:invalid_addr_type:ALLOW(M):LENGTHS(0,1)
 
//FIELD DEFINITIONS
FIELD:append_process_date:TYPE(STRING8):LIKE(invalid_8pastdate):0,0
FIELD:orig_reccode:TYPE(STRING1):LIKE(invalid_orig_reccode):0,0
FIELD:orig_clientidnum:TYPE(STRING10):LIKE(invalid_orig_clientidnum):0,0
FIELD:orig_dlnum:TYPE(STRING13):LIKE(invalid_dlnum_pid):0,0
FIELD:orig_personalidnum:TYPE(STRING13):LIKE(invalid_dlnum_pid):0,0
FIELD:orig_name:TYPE(STRING36):LIKE(invalid_orig_name):0,0
FIELD:orig_street:TYPE(STRING36):LIKE(invalid_wordbag):0,0
FIELD:orig_city:TYPE(STRING19):LIKE(invalid_alpha_specials):0,0
FIELD:orig_state:TYPE(STRING2):LIKE(invalid_state):0,0
FIELD:orig_zip:TYPE(STRING5):LIKE(invalid_zip):0,0
FIELD:orig_dob:TYPE(STRING8):LIKE(invalid_orig_dob):0,0
FIELD:orig_sex:TYPE(STRING1):LIKE(invalid_orig_sex):0,0
FIELD:orig_county:TYPE(STRING2):LIKE(invalid_orig_county):0,0
FIELD:orig_dlnorpidindicator:TYPE(STRING1):LIKE(invalid_orig_dlnorpidindicator):0,0
FIELD:orig_mailingstreet:TYPE(STRING36):LIKE(invalid_wordbag):0,0
FIELD:orig_mailingcity:TYPE(STRING19):LIKE(invalid_alpha_specials):0,0
FIELD:orig_mailingstate:TYPE(STRING2):LIKE(invalid_state):0,0
FIELD:orig_mailingzip:TYPE(STRING5):LIKE(invalid_zip):0,0
FIELD:orig_optoutindicator:TYPE(STRING1):0,0
FIELD:orig_lf:TYPE(STRING1):0,0
FIELD:clean_name_prefix:TYPE(STRING5):LIKE(invalid_alpha_specials):0,0
FIELD:clean_name_first:TYPE(STRING20):LIKE(invalid_wordbag):0,0
FIELD:clean_name_middle:TYPE(STRING20):LIKE(invalid_wordbag):0,0
FIELD:clean_name_last:TYPE(STRING20):LIKE(invalid_clean_name):0,0
FIELD:clean_name_suffix:TYPE(STRING5):LIKE(invalid_wordbag):0,0
FIELD:clean_name_score:TYPE(STRING3):0,0
FIELD:clean_prim_range:TYPE(STRING10):0,0
FIELD:clean_predir:TYPE(STRING2):0,0
FIELD:clean_prim_name:TYPE(STRING28):0,0
FIELD:clean_addr_suffix:TYPE(STRING4):0,0
FIELD:clean_postdir:TYPE(STRING2):0,0
FIELD:clean_unit_desig:TYPE(STRING10):0,0
FIELD:clean_sec_range:TYPE(STRING8):0,0
FIELD:clean_p_city_name:TYPE(STRING25):0,0
FIELD:clean_v_city_name:TYPE(STRING25):0,0
FIELD:clean_st:TYPE(STRING2):0,0
FIELD:clean_zip:TYPE(STRING5):0,0
FIELD:clean_zip4:TYPE(STRING4):0,0
FIELD:clean_cart:TYPE(STRING4):0,0
FIELD:clean_cr_sort_sz:TYPE(STRING1):0,0
FIELD:clean_lot:TYPE(STRING4):0,0
FIELD:clean_lot_order:TYPE(STRING1):0,0
FIELD:clean_dpbc:TYPE(STRING2):0,0
FIELD:clean_chk_digit:TYPE(STRING1):0,0
FIELD:clean_record_type:TYPE(STRING2):0,0
FIELD:clean_ace_fips_st:TYPE(STRING2):0,0
FIELD:clean_fipscounty:TYPE(STRING3):0,0
FIELD:clean_geo_lat:TYPE(STRING10):0,0
FIELD:clean_geo_long:TYPE(STRING11):0,0
FIELD:clean_msa:TYPE(STRING4):0,0
FIELD:clean_geo_blk:TYPE(STRING7):0,0
FIELD:clean_geo_match:TYPE(STRING1):0,0
FIELD:clean_err_stat:TYPE(STRING4):0,0
FIELD:addr_type:TYPE(STRING1):LIKE(invalid_addr_type):0,0
// CONCEPT statements should be used to group together interellated fields; such as address
// RELATIONSHIP is used to find non-obvious relationships between the clusters
// SOURCEFIELD is used if a field of the file denotes a source of the records in that file
// LINKPATH is used to define access paths for external linking
 
Total available specificity:0
Search Threshold set at -4
Use of PERSISTs in code set at:3
 
__Glossary__
Edit Distance: An edit distance of (say) one implies that one string can be converted into another by doing one of
  - Changing one character
  - Deleting one character
  - Transposing two characters
 
Forcing Criteria: In addition to the general 'best match' logic it is possible to insist that
one particular field must match to some degree or the whole record is considered a bad match.
The criterial applied to that one field is the forcing criteria.
 
Cascade: Best Type rules are applied in such a way that the rules are applied one by one UNTIL the first rule succeeds; subsequent rules are then skipped.
 
__General Notes__
How is it decided how much to subtract for a bad match?
SALT computes for each field the percentage likelihood that a valid cluster will have two or more values for a given field
this value (called the switch value in the SALT literature) is then used to produce the subtraction value from the match value.
The value in this document is the one typed into the SPC file; the code will use a value computed at run-time.
 
