export layout_BK_search_history_in := record
  string1     source;
  string8     process_date;
  string50    TMSID ;
  string10    seq_number;
  string5 	  court_code;
  string7 	  case_number;
  string25    orig_case_number;
  string2 	  debtor_type ;
  string3	  debtor_seq;
  string9 	  ssn ;
  string9     tax_id ; 
  string2     name_type; 
  string200   orig_name ; 
  string50	  orig_fname ;
  string30	  orig_mname  ;
  string50	  orig_lname ;
  string5 	  orig_name_suffix ;
  string150   orig_company ;
  string80	  orig_addr1 ;
  string80	  orig_addr2 ;
  string80    orig_city ;
  string2     orig_st ; 
  string5     orig_zip5 ; 
  string4     orig_zip4 ; 
  string10    phone ; 
  string150   cname; 
  string73	  clean_name;
  string182   clean_address;
  string8     date_last_seen ; 
  string8     date_first_seen ;  
  string12 	  DID  ;
  string9 	  debtor_ssn  ;
  string3  	  debtor_DID_score ;
  string12	  bdid  ;
  string1	  GLB_flag ; 
  string1     lf ; 
end;