export Layout_6000_Inquiries_In := 
record
   string8 process_date;
   string10 FILE_NUMBER;
   string4 SEGMENT_CODE;
   string5 SEQUENCE_NUMBER;
   string4 BUS_CODE;
   string10 BUS_DESC;
   string2 INQ_MM_1;
   string2 INQ_YY_1;
   string3 INQ_COUNT_1;
   string2 INQ_MM_2;
   string2 INQ_YY_2;
   string3 INQ_COUNT_2;
   string2 INQ_MM_3;
   string2 INQ_YY_3;
   string3 INQ_COUNT_3;
   string2 INQ_MM_4;
   string2 INQ_YY_4;
   string3 INQ_COUNT_4;
   string2 INQ_MM_5;
   string2 INQ_YY_5;
   string3 INQ_COUNT_5;
   string2 INQ_MM_6;
   string2 INQ_YY_6;
   string3 INQ_COUNT_6;
   string2 INQ_MM_7;
   string2 INQ_YY_7;
   string3 INQ_COUNT_7;
   string2 INQ_MM_8;
   string2 INQ_YY_8;
   string3 INQ_COUNT_8;
   string2 INQ_MM_9;
   string2 INQ_YY_9;
   string3 INQ_COUNT_9;
   string1 lf;
end;