export Layout_4510_UCC_Filings_In := 
record
   string8 process_date;
   string10 FILE_NUMBER;
   string4 SEGMENT_CODE;
   string5 SEQUENCE_NUMBER;
   string6 orig_DATE_FILED_YYMMDD;
   string2 TYPE_CODE;
   string10 TYPE_DESC;
   string2 ACTION_CODE;
   string10 ACTION_DESC;
   string16 DOCUMENT_NUMBER;
   string20 FILING_LOCATION;
   string1 COLL_CODE1;
   string36 COLL_DESC1;
   string1 COLL_CODE2;
   string36 COLL_DESC2;
   string1 COLL_CODE3;
   string36 COLL_DESC3;
   string1 COLL_CODE4;
   string36 COLL_DESC4;
   string1 COLL_CODE5;
   string36 COLL_DESC5;
   string1 COLL_CODE6;
   string36 COLL_DESC6;
   string7 ADDTNL_COLL_CODES;
   string60 SECURED_PARTY;
   string60 ASSIGNEE;
   string2 ORIG_FILE_STATE_CODE;
   string20 ORIG_FILE_STATE_DESC;
   string16 ORIG_FILE_NUMBER;
   string1 DISPUTE_IND;
   string2 DISPUTE_CODE;
   string8 date_filed;
   string1 lf := '';
end;