// Machine-readable versions of the spec file and subsets thereof
IMPORT SALT311;
EXPORT Voters_GenerationMod := MODULE(SALT311.iGenerationMod)
 
  // SALT Version info
  EXPORT salt_VERSION := 'V3.11.9';
  EXPORT salt_MODULE := 'SALT311'; // Optional override by HACK:SALTMODULE
  EXPORT salt_TOOLSMODULE := 'SALTTOOLS30'; // Optional override by HACK:SALTTOOLSMODULE
 
  // Core module configuration values
  EXPORT spc_MODULE := 'Scrubs_eMerges';
  EXPORT spc_NAMESCOPE := 'Voters';
  EXPORT spc_PROCESS := '';
  EXPORT spc_PROCLAYOUTS := 'Process__Layouts';
  EXPORT spc_IDNAME := ''; // cluster id (input)
  EXPORT spc_IDFIELD := ''; // cluster id (output)
  EXPORT spc_RIDFIELD := ''; // record id
  EXPORT spc_CONFIG := 'Config';
  EXPORT spc_CONFIGPARAM := FALSE;
  EXPORT spc_SOURCEFIELD := '';
  EXPORT spc_FILEPREFIX := 'In_';
  EXPORT spc_FILENAME := 'eMerges';
  EXPORT spc_INGESTSTATUS := '';
  EXPORT spc_EXTERNAL_MAPPING := 'UniqueID:';
  EXPORT spc_EXTERNAL_BATCH_PARAM := ',/* MY_ */,process_date,date_first_seen,date_last_seen,score,best_ssn,did_out,source,file_id,vendor_id,source_state,source_code,file_acquired_date,_use,title_in,lname_in,fname_in,mname_in,maiden_prior,name_suffix_in,votefiller,source_voterid,dob,agecat,headhousehold,place_of_birth,occupation,maiden_name,motorvoterid,regsource,regdate,race,gender,poliparty,poliparty_mapped,phone,work_phone,other_phone,active_status,active_status_mapped,votefiller2,active_other,voterstatus,voterstatus_mapped,resaddr1,resaddr2,res_city,res_state,res_zip,res_county,mail_addr1,mail_addr2,mail_city,mail_state,mail_zip,mail_county,addr_filler1,addr_filler2,city_filler,state_filler,zip_filler,county_filler,towncode,distcode,countycode,schoolcode,cityinout,spec_dist1,spec_dist2,precinct1,precinct2,precinct3,villageprecinct,schoolprecinct,ward,precinct_citytown,ancsmdindc,citycouncildist,countycommdist,statehouse,statesenate,ushouse,elemschooldist,schooldist,schoolfiller,commcolldist,dist_filler,municipal,villagedist,policejury,policedist,publicservcomm,rescue,fire,sanitary,sewerdist,waterdist,mosquitodist,taxdist,supremecourt,justiceofpeace,judicialdist,superiorctdist,appealsct,courtfiller,contributorparty,recptparty,dateofcontr,dollaramt,officecontto,cumuldollaramt,contfiller1,contfiller2,conttype,contfiller3,primary02,special02,other02,special202,general02,primary01,special01,other01,special201,general01,pres00,primary00,special00,other00,special200,general00,primary99,special99,other99,special299,general99,primary98,special98,other98,special298,general98,primary97,special97,other97,special297,general97,pres96,primary96,special96,other96,special296,general96,lastdayvote,title,fname,mname,lname,name_suffix,score_on_input,prim_range,predir,prim_name,suffix,postdir,unit_desig,sec_range,p_city_name,city_name,st,zip,zip4,cart,cr_sort_sz,lot,lot_order,dpbc,chk_digit,record_type,ace_fips_st,county,county_name,geo_lat,geo_long,msa,geo_blk,geo_match,err_stat,mail_prim_range,mail_predir,mail_prim_name,mail_addr_suffix,mail_postdir,mail_unit_desig,mail_sec_range,mail_p_city_name,mail_v_city_name,mail_st,mail_ace_zip,mail_zip4,mail_cart,mail_cr_sort_sz,mail_lot,mail_lot_order,mail_dpbc,mail_chk_digit,mail_record_type,mail_ace_fips_st,mail_fipscounty,mail_geo_lat,mail_geo_long,mail_msa,mail_geo_blk,mail_geo_match,mail_err_stat';
  EXPORT spc_HAS_TWOSTEP := FALSE;
  EXPORT spc_HAS_PARTITION := FALSE;
  EXPORT spc_HAS_FIELDTYPES := TRUE;
  EXPORT spc_HAS_INCREMENTAL := FALSE;
  EXPORT spc_HAS_ASOF := FALSE;
  EXPORT spc_HAS_NONCONTIGUOUS := FALSE;
  EXPORT spc_HAS_SUPERFILES := FALSE;
  EXPORT spc_HAS_CONSISTENT := FALSE;
  EXPORT spc_HAS_EXTERNAL := FALSE;
  EXPORT spc_HAS_PARENTS := FALSE;
  EXPORT spc_HAS_FORCE := FALSE;
  EXPORT spc_HAS_BLOCKLINK := FALSE;
 
  // The entire spec file
  EXPORT spcString :=
    'OPTIONS:-gh\n'
    + 'MODULE:Scrubs_eMerges\n'
    + 'FILENAME:eMerges\n'
    + 'NAMESCOPE:Voters\n'
    + '\n'
    + 'FIELDTYPE:Invalid_No:ALLOW(0123456789 )\n'
    + 'FIELDTYPE:Invalid_Float:ALLOW(0123456789 .-/)\n'
    + 'FIELDTYPE:Invalid_Alpha:ALLOW(abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ .\'-)\n'
    + 'FIELDTYPE:Invalid_AlphaNum:ALLOW(0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ .\'-)\n'
    + 'FIELDTYPE:Invalid_Date:CUSTOM(Scrubs.fn_valid_date>0)\n'
    + 'FIELDTYPE:Invalid_State:LIKE(Invalid_Alpha):LENGTHS(0,2)\n'
    + 'FIELDTYPE:Invalid_Zip:LIKE(Invalid_Float):LENGTHS(0,5,9,10)\n'
    + '\n'
    + 'FIELD:process_date:TYPE(STRING8):LIKE(Invalid_Date):0,0\n'
    + 'FIELD:date_first_seen:TYPE(STRING8):LIKE(Invalid_Date):0,0\n'
    + 'FIELD:date_last_seen:TYPE(STRING8):LIKE(Invalid_Date):0,0\n'
    + 'FIELD:score:TYPE(STRING3):LIKE(Invalid_No):0,0\n'
    + 'FIELD:best_ssn:TYPE(STRING9):LIKE(Invalid_Float):0,0\n'
    + 'FIELD:did_out:TYPE(STRING12):LIKE(Invalid_No):0,0\n'
    + 'FIELD:source:TYPE(STRING7):0,0\n'
    + 'FIELD:file_id:TYPE(STRING4):LIKE(Invalid_Alpha):0,0\n'
    + 'FIELD:vendor_id:TYPE(STRING13):0,0\n'
    + 'FIELD:source_state:TYPE(STRING2):LIKE(Invalid_State):0,0\n'
    + 'FIELD:source_code:TYPE(STRING2):LIKE(Invalid_Alpha):0,0\n'
    + 'FIELD:file_acquired_date:TYPE(STRING8):LIKE(Invalid_Date):0,0\n'
    + 'FIELD:_use:TYPE(STRING2):LIKE(Invalid_AlphaNum):0,0\n'
    + 'FIELD:title_in:TYPE(STRING10):LIKE(Invalid_Alpha):0,0\n'
    + 'FIELD:lname_in:TYPE(STRING30):LIKE(Invalid_Alpha):0,0\n'
    + 'FIELD:fname_in:TYPE(STRING30):LIKE(Invalid_Alpha):0,0\n'
    + 'FIELD:mname_in:TYPE(STRING30):LIKE(Invalid_Alpha):0,0\n'
    + 'FIELD:maiden_prior:TYPE(STRING30):LIKE(Invalid_Alpha):0,0\n'
    + 'FIELD:name_suffix_in:TYPE(STRING3):LIKE(Invalid_AlphaNum):0,0\n'
    + 'FIELD:votefiller:TYPE(STRING15):0,0\n'
    + 'FIELD:source_voterid:TYPE(STRING12):LIKE(Invalid_No):0,0\n'
    + 'FIELD:dob:TYPE(STRING8):LIKE(Invalid_Date):0,0\n'
    + 'FIELD:agecat:TYPE(STRING2):LIKE(Invalid_No):0,0\n'
    + 'FIELD:headhousehold:TYPE(STRING2):LIKE(Invalid_Alpha):0,0\n'
    + 'FIELD:place_of_birth:TYPE(STRING18):LIKE(Invalid_Date):0,0\n'
    + 'FIELD:occupation:TYPE(STRING30):LIKE(Invalid_Alpha):0,0\n'
    + 'FIELD:maiden_name:TYPE(STRING30):LIKE(Invalid_Alpha):0,0\n'
    + 'FIELD:motorvoterid:TYPE(STRING15):LIKE(Invalid_No):0,0\n'
    + 'FIELD:regsource:TYPE(STRING10):LIKE(Invalid_Alpha):0,0\n'
    + 'FIELD:regdate:TYPE(STRING8):LIKE(Invalid_Date):0,0\n'
    + 'FIELD:race:TYPE(STRING2):LIKE(Invalid_Alpha):0,0\n'
    + 'FIELD:gender:TYPE(STRING1):LIKE(Invalid_Alpha):0,0\n'
    + 'FIELD:poliparty:TYPE(STRING2):LIKE(Invalid_No):0,0\n'
    + 'FIELD:poliparty_mapped:TYPE(STRING25):LIKE(Invalid_Alpha):0,0\n'
    + 'FIELD:phone:TYPE(STRING10):LIKE(Invalid_Float):0,0\n'
    + 'FIELD:work_phone:TYPE(STRING10):LIKE(Invalid_Float):0,0\n'
    + 'FIELD:other_phone:TYPE(STRING10):LIKE(Invalid_Float):0,0\n'
    + 'FIELD:active_status:TYPE(STRING1):LIKE(Invalid_Alpha):0,0\n'
    + 'FIELD:active_status_mapped:TYPE(STRING20):LIKE(Invalid_Alpha):0,0\n'
    + 'FIELD:votefiller2:TYPE(STRING1):0,0\n'
    + 'FIELD:active_other:TYPE(STRING1):LIKE(Invalid_AlphaNum):0,0\n'
    + 'FIELD:voterstatus:TYPE(STRING2):LIKE(Invalid_AlphaNum):0,0\n'
    + 'FIELD:voterstatus_mapped:TYPE(STRING50):LIKE(Invalid_AlphaNum):0,0\n'
    + 'FIELD:resaddr1:TYPE(STRING40):LIKE(Invalid_AlphaNum):0,0\n'
    + 'FIELD:resaddr2:TYPE(STRING40):LIKE(Invalid_AlphaNum):0,0\n'
    + 'FIELD:res_city:TYPE(STRING40):LIKE(Invalid_Alpha):0,0\n'
    + 'FIELD:res_state:TYPE(STRING2):LIKE(Invalid_State):0,0\n'
    + 'FIELD:res_zip:TYPE(STRING9):LIKE(Invalid_Zip):0,0\n'
    + 'FIELD:res_county:TYPE(STRING3):LIKE(Invalid_AlphaNum):0,0\n'
    + 'FIELD:mail_addr1:TYPE(STRING40):LIKE(Invalid_AlphaNum):0,0\n'
    + 'FIELD:mail_addr2:TYPE(STRING40):LIKE(Invalid_AlphaNum):0,0\n'
    + 'FIELD:mail_city:TYPE(STRING40):LIKE(Invalid_Alpha):0,0\n'
    + 'FIELD:mail_state:TYPE(STRING2):LIKE(Invalid_State):0,0\n'
    + 'FIELD:mail_zip:TYPE(STRING9):LIKE(Invalid_Zip):0,0\n'
    + 'FIELD:mail_county:TYPE(STRING3):LIKE(Invalid_No):0,0\n'
    + 'FIELD:addr_filler1:TYPE(STRING40):0,0\n'
    + 'FIELD:addr_filler2:TYPE(STRING40):0,0\n'
    + 'FIELD:city_filler:TYPE(STRING40):0,0\n'
    + 'FIELD:state_filler:TYPE(STRING2):0,0\n'
    + 'FIELD:zip_filler:TYPE(STRING9):0,0\n'
    + 'FIELD:county_filler:TYPE(STRING3):0,0\n'
    + 'FIELD:towncode:TYPE(STRING5):LIKE(Invalid_AlphaNum):0,0\n'
    + 'FIELD:distcode:TYPE(STRING5):LIKE(Invalid_AlphaNum):0,0\n'
    + 'FIELD:countycode:TYPE(STRING5):LIKE(Invalid_AlphaNum):0,0\n'
    + 'FIELD:schoolcode:TYPE(STRING5):LIKE(Invalid_AlphaNum):0,0\n'
    + 'FIELD:cityinout:TYPE(STRING1):LIKE(Invalid_AlphaNum):0,0\n'
    + 'FIELD:spec_dist1:TYPE(STRING20):LIKE(Invalid_AlphaNum):0,0\n'
    + 'FIELD:spec_dist2:TYPE(STRING20):LIKE(Invalid_AlphaNum):0,0\n'
    + 'FIELD:precinct1:TYPE(STRING7):LIKE(Invalid_AlphaNum):0,0\n'
    + 'FIELD:precinct2:TYPE(STRING7):LIKE(Invalid_AlphaNum):0,0\n'
    + 'FIELD:precinct3:TYPE(STRING7):LIKE(Invalid_AlphaNum):0,0\n'
    + 'FIELD:villageprecinct:TYPE(STRING7):LIKE(Invalid_AlphaNum):0,0\n'
    + 'FIELD:schoolprecinct:TYPE(STRING7):LIKE(Invalid_AlphaNum):0,0\n'
    + 'FIELD:ward:TYPE(STRING7):LIKE(Invalid_AlphaNum):0,0\n'
    + 'FIELD:precinct_citytown:TYPE(STRING7):LIKE(Invalid_AlphaNum):0,0\n'
    + 'FIELD:ancsmdindc:TYPE(STRING7):LIKE(Invalid_AlphaNum):0,0\n'
    + 'FIELD:citycouncildist:TYPE(STRING4):LIKE(Invalid_AlphaNum):0,0\n'
    + 'FIELD:countycommdist:TYPE(STRING4):LIKE(Invalid_AlphaNum):0,0\n'
    + 'FIELD:statehouse:TYPE(STRING3):LIKE(Invalid_AlphaNum):0,0\n'
    + 'FIELD:statesenate:TYPE(STRING3):LIKE(Invalid_AlphaNum):0,0\n'
    + 'FIELD:ushouse:TYPE(STRING3):LIKE(Invalid_AlphaNum):0,0\n'
    + 'FIELD:elemschooldist:TYPE(STRING4):LIKE(Invalid_AlphaNum):0,0\n'
    + 'FIELD:schooldist:TYPE(STRING4):LIKE(Invalid_AlphaNum):0,0\n'
    + 'FIELD:schoolfiller:TYPE(STRING5):0,0\n'
    + 'FIELD:commcolldist:TYPE(STRING4):LIKE(Invalid_AlphaNum):0,0\n'
    + 'FIELD:dist_filler:TYPE(STRING5):0,0\n'
    + 'FIELD:municipal:TYPE(STRING4):LIKE(Invalid_AlphaNum):0,0\n'
    + 'FIELD:villagedist:TYPE(STRING4):LIKE(Invalid_AlphaNum):0,0\n'
    + 'FIELD:policejury:TYPE(STRING4):LIKE(Invalid_AlphaNum):0,0\n'
    + 'FIELD:policedist:TYPE(STRING4):LIKE(Invalid_AlphaNum):0,0\n'
    + 'FIELD:publicservcomm:TYPE(STRING4):LIKE(Invalid_AlphaNum):0,0\n'
    + 'FIELD:rescue:TYPE(STRING4):LIKE(Invalid_No):0,0\n'
    + 'FIELD:fire:TYPE(STRING4):LIKE(Invalid_No):0,0\n'
    + 'FIELD:sanitary:TYPE(STRING4):LIKE(Invalid_Alpha):0,0\n'
    + 'FIELD:sewerdist:TYPE(STRING4):LIKE(Invalid_No):0,0\n'
    + 'FIELD:waterdist:TYPE(STRING4):LIKE(Invalid_No):0,0\n'
    + 'FIELD:mosquitodist:TYPE(STRING4):LIKE(Invalid_No):0,0\n'
    + 'FIELD:taxdist:TYPE(STRING4):LIKE(Invalid_No):0,0\n'
    + 'FIELD:supremecourt:TYPE(STRING4):LIKE(Invalid_No):0,0\n'
    + 'FIELD:justiceofpeace:TYPE(STRING4):LIKE(Invalid_AlphaNum):0,0\n'
    + 'FIELD:judicialdist:TYPE(STRING4):LIKE(Invalid_AlphaNum):0,0\n'
    + 'FIELD:superiorctdist:TYPE(STRING4):LIKE(Invalid_AlphaNum):0,0\n'
    + 'FIELD:appealsct:TYPE(STRING4):LIKE(Invalid_AlphaNum):0,0\n'
    + 'FIELD:courtfiller:TYPE(STRING4):0,0\n'
    + 'FIELD:contributorparty:TYPE(STRING2):LIKE(Invalid_Alpha):0,0\n'
    + 'FIELD:recptparty:TYPE(STRING2):LIKE(Invalid_No):0,0\n'
    + 'FIELD:dateofcontr:TYPE(STRING8):LIKE(Invalid_Date):0,0\n'
    + 'FIELD:dollaramt:TYPE(STRING7):LIKE(Invalid_No):0,0\n'
    + 'FIELD:officecontto:TYPE(STRING3):0,0\n'
    + 'FIELD:cumuldollaramt:TYPE(STRING7):0,0\n'
    + 'FIELD:contfiller1:TYPE(STRING21):0,0\n'
    + 'FIELD:contfiller2:TYPE(STRING21):0,0\n'
    + 'FIELD:conttype:TYPE(STRING5):0,0\n'
    + 'FIELD:contfiller3:TYPE(STRING15):0,0\n'
    + 'FIELD:primary02:TYPE(STRING2):LIKE(Invalid_Alpha):0,0\n'
    + 'FIELD:special02:TYPE(STRING2):LIKE(Invalid_Alpha):0,0\n'
    + 'FIELD:other02:TYPE(STRING2):LIKE(Invalid_Alpha):0,0\n'
    + 'FIELD:special202:TYPE(STRING2):LIKE(Invalid_Alpha):0,0\n'
    + 'FIELD:general02:TYPE(STRING2):LIKE(Invalid_Alpha):0,0\n'
    + 'FIELD:primary01:TYPE(STRING2):LIKE(Invalid_Alpha):0,0\n'
    + 'FIELD:special01:TYPE(STRING2):LIKE(Invalid_Alpha):0,0\n'
    + 'FIELD:other01:TYPE(STRING2):LIKE(Invalid_Alpha):0,0\n'
    + 'FIELD:special201:TYPE(STRING2):LIKE(Invalid_Alpha):0,0\n'
    + 'FIELD:general01:TYPE(STRING2):LIKE(Invalid_Alpha):0,0\n'
    + 'FIELD:pres00:TYPE(STRING2):LIKE(Invalid_Alpha):0,0\n'
    + 'FIELD:primary00:TYPE(STRING2):LIKE(Invalid_Alpha):0,0\n'
    + 'FIELD:special00:TYPE(STRING2):LIKE(Invalid_Alpha):0,0\n'
    + 'FIELD:other00:TYPE(STRING2):LIKE(Invalid_Alpha):0,0\n'
    + 'FIELD:special200:TYPE(STRING2):LIKE(Invalid_Alpha):0,0\n'
    + 'FIELD:general00:TYPE(STRING2):LIKE(Invalid_Alpha):0,0\n'
    + 'FIELD:primary99:TYPE(STRING2):LIKE(Invalid_Alpha):0,0\n'
    + 'FIELD:special99:TYPE(STRING2):LIKE(Invalid_Alpha):0,0\n'
    + 'FIELD:other99:TYPE(STRING2):LIKE(Invalid_Alpha):0,0\n'
    + 'FIELD:special299:TYPE(STRING2):LIKE(Invalid_Alpha):0,0\n'
    + 'FIELD:general99:TYPE(STRING2):LIKE(Invalid_Alpha):0,0\n'
    + 'FIELD:primary98:TYPE(STRING2):LIKE(Invalid_Alpha):0,0\n'
    + 'FIELD:special98:TYPE(STRING2):LIKE(Invalid_Alpha):0,0\n'
    + 'FIELD:other98:TYPE(STRING2):LIKE(Invalid_Alpha):0,0\n'
    + 'FIELD:special298:TYPE(STRING2):LIKE(Invalid_Alpha):0,0\n'
    + 'FIELD:general98:TYPE(STRING2):LIKE(Invalid_Alpha):0,0\n'
    + 'FIELD:primary97:TYPE(STRING2):LIKE(Invalid_Alpha):0,0\n'
    + 'FIELD:special97:TYPE(STRING2):LIKE(Invalid_Alpha):0,0\n'
    + 'FIELD:other97:TYPE(STRING2):LIKE(Invalid_Alpha):0,0\n'
    + 'FIELD:special297:TYPE(STRING2):LIKE(Invalid_Alpha):0,0\n'
    + 'FIELD:general97:TYPE(STRING2):LIKE(Invalid_Alpha):0,0\n'
    + 'FIELD:pres96:TYPE(STRING2):LIKE(Invalid_Alpha):0,0\n'
    + 'FIELD:primary96:TYPE(STRING2):LIKE(Invalid_Alpha):0,0\n'
    + 'FIELD:special96:TYPE(STRING2):LIKE(Invalid_Alpha):0,0\n'
    + 'FIELD:other96:TYPE(STRING2):LIKE(Invalid_Alpha):0,0\n'
    + 'FIELD:special296:TYPE(STRING2):LIKE(Invalid_Alpha):0,0\n'
    + 'FIELD:general96:TYPE(STRING2):LIKE(Invalid_Alpha):0,0\n'
    + 'FIELD:lastdayvote:TYPE(STRING8):LIKE(Invalid_Date):0,0\n'
    + 'FIELD:title:TYPE(STRING5):LIKE(Invalid_Alpha):0,0\n'
    + 'FIELD:fname:TYPE(STRING20):LIKE(Invalid_Alpha):0,0\n'
    + 'FIELD:mname:TYPE(STRING20):LIKE(Invalid_Alpha):0,0\n'
    + 'FIELD:lname:TYPE(STRING20):LIKE(Invalid_Alpha):0,0\n'
    + 'FIELD:name_suffix:TYPE(STRING5):LIKE(Invalid_Alpha):0,0\n'
    + 'FIELD:score_on_input:TYPE(STRING3):LIKE(Invalid_No):0,0\n'
    + 'FIELD:prim_range:TYPE(STRING10):LIKE(Invalid_No):0,0\n'
    + 'FIELD:predir:TYPE(STRING2):LIKE(Invalid_Alpha):0,0\n'
    + 'FIELD:prim_name:TYPE(STRING28):LIKE(Invalid_AlphaNum):0,0\n'
    + 'FIELD:suffix:TYPE(STRING4):LIKE(Invalid_Alpha):0,0\n'
    + 'FIELD:postdir:TYPE(STRING2):LIKE(Invalid_Alpha):0,0\n'
    + 'FIELD:unit_desig:TYPE(STRING10):LIKE(Invalid_Alpha):0,0\n'
    + 'FIELD:sec_range:TYPE(STRING8):LIKE(Invalid_AlphaNum):0,0\n'
    + 'FIELD:p_city_name:TYPE(STRING25):LIKE(Invalid_Alpha):0,0\n'
    + 'FIELD:city_name:TYPE(STRING25):LIKE(Invalid_Alpha):0,0\n'
    + 'FIELD:st:TYPE(STRING2):LIKE(Invalid_Alpha):0,0\n'
    + 'FIELD:zip:TYPE(STRING5):LIKE(Invalid_Zip):0,0\n'
    + 'FIELD:zip4:TYPE(STRING4):LIKE(Invalid_No):0,0\n'
    + 'FIELD:cart:TYPE(STRING4):LIKE(Invalid_AlphaNum):0,0\n'
    + 'FIELD:cr_sort_sz:TYPE(STRING1):LIKE(Invalid_Alpha):0,0\n'
    + 'FIELD:lot:TYPE(STRING4):LIKE(Invalid_No):0,0\n'
    + 'FIELD:lot_order:TYPE(STRING1):LIKE(Invalid_Alpha):0,0\n'
    + 'FIELD:dpbc:TYPE(STRING2):LIKE(Invalid_No):0,0\n'
    + 'FIELD:chk_digit:TYPE(STRING1):LIKE(Invalid_No):0,0\n'
    + 'FIELD:record_type:TYPE(STRING2):LIKE(Invalid_Alpha):0,0\n'
    + 'FIELD:ace_fips_st:TYPE(STRING2):LIKE(Invalid_AlphaNum):0,0\n'
    + 'FIELD:county:TYPE(STRING3):LIKE(Invalid_No):0,0\n'
    + 'FIELD:county_name:TYPE(STRING18):LIKE(Invalid_Alpha):0,0\n'
    + 'FIELD:geo_lat:TYPE(STRING10):LIKE(Invalid_Float):0,0\n'
    + 'FIELD:geo_long:TYPE(STRING11):LIKE(Invalid_Float):0,0\n'
    + 'FIELD:msa:TYPE(STRING4):LIKE(Invalid_Float):0,0\n'
    + 'FIELD:geo_blk:TYPE(STRING7):LIKE(Invalid_Float):0,0\n'
    + 'FIELD:geo_match:TYPE(STRING1):LIKE(Invalid_Float):0,0\n'
    + 'FIELD:err_stat:TYPE(STRING4):LIKE(Invalid_AlphaNum):0,0\n'
    + 'FIELD:mail_prim_range:TYPE(STRING10):LIKE(Invalid_No):0,0\n'
    + 'FIELD:mail_predir:TYPE(STRING2):LIKE(Invalid_Alpha):0,0\n'
    + 'FIELD:mail_prim_name:TYPE(STRING28):LIKE(Invalid_AlphaNum):0,0\n'
    + 'FIELD:mail_addr_suffix:TYPE(STRING4):LIKE(Invalid_Alpha):0,0\n'
    + 'FIELD:mail_postdir:TYPE(STRING2):LIKE(Invalid_Alpha):0,0\n'
    + 'FIELD:mail_unit_desig:TYPE(STRING10):LIKE(Invalid_Alpha):0,0\n'
    + 'FIELD:mail_sec_range:TYPE(STRING8):LIKE(Invalid_AlphaNum):0,0\n'
    + 'FIELD:mail_p_city_name:TYPE(STRING25):LIKE(Invalid_Alpha):0,0\n'
    + 'FIELD:mail_v_city_name:TYPE(STRING25):LIKE(Invalid_Alpha):0,0\n'
    + 'FIELD:mail_st:TYPE(STRING2):LIKE(Invalid_Alpha):0,0\n'
    + 'FIELD:mail_ace_zip:TYPE(STRING5):LIKE(Invalid_Zip):0,0\n'
    + 'FIELD:mail_zip4:TYPE(STRING4):LIKE(Invalid_No):0,0\n'
    + 'FIELD:mail_cart:TYPE(STRING4):LIKE(Invalid_AlphaNum):0,0\n'
    + 'FIELD:mail_cr_sort_sz:TYPE(STRING1):LIKE(Invalid_Alpha):0,0\n'
    + 'FIELD:mail_lot:TYPE(STRING4):LIKE(Invalid_No):0,0\n'
    + 'FIELD:mail_lot_order:TYPE(STRING1):LIKE(Invalid_Alpha):0,0\n'
    + 'FIELD:mail_dpbc:TYPE(STRING2):LIKE(Invalid_No):0,0\n'
    + 'FIELD:mail_chk_digit:TYPE(STRING1):LIKE(Invalid_No):0,0\n'
    + 'FIELD:mail_record_type:TYPE(STRING2):LIKE(Invalid_Alpha):0,0\n'
    + 'FIELD:mail_ace_fips_st:TYPE(STRING2):LIKE(Invalid_No):0,0\n'
    + 'FIELD:mail_fipscounty:TYPE(STRING3):LIKE(Invalid_No):0,0\n'
    + 'FIELD:mail_geo_lat:TYPE(STRING10):LIKE(Invalid_Float):0,0\n'
    + 'FIELD:mail_geo_long:TYPE(STRING11):LIKE(Invalid_Float):0,0\n'
    + 'FIELD:mail_msa:TYPE(STRING4):LIKE(Invalid_Float):0,0\n'
    + 'FIELD:mail_geo_blk:TYPE(STRING7):LIKE(Invalid_Float):0,0\n'
    + 'FIELD:mail_geo_match:TYPE(STRING1):LIKE(Invalid_Float):0,0\n'
    + 'FIELD:mail_err_stat:TYPE(STRING4):LIKE(Invalid_AlphaNum):0,0\n'
    ;
 
  // Structured values
  EXPORT linkpaths := DATASET([
    ],{STRING linkpath;STRING compulsory;STRING optional;STRING bonus;STRING required;STRING search});
 
END;

