// Machine-readable versions of the spec file and subsets thereof
IMPORT SALT311;
EXPORT GenerationMod := MODULE(SALT311.iGenerationMod)
 
  // SALT Version info
  EXPORT salt_VERSION := 'V3.11.0';
  EXPORT salt_MODULE := 'SALT311'; // Optional override by HACK:SALTMODULE
  EXPORT salt_TOOLSMODULE := 'SALTTOOLS30'; // Optional override by HACK:SALTTOOLSMODULE
 
  // Core module configuration values
  EXPORT spc_MODULE := 'Scrubs_LN_PropertyV2_Assessor';
  EXPORT spc_NAMESCOPE := '';
  EXPORT spc_PROCESS := '';
  EXPORT spc_PROCLAYOUTS := 'Process__Layouts';
  EXPORT spc_IDNAME := ''; // cluster id (input)
  EXPORT spc_IDFIELD := ''; // cluster id (output)
  EXPORT spc_RIDFIELD := ''; // record id
  EXPORT spc_CONFIG := 'Config';
  EXPORT spc_CONFIGPARAM := FALSE;
  EXPORT spc_SOURCEFIELD := 'fips_code';
  EXPORT spc_FILEPREFIX := 'In_';
  EXPORT spc_FILENAME := 'Property_Assessor';
  EXPORT spc_INGESTSTATUS := '';
  EXPORT spc_EXTERNAL_MAPPING := 'UniqueID:';
  EXPORT spc_EXTERNAL_BATCH_PARAM := ',/* MY_ */,ln_fares_id,process_date,vendor_source_flag,current_record,fips_code,state_code,county_name,old_apn,apna_or_pin_number,fares_unformatted_apn,duplicate_apn_multiple_address_id,assessee_name,second_assessee_name,assessee_ownership_rights_code,assessee_relationship_code,assessee_phone_number,tax_account_number,contract_owner,assessee_name_type_code,second_assessee_name_type_code,mail_care_of_name_type_code,mailing_care_of_name,mailing_full_street_address,mailing_unit_number,mailing_city_state_zip,property_full_street_address,property_unit_number,property_city_state_zip,property_country_code,property_address_code,legal_lot_code,legal_lot_number,legal_land_lot,legal_block,legal_section,legal_district,legal_unit,legal_city_municipality_township,legal_subdivision_name,legal_phase_number,legal_tract_number,legal_sec_twn_rng_mer,legal_brief_description,legal_assessor_map_ref,census_tract,record_type_code,ownership_type_code,new_record_type_code,state_land_use_code,county_land_use_code,county_land_use_description,standardized_land_use_code,timeshare_code,zoning,owner_occupied,recorder_document_number,recorder_book_number,recorder_page_number,transfer_date,recording_date,sale_date,document_type,sales_price,sales_price_code,mortgage_loan_amount,mortgage_loan_type_code,mortgage_lender_name,mortgage_lender_type_code,prior_transfer_date,prior_recording_date,prior_sales_price,prior_sales_price_code,assessed_land_value,assessed_improvement_value,assessed_total_value,assessed_value_year,market_land_value,market_improvement_value,market_total_value,market_value_year,homestead_homeowner_exemption,tax_exemption1_code,tax_exemption2_code,tax_exemption3_code,tax_exemption4_code,tax_rate_code_area,tax_amount,tax_year,tax_delinquent_year,school_tax_district1,school_tax_district1_indicator,school_tax_district2,school_tax_district2_indicator,school_tax_district3,school_tax_district3_indicator,lot_size,lot_size_acres,lot_size_frontage_feet,lot_size_depth_feet,land_acres,land_square_footage,land_dimensions,building_area,building_area_indicator,building_area1,building_area1_indicator,building_area2,building_area2_indicator,building_area3,building_area3_indicator,building_area4,building_area4_indicator,building_area5,building_area5_indicator,building_area6,building_area6_indicator,building_area7,building_area7_indicator,year_built,effective_year_built,no_of_buildings,no_of_stories,no_of_units,no_of_rooms,no_of_bedrooms,no_of_baths,no_of_partial_baths,no_of_plumbing_fixtures,garage_type_code,parking_no_of_cars,pool_code,style_code,type_construction_code,foundation_code,building_quality_code,building_condition_code,exterior_walls_code,interior_walls_code,roof_cover_code,roof_type_code,floor_cover_code,water_code,sewer_code,heating_code,heating_fuel_type_code,air_conditioning_code,air_conditioning_type_code,elevator,fireplace_indicator,fireplace_number,basement_code,building_class_code,site_influence1_code,site_influence2_code,site_influence3_code,site_influence4_code,site_influence5_code,amenities1_code,amenities2_code,amenities3_code,amenities4_code,amenities5_code,amenities2_code1,amenities2_code2,amenities2_code3,amenities2_code4,amenities2_code5,extra_features1_area,extra_features1_indicator,extra_features2_area,extra_features2_indicator,extra_features3_area,extra_features3_indicator,extra_features4_area,extra_features4_indicator,other_buildings1_code,other_buildings2_code,other_buildings3_code,other_buildings4_code,other_buildings5_code,other_impr_building1_indicator,other_impr_building2_indicator,other_impr_building3_indicator,other_impr_building4_indicator,other_impr_building5_indicator,other_impr_building_area1,other_impr_building_area2,other_impr_building_area3,other_impr_building_area4,other_impr_building_area5,topograpy_code,neighborhood_code,condo_project_or_building_name,assessee_name_indicator,second_assessee_name_indicator,other_rooms_indicator,mail_care_of_name_indicator,comments,tape_cut_date,certification_date,edition_number,prop_addr_propagated_ind,ln_ownership_rights,ln_relationship_type,ln_mailing_country_code,ln_property_name,ln_property_name_type,ln_land_use_category,ln_lot,ln_block,ln_unit,ln_subfloor,ln_floor_cover,ln_mobile_home_indicator,ln_condo_indicator,ln_property_tax_exemption,ln_veteran_status,ln_old_apn_indicator,fips';
  EXPORT spc_HAS_TWOSTEP := FALSE;
  EXPORT spc_HAS_PARTITION := FALSE;
  EXPORT spc_HAS_FIELDTYPES := TRUE;
  EXPORT spc_HAS_INCREMENTAL := FALSE;
  EXPORT spc_HAS_ASOF := FALSE;
  EXPORT spc_HAS_NONCONTIGUOUS := FALSE;
  EXPORT spc_HAS_SUPERFILES := FALSE;
  EXPORT spc_HAS_CONSISTENT := TRUE;
  EXPORT spc_HAS_EXTERNAL := FALSE;
  EXPORT spc_HAS_PARENTS := FALSE;
  EXPORT spc_HAS_FORCE := FALSE;
  EXPORT spc_HAS_BLOCKLINK := FALSE;
 
  // The entire spec file
  EXPORT spcString :=
    'options:-gh\n'
    + 'MODULE:Scrubs_LN_PropertyV2_Assessor\n'
    + 'FILENAME:Property_Assessor\n'
    + '//Uncomment up to NINES for internal or external adl\n'
    + '//IDFIELD:EXISTS:<NameOfIDField>\n'
    + '//RIDFIELD:<NameOfRidField>\n'
    + '//RECORDS:<NumberOfRecordsInDataFile>\n'
    + '//POPULATION:<ExpectedNumberOfEntitiesInDataFile>\n'
    + '//NINES:<Precision required 3 = 99.9, 2 = 99 2.295662e+263tc>\n'
    + '//Uncomment Process if doing external adl\n'
    + '//PROCESS:<ProcessName>\n'
    + 'FIELDTYPE:invalid_alpha:SPACES( ):ALLOW( &(),-/.\'#:;*;ABCDEFGHIJKLMNOPQRSTUVWXYZ)\n'
    + 'FIELDTYPE:invalid_address:SPACES( ):ALLOW(\',./#-&/0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ)\n'
    + 'FIELDTYPE:invalid_county_name:ALLOW(ABCDEFGHIJKLMNOPQRSTUVWXYZ\'):SPACES( -):WORDS(1,2,3,4,5)\n'
    + 'FIELDTYPE:invalid_apn:SPACES( ):ALLOW( _-.,/:&()*0123456789:;ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz):LENGTHS(1..)\n'
    + 'FIELDTYPE:invalid_csz:SPACES( ):ALLOW( ,-ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789)\n'
    + 'FIELDTYPE:invalid_zip:ALLOW(0123456789):LENGTHS(5,9)\n'
    + 'FIELDTYPE:invalid_year:custom(Scrubs_LN_PropertyV2_Assessor.fn_valid_year>0)\n'
    + 'FIELDTYPE:invalid_date:ALLOW(0123456789):LENGTHS(0..8):CUSTOM(Scrubs.fn_valid_date>0)\n'
    + 'FIELDTYPE:invalid_phone:ALLOW(0123456789):LENGTHS(0..10)\n'
    + 'FIELDTYPE:invalid_fips:SPACES( ):ALLOW(0123456789):LENGTHS(5):WITHIN(Scrubs_LN_PropertyV2_Assessor.file_fips,fips_code)\n'
    + 'FIELDTYPE:invalid_prop_amount:ALLOW(0123456789.)\n'
    + 'FIELDTYPE:invalid_tax_amount:ALLOW(0123456789.)\n'
    + 'FIELDTYPE:invalid_state_num:ALLOW(0123456789):LENGTHS(2):INRANGE(1,78)\n'
    + 'FIELDTYPE:invalid_state_code:ALLOW(ACDEFGHIJKLMNOPRSTUVWXYZ):LEFTTRIM:LENGTHS(2)\n'
    + 'FIELDTYPE:invalud_document_number:ALLOW(ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789/-&\'):SPACES( -.)\n'
    + 'FIELDTYPE:invalid_land_use:CUSTOM(fn_valid_codesv3_property > 0,vendor_source_flag,\'LAND_USE\', \'FARES_2580\')\n'
    + 'FIELDTYPE:invalid_ownership_rights_code:CUSTOM(fn_valid_codesv3_property > 0,vendor_source_flag,\'OWNER_OWNERSHIP_RIGHTS_CODE\', \'FARES_2580\')\n'
    + 'FIELDTYPE:invalid_relationship_code:CUSTOM(fn_valid_codesv3_property > 0,vendor_source_flag,\'OWNER_RELATIONSHIP_CODE\', \'FARES_2580\')\n'
    + 'FIELDTYPE:invalid_name_type_code:CUSTOM(fn_valid_codesv3_property > 0,vendor_source_flag,\'ASSESSEE_NAME_TYPE_CODE\', \'FARES_2580\')\n'
    + 'FIELDTYPE:invalid_second_name_type_code:CUSTOM(fn_valid_codesv3_property > 0,vendor_source_flag,\'SECOND_ASSESSEE_NAME_TYPE_CODE\', \'FARES_2580\')\n'
    + 'FIELDTYPE:invalid_mail_care_of_name_type_code:CUSTOM(fn_valid_codesv3_property > 0,vendor_source_flag,\'MAIL_CARE_OF_NAME_TYPE_CODE\', \'FARES_2580\')\n'
    + 'FIELDTYPE:invalid_record_type_code:CUSTOM(fn_valid_codesv3_property > 0,vendor_source_flag,\'RECORD_TYPE_CODE\', \'FARES_2580\')\n'
    + 'FIELDTYPE:invalid_legal_lot_code:CUSTOM(fn_valid_codesv3_property > 0,vendor_source_flag,\'LEGAL_LOT_CODE\', \'FARES_2580\')\n'
    + 'FIELDTYPE:invalid_ownership_type_code:CUSTOM(fn_valid_codesv3_property > 0,vendor_source_flag,\'OWNERSHIP_TYPE_CODE\', \'FARES_2580\')\n'
    + 'FIELDTYPE:invalid_new_record_type_code:CUSTOM(fn_valid_codesv3_property > 0,vendor_source_flag,\'NEW_RECORD_TYPE_CODE\', \'FARES_2580\')\n'
    + 'FIELDTYPE:invalid_sale_code:CUSTOM(fn_valid_codesv3_property > 0,vendor_source_flag,\'SALE_CODE\', \'FARES_2580\')\n'
    + '//FIELDTYPE:invalid_prior_sales_price_code:CUSTOM(fn_valid_codesv3_property > 0,vendor_source_flag,\'PRIOR_SALES_PRICE_CODE\', \'FARES_2580\')\n'
    + 'FIELDTYPE:invalid_prior_sales_price_code:CUSTOM(fn_valid_codesv3_property > 0,vendor_source_flag,\'PRIOR_SALES_CODE\', \'FARES_2580\')\n'
    + 'FIELDTYPE:invalid_mortgage_loan_type_code:CUSTOM(fn_valid_codesv3_property > 0,vendor_source_flag,\'MORTGAGE_LOAN_TYPE_CODE\', \'FARES_2580\')\n'
    + 'FIELDTYPE:invalid_mortgage_lender_type_code:CUSTOM(fn_valid_codesv3_property > 0,vendor_source_flag,\'MORTGAGE_LENDER_TYPE_CODE\', \'FARES_2580\')\n'
    + 'FIELDTYPE:invalid_tax_exemption1_code:CUSTOM(fn_valid_codesv3_property > 0,vendor_source_flag,\'TAX_EXEMPTION1_CODE\', \'FARES_2580\')\n'
    + 'FIELDTYPE:invalid_tax_exemption2_code:CUSTOM(fn_valid_codesv3_property > 0,vendor_source_flag,\'TAX_EXEMPTION2_CODE\', \'FARES_2580\')\n'
    + 'FIELDTYPE:invalid_tax_exemption3_code:CUSTOM(fn_valid_codesv3_property > 0,vendor_source_flag,\'TAX_EXEMPTION3_CODE\', \'FARES_2580\')\n'
    + 'FIELDTYPE:invalid_tax_exemption4_code:CUSTOM(fn_valid_codesv3_property > 0,vendor_source_flag,\'TAX_EXEMPTION4_CODE\', \'FARES_2580\')\n'
    + 'FIELDTYPE:invalid_no_of_stories:ALLOW(0123456789.AB+):LENGTHS(0..5)\n'
    + 'FIELDTYPE:invalid_garage_type_code:CUSTOM(fn_valid_codesv3_property > 0,vendor_source_flag,\'GARAGE\', \'FARES_2580\')\n'
    + 'FIELDTYPE:invalid_pool_code:CUSTOM(fn_valid_codesv3_property > 0,vendor_source_flag,\'POOL_CODE\', \'FARES_2580\')\n'
    + 'FIELDTYPE:invalid_exterior_walls_code:CUSTOM(fn_valid_codesv3_property > 0,vendor_source_flag,\'EXTERIOR_WALLS\', \'FARES_2580\')\n'
    + 'FIELDTYPE:invalid_roof_type_code:CUSTOM(fn_valid_codesv3_property > 0,vendor_source_flag,\'ROOF_TYPE\', \'FARES_2580\')\n'
    + 'FIELDTYPE:invalid_heating_code:CUSTOM(fn_valid_codesv3_property > 0,vendor_source_flag,\'HEATING\', \'FARES_2580\')\n'
    + 'FIELDTYPE:invalid_heating_fuel_type_code:CUSTOM(fn_valid_codesv3_property > 0,vendor_source_flag,\'FUEL\', \'FARES_2580\')\n'
    + 'FIELDTYPE:invalid_air_conditioning_type_code:CUSTOM(fn_valid_codesv3_property > 0,vendor_source_flag,\'AIR_CONDITIONING_TYPE_CODE\', \'FARES_2580\')\n'
    + 'FIELDTYPE:invalid_building_class_code:CUSTOM(fn_valid_codesv3_property > 0,vendor_source_flag,\'BUILDING_CLASS_CODE\', \'FARES_2580\')\n'
    + 'FIELDTYPE:invalid_site_influence1_code:CUSTOM(fn_valid_codesv3_property > 0,vendor_source_flag,\'LOCATION_INFLUENCE\', \'FARES_2580\')\n'
    + 'FIELDTYPE:invalid_amenities1_code:CUSTOM(fn_valid_codesv3_property > 0,vendor_source_flag,\'AMENITIES1_CODE\', \'FARES_2580\')\n'
    + 'FIELDTYPE:invalid_amenities2_code:CUSTOM(fn_valid_codesv3_property > 0,vendor_source_flag,\'AMENITIES2_CODE\', \'FARES_2580\')\n'
    + 'FIELDTYPE:invalid_amenities3_code:CUSTOM(fn_valid_codesv3_property > 0,vendor_source_flag,\'AMENITIES3_CODE\', \'FARES_2580\')\n'
    + 'FIELDTYPE:invalid_amenities4_code:CUSTOM(fn_valid_codesv3_property > 0,vendor_source_flag,\'AMENITIES4_CODE\', \'FARES_2580\')\n'
    + 'FIELDTYPE:invalid_other_buildings1_code:CUSTOM(fn_valid_codesv3_property > 0,vendor_source_flag,\'BLDG_IMPV_CODE\', \'FARES_2580\')\n'
    + 'FIELDTYPE:invalid_fireplace_indicator:CUSTOM(fn_valid_codesv3_property > 0,vendor_source_flag,\'FIREPLACE_INDICATOR\', \'FARES_2580\')\n'
    + 'FIELDTYPE:invalid_property_address_code:CUSTOM(fn_valid_codesv3_property > 0,vendor_source_flag,\'PROPERTY_ADDRESS_CODE\', \'FARES_2580\')\n'
    + 'FIELDTYPE:invalid_floor_cover_code:CUSTOM(fn_valid_codesv3_property > 0,vendor_source_flag,\'FLOOR_COVER\', \'FARES_2580\')\n'
    + 'FIELDTYPE:invalid_building_quality_code:CUSTOM(fn_valid_codesv3_property > 0,vendor_source_flag,\'QUALITY\',\'FARES_2580\')\n'
    + 'FIELDTYPE:invalid_document_type_code:CUSTOM(fn_valid_codesv3_property > 0,vendor_source_flag,\'DOCUMENT_TYPE_CODE\', \'FARES_2580\'):SPACES( ):ALLOW( -.:ABCDEFGHIJKLMNOPQRSTUVWXYZ/():,&\'-)\n'
    + '//FIELDTYPE:invalid_basement_code:CUSTOM(fn_valid_codesv3_property > 0,vendor_source_flag,\'BASEMENT_CODE\', \'FARES_2580\')\n'
    + 'FIELDTYPE:invalid_basement_code:CUSTOM(fn_valid_codesv3_property > 0,vendor_source_flag,\'BASEMENT_FINISH\', \'FARES_2580\')\n'
    + '//FIELDTYPE:invalid_building_area_indicator:CUSTOM(fn_valid_codesv3_property > 0,vendor_source_flag,\'BUILDING_AREA_INDICATOR\', \'FARES_2580\')\n'
    + 'FIELDTYPE:invalid_building_area_indicator:CUSTOM(fn_valid_codesv3_property > 0,vendor_source_flag,\'BUILDING_SQ_FEET_IND\', \'FARES_2580\')\n'
    + 'FIELDTYPE:invalid_building_area1_indicator:CUSTOM(fn_valid_codesv3_property > 0,vendor_source_flag,\'BUILDING_AREA1_INDICATOR\', \'FARES_2580\')                  \n'
    + 'FIELDTYPE:invalid_building_area2_indicator:CUSTOM(fn_valid_codesv3_property > 0,vendor_source_flag,\'BUILDING_AREA2_INDICATOR\', \'FARES_2580\')               \n'
    + 'FIELDTYPE:invalid_building_area3_indicator:CUSTOM(fn_valid_codesv3_property > 0,vendor_source_flag,\'BUILDING_AREA3_INDICATOR\', \'FARES_2580\')                   \n'
    + 'FIELDTYPE:invalid_building_area4_indicator:CUSTOM(fn_valid_codesv3_property > 0,vendor_source_flag,\'BUILDING_AREA4_INDICATOR\', \'FARES_2580\')                      \n'
    + 'FIELDTYPE:invalid_building_area5_indicator:CUSTOM(fn_valid_codesv3_property > 0,vendor_source_flag,\'BUILDING_AREA5_INDICATOR\', \'FARES_2580\')                      \n'
    + 'FIELDTYPE:invalid_building_area6_indicator:CUSTOM(fn_valid_codesv3_property > 0,vendor_source_flag,\'BUILDING_AREA6_INDICATOR\', \'FARES_2580\')                     \n'
    + 'FIELDTYPE:invalid_building_area7_indicator:CUSTOM(fn_valid_codesv3_property > 0,vendor_source_flag,\'BUILDING_AREA7_INDICATOR\', \'FARES_2580\')                    \n'
    + 'FIELDTYPE:invalid_construction_type:CUSTOM(fn_valid_codesv3_property > 0,vendor_source_flag,\'CONSTRUCTION_TYPE\', \'FARES_2580\')   \n'
    + 'FIELDTYPE:invalid_building_area:CUSTOM(fn_valid_ratio > 0, sales_price)\n'
    + '                       \n'
    + 'FIELD:ln_fares_id:0,0\n'
    + 'DATEFIELD:process_date:LIKE(invalid_date):0,0\n'
    + 'FIELD:vendor_source_flag:0,0\n'
    + 'FIELD:current_record:0,0\n'
    + 'FIELD:fips_code:LIKE(invalid_fips):0,0\n'
    + 'FIELD:state_code:LIKE(invalid_state_code):0,0\n'
    + 'FIELD:county_name:LIKE(invalid_county_name):0,0\n'
    + 'FIELD:old_apn:0,0\n'
    + 'FIELD:apna_or_pin_number:LIKE(invalid_apn):0,0\n'
    + 'FIELD:fares_unformatted_apn:0,0\n'
    + 'FIELD:duplicate_apn_multiple_address_id:0,0\n'
    + 'FIELD:assessee_name:LIKE(invalid_alpha):0,0\n'
    + 'FIELD:second_assessee_name:LIKE(invalid_alpha):0,0\n'
    + 'FIELD:assessee_ownership_rights_code:LIKE(invalid_ownership_rights_code):0,0\n'
    + 'FIELD:assessee_relationship_code:LIKE(invalid_relationship_code):0,0\n'
    + 'FIELD:assessee_phone_number:LIKE(invalid_phone):0,0\n'
    + 'FIELD:tax_account_number:0,0\n'
    + 'FIELD:contract_owner:0,0\n'
    + 'FIELD:assessee_name_type_code:LIKE(invalid_name_type_code):0,0\n'
    + 'FIELD:second_assessee_name_type_code:LIKE(invalid_second_name_type_code):0,0\n'
    + 'FIELD:mail_care_of_name_type_code:LIKE(invalid_mail_care_of_name_type_code):0,0\n'
    + 'FIELD:mailing_care_of_name:LIKE(invalid_alpha):0,0\n'
    + 'FIELD:mailing_full_street_address:LIKE(invalid_address):0,0\n'
    + 'FIELD:mailing_unit_number:LIKE(invalid_address):0,0\n'
    + 'FIELD:mailing_city_state_zip:LIKE(invalid_csz):0,0\n'
    + 'FIELD:property_full_street_address:LIKE(invalid_address):0,0\n'
    + 'FIELD:property_unit_number:LIKE(invalid_address):0,0\n'
    + 'FIELD:property_city_state_zip:LIKE(invalid_csz):0,0\n'
    + 'FIELD:property_country_code:0,0\n'
    + 'FIELD:property_address_code:LIKE(invalid_property_address_code):0,0\n'
    + 'FIELD:legal_lot_code:LIKE(invalid_legal_lot_code):0,0\n'
    + 'FIELD:legal_lot_number:0,0\n'
    + 'FIELD:legal_land_lot:0,0\n'
    + 'FIELD:legal_block:0,0\n'
    + 'FIELD:legal_section:0,0\n'
    + 'FIELD:legal_district:0,0\n'
    + 'FIELD:legal_unit:0,0\n'
    + 'FIELD:legal_city_municipality_township:0,0\n'
    + 'FIELD:legal_subdivision_name:0,0\n'
    + 'FIELD:legal_phase_number:0,0\n'
    + 'FIELD:legal_tract_number:0,0\n'
    + 'FIELD:legal_sec_twn_rng_mer:0,0\n'
    + 'FIELD:legal_brief_description:0,0\n'
    + 'FIELD:legal_assessor_map_ref:0,0\n'
    + 'FIELD:census_tract:0,0\n'
    + 'FIELD:record_type_code:LIKE(invalid_record_type_code):0,0\n'
    + 'FIELD:ownership_type_code:LIKE(invalid_ownership_type_code):0,0\n'
    + 'FIELD:new_record_type_code:LIKE(invalid_new_record_type_code):0,0\n'
    + 'FIELD:state_land_use_code:0,0\n'
    + 'FIELD:county_land_use_code:0,0\n'
    + 'FIELD:county_land_use_description:0,0\n'
    + 'FIELD:standardized_land_use_code:LIKE(invalid_land_use):0,0\n'
    + 'FIELD:timeshare_code:0,0\n'
    + 'FIELD:zoning:0,0\n'
    + 'FIELD:owner_occupied:0,0\n'
    + 'FIELD:recorder_document_number:0,0\n'
    + 'FIELD:recorder_book_number:0,0\n'
    + 'FIELD:recorder_page_number:0,0\n'
    + 'DATEFIELD:transfer_date:LIKE(invalid_date):0,0\n'
    + 'DATEFIELD:recording_date:LIKE(invalid_date):0,0\n'
    + 'DATEFIELD:sale_date:LIKE(invalid_date):0,0\n'
    + 'FIELD:document_type:LIKE(invalid_document_type_code):0,0\n'
    + 'FIELD:sales_price:LIKE(invalid_prop_amount):0,0\n'
    + 'FIELD:sales_price_code:LIKE(invalid_sale_code):0,0\n'
    + 'FIELD:mortgage_loan_amount:LIKE(invalid_prop_amount):0,0\n'
    + 'FIELD:mortgage_loan_type_code:LIKE(invalid_mortgage_loan_type_code):0,0\n'
    + 'FIELD:mortgage_lender_name:LIKE(invalid_alpha):0,0\n'
    + 'FIELD:mortgage_lender_type_code:LIKE(invalid_mortgage_lender_type_code):0,0\n'
    + 'DATEFIELD:prior_transfer_date:LIKE(invalid_date):0,0\n'
    + 'DATEFIELD:prior_recording_date:LIKE(invalid_date):0,0\n'
    + 'FIELD:prior_sales_price:LIKE(invalid_prop_amount):0,0\n'
    + 'FIELD:prior_sales_price_code:LIKE(invalid_prior_sales_price_code):0,0\n'
    + 'FIELD:assessed_land_value:LIKE(invalid_prop_amount):0,0\n'
    + 'FIELD:assessed_improvement_value:LIKE(invalid_prop_amount):0,0\n'
    + 'FIELD:assessed_total_value:LIKE(invalid_prop_amount):0,0\n'
    + 'FIELD:assessed_value_year:LIKE(invalid_year):0,0\n'
    + 'FIELD:market_land_value:LIKE(invalid_prop_amount):0,0\n'
    + 'FIELD:market_improvement_value:LIKE(invalid_prop_amount):0,0\n'
    + 'FIELD:market_total_value:LIKE(invalid_prop_amount):0,0\n'
    + 'FIELD:market_value_year:LIKE(invalid_year):0,0\n'
    + 'FIELD:homestead_homeowner_exemption:0,0\n'
    + 'FIELD:tax_exemption1_code:LIKE(invalid_tax_exemption1_code):0,0\n'
    + 'FIELD:tax_exemption2_code:LIKE(invalid_tax_exemption2_code):0,0\n'
    + 'FIELD:tax_exemption3_code:LIKE(invalid_tax_exemption3_code):0,0\n'
    + 'FIELD:tax_exemption4_code:LIKE(invalid_tax_exemption4_code):0,0\n'
    + 'FIELD:tax_rate_code_area:0,0\n'
    + 'FIELD:tax_amount:LIKE(invalid_tax_amount):0,0\n'
    + 'FIELD:tax_year:LIKE(invalid_year):0,0\n'
    + 'FIELD:tax_delinquent_year:LIKE(invalid_year):0,0\n'
    + 'FIELD:school_tax_district1:0,0\n'
    + 'FIELD:school_tax_district1_indicator:0,0\n'
    + 'FIELD:school_tax_district2:0,0\n'
    + 'FIELD:school_tax_district2_indicator:0,0\n'
    + 'FIELD:school_tax_district3:0,0\n'
    + 'FIELD:school_tax_district3_indicator:0,0\n'
    + 'FIELD:lot_size:0,0\n'
    + 'FIELD:lot_size_acres:0,0\n'
    + 'FIELD:lot_size_frontage_feet:0,0\n'
    + 'FIELD:lot_size_depth_feet:0,0\n'
    + 'FIELD:land_acres:0,0\n'
    + 'FIELD:land_square_footage:0,0\n'
    + 'FIELD:land_dimensions:0,0\n'
    + 'FIELD:building_area:LIKE(invalid_building_area):0,0\n'
    + 'FIELD:building_area_indicator:LIKE(invalid_building_area_indicator):0,0\n'
    + 'FIELD:building_area1:LIKE(invalid_building_area):0,0\n'
    + 'FIELD:building_area1_indicator:LIKE(invalid_building_area1_indicator):0,0\n'
    + 'FIELD:building_area2:LIKE(invalid_building_area):0,0\n'
    + 'FIELD:building_area2_indicator:LIKE(invalid_building_area2_indicator):0,0\n'
    + 'FIELD:building_area3:LIKE(invalid_building_area):0,0 \n'
    + 'FIELD:building_area3_indicator:LIKE(invalid_building_area3_indicator):0,0\n'
    + 'FIELD:building_area4:LIKE(invalid_building_area):0,0\n'
    + 'FIELD:building_area4_indicator:LIKE(invalid_building_area4_indicator):0,0\n'
    + 'FIELD:building_area5:LIKE(invalid_building_area):0,0\n'
    + 'FIELD:building_area5_indicator:LIKE(invalid_building_area5_indicator):0,0\n'
    + 'FIELD:building_area6:LIKE(invalid_building_area):0,0\n'
    + 'FIELD:building_area6_indicator:LIKE(invalid_building_area6_indicator):0,0\n'
    + 'FIELD:building_area7:LIKE(invalid_building_area):0,0\n'
    + 'FIELD:building_area7_indicator:LIKE(invalid_building_area7_indicator):0,0\n'
    + 'FIELD:year_built:LIKE(invalid_year):0,0\n'
    + 'FIELD:effective_year_built:LIKE(invalid_year):0,0\n'
    + 'FIELD:no_of_buildings:0,0\n'
    + 'FIELD:no_of_stories:LIKE(invalid_no_of_stories):0,0\n'
    + 'FIELD:no_of_units:0,0\n'
    + 'FIELD:no_of_rooms:0,0\n'
    + 'FIELD:no_of_bedrooms:0,0\n'
    + 'FIELD:no_of_baths:0,0\n'
    + 'FIELD:no_of_partial_baths:0,0\n'
    + 'FIELD:no_of_plumbing_fixtures:0,0\n'
    + 'FIELD:garage_type_code:LIKE(invalid_garage_type_code):0,0\n'
    + 'FIELD:parking_no_of_cars:0,0\n'
    + 'FIELD:pool_code:LIKE(invalid_pool_code):0,0\n'
    + 'FIELD:style_code:0,0\n'
    + 'FIELD:type_construction_code:LIKE(invalid_construction_type):0,0\n'
    + 'FIELD:foundation_code:0,0\n'
    + 'FIELD:building_quality_code:LIKE(invalid_building_quality_code):0,0\n'
    + 'FIELD:building_condition_code:0,0\n'
    + 'FIELD:exterior_walls_code:LIKe(invalid_exterior_walls_code):0,0\n'
    + 'FIELD:interior_walls_code:0,0\n'
    + 'FIELD:roof_cover_code:0,0\n'
    + 'FIELD:roof_type_code:LIKE(invalid_roof_type_code):0,0\n'
    + 'FIELD:floor_cover_code:LIKe(invalid_floor_cover_code):0,0\n'
    + 'FIELD:water_code:0,0\n'
    + 'FIELD:sewer_code:0,0\n'
    + 'FIELD:heating_code:LIKE(invalid_heating_code):0,0\n'
    + 'FIELD:heating_fuel_type_code:LIKE(invalid_heating_fuel_type_code):0,0\n'
    + 'FIELD:air_conditioning_code:0,0\n'
    + 'FIELD:air_conditioning_type_code:LIKE(invalid_air_conditioning_type_code):0,0\n'
    + 'FIELD:elevator:0,0\n'
    + 'FIELD:fireplace_indicator:LIKE(invalid_fireplace_indicator):0,0\n'
    + 'FIELD:fireplace_number:0,0\n'
    + 'FIELD:basement_code:LIKE(invalid_basement_code):0,0\n'
    + 'FIELD:building_class_code:LIKE(invalid_building_class_code):0,0\n'
    + 'FIELD:site_influence1_code:LIKE(invalid_site_influence1_code):0,0\n'
    + 'FIELD:site_influence2_code:0,0\n'
    + 'FIELD:site_influence3_code:0,0\n'
    + 'FIELD:site_influence4_code:0,0\n'
    + 'FIELD:site_influence5_code:0,0\n'
    + 'FIELD:amenities1_code:LIKe(invalid_amenities1_code):0,0\n'
    + 'FIELD:amenities2_code:LIKe(invalid_amenities2_code):0,0\n'
    + 'FIELD:amenities3_code:LIKe(invalid_amenities3_code):0,0\n'
    + 'FIELD:amenities4_code:LIKe(invalid_amenities4_code):0,0\n'
    + 'FIELD:amenities5_code:0,0\n'
    + 'FIELD:amenities2_code1:0,0\n'
    + 'FIELD:amenities2_code2:0,0\n'
    + 'FIELD:amenities2_code3:0,0\n'
    + 'FIELD:amenities2_code4:0,0\n'
    + 'FIELD:amenities2_code5:0,0\n'
    + 'FIELD:extra_features1_area:0,0\n'
    + 'FIELD:extra_features1_indicator:0,0\n'
    + 'FIELD:extra_features2_area:0,0\n'
    + 'FIELD:extra_features2_indicator:0,0\n'
    + 'FIELD:extra_features3_area:0,0\n'
    + 'FIELD:extra_features3_indicator:0,0\n'
    + 'FIELD:extra_features4_area:0,0\n'
    + 'FIELD:extra_features4_indicator:0,0\n'
    + 'FIELD:other_buildings1_code:LIKE(invalid_other_buildings1_code):0,0\n'
    + 'FIELD:other_buildings2_code:0,0\n'
    + 'FIELD:other_buildings3_code:0,0\n'
    + 'FIELD:other_buildings4_code:0,0\n'
    + 'FIELD:other_buildings5_code:0,0\n'
    + 'FIELD:other_impr_building1_indicator:0,0\n'
    + 'FIELD:other_impr_building2_indicator:0,0\n'
    + 'FIELD:other_impr_building3_indicator:0,0\n'
    + 'FIELD:other_impr_building4_indicator:0,0\n'
    + 'FIELD:other_impr_building5_indicator:0,0\n'
    + 'FIELD:other_impr_building_area1:0,0\n'
    + 'FIELD:other_impr_building_area2:0,0\n'
    + 'FIELD:other_impr_building_area3:0,0\n'
    + 'FIELD:other_impr_building_area4:0,0\n'
    + 'FIELD:other_impr_building_area5:0,0\n'
    + 'FIELD:topograpy_code:0,0\n'
    + 'FIELD:neighborhood_code:0,0\n'
    + 'FIELD:condo_project_or_building_name:0,0\n'
    + 'FIELD:assessee_name_indicator:0,0\n'
    + 'FIELD:second_assessee_name_indicator:0,0\n'
    + 'FIELD:other_rooms_indicator:0,0\n'
    + 'FIELD:mail_care_of_name_indicator:0,0\n'
    + 'FIELD:comments:0,0\n'
    + 'DATEFIELD:tape_cut_date:LIKE(invalid_date):0,0\n'
    + 'DATEFIELD:certification_date:LIKE(invalid_date):0,0\n'
    + 'FIELD:edition_number:0,0\n'
    + 'FIELD:prop_addr_propagated_ind:0,0\n'
    + 'FIELD:ln_ownership_rights:0,0\n'
    + 'FIELD:ln_relationship_type:0,0\n'
    + 'FIELD:ln_mailing_country_code:0,0\n'
    + 'FIELD:ln_property_name:0,0\n'
    + 'FIELD:ln_property_name_type:0,0\n'
    + 'FIELD:ln_land_use_category:0,0\n'
    + 'FIELD:ln_lot:0,0\n'
    + 'FIELD:ln_block:0,0\n'
    + 'FIELD:ln_unit:0,0\n'
    + 'FIELD:ln_subfloor:0,0\n'
    + 'FIELD:ln_floor_cover:0,0\n'
    + 'FIELD:ln_mobile_home_indicator:0,0\n'
    + 'FIELD:ln_condo_indicator:0,0\n'
    + 'FIELD:ln_property_tax_exemption:0,0\n'
    + 'FIELD:ln_veteran_status:0,0\n'
    + 'FIELD:ln_old_apn_indicator:0,0\n'
    + 'FIELD:fips:LIKE(invalid_fips):0,0\n'
    + 'SOURCEFIELD:fips_code:CONSISTENT(standardized_land_use_code,document_type,sales_price,mortgage_loan_type_code)\n'
    + 'RECORDTYPE:trans_before_proc:CONDITION(transfer_date,<,process_date):VALID(transfer_date,process_date)\n'
    + 'RECORDTYPE:rec_before_proc:CONDITION(recording_date,<,process_date):VALID(recording_date,process_date)\n'
    + 'RECORDTYPE:sale_before_proc:CONDITION(sale_date,<,process_date):VALID(sale_date,process_date)\n'
    + 'RECORDTYPE:ptrans_before_proc:CONDITION(prior_transfer_date,<,process_date):VALID(prior_transfer_date,process_date)\n'
    + 'RECORDTYPE:prior_rec_before_proc:CONDITION(prior_recording_date,<,process_date):VALID(prior_recording_date,process_date)\n'
    + 'RECORDTYPE:cert_before_proc:CONDITION(certification_date,<,process_date):VALID(certification_date,process_date)\n'
    + 'RECORDTYPE:cut_before_proc:CONDITION(tape_cut_date,<,process_date):VALID(tape_cut_date,process_date)\n'
    + 'RECORDTYPE:AssImp_Eq_AssTot:CONDITION(assessed_improvement_value,<,assessed_total_value):VALID(assessed_improvement_value,assessed_total_value) \n'
    + 'RECORDTYPE:MarImp_Eq_MarTot:CONDITION(market_improvement_value,<,market_total_value):VALID(market_improvement_value,market_total_value)\n'
    + 'RECORDTYPE:AssLnd_Eq_AssTot:CONDITION(assessed_land_value,<=,assessed_total_value):VALID(assessed_land_value,assessed_total_value) \n'
    + 'RECORDTYPE:MarLnd_Eq_MarTot:CONDITION(market_land_value,<=,market_total_value):VALID(market_land_value,market_total_value)\n'
    + 'RECORDTYPE:tax_less_than_total_assessed:TAG(assessed_total_value,\'\'):NOTAG:CONDITION(tax_amount,<=,assessed_total_value):VALID(tax_amount,assessed_total_value)\n'
    ;
 
  // Structured values
  EXPORT linkpaths := DATASET([
    ],{STRING linkpath;STRING compulsory;STRING optional;STRING bonus;STRING required;STRING search});
 
END;

