import Autokey_batch,Address,iesp,NPPES,Address;

export NPI_Layouts  := MODULE

	EXPORT std_batch_in := RECORD
		Autokey_batch.Layouts.rec_inBatchMaster;
		String10 NPINumber;
	END;

	EXPORT batch_in := RECORD
		Autokey_batch.Layouts.rec_inBatchMaster.acctno;
		Autokey_batch.Layouts.rec_inBatchMaster.comp_name;
		Autokey_batch.Layouts.rec_inBatchMaster.name_first;
		Autokey_batch.Layouts.rec_inBatchMaster.name_middle;
		Autokey_batch.Layouts.rec_inBatchMaster.name_last;
		Autokey_batch.Layouts.rec_inBatchMaster.name_suffix;
		Autokey_batch.Layouts.rec_inBatchMaster.prim_range;
		Autokey_batch.Layouts.rec_inBatchMaster.predir;
		Autokey_batch.Layouts.rec_inBatchMaster.prim_name;
		Autokey_batch.Layouts.rec_inBatchMaster.addr_suffix;
		Autokey_batch.Layouts.rec_inBatchMaster.postdir;
		Autokey_batch.Layouts.rec_inBatchMaster.unit_desig;
		Autokey_batch.Layouts.rec_inBatchMaster.sec_range;
		Autokey_batch.Layouts.rec_inBatchMaster.p_city_name;
		Autokey_batch.Layouts.rec_inBatchMaster.st;
		Autokey_batch.Layouts.rec_inBatchMaster.z5;
		// Autokey_batch.Layouts.rec_inBatchMaster.did;		
		// Autokey_batch.Layouts.rec_inBatchMaster.bdid;
		String20 NPINumber;
		String15	Taxonomy1 := '';
		String15	Taxonomy2 := '';
		String15	Taxonomy3 := '';
		String15	Taxonomy4 := '';
		String15	Taxonomy5 := '';
	END;

	export t_NPIBatchRequest := record
		batch_in;
	end;

	EXPORT batch_out := RECORD
		Autokey_batch.Layouts.rec_inBatchMaster.acctno;
		Autokey_batch.Layouts.rec_inBatchMaster.comp_name;
		Autokey_batch.Layouts.rec_inBatchMaster.name_first;
		Autokey_batch.Layouts.rec_inBatchMaster.name_middle;
		Autokey_batch.Layouts.rec_inBatchMaster.name_last;
		Autokey_batch.Layouts.rec_inBatchMaster.name_suffix;
		Autokey_batch.Layouts.rec_inBatchMaster.prim_range;
		Autokey_batch.Layouts.rec_inBatchMaster.predir;
		Autokey_batch.Layouts.rec_inBatchMaster.prim_name;
		Autokey_batch.Layouts.rec_inBatchMaster.addr_suffix;
		Autokey_batch.Layouts.rec_inBatchMaster.postdir;
		Autokey_batch.Layouts.rec_inBatchMaster.unit_desig;
		Autokey_batch.Layouts.rec_inBatchMaster.sec_range;
		Autokey_batch.Layouts.rec_inBatchMaster.p_city_name;
		Autokey_batch.Layouts.rec_inBatchMaster.st;
		Autokey_batch.Layouts.rec_inBatchMaster.z5;
		// Autokey_batch.Layouts.rec_inBatchMaster.did;		
		// Autokey_batch.Layouts.rec_inBatchMaster.bdid;
		String20 NPINumber;
		NPPES.layouts.KeyBuild;
	END;

	EXPORT batch_out_penalty := RECORD
		batch_out;
		unsigned record_penalty := 0;
	END;

	export taxnomy := record
		string10 healthcare_provider_taxonomy_code;
		string20 provider_license_number;
		string2 provider_license_number_state_code;
		string1 healthcare_provider_primary_taxonomy_switch;
		integer cnt;
	end;
	
	export otherp	:=  record
		string20 other_provider_identifier;
		string2 other_provider_identifier_type_code;
		string2 other_provider_identifier_state;
		string80 other_provider_identifier_issuer;
	end;
	
	export tax_desc := record
		string100 taxonomy_desc;
		string1 healthcare_provider_primary_taxonomy_switch;
		string10 healthcare_provider_taxonomy_code;
	end;
	
	export pid_desc	:= record
		string28 other_pid_issuer_desc;
	end;
	
	EXPORT T_Batch_Out := RECORD
		string20 acctno;
		unsigned6 did;
		unsigned1 did_score;
		unsigned6 bdid;
		unsigned1 bdid_score;
		unsigned6 bid;
		unsigned1 bid_score;
		string8 process_date;
		unsigned4 dt_first_seen;
		unsigned4 dt_last_seen;
		unsigned4 dt_vendor_first_reported;
		unsigned4 dt_vendor_last_reported;
		string10 npi;
		string1 entity_type_code;
		string10 replacement_npi;
		string9 employer_identification_number;
		string70 provider_organization_name;
		string35 provider_last_name;
		string20 provider_first_name;
		string20 provider_middle_name;
		string5 provider_name_prefix_text;
		string5 provider_name_suffix_text;
		string20 provider_credential_text;
		string70 provider_other_organization_name;
		string1 provider_other_organization_name_type_code;
		string35 provider_other_last_name;
		string20 provider_other_first_name;
		string20 provider_other_middle_name;
		string5 provider_other_name_prefix_text;
		string5 provider_other_name_suffix_text;
		string20 provider_other_credential_text;
		string1 provider_other_last_name_type_code;
		string55 provider_first_line_business_mailing_address;
		string55 provider_second_line_business_mailing_address;
		string40 provider_business_mailing_address_city_name;
		string40 provider_business_mailing_address_state_name;
		string20 provider_business_mailing_address_postal_code;
		string2 provider_business_mailing_address_country_code;
		string20 provider_business_mailing_address_telephone_number;
		string20 provider_business_mailing_address_fax_number;
		string55 provider_first_line_business_practice_location_address;
		string55 provider_second_line_business_practice_location_address;
		string40 provider_business_practice_location_address_city_name;
		string40 provider_business_practice_location_address_state_name;
		string20 provider_business_practice_location_address_postal_code;
		string2 provider_business_practice_location_address_country_code;
		string20 provider_business_practice_location_address_telephone_number;
		string20 provider_business_practice_location_address_fax_number;
		string10 provider_enumeration_date;
		string10 last_update_date;
		string2 npi_deactivation_reason_code;
		string10 npi_deactivation_date;
		string10 npi_reactivation_date;
		string1 provider_gender_code;
		string35 authorized_official_last_name;
		string20 authorized_official_first_name;
		string20 authorized_official_middle_name;
		string35 authorized_official_title_or_position;
		string20 authorized_official_telephone_number;
		dataset (taxnomy) t {MAXCOUNT(15)};
		dataset (otherp)	p	{MAXCOUNT(50)};
		string1 is_sole_proprietor;
		string1 is_organization_subpart;
		string70 parent_organization_lbn;
		string9 parent_organization_tin;
		string5 authorized_official_name_prefix;
		string5 authorized_official_name_suffix;
		string20 authorized_official_credential;
		dataset (tax_desc) ta {MAXCOUNT(15)};
		string12 entity_type_desc;
		string11 deactivation_reason_desc;
		string26 organization_name_type_desc;
		string17 last_name_type_desc;
		string50 mailing_country_desc;
		string50 practice_location_country_desc;
		dataset (pid_desc) pid {MAXCOUNT(50)};		
		Address.layout_clean_name clean_name_provider;
		Address.layout_clean_name clean_name_provider_other;
		Address.layout_clean_name clean_name_authorized_official;
		string10 cleanmailingphone;
		string10 cleanlocationphone;
		unsigned8 rawaid_mailing;
		unsigned8 aceaid_mailing;
		string100 mailing_prep_address1;
		string50 mailing_prep_addresslast;
		unsigned8 rawaid_location;
		unsigned8 aceaid_location;
		string100 location_prep_address1;
		string50 location_prep_addresslast;
		Address.layout_clean182_fips clean_mailing_address;
		Address.layout_clean182_fips clean_location_address;
		Address.layout_clean182_fips clean_norm_address;
	END;
	
	EXPORT NPI_Batch_Out := RECORD
		string20 acctno;
		string10 npi;
		string12 entity_type_desc;
		string20 provider_first_name;
		string20 provider_middle_name;
		string35 provider_last_name;
		string20 provider_credential_text;
		string70 provider_organization_name;
		string70 provider_other_organization_name;
		string10 provider_enumeration_date;
		string55 provider_first_line_business_mailing_address;
		string55 provider_second_line_business_mailing_address;
		string40 provider_business_mailing_address_city_name;
		string40 provider_business_mailing_address_state_name;
		string20 provider_business_mailing_address_postal_code;
		string20 provider_business_mailing_address_telephone_number;
		string20 provider_business_mailing_address_fax_number;
		string55 provider_first_line_business_practice_location_address;
		string55 provider_second_line_business_practice_location_address;
		string40 provider_business_practice_location_address_city_name;
		string40 provider_business_practice_location_address_state_name;
		string20 provider_business_practice_location_address_postal_code;
		string20 provider_business_practice_location_address_telephone_number;
		string20 provider_business_practice_location_address_fax_number;
		string1 is_sole_proprietor;
		string11 deactivation_reason_desc;
		string10 npi_deactivation_date;
		string10 npi_reactivation_date;
		string10 replacement_npi;
		string100 primary_taxonomy_description;
		string10 primary_taxonomy_code;
		string100 taxonomy_desc2;
		string10 healthcare_provider_taxonomy_code_2;
		string100 taxonomy_desc3;
		string10 healthcare_provider_taxonomy_code_3;
		string28 other_pid_issuer_desc_1;
		string80 other_provider_identifier_1;
		string2 other_provider_identifier_state_1;
		string28 other_pid_issuer_desc_2;
		string80 other_provider_identifier_2;
		string2 other_provider_identifier_state_2;
		string28 other_pid_issuer_desc_3;
		string80 other_provider_identifier_3;
		string2 other_provider_identifier_state_3;
		string20 provider_license_number_1;
		string2 provider_license_number_state_code_1;
		string20 provider_license_number_2;
		string2 provider_license_number_state_code_2;
		string20 provider_license_number_3;
		string2 provider_license_number_state_code_3;
		unsigned6 did;
		unsigned6 bdid;
		boolean	 TaxonomyVerified := false;
		boolean	 Taxonomy1Verified := false;
		boolean	 Taxonomy2Verified := false;
		boolean	 Taxonomy3Verified := false;
		boolean	 Taxonomy4Verified := false;
		boolean	 Taxonomy5Verified := false;
		string10 taxonomy_code_1;
		string100 taxonomy_desc_1;
		string10 taxonomy_code_2;
		string100 taxonomy_desc_2;
		string10 taxonomy_code_3;
		string100 taxonomy_desc_3;
		string10 taxonomy_code_4;
		string100 taxonomy_desc_4;
		string10 taxonomy_code_5;
		string100 taxonomy_desc_5;
		string10 taxonomy_code_6;
		string100 taxonomy_desc_6;
		string10 taxonomy_code_7;
		string100 taxonomy_desc_7;
		string10 taxonomy_code_8;
		string100 taxonomy_desc_8;
		string10 taxonomy_code_9;
		string100 taxonomy_desc_9;
		string10 taxonomy_code_10;
		string100 taxonomy_desc_10;
		string10 taxonomy_code_11;
		string100 taxonomy_desc_11;
		string10 taxonomy_code_12;
		string100 taxonomy_desc_12;
		string10 taxonomy_code_13;
		string100 taxonomy_desc_13;
		string10 taxonomy_code_14;
		string100 taxonomy_desc_14;
		string10 taxonomy_code_15;
		string100 taxonomy_desc_15;
	END;
end;