//HPCC Systems KEL Compiler Version 1.2.1-dev
IMPORT KEL12 AS KEL;
IMPORT B_Account_1,B_Tradeline_1,CFG_graph,E_Account,E_Account_Tradeline,E_Tradeline FROM Business_Credit_KEL;
IMPORT * FROM KEL12.Null;
EXPORT B_Tradeline(CFG_graph.FDCDataset __in = CFG_graph.FDCDefault, CFG_graph __cfg = CFG_graph) := MODULE
  SHARED VIRTUAL TYPEOF(B_Account_1(__in,__cfg).__ENH_Account_1) __ENH_Account_1 := B_Account_1(__in,__cfg).__ENH_Account_1;
  SHARED VIRTUAL TYPEOF(E_Account_Tradeline(__in,__cfg).__Result) __E_Account_Tradeline := E_Account_Tradeline(__in,__cfg).__Result;
  SHARED VIRTUAL TYPEOF(B_Tradeline_1(__in,__cfg).__ENH_Tradeline_1) __ENH_Tradeline_1 := B_Tradeline_1(__in,__cfg).__ENH_Tradeline_1;
  SHARED __EE9610632 := __ENH_Tradeline_1;
  SHARED __EE9611185 := __ENH_Account_1;
  SHARED __EE9611183 := __E_Account_Tradeline;
  SHARED __EE9617402 := __EE9611183(__NN(__EE9611183._trade_) AND __NN(__EE9611183._acc_));
  SHARED __ST9613788_Layout := RECORD
    KEL.typ.nuid UID;
    KEL.typ.nunk _seq_;
    KEL.typ.nunk _ultid_;
    KEL.typ.nunk _orgid_;
    KEL.typ.nunk _seleid_;
    KEL.typ.nunk _proxid_;
    KEL.typ.nunk _powid_;
    KEL.typ.nunk _empid_;
    KEL.typ.nunk _dotid_;
    KEL.typ.nunk _ultscore_;
    KEL.typ.nunk _orgscore_;
    KEL.typ.nunk _selescore_;
    KEL.typ.nunk _proxscore_;
    KEL.typ.nunk _powscore_;
    KEL.typ.nunk _empscore_;
    KEL.typ.nunk _dotscore_;
    KEL.typ.nunk _ultweight_;
    KEL.typ.nunk _orgweight_;
    KEL.typ.nunk _seleweight_;
    KEL.typ.nunk _proxweight_;
    KEL.typ.nunk _powweight_;
    KEL.typ.nunk _empweight_;
    KEL.typ.nunk _dotweight_;
    KEL.typ.nkdate _dt__first__seen_;
    KEL.typ.nkdate _dt__last__seen_;
    KEL.typ.nkdate _dt__vendor__first__reported_;
    KEL.typ.nkdate _dt__vendor__last__reported_;
    KEL.typ.nkdate _dt__datawarehouse__first__reported_;
    KEL.typ.nkdate _dt__datawarehouse__last__reported_;
    KEL.typ.nunk _did_;
    KEL.typ.nunk _did__score_;
    KEL.typ.nint Account_Balance_;
    KEL.typ.nint Account_Utilization_;
    KEL.typ.nint Amount_Recieved_Monthly_;
    KEL.typ.nint Amount_Scheduled_Monthly_;
    KEL.typ.nint Balance12_Month_;
    KEL.typ.nint Balance12_Month_Util_;
    KEL.typ.nint Balance24_Month_;
    KEL.typ.nint Balance24_Month_Util_;
    KEL.typ.nint Balloon_Payment_Amount_;
    KEL.typ.nkdate Balloon_Payment_Date_;
    KEL.typ.nint Chargeoff_Amount_;
    KEL.typ.nkdate Chargeoff_Date_;
    KEL.typ.nint Current_Credit_Limit_;
    KEL.typ.nint Current_P_D_Amount_;
    KEL.typ.nint Current_Payment_Status_;
    KEL.typ.nint D_P_D01_Amount_Account_;
    KEL.typ.nint D_P_D121_Amount_Account_;
    KEL.typ.nint D_P_D31_Amount_Account_;
    KEL.typ.nint D_P_D61_Amount_Account_;
    KEL.typ.nint D_P_D91_Amount_Account_;
    KEL.typ.nkdate Date_Account_Opened_;
    KEL.typ.nkdate Date_Closed_;
    KEL.typ.nkdate Date_Closed_Estimated_;
    KEL.typ.nint Guarantor_Count_;
    KEL.typ.bool Has_Closed_ := FALSE;
    KEL.typ.bool Has_Positive_Balance12_Month_ := FALSE;
    KEL.typ.bool Has_Positive_Balance24_Month_ := FALSE;
    KEL.typ.bool Has_Positive_Balance36_Month_ := FALSE;
    KEL.typ.bool Has_Positive_Balance3_Month_ := FALSE;
    KEL.typ.bool Has_Positive_Balance60_Month_ := FALSE;
    KEL.typ.bool Has_Positive_Balance6_Month_ := FALSE;
    KEL.typ.bool Has_Positive_Balance84_Month_ := FALSE;
    KEL.typ.bool Has_Positive_Balance_Ever_ := FALSE;
    KEL.typ.nint High_Balance03_M_;
    KEL.typ.nint High_Balance06_M_;
    KEL.typ.nint High_Balance12_M_;
    KEL.typ.nint High_Balance24_M_;
    KEL.typ.nint High_Balance36_M_;
    KEL.typ.nint High_Balance60_M_;
    KEL.typ.nint High_Balance84_M_;
    KEL.typ.nint High_Balance_Ever_;
    KEL.typ.nint Highest_Utilized_Amount_;
    KEL.typ.nint Hist03_M_Credit_Limit_;
    KEL.typ.ntyp(E_Tradeline().Typ) Hist03_M_Tradeline_;
    KEL.typ.nint Hist06_M_Credit_Limit_;
    KEL.typ.ntyp(E_Tradeline().Typ) Hist06_M_Tradeline_;
    KEL.typ.nint Hist12_M_Credit_Limit_;
    KEL.typ.ntyp(E_Tradeline().Typ) Hist12_M_Tradeline_;
    KEL.typ.nint Hist24_M_Credit_Limit_;
    KEL.typ.ntyp(E_Tradeline().Typ) Hist24_M_Tradeline_;
    KEL.typ.nint Hist36_M_Credit_Limit_;
    KEL.typ.ntyp(E_Tradeline().Typ) Hist36_M_Tradeline_;
    KEL.typ.nint Hist60_M_Credit_Limit_;
    KEL.typ.ntyp(E_Tradeline().Typ) Hist60_M_Tradeline_;
    KEL.typ.nint Hist84_M_Credit_Limit_;
    KEL.typ.ntyp(E_Tradeline().Typ) Hist84_M_Tradeline_;
    KEL.typ.nbool Is_Active_;
    KEL.typ.nbool Is_Card_;
    KEL.typ.bool Is_Chargeoff_ := FALSE;
    KEL.typ.nbool Is_Closed_With_Balance_;
    KEL.typ.nbool Is_Delinquent_;
    KEL.typ.bool Is_Gov_Guaranteed_ := FALSE;
    KEL.typ.nbool Is_Inactive_;
    KEL.typ.nbool Is_Installment_;
    KEL.typ.bool Is_Involuntary_Closure_ := FALSE;
    KEL.typ.nbool Is_Lease_;
    KEL.typ.nbool Is_Letter_;
    KEL.typ.nbool Is_Line_;
    KEL.typ.nbool Is_Loan_;
    KEL.typ.nbool Is_O_Line_;
    KEL.typ.nbool Is_Open_;
    KEL.typ.nbool Is_Open12_Month_;
    KEL.typ.nbool Is_Open24_Month_;
    KEL.typ.nbool Is_Open36_Month_;
    KEL.typ.nbool Is_Open3_Month_;
    KEL.typ.nbool Is_Open60_Month_;
    KEL.typ.nbool Is_Open6_Month_;
    KEL.typ.nbool Is_Open84_Month_;
    KEL.typ.nbool Is_Other_;
    KEL.typ.nbool Is_Positive_Balance_;
    KEL.typ.nbool Is_Positive_Balance03_M_;
    KEL.typ.nbool Is_Positive_Balance06_M_;
    KEL.typ.nbool Is_Positive_Balance12_M_;
    KEL.typ.nbool Is_Positive_Balance24_M_;
    KEL.typ.nbool Is_Positive_Balance36_M_;
    KEL.typ.nbool Is_Positive_Balance60_M_;
    KEL.typ.nbool Is_Positive_Balance84_M_;
    KEL.typ.nbool Is_Revolving_Account_;
    KEL.typ.nbool Is_Satisfactory_;
    KEL.typ.nbool Is_Stale_;
    KEL.typ.nbool Is_Valid_Account_Utilization_;
    KEL.typ.nbool Is_Valid_Account_Utilization03_M_;
    KEL.typ.nkdate Last_Cycle_End_Date_;
    KEL.typ.nint Limit12_Month_;
    KEL.typ.nint Limit24_Month_;
    KEL.typ.nint Min_Days_From_One_Year_;
    KEL.typ.nint Min_Days_From_One_Year_Util_;
    KEL.typ.nint Min_Days_From_Two_Years_;
    KEL.typ.nint Min_Days_From_Two_Years_Util_;
    KEL.typ.nint Months_Closed_;
    KEL.typ.nkdate Most_Recent_Delinquency_Date_;
    KEL.typ.nkdate Most_Recent_Tradeline_Date_;
    KEL.typ.bool One_Year_Tradeline_Exists_ := FALSE;
    KEL.typ.bool One_Year_Tradeline_Exists_Util_ := FALSE;
    KEL.typ.bool Open1_Year_Ago_ := FALSE;
    KEL.typ.bool Open2_Years_Ago_ := FALSE;
    KEL.typ.nbool Opened_Last03_Month_;
    KEL.typ.nbool Opened_Last06_Month_;
    KEL.typ.nbool Opened_Last12_Month_;
    KEL.typ.nbool Opened_Last24_Month_;
    KEL.typ.nbool Opened_Last36_Month_;
    KEL.typ.nbool Opened_Last60_Month_;
    KEL.typ.nbool Opened_Last84_Month_;
    KEL.typ.nint Original_Credit_Limit_;
    KEL.typ.nint Principal_Count_;
    KEL.typ.bool Two_Year_Tradeline_Exists_ := FALSE;
    KEL.typ.bool Two_Year_Tradeline_Exists_Util_ := FALSE;
    KEL.typ.bool Unknown_D_P_D01_Amount_Account_ := FALSE;
    KEL.typ.bool Unknown_D_P_D121_Amount_Account_ := FALSE;
    KEL.typ.bool Unknown_D_P_D31_Amount_Account_ := FALSE;
    KEL.typ.bool Unknown_D_P_D61_Amount_Account_ := FALSE;
    KEL.typ.bool Unknown_D_P_D91_Amount_Account_ := FALSE;
    KEL.typ.bool Unknown_Gov_Guarantee_ := FALSE;
    KEL.typ.nbool Unknown_High_Utilization_;
    KEL.typ.bool Update12_Month_ := FALSE;
    KEL.typ.bool Update24_Month_ := FALSE;
    KEL.typ.bool Update36_Month_ := FALSE;
    KEL.typ.bool Update3_Month_ := FALSE;
    KEL.typ.bool Update60_Month_ := FALSE;
    KEL.typ.bool Update6_Month_ := FALSE;
    KEL.typ.bool Update84_Month_ := FALSE;
    KEL.typ.bool Update_Future12_ := FALSE;
    KEL.typ.bool Update_Future18_ := FALSE;
    KEL.typ.bool Update_Future24_ := FALSE;
    KEL.typ.bool Update_Future36_ := FALSE;
    KEL.typ.bool Update_Future6_ := FALSE;
    KEL.typ.nint Worst12_;
    KEL.typ.nint Worst24_;
    KEL.typ.nint Worst3_;
    KEL.typ.nint Worst36_;
    KEL.typ.nint Worst6_;
    KEL.typ.nint Worst60_;
    KEL.typ.nint Worst84_;
    KEL.typ.nint Worst_Ever_;
    KEL.typ.nint Worst_Future12_;
    KEL.typ.nint Worst_Future18_;
    KEL.typ.nint Worst_Future24_;
    KEL.typ.nint Worst_Future36_;
    KEL.typ.nint Worst_Future6_;
    KEL.typ.ntyp(E_Account().Typ) _acc_;
    KEL.typ.ntyp(E_Tradeline().Typ) _trade_;
    KEL.typ.int __RecordCount := 0;
  END;
  __JC9617420(B_Account_1(__in,__cfg).__ST217337_Layout __EE9611185, E_Account_Tradeline(__in,__cfg).Layout __EE9617402) := __EEQP(__EE9617402._acc_,__EE9611185.UID);
  __ST9613788_Layout __JT9617420(B_Account_1(__in,__cfg).__ST217337_Layout __l, E_Account_Tradeline(__in,__cfg).Layout __r) := TRANSFORM
    SELF := __l;
    SELF := __r;
  END;
  SHARED __EE9617421 := JOIN(__EE9617402,__EE9611185,__JC9617420(RIGHT,LEFT),__JT9617420(RIGHT,LEFT),INNER,HASH);
  SHARED __ST9612484_Layout := RECORD
    KEL.typ.ntyp(E_Tradeline().Typ) UID;
    KEL.typ.ntyp(E_Account().Typ) _acc_;
    KEL.typ.ntyp(E_Tradeline().Typ) _trade_;
    KEL.typ.nuid U_I_D__1_;
    KEL.typ.nunk _seq_;
    KEL.typ.nunk _ultid_;
    KEL.typ.nunk _orgid_;
    KEL.typ.nunk _seleid_;
    KEL.typ.nunk _proxid_;
    KEL.typ.nunk _powid_;
    KEL.typ.nunk _empid_;
    KEL.typ.nunk _dotid_;
    KEL.typ.nunk _ultscore_;
    KEL.typ.nunk _orgscore_;
    KEL.typ.nunk _selescore_;
    KEL.typ.nunk _proxscore_;
    KEL.typ.nunk _powscore_;
    KEL.typ.nunk _empscore_;
    KEL.typ.nunk _dotscore_;
    KEL.typ.nunk _ultweight_;
    KEL.typ.nunk _orgweight_;
    KEL.typ.nunk _seleweight_;
    KEL.typ.nunk _proxweight_;
    KEL.typ.nunk _powweight_;
    KEL.typ.nunk _empweight_;
    KEL.typ.nunk _dotweight_;
    KEL.typ.nkdate _dt__first__seen_;
    KEL.typ.nkdate _dt__last__seen_;
    KEL.typ.nkdate _dt__vendor__first__reported_;
    KEL.typ.nkdate _dt__vendor__last__reported_;
    KEL.typ.nkdate _dt__datawarehouse__first__reported_;
    KEL.typ.nkdate _dt__datawarehouse__last__reported_;
    KEL.typ.nunk _did_;
    KEL.typ.nunk _did__score_;
    KEL.typ.nint Account_Balance_;
    KEL.typ.nint Account_Utilization_;
    KEL.typ.nint Amount_Recieved_Monthly_;
    KEL.typ.nint Amount_Scheduled_Monthly_;
    KEL.typ.nint Balance12_Month_;
    KEL.typ.nint Balance12_Month_Util_;
    KEL.typ.nint Balance24_Month_;
    KEL.typ.nint Balance24_Month_Util_;
    KEL.typ.nint Balloon_Payment_Amount_;
    KEL.typ.nkdate Balloon_Payment_Date_;
    KEL.typ.nint Chargeoff_Amount_;
    KEL.typ.nkdate Chargeoff_Date_;
    KEL.typ.nint Current_Credit_Limit_;
    KEL.typ.nint Current_P_D_Amount_;
    KEL.typ.nint Current_Payment_Status_;
    KEL.typ.nint D_P_D01_Amount_Account_;
    KEL.typ.nint D_P_D121_Amount_Account_;
    KEL.typ.nint D_P_D31_Amount_Account_;
    KEL.typ.nint D_P_D61_Amount_Account_;
    KEL.typ.nint D_P_D91_Amount_Account_;
    KEL.typ.nkdate Date_Account_Opened_;
    KEL.typ.nkdate Date_Closed_;
    KEL.typ.nkdate Date_Closed_Estimated_;
    KEL.typ.nint Guarantor_Count_;
    KEL.typ.bool Has_Closed_ := FALSE;
    KEL.typ.bool Has_Positive_Balance12_Month_ := FALSE;
    KEL.typ.bool Has_Positive_Balance24_Month_ := FALSE;
    KEL.typ.bool Has_Positive_Balance36_Month_ := FALSE;
    KEL.typ.bool Has_Positive_Balance3_Month_ := FALSE;
    KEL.typ.bool Has_Positive_Balance60_Month_ := FALSE;
    KEL.typ.bool Has_Positive_Balance6_Month_ := FALSE;
    KEL.typ.bool Has_Positive_Balance84_Month_ := FALSE;
    KEL.typ.bool Has_Positive_Balance_Ever_ := FALSE;
    KEL.typ.nint High_Balance03_M_;
    KEL.typ.nint High_Balance06_M_;
    KEL.typ.nint High_Balance12_M_;
    KEL.typ.nint High_Balance24_M_;
    KEL.typ.nint High_Balance36_M_;
    KEL.typ.nint High_Balance60_M_;
    KEL.typ.nint High_Balance84_M_;
    KEL.typ.nint High_Balance_Ever_;
    KEL.typ.nint Highest_Utilized_Amount_;
    KEL.typ.nint Hist03_M_Credit_Limit_;
    KEL.typ.ntyp(E_Tradeline().Typ) Hist03_M_Tradeline_;
    KEL.typ.nint Hist06_M_Credit_Limit_;
    KEL.typ.ntyp(E_Tradeline().Typ) Hist06_M_Tradeline_;
    KEL.typ.nint Hist12_M_Credit_Limit_;
    KEL.typ.ntyp(E_Tradeline().Typ) Hist12_M_Tradeline_;
    KEL.typ.nint Hist24_M_Credit_Limit_;
    KEL.typ.ntyp(E_Tradeline().Typ) Hist24_M_Tradeline_;
    KEL.typ.nint Hist36_M_Credit_Limit_;
    KEL.typ.ntyp(E_Tradeline().Typ) Hist36_M_Tradeline_;
    KEL.typ.nint Hist60_M_Credit_Limit_;
    KEL.typ.ntyp(E_Tradeline().Typ) Hist60_M_Tradeline_;
    KEL.typ.nint Hist84_M_Credit_Limit_;
    KEL.typ.ntyp(E_Tradeline().Typ) Hist84_M_Tradeline_;
    KEL.typ.nbool Is_Active_;
    KEL.typ.nbool Is_Card_;
    KEL.typ.bool Is_Chargeoff_ := FALSE;
    KEL.typ.nbool Is_Closed_With_Balance_;
    KEL.typ.nbool Is_Delinquent_;
    KEL.typ.bool Is_Gov_Guaranteed_ := FALSE;
    KEL.typ.nbool Is_Inactive_;
    KEL.typ.nbool Is_Installment_;
    KEL.typ.bool Is_Involuntary_Closure_ := FALSE;
    KEL.typ.nbool Is_Lease_;
    KEL.typ.nbool Is_Letter_;
    KEL.typ.nbool Is_Line_;
    KEL.typ.nbool Is_Loan_;
    KEL.typ.nbool Is_O_Line_;
    KEL.typ.nbool Is_Open_;
    KEL.typ.nbool Is_Open12_Month_;
    KEL.typ.nbool Is_Open24_Month_;
    KEL.typ.nbool Is_Open36_Month_;
    KEL.typ.nbool Is_Open3_Month_;
    KEL.typ.nbool Is_Open60_Month_;
    KEL.typ.nbool Is_Open6_Month_;
    KEL.typ.nbool Is_Open84_Month_;
    KEL.typ.nbool Is_Other_;
    KEL.typ.nbool Is_Positive_Balance_;
    KEL.typ.nbool Is_Positive_Balance03_M_;
    KEL.typ.nbool Is_Positive_Balance06_M_;
    KEL.typ.nbool Is_Positive_Balance12_M_;
    KEL.typ.nbool Is_Positive_Balance24_M_;
    KEL.typ.nbool Is_Positive_Balance36_M_;
    KEL.typ.nbool Is_Positive_Balance60_M_;
    KEL.typ.nbool Is_Positive_Balance84_M_;
    KEL.typ.nbool Is_Revolving_Account_;
    KEL.typ.nbool Is_Satisfactory_;
    KEL.typ.nbool Is_Stale_;
    KEL.typ.nbool Is_Valid_Account_Utilization_;
    KEL.typ.nbool Is_Valid_Account_Utilization03_M_;
    KEL.typ.nkdate Last_Cycle_End_Date_;
    KEL.typ.nint Limit12_Month_;
    KEL.typ.nint Limit24_Month_;
    KEL.typ.nint Min_Days_From_One_Year_;
    KEL.typ.nint Min_Days_From_One_Year_Util_;
    KEL.typ.nint Min_Days_From_Two_Years_;
    KEL.typ.nint Min_Days_From_Two_Years_Util_;
    KEL.typ.nint Months_Closed_;
    KEL.typ.nkdate Most_Recent_Delinquency_Date_;
    KEL.typ.nkdate Most_Recent_Tradeline_Date_;
    KEL.typ.bool One_Year_Tradeline_Exists_ := FALSE;
    KEL.typ.bool One_Year_Tradeline_Exists_Util_ := FALSE;
    KEL.typ.bool Open1_Year_Ago_ := FALSE;
    KEL.typ.bool Open2_Years_Ago_ := FALSE;
    KEL.typ.nbool Opened_Last03_Month_;
    KEL.typ.nbool Opened_Last06_Month_;
    KEL.typ.nbool Opened_Last12_Month_;
    KEL.typ.nbool Opened_Last24_Month_;
    KEL.typ.nbool Opened_Last36_Month_;
    KEL.typ.nbool Opened_Last60_Month_;
    KEL.typ.nbool Opened_Last84_Month_;
    KEL.typ.nint Original_Credit_Limit_;
    KEL.typ.nint Principal_Count_;
    KEL.typ.bool Two_Year_Tradeline_Exists_ := FALSE;
    KEL.typ.bool Two_Year_Tradeline_Exists_Util_ := FALSE;
    KEL.typ.bool Unknown_D_P_D01_Amount_Account_ := FALSE;
    KEL.typ.bool Unknown_D_P_D121_Amount_Account_ := FALSE;
    KEL.typ.bool Unknown_D_P_D31_Amount_Account_ := FALSE;
    KEL.typ.bool Unknown_D_P_D61_Amount_Account_ := FALSE;
    KEL.typ.bool Unknown_D_P_D91_Amount_Account_ := FALSE;
    KEL.typ.bool Unknown_Gov_Guarantee_ := FALSE;
    KEL.typ.nbool Unknown_High_Utilization_;
    KEL.typ.bool Update12_Month_ := FALSE;
    KEL.typ.bool Update24_Month_ := FALSE;
    KEL.typ.bool Update36_Month_ := FALSE;
    KEL.typ.bool Update3_Month_ := FALSE;
    KEL.typ.bool Update60_Month_ := FALSE;
    KEL.typ.bool Update6_Month_ := FALSE;
    KEL.typ.bool Update84_Month_ := FALSE;
    KEL.typ.bool Update_Future12_ := FALSE;
    KEL.typ.bool Update_Future18_ := FALSE;
    KEL.typ.bool Update_Future24_ := FALSE;
    KEL.typ.bool Update_Future36_ := FALSE;
    KEL.typ.bool Update_Future6_ := FALSE;
    KEL.typ.nint Worst12_;
    KEL.typ.nint Worst24_;
    KEL.typ.nint Worst3_;
    KEL.typ.nint Worst36_;
    KEL.typ.nint Worst6_;
    KEL.typ.nint Worst60_;
    KEL.typ.nint Worst84_;
    KEL.typ.nint Worst_Ever_;
    KEL.typ.nint Worst_Future12_;
    KEL.typ.nint Worst_Future18_;
    KEL.typ.nint Worst_Future24_;
    KEL.typ.nint Worst_Future36_;
    KEL.typ.nint Worst_Future6_;
  END;
  SHARED __ST9612484_Layout __ND9617609__Project(__ST9613788_Layout __PP9617422) := TRANSFORM
    SELF.UID := __PP9617422._trade_;
    SELF.U_I_D__1_ := __PP9617422.UID;
    SELF := __PP9617422;
  END;
  SHARED __EE9618342 := PROJECT(__EE9617421,__ND9617609__Project(LEFT));
  SHARED __ST9612863_Layout := RECORD
    KEL.typ.ntyp(E_Tradeline().Typ) UID;
    KEL.typ.nkdate Most_Recent_Tradeline_Date_;
  END;
  SHARED __EE9618356 := PROJECT(__EE9618342,__ST9612863_Layout);
  SHARED __ST9612878_Layout := RECORD
    KEL.typ.nkdate M_A_X___Most_Recent_Tradeline_Date_;
    KEL.typ.ntyp(E_Tradeline().Typ) UID;
  END;
  SHARED __EE9618372 := PROJECT(__CLEANANDDO(__EE9618356,TABLE(__EE9618356,{KEL.Aggregates.MaxNG(__EE9618356.Most_Recent_Tradeline_Date_) M_A_X___Most_Recent_Tradeline_Date_,UID},UID,MERGE)),__ST9612878_Layout);
  SHARED __ST9614720_Layout := RECORD
    KEL.typ.nuid UID;
    KEL.typ.nkdate _load__date_;
    KEL.typ.nstr _sbfe__contributor__number_;
    KEL.typ.nstr _contract__account__number_;
    KEL.typ.nkdate _cycle__end__date_;
    KEL.typ.nstr _segment__identifier_;
    KEL.typ.nstr _file__segment__num_;
    KEL.typ.nstr _parent__sequence__number_;
    KEL.typ.nstr _account__holder__business__name_;
    KEL.typ.nstr _dba_;
    KEL.typ.nstr _company__website_;
    KEL.typ.nint _legal__business__structure_;
    KEL.typ.nkdate _business__established__date_;
    KEL.typ.nint _account__type__reported_;
    KEL.typ.nstr _account__status__1_;
    KEL.typ.nstr _account__status__2_;
    KEL.typ.nkdate _date__account__opened_;
    KEL.typ.nkdate _date__account__closed_;
    KEL.typ.nstr _account__closure__basis_;
    KEL.typ.nkdate _account__expiration__date_;
    KEL.typ.nkdate _last__activity__date_;
    KEL.typ.nstr _last__activity__type_;
    KEL.typ.nstr _recent__activity__indicator_;
    KEL.typ.nint _original__credit__limit_;
    KEL.typ.nint _highest__credit__used_;
    KEL.typ.nint _current__credit__limit_;
    KEL.typ.nunk _reporting__indicator__length_;
    KEL.typ.nstr _payment__interval_;
    KEL.typ.nstr _payment__status__category_;
    KEL.typ.nunk _term__of__account__in__months_;
    KEL.typ.nkdate _first__payment__due__date_;
    KEL.typ.nkdate _final__pyament__due__date_;
    KEL.typ.nunk _original__rate_;
    KEL.typ.nunk _floating__rate_;
    KEL.typ.nunk _grace__period_;
    KEL.typ.nunk _payment__category_;
    KEL.typ.nunk _payment__history__profile__12__months_;
    KEL.typ.nunk _payment__history__profile__13__24__months_;
    KEL.typ.nunk _payment__history__profile__25__36__months_;
    KEL.typ.nunk _payment__history__profile__37__48__months_;
    KEL.typ.nunk _payment__history__length_;
    KEL.typ.nunk _year__to__date__purchases__count_;
    KEL.typ.nunk _lifetime__to__date__purchases__count_;
    KEL.typ.nunk _year__to__date__purchases__sum__amount_;
    KEL.typ.nunk _lifetime__to__date__purchases__sum__amount_;
    KEL.typ.nint _payment__amount__scheduled_;
    KEL.typ.nint _recent__payment__amount_;
    KEL.typ.nkdate _recent__payment__date_;
    KEL.typ.nint _remaining__balance_;
    KEL.typ.nunk _carried__over__amount_;
    KEL.typ.nunk _new__applied__charges_;
    KEL.typ.nint _balloon__payment__due_;
    KEL.typ.nkdate _balloon__payment__due__date_;
    KEL.typ.nkdate _delinquency__date_;
    KEL.typ.nunk _days__delinquent_;
    KEL.typ.nint _past__due__amount_;
    KEL.typ.nunk _maximum__number__of__past__due__aging__amounts__buckets__provided_;
    KEL.typ.nunk _past__due__aging__bucket__type_;
    KEL.typ.nint _past__due__aging__amount__bucket__1_;
    KEL.typ.nint _past__due__aging__amount__bucket__2_;
    KEL.typ.nint _past__due__aging__amount__bucket__3_;
    KEL.typ.nint _past__due__aging__amount__bucket__4_;
    KEL.typ.nint _past__due__aging__amount__bucket__5_;
    KEL.typ.nint _past__due__aging__amount__bucket__6_;
    KEL.typ.nint _past__due__aging__amount__bucket__7_;
    KEL.typ.nunk _maximum__number__of__payment__tracking__cycle__periods__provided_;
    KEL.typ.nunk _payment__tracking__cycle__type_;
    KEL.typ.nunk _payment__tracking__cycle__0__current_;
    KEL.typ.nunk _payment__tracking__cycle__1__1__30__days_;
    KEL.typ.nunk _payment__tracking__cycle__2__31__60__days_;
    KEL.typ.nunk _payment__tracking__cycle__3__61__90__days_;
    KEL.typ.nunk _payment__tracking__cycle__4__91__120__days_;
    KEL.typ.nunk _payment__tracking__cycle__5__121__150days_;
    KEL.typ.nunk _payment__tracking__number__of__times__cycle__6__151__180__days_;
    KEL.typ.nunk _payment__tracking__number__of__times__cycle__7__181__or__greater__days_;
    KEL.typ.nkdate _date__account__was__charged__off_;
    KEL.typ.nint _amount__charged__off__by__creditor_;
    KEL.typ.nstr _charge__off__type__indicator_;
    KEL.typ.nint _total__charge__off__recoveries__to__date_;
    KEL.typ.nstr _government__guarantee__flag_;
    KEL.typ.nint _government__guarantee__category_;
    KEL.typ.nint _portion__of__account__guaranteed__by__government_;
    KEL.typ.nstr _guarantors__indicator_;
    KEL.typ.nint _number__of__guarantors_;
    KEL.typ.nstr _owners__indicator_;
    KEL.typ.nint _number__of__principals_;
    KEL.typ.nunk _account__update__deletion__indicator_;
    KEL.typ.nint Account_Balance_;
    KEL.typ.bool Account_Closed_ := FALSE;
    KEL.typ.kdate Current_Date_Month_ := 0;
    KEL.typ.nint Cycle_Balance_;
    KEL.typ.nint Cycle_End_Month_;
    KEL.typ.nkdate Cycle_End_Month_Date_;
    KEL.typ.nint D_P_D01_Amount_;
    KEL.typ.nint D_P_D121_Amount_;
    KEL.typ.nint D_P_D31_Amount_;
    KEL.typ.nint D_P_D61_Amount_;
    KEL.typ.nint D_P_D91_Amount_;
    KEL.typ.nkdate Date_Reported_Closed_;
    KEL.typ.nint Days_Ago_;
    KEL.typ.nint Days_From_One_Year_;
    KEL.typ.nint Days_From_Two_Years_;
    KEL.typ.nbool Good_Average_Date_;
    KEL.typ.nbool Good_Utilization_Ave_Tradeline_;
    KEL.typ.nbool Is12_Month_;
    KEL.typ.nbool Is12_Months_Ago_;
    KEL.typ.nbool Is24_Month_;
    KEL.typ.nbool Is24_Months_Ago_;
    KEL.typ.nbool Is36_Month_;
    KEL.typ.nbool Is3_Month_;
    KEL.typ.nbool Is60_Month_;
    KEL.typ.nbool Is6_Month_;
    KEL.typ.nbool Is84_Month_;
    KEL.typ.nbool Is_Chargeoff_;
    KEL.typ.nbool Is_Closed_;
    KEL.typ.nbool Is_Closed_Involuntary_;
    KEL.typ.nbool Is_Gov_Guaranteed_;
    KEL.typ.nbool Is_Last_Cycle_;
    KEL.typ.nbool Is_Last_Monthly_Report_;
    KEL.typ.nbool Is_One_Year_Tradeline_;
    KEL.typ.nbool Is_One_Year_Tradeline_Util_;
    KEL.typ.nbool Is_Two_Year_Tradeline_;
    KEL.typ.nbool Is_Two_Year_Tradeline_Util_;
    KEL.typ.float Months_Between_Payment_ := 0.0;
    KEL.typ.nint Months_Since_Trade_;
    KEL.typ.nint Original_Credit_Limit_;
    KEL.typ.nint Past_Due_Amount_;
    KEL.typ.nint Past_Due_Amount_Bucket1_;
    KEL.typ.nint Past_Due_Amount_Bucket2_;
    KEL.typ.nint Past_Due_Amount_Bucket3_;
    KEL.typ.nint Past_Due_Amount_Bucket4_;
    KEL.typ.nint Past_Due_Amount_Bucket5_;
    KEL.typ.nint Past_Due_Amount_Bucket6_;
    KEL.typ.nint Past_Due_Amount_Bucket7_;
    KEL.typ.int Past_Due_Amount_Status_ := 0;
    KEL.typ.int Payment_Status_ := 0;
    KEL.typ.nbool Shows_Closed_Account_;
    KEL.typ.nbool Unknown_D_P_D01_Amount_;
    KEL.typ.nbool Unknown_D_P_D121_Amount_;
    KEL.typ.nbool Unknown_D_P_D31_Amount_;
    KEL.typ.nbool Unknown_D_P_D61_Amount_;
    KEL.typ.nbool Unknown_D_P_D91_Amount_;
    KEL.typ.nfloat Utilization_Percent_;
    KEL.typ.nint _acc_;
    KEL.typ.nkdate M_A_X___Most_Recent_Tradeline_Date_;
    KEL.typ.ntyp(E_Tradeline().Typ) U_I_D__1_;
    KEL.typ.int __RecordCount := 0;
  END;
  __JC9618378(B_Tradeline_1(__in,__cfg).__ST255623_Layout __EE9610632, __ST9612878_Layout __EE9618372) := __EEQP(__EE9610632.UID,__EE9618372.UID);
  __ST9614720_Layout __JT9618378(B_Tradeline_1(__in,__cfg).__ST255623_Layout __l, __ST9612878_Layout __r) := TRANSFORM
    SELF.U_I_D__1_ := __r.UID;
    SELF := __l;
    SELF := __r;
  END;
  SHARED __EE9618379 := JOIN(__EE9610632,__EE9618372,__JC9618378(LEFT,RIGHT),__JT9618378(LEFT,RIGHT),LEFT OUTER,HASH);
  EXPORT __ST215763_Layout := RECORD
    KEL.typ.nuid UID;
    KEL.typ.nkdate _load__date_;
    KEL.typ.nstr _sbfe__contributor__number_;
    KEL.typ.nstr _contract__account__number_;
    KEL.typ.nkdate _cycle__end__date_;
    KEL.typ.nstr _segment__identifier_;
    KEL.typ.nstr _file__segment__num_;
    KEL.typ.nstr _parent__sequence__number_;
    KEL.typ.nstr _account__holder__business__name_;
    KEL.typ.nstr _dba_;
    KEL.typ.nstr _company__website_;
    KEL.typ.nint _legal__business__structure_;
    KEL.typ.nkdate _business__established__date_;
    KEL.typ.nint _account__type__reported_;
    KEL.typ.nstr _account__status__1_;
    KEL.typ.nstr _account__status__2_;
    KEL.typ.nkdate _date__account__opened_;
    KEL.typ.nkdate _date__account__closed_;
    KEL.typ.nstr _account__closure__basis_;
    KEL.typ.nkdate _account__expiration__date_;
    KEL.typ.nkdate _last__activity__date_;
    KEL.typ.nstr _last__activity__type_;
    KEL.typ.nstr _recent__activity__indicator_;
    KEL.typ.nint _original__credit__limit_;
    KEL.typ.nint _highest__credit__used_;
    KEL.typ.nint _current__credit__limit_;
    KEL.typ.nunk _reporting__indicator__length_;
    KEL.typ.nstr _payment__interval_;
    KEL.typ.nstr _payment__status__category_;
    KEL.typ.nunk _term__of__account__in__months_;
    KEL.typ.nkdate _first__payment__due__date_;
    KEL.typ.nkdate _final__pyament__due__date_;
    KEL.typ.nunk _original__rate_;
    KEL.typ.nunk _floating__rate_;
    KEL.typ.nunk _grace__period_;
    KEL.typ.nunk _payment__category_;
    KEL.typ.nunk _payment__history__profile__12__months_;
    KEL.typ.nunk _payment__history__profile__13__24__months_;
    KEL.typ.nunk _payment__history__profile__25__36__months_;
    KEL.typ.nunk _payment__history__profile__37__48__months_;
    KEL.typ.nunk _payment__history__length_;
    KEL.typ.nunk _year__to__date__purchases__count_;
    KEL.typ.nunk _lifetime__to__date__purchases__count_;
    KEL.typ.nunk _year__to__date__purchases__sum__amount_;
    KEL.typ.nunk _lifetime__to__date__purchases__sum__amount_;
    KEL.typ.nint _payment__amount__scheduled_;
    KEL.typ.nint _recent__payment__amount_;
    KEL.typ.nkdate _recent__payment__date_;
    KEL.typ.nint _remaining__balance_;
    KEL.typ.nunk _carried__over__amount_;
    KEL.typ.nunk _new__applied__charges_;
    KEL.typ.nint _balloon__payment__due_;
    KEL.typ.nkdate _balloon__payment__due__date_;
    KEL.typ.nkdate _delinquency__date_;
    KEL.typ.nunk _days__delinquent_;
    KEL.typ.nint _past__due__amount_;
    KEL.typ.nunk _maximum__number__of__past__due__aging__amounts__buckets__provided_;
    KEL.typ.nunk _past__due__aging__bucket__type_;
    KEL.typ.nint _past__due__aging__amount__bucket__1_;
    KEL.typ.nint _past__due__aging__amount__bucket__2_;
    KEL.typ.nint _past__due__aging__amount__bucket__3_;
    KEL.typ.nint _past__due__aging__amount__bucket__4_;
    KEL.typ.nint _past__due__aging__amount__bucket__5_;
    KEL.typ.nint _past__due__aging__amount__bucket__6_;
    KEL.typ.nint _past__due__aging__amount__bucket__7_;
    KEL.typ.nunk _maximum__number__of__payment__tracking__cycle__periods__provided_;
    KEL.typ.nunk _payment__tracking__cycle__type_;
    KEL.typ.nunk _payment__tracking__cycle__0__current_;
    KEL.typ.nunk _payment__tracking__cycle__1__1__30__days_;
    KEL.typ.nunk _payment__tracking__cycle__2__31__60__days_;
    KEL.typ.nunk _payment__tracking__cycle__3__61__90__days_;
    KEL.typ.nunk _payment__tracking__cycle__4__91__120__days_;
    KEL.typ.nunk _payment__tracking__cycle__5__121__150days_;
    KEL.typ.nunk _payment__tracking__number__of__times__cycle__6__151__180__days_;
    KEL.typ.nunk _payment__tracking__number__of__times__cycle__7__181__or__greater__days_;
    KEL.typ.nkdate _date__account__was__charged__off_;
    KEL.typ.nint _amount__charged__off__by__creditor_;
    KEL.typ.nstr _charge__off__type__indicator_;
    KEL.typ.nint _total__charge__off__recoveries__to__date_;
    KEL.typ.nstr _government__guarantee__flag_;
    KEL.typ.nint _government__guarantee__category_;
    KEL.typ.nint _portion__of__account__guaranteed__by__government_;
    KEL.typ.nstr _guarantors__indicator_;
    KEL.typ.nint _number__of__guarantors_;
    KEL.typ.nstr _owners__indicator_;
    KEL.typ.nint _number__of__principals_;
    KEL.typ.nunk _account__update__deletion__indicator_;
    KEL.typ.nint Account_Balance_;
    KEL.typ.bool Account_Closed_ := FALSE;
    KEL.typ.kdate Current_Date_Month_ := 0;
    KEL.typ.nint Cycle_Balance_;
    KEL.typ.nint Cycle_End_Month_;
    KEL.typ.nkdate Cycle_End_Month_Date_;
    KEL.typ.nint D_P_D01_Amount_;
    KEL.typ.nint D_P_D121_Amount_;
    KEL.typ.nint D_P_D31_Amount_;
    KEL.typ.nint D_P_D61_Amount_;
    KEL.typ.nint D_P_D91_Amount_;
    KEL.typ.nkdate Date_Reported_Closed_;
    KEL.typ.nint Days_Ago_;
    KEL.typ.nint Days_From_One_Year_;
    KEL.typ.nint Days_From_Two_Years_;
    KEL.typ.nbool Good_Average_Date_;
    KEL.typ.nbool Good_Utilization_Ave_Tradeline_;
    KEL.typ.nbool Is12_Month_;
    KEL.typ.nbool Is12_Months_Ago_;
    KEL.typ.nbool Is24_Month_;
    KEL.typ.nbool Is24_Months_Ago_;
    KEL.typ.nbool Is36_Month_;
    KEL.typ.nbool Is3_Month_;
    KEL.typ.nbool Is60_Month_;
    KEL.typ.nbool Is6_Month_;
    KEL.typ.nbool Is84_Month_;
    KEL.typ.nbool Is_Chargeoff_;
    KEL.typ.nbool Is_Closed_;
    KEL.typ.nbool Is_Closed_Involuntary_;
    KEL.typ.nbool Is_Gov_Guaranteed_;
    KEL.typ.nbool Is_Last_Cycle_;
    KEL.typ.nbool Is_Last_Monthly_Report_;
    KEL.typ.nbool Is_Most_Recent_Tradeline_;
    KEL.typ.nbool Is_One_Year_Tradeline_;
    KEL.typ.nbool Is_One_Year_Tradeline_Util_;
    KEL.typ.nbool Is_Two_Year_Tradeline_;
    KEL.typ.nbool Is_Two_Year_Tradeline_Util_;
    KEL.typ.float Months_Between_Payment_ := 0.0;
    KEL.typ.nint Months_Since_Trade_;
    KEL.typ.nint Original_Credit_Limit_;
    KEL.typ.nint Past_Due_Amount_;
    KEL.typ.nint Past_Due_Amount_Bucket1_;
    KEL.typ.nint Past_Due_Amount_Bucket2_;
    KEL.typ.nint Past_Due_Amount_Bucket3_;
    KEL.typ.nint Past_Due_Amount_Bucket4_;
    KEL.typ.nint Past_Due_Amount_Bucket5_;
    KEL.typ.nint Past_Due_Amount_Bucket6_;
    KEL.typ.nint Past_Due_Amount_Bucket7_;
    KEL.typ.int Past_Due_Amount_Status_ := 0;
    KEL.typ.int Payment_Status_ := 0;
    KEL.typ.nbool Shows_Closed_Account_;
    KEL.typ.nbool Shows_Open_Account_;
    KEL.typ.nbool Unknown_D_P_D01_Amount_;
    KEL.typ.nbool Unknown_D_P_D121_Amount_;
    KEL.typ.nbool Unknown_D_P_D31_Amount_;
    KEL.typ.nbool Unknown_D_P_D61_Amount_;
    KEL.typ.nbool Unknown_D_P_D91_Amount_;
    KEL.typ.nfloat Utilization_Percent_;
    KEL.typ.nint _acc_;
    KEL.typ.int __RecordCount := 0;
  END;
  SHARED __ST215763_Layout __ND9619131__Project(__ST9614720_Layout __PP9618380) := TRANSFORM
    SELF.Is_Most_Recent_Tradeline_ := __OP2(__PP9618380._load__date_,=,__PP9618380.M_A_X___Most_Recent_Tradeline_Date_);
    SELF.Shows_Open_Account_ := __AND(__NOT(__NT(__PP9618380._date__account__opened_)),__OP2(__PP9618380._date__account__opened_,<=,__CN(__cfg.CurrentDate)));
    SELF := __PP9618380;
  END;
  EXPORT __ENH_Tradeline := PROJECT(__EE9618379,__ND9619131__Project(LEFT));
  SHARED __EE9642924 := __ENH_Tradeline;
  SHARED IDX_Tradeline_UID_Layout := RECORD
    KEL.typ.uid UID;
    __EE9642924._load__date_;
    __EE9642924._sbfe__contributor__number_;
    __EE9642924._contract__account__number_;
    __EE9642924._cycle__end__date_;
    __EE9642924._segment__identifier_;
    __EE9642924._file__segment__num_;
    __EE9642924._parent__sequence__number_;
    __EE9642924._account__holder__business__name_;
    __EE9642924._dba_;
    __EE9642924._company__website_;
    __EE9642924._legal__business__structure_;
    __EE9642924._business__established__date_;
    __EE9642924._account__type__reported_;
    __EE9642924._account__status__1_;
    __EE9642924._account__status__2_;
    __EE9642924._date__account__opened_;
    __EE9642924._date__account__closed_;
    __EE9642924._account__closure__basis_;
    __EE9642924._account__expiration__date_;
    __EE9642924._last__activity__date_;
    __EE9642924._last__activity__type_;
    __EE9642924._recent__activity__indicator_;
    __EE9642924._original__credit__limit_;
    __EE9642924._highest__credit__used_;
    __EE9642924._current__credit__limit_;
    __EE9642924._reporting__indicator__length_;
    __EE9642924._payment__interval_;
    __EE9642924._payment__status__category_;
    __EE9642924._term__of__account__in__months_;
    __EE9642924._first__payment__due__date_;
    __EE9642924._final__pyament__due__date_;
    __EE9642924._original__rate_;
    __EE9642924._floating__rate_;
    __EE9642924._grace__period_;
    __EE9642924._payment__category_;
    __EE9642924._payment__history__profile__12__months_;
    __EE9642924._payment__history__profile__13__24__months_;
    __EE9642924._payment__history__profile__25__36__months_;
    __EE9642924._payment__history__profile__37__48__months_;
    __EE9642924._payment__history__length_;
    __EE9642924._year__to__date__purchases__count_;
    __EE9642924._lifetime__to__date__purchases__count_;
    __EE9642924._year__to__date__purchases__sum__amount_;
    __EE9642924._lifetime__to__date__purchases__sum__amount_;
    __EE9642924._payment__amount__scheduled_;
    __EE9642924._recent__payment__amount_;
    __EE9642924._recent__payment__date_;
    __EE9642924._remaining__balance_;
    __EE9642924._carried__over__amount_;
    __EE9642924._new__applied__charges_;
    __EE9642924._balloon__payment__due_;
    __EE9642924._balloon__payment__due__date_;
    __EE9642924._delinquency__date_;
    __EE9642924._days__delinquent_;
    __EE9642924._past__due__amount_;
    __EE9642924._maximum__number__of__past__due__aging__amounts__buckets__provided_;
    __EE9642924._past__due__aging__bucket__type_;
    __EE9642924._past__due__aging__amount__bucket__1_;
    __EE9642924._past__due__aging__amount__bucket__2_;
    __EE9642924._past__due__aging__amount__bucket__3_;
    __EE9642924._past__due__aging__amount__bucket__4_;
    __EE9642924._past__due__aging__amount__bucket__5_;
    __EE9642924._past__due__aging__amount__bucket__6_;
    __EE9642924._past__due__aging__amount__bucket__7_;
    __EE9642924._maximum__number__of__payment__tracking__cycle__periods__provided_;
    __EE9642924._payment__tracking__cycle__type_;
    __EE9642924._payment__tracking__cycle__0__current_;
    __EE9642924._payment__tracking__cycle__1__1__30__days_;
    __EE9642924._payment__tracking__cycle__2__31__60__days_;
    __EE9642924._payment__tracking__cycle__3__61__90__days_;
    __EE9642924._payment__tracking__cycle__4__91__120__days_;
    __EE9642924._payment__tracking__cycle__5__121__150days_;
    __EE9642924._payment__tracking__number__of__times__cycle__6__151__180__days_;
    __EE9642924._payment__tracking__number__of__times__cycle__7__181__or__greater__days_;
    __EE9642924._date__account__was__charged__off_;
    __EE9642924._amount__charged__off__by__creditor_;
    __EE9642924._charge__off__type__indicator_;
    __EE9642924._total__charge__off__recoveries__to__date_;
    __EE9642924._government__guarantee__flag_;
    __EE9642924._government__guarantee__category_;
    __EE9642924._portion__of__account__guaranteed__by__government_;
    __EE9642924._guarantors__indicator_;
    __EE9642924._number__of__guarantors_;
    __EE9642924._owners__indicator_;
    __EE9642924._number__of__principals_;
    __EE9642924._account__update__deletion__indicator_;
    __EE9642924.Shows_Open_Account_;
    __EE9642924.Date_Reported_Closed_;
    __EE9642924.Shows_Closed_Account_;
    __EE9642924.Is_Chargeoff_;
    __EE9642924.Is_Closed_;
    __EE9642924.Is_Closed_Involuntary_;
    __EE9642924.Months_Since_Trade_;
    __EE9642924.Is_Last_Cycle_;
    __EE9642924.Account_Balance_;
    __EE9642924.Cycle_Balance_;
    __EE9642924.Account_Closed_;
    __EE9642924.Cycle_End_Month_;
    __EE9642924.Cycle_End_Month_Date_;
    __EE9642924.Current_Date_Month_;
    __EE9642924.Good_Average_Date_;
    __EE9642924._acc_;
    __EE9642924.Is_Last_Monthly_Report_;
    __EE9642924.Original_Credit_Limit_;
    __EE9642924.Months_Between_Payment_;
    __EE9642924.Is12_Months_Ago_;
    __EE9642924.Days_Ago_;
    __EE9642924.Days_From_One_Year_;
    __EE9642924.Is_One_Year_Tradeline_;
    __EE9642924.Is24_Months_Ago_;
    __EE9642924.Days_From_Two_Years_;
    __EE9642924.Is_Two_Year_Tradeline_;
    __EE9642924.Is_One_Year_Tradeline_Util_;
    __EE9642924.Is_Two_Year_Tradeline_Util_;
    __EE9642924.Utilization_Percent_;
    __EE9642924.Good_Utilization_Ave_Tradeline_;
    __EE9642924.Past_Due_Amount_;
    __EE9642924.Past_Due_Amount_Status_;
    __EE9642924.Payment_Status_;
    __EE9642924.Is3_Month_;
    __EE9642924.Is6_Month_;
    __EE9642924.Is12_Month_;
    __EE9642924.Is24_Month_;
    __EE9642924.Is36_Month_;
    __EE9642924.Is60_Month_;
    __EE9642924.Is84_Month_;
    __EE9642924.Past_Due_Amount_Bucket1_;
    __EE9642924.Past_Due_Amount_Bucket2_;
    __EE9642924.Past_Due_Amount_Bucket3_;
    __EE9642924.Past_Due_Amount_Bucket4_;
    __EE9642924.Past_Due_Amount_Bucket5_;
    __EE9642924.Past_Due_Amount_Bucket6_;
    __EE9642924.Past_Due_Amount_Bucket7_;
    __EE9642924.D_P_D01_Amount_;
    __EE9642924.D_P_D31_Amount_;
    __EE9642924.D_P_D61_Amount_;
    __EE9642924.D_P_D91_Amount_;
    __EE9642924.D_P_D121_Amount_;
    __EE9642924.Is_Most_Recent_Tradeline_;
    __EE9642924.Unknown_D_P_D01_Amount_;
    __EE9642924.Unknown_D_P_D31_Amount_;
    __EE9642924.Unknown_D_P_D61_Amount_;
    __EE9642924.Unknown_D_P_D91_Amount_;
    __EE9642924.Unknown_D_P_D121_Amount_;
    __EE9642924.Is_Gov_Guaranteed_;
    __EE9642924.__RecordCount;
  END;
  EXPORT IDX_Tradeline_UID_BaseFile := PROJECT(__EE9642924,TRANSFORM(IDX_Tradeline_UID_Layout,SELF.UID:=__T(LEFT.UID),SELF:=LEFT));
  EXPORT IDX_Tradeline_UID_Name := '~key::KEL::Business_Credit_KEL::Tradeline::UID';
  EXPORT IDX_Tradeline_UID_From(TYPEOF(IDX_Tradeline_UID_BaseFile) source) := INDEX(source,{UID},{source},IDX_Tradeline_UID_Name);
  EXPORT IDX_Tradeline_UID := IDX_Tradeline_UID_From(IDX_Tradeline_UID_BaseFile);
  EXPORT IDX_Tradeline_UID_Build := BUILD(IDX_Tradeline_UID,OVERWRITE);
  EXPORT __ST9655104_Layout := RECORDOF(IDX_Tradeline_UID);
  EXPORT IDX_Tradeline_UID_Wrapped := PROJECT(IDX_Tradeline_UID,TRANSFORM(__ST215763_Layout,SELF.UID := __CN(LEFT.UID),SELF:=LEFT));
  EXPORT BuildAll := PARALLEL(IDX_Tradeline_UID_Build);
END;
