EXPORT string QuarantineReasons(integer record_type, integer code) := 
	if(record_type = 2, CASE(code,
										1 => 'Unknown addresss',
										2 => 'Initial Type missing',
										3 => 'Future Officer DateTimeEnroute',
										4 => 'Officer DateTimeDispatched before CFS DateTimeReceived',
										5 => 'Future Officer DateTimeArrived',
										6 => 'DateTimeReceived missing',
										7 => 'Future Officer DateTimeCleared',
										8 => 'Missing address',
										9 => 'Low Accuracy',
										10 => 'Both Unit and Officer Name are missing from OFFICER record',
										11 => 'Future DateTimeReceived',
										12 => 'Out of bounds',
										13 => 'Officer DateTimeArrived before CFS DateTimeReceived',
										14 => 'Officer DateTimeEnroute before CFS DateTimeReceived',
										15 => 'Future Officer DateTimeDispatched',
										16 => 'DateTimeReceived before 1900',
										17 => 'Officer DateTimeCleared before CFS DateTimeReceived',
										'Unexpected quarantine code: ' + (string)code),
	if(record_type = 1, CASE(code,
										1 => 'First Date time and time missing',
										2 => 'Unknown geocoding error',
										3 => 'Low Accuracy',
										4 => 'Invalid date string',
										5 => 'First Date Time after Last Date Time',
										6 => 'Future Last Date',
										7 => 'Future Last Date Time',
										8 => 'Invalid time string',
										9 => 'Excessive intersection offset distance',
										10 => 'Missing address',
										11 => 'Last Date Time before 1900',
										12 => 'Unknown addresss',
										13 => 'Out of bounds',
										14 => 'Entire ORI-IR set quarantined',
										15 => 'First Date after Last Date',
										16 => 'First Date Time before 1900',
										17 => 'Future First Date Time',
										18 => 'First Date time did not match date and time',
										19 => 'Entire ORI-IR set quarantined',
										20 => 'Entire ORI-IR set quarantined',
										'Unexpected quarantine code: ' + (string)code),
	if(record_type = 4, CASE(code,
										1 => 'Missing X/Y Coordinates',
										2 => 'Out of bounds',
										3 => 'Future CaptureDateTime',
										'Unexpected quarantine code: ' + (string)code),
	if(record_type = 3, CASE(code,
										1 => 'Missing Address',
										2 => 'Unknown address',
										3 => 'Out of bounds',
										4 => 'Future report date',
										'Unexpected quarantine code: ' + (string)code),
	if(record_type = 7, CASE(code,
										1 => 'Missing Address',
										2 => 'Unknown address',
										'Unexpected quarantine code: ' + (string)code),
	'Unexpected record type')
))));
