export layout_pp_raw_common := record
  unsigned2    penalt;
  unsigned6    did := 0;
  string2      src;
  string8      dt_first_seen;
  string8      dt_last_seen;
  string1      rec_type;
  string2      vendor_id;
	string25	 	 append_phone_type:= '';
  qstring10    phone;
  qstring9     ssn;
  integer4     dob;
  qstring20    fname;
  qstring20    mname;
  qstring20    lname;
  qstring5     name_suffix;
  qstring10    prim_range;
  string2      predir;
  qstring28    prim_name;
  qstring4     suffix;
  string2      postdir;
  qstring10    unit_desig;
  qstring8     sec_range;
  qstring25    city_name;
  string2      st;
  qstring5     zip;
  qstring4     zip4;
  string5      county_code := '';
  string18     county_name := '';
  string1      tnt := ' ';
  unsigned6    hhid := 0;
  STRING120    listed_name := '';
  STRING120    listed_name_targus := '';
  STRING10     listed_phone := '';
  string1      listing_type_res := '';	
  string1      listing_type_bus := '';
  string1      listing_type_gov := '';
  string254    caption_text := '';
  unsigned6    bdid := 0;
  unsigned2	ConfidenceScore := 0; 
  string1		ActiveFlag := '';
  STRING2      TargusType := '';
  boolean      confirmed_flag := false;
  boolean      vendor_dt_last_seen_used := false;
	boolean      isDeepDive := false;
  unsigned4    global_sid := 0;
	unsigned8    record_sid := 0;
end;