EXPORT Layout_Infiles := MODULE

	EXPORT payload := RECORD,MAXLENGTH(20000)
	  STRING line;
	END;

	EXPORT agency := RECORD  
	  STRING Agency_ID;
	  STRING Agency_Name;
	  STRING Source_ID;
	  STRING Agency_State_Abbr;
	  STRING Agency_ori; 
	  STRING Allow_Open_Search; 
	  STRING Append_Overwrite_Flag;
	  STRING Drivers_Exchange_Flag;  
	END;

	EXPORT billing_agencies := RECORD
		STRING Cru_Agency_ID;
		STRING Cru_State_Number;
		STRING Mbsi_Agency_ID;
	END;

	EXPORT citation := RECORD 
		STRING Citation_ID;
		STRING Creation_Date;
		STRING Incident_ID;
		STRING Person_ID;
		STRING Citation_Issued;
		STRING Citation_Number1;
		STRING Citation_Number2;
		STRING Section_Number1;
		STRING Court_Date;
		STRING Court_Time;
		STRING Citation_Detail1;
		STRING Local_Code;
		STRING Violation_Code1;
		STRING Violation_Code2;
		STRING Multiple_Charges_Indicator;
		STRING DUI_Indicator;
		STRING Court_Time_AM;
		STRING Court_Time_PM;
		STRING Violator_Name;
		STRING Type_Hazardous;
		STRING Type_Other;
		STRING Citation_Status;
	END;


	EXPORT commercial := RECORD
		STRING Commercial_ID;
		STRING Creation_Date;
		STRING Vehicle_ID;
		STRING Commercial_Info_Source;
		STRING Commercial_Vehicle_Type;
		STRING Motor_Carrier_ID_DOT_Number;
		STRING Motor_Carrier_ID_State_ID;
		STRING Motor_Carrier_ID_Carrier_Name;
		STRING Motor_Carrier_ID_Address;
		STRING Motor_Carrier_ID_City;
		STRING Motor_Carrier_ID_State;
		STRING Motor_Carrier_ID_Zipcode;
		STRING Motor_Carrier_ID_Commercial_Indicator;
		STRING Carrier_ID_Type;
		STRING Carrier_Unit_Number;
		STRING DOT_Permit_Number;
		STRING ICCMC_Number;
		STRING MCS_Vehicle_Inspection;
		STRING MCS_Form_Number;
		STRING MCS_Out_of_Service;
		STRING MCS_Violation_Related;
		STRING Number_of_Axles;
		STRING Number_of_Tires;
		STRING GVW_Over_10K_Pounds;
		STRING Weight_Rating;
		STRING Registered_Gross_Vehicle_Weight;
		STRING Vehicle_Length_Feet;
		STRING Cargo_Body_Type;
		STRING Load_Type;
		STRING Oversize_Load;
		STRING Vehicle_Configuration;
		STRING Trailer1_Type;
		STRING Trailer1_Length_Feet;
		STRING Trailer1_Width_Feet;
		STRING Trailer2_Type;
		STRING Trailer2_Length_Feet;
		STRING Trailer2_Width_Feet;
		STRING Federally_Reportable;
		STRING Vehicle_Inspection_Hazmat;
		STRING Hazmat_Form_Number;
		STRING Hazmt_Out_of_Service;
		STRING Hazmat_Violation_Related;
		STRING Hazardous_Materials_Placard;
		STRING Hazardous_Materials_Class_Number1;
		STRING Hazardous_Materials_Class_Number2;
		STRING Hazmat_Placard_Name;
		STRING Hazardous_Materials_Released1;
		STRING Hazardous_Materials_Released2;
		STRING Hazardous_Materials_Released3;
		STRING Hazardous_Materials_Released4;
		STRING Commercial_Event1;
		STRING Commercial_Event2;
		STRING Commercial_Event3;
		STRING Commercial_Event4;
		STRING Recommended_Driver_Reexam;
		STRING Transporting_HazMat;
		STRING Liquid_HazMat_Volume;
		STRING Oversize_Vehicle;
		STRING Overlength_Vehicle;
		STRING Oversize_Vehicle_Permitted;
		STRING Overlength_Vehicle_Permitted;
		STRING Carrier_Phone_Number;
		STRING Commerce_Type;
		STRING Citation_Issued_to_Vehicle;
		STRING CDL_Class;
		STRING DOT_State;
		STRING Fire_Hazardous_Materials_Involvement;
		STRING Commercial_Event_Description;
		STRING Supplment_Required_Hazmat_Placard;
		STRING Other_State_Number1;
		STRING Other_State_Number2;
		STRING Hazardous_Materials_Hazmat_Placard_Number1;
		STRING Hazardous_Materials_Hazmat_Placard_Number2;
		STRING Unit_Type_And_Axles1;
		STRING Unit_Type_And_Axles2;
		STRING Unit_Type_And_Axles3;
		STRING Unit_Type_And_Axles4;
	END;


	EXPORT incident_NEW := RECORD,MAXLENGTH(20000)
		STRING Incident_ID;
		STRING Creation_Date;
		STRING Work_Type_ID;
		STRING Report_ID;
		STRING Agency_ID;
		STRING Sent_to_HPCC_DateTime;
		STRING Corrected_Incident;
		STRING CRU_Order_ID;
		STRING CRU_Sequence_Nbr;
		STRING Loss_State_Abbr;
		STRING Report_Type_ID;
		STRING Hash_Key;
		STRING Case_Identifier;
		STRING Crash_County;
		STRING County_Cd;
		STRING Crash_CityPlace;
		STRING Crash_City;
		STRING City_Code;
		STRING First_Harmful_Event;
		STRING First_Harmful_Event_Location;
		STRING Manner_Crash_Impact1;
		STRING Weather_Condition1;
		STRING Weather_Condition2;
		STRING Light_Condition1;
		STRING Light_Condition2;
		STRING Road_Surface_Condition;
		STRING Contributing_Circumstances_Environmental1;
		STRING Contributing_Circumstances_Environmental2;
		STRING Contributing_Circumstances_Environmental3;
		STRING Contributing_Circumstances_Environmental4;
		STRING Contributing_Circumstances_Road1;
		STRING Contributing_Circumstances_Road2;
		STRING Contributing_Circumstances_Road3;
		STRING Contributing_Circumstances_Road4;
		STRING Relation_to_Junction;
		STRING Intersection_Type;
		STRING School_Bus_Related;
		STRING Work_Zone_Related;
		STRING Work_Zone_Location;
		STRING Work_Zone_Type;
		STRING Work_Zone_Workers_Present;
		STRING Work_Zone_Law_Enforcement_Present;
		STRING Crash_Severity;
		STRING Number_of_Vehicles;
		STRING Total_Nonfatal_Injuries;
		STRING Total_Fatal_Injuries;
		STRING Day_of_Week;
		STRING Roadway_Curvature;
		STRING Part_of_National_Highway_System;
		STRING Roadway_Functional_Class;
		STRING Access_Control;
		STRING RR_Crossing_ID;
		STRING Roadway_Lighting;
		STRING Traffic_Control_Type_at_Intersection1;
		STRING Traffic_Control_Type_at_Intersection2;
		STRING NCIC_Number;
		STRING State_Report_Number;
		STRING ORI_Number;
		STRING Crash_Date;
		STRING Crash_Time;
		STRING Lattitude;
		STRING Longitude;
		STRING Milepost1;
		STRING Milepost2;
		STRING Address_Number;
		STRING Loss_Street;
		STRING Loss_Street_Route_Number;
		STRING loss_street_type;
		STRING Loss_Street_Speed_Limit;
		STRING Incident_Location_Indicator;
		STRING Loss_Cross_Street;
		STRING Loss_Cross_Street_Route_Number;
		STRING Loss_Cross_Street_Intersecting_Route_Segment;
		STRING Loss_Cross_Street_Type;
		STRING Loss_Cross_Street_Speed_Limit;
		STRING Loss_Cross_Street_Number_of_Lanes;
		STRING Loss_Cross_Street_Orientation;
		STRING Loss_Cross_Street_Route_Sign;
		STRING At_Node_Number;
		STRING Distance_From_Node_Feet;
		STRING Distance_From_Node_Miles;
		STRING Next_Node_Number;
		STRING Next_Roadway_Node_Number;
		STRING Direction_of_Travel;
		STRING Next_Street;
		STRING Next_Street_Type;
		STRING Next_Street_Suffix;
		STRING Before_or_After_Next_Street;
		STRING Next_Street_Distance_Feet;
		STRING Next_Street_Distance_Miles;
		STRING Next_Street_Direction;
		STRING Next_Street_Route_Segment;
		STRING Continuing_Toward_Street;
		STRING Continuing_Street_Suffix;
		STRING Continuing_Street_Direction;
		STRING Continuting_Street_Route_Segment;
		STRING City_Type;
		STRING Outside_City_Indicator;
		STRING Outside_City_Direction;
		STRING Outside_City_Distance_Feet;
		STRING Outside_City_Distance_Miles;
		STRING Crash_Type;
		STRING Motor_Vehicle_Involved_With;
		STRING Report_Investigation_Type;
		STRING Incident_Hit_and_Run;
		STRING Tow_Away;
		STRING Date_Notified;
		STRING Time_Notified;
		STRING Notification_Method;
		STRING Officer_Arrival_Time;
		STRING Officer_Report_Date;
		STRING Officer_Report_Time;
		STRING Officer_ID;
		STRING Officer_Department;
		STRING Officer_Rank;
		STRING Officer_Command;
		STRING Officer_Tax_ID_Number;
		STRING Completed_Report_Date;
		STRING Supervisor_Check_Date;
		STRING Supervisor_Check_Time;
		STRING Supervisor_ID;
		STRING Supervisor_Rank;
		STRING Reviewers_Name;
		STRING Road_Surface;
		STRING Roadway_Alignment;
		STRING Traffic_Way_Description;
		STRING Traffic_Flow;
		STRING Property_Damage_Involved;
		STRING Property_Damage_Description1;
		STRING Property_Damage_Description2;
		STRING Property_Damage_Estimate1;
		STRING Property_Damage_Estimate2;
		STRING Incident_Damage_Over_Limit;
		STRING Property_Owner_Notified;
		STRING Government_Property;
		STRING Accident_Condition;
		STRING Unusual_Road_Condition1;
		STRING Unusual_Road_Condition2;
		STRING Number_of_Lanes;
		STRING Divided_Highway;
		STRING Most_Harmful_Event;
		STRING Second_Harmful_Event;
		STRING EMS_Notified_Date;
		STRING EMS_Arrival_Date;
		STRING Hospital_Arrival_Date;
		STRING Injured_Taken_By;
		STRING Injured_Taken_To;
		STRING Incident_Transported_for_Medical_Care;
		STRING Photographs_Taken;
		STRING Photographed_By;
		STRING Photographer_ID;
		STRING Photography_Agency_Name;
		STRING Agency_Name;
		STRING Judicial_District;
		STRING Precinct;
		STRING Beat;
		STRING Location_Type;
		STRING Shoulder_Type;
		STRING Investigation_Complete;
		STRING Investigation_Not_Complete_Why;
		STRING Investigating_Officer_Name;
		STRING Investigation_Notification_Issued;
		STRING Agency_Type;
		STRING No_Injury_Tow_Involved;
		STRING Injury_Tow_Involved;
		STRING LARS_Code1;
		STRING LARS_Code2;
		STRING Private_Property_Incident;
		STRING Accident_Involvement;
		STRING Local_Use;
		STRING Street_Prefix;
		STRING Street_Suffix;
		STRING Toll_Road;
		STRING Street_Description;
		STRING Cross_Street_Address_Number;
		STRING Cross_Street_Prefix;
		STRING Cross_Street_Suffix;
		STRING Report_Complete;
		STRING Dispatch_Notified;
		STRING Counter_Report;
		STRING Road_Type;
		STRING Agency_Code;
		STRING Public_Property_Employee;
		STRING Bridge_Related;
		STRING Ramp_Indicator;
		STRING To_or_From_Location;
		STRING Complaint_Number;
		STRING School_Zone_Related;
		STRING Notify_DOT_Maintenance;
		STRING Special_Location;
		STRING Route_Segment;
		STRING Route_Sign;
		STRING Route_Category_Street;
		STRING Route_Category_Cross_Street;
		STRING Route_Category_Next_Street;
		STRING Lane_Closed;
		STRING Lane_Closure_Direction;
		STRING Lane_Direction;
		STRING Traffic_Detoured;
		STRING Time_Closed;
		STRING Pedestrian_Signals;
		STRING Work_Zone_Speed_Limit;
		STRING Work_Zone_Shoulder_Median;
		STRING Work_Zone_Intermittent_Moving;
		STRING Work_Zone_Flagger_Control;
		STRING Special_Work_Zone_Characteristics;
		STRING Lane_Number;
		STRING Offset_Distance_Feet;
		STRING Offset_Distance_MIles;
		STRING Offset_Direction;
		STRING ASRU_Code;
		STRING MP_Grid;
		STRING Number_of_Qualifying_Units;
		STRING Number_of_HazMat_Vehicles;
		STRING Number_of_Buses_Involved;
		STRING Number_Taken_to_Treatment;
		STRING Number_Vehicles_Towed;
		STRING Vehicle_at_Fault_Unit_Number;
		STRING Time_Officer_Cleared_Scene;
		STRING Total_Minutes_on_Scene;
		STRING Motorists_Report;
		STRING Fatality_Involved;
		STRING Local_DOT_Index_Number;
		STRING DOR_Number;
		STRING Hospital_Code;
		STRING Special_Jurisdiction;
		STRING Document_Type;
		STRING Distance_Was_Measured;
		STRING Street_Orientation;
		STRING Intersecting_Route_Segment;
		STRING Primary_Fault_Indicator;
		STRING First_Harmful_Event_Pedestrian;
		STRING Reference_Markers;
		STRING Other_Officer_on_Scene;
		STRING Other_Officer_Badge_Number;
		STRING Supplemental_Report;
		STRING Supplemental_Type;
		STRING Amended_Report;
		STRING Corrected_Report;
		STRING State_Highway_Related;
		STRING Roadway_Lighting_Condition;
		STRING Vendor_Reference_Number;
		STRING Duplicate_Copy_Unit_Number;
		STRING Other_City_Agency_Description;
		STRING Notifcation_Description;
		STRING Primary_Collision_Improper_Driving_Description;
		STRING Weather_Other_Description;
		STRING Crash_Type_Description;
		STRING Motor_Vehicle_Involved_With_Animal_Description;
		STRING Motor_Vehicle_Involved_With_Fixed_Object_Description;
		STRING Motor_Vehicle_Involved_With_Other_Object_Description;
		STRING Other_Investigation_Time;
		STRING Milepost_Detail;
		STRING Utility_Pole_Number1;
		STRING Utility_Pole_Number2;
		STRING Utility_Pole_Number3;
		STRING Utility_Pole_Number4;
		STRING Incident_Special_Use;
		STRING Felony_Misdemeanor_Involved;
		STRING Duplicate_Copy_Required;
		STRING Highway_District_at_Scene;
		STRING Distance_Was_Approximated;
		STRING Avoidance_Maneuver;
		STRING Investigation_at_Scene;
		STRING Accident_Investigation_Site;
		STRING Narrative;
		STRING Narrative_Continuance;
		STRING Report_Has_Coversheet;
		STRING Crash_Time_AM;
		STRING Crash_Time_PM;
		STRING Time_Notified_AM;
		STRING Time_Notified_PM;
		STRING EMS_Notified_Time;
		STRING EMS_Arrival_Time;
		STRING First_Aid_By ; 
		STRING Person_First_Aid_Party_Type  ; 
		STRING Person_First_Aid_Party_Type_Description ;
		STRING Source_ID;
		STRING traffic_control_condition;
		STRING intersection_related;	
		STRING special_study_local;	
		STRING special_study_state;	
		STRING off_road_vehicle_involved;	
		STRING location_type2	;
		STRING speed_limit_posted;
		STRING traffic_control_damage_notify_date;
		STRING traffic_control_damage_notify_time	;
		STRING traffic_control_damage_notify_name;	
		STRING public_property_damaged;
		STRING replacement_report	;
		STRING deleted_report;
		STRING next_street_prefix	 ;
		STRING incident_damage_amount; 
		// silverlight 
		STRING dot_use;	
		STRING  number_of_persons_involved;	
		STRING unusual_road_condition_other_description	;
		STRING number_of_narrative_sections	;
		STRING CAD_number	;
		STRING visibility	;
		STRING  accident_at_intersection;
		STRING  accident_not_at_intersection	;
		STRING  first_harmful_event_within_interchange	;
		STRING  injury_involved;
		//STRING Admin_Portal_Visible;
		STRING Vendor_Code;	
		STRING Report_Property_Damage;	
		STRING Report_Collision_Type;	
		STRING Report_First_Harmful_Event;	
		STRING Report_Light_Condition;	
		STRING Report_Weather_Condition;
		STRING Report_Road_Condition;
		STRING cru_agency_id;
		STRING cru_agency_name;
		STRING Vendor_Report_Id	;
		STRING is_available_for_public	;
		STRING has_addendum	;
		STRING report_agency_ori	;
		STRING report_status;
		STRING ReportLinkID;
		STRING Page_Count;
		STRING is_delete;
		STRING last_update_date;
		STRING Contrib_source;
		//BuyCrash Release 6
		STRING Date_Report_Submitted;
		//CrashLogic Release 4
	  STRING1 Releasable;
	END;

	EXPORT persn_NEW := RECORD ,MAXLENGTH(20000)
		STRING Person_ID;
		STRING Creation_Date;
		STRING Incident_ID;
		STRING Person_Number;
		STRING Sex;
		STRING Person_Type;
		STRING Injury_Status;
		STRING Vehicle_Unit_Number;
		STRING Seating_Position1;
		STRING Safety_Equipment_Restraint1;
		STRING Safety_Equipment_Restraint2;
		STRING Safety_Equipment_Helmet;
		STRING Air_Bag_Deployed;
		STRING Ejection;
		STRING Drivers_License_Jurisdiction;
		STRING DL_Number_Class;
		STRING DL_Number_CDL;
		STRING DL_Number_endorsements;
		STRING Driver_Actions_at_Time_of_Crash1;
		STRING Driver_Actions_at_Time_of_Crash2;
		STRING Driver_Actions_at_Time_of_Crash3;
		STRING Driver_Actions_at_Time_of_Crash4;
		STRING Violation_Codes;
		STRING Condition_at_Time_of_Crash1;
		STRING Condition_at_Time_of_Crash2;
		STRING Law_Enforcement_Suspects_Alcohol_Use;
		STRING Alcohol_Test_Status;
		STRING Alcohol_Test_Type;
		STRING Alcohol_Test_Result;
		STRING Law_Enforcement_Suspects_Drug_Use;
		STRING Drug_Test_Given;
		STRING Non_Motorist_Actions_Prior_to_Crash1;
		STRING Non_Motorist_Actions_Prior_to_Crash2;
		STRING Non_Motorist_Actions_at_Time_of_Crash;
		STRING Non_Motorist_Location_at_Time_of_Crash;
		STRING Non_Motorist_Safety_Equipment1;
		STRING Age;
		STRING Driver_License_Restrictions1;
		STRING Drug_Test_Type;
		STRING Drug_Test_Result1;
		STRING Drug_Test_Result2;
		STRING Drug_Test_Result3;
		STRING Drug_Test_Result4;
		STRING Injury_Area;
		STRING Injury_Description;
		STRING Motorcyclist_Head_Injury;
		STRING Party_ID;
		STRING Same_as_Driver;
		STRING Address_Same_as_Driver;
		STRING Last_Name;
		STRING First_Name;
		STRING Middle_Name;
		STRING Name_Suffx;
		STRING Date_of_Birth;
		STRING Address;
		STRING City;
		STRING State;
		STRING Zip_Code;
		STRING Home_Phone;
		STRING Business_Phone;
		STRING Insurance_Company;
		STRING Insurance_Company_Phone_Number;
		STRING Insurance_Policy_Number;
		STRING Insurance_Effective_Date;
		STRING SSN;
		STRING Drivers_License_Number;
		STRING Drivers_License_Expiration;
		STRING Eye_Color;
		STRING Hair_Color;
		STRING Height;
		STRING Weight;
		STRING Race;
		STRING Pedestrian_Cyclist_Visibility;
		STRING First_Aid_By;
		STRING Person_First_Aid_Party_Type;
		STRING Person_First_Aid_Party_Type_Description;
		STRING Deceased_At_Scene;
		STRING Death_Date;
		STRING Death_TIme;
		STRING Extricated;
		STRING Alcohol_Drug_Use;
		STRING Physical_Defects;
		STRING Driver_Residence;
		STRING ID_Type;
		STRING Proof_of_Insurance;
		STRING Insurance_Expired;
		STRING Insurance_Exempt;
		STRING Insurance_Type;
		STRING Violent_Crime_Victim_Notified;
		STRING Insurance_Company_Code;
		STRING Refused_Medical_Treatment;
		STRING Safety_Equipment_Available_or_Used;
		STRING Apartment_Number;
		STRING Licensed_Driver;
		STRING Physical_Emotional_Status;
		STRING Driver_Presence;
		STRING Ejection_Path;
		STRING State_Person_ID;
		STRING Contributed_to_Collision;
		STRING Person_Transported_for_Medical_Care;
		STRING Transported_by_Agency_Type;
		STRING Transported_To;
		STRING Non_Motorist_Driver_License_Number;
		STRING Air_Bag_Type;
		STRING Cell_Phone_Use;
		STRING Driver_License_Restriction_Compliance;
		STRING Driver_License_endorsement_Compliance;
		STRING Driver_License_Compliance;
		STRING Contributing_Circumstances_p1;
		STRING Contributing_Circumstances_p2;
		STRING Contributing_Circumstances_p3;
		STRING Contributing_Circumstances_p4;
		STRING Passenger_Number;
		STRING Person_Deleted;
		STRING Owner_Lessee;
		STRING Driver_Charged;
		STRING Motorcycle_Eye_Protection;
		STRING Motorcycle_Long_Sleeves;
		STRING Motorcycle_Long_Pants;
		STRING Motorcycle_Over_Ankle_Boots;
		STRING Contributing_Circumstances_Environmental_Non_Incident1;
		STRING Contributing_Circumstances_Environmental_Non_Incident2;
		STRING Alcohol_Drug_Test_Given;
		STRING Alcohol_Drug_Test_Type;
		STRING Alcohol_Drug_Test_Result;
		STRING Law_Enforcement_Suspects_Alcohol_Use1;
		STRING Law_Enforcement_Suspects_Drug_Use1;
		//3.0.1
		STRING Solicitation	;
		STRING drivers_license_type	;
		STRING alcohol_test_type_refused;	
		STRING alcohol_test_type_not_offered	;
		STRING alcohol_test_type_field;	
		STRING alcohol_test_type_pbt	;
		STRING alcohol_test_type_breath	;
		STRING alcohol_test_type_blood	;
		STRING alcohol_test_type_urine	;
		STRING trapped	;
		STRING dl_number_cdl_endorsements;
		STRING dl_number_cdl_restrictions	;
		STRING dl_number_cdl_exempt	;
		STRING dl_number_cdl_medical_card	;
		STRING interlock_device_in_use	;
		STRING drug_test_type_blood	;
		STRING drug_test_type_urine;
		STRING driver_distracted_by;	
		STRING non_motorist_type;	
		STRING seating_position_row;	
		STRING seating_position_seat	;
		STRING seating_position_description;	
		STRING transported_id_number;	
		STRING witness_number	;
		STRING date_of_birth_derived;
		STRING Report_Injury_Status; 
		STRING Address2;
	END;

	EXPORT vehicl_NEW:= RECORD,MAXLENGTH(20000)
		STRING Vehicle_ID;
		STRING Creation_Date;
		STRING Incident_ID;
		STRING VIN;	
		STRING VIN_Status;
		STRING Damaged_Areas_Derived1;
		STRING Damaged_Areas_Derived2;
		STRING Airbags_Deployed_Derived;
		STRING Vehicle_Towed_Derived;
		STRING Unit_Type;
		STRING Unit_Number;
		STRING Registration_State;
		STRING Registration_Year;
		STRING License_Plate;
		STRING Make;
		STRING Model_Yr;
		STRING Model;
		STRING Body_Type_Category;
		STRING Total_Occupants_in_Vehicle;
		STRING Special_Function_in_Transport;
		STRING Special_Function_in_Transport_Other_Unit;
		STRING Emergency_Use;
		STRING Posted_Satutory_Speed_Limit;
		STRING Direction_of_Travel_Before_Crash;
		STRING Trafficway_Description;
		STRING Traffic_Control_Device_Type;
		STRING Vehicle_Maneuver_Action_Prior1;
		STRING Vehicle_Maneuver_Action_Prior2;
		STRING Impact_Area1;
		STRING Impact_Area2;
		STRING Event_Sequence1;
		STRING Event_Sequence2;
		STRING Event_Sequence3;
		STRING Event_Sequence4;
		STRING Most_Harmful_Event_for_Vehicle;
		STRING Bus_Use;
		STRING Vehicle_Hit_and_Run;
		STRING Vehicle_Towed;
		STRING Contributing_Circumstances_v1;
		STRING Contributing_Circumstances_v2;
		STRING Contributing_Circumstances_v3;
		STRING Contributing_Circumstances_v4;
		STRING On_Street;
		STRING Vehicle_Color;
		STRING Estimated_Speed;
		STRING Car_Fire;
		STRING Vehicle_Damage_Amount;
		STRING Contributing_Factors1;
		STRING Contributing_Factors2;
		STRING Contributing_Factors3;
		STRING Contributing_Factors4;
		STRING Other_Contributing_Factors1;
		STRING Other_Contributing_Factors2;
		STRING Other_Contributing_Factors3;
		STRING Vision_Obscured1;
		STRING Vision_Obscured2;
		STRING Vehicle_on_Road;
		STRING Ran_Off_Road;
		STRING Skidding_Occurred;
		STRING Vehicle_Incident_Location1;
		STRING Vehicle_Incident_Location2;
		STRING Vehicle_Incident_Location3;
		STRING Vehicle_Disabled;
		STRING Vehicle_Removed_To;
		STRING Removed_By;
		STRING Tow_Requested_by_Driver;
		STRING Solicitation;
		STRING Other_Unit_Vehicle_Damage_Amount;
		STRING Other_Unit_Model_Year;
		STRING Other_Unit_Make;
		STRING Other_Unit_Model;
		STRING Other_Unit_VIN;
		STRING Other_Unit_VIN_Status;
		STRING Other_Unit_Body_Type_Category;
		STRING Other_Unit_Registration_State;
		STRING Other_Unit_Registration_Year;
		STRING Other_Unit_License_Plate;
		STRING Other_Unit_Color;
		STRING Other_Unit_Type;
		STRING Damaged_Areas1;
		STRING Damaged_Areas2;
		STRING Parked_Vehicle;
		STRING Damage_Rating1;
		STRING Damage_Rating2;
		STRING Vehicle_Inventoried;
		STRING Vehicle_Defect_Apparent;
		STRING Defect_May_Have_Contributed1;
		STRING Defect_May_Have_Contributed2;
		STRING Registration_Expiration;
		STRING Owner_Driver_Type;
		STRING Make_Code;
		STRING Number_Trailing_Units;
		STRING Vehicle_Position;
		STRING Vehicle_Type;
		STRING Motorcycle_Engine_Size;
		STRING Motorcycle_Driver_Educated;
		STRING Motorcycle_Helmet_Type;
		STRING Motorcycle_Passenger;
		STRING Motorcycle_Helmet_Stayed_On;
		STRING Motorcycle_Helmet_DOT_Snell;
		STRING Motorcycle_Saddlebag_Trunk;
		STRING Motorcycle_Trailer;
		STRING Pedacycle_Passenger;
		STRING Pedacycle_Headlights;
		STRING Pedacycle_Helmet;
		STRING Pedacycle_Rear_Reflectors;
		STRING CDL_Required;
		STRING Truck_Bus_Supplement_Required;
		STRING Unit_Damage_Amount;
		STRING Airbag_Switch;
		STRING Underride_Override_Damage;
		STRING Vehicle_Attachment;
		STRING Action_on_Impact;
		STRING Speed_Detection_Method;
		STRING Non_Motorist_Direction_of_Travel_From;
		STRING Non_Motorist_Direction_of_Travel_To;
		STRING Vehicle_Use;
		STRING Department_Unit_Number;
		STRING Equipment_in_Use_at_Time_of_Accident;
		STRING Actions_of_Police_Vehicle;
		STRING Vehicle_Command_ID;
		STRING Traffic_Control_Device_Inoperative;
		STRING Direction_of_Impact1;
		STRING Direction_of_Impact2;
		STRING Ran_Off_Road_Direction;
		STRING VIN_Other_Unit_Number;
		STRING Damaged_Area_Generic;
		STRING Vision_Obscured_Description;
		STRING Inattention_Description;
		STRING Contributing_Circumstances_Defect_Description;
		STRING Contributing_Circumstances_Other_Descriptioin;
		STRING Vehicle_Maneuver_Action_Prior_Other_Description;
		STRING Vehicle_Special_Use;
		STRING Vehicle_Type_Extended1;
		STRING Vehicle_Type_Extended2;
		STRING Fixed_Object_Direction1;
		STRING Fixed_Object_Direction2;
		STRING Fixed_Object_Direction3;
		STRING Fixed_Object_Direction4;
		STRING Vehicle_Left_at_Scene;
		STRING Vehicle_Impounded;
		STRING Vehicle_Driven_From_Scene;
		STRING On_Cross_Street;
		STRING Actions_of_Police_Vehicle_Description;
		STRING Avoidance_Maneuver;
		STRING Insurance_Expiration_Date;
		STRING Insurance_Policy_Number;
		STRING Insurance_Company;
		STRING avoidance_maneuver2;
		STRING  avoidance_maneuver3;
		STRING  avoidance_maneuver4;
		STRING  damaged_areas_severity1 ;
		STRING  damaged_areas_severity2 ;
		STRING  vehicle_outside_city_indicator;
		STRING  vehicle_outside_city_distance_miles ;
		STRING  vehicle_outside_city_direction;
		STRING  vehicle_crash_cityplace;
		STRING Insurance_Company_Standardized; 
		// moved fields from person
		STRING Insurance_Company_Phone_Number :=''; 
		STRING Insurance_Effective_Date:=''; 
		STRING Proof_of_Insurance:=''; 
		STRING Insurance_Expired:=''; 
		STRING Insurance_Exempt:=''; 
		STRING Insurance_Type:=''; 
		STRING Insurance_Company_Code:=''; 
		// new fields
		STRING Insurance_Policy_Holder:=''; 
		STRING Is_Tag_Converted:=''; 
		STRING VIN_Original :=''; 
		STRING Make_Original :=''; 
		STRING Model_Original :=''; 
		STRING Model_Year_Original :=''; 
		STRING Other_Unit_VIN_Original :=''; 
		STRING Other_Unit_Make_Original :=''; 
		STRING Other_Unit_Model_Original :=''; 
		STRING Other_Unit_Model_Year_Original:=''; 
		STRING initial_point_of_contact	:='';
		STRING vehicle_driveable:='';
		STRING commercial_vehicle;
		STRING number_of_lanes;
		STRING divided_highway;
		STRING not_in_transport;
		STRING other_unit_number;
		STRING other_unit_length;
		STRING other_unit_axles;
		STRING other_unit_plate_expiration;
		STRING other_unit_permanent_registration;	
		STRING other_unit_model_year2;
		STRING other_unit_make2;
		STRING other_unit_vin2;
		STRING other_unit_registration_state2;
		STRING other_unit_registration_year2;
		STRING other_unit_license_plate2;
		STRING other_unit_number2;
		STRING other_unit_length2;
		STRING other_unit_axles2;
		STRING other_unit_plate_expiration2;
		STRING other_unit_permanent_registration2;
		STRING other_unit_type2;
		STRING other_unit_model_year3;
		STRING other_unit_make3	;
		STRING other_unit_vin3;
		STRING other_unit_registration_state3;
		STRING other_unit_registration_year3;
		STRING other_unit_license_plate3;
		STRING other_unit_number3;
		STRING other_unit_length3;
		STRING other_unit_axles3;
		STRING other_unit_plate_expiration3;
		STRING other_unit_permanent_registration3;
		STRING other_unit_type3;
		STRING damaged_areas3;
		STRING speed_limit_posted;
		STRING Report_Damage_Extent;
		STRING Report_Vehicle_Type;
		STRING Report_Traffic_Control_Device_Type;	
		STRING Report_Contributing_Circumstances_v;	
		STRING Report_Vehicle_Maneuver_Action_Prior;	
		STRING Report_Vehicle_Body_Type;
	END;

	EXPORT property_damage := RECORD
    STRING Property_Damage_ID;
		STRING Incident_ID;
		STRING damage_description;
		STRING damage_estimate;
		STRING property_owner_name;
		STRING property_owner_phone;
		STRING property_owner_last_name;
		STRING property_owner_first_name;
		STRING property_owner_middle_name;
		STRING property_owner_address;
		STRING property_owner_city;
		STRING property_owner_state;
		STRING property_owner_zip_code;
		STRING property_owner_notified;
	END; 

	EXPORT layoutNahdbBatch := RECORD
		STRING EVENT_ID;
		STRING DATE_OF_INCIDENT;
		STRING FIRST_NAME;        
		STRING MIDDLE_INITIAL;
		STRING LAST_NAME;         
		STRING ADDRESS1;
		//STRING ADDRESS2;             
		STRING CITY;
		STRING STATE;
		STRING ZIP;
		STRING DOB;
		STRING SSN;
		STRING ADL; 
		STRING VIN; 
	END; 

	EXPORT layout_temp := RECORD
		STRING title; 
		STRING fname; 
		STRING mname; 
		STRING lname; 
		STRING suffix; 
		STRING clean_dob; 
		STRING clean_DATE_OF_INCIDENT; 
		STRING acc_dol,
		STRING acc_city,	
		STRING acc_st	,
		STRING acc_county,	
		STRING acc_vin,
		STRING order_id	,
		STRING sequence_nbr,	
		STRING acct_nbr	,
		STRING vehicle_incident_id,	
		STRING carrier_name,	
		STRING source_id,	
		STRING orig_accnbr,	
		STRING report_code,	
		STRING person_type,	
		STRING match_flag,	
		STRING date_vendor_last_reported,
		layoutNahdbBatch;
	END; 

	EXPORT layout_out := RECORD
		layoutNahdbBatch;
		STRING acc_dol,
		STRING acc_city,	
		STRING acc_st	,
		STRING acc_county,	
		STRING acc_vin,
		STRING order_id	,
		STRING sequence_nbr,	
		STRING acct_nbr	,
		STRING vehicle_incident_id,	
		STRING carrier_name,	
		STRING source_id,	
		STRING orig_accnbr,	
		STRING report_code,	
		STRING person_type,	
		STRING match_flag,	
		STRING date_vendor_last_reported,
	END; 

END;
