// Mapping for contact title for USABIZ (provider: InfoUSA), per Rosemary Murphy e-mail

EXPORT string35 GetContactTitle (string1 code) := MAP (
  code = 'A' => 'Chairman',
  code = 'B' => 'Vice Chairman',
  code = 'C' => 'Chief Executive Officer',
  code = 'D' => 'Director (Public Co)',
  code = 'E' => 'Chief Operating Officer',
  code = 'F' => 'Chief Financial Officer',
  code = 'G' => 'Treasurer',
  code = 'H' => 'Controller',
  code = 'I' => 'Executive Vice President',
  code = 'J' => 'Senior Vice President',
  code = 'K' => 'Vice President',
  code = 'L' => 'Administration Executive',
  code = 'M' => 'Corporate Communications Executive',
  code = 'N' => 'Data Processing Executive',
  code = 'O' => 'Finance Executive',
  code = 'P' => 'Human Resources Executive',
  code = 'Q' => 'Telecommunications Executive',
  code = 'R' => 'Marketing Executive',
  code = 'S' => 'Operations Executive',
  code = 'T' => 'Sales Executive',
  code = 'U' => 'Corporate Secretary',
  code = 'V' => 'General Counsel',
  code = 'W' => 'Executive Officer',
  code = 'X' => 'Plant Manager',
  code = 'Y' => 'Purchasing Agent',
  code = 'Z' => 'Auditor',
  code = '1' => 'Owner',
  code = '2' => 'President',
  code = '3' => 'Manager',
  code = '4' => 'Executive Director',
  code = '5' => 'Principal',
  code = '6' => 'Publisher',
  code = '7' => 'Administrator',
  code = '8' => 'Religious Leader',
  code = '9' => 'Partner',
  ''
);
