//HPCC Systems KEL Compiler Version 1.5.0
IMPORT KEL15 AS KEL;
IMPORT B_Business_Sele_1,B_Business_Sele_3,B_Sele_Tradeline_1,B_Sele_Tradeline_3,B_Tradeline_1,B_Tradeline_4,CFG_Compile,E_Business_Org,E_Business_Sele,E_Business_Sele_Overflow,E_Business_Ult,E_Sele_Tradeline,E_Tradeline,FN_Compile FROM PublicRecords_KEL_Queries.B2B_KEL;
IMPORT * FROM KEL15.Null;
EXPORT B_Business_Sele(CFG_Compile.FDCDataset __in = CFG_Compile.FDCDefault, CFG_Compile __cfg = CFG_Compile) := MODULE
  SHARED VIRTUAL TYPEOF(B_Business_Sele_1(__in,__cfg).__ENH_Business_Sele_1) __ENH_Business_Sele_1 := B_Business_Sele_1(__in,__cfg).__ENH_Business_Sele_1;
  SHARED VIRTUAL TYPEOF(B_Sele_Tradeline_1(__in,__cfg).__ENH_Sele_Tradeline_1) __ENH_Sele_Tradeline_1 := B_Sele_Tradeline_1(__in,__cfg).__ENH_Sele_Tradeline_1;
  SHARED VIRTUAL TYPEOF(B_Tradeline_1(__in,__cfg).__ENH_Tradeline_1) __ENH_Tradeline_1 := B_Tradeline_1(__in,__cfg).__ENH_Tradeline_1;
  SHARED __EE617267 := __ENH_Business_Sele_1;
  SHARED __EE617904 := __ENH_Tradeline_1;
  SHARED __EE617907 := __ENH_Sele_Tradeline_1;
  SHARED __EE630994 := __EE617907(__NN(__EE617907.Legal_) AND __NN(__EE617907.Account_));
  SHARED __ST394704_Layout := RECORD
    KEL.typ.nuid UID;
    KEL.typ.nint Ult_I_D_;
    KEL.typ.nint Org_I_D_;
    KEL.typ.nint Sele_I_D_;
    KEL.typ.nstr Account_Key_;
    KEL.typ.ndataset(B_Tradeline_1(__in,__cfg).__ST132477_Layout) Records_;
    KEL.typ.ndataset(E_Tradeline(__in,__cfg).Vendor_Dates_Layout) Vendor_Dates_;
    KEL.typ.ndataset(E_Tradeline(__in,__cfg).Data_Sources_Layout) Data_Sources_;
    KEL.typ.ntyp(E_Business_Sele().Typ) Legal_;
    KEL.typ.ntyp(E_Tradeline().Typ) Account_;
    KEL.typ.ndataset(E_Sele_Tradeline(__in,__cfg).Data_Sources_Layout) Data_Sources__1_;
    KEL.typ.ndataset(B_Sele_Tradeline_3(__in,__cfg).__ST70275_Layout) Trade_Account_;
    KEL.typ.epoch Archive___Date_ := 0;
    KEL.typ.epoch Date_First_Seen_ := 0;
    KEL.typ.epoch Date_Last_Seen_ := 0;
    KEL.typ.epoch Hybrid_Archive_Date_ := 0;
    KEL.typ.epoch Vault_Date_Last_Seen_ := 0;
    KEL.typ.int __RecordCount := 0;
  END;
  __JC631012(B_Tradeline_1(__in,__cfg).__ST132470_Layout __EE617904, B_Sele_Tradeline_3(__in,__cfg).__ST139699_Layout __EE630994) := __EEQP(__EE630994.Account_,__EE617904.UID);
  __ST394704_Layout __JT631012(B_Tradeline_1(__in,__cfg).__ST132470_Layout __l, B_Sele_Tradeline_3(__in,__cfg).__ST139699_Layout __r) := TRANSFORM
    SELF.Data_Sources__1_ := __r.Data_Sources_;
    SELF := __l;
    SELF := __r;
  END;
  SHARED __EE631013 := JOIN(__EE630994,__EE617904,__JC631012(RIGHT,LEFT),__JT631012(RIGHT,LEFT),INNER,HASH);
  SHARED __EE634144 := __EE631013;
  SHARED __ST393312_Layout := RECORD
    KEL.typ.ntyp(E_Business_Sele().Typ) UID;
    KEL.typ.ntyp(E_Business_Sele().Typ) Legal_;
    KEL.typ.ntyp(E_Tradeline().Typ) Account_;
    KEL.typ.ndataset(E_Sele_Tradeline(__in,__cfg).Data_Sources_Layout) Data_Sources_;
    KEL.typ.ndataset(B_Sele_Tradeline_3(__in,__cfg).__ST70275_Layout) Trade_Account_;
    KEL.typ.nuid U_I_D__1_;
    KEL.typ.nint Ult_I_D_;
    KEL.typ.nint Org_I_D_;
    KEL.typ.nint Sele_I_D_;
    KEL.typ.nstr Account_Key_;
    KEL.typ.ndataset(B_Tradeline_1(__in,__cfg).__ST132477_Layout) Records_;
    KEL.typ.ndataset(E_Tradeline(__in,__cfg).Vendor_Dates_Layout) Vendor_Dates_;
    KEL.typ.ndataset(E_Tradeline(__in,__cfg).Data_Sources_Layout) Data_Sources__1_;
    KEL.typ.epoch Archive___Date_ := 0;
    KEL.typ.epoch Date_First_Seen_ := 0;
    KEL.typ.epoch Date_Last_Seen_ := 0;
    KEL.typ.epoch Hybrid_Archive_Date_ := 0;
    KEL.typ.epoch Vault_Date_Last_Seen_ := 0;
  END;
  SHARED __ST393312_Layout __ND634151__Project(__ST394704_Layout __PP634147) := TRANSFORM
    SELF.UID := __PP634147.Legal_;
    SELF.Data_Sources_ := __PP634147.Data_Sources__1_;
    SELF.U_I_D__1_ := __PP634147.UID;
    SELF.Data_Sources__1_ := __PP634147.Data_Sources_;
    SELF := __PP634147;
  END;
  SHARED __EE634278 := PROJECT(__EE634144,__ND634151__Project(LEFT));
  SHARED __ST393427_Layout := RECORD
    KEL.typ.ntyp(E_Business_Sele().Typ) UID;
    KEL.typ.nkdate C_U_R_R_E_N_T___D_A_T_E_;
    KEL.typ.epoch Archive___Date_ := 0;
    KEL.typ.epoch Date_First_Seen_ := 0;
    KEL.typ.epoch Date_Last_Seen_ := 0;
    KEL.typ.epoch Hybrid_Archive_Date_ := 0;
    KEL.typ.epoch Vault_Date_Last_Seen_ := 0;
  END;
  SHARED __ST393427_Layout __ND634283__Project(__ST393312_Layout __PP634279) := TRANSFORM
    __CC13258 := KEL.Routines.MinN(FN_Compile(__cfg).FN_G_E_T_B_U_I_L_D_D_A_T_E(__ECAST(KEL.typ.nstr,__CN('cortera_build_version'))),__CN(__cfg.CurrentDate));
    SELF.C_U_R_R_E_N_T___D_A_T_E_ := __CC13258;
    SELF := __PP634279;
  END;
  SHARED __EE634290 := PROJECT(__EE634278,__ND634283__Project(LEFT));
  SHARED __ST393568_Layout := RECORD
    KEL.typ.ntyp(E_Business_Sele().Typ) UID;
    KEL.typ.nkdate O_N_L_Y___C_U_R_R_E_N_T___D_A_T_E_;
    KEL.typ.nkdate O_N_L_Y___C_U_R_R_E_N_T___D_A_T_E__1_;
    KEL.typ.nkdate O_N_L_Y___C_U_R_R_E_N_T___D_A_T_E__2_;
    KEL.typ.nkdate O_N_L_Y___C_U_R_R_E_N_T___D_A_T_E__3_;
    KEL.typ.nkdate O_N_L_Y___C_U_R_R_E_N_T___D_A_T_E__4_;
    KEL.typ.nkdate O_N_L_Y___C_U_R_R_E_N_T___D_A_T_E__5_;
    KEL.typ.nkdate O_N_L_Y___C_U_R_R_E_N_T___D_A_T_E__6_;
    KEL.typ.nkdate O_N_L_Y___C_U_R_R_E_N_T___D_A_T_E__7_;
    KEL.typ.nkdate O_N_L_Y___C_U_R_R_E_N_T___D_A_T_E__8_;
    KEL.typ.nkdate O_N_L_Y___C_U_R_R_E_N_T___D_A_T_E__9_;
    KEL.typ.nkdate O_N_L_Y___C_U_R_R_E_N_T___D_A_T_E__10_;
    KEL.typ.nkdate O_N_L_Y___C_U_R_R_E_N_T___D_A_T_E__11_;
    KEL.typ.nkdate O_N_L_Y___C_U_R_R_E_N_T___D_A_T_E__12_;
    KEL.typ.nkdate O_N_L_Y___C_U_R_R_E_N_T___D_A_T_E__13_;
    KEL.typ.nkdate O_N_L_Y___C_U_R_R_E_N_T___D_A_T_E__14_;
    KEL.typ.epoch Archive___Date_ := 0;
    KEL.typ.epoch Date_First_Seen_ := 0;
    KEL.typ.epoch Date_Last_Seen_ := 0;
    KEL.typ.epoch Hybrid_Archive_Date_ := 0;
    KEL.typ.epoch Vault_Date_Last_Seen_ := 0;
  END;
  SHARED __ST393568_Layout __ND634295__Project(__ST393427_Layout __PP634291) := TRANSFORM
    SELF.O_N_L_Y___C_U_R_R_E_N_T___D_A_T_E_ := __PP634291.C_U_R_R_E_N_T___D_A_T_E_;
    SELF.O_N_L_Y___C_U_R_R_E_N_T___D_A_T_E__1_ := __PP634291.C_U_R_R_E_N_T___D_A_T_E_;
    SELF.O_N_L_Y___C_U_R_R_E_N_T___D_A_T_E__2_ := __PP634291.C_U_R_R_E_N_T___D_A_T_E_;
    SELF.O_N_L_Y___C_U_R_R_E_N_T___D_A_T_E__3_ := __PP634291.C_U_R_R_E_N_T___D_A_T_E_;
    SELF.O_N_L_Y___C_U_R_R_E_N_T___D_A_T_E__4_ := __PP634291.C_U_R_R_E_N_T___D_A_T_E_;
    SELF.O_N_L_Y___C_U_R_R_E_N_T___D_A_T_E__5_ := __PP634291.C_U_R_R_E_N_T___D_A_T_E_;
    SELF.O_N_L_Y___C_U_R_R_E_N_T___D_A_T_E__6_ := __PP634291.C_U_R_R_E_N_T___D_A_T_E_;
    SELF.O_N_L_Y___C_U_R_R_E_N_T___D_A_T_E__7_ := __PP634291.C_U_R_R_E_N_T___D_A_T_E_;
    SELF.O_N_L_Y___C_U_R_R_E_N_T___D_A_T_E__8_ := __PP634291.C_U_R_R_E_N_T___D_A_T_E_;
    SELF.O_N_L_Y___C_U_R_R_E_N_T___D_A_T_E__9_ := __PP634291.C_U_R_R_E_N_T___D_A_T_E_;
    SELF.O_N_L_Y___C_U_R_R_E_N_T___D_A_T_E__10_ := __PP634291.C_U_R_R_E_N_T___D_A_T_E_;
    SELF.O_N_L_Y___C_U_R_R_E_N_T___D_A_T_E__11_ := __PP634291.C_U_R_R_E_N_T___D_A_T_E_;
    SELF.O_N_L_Y___C_U_R_R_E_N_T___D_A_T_E__12_ := __PP634291.C_U_R_R_E_N_T___D_A_T_E_;
    SELF.O_N_L_Y___C_U_R_R_E_N_T___D_A_T_E__13_ := __PP634291.C_U_R_R_E_N_T___D_A_T_E_;
    SELF.O_N_L_Y___C_U_R_R_E_N_T___D_A_T_E__14_ := __PP634291.C_U_R_R_E_N_T___D_A_T_E_;
    SELF := __PP634291;
  END;
  SHARED __EE634360 := PROJECT(__EE634290,__ND634295__Project(LEFT));
  SHARED __ST395683_Layout := RECORD
    KEL.typ.nuid UID;
    KEL.typ.nint Ult_I_D_;
    KEL.typ.nint Org_I_D_;
    KEL.typ.nint Sele_I_D_;
    KEL.typ.ntyp(E_Business_Org().Typ) Sele_Org_;
    KEL.typ.ntyp(E_Business_Sele_Overflow().Typ) Sele_Overflow_;
    KEL.typ.nbool Sele_Gold_;
    KEL.typ.nbool Is_Sele_Level_;
    KEL.typ.nbool Is_Org_Level_;
    KEL.typ.nbool Is_Ult_Level_;
    KEL.typ.nstr Sele_Segment_;
    KEL.typ.nbool Is_Corporation_;
    KEL.typ.ndataset(E_Business_Sele(__in,__cfg).Business_Structure_Layout) Business_Structure_;
    KEL.typ.ndataset(E_Business_Sele(__in,__cfg).Ownership_Layout) Ownership_;
    KEL.typ.ndataset(E_Business_Sele(__in,__cfg).Industry_Layout) Industry_;
    KEL.typ.ndataset(E_Business_Sele(__in,__cfg).Company_Statuses_Layout) Company_Statuses_;
    KEL.typ.ndataset(E_Business_Sele(__in,__cfg).Age_Layout) Age_;
    KEL.typ.ndataset(E_Business_Sele(__in,__cfg).Reported_Names_Layout) Reported_Names_;
    KEL.typ.ndataset(E_Business_Sele(__in,__cfg).Stock_Tickers_Layout) Stock_Tickers_;
    KEL.typ.ndataset(E_Business_Sele(__in,__cfg).U_R_Ls_Layout) U_R_Ls_;
    KEL.typ.ndataset(E_Business_Sele(__in,__cfg).S_I_C_Codes_Layout) S_I_C_Codes_;
    KEL.typ.ndataset(E_Business_Sele(__in,__cfg).N_A_I_C_S_Codes_Layout) N_A_I_C_S_Codes_;
    KEL.typ.ndataset(E_Business_Sele(__in,__cfg).Employee_Counts_Layout) Employee_Counts_;
    KEL.typ.ndataset(E_Business_Sele(__in,__cfg).Sale_Amounts_Layout) Sale_Amounts_;
    KEL.typ.ndataset(E_Business_Sele(__in,__cfg).Earning_Amounts_Layout) Earning_Amounts_;
    KEL.typ.ndataset(E_Business_Sele(__in,__cfg).Asset_Amounts_Layout) Asset_Amounts_;
    KEL.typ.nkdate B_B_B_Member_Since_;
    KEL.typ.ndataset(E_Business_Sele(__in,__cfg).B_B_B_Categories_Layout) B_B_B_Categories_;
    KEL.typ.nstr For_Profit_Indicator_;
    KEL.typ.nstr Public_Or_Private_Indicator_;
    KEL.typ.ndataset(E_Business_Sele(__in,__cfg).Non_Profit_Layout) Non_Profit_;
    KEL.typ.ndataset(E_Business_Sele(__in,__cfg).Best_Company_Names_Layout) Best_Company_Names_;
    KEL.typ.ndataset(E_Business_Sele(__in,__cfg).Best_S_I_C_Codes_Layout) Best_S_I_C_Codes_;
    KEL.typ.ndataset(E_Business_Sele(__in,__cfg).Best_N_A_I_C_S_Codes_Layout) Best_N_A_I_C_S_Codes_;
    KEL.typ.ndataset(E_Business_Sele(__in,__cfg).Business_Characteristics_Layout) Business_Characteristics_;
    KEL.typ.ndataset(E_Business_Sele(__in,__cfg).Experian_C_R_D_B_Tradelines_Layout) Experian_C_R_D_B_Tradelines_;
    KEL.typ.ndataset(E_Business_Sele(__in,__cfg).Data_Sources_Layout) Data_Sources_;
    KEL.typ.ndataset(B_Business_Sele_3(__in,__cfg).__ST71727_Layout) B2b_T_L_Bal_In_Carr_Newest_Date2_Y_;
    KEL.typ.ndataset(B_Business_Sele_3(__in,__cfg).__ST71767_Layout) B2b_T_L_Bal_In_Flt_Newest_Date2_Y_;
    KEL.typ.ndataset(B_Business_Sele_3(__in,__cfg).__ST71807_Layout) B2b_T_L_Bal_In_Mat_Newest_Date2_Y_;
    KEL.typ.ndataset(B_Business_Sele_3(__in,__cfg).__ST71847_Layout) B2b_T_L_Bal_In_Ops_Newest_Date2_Y_;
    KEL.typ.ndataset(B_Business_Sele_3(__in,__cfg).__ST71887_Layout) B2b_T_L_Bal_In_Oth_Newest_Date2_Y_;
    KEL.typ.ndataset(B_Business_Sele_3(__in,__cfg).__ST71687_Layout) B2b_T_L_Bal_Newest_Date2_Y_;
    KEL.typ.nfloat B2b_T_L_Devation_Sample_;
    KEL.typ.nfloat B2b_T_L_Devation_Sample_In_Carr_;
    KEL.typ.nfloat B2b_T_L_Devation_Sample_In_Flt_;
    KEL.typ.nfloat B2b_T_L_Devation_Sample_In_Mat_;
    KEL.typ.nfloat B2b_T_L_Devation_Sample_In_Ops_;
    KEL.typ.nfloat B2b_T_L_Devation_Sample_In_Oth_;
    KEL.typ.nfloat B2b_T_L_In_Carr_M_E_A_N_;
    KEL.typ.nfloat B2b_T_L_In_Flt_M_E_A_N_;
    KEL.typ.nfloat B2b_T_L_In_Mat_M_E_A_N_;
    KEL.typ.nfloat B2b_T_L_In_Ops_M_E_A_N_;
    KEL.typ.nfloat B2b_T_L_In_Oth_M_E_A_N_;
    KEL.typ.nfloat B2b_T_L_M_E_A_N_;
    KEL.typ.int B_E___B2_B_Actv1p_Dpd_Bal_Tot_A1_Y_ := 0;
    KEL.typ.int B_E___B2_B_Actv1p_Dpd_Bal_Tot_A1_Y_No_Cap_ := 0;
    KEL.typ.int B_E___B2_B_Actv1p_Dpd_Bal_Tot_No_Cap_ := 0;
    KEL.typ.int B_E___B2_B_Actv1p_Dpd_Cnt_No_Cap_ := 0;
    KEL.typ.int B_E___B2_B_Actv31p_Dpd_Bal_Tot_A1_Y_ := 0;
    KEL.typ.int B_E___B2_B_Actv31p_Dpd_Bal_Tot_A1_Y_No_Cap_ := 0;
    KEL.typ.int B_E___B2_B_Actv31p_Dpd_Bal_Tot_No_Cap_ := 0;
    KEL.typ.int B_E___B2_B_Actv31p_Dpd_Cnt_No_Cap_ := 0;
    KEL.typ.int B_E___B2_B_Actv61p_Dpd_Bal_Tot_A1_Y_ := 0;
    KEL.typ.int B_E___B2_B_Actv61p_Dpd_Bal_Tot_A1_Y_No_Cap_ := 0;
    KEL.typ.int B_E___B2_B_Actv61p_Dpd_Bal_Tot_No_Cap_ := 0;
    KEL.typ.int B_E___B2_B_Actv61p_Dpd_Cnt_No_Cap_ := 0;
    KEL.typ.int B_E___B2_B_Actv91p_Dpd_Bal_Tot_A1_Y_ := 0;
    KEL.typ.int B_E___B2_B_Actv91p_Dpd_Bal_Tot_A1_Y_No_Cap_ := 0;
    KEL.typ.int B_E___B2_B_Actv91p_Dpd_Bal_Tot_No_Cap_ := 0;
    KEL.typ.int B_E___B2_B_Actv91p_Dpd_Cnt_No_Cap_ := 0;
    KEL.typ.int B_E___B2_B_Actv_Bal_Tot_ := 0;
    KEL.typ.int B_E___B2_B_Actv_Bal_Tot_A1_Y_ := 0;
    KEL.typ.int B_E___B2_B_Actv_Bal_Tot_Arch1_Y_No_Cap_ := 0;
    KEL.typ.nfloat B_E___B2_B_Actv_Bal_Tot_Grow1_Y_;
    KEL.typ.int B_E___B2_B_Actv_Bal_Tot_No_Cap_ := 0;
    KEL.typ.int B_E___B2_B_Actv_Carr_Bal_Tot_ := 0;
    KEL.typ.int B_E___B2_B_Actv_Carr_Bal_Tot_A1_Y_ := 0;
    KEL.typ.int B_E___B2_B_Actv_Carr_Bal_Tot_Arch1_Y_No_Cap_ := 0;
    KEL.typ.nfloat B_E___B2_B_Actv_Carr_Bal_Tot_Grow1_Y_;
    KEL.typ.int B_E___B2_B_Actv_Carr_Bal_Tot_No_Cap_ := 0;
    KEL.typ.int B_E___B2_B_Actv_Carr_Cnt_ := 0;
    KEL.typ.int B_E___B2_B_Actv_Carr_Cnt_A1_Y_ := 0;
    KEL.typ.int B_E___B2_B_Actv_Carr_Cnt_A1_Y_No_Cap_ := 0;
    KEL.typ.int B_E___B2_B_Actv_Carr_Cnt_No_Cap_ := 0;
    KEL.typ.int B_E___B2_B_Actv_Cnt_ := 0;
    KEL.typ.int B_E___B2_B_Actv_Cnt_A1_Y_ := 0;
    KEL.typ.int B_E___B2_B_Actv_Cnt_A1_Y_No_Cap_ := 0;
    KEL.typ.int B_E___B2_B_Actv_Cnt_No_Cap_ := 0;
    KEL.typ.int B_E___B2_B_Actv_Flt_Bal_Tot_ := 0;
    KEL.typ.int B_E___B2_B_Actv_Flt_Bal_Tot_A1_Y_ := 0;
    KEL.typ.int B_E___B2_B_Actv_Flt_Bal_Tot_Arch1_Y_No_Cap_ := 0;
    KEL.typ.nfloat B_E___B2_B_Actv_Flt_Bal_Tot_Grow1_Y_;
    KEL.typ.int B_E___B2_B_Actv_Flt_Bal_Tot_No_Cap_ := 0;
    KEL.typ.int B_E___B2_B_Actv_Flt_Cnt_ := 0;
    KEL.typ.int B_E___B2_B_Actv_Flt_Cnt_A1_Y_ := 0;
    KEL.typ.int B_E___B2_B_Actv_Flt_Cnt_A1_Y_No_Cap_ := 0;
    KEL.typ.int B_E___B2_B_Actv_Flt_Cnt_No_Cap_ := 0;
    KEL.typ.int B_E___B2_B_Actv_Mat_Bal_Tot_ := 0;
    KEL.typ.int B_E___B2_B_Actv_Mat_Bal_Tot_A1_Y_ := 0;
    KEL.typ.int B_E___B2_B_Actv_Mat_Bal_Tot_Arch1_Y_No_Cap_ := 0;
    KEL.typ.nfloat B_E___B2_B_Actv_Mat_Bal_Tot_Grow1_Y_;
    KEL.typ.int B_E___B2_B_Actv_Mat_Bal_Tot_No_Cap_ := 0;
    KEL.typ.int B_E___B2_B_Actv_Mat_Cnt_ := 0;
    KEL.typ.int B_E___B2_B_Actv_Mat_Cnt_A1_Y_ := 0;
    KEL.typ.int B_E___B2_B_Actv_Mat_Cnt_A1_Y_No_Cap_ := 0;
    KEL.typ.int B_E___B2_B_Actv_Mat_Cnt_No_Cap_ := 0;
    KEL.typ.int B_E___B2_B_Actv_Ops_Bal_Tot_ := 0;
    KEL.typ.int B_E___B2_B_Actv_Ops_Bal_Tot_A1_Y_ := 0;
    KEL.typ.int B_E___B2_B_Actv_Ops_Bal_Tot_Arch1_Y_No_Cap_ := 0;
    KEL.typ.nfloat B_E___B2_B_Actv_Ops_Bal_Tot_Grow1_Y_;
    KEL.typ.int B_E___B2_B_Actv_Ops_Bal_Tot_No_Cap_ := 0;
    KEL.typ.int B_E___B2_B_Actv_Ops_Cnt_ := 0;
    KEL.typ.int B_E___B2_B_Actv_Ops_Cnt_A1_Y_ := 0;
    KEL.typ.int B_E___B2_B_Actv_Ops_Cnt_A1_Y_No_Cap_ := 0;
    KEL.typ.int B_E___B2_B_Actv_Ops_Cnt_No_Cap_ := 0;
    KEL.typ.int B_E___B2_B_Actv_Oth_Bal_Tot_ := 0;
    KEL.typ.int B_E___B2_B_Actv_Oth_Bal_Tot_A1_Y_ := 0;
    KEL.typ.int B_E___B2_B_Actv_Oth_Bal_Tot_Arch1_Y_No_Cap_ := 0;
    KEL.typ.nfloat B_E___B2_B_Actv_Oth_Bal_Tot_Grow1_Y_;
    KEL.typ.int B_E___B2_B_Actv_Oth_Bal_Tot_No_Cap_ := 0;
    KEL.typ.int B_E___B2_B_Actv_Oth_Cnt_ := 0;
    KEL.typ.int B_E___B2_B_Actv_Oth_Cnt_A1_Y_ := 0;
    KEL.typ.int B_E___B2_B_Actv_Oth_Cnt_A1_Y_No_Cap_ := 0;
    KEL.typ.int B_E___B2_B_Actv_Oth_Cnt_No_Cap_ := 0;
    KEL.typ.nint B_E___B2_B_Bal_Max2_Y_No_Cap_;
    KEL.typ.nstr B_E___B2_B_Bal_Max_Dt2_Y_;
    KEL.typ.int B_E___B2_B_Bal_Max_Seg_Type2_Y_Map_Carr_ := 0;
    KEL.typ.int B_E___B2_B_Bal_Max_Seg_Type2_Y_Map_Flt_ := 0;
    KEL.typ.int B_E___B2_B_Bal_Max_Seg_Type2_Y_Map_Mat_ := 0;
    KEL.typ.int B_E___B2_B_Bal_Max_Seg_Type2_Y_Map_Ops_ := 0;
    KEL.typ.int B_E___B2_B_Bal_Max_Seg_Type2_Y_Map_Oth_ := 0;
    KEL.typ.nint B_E___B2_B_Carr_Bal_Max2_Y_No_Cap_;
    KEL.typ.nstr B_E___B2_B_Carr_Bal_Max_Dt2_Y_;
    KEL.typ.int B_E___B2_B_Carr_Cnt24_Mc_ := 0;
    KEL.typ.int B_E___B2_B_Carr_Cnt24_Mc_No_Cap_ := 0;
    KEL.typ.int B_E___B2_B_Carr_Cnt2_Y_ := 0;
    KEL.typ.int B_E___B2_B_Carr_Cnt2_Y_No_Cap_ := 0;
    KEL.typ.str B_E___B2_B_Carr_Rec_Flag_By_Mon_Str24_Mc_ := '';
    KEL.typ.nint B_E___B2_B_Carr_Rec_Flag_By_Mon_Sum24_Mc_;
    KEL.typ.nstr B_E___B2_B_Carr_Worst_Perf_Dt2_Y_;
    KEL.typ.str B_E___B2_B_Carr_Worst_Perf_Indx2_Y_ := '';
    KEL.typ.int B_E___B2_B_Cnt24_Mc_ := 0;
    KEL.typ.int B_E___B2_B_Cnt24_Mc_No_Cap_ := 0;
    KEL.typ.int B_E___B2_B_Cnt2_Y_ := 0;
    KEL.typ.int B_E___B2_B_Cnt2_Y_No_Cap_ := 0;
    KEL.typ.nint B_E___B2_B_Cnt_Ev_;
    KEL.typ.nint B_E___B2_B_Flt_Bal_Max2_Y_No_Cap_;
    KEL.typ.nstr B_E___B2_B_Flt_Bal_Max_Dt2_Y_;
    KEL.typ.int B_E___B2_B_Flt_Cnt24_Mc_ := 0;
    KEL.typ.int B_E___B2_B_Flt_Cnt24_Mc_No_Cap_ := 0;
    KEL.typ.int B_E___B2_B_Flt_Cnt2_Y_ := 0;
    KEL.typ.int B_E___B2_B_Flt_Cnt2_Y_No_Cap_ := 0;
    KEL.typ.str B_E___B2_B_Flt_Rec_Flag_By_Mon_Str24_Mc_ := '';
    KEL.typ.nint B_E___B2_B_Flt_Rec_Flag_By_Mon_Sum24_Mc_;
    KEL.typ.nstr B_E___B2_B_Flt_Worst_Perf_Dt2_Y_;
    KEL.typ.str B_E___B2_B_Flt_Worst_Perf_Indx2_Y_ := '';
    KEL.typ.nint B_E___B2_B_Mat_Bal_Max2_Y_No_Cap_;
    KEL.typ.nstr B_E___B2_B_Mat_Bal_Max_Dt2_Y_;
    KEL.typ.int B_E___B2_B_Mat_Cnt24_Mc_ := 0;
    KEL.typ.int B_E___B2_B_Mat_Cnt24_Mc_No_Cap_ := 0;
    KEL.typ.int B_E___B2_B_Mat_Cnt2_Y_ := 0;
    KEL.typ.int B_E___B2_B_Mat_Cnt2_Y_No_Cap_ := 0;
    KEL.typ.str B_E___B2_B_Mat_Rec_Flag_By_Mon_Str24_Mc_ := '';
    KEL.typ.nint B_E___B2_B_Mat_Rec_Flag_By_Mon_Sum24_Mc_;
    KEL.typ.nstr B_E___B2_B_Mat_Worst_Perf_Dt2_Y_;
    KEL.typ.str B_E___B2_B_Mat_Worst_Perf_Indx2_Y_ := '';
    KEL.typ.nstr B_E___B2_B_New_Dt2_Y_;
    KEL.typ.nstr B_E___B2_B_Old_Dt2_Y_;
    KEL.typ.nstr B_E___B2_B_Old_Dt_Ev_;
    KEL.typ.nint B_E___B2_B_Ops_Bal_Max2_Y_No_Cap_;
    KEL.typ.nstr B_E___B2_B_Ops_Bal_Max_Dt2_Y_;
    KEL.typ.int B_E___B2_B_Ops_Cnt24_Mc_ := 0;
    KEL.typ.int B_E___B2_B_Ops_Cnt24_Mc_No_Cap_ := 0;
    KEL.typ.int B_E___B2_B_Ops_Cnt2_Y_ := 0;
    KEL.typ.int B_E___B2_B_Ops_Cnt2_Y_No_Cap_ := 0;
    KEL.typ.str B_E___B2_B_Ops_Rec_Flag_By_Mon_Str24_Mc_ := '';
    KEL.typ.nint B_E___B2_B_Ops_Rec_Flag_By_Mon_Sum24_Mc_;
    KEL.typ.nstr B_E___B2_B_Ops_Worst_Perf_Dt2_Y_;
    KEL.typ.str B_E___B2_B_Ops_Worst_Perf_Indx2_Y_ := '';
    KEL.typ.nint B_E___B2_B_Oth_Bal_Max2_Y_No_Cap_;
    KEL.typ.nstr B_E___B2_B_Oth_Bal_Max_Dt2_Y_;
    KEL.typ.int B_E___B2_B_Oth_Cnt24_Mc_ := 0;
    KEL.typ.int B_E___B2_B_Oth_Cnt24_Mc_No_Cap_ := 0;
    KEL.typ.int B_E___B2_B_Oth_Cnt2_Y_ := 0;
    KEL.typ.int B_E___B2_B_Oth_Cnt2_Y_No_Cap_ := 0;
    KEL.typ.str B_E___B2_B_Oth_Rec_Flag_By_Mon_Str24_Mc_ := '';
    KEL.typ.nint B_E___B2_B_Oth_Rec_Flag_By_Mon_Sum24_Mc_;
    KEL.typ.nstr B_E___B2_B_Oth_Worst_Perf_Dt2_Y_;
    KEL.typ.str B_E___B2_B_Oth_Worst_Perf_Indx2_Y_ := '';
    KEL.typ.str B_E___B2_B_Rec_Flag_By_Mon_Str24_Mc_ := '';
    KEL.typ.nint B_E___B2_B_Rec_Flag_By_Mon_Sum24_Mc_;
    KEL.typ.nstr B_E___B2_B_Worst_Perf_Dt2_Y_;
    KEL.typ.str B_E___B2_B_Worst_Perf_Indx2_Y_ := '';
    KEL.typ.ntyp(E_Business_Sele().Typ) U_I_D__1_;
    KEL.typ.nkdate O_N_L_Y___C_U_R_R_E_N_T___D_A_T_E_;
    KEL.typ.nkdate O_N_L_Y___C_U_R_R_E_N_T___D_A_T_E__1_;
    KEL.typ.nkdate O_N_L_Y___C_U_R_R_E_N_T___D_A_T_E__2_;
    KEL.typ.nkdate O_N_L_Y___C_U_R_R_E_N_T___D_A_T_E__3_;
    KEL.typ.nkdate O_N_L_Y___C_U_R_R_E_N_T___D_A_T_E__4_;
    KEL.typ.nkdate O_N_L_Y___C_U_R_R_E_N_T___D_A_T_E__5_;
    KEL.typ.nkdate O_N_L_Y___C_U_R_R_E_N_T___D_A_T_E__6_;
    KEL.typ.nkdate O_N_L_Y___C_U_R_R_E_N_T___D_A_T_E__7_;
    KEL.typ.nkdate O_N_L_Y___C_U_R_R_E_N_T___D_A_T_E__8_;
    KEL.typ.nkdate O_N_L_Y___C_U_R_R_E_N_T___D_A_T_E__9_;
    KEL.typ.nkdate O_N_L_Y___C_U_R_R_E_N_T___D_A_T_E__10_;
    KEL.typ.nkdate O_N_L_Y___C_U_R_R_E_N_T___D_A_T_E__11_;
    KEL.typ.nkdate O_N_L_Y___C_U_R_R_E_N_T___D_A_T_E__12_;
    KEL.typ.nkdate O_N_L_Y___C_U_R_R_E_N_T___D_A_T_E__13_;
    KEL.typ.nkdate O_N_L_Y___C_U_R_R_E_N_T___D_A_T_E__14_;
    KEL.typ.epoch Archive___Date_ := 0;
    KEL.typ.epoch Date_First_Seen_ := 0;
    KEL.typ.epoch Date_Last_Seen_ := 0;
    KEL.typ.epoch Hybrid_Archive_Date_ := 0;
    KEL.typ.epoch Vault_Date_Last_Seen_ := 0;
    KEL.typ.int __RecordCount := 0;
  END;
  __JC634366(B_Business_Sele_1(__in,__cfg).__ST131971_Layout __EE617267, __ST393568_Layout __EE634360) := __EEQP(__EE617267.UID,__EE634360.UID);
  __ST395683_Layout __JT634366(B_Business_Sele_1(__in,__cfg).__ST131971_Layout __l, __ST393568_Layout __r) := TRANSFORM
    SELF.U_I_D__1_ := __r.UID;
    SELF := __l;
    SELF := __r;
  END;
  SHARED __EE634367 := JOIN(__EE617267,__EE634360,__JC634366(LEFT,RIGHT),__JT634366(LEFT,RIGHT),LEFT OUTER,HASH,KEEP(1));
  SHARED __ST395018_Layout := RECORD
    KEL.typ.nuid UID;
    KEL.typ.nint Ult_I_D_;
    KEL.typ.nint Org_I_D_;
    KEL.typ.nint Sele_I_D_;
    KEL.typ.nstr Account_Key_;
    KEL.typ.ndataset(B_Tradeline_1(__in,__cfg).__ST132477_Layout) Records_;
    KEL.typ.ndataset(E_Tradeline(__in,__cfg).Vendor_Dates_Layout) Vendor_Dates_;
    KEL.typ.ndataset(E_Tradeline(__in,__cfg).Data_Sources_Layout) Data_Sources_;
    KEL.typ.ntyp(E_Business_Sele().Typ) Legal_;
    KEL.typ.ntyp(E_Tradeline().Typ) Account_;
    KEL.typ.ndataset(E_Sele_Tradeline(__in,__cfg).Data_Sources_Layout) Data_Sources__1_;
    KEL.typ.ndataset(B_Sele_Tradeline_3(__in,__cfg).__ST70275_Layout) Trade_Account_;
    KEL.typ.nkdate A_R_Date_;
    KEL.typ.nint Total_A_R_;
    KEL.typ.nint Current_A_R_;
    KEL.typ.nint Aging1_To30_;
    KEL.typ.nint Aging31_To60_;
    KEL.typ.nint Aging61_To90_;
    KEL.typ.nint Aging91_Plus_;
    KEL.typ.nint Credit_Limit_;
    KEL.typ.nint Segment_I_D_;
    KEL.typ.nkdate File_Date_;
    KEL.typ.nstr Status_;
    KEL.typ.nkdate First_Sale_Date_;
    KEL.typ.nkdate Last_Sale_Date_;
    KEL.typ.nint Aging1_To30_L_N_;
    KEL.typ.nint Aging31_To60_L_N_;
    KEL.typ.nint Aging61_To90_L_N_;
    KEL.typ.nint Aging91_Plus_L_N_;
    KEL.typ.nbool Carrier_Segment_;
    KEL.typ.nbool Fleet_Segment_;
    KEL.typ.nbool Is_Most_Recent_Active_Record_;
    KEL.typ.nbool Is_Two_Year_Full_Record_;
    KEL.typ.nbool Materials_Segment_;
    KEL.typ.nint Months_From_First_Of_Current_Month_;
    KEL.typ.nbool Operations_Segment_;
    KEL.typ.nbool Other_Segment_;
    KEL.typ.int Perf_Level_ := 0;
    KEL.typ.nint Record_Age_In_Days_;
    KEL.typ.epoch Archive___Date_ := 0;
    KEL.typ.epoch Date_First_Seen_ := 0;
    KEL.typ.epoch Date_Last_Seen_ := 0;
    KEL.typ.epoch Hybrid_Archive_Date_ := 0;
    KEL.typ.epoch Vault_Date_Last_Seen_ := 0;
    KEL.typ.int __RecordCount := 0;
  END;
  __JC631082(__ST394704_Layout __EE631013, B_Tradeline_1(__in,__cfg).__ST132477_Layout __EE631068) := __T(__EE631068.Is_Most_Recent_Active_Record_);
  __ST395018_Layout __JT631082(__ST394704_Layout __l, B_Tradeline_1(__in,__cfg).__ST132477_Layout __r) := TRANSFORM, SKIP(NOT(__JC631082(__l,__r)))
    SELF.Archive___Date_ := __r.Archive___Date_;
    SELF.Date_First_Seen_ := __r.Date_First_Seen_;
    SELF.Date_Last_Seen_ := __r.Date_Last_Seen_;
    SELF.Hybrid_Archive_Date_ := __r.Hybrid_Archive_Date_;
    SELF.Vault_Date_Last_Seen_ := __r.Vault_Date_Last_Seen_;
    SELF.__RecordCount := __r.__RecordCount;
    SELF := __l;
    SELF := __r;
  END;
  SHARED __EE631083 := NORMALIZE(__EE631013,__T(LEFT.Records_),__JT631082(LEFT,RIGHT));
  SHARED __ST391258_Layout := RECORD
    KEL.typ.ntyp(E_Business_Sele().Typ) UID;
    KEL.typ.ntyp(E_Business_Sele().Typ) Legal_;
    KEL.typ.ntyp(E_Tradeline().Typ) Account_;
    KEL.typ.ndataset(E_Sele_Tradeline(__in,__cfg).Data_Sources_Layout) Data_Sources_;
    KEL.typ.ndataset(B_Sele_Tradeline_3(__in,__cfg).__ST70275_Layout) Trade_Account_;
    KEL.typ.nuid U_I_D__1_;
    KEL.typ.nint Ult_I_D_;
    KEL.typ.nint Org_I_D_;
    KEL.typ.nint Sele_I_D_;
    KEL.typ.nstr Account_Key_;
    KEL.typ.ndataset(B_Tradeline_1(__in,__cfg).__ST132477_Layout) Records_;
    KEL.typ.ndataset(E_Tradeline(__in,__cfg).Vendor_Dates_Layout) Vendor_Dates_;
    KEL.typ.ndataset(E_Tradeline(__in,__cfg).Data_Sources_Layout) Data_Sources__1_;
    KEL.typ.nkdate A_R_Date_;
    KEL.typ.nint Total_A_R_;
    KEL.typ.nint Current_A_R_;
    KEL.typ.nint Aging1_To30_;
    KEL.typ.nint Aging31_To60_;
    KEL.typ.nint Aging61_To90_;
    KEL.typ.nint Aging91_Plus_;
    KEL.typ.nint Credit_Limit_;
    KEL.typ.nint Segment_I_D_;
    KEL.typ.nkdate File_Date_;
    KEL.typ.nstr Status_;
    KEL.typ.nkdate First_Sale_Date_;
    KEL.typ.nkdate Last_Sale_Date_;
    KEL.typ.nint Aging1_To30_L_N_;
    KEL.typ.nint Aging31_To60_L_N_;
    KEL.typ.nint Aging61_To90_L_N_;
    KEL.typ.nint Aging91_Plus_L_N_;
    KEL.typ.nbool Carrier_Segment_;
    KEL.typ.nbool Fleet_Segment_;
    KEL.typ.nbool Is_Most_Recent_Active_Record_;
    KEL.typ.nbool Is_Two_Year_Full_Record_;
    KEL.typ.nbool Materials_Segment_;
    KEL.typ.nint Months_From_First_Of_Current_Month_;
    KEL.typ.nbool Operations_Segment_;
    KEL.typ.nbool Other_Segment_;
    KEL.typ.int Perf_Level_ := 0;
    KEL.typ.nint Record_Age_In_Days_;
    KEL.typ.epoch Archive___Date_ := 0;
    KEL.typ.epoch Date_First_Seen_ := 0;
    KEL.typ.epoch Date_Last_Seen_ := 0;
    KEL.typ.epoch Hybrid_Archive_Date_ := 0;
    KEL.typ.epoch Vault_Date_Last_Seen_ := 0;
  END;
  SHARED __ST391258_Layout __ND631165__Project(__ST395018_Layout __PP631084) := TRANSFORM
    SELF.UID := __PP631084.Legal_;
    SELF.Data_Sources_ := __PP631084.Data_Sources__1_;
    SELF.U_I_D__1_ := __PP631084.UID;
    SELF.Data_Sources__1_ := __PP631084.Data_Sources_;
    SELF := __PP631084;
  END;
  SHARED __EE631400 := PROJECT(__EE631083,__ND631165__Project(LEFT));
  SHARED __ST391455_Layout := RECORD
    KEL.typ.ntyp(E_Business_Sele().Typ) UID;
    KEL.typ.nint Exp1_;
    KEL.typ.nint Exp2_;
    KEL.typ.nint Exp3_;
    KEL.typ.nint Exp4_;
    KEL.typ.nint Exp5_;
    KEL.typ.nint Exp6_;
    KEL.typ.epoch Archive___Date_ := 0;
    KEL.typ.epoch Date_First_Seen_ := 0;
    KEL.typ.epoch Date_Last_Seen_ := 0;
    KEL.typ.epoch Hybrid_Archive_Date_ := 0;
    KEL.typ.epoch Vault_Date_Last_Seen_ := 0;
  END;
  SHARED __ST391455_Layout __ND637344__Project(__ST391258_Layout __PP631401) := TRANSFORM
    SELF.Exp1_ := IF(__T(__PP631401.Carrier_Segment_),__ECAST(KEL.typ.nint,__CN(__PP631401.Perf_Level_)),__ECAST(KEL.typ.nint,__N(KEL.typ.int)));
    SELF.Exp2_ := IF(__T(__PP631401.Fleet_Segment_),__ECAST(KEL.typ.nint,__CN(__PP631401.Perf_Level_)),__ECAST(KEL.typ.nint,__N(KEL.typ.int)));
    SELF.Exp3_ := IF(__T(__PP631401.Materials_Segment_),__ECAST(KEL.typ.nint,__CN(__PP631401.Perf_Level_)),__ECAST(KEL.typ.nint,__N(KEL.typ.int)));
    SELF.Exp4_ := IF(__T(__PP631401.Operations_Segment_),__ECAST(KEL.typ.nint,__CN(__PP631401.Perf_Level_)),__ECAST(KEL.typ.nint,__N(KEL.typ.int)));
    SELF.Exp5_ := IF(__T(__PP631401.Other_Segment_),__ECAST(KEL.typ.nint,__CN(__PP631401.Perf_Level_)),__ECAST(KEL.typ.nint,__N(KEL.typ.int)));
    SELF.Exp6_ := __CN(__PP631401.Perf_Level_);
    SELF := __PP631401;
  END;
  SHARED __EE637361 := PROJECT(__EE631400,__ND637344__Project(LEFT));
  SHARED __ST391495_Layout := RECORD
    KEL.typ.nint M_A_X___Perf_Level_;
    KEL.typ.nint M_A_X___Perf_Level__1_;
    KEL.typ.nint M_A_X___Perf_Level__2_;
    KEL.typ.nint M_A_X___Perf_Level__3_;
    KEL.typ.nint M_A_X___Perf_Level__4_;
    KEL.typ.nint M_A_X___Perf_Level__5_;
    KEL.typ.ntyp(E_Business_Sele().Typ) UID;
    KEL.typ.epoch Archive___Date_ := 0;
    KEL.typ.epoch Date_First_Seen_ := 0;
    KEL.typ.epoch Date_Last_Seen_ := 0;
    KEL.typ.epoch Hybrid_Archive_Date_ := 0;
    KEL.typ.epoch Vault_Date_Last_Seen_ := 0;
  END;
  SHARED __EE637402 := PROJECT(__CLEANANDDO(__EE637361,TABLE(__EE637361,{KEL.typ.epoch Archive___Date_ := KEL.era.SimpleRoll(GROUP,Archive___Date_,MIN,FALSE),KEL.typ.epoch Date_First_Seen_ := KEL.era.SimpleRoll(GROUP,Date_First_Seen_,MIN,FALSE),KEL.typ.epoch Date_Last_Seen_ := KEL.era.SimpleRoll(GROUP,Date_Last_Seen_,MAX,FALSE),KEL.typ.epoch Hybrid_Archive_Date_ := KEL.era.SimpleRoll(GROUP,Hybrid_Archive_Date_,MIN,FALSE),KEL.typ.epoch Vault_Date_Last_Seen_ := KEL.era.SimpleRoll(GROUP,Vault_Date_Last_Seen_,MAX,NMAX),KEL.Aggregates.MaxNG(__EE637361.Exp1_) M_A_X___Perf_Level_,KEL.Aggregates.MaxNG(__EE637361.Exp2_) M_A_X___Perf_Level__1_,KEL.Aggregates.MaxNG(__EE637361.Exp3_) M_A_X___Perf_Level__2_,KEL.Aggregates.MaxNG(__EE637361.Exp4_) M_A_X___Perf_Level__3_,KEL.Aggregates.MaxNG(__EE637361.Exp5_) M_A_X___Perf_Level__4_,KEL.Aggregates.MaxNG(__EE637361.Exp6_) M_A_X___Perf_Level__5_,UID},UID,MERGE)),__ST391495_Layout);
  SHARED __ST398525_Layout := RECORD
    KEL.typ.nuid UID;
    KEL.typ.nint Ult_I_D_;
    KEL.typ.nint Org_I_D_;
    KEL.typ.nint Sele_I_D_;
    KEL.typ.ntyp(E_Business_Org().Typ) Sele_Org_;
    KEL.typ.ntyp(E_Business_Sele_Overflow().Typ) Sele_Overflow_;
    KEL.typ.nbool Sele_Gold_;
    KEL.typ.nbool Is_Sele_Level_;
    KEL.typ.nbool Is_Org_Level_;
    KEL.typ.nbool Is_Ult_Level_;
    KEL.typ.nstr Sele_Segment_;
    KEL.typ.nbool Is_Corporation_;
    KEL.typ.ndataset(E_Business_Sele(__in,__cfg).Business_Structure_Layout) Business_Structure_;
    KEL.typ.ndataset(E_Business_Sele(__in,__cfg).Ownership_Layout) Ownership_;
    KEL.typ.ndataset(E_Business_Sele(__in,__cfg).Industry_Layout) Industry_;
    KEL.typ.ndataset(E_Business_Sele(__in,__cfg).Company_Statuses_Layout) Company_Statuses_;
    KEL.typ.ndataset(E_Business_Sele(__in,__cfg).Age_Layout) Age_;
    KEL.typ.ndataset(E_Business_Sele(__in,__cfg).Reported_Names_Layout) Reported_Names_;
    KEL.typ.ndataset(E_Business_Sele(__in,__cfg).Stock_Tickers_Layout) Stock_Tickers_;
    KEL.typ.ndataset(E_Business_Sele(__in,__cfg).U_R_Ls_Layout) U_R_Ls_;
    KEL.typ.ndataset(E_Business_Sele(__in,__cfg).S_I_C_Codes_Layout) S_I_C_Codes_;
    KEL.typ.ndataset(E_Business_Sele(__in,__cfg).N_A_I_C_S_Codes_Layout) N_A_I_C_S_Codes_;
    KEL.typ.ndataset(E_Business_Sele(__in,__cfg).Employee_Counts_Layout) Employee_Counts_;
    KEL.typ.ndataset(E_Business_Sele(__in,__cfg).Sale_Amounts_Layout) Sale_Amounts_;
    KEL.typ.ndataset(E_Business_Sele(__in,__cfg).Earning_Amounts_Layout) Earning_Amounts_;
    KEL.typ.ndataset(E_Business_Sele(__in,__cfg).Asset_Amounts_Layout) Asset_Amounts_;
    KEL.typ.nkdate B_B_B_Member_Since_;
    KEL.typ.ndataset(E_Business_Sele(__in,__cfg).B_B_B_Categories_Layout) B_B_B_Categories_;
    KEL.typ.nstr For_Profit_Indicator_;
    KEL.typ.nstr Public_Or_Private_Indicator_;
    KEL.typ.ndataset(E_Business_Sele(__in,__cfg).Non_Profit_Layout) Non_Profit_;
    KEL.typ.ndataset(E_Business_Sele(__in,__cfg).Best_Company_Names_Layout) Best_Company_Names_;
    KEL.typ.ndataset(E_Business_Sele(__in,__cfg).Best_S_I_C_Codes_Layout) Best_S_I_C_Codes_;
    KEL.typ.ndataset(E_Business_Sele(__in,__cfg).Best_N_A_I_C_S_Codes_Layout) Best_N_A_I_C_S_Codes_;
    KEL.typ.ndataset(E_Business_Sele(__in,__cfg).Business_Characteristics_Layout) Business_Characteristics_;
    KEL.typ.ndataset(E_Business_Sele(__in,__cfg).Experian_C_R_D_B_Tradelines_Layout) Experian_C_R_D_B_Tradelines_;
    KEL.typ.ndataset(E_Business_Sele(__in,__cfg).Data_Sources_Layout) Data_Sources_;
    KEL.typ.ndataset(B_Business_Sele_3(__in,__cfg).__ST71727_Layout) B2b_T_L_Bal_In_Carr_Newest_Date2_Y_;
    KEL.typ.ndataset(B_Business_Sele_3(__in,__cfg).__ST71767_Layout) B2b_T_L_Bal_In_Flt_Newest_Date2_Y_;
    KEL.typ.ndataset(B_Business_Sele_3(__in,__cfg).__ST71807_Layout) B2b_T_L_Bal_In_Mat_Newest_Date2_Y_;
    KEL.typ.ndataset(B_Business_Sele_3(__in,__cfg).__ST71847_Layout) B2b_T_L_Bal_In_Ops_Newest_Date2_Y_;
    KEL.typ.ndataset(B_Business_Sele_3(__in,__cfg).__ST71887_Layout) B2b_T_L_Bal_In_Oth_Newest_Date2_Y_;
    KEL.typ.ndataset(B_Business_Sele_3(__in,__cfg).__ST71687_Layout) B2b_T_L_Bal_Newest_Date2_Y_;
    KEL.typ.nfloat B2b_T_L_Devation_Sample_;
    KEL.typ.nfloat B2b_T_L_Devation_Sample_In_Carr_;
    KEL.typ.nfloat B2b_T_L_Devation_Sample_In_Flt_;
    KEL.typ.nfloat B2b_T_L_Devation_Sample_In_Mat_;
    KEL.typ.nfloat B2b_T_L_Devation_Sample_In_Ops_;
    KEL.typ.nfloat B2b_T_L_Devation_Sample_In_Oth_;
    KEL.typ.nfloat B2b_T_L_In_Carr_M_E_A_N_;
    KEL.typ.nfloat B2b_T_L_In_Flt_M_E_A_N_;
    KEL.typ.nfloat B2b_T_L_In_Mat_M_E_A_N_;
    KEL.typ.nfloat B2b_T_L_In_Ops_M_E_A_N_;
    KEL.typ.nfloat B2b_T_L_In_Oth_M_E_A_N_;
    KEL.typ.nfloat B2b_T_L_M_E_A_N_;
    KEL.typ.int B_E___B2_B_Actv1p_Dpd_Bal_Tot_A1_Y_ := 0;
    KEL.typ.int B_E___B2_B_Actv1p_Dpd_Bal_Tot_A1_Y_No_Cap_ := 0;
    KEL.typ.int B_E___B2_B_Actv1p_Dpd_Bal_Tot_No_Cap_ := 0;
    KEL.typ.int B_E___B2_B_Actv1p_Dpd_Cnt_No_Cap_ := 0;
    KEL.typ.int B_E___B2_B_Actv31p_Dpd_Bal_Tot_A1_Y_ := 0;
    KEL.typ.int B_E___B2_B_Actv31p_Dpd_Bal_Tot_A1_Y_No_Cap_ := 0;
    KEL.typ.int B_E___B2_B_Actv31p_Dpd_Bal_Tot_No_Cap_ := 0;
    KEL.typ.int B_E___B2_B_Actv31p_Dpd_Cnt_No_Cap_ := 0;
    KEL.typ.int B_E___B2_B_Actv61p_Dpd_Bal_Tot_A1_Y_ := 0;
    KEL.typ.int B_E___B2_B_Actv61p_Dpd_Bal_Tot_A1_Y_No_Cap_ := 0;
    KEL.typ.int B_E___B2_B_Actv61p_Dpd_Bal_Tot_No_Cap_ := 0;
    KEL.typ.int B_E___B2_B_Actv61p_Dpd_Cnt_No_Cap_ := 0;
    KEL.typ.int B_E___B2_B_Actv91p_Dpd_Bal_Tot_A1_Y_ := 0;
    KEL.typ.int B_E___B2_B_Actv91p_Dpd_Bal_Tot_A1_Y_No_Cap_ := 0;
    KEL.typ.int B_E___B2_B_Actv91p_Dpd_Bal_Tot_No_Cap_ := 0;
    KEL.typ.int B_E___B2_B_Actv91p_Dpd_Cnt_No_Cap_ := 0;
    KEL.typ.int B_E___B2_B_Actv_Bal_Tot_ := 0;
    KEL.typ.int B_E___B2_B_Actv_Bal_Tot_A1_Y_ := 0;
    KEL.typ.int B_E___B2_B_Actv_Bal_Tot_Arch1_Y_No_Cap_ := 0;
    KEL.typ.nfloat B_E___B2_B_Actv_Bal_Tot_Grow1_Y_;
    KEL.typ.int B_E___B2_B_Actv_Bal_Tot_No_Cap_ := 0;
    KEL.typ.int B_E___B2_B_Actv_Carr_Bal_Tot_ := 0;
    KEL.typ.int B_E___B2_B_Actv_Carr_Bal_Tot_A1_Y_ := 0;
    KEL.typ.int B_E___B2_B_Actv_Carr_Bal_Tot_Arch1_Y_No_Cap_ := 0;
    KEL.typ.nfloat B_E___B2_B_Actv_Carr_Bal_Tot_Grow1_Y_;
    KEL.typ.int B_E___B2_B_Actv_Carr_Bal_Tot_No_Cap_ := 0;
    KEL.typ.int B_E___B2_B_Actv_Carr_Cnt_ := 0;
    KEL.typ.int B_E___B2_B_Actv_Carr_Cnt_A1_Y_ := 0;
    KEL.typ.int B_E___B2_B_Actv_Carr_Cnt_A1_Y_No_Cap_ := 0;
    KEL.typ.int B_E___B2_B_Actv_Carr_Cnt_No_Cap_ := 0;
    KEL.typ.int B_E___B2_B_Actv_Cnt_ := 0;
    KEL.typ.int B_E___B2_B_Actv_Cnt_A1_Y_ := 0;
    KEL.typ.int B_E___B2_B_Actv_Cnt_A1_Y_No_Cap_ := 0;
    KEL.typ.int B_E___B2_B_Actv_Cnt_No_Cap_ := 0;
    KEL.typ.int B_E___B2_B_Actv_Flt_Bal_Tot_ := 0;
    KEL.typ.int B_E___B2_B_Actv_Flt_Bal_Tot_A1_Y_ := 0;
    KEL.typ.int B_E___B2_B_Actv_Flt_Bal_Tot_Arch1_Y_No_Cap_ := 0;
    KEL.typ.nfloat B_E___B2_B_Actv_Flt_Bal_Tot_Grow1_Y_;
    KEL.typ.int B_E___B2_B_Actv_Flt_Bal_Tot_No_Cap_ := 0;
    KEL.typ.int B_E___B2_B_Actv_Flt_Cnt_ := 0;
    KEL.typ.int B_E___B2_B_Actv_Flt_Cnt_A1_Y_ := 0;
    KEL.typ.int B_E___B2_B_Actv_Flt_Cnt_A1_Y_No_Cap_ := 0;
    KEL.typ.int B_E___B2_B_Actv_Flt_Cnt_No_Cap_ := 0;
    KEL.typ.int B_E___B2_B_Actv_Mat_Bal_Tot_ := 0;
    KEL.typ.int B_E___B2_B_Actv_Mat_Bal_Tot_A1_Y_ := 0;
    KEL.typ.int B_E___B2_B_Actv_Mat_Bal_Tot_Arch1_Y_No_Cap_ := 0;
    KEL.typ.nfloat B_E___B2_B_Actv_Mat_Bal_Tot_Grow1_Y_;
    KEL.typ.int B_E___B2_B_Actv_Mat_Bal_Tot_No_Cap_ := 0;
    KEL.typ.int B_E___B2_B_Actv_Mat_Cnt_ := 0;
    KEL.typ.int B_E___B2_B_Actv_Mat_Cnt_A1_Y_ := 0;
    KEL.typ.int B_E___B2_B_Actv_Mat_Cnt_A1_Y_No_Cap_ := 0;
    KEL.typ.int B_E___B2_B_Actv_Mat_Cnt_No_Cap_ := 0;
    KEL.typ.int B_E___B2_B_Actv_Ops_Bal_Tot_ := 0;
    KEL.typ.int B_E___B2_B_Actv_Ops_Bal_Tot_A1_Y_ := 0;
    KEL.typ.int B_E___B2_B_Actv_Ops_Bal_Tot_Arch1_Y_No_Cap_ := 0;
    KEL.typ.nfloat B_E___B2_B_Actv_Ops_Bal_Tot_Grow1_Y_;
    KEL.typ.int B_E___B2_B_Actv_Ops_Bal_Tot_No_Cap_ := 0;
    KEL.typ.int B_E___B2_B_Actv_Ops_Cnt_ := 0;
    KEL.typ.int B_E___B2_B_Actv_Ops_Cnt_A1_Y_ := 0;
    KEL.typ.int B_E___B2_B_Actv_Ops_Cnt_A1_Y_No_Cap_ := 0;
    KEL.typ.int B_E___B2_B_Actv_Ops_Cnt_No_Cap_ := 0;
    KEL.typ.int B_E___B2_B_Actv_Oth_Bal_Tot_ := 0;
    KEL.typ.int B_E___B2_B_Actv_Oth_Bal_Tot_A1_Y_ := 0;
    KEL.typ.int B_E___B2_B_Actv_Oth_Bal_Tot_Arch1_Y_No_Cap_ := 0;
    KEL.typ.nfloat B_E___B2_B_Actv_Oth_Bal_Tot_Grow1_Y_;
    KEL.typ.int B_E___B2_B_Actv_Oth_Bal_Tot_No_Cap_ := 0;
    KEL.typ.int B_E___B2_B_Actv_Oth_Cnt_ := 0;
    KEL.typ.int B_E___B2_B_Actv_Oth_Cnt_A1_Y_ := 0;
    KEL.typ.int B_E___B2_B_Actv_Oth_Cnt_A1_Y_No_Cap_ := 0;
    KEL.typ.int B_E___B2_B_Actv_Oth_Cnt_No_Cap_ := 0;
    KEL.typ.nint B_E___B2_B_Bal_Max2_Y_No_Cap_;
    KEL.typ.nstr B_E___B2_B_Bal_Max_Dt2_Y_;
    KEL.typ.int B_E___B2_B_Bal_Max_Seg_Type2_Y_Map_Carr_ := 0;
    KEL.typ.int B_E___B2_B_Bal_Max_Seg_Type2_Y_Map_Flt_ := 0;
    KEL.typ.int B_E___B2_B_Bal_Max_Seg_Type2_Y_Map_Mat_ := 0;
    KEL.typ.int B_E___B2_B_Bal_Max_Seg_Type2_Y_Map_Ops_ := 0;
    KEL.typ.int B_E___B2_B_Bal_Max_Seg_Type2_Y_Map_Oth_ := 0;
    KEL.typ.nint B_E___B2_B_Carr_Bal_Max2_Y_No_Cap_;
    KEL.typ.nstr B_E___B2_B_Carr_Bal_Max_Dt2_Y_;
    KEL.typ.int B_E___B2_B_Carr_Cnt24_Mc_ := 0;
    KEL.typ.int B_E___B2_B_Carr_Cnt24_Mc_No_Cap_ := 0;
    KEL.typ.int B_E___B2_B_Carr_Cnt2_Y_ := 0;
    KEL.typ.int B_E___B2_B_Carr_Cnt2_Y_No_Cap_ := 0;
    KEL.typ.str B_E___B2_B_Carr_Rec_Flag_By_Mon_Str24_Mc_ := '';
    KEL.typ.nint B_E___B2_B_Carr_Rec_Flag_By_Mon_Sum24_Mc_;
    KEL.typ.nstr B_E___B2_B_Carr_Worst_Perf_Dt2_Y_;
    KEL.typ.str B_E___B2_B_Carr_Worst_Perf_Indx2_Y_ := '';
    KEL.typ.int B_E___B2_B_Cnt24_Mc_ := 0;
    KEL.typ.int B_E___B2_B_Cnt24_Mc_No_Cap_ := 0;
    KEL.typ.int B_E___B2_B_Cnt2_Y_ := 0;
    KEL.typ.int B_E___B2_B_Cnt2_Y_No_Cap_ := 0;
    KEL.typ.nint B_E___B2_B_Cnt_Ev_;
    KEL.typ.nint B_E___B2_B_Flt_Bal_Max2_Y_No_Cap_;
    KEL.typ.nstr B_E___B2_B_Flt_Bal_Max_Dt2_Y_;
    KEL.typ.int B_E___B2_B_Flt_Cnt24_Mc_ := 0;
    KEL.typ.int B_E___B2_B_Flt_Cnt24_Mc_No_Cap_ := 0;
    KEL.typ.int B_E___B2_B_Flt_Cnt2_Y_ := 0;
    KEL.typ.int B_E___B2_B_Flt_Cnt2_Y_No_Cap_ := 0;
    KEL.typ.str B_E___B2_B_Flt_Rec_Flag_By_Mon_Str24_Mc_ := '';
    KEL.typ.nint B_E___B2_B_Flt_Rec_Flag_By_Mon_Sum24_Mc_;
    KEL.typ.nstr B_E___B2_B_Flt_Worst_Perf_Dt2_Y_;
    KEL.typ.str B_E___B2_B_Flt_Worst_Perf_Indx2_Y_ := '';
    KEL.typ.nint B_E___B2_B_Mat_Bal_Max2_Y_No_Cap_;
    KEL.typ.nstr B_E___B2_B_Mat_Bal_Max_Dt2_Y_;
    KEL.typ.int B_E___B2_B_Mat_Cnt24_Mc_ := 0;
    KEL.typ.int B_E___B2_B_Mat_Cnt24_Mc_No_Cap_ := 0;
    KEL.typ.int B_E___B2_B_Mat_Cnt2_Y_ := 0;
    KEL.typ.int B_E___B2_B_Mat_Cnt2_Y_No_Cap_ := 0;
    KEL.typ.str B_E___B2_B_Mat_Rec_Flag_By_Mon_Str24_Mc_ := '';
    KEL.typ.nint B_E___B2_B_Mat_Rec_Flag_By_Mon_Sum24_Mc_;
    KEL.typ.nstr B_E___B2_B_Mat_Worst_Perf_Dt2_Y_;
    KEL.typ.str B_E___B2_B_Mat_Worst_Perf_Indx2_Y_ := '';
    KEL.typ.nstr B_E___B2_B_New_Dt2_Y_;
    KEL.typ.nstr B_E___B2_B_Old_Dt2_Y_;
    KEL.typ.nstr B_E___B2_B_Old_Dt_Ev_;
    KEL.typ.nint B_E___B2_B_Ops_Bal_Max2_Y_No_Cap_;
    KEL.typ.nstr B_E___B2_B_Ops_Bal_Max_Dt2_Y_;
    KEL.typ.int B_E___B2_B_Ops_Cnt24_Mc_ := 0;
    KEL.typ.int B_E___B2_B_Ops_Cnt24_Mc_No_Cap_ := 0;
    KEL.typ.int B_E___B2_B_Ops_Cnt2_Y_ := 0;
    KEL.typ.int B_E___B2_B_Ops_Cnt2_Y_No_Cap_ := 0;
    KEL.typ.str B_E___B2_B_Ops_Rec_Flag_By_Mon_Str24_Mc_ := '';
    KEL.typ.nint B_E___B2_B_Ops_Rec_Flag_By_Mon_Sum24_Mc_;
    KEL.typ.nstr B_E___B2_B_Ops_Worst_Perf_Dt2_Y_;
    KEL.typ.str B_E___B2_B_Ops_Worst_Perf_Indx2_Y_ := '';
    KEL.typ.nint B_E___B2_B_Oth_Bal_Max2_Y_No_Cap_;
    KEL.typ.nstr B_E___B2_B_Oth_Bal_Max_Dt2_Y_;
    KEL.typ.int B_E___B2_B_Oth_Cnt24_Mc_ := 0;
    KEL.typ.int B_E___B2_B_Oth_Cnt24_Mc_No_Cap_ := 0;
    KEL.typ.int B_E___B2_B_Oth_Cnt2_Y_ := 0;
    KEL.typ.int B_E___B2_B_Oth_Cnt2_Y_No_Cap_ := 0;
    KEL.typ.str B_E___B2_B_Oth_Rec_Flag_By_Mon_Str24_Mc_ := '';
    KEL.typ.nint B_E___B2_B_Oth_Rec_Flag_By_Mon_Sum24_Mc_;
    KEL.typ.nstr B_E___B2_B_Oth_Worst_Perf_Dt2_Y_;
    KEL.typ.str B_E___B2_B_Oth_Worst_Perf_Indx2_Y_ := '';
    KEL.typ.str B_E___B2_B_Rec_Flag_By_Mon_Str24_Mc_ := '';
    KEL.typ.nint B_E___B2_B_Rec_Flag_By_Mon_Sum24_Mc_;
    KEL.typ.nstr B_E___B2_B_Worst_Perf_Dt2_Y_;
    KEL.typ.str B_E___B2_B_Worst_Perf_Indx2_Y_ := '';
    KEL.typ.ntyp(E_Business_Sele().Typ) U_I_D__1_;
    KEL.typ.nkdate O_N_L_Y___C_U_R_R_E_N_T___D_A_T_E_;
    KEL.typ.nkdate O_N_L_Y___C_U_R_R_E_N_T___D_A_T_E__1_;
    KEL.typ.nkdate O_N_L_Y___C_U_R_R_E_N_T___D_A_T_E__2_;
    KEL.typ.nkdate O_N_L_Y___C_U_R_R_E_N_T___D_A_T_E__3_;
    KEL.typ.nkdate O_N_L_Y___C_U_R_R_E_N_T___D_A_T_E__4_;
    KEL.typ.nkdate O_N_L_Y___C_U_R_R_E_N_T___D_A_T_E__5_;
    KEL.typ.nkdate O_N_L_Y___C_U_R_R_E_N_T___D_A_T_E__6_;
    KEL.typ.nkdate O_N_L_Y___C_U_R_R_E_N_T___D_A_T_E__7_;
    KEL.typ.nkdate O_N_L_Y___C_U_R_R_E_N_T___D_A_T_E__8_;
    KEL.typ.nkdate O_N_L_Y___C_U_R_R_E_N_T___D_A_T_E__9_;
    KEL.typ.nkdate O_N_L_Y___C_U_R_R_E_N_T___D_A_T_E__10_;
    KEL.typ.nkdate O_N_L_Y___C_U_R_R_E_N_T___D_A_T_E__11_;
    KEL.typ.nkdate O_N_L_Y___C_U_R_R_E_N_T___D_A_T_E__12_;
    KEL.typ.nkdate O_N_L_Y___C_U_R_R_E_N_T___D_A_T_E__13_;
    KEL.typ.nkdate O_N_L_Y___C_U_R_R_E_N_T___D_A_T_E__14_;
    KEL.typ.nint M_A_X___Perf_Level_;
    KEL.typ.nint M_A_X___Perf_Level__1_;
    KEL.typ.nint M_A_X___Perf_Level__2_;
    KEL.typ.nint M_A_X___Perf_Level__3_;
    KEL.typ.nint M_A_X___Perf_Level__4_;
    KEL.typ.nint M_A_X___Perf_Level__5_;
    KEL.typ.ntyp(E_Business_Sele().Typ) U_I_D__2_;
    KEL.typ.epoch Archive___Date_ := 0;
    KEL.typ.epoch Date_First_Seen_ := 0;
    KEL.typ.epoch Date_Last_Seen_ := 0;
    KEL.typ.epoch Hybrid_Archive_Date_ := 0;
    KEL.typ.epoch Vault_Date_Last_Seen_ := 0;
    KEL.typ.int __RecordCount := 0;
  END;
  __JC637408(__ST395683_Layout __EE634367, __ST391495_Layout __EE637402) := __EEQP(__EE634367.UID,__EE637402.UID);
  __ST398525_Layout __JT637408(__ST395683_Layout __l, __ST391495_Layout __r) := TRANSFORM
    SELF.U_I_D__2_ := __r.UID;
    SELF := __l;
    SELF := __r;
  END;
  SHARED __EE637752 := JOIN(__EE634367,__EE637402,__JC637408(LEFT,RIGHT),__JT637408(LEFT,RIGHT),LEFT OUTER,HASH);
  EXPORT __ST127693_Layout := RECORD
    KEL.typ.nuid UID;
    KEL.typ.nint Ult_I_D_;
    KEL.typ.nint Org_I_D_;
    KEL.typ.nint Sele_I_D_;
    KEL.typ.ntyp(E_Business_Org().Typ) Sele_Org_;
    KEL.typ.ntyp(E_Business_Sele_Overflow().Typ) Sele_Overflow_;
    KEL.typ.nbool Sele_Gold_;
    KEL.typ.nbool Is_Sele_Level_;
    KEL.typ.nbool Is_Org_Level_;
    KEL.typ.nbool Is_Ult_Level_;
    KEL.typ.nstr Sele_Segment_;
    KEL.typ.nbool Is_Corporation_;
    KEL.typ.ndataset(E_Business_Sele(__in,__cfg).Business_Structure_Layout) Business_Structure_;
    KEL.typ.ndataset(E_Business_Sele(__in,__cfg).Ownership_Layout) Ownership_;
    KEL.typ.ndataset(E_Business_Sele(__in,__cfg).Industry_Layout) Industry_;
    KEL.typ.ndataset(E_Business_Sele(__in,__cfg).Company_Statuses_Layout) Company_Statuses_;
    KEL.typ.ndataset(E_Business_Sele(__in,__cfg).Age_Layout) Age_;
    KEL.typ.ndataset(E_Business_Sele(__in,__cfg).Reported_Names_Layout) Reported_Names_;
    KEL.typ.ndataset(E_Business_Sele(__in,__cfg).Stock_Tickers_Layout) Stock_Tickers_;
    KEL.typ.ndataset(E_Business_Sele(__in,__cfg).U_R_Ls_Layout) U_R_Ls_;
    KEL.typ.ndataset(E_Business_Sele(__in,__cfg).S_I_C_Codes_Layout) S_I_C_Codes_;
    KEL.typ.ndataset(E_Business_Sele(__in,__cfg).N_A_I_C_S_Codes_Layout) N_A_I_C_S_Codes_;
    KEL.typ.ndataset(E_Business_Sele(__in,__cfg).Employee_Counts_Layout) Employee_Counts_;
    KEL.typ.ndataset(E_Business_Sele(__in,__cfg).Sale_Amounts_Layout) Sale_Amounts_;
    KEL.typ.ndataset(E_Business_Sele(__in,__cfg).Earning_Amounts_Layout) Earning_Amounts_;
    KEL.typ.ndataset(E_Business_Sele(__in,__cfg).Asset_Amounts_Layout) Asset_Amounts_;
    KEL.typ.nkdate B_B_B_Member_Since_;
    KEL.typ.ndataset(E_Business_Sele(__in,__cfg).B_B_B_Categories_Layout) B_B_B_Categories_;
    KEL.typ.nstr For_Profit_Indicator_;
    KEL.typ.nstr Public_Or_Private_Indicator_;
    KEL.typ.ndataset(E_Business_Sele(__in,__cfg).Non_Profit_Layout) Non_Profit_;
    KEL.typ.ndataset(E_Business_Sele(__in,__cfg).Best_Company_Names_Layout) Best_Company_Names_;
    KEL.typ.ndataset(E_Business_Sele(__in,__cfg).Best_S_I_C_Codes_Layout) Best_S_I_C_Codes_;
    KEL.typ.ndataset(E_Business_Sele(__in,__cfg).Best_N_A_I_C_S_Codes_Layout) Best_N_A_I_C_S_Codes_;
    KEL.typ.ndataset(E_Business_Sele(__in,__cfg).Business_Characteristics_Layout) Business_Characteristics_;
    KEL.typ.ndataset(E_Business_Sele(__in,__cfg).Experian_C_R_D_B_Tradelines_Layout) Experian_C_R_D_B_Tradelines_;
    KEL.typ.ndataset(E_Business_Sele(__in,__cfg).Data_Sources_Layout) Data_Sources_;
    KEL.typ.int B_E___B2_B_Actv1p_Dpd_Bal_Tot_ := 0;
    KEL.typ.int B_E___B2_B_Actv1p_Dpd_Bal_Tot_A1_Y_ := 0;
    KEL.typ.float B_E___B2_B_Actv1p_Dpd_Bal_Tot_Grow1_Y_ := 0.0;
    KEL.typ.float B_E___B2_B_Actv1p_Dpd_Bal_Tot_Pct_ := 0.0;
    KEL.typ.int B_E___B2_B_Actv1p_Dpd_Cnt_ := 0;
    KEL.typ.float B_E___B2_B_Actv1p_Dpd_Pct_ := 0.0;
    KEL.typ.int B_E___B2_B_Actv31p_Dpd_Bal_Tot_ := 0;
    KEL.typ.int B_E___B2_B_Actv31p_Dpd_Bal_Tot_A1_Y_ := 0;
    KEL.typ.float B_E___B2_B_Actv31p_Dpd_Bal_Tot_Grow1_Y_ := 0.0;
    KEL.typ.float B_E___B2_B_Actv31p_Dpd_Bal_Tot_Pct_ := 0.0;
    KEL.typ.int B_E___B2_B_Actv31p_Dpd_Cnt_ := 0;
    KEL.typ.float B_E___B2_B_Actv31p_Dpd_Pct_ := 0.0;
    KEL.typ.int B_E___B2_B_Actv61p_Dpd_Bal_Tot_ := 0;
    KEL.typ.int B_E___B2_B_Actv61p_Dpd_Bal_Tot_A1_Y_ := 0;
    KEL.typ.float B_E___B2_B_Actv61p_Dpd_Bal_Tot_Grow1_Y_ := 0.0;
    KEL.typ.float B_E___B2_B_Actv61p_Dpd_Bal_Tot_Pct_ := 0.0;
    KEL.typ.int B_E___B2_B_Actv61p_Dpd_Cnt_ := 0;
    KEL.typ.float B_E___B2_B_Actv61p_Dpd_Pct_ := 0.0;
    KEL.typ.int B_E___B2_B_Actv91p_Dpd_Bal_Tot_ := 0;
    KEL.typ.int B_E___B2_B_Actv91p_Dpd_Bal_Tot_A1_Y_ := 0;
    KEL.typ.float B_E___B2_B_Actv91p_Dpd_Bal_Tot_Grow1_Y_ := 0.0;
    KEL.typ.float B_E___B2_B_Actv91p_Dpd_Bal_Tot_Pct_ := 0.0;
    KEL.typ.int B_E___B2_B_Actv91p_Dpd_Cnt_ := 0;
    KEL.typ.float B_E___B2_B_Actv91p_Dpd_Pct_ := 0.0;
    KEL.typ.int B_E___B2_B_Actv_Bal_Avg_ := 0;
    KEL.typ.int B_E___B2_B_Actv_Bal_Tot_ := 0;
    KEL.typ.int B_E___B2_B_Actv_Bal_Tot_A1_Y_ := 0;
    KEL.typ.nfloat B_E___B2_B_Actv_Bal_Tot_Grow1_Y_;
    KEL.typ.nstr B_E___B2_B_Actv_Bal_Tot_Grow_Indx1_Y_;
    KEL.typ.nstr B_E___B2_B_Actv_Bal_Tot_Rnge_;
    KEL.typ.int B_E___B2_B_Actv_Carr_Bal_Avg_ := 0;
    KEL.typ.int B_E___B2_B_Actv_Carr_Bal_Tot_ := 0;
    KEL.typ.int B_E___B2_B_Actv_Carr_Bal_Tot_A1_Y_ := 0;
    KEL.typ.nfloat B_E___B2_B_Actv_Carr_Bal_Tot_Grow1_Y_;
    KEL.typ.nstr B_E___B2_B_Actv_Carr_Bal_Tot_Grow_Indx1_Y_;
    KEL.typ.nfloat B_E___B2_B_Actv_Carr_Bal_Tot_Pct_;
    KEL.typ.nstr B_E___B2_B_Actv_Carr_Bal_Tot_Rnge_;
    KEL.typ.int B_E___B2_B_Actv_Carr_Cnt_ := 0;
    KEL.typ.int B_E___B2_B_Actv_Carr_Cnt_A1_Y_ := 0;
    KEL.typ.float B_E___B2_B_Actv_Carr_Cnt_Grow1_Y_ := 0.0;
    KEL.typ.float B_E___B2_B_Actv_Carr_Pct_ := 0.0;
    KEL.typ.nstr B_E___B2_B_Actv_Carr_Worst_Perf_Indx_;
    KEL.typ.int B_E___B2_B_Actv_Cnt_ := 0;
    KEL.typ.int B_E___B2_B_Actv_Cnt_A1_Y_ := 0;
    KEL.typ.float B_E___B2_B_Actv_Cnt_Grow1_Y_ := 0.0;
    KEL.typ.int B_E___B2_B_Actv_Flt_Bal_Avg_ := 0;
    KEL.typ.nfloat B_E___B2_B_Actv_Flt_Bal_Pct_;
    KEL.typ.int B_E___B2_B_Actv_Flt_Bal_Tot_ := 0;
    KEL.typ.int B_E___B2_B_Actv_Flt_Bal_Tot_A1_Y_ := 0;
    KEL.typ.nfloat B_E___B2_B_Actv_Flt_Bal_Tot_Grow1_Y_;
    KEL.typ.nstr B_E___B2_B_Actv_Flt_Bal_Tot_Grow_Indx1_Y_;
    KEL.typ.nstr B_E___B2_B_Actv_Flt_Bal_Tot_Rnge_;
    KEL.typ.int B_E___B2_B_Actv_Flt_Cnt_ := 0;
    KEL.typ.int B_E___B2_B_Actv_Flt_Cnt_A1_Y_ := 0;
    KEL.typ.float B_E___B2_B_Actv_Flt_Cnt_Grow1_Y_ := 0.0;
    KEL.typ.float B_E___B2_B_Actv_Flt_Pct_ := 0.0;
    KEL.typ.nstr B_E___B2_B_Actv_Flt_Worst_Perf_Indx_;
    KEL.typ.int B_E___B2_B_Actv_Mat_Bal_Avg_ := 0;
    KEL.typ.nfloat B_E___B2_B_Actv_Mat_Bal_Pct_;
    KEL.typ.int B_E___B2_B_Actv_Mat_Bal_Tot_ := 0;
    KEL.typ.int B_E___B2_B_Actv_Mat_Bal_Tot_A1_Y_ := 0;
    KEL.typ.nfloat B_E___B2_B_Actv_Mat_Bal_Tot_Grow1_Y_;
    KEL.typ.nstr B_E___B2_B_Actv_Mat_Bal_Tot_Grow_Indx1_Y_;
    KEL.typ.nstr B_E___B2_B_Actv_Mat_Bal_Tot_Rnge_;
    KEL.typ.int B_E___B2_B_Actv_Mat_Cnt_ := 0;
    KEL.typ.int B_E___B2_B_Actv_Mat_Cnt_A1_Y_ := 0;
    KEL.typ.float B_E___B2_B_Actv_Mat_Cnt_Grow1_Y_ := 0.0;
    KEL.typ.float B_E___B2_B_Actv_Mat_Pct_ := 0.0;
    KEL.typ.nstr B_E___B2_B_Actv_Mat_Worst_Perf_Indx_;
    KEL.typ.int B_E___B2_B_Actv_Ops_Bal_Avg_ := 0;
    KEL.typ.nfloat B_E___B2_B_Actv_Ops_Bal_Pct_;
    KEL.typ.int B_E___B2_B_Actv_Ops_Bal_Tot_ := 0;
    KEL.typ.int B_E___B2_B_Actv_Ops_Bal_Tot_A1_Y_ := 0;
    KEL.typ.nfloat B_E___B2_B_Actv_Ops_Bal_Tot_Grow1_Y_;
    KEL.typ.nstr B_E___B2_B_Actv_Ops_Bal_Tot_Grow_Indx1_Y_;
    KEL.typ.nstr B_E___B2_B_Actv_Ops_Bal_Tot_Rnge_;
    KEL.typ.int B_E___B2_B_Actv_Ops_Cnt_ := 0;
    KEL.typ.int B_E___B2_B_Actv_Ops_Cnt_A1_Y_ := 0;
    KEL.typ.float B_E___B2_B_Actv_Ops_Cnt_Grow1_Y_ := 0.0;
    KEL.typ.float B_E___B2_B_Actv_Ops_Pct_ := 0.0;
    KEL.typ.nstr B_E___B2_B_Actv_Ops_Worst_Perf_Indx_;
    KEL.typ.int B_E___B2_B_Actv_Oth_Bal_Avg_ := 0;
    KEL.typ.nfloat B_E___B2_B_Actv_Oth_Bal_Pct_;
    KEL.typ.int B_E___B2_B_Actv_Oth_Bal_Tot_ := 0;
    KEL.typ.int B_E___B2_B_Actv_Oth_Bal_Tot_A1_Y_ := 0;
    KEL.typ.nfloat B_E___B2_B_Actv_Oth_Bal_Tot_Grow1_Y_;
    KEL.typ.nstr B_E___B2_B_Actv_Oth_Bal_Tot_Grow_Indx1_Y_;
    KEL.typ.nstr B_E___B2_B_Actv_Oth_Bal_Tot_Rnge_;
    KEL.typ.int B_E___B2_B_Actv_Oth_Cnt_ := 0;
    KEL.typ.int B_E___B2_B_Actv_Oth_Cnt_A1_Y_ := 0;
    KEL.typ.float B_E___B2_B_Actv_Oth_Cnt_Grow1_Y_ := 0.0;
    KEL.typ.float B_E___B2_B_Actv_Oth_Pct_ := 0.0;
    KEL.typ.nstr B_E___B2_B_Actv_Oth_Worst_Perf_Indx_;
    KEL.typ.nstr B_E___B2_B_Actv_Worst_Perf_Indx_;
    KEL.typ.nint B_E___B2_B_Bal_Max2_Y_;
    KEL.typ.nstr B_E___B2_B_Bal_Max_Dt2_Y_;
    KEL.typ.nint B_E___B2_B_Bal_Max_Msnc2_Y_;
    KEL.typ.nstr B_E___B2_B_Bal_Max_Seg_Type2_Y_;
    KEL.typ.nfloat B_E___B2_B_Bal_Vol24_Mc_;
    KEL.typ.nint B_E___B2_B_Carr_Bal_Max2_Y_;
    KEL.typ.nstr B_E___B2_B_Carr_Bal_Max_Dt2_Y_;
    KEL.typ.nint B_E___B2_B_Carr_Bal_Max_Msnc2_Y_;
    KEL.typ.nfloat B_E___B2_B_Carr_Bal_Vol24_Mc_;
    KEL.typ.int B_E___B2_B_Carr_Cnt24_Mc_ := 0;
    KEL.typ.int B_E___B2_B_Carr_Cnt2_Y_ := 0;
    KEL.typ.float B_E___B2_B_Carr_Pct2_Y_ := 0.0;
    KEL.typ.str B_E___B2_B_Carr_Rec_Flag_By_Mon_Str24_Mc_ := '';
    KEL.typ.nint B_E___B2_B_Carr_Rec_Flag_By_Mon_Sum24_Mc_;
    KEL.typ.nstr B_E___B2_B_Carr_Worst_Perf_Dt2_Y_;
    KEL.typ.str B_E___B2_B_Carr_Worst_Perf_Indx2_Y_ := '';
    KEL.typ.nint B_E___B2_B_Carr_Worst_Perf_Msnc2_Y_;
    KEL.typ.int B_E___B2_B_Cnt24_Mc_ := 0;
    KEL.typ.int B_E___B2_B_Cnt2_Y_ := 0;
    KEL.typ.nint B_E___B2_B_Cnt_Ev_;
    KEL.typ.nint B_E___B2_B_Flt_Bal_Max2_Y_;
    KEL.typ.nstr B_E___B2_B_Flt_Bal_Max_Dt2_Y_;
    KEL.typ.nint B_E___B2_B_Flt_Bal_Max_Msnc2_Y_;
    KEL.typ.nfloat B_E___B2_B_Flt_Bal_Vol24_Mc_;
    KEL.typ.int B_E___B2_B_Flt_Cnt24_Mc_ := 0;
    KEL.typ.int B_E___B2_B_Flt_Cnt2_Y_ := 0;
    KEL.typ.float B_E___B2_B_Flt_Pct2_Y_ := 0.0;
    KEL.typ.str B_E___B2_B_Flt_Rec_Flag_By_Mon_Str24_Mc_ := '';
    KEL.typ.nint B_E___B2_B_Flt_Rec_Flag_By_Mon_Sum24_Mc_;
    KEL.typ.nstr B_E___B2_B_Flt_Worst_Perf_Dt2_Y_;
    KEL.typ.str B_E___B2_B_Flt_Worst_Perf_Indx2_Y_ := '';
    KEL.typ.nint B_E___B2_B_Flt_Worst_Perf_Msnc2_Y_;
    KEL.typ.nint B_E___B2_B_Mat_Bal_Max2_Y_;
    KEL.typ.nstr B_E___B2_B_Mat_Bal_Max_Dt2_Y_;
    KEL.typ.nint B_E___B2_B_Mat_Bal_Max_Msnc2_Y_;
    KEL.typ.nfloat B_E___B2_B_Mat_Bal_Vol24_Mc_;
    KEL.typ.int B_E___B2_B_Mat_Cnt24_Mc_ := 0;
    KEL.typ.int B_E___B2_B_Mat_Cnt2_Y_ := 0;
    KEL.typ.float B_E___B2_B_Mat_Pct2_Y_ := 0.0;
    KEL.typ.str B_E___B2_B_Mat_Rec_Flag_By_Mon_Str24_Mc_ := '';
    KEL.typ.nint B_E___B2_B_Mat_Rec_Flag_By_Mon_Sum24_Mc_;
    KEL.typ.nstr B_E___B2_B_Mat_Worst_Perf_Dt2_Y_;
    KEL.typ.str B_E___B2_B_Mat_Worst_Perf_Indx2_Y_ := '';
    KEL.typ.nint B_E___B2_B_Mat_Worst_Perf_Msnc2_Y_;
    KEL.typ.nstr B_E___B2_B_New_Dt2_Y_;
    KEL.typ.nint B_E___B2_B_New_Msnc2_Y_;
    KEL.typ.nstr B_E___B2_B_Old_Dt2_Y_;
    KEL.typ.nstr B_E___B2_B_Old_Dt_Ev_;
    KEL.typ.nint B_E___B2_B_Old_Msnc2_Y_;
    KEL.typ.nint B_E___B2_B_Old_Msnc_Ev_;
    KEL.typ.nint B_E___B2_B_Ops_Bal_Max2_Y_;
    KEL.typ.nstr B_E___B2_B_Ops_Bal_Max_Dt2_Y_;
    KEL.typ.nint B_E___B2_B_Ops_Bal_Max_Msnc2_Y_;
    KEL.typ.nfloat B_E___B2_B_Ops_Bal_Vol24_Mc_;
    KEL.typ.int B_E___B2_B_Ops_Cnt24_Mc_ := 0;
    KEL.typ.int B_E___B2_B_Ops_Cnt2_Y_ := 0;
    KEL.typ.float B_E___B2_B_Ops_Pct2_Y_ := 0.0;
    KEL.typ.str B_E___B2_B_Ops_Rec_Flag_By_Mon_Str24_Mc_ := '';
    KEL.typ.nint B_E___B2_B_Ops_Rec_Flag_By_Mon_Sum24_Mc_;
    KEL.typ.nstr B_E___B2_B_Ops_Worst_Perf_Dt2_Y_;
    KEL.typ.str B_E___B2_B_Ops_Worst_Perf_Indx2_Y_ := '';
    KEL.typ.nint B_E___B2_B_Ops_Worst_Perf_Msnc2_Y_;
    KEL.typ.nint B_E___B2_B_Oth_Bal_Max2_Y_;
    KEL.typ.nstr B_E___B2_B_Oth_Bal_Max_Dt2_Y_;
    KEL.typ.nint B_E___B2_B_Oth_Bal_Max_Msnc2_Y_;
    KEL.typ.nfloat B_E___B2_B_Oth_Bal_Vol24_Mc_;
    KEL.typ.int B_E___B2_B_Oth_Cnt24_Mc_ := 0;
    KEL.typ.int B_E___B2_B_Oth_Cnt2_Y_ := 0;
    KEL.typ.float B_E___B2_B_Oth_Pct2_Y_ := 0.0;
    KEL.typ.str B_E___B2_B_Oth_Rec_Flag_By_Mon_Str24_Mc_ := '';
    KEL.typ.nint B_E___B2_B_Oth_Rec_Flag_By_Mon_Sum24_Mc_;
    KEL.typ.nstr B_E___B2_B_Oth_Worst_Perf_Dt2_Y_;
    KEL.typ.str B_E___B2_B_Oth_Worst_Perf_Indx2_Y_ := '';
    KEL.typ.nint B_E___B2_B_Oth_Worst_Perf_Msnc2_Y_;
    KEL.typ.str B_E___B2_B_Rec_Flag_By_Mon_Str24_Mc_ := '';
    KEL.typ.nint B_E___B2_B_Rec_Flag_By_Mon_Sum24_Mc_;
    KEL.typ.nstr B_E___B2_B_Worst_Perf_Dt2_Y_;
    KEL.typ.str B_E___B2_B_Worst_Perf_Indx2_Y_ := '';
    KEL.typ.nint B_E___B2_B_Worst_Perf_Msnc2_Y_;
    KEL.typ.str B___Lex_I_D_Legal_Seen_Flag_ := '';
    KEL.typ.epoch Archive___Date_ := 0;
    KEL.typ.epoch Date_First_Seen_ := 0;
    KEL.typ.epoch Date_Last_Seen_ := 0;
    KEL.typ.epoch Hybrid_Archive_Date_ := 0;
    KEL.typ.epoch Vault_Date_Last_Seen_ := 0;
    KEL.typ.int __RecordCount := 0;
  END;
  SHARED __ST127693_Layout __ND637757__Project(__ST398525_Layout __PP637753) := TRANSFORM
    __CC13803 := -99998;
    SELF.B_E___B2_B_Actv1p_Dpd_Bal_Tot_ := IF(__PP637753.B_E___B2_B_Actv_Cnt_ = 0,__CC13803,KEL.Routines.BoundsFold(__PP637753.B_E___B2_B_Actv1p_Dpd_Bal_Tot_No_Cap_,0,99999999));
    __CC13806 := -99997;
    SELF.B_E___B2_B_Actv1p_Dpd_Bal_Tot_Grow1_Y_ := MAP(__PP637753.B_E___B2_B_Actv_Cnt_A1_Y_ = 0 OR __PP637753.B_E___B2_B_Actv_Cnt_ = 0=>(KEL.typ.float)__CC13803,__PP637753.B_E___B2_B_Actv1p_Dpd_Bal_Tot_A1_Y_ = 0=>(KEL.typ.float)__CC13806,MIN(ROUND(__PP637753.B_E___B2_B_Actv1p_Dpd_Bal_Tot_No_Cap_ / __PP637753.B_E___B2_B_Actv1p_Dpd_Bal_Tot_A1_Y_No_Cap_,4),9999.9999));
    SELF.B_E___B2_B_Actv1p_Dpd_Bal_Tot_Pct_ := MAP(__PP637753.B_E___B2_B_Actv_Cnt_ = 0=>(KEL.typ.float)__CC13803,__PP637753.B_E___B2_B_Actv_Bal_Tot_ = 0=>(KEL.typ.float)__CC13806,__PP637753.B_E___B2_B_Actv1p_Dpd_Bal_Tot_No_Cap_ / __PP637753.B_E___B2_B_Actv_Bal_Tot_No_Cap_ * 100);
    SELF.B_E___B2_B_Actv1p_Dpd_Cnt_ := IF(__PP637753.B_E___B2_B_Actv_Cnt_ = 0,__CC13803,__PP637753.B_E___B2_B_Actv1p_Dpd_Cnt_No_Cap_);
    SELF.B_E___B2_B_Actv1p_Dpd_Pct_ := IF(__PP637753.B_E___B2_B_Actv_Cnt_ = 0,(KEL.typ.float)__CC13803,__PP637753.B_E___B2_B_Actv1p_Dpd_Cnt_No_Cap_ / __PP637753.B_E___B2_B_Actv_Cnt_No_Cap_ * 100);
    SELF.B_E___B2_B_Actv31p_Dpd_Bal_Tot_ := IF(__PP637753.B_E___B2_B_Actv_Cnt_ = 0,__CC13803,KEL.Routines.BoundsFold(__PP637753.B_E___B2_B_Actv31p_Dpd_Bal_Tot_No_Cap_,0,99999999));
    SELF.B_E___B2_B_Actv31p_Dpd_Bal_Tot_Grow1_Y_ := MAP(__PP637753.B_E___B2_B_Actv_Cnt_A1_Y_ = 0 OR __PP637753.B_E___B2_B_Actv_Cnt_ = 0=>(KEL.typ.float)__CC13803,__PP637753.B_E___B2_B_Actv31p_Dpd_Bal_Tot_A1_Y_ = 0=>(KEL.typ.float)__CC13806,MIN(ROUND(__PP637753.B_E___B2_B_Actv31p_Dpd_Bal_Tot_No_Cap_ / __PP637753.B_E___B2_B_Actv31p_Dpd_Bal_Tot_A1_Y_No_Cap_,4),9999.9999));
    SELF.B_E___B2_B_Actv31p_Dpd_Bal_Tot_Pct_ := MAP(__PP637753.B_E___B2_B_Actv_Cnt_ = 0=>(KEL.typ.float)__CC13803,__PP637753.B_E___B2_B_Actv_Bal_Tot_ = 0=>(KEL.typ.float)__CC13806,__PP637753.B_E___B2_B_Actv31p_Dpd_Bal_Tot_No_Cap_ / __PP637753.B_E___B2_B_Actv_Bal_Tot_No_Cap_ * 100);
    SELF.B_E___B2_B_Actv31p_Dpd_Cnt_ := IF(__PP637753.B_E___B2_B_Actv_Cnt_ = 0,__CC13803,__PP637753.B_E___B2_B_Actv31p_Dpd_Cnt_No_Cap_);
    SELF.B_E___B2_B_Actv31p_Dpd_Pct_ := IF(__PP637753.B_E___B2_B_Actv_Cnt_ = 0,(KEL.typ.float)__CC13803,__PP637753.B_E___B2_B_Actv31p_Dpd_Cnt_No_Cap_ / __PP637753.B_E___B2_B_Actv_Cnt_No_Cap_ * 100);
    SELF.B_E___B2_B_Actv61p_Dpd_Bal_Tot_ := IF(__PP637753.B_E___B2_B_Actv_Cnt_ = 0,__CC13803,KEL.Routines.BoundsFold(__PP637753.B_E___B2_B_Actv61p_Dpd_Bal_Tot_No_Cap_,0,99999999));
    SELF.B_E___B2_B_Actv61p_Dpd_Bal_Tot_Grow1_Y_ := MAP(__PP637753.B_E___B2_B_Actv_Cnt_A1_Y_ = 0 OR __PP637753.B_E___B2_B_Actv_Cnt_ = 0=>(KEL.typ.float)__CC13803,__PP637753.B_E___B2_B_Actv61p_Dpd_Bal_Tot_A1_Y_ = 0=>(KEL.typ.float)__CC13806,MIN(ROUND(__PP637753.B_E___B2_B_Actv61p_Dpd_Bal_Tot_No_Cap_ / __PP637753.B_E___B2_B_Actv61p_Dpd_Bal_Tot_A1_Y_No_Cap_,4),9999.9999));
    SELF.B_E___B2_B_Actv61p_Dpd_Bal_Tot_Pct_ := MAP(__PP637753.B_E___B2_B_Actv_Cnt_ = 0=>(KEL.typ.float)__CC13803,__PP637753.B_E___B2_B_Actv_Bal_Tot_ = 0=>(KEL.typ.float)__CC13806,__PP637753.B_E___B2_B_Actv61p_Dpd_Bal_Tot_No_Cap_ / __PP637753.B_E___B2_B_Actv_Bal_Tot_No_Cap_ * 100);
    SELF.B_E___B2_B_Actv61p_Dpd_Cnt_ := IF(__PP637753.B_E___B2_B_Actv_Cnt_ = 0,__CC13803,__PP637753.B_E___B2_B_Actv61p_Dpd_Cnt_No_Cap_);
    SELF.B_E___B2_B_Actv61p_Dpd_Pct_ := IF(__PP637753.B_E___B2_B_Actv_Cnt_ = 0,(KEL.typ.float)__CC13803,__PP637753.B_E___B2_B_Actv61p_Dpd_Cnt_No_Cap_ / __PP637753.B_E___B2_B_Actv_Cnt_No_Cap_ * 100);
    SELF.B_E___B2_B_Actv91p_Dpd_Bal_Tot_ := IF(__PP637753.B_E___B2_B_Actv_Cnt_ = 0,__CC13803,KEL.Routines.BoundsFold(__PP637753.B_E___B2_B_Actv91p_Dpd_Bal_Tot_No_Cap_,0,99999999));
    SELF.B_E___B2_B_Actv91p_Dpd_Bal_Tot_Grow1_Y_ := MAP(__PP637753.B_E___B2_B_Actv_Cnt_A1_Y_ = 0 OR __PP637753.B_E___B2_B_Actv_Cnt_ = 0=>(KEL.typ.float)__CC13803,__PP637753.B_E___B2_B_Actv91p_Dpd_Bal_Tot_A1_Y_ = 0=>(KEL.typ.float)__CC13806,MIN(ROUND(__PP637753.B_E___B2_B_Actv91p_Dpd_Bal_Tot_No_Cap_ / __PP637753.B_E___B2_B_Actv91p_Dpd_Bal_Tot_A1_Y_No_Cap_,4),9999.9999));
    SELF.B_E___B2_B_Actv91p_Dpd_Bal_Tot_Pct_ := MAP(__PP637753.B_E___B2_B_Actv_Cnt_ = 0=>(KEL.typ.float)__CC13803,__PP637753.B_E___B2_B_Actv_Bal_Tot_ = 0=>(KEL.typ.float)__CC13806,__PP637753.B_E___B2_B_Actv91p_Dpd_Bal_Tot_No_Cap_ / __PP637753.B_E___B2_B_Actv_Bal_Tot_No_Cap_ * 100);
    SELF.B_E___B2_B_Actv91p_Dpd_Cnt_ := IF(__PP637753.B_E___B2_B_Actv_Cnt_ = 0,__CC13803,__PP637753.B_E___B2_B_Actv91p_Dpd_Cnt_No_Cap_);
    SELF.B_E___B2_B_Actv91p_Dpd_Pct_ := IF(__PP637753.B_E___B2_B_Actv_Cnt_ = 0,(KEL.typ.float)__CC13803,__PP637753.B_E___B2_B_Actv91p_Dpd_Cnt_No_Cap_ / __PP637753.B_E___B2_B_Actv_Cnt_No_Cap_ * 100);
    SELF.B_E___B2_B_Actv_Bal_Avg_ := IF(__PP637753.B_E___B2_B_Actv_Cnt_ = 0,__CC13803,KEL.Routines.BoundsFold(ROUND(__PP637753.B_E___B2_B_Actv_Bal_Tot_No_Cap_ / __PP637753.B_E___B2_B_Actv_Cnt_No_Cap_),0,99999999));
    __CC13800 := '-99998';
    __CC13808 := '-99997';
    SELF.B_E___B2_B_Actv_Bal_Tot_Grow_Indx1_Y_ := MAP(__PP637753.B_E___B2_B_Actv_Cnt_ = 0=>__ECAST(KEL.typ.nstr,__CN(__CC13800)),__PP637753.B_E___B2_B_Actv_Cnt_A1_Y_ = 0=>__ECAST(KEL.typ.nstr,__CN(__CC13800)),__PP637753.B_E___B2_B_Actv_Bal_Tot_A1_Y_ = 0=>__ECAST(KEL.typ.nstr,__CN(__CC13808)),__T(__AND(__OP2(__PP637753.B_E___B2_B_Actv_Bal_Tot_Grow1_Y_,>=,__CN(0)),__OP2(__PP637753.B_E___B2_B_Actv_Bal_Tot_Grow1_Y_,<,__CN(1))))=>__ECAST(KEL.typ.nstr,__CN('0')),__T(__OP2(__PP637753.B_E___B2_B_Actv_Bal_Tot_Grow1_Y_,=,__CN(1)))=>__ECAST(KEL.typ.nstr,__CN('1')),__T(__AND(__OP2(__PP637753.B_E___B2_B_Actv_Bal_Tot_Grow1_Y_,>,__CN(1)),__OP2(__PP637753.B_E___B2_B_Actv_Bal_Tot_Grow1_Y_,<=,__CN(9999.9999))))=>__ECAST(KEL.typ.nstr,__CN('2')),__N(KEL.typ.str));
    SELF.B_E___B2_B_Actv_Bal_Tot_Rnge_ := MAP(__PP637753.B_E___B2_B_Actv_Cnt_ = 0=>__ECAST(KEL.typ.nstr,__CN(__CC13800)),__PP637753.B_E___B2_B_Actv_Bal_Tot_ >= 0 AND __PP637753.B_E___B2_B_Actv_Bal_Tot_ <= 500=>__ECAST(KEL.typ.nstr,__CN('1')),__PP637753.B_E___B2_B_Actv_Bal_Tot_ >= 501 AND __PP637753.B_E___B2_B_Actv_Bal_Tot_ <= 1000=>__ECAST(KEL.typ.nstr,__CN('2')),__PP637753.B_E___B2_B_Actv_Bal_Tot_ >= 1001 AND __PP637753.B_E___B2_B_Actv_Bal_Tot_ <= 5000=>__ECAST(KEL.typ.nstr,__CN('3')),__PP637753.B_E___B2_B_Actv_Bal_Tot_ >= 5001 AND __PP637753.B_E___B2_B_Actv_Bal_Tot_ <= 10000=>__ECAST(KEL.typ.nstr,__CN('4')),__PP637753.B_E___B2_B_Actv_Bal_Tot_ >= 10001 AND __PP637753.B_E___B2_B_Actv_Bal_Tot_ <= 20000=>__ECAST(KEL.typ.nstr,__CN('5')),__PP637753.B_E___B2_B_Actv_Bal_Tot_ >= 20001 AND __PP637753.B_E___B2_B_Actv_Bal_Tot_ <= 40000=>__ECAST(KEL.typ.nstr,__CN('6')),__PP637753.B_E___B2_B_Actv_Bal_Tot_ >= 40001 AND __PP637753.B_E___B2_B_Actv_Bal_Tot_ <= 99999999=>__ECAST(KEL.typ.nstr,__CN('7')),__N(KEL.typ.str));
    SELF.B_E___B2_B_Actv_Carr_Bal_Avg_ := IF(__PP637753.B_E___B2_B_Actv_Carr_Cnt_ = 0,__CC13803,KEL.Routines.BoundsFold(ROUND(__PP637753.B_E___B2_B_Actv_Carr_Bal_Tot_No_Cap_ / __PP637753.B_E___B2_B_Actv_Carr_Cnt_No_Cap_),0,99999999));
    SELF.B_E___B2_B_Actv_Carr_Bal_Tot_Grow_Indx1_Y_ := MAP(__PP637753.B_E___B2_B_Actv_Carr_Cnt_ = 0=>__ECAST(KEL.typ.nstr,__CN(__CC13800)),__PP637753.B_E___B2_B_Actv_Carr_Cnt_A1_Y_ = 0=>__ECAST(KEL.typ.nstr,__CN(__CC13800)),__PP637753.B_E___B2_B_Actv_Carr_Bal_Tot_A1_Y_ = 0=>__ECAST(KEL.typ.nstr,__CN(__CC13808)),__T(__AND(__OP2(__PP637753.B_E___B2_B_Actv_Carr_Bal_Tot_Grow1_Y_,>=,__CN(0)),__OP2(__PP637753.B_E___B2_B_Actv_Carr_Bal_Tot_Grow1_Y_,<,__CN(1))))=>__ECAST(KEL.typ.nstr,__CN('0')),__T(__OP2(__PP637753.B_E___B2_B_Actv_Carr_Bal_Tot_Grow1_Y_,=,__CN(1)))=>__ECAST(KEL.typ.nstr,__CN('1')),__T(__AND(__OP2(__PP637753.B_E___B2_B_Actv_Carr_Bal_Tot_Grow1_Y_,>,__CN(1)),__OP2(__PP637753.B_E___B2_B_Actv_Carr_Bal_Tot_Grow1_Y_,<=,__CN(9999.9999))))=>__ECAST(KEL.typ.nstr,__CN('2')),__N(KEL.typ.str));
    SELF.B_E___B2_B_Actv_Carr_Bal_Tot_Pct_ := MAP(__PP637753.B_E___B2_B_Actv_Cnt_No_Cap_ = 0=>__ECAST(KEL.typ.nfloat,__CAST(KEL.typ.float,__CN(__CC13803))),__PP637753.B_E___B2_B_Actv_Carr_Cnt_ = 0=>__ECAST(KEL.typ.nfloat,__CAST(KEL.typ.float,__CN(__CC13803))),__PP637753.B_E___B2_B_Actv_Bal_Tot_ = 0=>__ECAST(KEL.typ.nfloat,__CAST(KEL.typ.float,__CN(__CC13806))),__PP637753.B_E___B2_B_Actv_Bal_Tot_ > 0=>__ECAST(KEL.typ.nfloat,__CN(__PP637753.B_E___B2_B_Actv_Carr_Bal_Tot_No_Cap_ / __PP637753.B_E___B2_B_Actv_Bal_Tot_No_Cap_ * 100)),__N(KEL.typ.float));
    SELF.B_E___B2_B_Actv_Carr_Bal_Tot_Rnge_ := MAP(__PP637753.B_E___B2_B_Actv_Carr_Cnt_ = 0=>__ECAST(KEL.typ.nstr,__CN(__CC13800)),__PP637753.B_E___B2_B_Actv_Carr_Bal_Tot_ >= 0 AND __PP637753.B_E___B2_B_Actv_Carr_Bal_Tot_ <= 500=>__ECAST(KEL.typ.nstr,__CN('1')),__PP637753.B_E___B2_B_Actv_Carr_Bal_Tot_ >= 501 AND __PP637753.B_E___B2_B_Actv_Carr_Bal_Tot_ <= 1000=>__ECAST(KEL.typ.nstr,__CN('2')),__PP637753.B_E___B2_B_Actv_Carr_Bal_Tot_ >= 1001 AND __PP637753.B_E___B2_B_Actv_Carr_Bal_Tot_ <= 5000=>__ECAST(KEL.typ.nstr,__CN('3')),__PP637753.B_E___B2_B_Actv_Carr_Bal_Tot_ >= 5001 AND __PP637753.B_E___B2_B_Actv_Carr_Bal_Tot_ <= 10000=>__ECAST(KEL.typ.nstr,__CN('4')),__PP637753.B_E___B2_B_Actv_Carr_Bal_Tot_ >= 10001 AND __PP637753.B_E___B2_B_Actv_Carr_Bal_Tot_ <= 20000=>__ECAST(KEL.typ.nstr,__CN('5')),__PP637753.B_E___B2_B_Actv_Carr_Bal_Tot_ >= 20001 AND __PP637753.B_E___B2_B_Actv_Carr_Bal_Tot_ <= 40000=>__ECAST(KEL.typ.nstr,__CN('6')),__PP637753.B_E___B2_B_Actv_Carr_Bal_Tot_ >= 40001 AND __PP637753.B_E___B2_B_Actv_Carr_Bal_Tot_ <= 99999999=>__ECAST(KEL.typ.nstr,__CN('7')),__N(KEL.typ.str));
    SELF.B_E___B2_B_Actv_Carr_Cnt_Grow1_Y_ := IF(__PP637753.B_E___B2_B_Actv_Carr_Cnt_A1_Y_ = 0,(KEL.typ.float)__CC13803,MIN(__PP637753.B_E___B2_B_Actv_Carr_Cnt_No_Cap_ / __PP637753.B_E___B2_B_Actv_Carr_Cnt_A1_Y_No_Cap_,999.9999));
    SELF.B_E___B2_B_Actv_Carr_Pct_ := IF(__PP637753.B_E___B2_B_Actv_Cnt_No_Cap_ = 0,(KEL.typ.float)__CC13803,__PP637753.B_E___B2_B_Actv_Carr_Cnt_No_Cap_ / __PP637753.B_E___B2_B_Actv_Cnt_No_Cap_ * 100);
    SELF.B_E___B2_B_Actv_Carr_Worst_Perf_Indx_ := IF(__PP637753.B_E___B2_B_Actv_Carr_Cnt_ = 0,__ECAST(KEL.typ.nstr,__CN(__CC13800)),__ECAST(KEL.typ.nstr,__ECAST(KEL.typ.nstr,__PP637753.M_A_X___Perf_Level_)));
    SELF.B_E___B2_B_Actv_Cnt_Grow1_Y_ := IF(__PP637753.B_E___B2_B_Actv_Cnt_A1_Y_ = 0,(KEL.typ.float)__CC13803,MIN(__PP637753.B_E___B2_B_Actv_Cnt_No_Cap_ / __PP637753.B_E___B2_B_Actv_Cnt_A1_Y_No_Cap_,999.9999));
    SELF.B_E___B2_B_Actv_Flt_Bal_Avg_ := IF(__PP637753.B_E___B2_B_Actv_Flt_Cnt_ = 0,__CC13803,KEL.Routines.BoundsFold(ROUND(__PP637753.B_E___B2_B_Actv_Flt_Bal_Tot_No_Cap_ / __PP637753.B_E___B2_B_Actv_Flt_Cnt_No_Cap_),0,99999999));
    SELF.B_E___B2_B_Actv_Flt_Bal_Pct_ := MAP(__PP637753.B_E___B2_B_Actv_Cnt_No_Cap_ = 0=>__ECAST(KEL.typ.nfloat,__CAST(KEL.typ.float,__CN(__CC13803))),__PP637753.B_E___B2_B_Actv_Flt_Cnt_ = 0=>__ECAST(KEL.typ.nfloat,__CAST(KEL.typ.float,__CN(__CC13803))),__PP637753.B_E___B2_B_Actv_Bal_Tot_ = 0=>__ECAST(KEL.typ.nfloat,__CAST(KEL.typ.float,__CN(__CC13806))),__PP637753.B_E___B2_B_Actv_Bal_Tot_ > 0=>__ECAST(KEL.typ.nfloat,__CN(__PP637753.B_E___B2_B_Actv_Flt_Bal_Tot_No_Cap_ / __PP637753.B_E___B2_B_Actv_Bal_Tot_No_Cap_ * 100)),__N(KEL.typ.float));
    SELF.B_E___B2_B_Actv_Flt_Bal_Tot_Grow_Indx1_Y_ := MAP(__PP637753.B_E___B2_B_Actv_Flt_Cnt_ = 0=>__ECAST(KEL.typ.nstr,__CN(__CC13800)),__PP637753.B_E___B2_B_Actv_Flt_Cnt_A1_Y_ = 0=>__ECAST(KEL.typ.nstr,__CN(__CC13800)),__PP637753.B_E___B2_B_Actv_Flt_Bal_Tot_A1_Y_ = 0=>__ECAST(KEL.typ.nstr,__CN(__CC13808)),__T(__AND(__OP2(__PP637753.B_E___B2_B_Actv_Flt_Bal_Tot_Grow1_Y_,>=,__CN(0)),__OP2(__PP637753.B_E___B2_B_Actv_Flt_Bal_Tot_Grow1_Y_,<,__CN(1))))=>__ECAST(KEL.typ.nstr,__CN('0')),__T(__OP2(__PP637753.B_E___B2_B_Actv_Flt_Bal_Tot_Grow1_Y_,=,__CN(1)))=>__ECAST(KEL.typ.nstr,__CN('1')),__T(__AND(__OP2(__PP637753.B_E___B2_B_Actv_Flt_Bal_Tot_Grow1_Y_,>,__CN(1)),__OP2(__PP637753.B_E___B2_B_Actv_Flt_Bal_Tot_Grow1_Y_,<=,__CN(9999.9999))))=>__ECAST(KEL.typ.nstr,__CN('2')),__N(KEL.typ.str));
    SELF.B_E___B2_B_Actv_Flt_Bal_Tot_Rnge_ := MAP(__PP637753.B_E___B2_B_Actv_Flt_Cnt_ = 0=>__ECAST(KEL.typ.nstr,__CN(__CC13800)),__PP637753.B_E___B2_B_Actv_Flt_Bal_Tot_ >= 0 AND __PP637753.B_E___B2_B_Actv_Flt_Bal_Tot_ <= 500=>__ECAST(KEL.typ.nstr,__CN('1')),__PP637753.B_E___B2_B_Actv_Flt_Bal_Tot_ >= 501 AND __PP637753.B_E___B2_B_Actv_Flt_Bal_Tot_ <= 1000=>__ECAST(KEL.typ.nstr,__CN('2')),__PP637753.B_E___B2_B_Actv_Flt_Bal_Tot_ >= 1001 AND __PP637753.B_E___B2_B_Actv_Flt_Bal_Tot_ <= 5000=>__ECAST(KEL.typ.nstr,__CN('3')),__PP637753.B_E___B2_B_Actv_Flt_Bal_Tot_ >= 5001 AND __PP637753.B_E___B2_B_Actv_Flt_Bal_Tot_ <= 10000=>__ECAST(KEL.typ.nstr,__CN('4')),__PP637753.B_E___B2_B_Actv_Flt_Bal_Tot_ >= 10001 AND __PP637753.B_E___B2_B_Actv_Flt_Bal_Tot_ <= 20000=>__ECAST(KEL.typ.nstr,__CN('5')),__PP637753.B_E___B2_B_Actv_Flt_Bal_Tot_ >= 20001 AND __PP637753.B_E___B2_B_Actv_Flt_Bal_Tot_ <= 40000=>__ECAST(KEL.typ.nstr,__CN('6')),__PP637753.B_E___B2_B_Actv_Flt_Bal_Tot_ >= 40001 AND __PP637753.B_E___B2_B_Actv_Flt_Bal_Tot_ <= 99999999=>__ECAST(KEL.typ.nstr,__CN('7')),__N(KEL.typ.str));
    SELF.B_E___B2_B_Actv_Flt_Cnt_Grow1_Y_ := IF(__PP637753.B_E___B2_B_Actv_Flt_Cnt_A1_Y_ = 0,(KEL.typ.float)__CC13803,MIN(__PP637753.B_E___B2_B_Actv_Flt_Cnt_No_Cap_ / __PP637753.B_E___B2_B_Actv_Flt_Cnt_A1_Y_No_Cap_,999.9999));
    SELF.B_E___B2_B_Actv_Flt_Pct_ := IF(__PP637753.B_E___B2_B_Actv_Cnt_No_Cap_ = 0,(KEL.typ.float)__CC13803,__PP637753.B_E___B2_B_Actv_Flt_Cnt_No_Cap_ / __PP637753.B_E___B2_B_Actv_Cnt_No_Cap_ * 100);
    SELF.B_E___B2_B_Actv_Flt_Worst_Perf_Indx_ := IF(__PP637753.B_E___B2_B_Actv_Flt_Cnt_ = 0,__ECAST(KEL.typ.nstr,__CN(__CC13800)),__ECAST(KEL.typ.nstr,__ECAST(KEL.typ.nstr,__PP637753.M_A_X___Perf_Level__1_)));
    SELF.B_E___B2_B_Actv_Mat_Bal_Avg_ := IF(__PP637753.B_E___B2_B_Actv_Mat_Cnt_ = 0,__CC13803,KEL.Routines.BoundsFold(ROUND(__PP637753.B_E___B2_B_Actv_Mat_Bal_Tot_No_Cap_ / __PP637753.B_E___B2_B_Actv_Mat_Cnt_No_Cap_),0,99999999));
    SELF.B_E___B2_B_Actv_Mat_Bal_Pct_ := MAP(__PP637753.B_E___B2_B_Actv_Cnt_No_Cap_ = 0=>__ECAST(KEL.typ.nfloat,__CAST(KEL.typ.float,__CN(__CC13803))),__PP637753.B_E___B2_B_Actv_Mat_Cnt_ = 0=>__ECAST(KEL.typ.nfloat,__CAST(KEL.typ.float,__CN(__CC13803))),__PP637753.B_E___B2_B_Actv_Bal_Tot_ = 0=>__ECAST(KEL.typ.nfloat,__CAST(KEL.typ.float,__CN(__CC13806))),__PP637753.B_E___B2_B_Actv_Bal_Tot_ > 0=>__ECAST(KEL.typ.nfloat,__CN(__PP637753.B_E___B2_B_Actv_Mat_Bal_Tot_No_Cap_ / __PP637753.B_E___B2_B_Actv_Bal_Tot_No_Cap_ * 100)),__N(KEL.typ.float));
    SELF.B_E___B2_B_Actv_Mat_Bal_Tot_Grow_Indx1_Y_ := MAP(__PP637753.B_E___B2_B_Actv_Mat_Cnt_ = 0=>__ECAST(KEL.typ.nstr,__CN(__CC13800)),__PP637753.B_E___B2_B_Actv_Mat_Cnt_A1_Y_ = 0=>__ECAST(KEL.typ.nstr,__CN(__CC13800)),__PP637753.B_E___B2_B_Actv_Mat_Bal_Tot_A1_Y_ = 0=>__ECAST(KEL.typ.nstr,__CN(__CC13808)),__T(__AND(__OP2(__PP637753.B_E___B2_B_Actv_Mat_Bal_Tot_Grow1_Y_,>=,__CN(0)),__OP2(__PP637753.B_E___B2_B_Actv_Mat_Bal_Tot_Grow1_Y_,<,__CN(1))))=>__ECAST(KEL.typ.nstr,__CN('0')),__T(__OP2(__PP637753.B_E___B2_B_Actv_Mat_Bal_Tot_Grow1_Y_,=,__CN(1)))=>__ECAST(KEL.typ.nstr,__CN('1')),__T(__AND(__OP2(__PP637753.B_E___B2_B_Actv_Mat_Bal_Tot_Grow1_Y_,>,__CN(1)),__OP2(__PP637753.B_E___B2_B_Actv_Mat_Bal_Tot_Grow1_Y_,<=,__CN(9999.9999))))=>__ECAST(KEL.typ.nstr,__CN('2')),__N(KEL.typ.str));
    SELF.B_E___B2_B_Actv_Mat_Bal_Tot_Rnge_ := MAP(__PP637753.B_E___B2_B_Actv_Mat_Cnt_ = 0=>__ECAST(KEL.typ.nstr,__CN(__CC13800)),__PP637753.B_E___B2_B_Actv_Mat_Bal_Tot_ >= 0 AND __PP637753.B_E___B2_B_Actv_Mat_Bal_Tot_ <= 500=>__ECAST(KEL.typ.nstr,__CN('1')),__PP637753.B_E___B2_B_Actv_Mat_Bal_Tot_ >= 501 AND __PP637753.B_E___B2_B_Actv_Mat_Bal_Tot_ <= 1000=>__ECAST(KEL.typ.nstr,__CN('2')),__PP637753.B_E___B2_B_Actv_Mat_Bal_Tot_ >= 1001 AND __PP637753.B_E___B2_B_Actv_Mat_Bal_Tot_ <= 5000=>__ECAST(KEL.typ.nstr,__CN('3')),__PP637753.B_E___B2_B_Actv_Mat_Bal_Tot_ >= 5001 AND __PP637753.B_E___B2_B_Actv_Mat_Bal_Tot_ <= 10000=>__ECAST(KEL.typ.nstr,__CN('4')),__PP637753.B_E___B2_B_Actv_Mat_Bal_Tot_ >= 10001 AND __PP637753.B_E___B2_B_Actv_Mat_Bal_Tot_ <= 20000=>__ECAST(KEL.typ.nstr,__CN('5')),__PP637753.B_E___B2_B_Actv_Mat_Bal_Tot_ >= 20001 AND __PP637753.B_E___B2_B_Actv_Mat_Bal_Tot_ <= 40000=>__ECAST(KEL.typ.nstr,__CN('6')),__PP637753.B_E___B2_B_Actv_Mat_Bal_Tot_ >= 40001 AND __PP637753.B_E___B2_B_Actv_Mat_Bal_Tot_ <= 99999999=>__ECAST(KEL.typ.nstr,__CN('7')),__N(KEL.typ.str));
    SELF.B_E___B2_B_Actv_Mat_Cnt_Grow1_Y_ := IF(__PP637753.B_E___B2_B_Actv_Mat_Cnt_A1_Y_ = 0,(KEL.typ.float)__CC13803,MIN(__PP637753.B_E___B2_B_Actv_Mat_Cnt_No_Cap_ / __PP637753.B_E___B2_B_Actv_Mat_Cnt_A1_Y_No_Cap_,999.9999));
    SELF.B_E___B2_B_Actv_Mat_Pct_ := IF(__PP637753.B_E___B2_B_Actv_Cnt_No_Cap_ = 0,(KEL.typ.float)__CC13803,__PP637753.B_E___B2_B_Actv_Mat_Cnt_No_Cap_ / __PP637753.B_E___B2_B_Actv_Cnt_No_Cap_ * 100);
    SELF.B_E___B2_B_Actv_Mat_Worst_Perf_Indx_ := IF(__PP637753.B_E___B2_B_Actv_Mat_Cnt_ = 0,__ECAST(KEL.typ.nstr,__CN(__CC13800)),__ECAST(KEL.typ.nstr,__ECAST(KEL.typ.nstr,__PP637753.M_A_X___Perf_Level__2_)));
    SELF.B_E___B2_B_Actv_Ops_Bal_Avg_ := IF(__PP637753.B_E___B2_B_Actv_Ops_Cnt_ = 0,__CC13803,KEL.Routines.BoundsFold(ROUND(__PP637753.B_E___B2_B_Actv_Ops_Bal_Tot_No_Cap_ / __PP637753.B_E___B2_B_Actv_Ops_Cnt_No_Cap_),0,99999999));
    SELF.B_E___B2_B_Actv_Ops_Bal_Pct_ := MAP(__PP637753.B_E___B2_B_Actv_Cnt_No_Cap_ = 0=>__ECAST(KEL.typ.nfloat,__CAST(KEL.typ.float,__CN(__CC13803))),__PP637753.B_E___B2_B_Actv_Ops_Cnt_ = 0=>__ECAST(KEL.typ.nfloat,__CAST(KEL.typ.float,__CN(__CC13803))),__PP637753.B_E___B2_B_Actv_Bal_Tot_ = 0=>__ECAST(KEL.typ.nfloat,__CAST(KEL.typ.float,__CN(__CC13806))),__PP637753.B_E___B2_B_Actv_Bal_Tot_ > 0=>__ECAST(KEL.typ.nfloat,__CN(__PP637753.B_E___B2_B_Actv_Ops_Bal_Tot_No_Cap_ / __PP637753.B_E___B2_B_Actv_Bal_Tot_No_Cap_ * 100)),__N(KEL.typ.float));
    SELF.B_E___B2_B_Actv_Ops_Bal_Tot_Grow_Indx1_Y_ := MAP(__PP637753.B_E___B2_B_Actv_Ops_Cnt_ = 0=>__ECAST(KEL.typ.nstr,__CN(__CC13800)),__PP637753.B_E___B2_B_Actv_Ops_Cnt_A1_Y_ = 0=>__ECAST(KEL.typ.nstr,__CN(__CC13800)),__PP637753.B_E___B2_B_Actv_Ops_Bal_Tot_A1_Y_ = 0=>__ECAST(KEL.typ.nstr,__CN(__CC13808)),__T(__AND(__OP2(__PP637753.B_E___B2_B_Actv_Ops_Bal_Tot_Grow1_Y_,>=,__CN(0)),__OP2(__PP637753.B_E___B2_B_Actv_Ops_Bal_Tot_Grow1_Y_,<,__CN(1))))=>__ECAST(KEL.typ.nstr,__CN('0')),__T(__OP2(__PP637753.B_E___B2_B_Actv_Ops_Bal_Tot_Grow1_Y_,=,__CN(1)))=>__ECAST(KEL.typ.nstr,__CN('1')),__T(__AND(__OP2(__PP637753.B_E___B2_B_Actv_Ops_Bal_Tot_Grow1_Y_,>,__CN(1)),__OP2(__PP637753.B_E___B2_B_Actv_Ops_Bal_Tot_Grow1_Y_,<=,__CN(9999.9999))))=>__ECAST(KEL.typ.nstr,__CN('2')),__N(KEL.typ.str));
    SELF.B_E___B2_B_Actv_Ops_Bal_Tot_Rnge_ := MAP(__PP637753.B_E___B2_B_Actv_Ops_Cnt_ = 0=>__ECAST(KEL.typ.nstr,__CN(__CC13800)),__PP637753.B_E___B2_B_Actv_Ops_Bal_Tot_ >= 0 AND __PP637753.B_E___B2_B_Actv_Ops_Bal_Tot_ <= 500=>__ECAST(KEL.typ.nstr,__CN('1')),__PP637753.B_E___B2_B_Actv_Ops_Bal_Tot_ >= 501 AND __PP637753.B_E___B2_B_Actv_Ops_Bal_Tot_ <= 1000=>__ECAST(KEL.typ.nstr,__CN('2')),__PP637753.B_E___B2_B_Actv_Ops_Bal_Tot_ >= 1001 AND __PP637753.B_E___B2_B_Actv_Ops_Bal_Tot_ <= 5000=>__ECAST(KEL.typ.nstr,__CN('3')),__PP637753.B_E___B2_B_Actv_Ops_Bal_Tot_ >= 5001 AND __PP637753.B_E___B2_B_Actv_Ops_Bal_Tot_ <= 10000=>__ECAST(KEL.typ.nstr,__CN('4')),__PP637753.B_E___B2_B_Actv_Ops_Bal_Tot_ >= 10001 AND __PP637753.B_E___B2_B_Actv_Ops_Bal_Tot_ <= 20000=>__ECAST(KEL.typ.nstr,__CN('5')),__PP637753.B_E___B2_B_Actv_Ops_Bal_Tot_ >= 20001 AND __PP637753.B_E___B2_B_Actv_Ops_Bal_Tot_ <= 40000=>__ECAST(KEL.typ.nstr,__CN('6')),__PP637753.B_E___B2_B_Actv_Ops_Bal_Tot_ >= 40001 AND __PP637753.B_E___B2_B_Actv_Ops_Bal_Tot_ <= 99999999=>__ECAST(KEL.typ.nstr,__CN('7')),__N(KEL.typ.str));
    SELF.B_E___B2_B_Actv_Ops_Cnt_Grow1_Y_ := IF(__PP637753.B_E___B2_B_Actv_Ops_Cnt_A1_Y_ = 0,(KEL.typ.float)__CC13803,MIN(__PP637753.B_E___B2_B_Actv_Ops_Cnt_No_Cap_ / __PP637753.B_E___B2_B_Actv_Ops_Cnt_A1_Y_No_Cap_,999.9999));
    SELF.B_E___B2_B_Actv_Ops_Pct_ := IF(__PP637753.B_E___B2_B_Actv_Cnt_No_Cap_ = 0,(KEL.typ.float)__CC13803,__PP637753.B_E___B2_B_Actv_Ops_Cnt_No_Cap_ / __PP637753.B_E___B2_B_Actv_Cnt_No_Cap_ * 100);
    SELF.B_E___B2_B_Actv_Ops_Worst_Perf_Indx_ := IF(__PP637753.B_E___B2_B_Actv_Ops_Cnt_ = 0,__ECAST(KEL.typ.nstr,__CN(__CC13800)),__ECAST(KEL.typ.nstr,__ECAST(KEL.typ.nstr,__PP637753.M_A_X___Perf_Level__3_)));
    SELF.B_E___B2_B_Actv_Oth_Bal_Avg_ := IF(__PP637753.B_E___B2_B_Actv_Oth_Cnt_ = 0,__CC13803,KEL.Routines.BoundsFold(ROUND(__PP637753.B_E___B2_B_Actv_Oth_Bal_Tot_No_Cap_ / __PP637753.B_E___B2_B_Actv_Oth_Cnt_No_Cap_),0,99999999));
    SELF.B_E___B2_B_Actv_Oth_Bal_Pct_ := MAP(__PP637753.B_E___B2_B_Actv_Cnt_No_Cap_ = 0=>__ECAST(KEL.typ.nfloat,__CAST(KEL.typ.float,__CN(__CC13803))),__PP637753.B_E___B2_B_Actv_Oth_Cnt_ = 0=>__ECAST(KEL.typ.nfloat,__CAST(KEL.typ.float,__CN(__CC13803))),__PP637753.B_E___B2_B_Actv_Bal_Tot_ = 0=>__ECAST(KEL.typ.nfloat,__CAST(KEL.typ.float,__CN(__CC13806))),__PP637753.B_E___B2_B_Actv_Bal_Tot_ > 0=>__ECAST(KEL.typ.nfloat,__CN(__PP637753.B_E___B2_B_Actv_Oth_Bal_Tot_No_Cap_ / __PP637753.B_E___B2_B_Actv_Bal_Tot_No_Cap_ * 100)),__N(KEL.typ.float));
    SELF.B_E___B2_B_Actv_Oth_Bal_Tot_Grow_Indx1_Y_ := MAP(__PP637753.B_E___B2_B_Actv_Oth_Cnt_ = 0=>__ECAST(KEL.typ.nstr,__CN(__CC13800)),__PP637753.B_E___B2_B_Actv_Oth_Cnt_A1_Y_ = 0=>__ECAST(KEL.typ.nstr,__CN(__CC13800)),__PP637753.B_E___B2_B_Actv_Oth_Bal_Tot_A1_Y_ = 0=>__ECAST(KEL.typ.nstr,__CN(__CC13808)),__T(__AND(__OP2(__PP637753.B_E___B2_B_Actv_Oth_Bal_Tot_Grow1_Y_,>=,__CN(0)),__OP2(__PP637753.B_E___B2_B_Actv_Oth_Bal_Tot_Grow1_Y_,<,__CN(1))))=>__ECAST(KEL.typ.nstr,__CN('0')),__T(__OP2(__PP637753.B_E___B2_B_Actv_Oth_Bal_Tot_Grow1_Y_,=,__CN(1)))=>__ECAST(KEL.typ.nstr,__CN('1')),__T(__AND(__OP2(__PP637753.B_E___B2_B_Actv_Oth_Bal_Tot_Grow1_Y_,>,__CN(1)),__OP2(__PP637753.B_E___B2_B_Actv_Oth_Bal_Tot_Grow1_Y_,<=,__CN(9999.9999))))=>__ECAST(KEL.typ.nstr,__CN('2')),__N(KEL.typ.str));
    SELF.B_E___B2_B_Actv_Oth_Bal_Tot_Rnge_ := MAP(__PP637753.B_E___B2_B_Actv_Oth_Cnt_ = 0=>__ECAST(KEL.typ.nstr,__CN(__CC13800)),__PP637753.B_E___B2_B_Actv_Oth_Bal_Tot_ >= 0 AND __PP637753.B_E___B2_B_Actv_Oth_Bal_Tot_ <= 500=>__ECAST(KEL.typ.nstr,__CN('1')),__PP637753.B_E___B2_B_Actv_Oth_Bal_Tot_ >= 501 AND __PP637753.B_E___B2_B_Actv_Oth_Bal_Tot_ <= 1000=>__ECAST(KEL.typ.nstr,__CN('2')),__PP637753.B_E___B2_B_Actv_Oth_Bal_Tot_ >= 1001 AND __PP637753.B_E___B2_B_Actv_Oth_Bal_Tot_ <= 5000=>__ECAST(KEL.typ.nstr,__CN('3')),__PP637753.B_E___B2_B_Actv_Oth_Bal_Tot_ >= 5001 AND __PP637753.B_E___B2_B_Actv_Oth_Bal_Tot_ <= 10000=>__ECAST(KEL.typ.nstr,__CN('4')),__PP637753.B_E___B2_B_Actv_Oth_Bal_Tot_ >= 10001 AND __PP637753.B_E___B2_B_Actv_Oth_Bal_Tot_ <= 20000=>__ECAST(KEL.typ.nstr,__CN('5')),__PP637753.B_E___B2_B_Actv_Oth_Bal_Tot_ >= 20001 AND __PP637753.B_E___B2_B_Actv_Oth_Bal_Tot_ <= 40000=>__ECAST(KEL.typ.nstr,__CN('6')),__PP637753.B_E___B2_B_Actv_Oth_Bal_Tot_ >= 40001 AND __PP637753.B_E___B2_B_Actv_Oth_Bal_Tot_ <= 99999999=>__ECAST(KEL.typ.nstr,__CN('7')),__N(KEL.typ.str));
    SELF.B_E___B2_B_Actv_Oth_Cnt_Grow1_Y_ := IF(__PP637753.B_E___B2_B_Actv_Oth_Cnt_A1_Y_ = 0,(KEL.typ.float)__CC13803,MIN(__PP637753.B_E___B2_B_Actv_Oth_Cnt_No_Cap_ / __PP637753.B_E___B2_B_Actv_Oth_Cnt_A1_Y_No_Cap_,999.9999));
    SELF.B_E___B2_B_Actv_Oth_Pct_ := IF(__PP637753.B_E___B2_B_Actv_Cnt_No_Cap_ = 0,(KEL.typ.float)__CC13803,__PP637753.B_E___B2_B_Actv_Oth_Cnt_No_Cap_ / __PP637753.B_E___B2_B_Actv_Cnt_No_Cap_ * 100);
    SELF.B_E___B2_B_Actv_Oth_Worst_Perf_Indx_ := IF(__PP637753.B_E___B2_B_Actv_Oth_Cnt_ = 0,__ECAST(KEL.typ.nstr,__CN(__CC13800)),__ECAST(KEL.typ.nstr,__ECAST(KEL.typ.nstr,__PP637753.M_A_X___Perf_Level__4_)));
    SELF.B_E___B2_B_Actv_Worst_Perf_Indx_ := IF(__PP637753.B_E___B2_B_Actv_Cnt_ = 0,__ECAST(KEL.typ.nstr,__CN(__CC13800)),__ECAST(KEL.typ.nstr,__ECAST(KEL.typ.nstr,__PP637753.M_A_X___Perf_Level__5_)));
    SELF.B_E___B2_B_Bal_Max2_Y_ := IF(__PP637753.B_E___B2_B_Cnt2_Y_ = 0,__ECAST(KEL.typ.nint,__CN(__CC13803)),__ECAST(KEL.typ.nint,__FN3(KEL.Routines.BoundsFold,__PP637753.B_E___B2_B_Bal_Max2_Y_No_Cap_,__CN(0),__CN(99999999))));
    SELF.B_E___B2_B_Bal_Max_Msnc2_Y_ := IF(__PP637753.B_E___B2_B_Cnt2_Y_ = 0,__ECAST(KEL.typ.nint,__CN(__CC13803)),__ECAST(KEL.typ.nint,__FN3(KEL.Routines.BoundsFold,__FN2(KEL.Routines.MonthsBetween,KEL.Routines.CastStringToDate(__PP637753.B_E___B2_B_Bal_Max_Dt2_Y_),__PP637753.O_N_L_Y___C_U_R_R_E_N_T___D_A_T_E_),__CN(0),__CN(24))));
    SELF.B_E___B2_B_Bal_Max_Seg_Type2_Y_ := MAP(__PP637753.B_E___B2_B_Cnt2_Y_ = 0=>__ECAST(KEL.typ.nstr,__CN(__CC13800)),__PP637753.B_E___B2_B_Bal_Max_Seg_Type2_Y_Map_Carr_ + __PP637753.B_E___B2_B_Bal_Max_Seg_Type2_Y_Map_Flt_ + __PP637753.B_E___B2_B_Bal_Max_Seg_Type2_Y_Map_Mat_ + __PP637753.B_E___B2_B_Bal_Max_Seg_Type2_Y_Map_Ops_ + __PP637753.B_E___B2_B_Bal_Max_Seg_Type2_Y_Map_Oth_ > 1=>__ECAST(KEL.typ.nstr,__CN('5')),__T(__OP2(__PP637753.B_E___B2_B_Carr_Bal_Max2_Y_No_Cap_,=,__PP637753.B_E___B2_B_Bal_Max2_Y_No_Cap_))=>__ECAST(KEL.typ.nstr,__CN('4')),__T(__OP2(__PP637753.B_E___B2_B_Flt_Bal_Max2_Y_No_Cap_,=,__PP637753.B_E___B2_B_Bal_Max2_Y_No_Cap_))=>__ECAST(KEL.typ.nstr,__CN('3')),__T(__OP2(__PP637753.B_E___B2_B_Mat_Bal_Max2_Y_No_Cap_,=,__PP637753.B_E___B2_B_Bal_Max2_Y_No_Cap_))=>__ECAST(KEL.typ.nstr,__CN('2')),__T(__OP2(__PP637753.B_E___B2_B_Ops_Bal_Max2_Y_No_Cap_,=,__PP637753.B_E___B2_B_Bal_Max2_Y_No_Cap_))=>__ECAST(KEL.typ.nstr,__CN('1')),__T(__OP2(__PP637753.B_E___B2_B_Oth_Bal_Max2_Y_No_Cap_,=,__PP637753.B_E___B2_B_Bal_Max2_Y_No_Cap_))=>__ECAST(KEL.typ.nstr,__CN('0')),__N(KEL.typ.str));
    SELF.B_E___B2_B_Bal_Vol24_Mc_ := MAP(__T(__OP2(__PP637753.B_E___B2_B_Rec_Flag_By_Mon_Sum24_Mc_,=,__CN(1)))=>__ECAST(KEL.typ.nfloat,__CAST(KEL.typ.float,__CN(__CC13806))),__PP637753.B_E___B2_B_Cnt24_Mc_ = 0=>__ECAST(KEL.typ.nfloat,__CAST(KEL.typ.float,__CN(__CC13803))),__ECAST(KEL.typ.nfloat,KEL.Routines.MinN(__OP2(__PP637753.B2b_T_L_Devation_Sample_,/,__PP637753.B2b_T_L_M_E_A_N_),__CN(2.0))));
    SELF.B_E___B2_B_Carr_Bal_Max2_Y_ := IF(__PP637753.B_E___B2_B_Carr_Cnt2_Y_ = 0,__ECAST(KEL.typ.nint,__CN(__CC13803)),__ECAST(KEL.typ.nint,__FN3(KEL.Routines.BoundsFold,__PP637753.B_E___B2_B_Carr_Bal_Max2_Y_No_Cap_,__CN(0),__CN(99999999))));
    SELF.B_E___B2_B_Carr_Bal_Max_Msnc2_Y_ := IF(__PP637753.B_E___B2_B_Carr_Cnt2_Y_ = 0,__ECAST(KEL.typ.nint,__CN(__CC13803)),__ECAST(KEL.typ.nint,__FN3(KEL.Routines.BoundsFold,__FN2(KEL.Routines.MonthsBetween,KEL.Routines.CastStringToDate(__PP637753.B_E___B2_B_Carr_Bal_Max_Dt2_Y_),__PP637753.O_N_L_Y___C_U_R_R_E_N_T___D_A_T_E__1_),__CN(0),__CN(24))));
    SELF.B_E___B2_B_Carr_Bal_Vol24_Mc_ := MAP(__T(__OP2(__PP637753.B_E___B2_B_Carr_Rec_Flag_By_Mon_Sum24_Mc_,=,__CN(1)))=>__ECAST(KEL.typ.nfloat,__CAST(KEL.typ.float,__CN(__CC13806))),__PP637753.B_E___B2_B_Carr_Cnt24_Mc_ = 0=>__ECAST(KEL.typ.nfloat,__CAST(KEL.typ.float,__CN(__CC13803))),__ECAST(KEL.typ.nfloat,KEL.Routines.MinN(__OP2(__PP637753.B2b_T_L_Devation_Sample_In_Carr_,/,__PP637753.B2b_T_L_In_Carr_M_E_A_N_),__CN(2.0))));
    SELF.B_E___B2_B_Carr_Pct2_Y_ := IF(__PP637753.B_E___B2_B_Cnt2_Y_ = 0,(KEL.typ.float)__CC13803,__PP637753.B_E___B2_B_Carr_Cnt2_Y_No_Cap_ / __PP637753.B_E___B2_B_Cnt2_Y_No_Cap_ * 100);
    SELF.B_E___B2_B_Carr_Worst_Perf_Msnc2_Y_ := MAP(__PP637753.B_E___B2_B_Carr_Cnt2_Y_ = 0=>__ECAST(KEL.typ.nint,__CN(__CC13803)),__PP637753.B_E___B2_B_Carr_Worst_Perf_Indx2_Y_ = (KEL.typ.str)0=>__ECAST(KEL.typ.nint,__CN(__CC13806)),__ECAST(KEL.typ.nint,__FN3(KEL.Routines.BoundsFold,__FN2(KEL.Routines.MonthsBetween,KEL.Routines.CastStringToDate(__PP637753.B_E___B2_B_Carr_Worst_Perf_Dt2_Y_),__PP637753.O_N_L_Y___C_U_R_R_E_N_T___D_A_T_E__2_),__CN(0),__CN(24))));
    SELF.B_E___B2_B_Flt_Bal_Max2_Y_ := IF(__PP637753.B_E___B2_B_Flt_Cnt2_Y_ = 0,__ECAST(KEL.typ.nint,__CN(__CC13803)),__ECAST(KEL.typ.nint,__FN3(KEL.Routines.BoundsFold,__PP637753.B_E___B2_B_Flt_Bal_Max2_Y_No_Cap_,__CN(0),__CN(99999999))));
    SELF.B_E___B2_B_Flt_Bal_Max_Msnc2_Y_ := IF(__PP637753.B_E___B2_B_Flt_Cnt2_Y_ = 0,__ECAST(KEL.typ.nint,__CN(__CC13803)),__ECAST(KEL.typ.nint,__FN3(KEL.Routines.BoundsFold,__FN2(KEL.Routines.MonthsBetween,KEL.Routines.CastStringToDate(__PP637753.B_E___B2_B_Flt_Bal_Max_Dt2_Y_),__PP637753.O_N_L_Y___C_U_R_R_E_N_T___D_A_T_E__3_),__CN(0),__CN(24))));
    SELF.B_E___B2_B_Flt_Bal_Vol24_Mc_ := MAP(__T(__OP2(__PP637753.B_E___B2_B_Flt_Rec_Flag_By_Mon_Sum24_Mc_,=,__CN(1)))=>__ECAST(KEL.typ.nfloat,__CAST(KEL.typ.float,__CN(__CC13806))),__PP637753.B_E___B2_B_Flt_Cnt24_Mc_ = 0=>__ECAST(KEL.typ.nfloat,__CAST(KEL.typ.float,__CN(__CC13803))),__ECAST(KEL.typ.nfloat,KEL.Routines.MinN(__OP2(__PP637753.B2b_T_L_Devation_Sample_In_Flt_,/,__PP637753.B2b_T_L_In_Flt_M_E_A_N_),__CN(2.0))));
    SELF.B_E___B2_B_Flt_Pct2_Y_ := IF(__PP637753.B_E___B2_B_Cnt2_Y_ = 0,(KEL.typ.float)__CC13803,__PP637753.B_E___B2_B_Flt_Cnt2_Y_No_Cap_ / __PP637753.B_E___B2_B_Cnt2_Y_No_Cap_ * 100);
    SELF.B_E___B2_B_Flt_Worst_Perf_Msnc2_Y_ := MAP(__PP637753.B_E___B2_B_Flt_Cnt2_Y_ = 0=>__ECAST(KEL.typ.nint,__CN(__CC13803)),__PP637753.B_E___B2_B_Flt_Worst_Perf_Indx2_Y_ = (KEL.typ.str)0=>__ECAST(KEL.typ.nint,__CN(__CC13806)),__ECAST(KEL.typ.nint,__FN3(KEL.Routines.BoundsFold,__FN2(KEL.Routines.MonthsBetween,KEL.Routines.CastStringToDate(__PP637753.B_E___B2_B_Flt_Worst_Perf_Dt2_Y_),__PP637753.O_N_L_Y___C_U_R_R_E_N_T___D_A_T_E__4_),__CN(0),__CN(24))));
    SELF.B_E___B2_B_Mat_Bal_Max2_Y_ := IF(__PP637753.B_E___B2_B_Mat_Cnt2_Y_ = 0,__ECAST(KEL.typ.nint,__CN(__CC13803)),__ECAST(KEL.typ.nint,__FN3(KEL.Routines.BoundsFold,__PP637753.B_E___B2_B_Mat_Bal_Max2_Y_No_Cap_,__CN(0),__CN(99999999))));
    SELF.B_E___B2_B_Mat_Bal_Max_Msnc2_Y_ := IF(__PP637753.B_E___B2_B_Mat_Cnt2_Y_ = 0,__ECAST(KEL.typ.nint,__CN(__CC13803)),__ECAST(KEL.typ.nint,__FN3(KEL.Routines.BoundsFold,__FN2(KEL.Routines.MonthsBetween,KEL.Routines.CastStringToDate(__PP637753.B_E___B2_B_Mat_Bal_Max_Dt2_Y_),__PP637753.O_N_L_Y___C_U_R_R_E_N_T___D_A_T_E__5_),__CN(0),__CN(24))));
    SELF.B_E___B2_B_Mat_Bal_Vol24_Mc_ := MAP(__T(__OP2(__PP637753.B_E___B2_B_Mat_Rec_Flag_By_Mon_Sum24_Mc_,=,__CN(1)))=>__ECAST(KEL.typ.nfloat,__CAST(KEL.typ.float,__CN(__CC13806))),__PP637753.B_E___B2_B_Mat_Cnt24_Mc_ = 0=>__ECAST(KEL.typ.nfloat,__CAST(KEL.typ.float,__CN(__CC13803))),__ECAST(KEL.typ.nfloat,KEL.Routines.MinN(__OP2(__PP637753.B2b_T_L_Devation_Sample_In_Mat_,/,__PP637753.B2b_T_L_In_Mat_M_E_A_N_),__CN(2.0))));
    SELF.B_E___B2_B_Mat_Pct2_Y_ := IF(__PP637753.B_E___B2_B_Cnt2_Y_ = 0,(KEL.typ.float)__CC13803,__PP637753.B_E___B2_B_Mat_Cnt2_Y_No_Cap_ / __PP637753.B_E___B2_B_Cnt2_Y_No_Cap_ * 100);
    SELF.B_E___B2_B_Mat_Worst_Perf_Msnc2_Y_ := MAP(__PP637753.B_E___B2_B_Mat_Cnt2_Y_ = 0=>__ECAST(KEL.typ.nint,__CN(__CC13803)),__PP637753.B_E___B2_B_Mat_Worst_Perf_Indx2_Y_ = (KEL.typ.str)0=>__ECAST(KEL.typ.nint,__CN(__CC13806)),__ECAST(KEL.typ.nint,__FN3(KEL.Routines.BoundsFold,__FN2(KEL.Routines.MonthsBetween,KEL.Routines.CastStringToDate(__PP637753.B_E___B2_B_Mat_Worst_Perf_Dt2_Y_),__PP637753.O_N_L_Y___C_U_R_R_E_N_T___D_A_T_E__6_),__CN(0),__CN(24))));
    SELF.B_E___B2_B_New_Msnc2_Y_ := IF(__PP637753.B_E___B2_B_Cnt2_Y_ = 0,__ECAST(KEL.typ.nint,__CN(__CC13803)),__ECAST(KEL.typ.nint,__FN3(KEL.Routines.BoundsFold,__FN2(KEL.Routines.MonthsBetween,KEL.Routines.CastStringToDate(__PP637753.B_E___B2_B_New_Dt2_Y_),__PP637753.O_N_L_Y___C_U_R_R_E_N_T___D_A_T_E__7_),__CN(0),__CN(24))));
    SELF.B_E___B2_B_Old_Msnc2_Y_ := IF(__PP637753.B_E___B2_B_Cnt2_Y_ = 0,__ECAST(KEL.typ.nint,__CN(__CC13803)),__ECAST(KEL.typ.nint,__FN3(KEL.Routines.BoundsFold,__FN2(KEL.Routines.MonthsBetween,KEL.Routines.CastStringToDate(__PP637753.B_E___B2_B_Old_Dt2_Y_),__PP637753.O_N_L_Y___C_U_R_R_E_N_T___D_A_T_E__8_),__CN(0),__CN(24))));
    SELF.B_E___B2_B_Old_Msnc_Ev_ := IF(__T(__OP2(__PP637753.B_E___B2_B_Cnt_Ev_,=,__CN(0))),__ECAST(KEL.typ.nint,__CN(__CC13803)),__ECAST(KEL.typ.nint,__FN3(KEL.Routines.BoundsFold,__FN2(KEL.Routines.MonthsBetween,KEL.Routines.CastStringToDate(__PP637753.B_E___B2_B_Old_Dt_Ev_),__PP637753.O_N_L_Y___C_U_R_R_E_N_T___D_A_T_E__9_),__CN(0),__CN(999))));
    SELF.B_E___B2_B_Ops_Bal_Max2_Y_ := IF(__PP637753.B_E___B2_B_Ops_Cnt2_Y_ = 0,__ECAST(KEL.typ.nint,__CN(__CC13803)),__ECAST(KEL.typ.nint,__FN3(KEL.Routines.BoundsFold,__PP637753.B_E___B2_B_Ops_Bal_Max2_Y_No_Cap_,__CN(0),__CN(99999999))));
    SELF.B_E___B2_B_Ops_Bal_Max_Msnc2_Y_ := IF(__PP637753.B_E___B2_B_Ops_Cnt2_Y_ = 0,__ECAST(KEL.typ.nint,__CN(__CC13803)),__ECAST(KEL.typ.nint,__FN3(KEL.Routines.BoundsFold,__FN2(KEL.Routines.MonthsBetween,KEL.Routines.CastStringToDate(__PP637753.B_E___B2_B_Ops_Bal_Max_Dt2_Y_),__PP637753.O_N_L_Y___C_U_R_R_E_N_T___D_A_T_E__10_),__CN(0),__CN(24))));
    SELF.B_E___B2_B_Ops_Bal_Vol24_Mc_ := MAP(__T(__OP2(__PP637753.B_E___B2_B_Ops_Rec_Flag_By_Mon_Sum24_Mc_,=,__CN(1)))=>__ECAST(KEL.typ.nfloat,__CAST(KEL.typ.float,__CN(__CC13806))),__PP637753.B_E___B2_B_Ops_Cnt24_Mc_ = 0=>__ECAST(KEL.typ.nfloat,__CAST(KEL.typ.float,__CN(__CC13803))),__ECAST(KEL.typ.nfloat,KEL.Routines.MinN(__OP2(__PP637753.B2b_T_L_Devation_Sample_In_Ops_,/,__PP637753.B2b_T_L_In_Ops_M_E_A_N_),__CN(2.0))));
    SELF.B_E___B2_B_Ops_Pct2_Y_ := IF(__PP637753.B_E___B2_B_Cnt2_Y_ = 0,(KEL.typ.float)__CC13803,__PP637753.B_E___B2_B_Ops_Cnt2_Y_No_Cap_ / __PP637753.B_E___B2_B_Cnt2_Y_No_Cap_ * 100);
    SELF.B_E___B2_B_Ops_Worst_Perf_Msnc2_Y_ := MAP(__PP637753.B_E___B2_B_Ops_Cnt2_Y_ = 0=>__ECAST(KEL.typ.nint,__CN(__CC13803)),__PP637753.B_E___B2_B_Ops_Worst_Perf_Indx2_Y_ = (KEL.typ.str)0=>__ECAST(KEL.typ.nint,__CN(__CC13806)),__ECAST(KEL.typ.nint,__FN3(KEL.Routines.BoundsFold,__FN2(KEL.Routines.MonthsBetween,KEL.Routines.CastStringToDate(__PP637753.B_E___B2_B_Ops_Worst_Perf_Dt2_Y_),__PP637753.O_N_L_Y___C_U_R_R_E_N_T___D_A_T_E__11_),__CN(0),__CN(24))));
    SELF.B_E___B2_B_Oth_Bal_Max2_Y_ := IF(__PP637753.B_E___B2_B_Oth_Cnt2_Y_ = 0,__ECAST(KEL.typ.nint,__CN(__CC13803)),__ECAST(KEL.typ.nint,__FN3(KEL.Routines.BoundsFold,__PP637753.B_E___B2_B_Oth_Bal_Max2_Y_No_Cap_,__CN(0),__CN(99999999))));
    SELF.B_E___B2_B_Oth_Bal_Max_Msnc2_Y_ := IF(__PP637753.B_E___B2_B_Oth_Cnt2_Y_ = 0,__ECAST(KEL.typ.nint,__CN(__CC13803)),__ECAST(KEL.typ.nint,__FN3(KEL.Routines.BoundsFold,__FN2(KEL.Routines.MonthsBetween,KEL.Routines.CastStringToDate(__PP637753.B_E___B2_B_Oth_Bal_Max_Dt2_Y_),__PP637753.O_N_L_Y___C_U_R_R_E_N_T___D_A_T_E__12_),__CN(0),__CN(24))));
    SELF.B_E___B2_B_Oth_Bal_Vol24_Mc_ := MAP(__T(__OP2(__PP637753.B_E___B2_B_Oth_Rec_Flag_By_Mon_Sum24_Mc_,=,__CN(1)))=>__ECAST(KEL.typ.nfloat,__CAST(KEL.typ.float,__CN(__CC13806))),__PP637753.B_E___B2_B_Oth_Cnt24_Mc_ = 0=>__ECAST(KEL.typ.nfloat,__CAST(KEL.typ.float,__CN(__CC13803))),__ECAST(KEL.typ.nfloat,KEL.Routines.MinN(__OP2(__PP637753.B2b_T_L_Devation_Sample_In_Oth_,/,__PP637753.B2b_T_L_In_Oth_M_E_A_N_),__CN(2.0))));
    SELF.B_E___B2_B_Oth_Pct2_Y_ := IF(__PP637753.B_E___B2_B_Cnt2_Y_ = 0,(KEL.typ.float)__CC13803,__PP637753.B_E___B2_B_Oth_Cnt2_Y_No_Cap_ / __PP637753.B_E___B2_B_Cnt2_Y_No_Cap_ * 100);
    SELF.B_E___B2_B_Oth_Worst_Perf_Msnc2_Y_ := MAP(__PP637753.B_E___B2_B_Oth_Cnt2_Y_ = 0=>__ECAST(KEL.typ.nint,__CN(__CC13803)),__PP637753.B_E___B2_B_Oth_Worst_Perf_Indx2_Y_ = (KEL.typ.str)0=>__ECAST(KEL.typ.nint,__CN(__CC13806)),__ECAST(KEL.typ.nint,__FN3(KEL.Routines.BoundsFold,__FN2(KEL.Routines.MonthsBetween,KEL.Routines.CastStringToDate(__PP637753.B_E___B2_B_Oth_Worst_Perf_Dt2_Y_),__PP637753.O_N_L_Y___C_U_R_R_E_N_T___D_A_T_E__13_),__CN(0),__CN(24))));
    SELF.B_E___B2_B_Worst_Perf_Msnc2_Y_ := MAP(__PP637753.B_E___B2_B_Cnt2_Y_ = 0=>__ECAST(KEL.typ.nint,__CN(__CC13803)),__PP637753.B_E___B2_B_Worst_Perf_Indx2_Y_ = (KEL.typ.str)0=>__ECAST(KEL.typ.nint,__CN(__CC13806)),__ECAST(KEL.typ.nint,__FN3(KEL.Routines.BoundsFold,__FN2(KEL.Routines.MonthsBetween,KEL.Routines.CastStringToDate(__PP637753.B_E___B2_B_Worst_Perf_Dt2_Y_),__PP637753.O_N_L_Y___C_U_R_R_E_N_T___D_A_T_E__14_),__CN(0),__CN(24))));
    __BS639955 := __T(__PP637753.Data_Sources_);
    SELF.B___Lex_I_D_Legal_Seen_Flag_ := IF(EXISTS(__BS639955(__T(__T(__PP637753.Data_Sources_).Header_Hit_Flag_))),'1','0');
    SELF := __PP637753;
  END;
  EXPORT __ENH_Business_Sele := PROJECT(__EE637752,__ND637757__Project(LEFT));
END;
