export get_ca_eldorado(string pInput) := 

map(
pInput = 'ABD ASMT DIS'       =>        	'ABANDONMENT ASMT DIST                  '   , 
pInput = 'ABD ESMT'       =>        	'ABANDONMENT EASMENT                    '       , 
pInput = 'ABD HMTSD'       =>        	'ABANDONMENT HOMESTEAD                  '       , 
pInput = 'ABD MINE CLM'       =>        	'ABANDONMENT MINING CLAIM LOCATION      '   , 
pInput = 'ABD MISC'       =>        	'ABANDONMENT                            '       , 
pInput = 'ABD RD MAINT'       =>        	'ABANDONMENT ROAD MAINT                 '   , 
pInput = 'ABD ROAD'       =>        	'ABANDONMENT ROAD                       '       , 
pInput = 'ABSTR AGR'       =>        	'ABSTRACT AGREE                         '       , 
pInput = 'ABSTR JUDG'       =>        	'ABSTRACT OF JUDGEMENT                  '     , 
pInput = 'ABSTR MISC'       =>        	'ABSTRACT MISC                          '     , 
pInput = 'ABSTR SUP'       =>        	'ABSTRACT OF SUPPORT JUDGEMENT          '       , 
pInput = 'ABSTR TR AGR'       =>        	'ABSTRACT TR AGR                        '   , 
pInput = 'ACCEPT APPT'       =>        	'ACCEPTANCE APPOINTMENT                 '     , 
pInput = 'ACK MISC'       =>        	'ACKNOWLEDGMENT MISC                    '       , 
pInput = 'AFF BIRTH'       =>        	'AFFIDAVIT BIRTH                        '       , 
pInput = 'AFF D LF EST'       =>        	'AFFIDAVIT DEATH LF EST                 '   , 
pInput = 'AFF D SPSE'       =>        	'AFFIDAVIT DEATH SPOUSE                 '     , 
pInput = 'AFF DEATH TR'       =>        	'AFFIDAVIT DEATH TR                     '   , 
pInput = 'AFF DJT'       =>        	'AFFIDAVIT OF DEATH OF JOINT TENANT     '         , 
pInput = 'AFF IDENT'       =>        	'AFFIDAVIT IDENTITY                     '       , 
pInput = 'AFF MISC'       =>        	'AFFIDAVIT MISC                         '       , 
pInput = 'AFF PUB'       =>        	'AFFIDAVIT PUBLICATION                  '         , 
pInput = 'AFF REAL R P'       =>        	'AFFIDAVIT RE R P SMALL VALUE           '   , 
pInput = 'AFF TERM INT'       =>        	'AFFIDAVIT TERM DECD INT R P            '   , 
pInput = 'AFF TERM JT'       =>        	'AFFIDAVIT TERM JT TEN                  '     , 
pInput = 'AFF TERM L E'       =>        	'AFFIDAVIT TERM LF EST HMSTD COMM PROP  '   , 
pInput = 'AGR & ESMT'       =>        	'AGREEMENT COVENANTS RESTR & ESMT       '     , 
pInput = 'AGR & ESMT'       =>        	'AGREEMENT & GRANT ESMT                 '     , 
pInput = 'AGR & LIEN'       =>        	'GRANT AGREEMENT & LIEN                 '     , 
pInput = 'AGR & MTG'       =>        	'AGREEMENT & CHATL MTG                  '       , 
pInput = 'AGR & WAIVER'       =>        	'AGREEMENT & WAIVER                     '   , 
pInput = 'AGR AM TR D'       =>        	'AGREEMENT AM D T                       '     , 
pInput = 'AGR BNDY ADJ'       =>        	'AGREEMENT BNDY LINE ADJUST             '   , 
pInput = 'AGR CAC LSE'       =>        	'AGREEMENT CAC LEASE                    '     , 
pInput = 'AGR CAC TR D'       =>        	'AGREEMENT CAC D T                      '   , 
pInput = 'AGR COM PROP'       =>        	'AGREEMENT CONCERN COMM PROP            '   , 
pInput = 'AGR CONVEY'       =>        	'AGREEMENT CONVEY INT R P               '     , 
pInput = 'AGR COR RECO'       =>        	'AGREEMENT COR RECORD & REINSTATE D T   '   , 
pInput = 'AGR DEDICATI'       =>        	'AGREEMENT DEDICATION PARKS             '   , 
pInput = 'AGR DSLN PTN'       =>        	'AGREEMENT DSLN PTN                     '   , 
pInput = 'AGR FIRE&WTR'       =>        	'AGREEMENT FIRE HYDRANT WTR & SEWER     '   , 
pInput = 'AGR INSTALL'       =>        	'AGREEMENT INSTALL                      '     , 
pInput = 'AGR LEASE'       =>        	'AGREEMENT LEASE                        '       , 
pInput = 'AGR LIQ JV'       =>        	'AGREEMENT LIQUIDATE JT VEN AGR         '     , 
pInput = 'AGR METER SZ'       =>        	'AGREEMENT METER SIZE                   '   , 
pInput = 'AGR MOD TR D'       =>        	'AGREEMENT MOD D T                      '   , 
pInput = 'AGR NOT SELL'       =>        	'AGREEMENT NO SELL OR ENCUMBER R P      '   , 
pInput = 'AGR PAY FEE'       =>        	'AGREEMENT TO PAY FEE                   '     , 
pInput = 'AGR REIMBURS'       =>        	'AGREEMENT REIMBURSEMENT                '   , 
pInput = 'AGR RW'       =>        	'AGREEMENT MAINTAIN RW                  '         , 
pInput = 'AGR SERV'       =>        	'AGREEMENT SERVICE                      '       , 
pInput = 'AGR SUBOR LN'       =>        	'AGREEMENT SUBOR LIEN POSTPONEMENT TAX  '   , 
pInput = 'AGR TERM LSE'       =>        	'AGREEMENT TERM LEASE MUT CONSENT       '   , 
pInput = 'AGR TERM RST'       =>        	'AGREEMENT TERM RESTRICTIONS            '   , 
pInput = 'AGR TRN R P'       =>        	'AGREEMENT TRN CONTROL POSSESSION ST R P'     , 
pInput = 'AGR WTR SERV'       =>        	'AGREEMENT WATER SERV                   '   , 
pInput = 'AGR&DEED RET'       =>        	'AGREEMENT & DEED RESTR REGARD RETIRE   '   , 
pInput = 'AGREE'       =>        	'AGREEMENT                              '           , 
pInput = 'AGREE SALE'       =>        	'AGREEMENT SALE                         '     , 
pInput = 'AM & RELINQ'       =>        	'AMENDED MINING CLAIM RELINQ POR        '     , 
pInput = 'AM ABSTR JUD'       =>        	'AMENDED ABSTR JUDG                     '   , 
pInput = 'AM AGR LAND'       =>        	'AMENDED AGR LAND USE INCOMPATIBLE FOREST'    , 
pInput = 'AM APPT REF'       =>        	'AMENDED FIND & CO APPT SPECIAL REF     '     , 
pInput = 'AM CERT LLC'       =>        	'Limited Liability Company Certificate of Amend',
pInput = 'AM DEV AGR'       =>        	'AMENDED & RESTATED DEV AGR             '     , 
pInput = 'AM LTD PTN'       =>        	'AMENDED CERT LTD PTN                   '     , 
pInput = 'AM MITIGAT'       =>        	'AMENDED MITIGATION AGR                 '     , 
pInput = 'AM TR D'       =>        	'AMENDMENT TR D                         '         , 
pInput = 'ANNEX'       =>        	'ANNEXATION                             '           , 
pInput = 'ANNEX AGR'       =>        	'ANNEXATION AGR                         '       , 
pInput = 'ANNEX FEE AG'       =>        	'ANNEXATION FEE AGR                     '   , 
pInput = 'ANSWER'       =>        	'ANSWER                                 '         , 
pInput = 'APPL AGR SER'       =>        	'APPLICATION & AGR WTR SERV EID         '   , 
pInput = 'APPL ETC'       =>        	'APPLICATION etc.                       '       , 
pInput = 'APPL LLC'       =>        	'APPLICATION FOR LIMITED LIABILITY CO   '       , 
pInput = 'APPL LTD PTN'       =>        	'APPLICATION REGISTRATION FOREIGN LTD PTN'  , 
pInput = 'APPT RECEIVE'       =>        	'APPOINTMENT RECEIVER                   '   , 
pInput = 'APPT SUC TR'       =>        	'APPOINTMENT SUC TR                     '     , 
pInput = 'ART MERGER'       =>        	'ARTICLES MERGER                        '     , 
pInput = 'ARTICLES'       =>        	'ARTICLES etc.                          '       , 
pInput = 'ASGN'       =>        	'ASSIGNMENT                             '           , 
pInput = 'ASGN & AGR'       =>        	'ASSIGNMENT & AGR                       '     , 
pInput = 'ASGN AGR SLE'       =>        	'ASSIGNMENT AGR SALE                    '   , 
pInput = 'ASGN CHATL M'       =>        	'ASSIGNMENT CHATTEL MTG                 '   , 
pInput = 'ASGN CONTR'       =>        	'ASSIGNMENT CONTR SALE R E              '     , 
pInput = 'ASGN INT'       =>        	'ASSIGNMENT INTEREST                    '       , 
pInput = 'ASGN JUDG'       =>        	'ASSIGNMENT JUDG                        '       , 
pInput = 'ASGN LEASE'       =>        	'ASSIGNMENT LEASE                       '     , 
pInput = 'ASGN LIEN'       =>        	'ASSIGNMENT LIEN                        '       , 
pInput = 'ASGN MTG'       =>        	'ASSIGNMENT MORTGAGE                    '       , 
pInput = 'ASGN OPTION'       =>        	'ASSIGNMENT OPTION AGR                  '     , 
pInput = 'ASGN RENTS'       =>        	'ASSIGNMENT OF RENTS                    '     , 
pInput = 'ASGN SEC AGR'       =>        	'ASSIGNMENT SEC AGR                     '   , 
pInput = 'ASGN TR D'       =>        	'ASSIGNMENT DEED OF TRUST               '       , 
pInput = 'ASGN&ASSUMP'       =>        	'ASSIGNMENT OF ASSUMPTION               '     , 
pInput = 'ASMT MAP'       =>        	'ASSESSMENT MAP                         '       , 
pInput = 'ASSIST BOND'       =>        	'ASSIST BOND                            '     , 
pInput = 'ASSUMP & REL'       =>        	'ASSUMPTION & REL AGR                   '   , 
pInput = 'ASSUMP AGR'       =>        	'AGREEMENT ASSUMP & MOD PROM NOTE & D T '     , 
pInput = 'ASSUMP AGR'       =>        	'ASSUMPTION AGR                         '     , 
pInput = 'ASSUMP TR D'       =>        	'ASSUMPTION D T                         '     , 
pInput = 'ATTORN AGR'       =>        	'ATTORNMENT AGREEMENT                   '     , 
pInput = 'AUTHORIZE'       =>        	'OWNER AUTHORIZATION                    '       , 
pInput = 'BAPTISM'       =>        	'BAPTISM                                '         , 
pInput = 'BENE CERT'       =>        	'BENEFICIARY CERT                       '       , 
pInput = 'BILL OF SALE'       =>        	'BILL OF SALE                           '   , 
pInput = 'BIRTH'       =>        	'BIRTH COPY                             '           , 
pInput = 'BNDRY LN ADJ'       =>        	'BOUNDRY LINE ADJ DEED                  '   , 
pInput = 'BOND LOST TRD'       =>       	'Bond for Lost Trust Deed Note          '   , 
pInput = 'BOND RECON'       =>        	'BOND LOST TR D & OR MISSING BENE       '     , 
pInput = 'BOND REL LN'       =>        	'BOND REL MECH LIEN                     '     , 
pInput = 'BY LAWS'       =>        	'BY LAWS                                '         , 
pInput = 'CAC AGR SALE'       =>        	'CANCELLATION AGR SALE                  '   , 
pInput = 'CAC ASMT LN'       =>        	'CANCELLATION ASMT LIEN                 '     , 
pInput = 'CAC DEED'       =>        	'CANCELLATION TRANSFER DEED             '       , 
pInput = 'CAC ETC'       =>        	'Cancellation etc.                      '         , 
pInput = 'CAC LEASE'       =>        	'CANCELLATION LEASE                     '       , 
pInput = 'CAC LTD PTN'       =>        	'CANCELLATION LTD PTN                   '     , 
pInput = 'CAC NT ASMT'       =>        	'CANCELATION NT ASMT LIEN               '     , 
pInput = 'CAC NT DEF'       =>        	'CANCELLATION NOTICE OF DEFAULT         '     , 
pInput = 'CAC NT TAX D'       =>        	'CANCELLATION NT TAX DEFAULT PROP       '   , 
pInput = 'CAC PAR RECO'       =>        	'AGREEMENT CAC PAR RECON                '   , 
pInput = 'CAC PWR ATTY'       =>        	'CANCELLATION PWR ATTY                  '   , 
pInput = 'CAC RECON'       =>        	'AGREEMENT CAC RECON                    '       , 
pInput = 'CAC RECON'       =>        	'CANCELLATION RECON                     '       , 
pInput = 'CAC REL EQUI'       =>        	'CANCELLATION REL EQUITY                '   , 
pInput = 'CAC REQ NT'       =>        	'CANCELLATION REQ NT                    '     , 
pInput = 'CAC RESTR'       =>        	'CANCELLATION RESTR                     '       , 
pInput = 'CAC TAX DEED'       =>        	'CANCELLATION TAX DEED                  '   , 
pInput = 'CAC TSTEE SL'       =>        	'CANCELLATION TSTEE SALE                '   , 
pInput = 'CEMETERY MAP'       =>        	'CEMETERY MAP                           '   , 
pInput = 'CERT & AGR'       =>        	'HAZARDOUS SUBSTANCES CERTIFICATE & INDMN'    , 
pInput = 'CERT ACCEPT'       =>        	'CERTIFICATE ACCEPT & WAIVER            '     , 
pInput = 'CERT ATT R P'       =>        	'CERTIFICATE ATTACH R P                 '   , 
pInput = 'CERT AUTH'       =>        	'Certificate of Authority               '       , 
pInput = 'CERT CAC AGR'       =>        	'CERTIFICATE CAC AGR PRESERVE           '   , 
pInput = 'CERT CAC LN'       =>        	'CERTIFICATE CAC LIEN                   '     , 
pInput = 'CERT COMPL'       =>        	'CERTIFICATE COMPL                      '     , 
pInput = 'CERT CONSOLI'       =>        	'CERTIFICATE CONSOLIDATION              '   , 
pInput = 'CERT COR'       =>        	'CERTIFICATE OF CORRECTION              '       , 
pInput = 'CERT COR D'       =>        	'CERTIFICATE COR DEED                   '     , 
pInput = 'CERT DELINQ'       =>        	'CERTIFICATE OF DELINQUENCY             '     , 
pInput = 'CERT DISCHG'       =>        	'CERTIFICATE DISCHG LIEN                '     , 
pInput = 'CERT EDUCATI'       =>        	'CERTIFICATE EDUCATION                  '   , 
pInput = 'CERT INH TAX'       =>        	'CERTIFICATE INH TAX                    '   , 
pInput = 'CERT INT R P'       =>        	'CERTIFICATE INT R P                    '   , 
pInput = 'CERT JT VEN'       =>        	'CERTIFICATE JT VEN                     '     , 
pInput = 'CERT JUDG DE'       =>        	'CERT JUDG DEBTOR                       '   , 
pInput = 'CERT LTD PTN'       =>        	'CERTIFICATE LIMITED PARTNERSHIP        '   , 
pInput = 'CERT MERGE'       =>        	'CERTIFICATE MERGE                      '     , 
pInput = 'CERT NON ATT'       =>        	'CERTIFICATE NON ATTACH FED TAX LIEN    '   , 
pInput = 'CERT OCCUPCY'       =>        	'CERTIFICATE OF OCCUPANCY               '   , 
pInput = 'CERT ORG'       =>        	'CERTIFICATE ORG                        '       , 
pInput = 'CERT PAR PAY'       =>        	'JUDGEMENT CRED CERT PAR PAYMENT        '   , 
pInput = 'CERT POST NT'       =>        	'CERTIFICATE POST NT ABATE NUISANCE     '   , 
pInput = 'CERT REDEMP'       =>        	'CERTIFICATE REDEMPTION STREET IMP BOND '     , 
pInput = 'CERT REDEMP'       =>        	'CERTIFICATE REDEMPTION                 '     , 
pInput = 'CERT REL'       =>        	'CERTIFICATE REL                        '       , 
pInput = 'CERT RELIEN'       =>        	'CERTIFICATE DELINQUENCY RELIEN         '     , 
pInput = 'CERT SALE'       =>        	'CERTIFICATE SALE                       '       , 
pInput = 'CERT SLE PRO'       =>        	'CERTIFICATE SALE PERSONAL PROP         '   , 
pInput = 'CERT SLE SEI'       =>        	'CERTIFICATE SALE SEIZED PROP           '   , 
pInput = 'CERT SUBOR L'       =>        	'CERTIFICATE SUBOR LIEN FED TAX         '   , 
pInput = 'CERT TRUST'       =>        	'CERTIFICATE TRUST                      '     , 
pInput = 'CERT TRUSTEE'       =>        	'CERTIFICATION TRUSTEE                  '   , 
pInput = 'CERTIFICATE'       =>        	'CERTIFICATE                            '     , 
pInput = 'CHATL MTG'       =>        	'CHATTEL MTG                            '       , 
pInput = 'COL DEED'       =>        	'COLLECTORS DEED                        '       , 
pInput = 'COMM PROP AG'       =>        	'COMMUNITY PROP AGR                     '   , 
pInput = 'COMM PROP OR'       =>        	'COMMUNIITY PROPERTY ORDER              '   , 
pInput = 'COMPLIANCE'       =>        	'COMPLIANCE                             '     , 
pInput = 'COND COMPL'       =>        	'CERTIFICATE COMPLIANCE CONDITIONAL     '     , 
pInput = 'COND WAIVER'       =>        	'CONDITIONAL WAIVER                     '     , 
pInput = 'CONSENT'       =>        	'CONSENT                                '         , 
pInput = 'CONSENT AGR'       =>        	'CONSENT COMMON USE AGR                 '     , 
pInput = 'CONSENT ASGN'       =>        	'CONSENT ASGN                           '   , 
pInput = 'CONSENT ESMT'       =>        	'CONSENT EASEMENT                       '   , 
pInput = 'CONSENT MOD'       =>        	'CONSENT MOD                            '     , 
pInput = 'CONSENT REM'       =>        	'CONSENT TO REMOVAL OF PERSONAL PROPERTY'     , 
pInput = 'CONSENT REST'       =>        	'CONSENT RESTR                          '   , 
pInput = 'CONSENT SUBO'       =>        	'CONSENT SUBOR                          '   , 
pInput = 'CONSENT TERM'       =>        	'CONSENT TERM AGR                       '   , 
pInput = 'CONSENT TRN'       =>        	'CONSENT TRN                            '     , 
pInput = 'CONSENT WAIV'       =>        	'CONSENT & WAIVER BY OWNER,LANDLORD&MTGEE',
pInput = 'CONSTR REPOR'       =>        	'CONSTRUCTION COMPL REPORT              '   , 
pInput = 'CONSTR TR D'       =>        	'CONSTRUCTION DEED OF TRUST             '     , 
pInput = 'CONTR & ESMT'       =>        	'CONTRACT & EASEMENT                    '   , 
pInput = 'CONTR & ESMT'       =>        	'CONTRACT & ESMT                        '   , 
pInput = 'CONTR BOND'       =>        	'BOND CONTRACTORS                       '     , 
pInput = 'CONTRACT'       =>        	'CONTRACT                               '       , 
pInput = 'COURT ORDER'       =>        	'COURT ORDER                            '     , 
pInput = 'COVENANT ETC'       =>        	'COVENANT etc.                          '   , 
pInput = 'COVNT RUN LND'       =>       	'Covenant Running with the Land         '   , 
pInput = 'CR PETITION'       =>        	'INVOLUNTARY CASE CRED PETITION         '     , 
pInput = 'DEBT MOTION'       =>        	'DEBTORS MOTION PRELIM INJUNCTION       '     , 
pInput = 'DEBT PETITIO'       =>        	'DEBTORS PETITION                       '   , 
pInput = 'DECL'       =>        	'DECLARATION                            '           , 
pInput = 'DECL & AGR T'       =>        	'DECLARATION & AGR TRUST                '   , 
pInput = 'DECL ABD MIN'       =>        	'DECLARATION ABD MINING CLAIM           '   , 
pInput = 'DECL ANNEX'       =>        	'DECLARATION ANNEX                      '     , 
pInput = 'DECL COMM PR'       =>        	'DECLARATION COMM PROP                  '   , 
pInput = 'DECL DEATH'       =>        	'DECLARATION DEATH                      '     , 
pInput = 'DECL DJT'       =>        	'DECLARATION DEATH JT TEN               '       , 
pInput = 'DECL HMSTD'       =>        	'DECLARATION HOMESTEAD                  '     , 
pInput = 'DECL OR & NT'       =>        	'DECLARATION ORDER & NT ASGN            '   , 
pInput = 'DECL RESTR'       =>        	'DECLARATION RESTRICTIONS               '     , 
pInput = 'DECR'       =>        	'DECREES                                '           , 
pInput = 'DECR CHG NAM'       =>        	'DECREE CHANGING NAME                   '   , 
pInput = 'DECR DEATH'       =>        	'DECREE DEATH etc.                      '     , 
pInput = 'DECR PAR DIS'       =>        	'DECREE APPROVE ACCT & PETITION PAR DISTR'  , 
pInput = 'DECR QT TL'       =>        	'DECREE QUIETING TITLE                  '     , 
pInput = 'DEED'       =>        	'GRANT DEED                             '           , 
pInput = 'DEED RESTR'       =>        	'DEED RESTR                             '     , 
pInput = 'DEL CERT BIR'       =>        	'DELAYED CERT BIRTH                     '   , 
pInput = 'DESIGN LIEN'       =>        	'DISIGN PROFESSIONALS LIEN              '     , 
pInput = 'DEV AGR'       =>        	'DEVELOPMENT AGR                        '         , 
pInput = 'DISCHARGE'       =>        	'DISCHARGE                              '       , 
pInput = 'DISCHG DEBT'       =>        	'DISCHARGE OF DEBTOR                    '     , 
pInput = 'DISCHG LIEN'       =>        	'CERTIFICATE DISCHG PROP FED TAX LIEN   '     , 
pInput = 'DISCHG MTG'       =>        	'DISCHARGE MORTGAGE                     '     , 
pInput = 'DISCLAIMER'       =>        	'DISCLAIMER                             '     , 
pInput = 'DSLN JT VEN'       =>        	'DISSOLUTION JT VEN                     '     , 
pInput = 'DSLN PTN'       =>        	'DISSOLUTION PTN                        '       , 
pInput = 'DSML ADVERSA'       =>        	'DISMISSAL ADVERSARY PROCEEDING         '   , 
pInput = 'ESMT'       =>        	'EASEMENT                               '           , 
pInput = 'ESMT HOLD AG'       =>        	'EASEMENT & HOLD HARM AGR               '   , 
pInput = 'ESTOPPEL CER'       =>        	'ESTOPPEL CERT                          '   , 
pInput = 'EX PARTE APP'       =>        	'EX PARTE APPL OR CONFIRM SALE R P      '   , 
pInput = 'EX PARTE ETC'       =>        	'EX PARTE etc.                          '   , 
pInput = 'EX PARTE OR'       =>        	'EX PARTE ORDER APPT RECIEVER           '     , 
pInput = 'EX PARTE RL'       =>        	'EL PARTE REL & EXPUNGE LIS PEN         '     , 
pInput = 'EXONERAT ETC'       =>        	'Exoneration of Release of Lien Bond etc'  , 
pInput = 'EXPUNG JUDGE'       =>        	'EXPUNGEMENT ABSTRACT JUDGEMENT         '   , 
pInput = 'EXPUNGE L P'       =>        	'EXPUNGEMENT LIS PEN                    '     , 
pInput = 'EXPUNGE ZONE'       =>        	'EXPUNGEMENT NT ZONING VIOLATION        '   , 
pInput = 'EXT AGR'       =>        	'EXTENSION AGREEMENT                    '         , 
pInput = 'EXT CR & NT'       =>        	'EXTENSION CREDIT & NOTICE              '     , 
pInput = 'EXT LIEN'       =>        	'EXTENSION LIEN (MECHANICS LIEN)        '       , 
pInput = 'EXT OPTION'       =>        	'EXTENSION OPTION                       '     , 
pInput = 'EXT PWR ATTY'       =>        	'EXTENSION POWER ATTORNEY               '   , 
pInput = 'EXT ST LIEN'       =>        	'EXTENSION STATE LIEN                   '     , 
pInput = 'FED TAX LIEN'       =>        	'TAX LIEN (IRS)                         '   , 
pInput = 'FICT CHATL M'       =>        	'FICTITIOUS CHATL MORTGAGE              '   , 
pInput = 'FICT CN TR D'       =>        	'FICTITIOUS CONSTRUCTION TRUST DEED     '   , 
pInput = 'FICT TR D'       =>        	'FICTITIOUS TRUST DEED                  '       , 
pInput = 'FIN CONDEMN'       =>        	'FINAL JUDGEMENT CONDEMNATION           '     , 
pInput = 'FIN JUDG SEP'       =>        	'FINAL JUDGEMENT LEGAL SEPERATION       '   , 
pInput = 'FIN OR CONDM'       =>        	'FINAL ORDER CONDEMNATION               '   , 
pInput = 'FIN STATE'       =>        	'FINANCE STATEMENT                      '       , 
pInput = 'FIN STIP JDG'       =>        	'FINAL STIPULATION & JUDGEMENT          '   , 
pInput = 'FINAL DISTR'       =>        	'FINAL DISTRIBUTION                     '     , 
pInput = 'FINAL DSLN'       =>        	'FINAL DISSOLUTION                      '     , 
pInput = 'FINAL JUDG'       =>        	'FINAL JUDGEMENT                        '     , 
pInput = 'FORECLSE DEE'       =>        	'FORECLSE DEED                          '   , 
pInput = 'GRANT & AGR'       =>        	'GRANT & AGREEMENT                      '     , 
pInput = 'HOLD HARM AG'       =>        	'HOLD HARMLESS AGR                      '   , 
pInput = 'HOSP LIEN'       =>        	'HOSPITAL LIEN                          '       , 
pInput = 'INDEM AGR'       =>        	'INDEMNITY AGREEMENT                    '       , 
pInput = 'INSTRUCT REL'       =>        	'INSTRUCTION RELEASE PROPERTY           '   , 
pInput = 'INTELOC JUDG'       =>        	'INTERLOCUTORY JUDGEMENT                '   , 
pInput = 'INTERLC DECR'       =>        	'INTERLOCUTORY DECREE FORECLOSURE       '   , 
pInput = 'INTERLOC DIV'       =>        	'INTERLOCUTORY DIVORCE                  '   , 
pInput = 'INTERLOC DSL'       =>        	'INTERLOCATORY DISSOLUTION              '   , 
pInput = 'JOINT AGR'       =>        	'JOINT OWNERSHIP OR USE AGREEMENT       '       , 
pInput = 'JT VEN AGR'       =>        	'JOINT VENTURE AGREE                    '     , 
pInput = 'JUDG'       =>        	'JUDGEMENT                              '           , 
pInput = 'JUDG & DECR'       =>        	'JUDGEMENT & DECREE                     '     , 
pInput = 'JUDG & ORDER'       =>        	'JUDGEMENT & ORDER                      '   , 
pInput = 'JUDG CONDEMN'       =>        	'JUDGEMENT CONDEMNATION                 '   , 
pInput = 'JUDG DEATH'       =>        	'JUDGEMENT ESTABLISH FACT DEATH         '     , 
pInput = 'JUDG DJT'       =>        	'JUDGEMENT ESTABLISH FACT DEATH JT TENANT'      , 
pInput = 'JUDG DSLN'       =>        	'JUDGEMENT DISSOLUTION                  '       , 
pInput = 'JUDG FORFEIT'       =>        	'FINAL JUDGEMENT FORFEITURE             '   , 
pInput = 'JUDG ISSUES'       =>        	'JUDGEMENT RESERVED ISSUES              '     , 
pInput = 'JUDG PRELIM'       =>        	'JUDGEMENT PRELIM DISTRIBUTION          '     , 
pInput = 'JUDG QT TL'       =>        	'JUDGEMENT QUIETING TITLE               '     , 
pInput = 'JUDG REIMBSE'       =>        	'JUDGEMENT REIMBURSE                    '   , 
pInput = 'JUDG REL LN'       =>        	'JUDGEMENT RELEASE LIEN                 '     , 
pInput = 'JUDG VOID LN'       =>        	'JUDGEMENT VOID LIEN                    '   , 
pInput = 'JUDGE DEFALT'       =>        	'JUDGEMENT DEFAULT                      '   , 
pInput = 'LABOR BOND'       =>        	'BOND LABOR                             '     , 
pInput = 'LAND CONTR'       =>        	'LAND CONTR OR LAND SALE CONTR          '     , 
pInput = 'LANDSCAPE'       =>        	'LANDSCAPE                              '       , 
pInput = 'LEASE'       =>        	'LEASE                                  '           , 
pInput = 'LICENSE AGR'       =>        	'LICENSE AGREEMENT                      '     , 
pInput = 'LIEN'       =>        	'LIEN                                   '           , 
pInput = 'LIEN CONTR'       =>        	'LIEN CONTRACTOR                        '     , 
pInput = 'LN REFIN INS'       =>        	'BALLOON LOAN REFINANCING INSTRUMENT    '   , 
pInput = 'LNDLRD CNSNT'       =>        	'LANDLORD CONSENT                       '   , 
pInput = 'LOST ASGN'       =>        	'LOST ASSIGNMENT                        '       , 
pInput = 'LOST SEC BND'       =>        	'LOST SECURITIES BOND                   '   , 
pInput = 'LSE & OPT RL'       =>        	'LEASE & OPTION TERMENATION AGREEMENT   '   , 
pInput = 'LTR UNDERSTD'       =>        	'LETTERS UNDERSTAND                     '   , 
pInput = 'LTRS ADMN'       =>        	'LETTERS ADMINSTRATION                  '       , 
pInput = 'LTRS AUTH'       =>        	'LETTER AUTHORITY                       '       , 
pInput = 'LTRS CON TOR'       =>        	'LETTERS CONSERVATORSHIP                '   , 
pInput = 'LTRS ETC'       =>        	'LETTERS etc.                           '       , 
pInput = 'LTRS GDN'       =>        	'LETTERS GUARDIANSHIP                   '       , 
pInput = 'LTRS TEST'       =>        	'LETTERS TESTAMENTARY                   '       , 
pInput = 'MAR SET AGR'       =>        	'MARRIAGE SETTLEMENT AGREEMENT          '     , 
pInput = 'MATURE INSTL'       =>        	'MATURE INSTALL                         '   , 
pInput = 'MATURE INSTL'       =>        	'ACKNOWLEDGEMENT SAT JUDG MATURE INSTALL'   , 
pInput = 'MECH LIEN'       =>        	'MECHANICS LIEN                         '       , 
pInput = 'MERGER'       =>        	'MERGER                                 '         , 
pInput = 'MERGER AGR'       =>        	'MERGER AGREEMENT                       '     , 
pInput = 'MIL DISCHG'       =>        	'MILTITARY DISCHARGE                    '     , 
pInput = 'MINUTES'       =>        	'MINUTES                                '         , 
pInput = 'MISC'       =>        	'MISCELLEANOUS DOCUMENTS                '           , 
pInput = 'MOD AGR'       =>        	'MODIFICATION AGR                       '         , 
pInput = 'MOD TR D'       =>        	'MODIFICATION OF DEED OF TRUST          '       , 
pInput = 'MOD&EXT AGR'       =>        	'MODIFICATION & EXTENTION AGREEMENT     '     , 
pInput = 'MORTGAGE'       =>        	'MORTGAGE                               '       , 
pInput = 'MOTION DISML'       =>        	'MOTION DISMISSAL & ORDER THEREON       '   , 
pInput = 'MTG ANIMATE'       =>        	'MORTGAGE ANIMATE CHATTEL               '     , 
pInput = 'MTG CROPS'       =>        	'MORTGAGE CROPS                         '       , 
pInput = 'MTG LVSTK'       =>        	'MORTGAGE LIVESTOCK                     '       , 
pInput = 'MTG PER PROP'       =>        	'MORTGAGE PERSONAL PROP                 '   , 
pInput = 'MTG REAL PRP'       =>        	'MORTGAGE REAL PROP                     '   , 
pInput = 'NON COMPLIAN'       =>        	'CERTIFICATE OF NON COMPLIANCE          '   , 
pInput = 'NON DISTRUB'       =>        	'NONDISTURBANCE AGREEMENT               '     , 
pInput = 'NOTARY BOND'       =>        	'NOTARY BOND                            '     , 
pInput = 'NOTICE'       =>        	'NOTICE                                 '         , 
pInput = 'NOTICE LIEN'       =>        	'NOTICE OF FAMILY LAW REAL PROPERTY LIEN'     , 
pInput = 'NT ABD & CES'       =>        	'NOTICE ABD & CESSATION                 '   , 
pInput = 'NT ACTION'       =>        	'NOTICE OF PENDING ACTION               '       , 
pInput = 'NT ADD ADV'       =>        	'NOTICE OF ADDITIONAL ADVANCE           '     , 
pInput = 'NT AGR'       =>        	'NOTICE AGREEMENT                       '         , 
pInput = 'NT AM ASMT'       =>        	'NOTICE AMENDED ASSESSMENT              '     , 
pInput = 'NT ASMT'       =>        	'NOTICE ASSESSMENT                      '         , 
pInput = 'NT ASSURANCE'       =>        	'NOTICE ASSURANCES USE PROP & RIGHT RECAP'  , 
pInput = 'NT ATTACH'       =>        	'NOTICE ATTACH                          '       , 
pInput = 'NT BKPCY'       =>        	'NOTICE BKPCY PROCEEDINGS               '       , 
pInput = 'NT BREACH'       =>        	'NOTICE BREACH                          '       , 
pInput = 'NT BULK TRAN'       =>        	'NOTICE BULK TRANSFER                   '   , 
pInput = 'NT BUYERS'       =>        	'NOTICE PROSPECTIVE BUYERS              '       , 
pInput = 'NT CAC'       =>        	'NOTICE CANCELLATION                    '         , 
pInput = 'NT CEASE'       =>        	'NOTICE CEASE & DESIST                  '       , 
pInput = 'NT CESSATION'       =>        	'NOTICE OF CESSATION                    '   , 
pInput = 'NT CLAIM LN'       =>        	'NOTICE CLAIM LIEN                      '     , 
pInput = 'NT COML DISH'       =>        	'NOTICE GOMMERCIAL DISHONOR             '   , 
pInput = 'NT COMPL'       =>        	'NOTICE COMPLETION                      '       , 
pInput = 'NT CONSENT'       =>        	'NOTICE CONSENT USE LAND                '     , 
pInput = 'NT COR FP RL'       =>        	'NOTICE CORRECT FOREST PRACTICE RULE    '   , 
pInput = 'NT DEF'       =>        	'NOTICE DEFAULT                         '         , 
pInput = 'NT DISHG LN'       =>        	'NOTICE DISCHARGE ASMT LIEN             '     , 
pInput = 'NT EXT ASMT'       =>        	'NOTICE EXT DELINQ ASMT                 '     , 
pInput = 'NT EXT LIEN'       =>        	'NOTICE EXT STATE TAX LIEN              '     , 
pInput = 'NT INT SALE'       =>        	'NOTICE INTENDED SALE                   '     , 
pInput = 'NT INTENT'       =>        	'NOTICE INTENT                          '       , 
pInput = 'NT INTEREST'       =>        	'NOTICE INTEREST R P                    '     , 
pInput = 'NT LEVY'       =>        	'NOTICE LEVY                            '         , 
pInput = 'NT LIEN SALE'       =>        	'NOTICE LIEN SALE                       '   , 
pInput = 'NT LIEN SR T'       =>        	'NOTICE LIEN PROSTPONED PROP TAX        '   , 
pInput = 'NT LIFT VIOL'       =>        	'NOTICE LIFT ZONE VIOLATION             '   , 
pInput = 'NT LOC'       =>        	'NOTICE MINING LOCATION                 '         , 
pInput = 'NT MIN RIGHT'       =>        	'NOTICE INTENT PRESERVE MINERAL RIGHTS  '   , 
pInput = 'NT MOD ASMT '       =>        	'NOTICE MOD ASMT                        '   , 
pInput = 'NT NON ACCPT'       =>        	'NOTICE NON ACCEPT DEED                 '   , 
pInput = 'NT NON RENWL'       =>        	'NOTICE NON RENEWAL                     '   , 
pInput = 'NT NON RESP'       =>        	'NOTICE NON RESPONSIBILITY              '     , 
pInput = 'NT OCCUPCYTX'       =>        	'NOTICE OCCUPCY TAX                     '   , 
pInput = 'NT OPTN AGR'       =>        	'NOTICE OPTION AGR                      '     , 
pInput = 'NT OPTN PUR'       =>        	'NOTICE OPTION PURCHASE R P             '     , 
pInput = 'NT PEN LIT'       =>        	'NOTICE PENDING LITIGATION              '     , 
pInput = 'NT REASMT'       =>        	'NOTICE REASSESSMENT                    '       , 
pInput = 'NT REL RESTR'       =>        	'NOTICE OF RELEASE OF RESTRICTION       '   , 
pInput = 'NT RES AGR'       =>        	'NOTICE OF RESCISSION OF AGREEMENT      '     , 
pInput = 'NT RES LIEN'       =>        	'NOTICE RESCIND ASMT LIEN               '     , 
pInput = 'NT RES OPTN'       =>        	'NOTICE RESCISSION PURPORTED OPTIN      '     , 
pInput = 'NT RESC DECL'       =>        	'NOTICE RESCISSION DECL                 '   , 
pInput = 'NT RESTR'       =>        	'NOTICE OF RESTRICTIONS                 '       , 
pInput = 'NT RESTRUCT'       =>        	'NOTICE RESTRUCT LN SEC BY D T          '     , 
pInput = 'NT REV AGR'       =>        	'NOTICE REV AGR & FIRST RIGHT REFUSAL   '     , 
pInput = 'NT REV TRUST'       =>        	'NOTICE REV TRUST                       '   , 
pInput = 'NT SALE'       =>        	'NOTICE SALE                            '         , 
pInput = 'NT SAT ADDLN'       =>        	'NOTICE SAT ADD LN UNDER D T            '   , 
pInput = 'NT SAT LIEN'       =>        	'NOTICE SAT & REL LIEN                  '     , 
pInput = 'NT SEPARATN'       =>        	'NOTICE SEPARATION                      '     , 
pInput = 'NT TAX DEF'       =>        	'NOTICE POWER SELL TAX DEFAULTED PROP   '     , 
pInput = 'NT TERM ACTN'       =>        	'NOTICE TERM ACTION                     '   , 
pInput = 'NT TERM ESMT'       =>        	'NOTICE TERM TEMP ESMT                  '   , 
pInput = 'NT TERM TEN'       =>        	'NOTICE TERM TENANCY                    '     , 
pInput = 'NT TRN OPTN'       =>        	'NOTICE TRANSFER OPTION REPURCHASE      '     , 
pInput = 'NT TRN SEWER'       =>        	'NOTICE REGARD TRN SEWER UNITS          '   , 
pInput = 'NT TSTEE SAL'       =>        	'NOTICE OF TRUSTEE SALE                 '   , 
pInput = 'NT VIOLATION'       =>        	'NOTICE VIOLATION                       '   , 
pInput = 'NT WITHDRAW'       =>        	'NOTICE WITHDRAWAL LEIN WATER FURNISHED '     , 
pInput = 'NT WTR LINE'       =>        	'NOTICE PRIVATE WATER LINE              '     , 
pInput = 'NT ZONE ADMR'       =>        	'NOTICE ZONING ADMR USE PERMIT          '   , 
pInput = 'NUPTIAL AGR'       =>        	'\"ANTE , PRE, POST NUPTIAL AGR\"       '     , 
pInput = 'OBJECTION SL'       =>        	'OBJECTION SALE FREE & CLEAR ALL LIENS  '   , 
pInput = 'OFF BOND'       =>        	'OFFICIAL BOND                          '       , 
pInput = 'OFF BOND'       =>        	'BOND OFFICIAL                          '       , 
pInput = 'OFFER'       =>        	'OFFER OF STREET DEDICATION             '           , 
pInput = 'OFFER ETC'       =>        	'OFFER etc.                             '       , 
pInput = 'OPTION'       =>        	'OPTION BUY R P                         '         , 
pInput = 'OPTION AGR'       =>        	'ABSTRACT OPTION AGREE                  '     , 
pInput = 'OPTION AGR'       =>        	'OPTION AGR                             '     , 
pInput = 'OPTION PUR'       =>        	'OPTION PURCHASE                        '     , 
pInput = 'OR ABD HWY'       =>        	'ORDER ABANDON HWY                      '     , 
pInput = 'OR ABD R P'       =>        	'ORDER ABANDON R P                      '     , 
pInput = 'OR ABD ROAD'       =>        	'ORDER ABANDON COUNTY ROAD              '     , 
pInput = 'OR APPOINT'       =>        	'ORDER APPOINT                          '     , 
pInput = 'OR APPT CNTR'       =>        	'ORDER APPOINT CONSERVATOR              '   , 
pInput = 'OR APPT RCVR'       =>        	'ORDER APPOINT RECEIVER                 '   , 
pInput = 'OR APPT TR'       =>        	'ORDER APPOINT TR                       '     , 
pInput = 'OR ASGN WAGE'       =>        	'ORDER ASSIGN SALARY WAGES CHILD SUPPORT'   , 
pInput = 'OR AUTH ABD'       =>        	'ORDER AUTH ABD PROP                    '     , 
pInput = 'OR AVD LIEN'       =>        	'ORDER AVOID JUDICIAL LIEN              '     , 
pInput = 'OR CHANGE'       =>        	'ORDER ALLOW CHANGES MULTI PURPOSE      '       , 
pInput = 'OR COMPROMIS'       =>        	'ORDER AUTHORIZE COMPROMISE             '   , 
pInput = 'OR CONVEY'       =>        	'ORDER DIRECT CONVEY R P                '       , 
pInput = 'OR DETERM RP'       =>        	'ORDER DETERM SUCCESSION R P            '   , 
pInput = 'OR DISML'       =>        	'ORDER DISMISS CHAPTER 11               '       , 
pInput = 'OR EXEMPT'       =>        	'ORDER EDECL APPLICABITLITY HMSTD EXEMPT'       , 
pInput = 'OR EXLUD LND'       =>        	'ORDER EXCLUDING LANDS                  '   , 
pInput = 'OR EXONERATE'       =>        	'ORDER COURT EXONERATING PROP BOND      '   , 
pInput = 'OR EXPUNGE'       =>        	'ORDER EXPUNGE LIS PEN                  '     , 
pInput = 'OR HEARING'       =>        	'ORDER HEARING                          '     , 
pInput = 'OR INC LANDS'       =>        	'ORDER INCLUDING LANDS                  '   , 
pInput = 'OR ISSUES'       =>        	'ORDER ISSUES                           '       , 
pInput = 'OR JUDG DSML'       =>        	'ORDER JUDG & DISML                     '   , 
pInput = 'OR LIEN INVL'       =>        	'ORDER ADJUD LIEN INVALID               '   , 
pInput = 'OR LIFT STAY'       =>        	'ORDER LIFT AUTOMATIC STAY              '   , 
pInput = 'OR LIQUID'       =>        	'FINDINGS FACT & OR PROCED LIQUID       '       , 
pInput = 'OR PAR DISTR'       =>        	'ORDER PARTIAL DISTRIBUTION             '   , 
pInput = 'OR PAY ABATE'       =>        	'ORDER PAYMENT ABATEMENT NUISANCE       '   , 
pInput = 'OR REV LIC'       =>        	'ORDER REVOKING LICENSE                 '     , 
pInput = 'OR SALE'       =>        	'ORDER OF SALE                          '         , 
pInput = 'OR SELL ASTS'       =>        	'ORDER SELL ASSETS                      '   , 
pInput = 'OR SET TR BD'       =>        	'ORDER SET AMT TR BOND                  '   , 
pInput = 'OR SUB TR'       =>        	'ORDER SUB TR                           '       , 
pInput = 'OR SUPPORT'       =>        	'ORDER SUPPORT                          '     , 
pInput = 'OR TERM TR'       =>        	'ORDER TERMINATE TRUST                  '     , 
pInput = 'OR TR BOND'       =>        	'ORDER APPROVE TR                       '     , 
pInput = 'OR TRAN R P'       =>        	'ORDER TRANSFER R P                     '     , 
pInput = 'OR VAC & SLE'       =>        	'ORDER VACATE OR SALE & OR SALE         '   , 
pInput = 'OR VAC LIEN'       =>        	'EX PARTE ORDER VACATE MECHANICS LIEN   '     , 
pInput = 'ORDER'       =>        	'ORDER                                  '           , 
pInput = 'OWN CERT'       =>        	'OWNERS CERTIFICATE                     '       , 
pInput = 'PAR ASGN JUD'       =>        	'PARTIAL ASGN JUDG                      '   , 
pInput = 'PAR ASGN TR'       =>        	'PARTIAL ASGN TR D                      '     , 
pInput = 'PAR CAC LIEN'       =>        	'CERTIFICATE PAR CAC LIEN               '   , 
pInput = 'PAR REASGN'       =>        	'PARTIAL REASSIGNMENT OF NOTES AND LIENS'     , 
pInput = 'PAR RECON'       =>        	'PARTIAL RECONVEYANCE                   '       , 
pInput = 'PAR REL EQUI'       =>        	'PAR REL EQUITY                         '   , 
pInput = 'PAR REL FED'       =>        	'PARTIAL REL JUDG LIEN                  '     , 
pInput = 'PAR REL JUDG'       =>        	'PAR REL ABSTR JUDG                     '   , 
pInput = 'PAR REL JUDG'       =>        	'ACKNOWLEDGMENT SAT JUDG PARTIAL        '   , 
pInput = 'PAR REL LIEN'       =>        	'PARTIAL RELEASE OF LIEN                '   , 
pInput = 'PAR REL LIS'       =>        	'PAR REL LIS PEN                        '     , 
pInput = 'PAR REL MTG'       =>        	'PARTIAL REL MTG                        '     , 
pInput = 'PAR REL SALE'       =>        	'PAR REL NT SALE                        '   , 
pInput = 'PAR RELEASE'       =>        	'PARTIAL RELEASE                        '     , 
pInput = 'PAR RELINQ M'       =>        	'PAR RELINQ MINING CLAIM                '   , 
pInput = 'PAR SAT JUDG'       =>        	'PARTIAL SAT JUDG                       '   , 
pInput = 'PAR TERM AGR'       =>        	'Partial Termination of Agreement       '   , 
pInput = 'PARCEL MAP'       =>        	'PARCEL MAP                             '     , 
pInput = 'PATENT'       =>        	'PATENT                                 '         , 
pInput = 'PAYMENT BOND'       =>        	'PAYMENT BOND                           '   , 
pInput = 'PERFORM BOND'       =>        	'BOND PERFORMANCE                       '   , 
pInput = 'PERFORM BOND'       =>        	'PERFORMANCE BOND                       '   , 
pInput = 'PERMISSION U'       =>        	'PERMISSION USE                         '   , 
pInput = 'PET & ORDER'       =>        	'PETITION & ORDER                       '     , 
pInput = 'PET AM JUDG'       =>        	'PETITION OR AM FINAL JUDG              '     , 
pInput = 'PET AM RESTR'       =>        	'PETITION AM BLDG RESTR                 '   , 
pInput = 'PET CHAPTER'       =>        	'PETITION CHAPTER 11                    '     , 
pInput = 'PET IDENT'       =>        	'PETITION ESTABLISH IDENITY             '       , 
pInput = 'PET INCL LAN'       =>        	'PETITION INCLUDING LANDS               '   , 
pInput = 'PETITION'       =>        	'PETITION                               '       , 
pInput = 'PHOTO BOND'       =>        	'BOND FORFESSIONAL PHOTOCOPIER          '     , 
pInput = 'PLANS & SPEC'       =>        	'PLANS & SPEC                           '   , 
pInput = 'PLEDGE AGR'       =>        	'PLEDGE AGR                             '     , 
pInput = 'PRELIM AGR'       =>        	'PRELIMINARY AGR                        '     , 
pInput = 'PRELIM DISTR'       =>        	'ORDER PRELIM DISTR                     '   , 
pInput = 'PRELIM DISTR'       =>        	'PRELIMINARY DISTR                      '   , 
pInput = 'PRELIM DISTR'       =>        	'DECREE PRELIM DISTR                    '   , 
pInput = 'PRELIM INJUN'       =>        	'PRELIMINARY INJUNCTION                 '   , 
pInput = 'PROCESS BOND'       =>        	'PROCESS SERVERS BOND                   '   , 
pInput = 'PROM NOTE'       =>        	'PROMISSORY NOTE                        '       , 
pInput = 'PROOF LABOR'       =>        	'PROOF OF LABOR                         '     , 
pInput = 'PROOF PUB'       =>        	'PROOF PUBLICATION                      '       , 
pInput = 'PROP & CONTR'       =>        	'PROPOSAL & CONTR                       '   , 
pInput = 'PROP AGR'       =>        	'PROPERTY AGR                           '       , 
pInput = 'PROP OR'       =>        	'SPOUSAL PROPERTY ORDER                 '         , 
pInput = 'PROP SET AGR'       =>        	'PROPERTY SETTLEMENT AGR                '   , 
pInput = 'PROPOSAL'       =>        	'PROPOSAL                               '       , 
pInput = 'PTN AGR'       =>        	'PARTNERSHIP AGR                        '         , 
pInput = 'PUR & SALE A'       =>        	'PURCHASE & SALE AGR                    '   , 
pInput = 'PWR ATTY'       =>        	'POWER OF ATTORNEY                      '       , 
pInput = 'PWR ATTY ST'       =>        	'POWER ATTY STATE                       '     , 
pInput = 'R E CONSENT'       =>        	'REAL EST CONSENT                       '     , 
pInput = 'R E CONTR SL'       =>        	'REAL EST SALES CONTR                   '   , 
pInput = 'RD MAIN AGR'       =>        	'ROAD MAINTENANCE AGREEMENT             '     , 
pInput = 'RE ASMT MAP'       =>        	'RE ASMT MAP                            '     , 
pInput = 'REASGN TR D'       =>        	'REASSIGNMENT DEED TRUST                '     , 
pInput = 'REC SURVEY'       =>        	'RECORD OF SURVEY                       '     , 
pInput = 'RECON'       =>        	'RECONVEYANCE                           '           , 
pInput = 'REDEMP REL'       =>        	'RIGHT REDEMPTION REL                   '     , 
pInput = 'REFILE FED L'       =>        	'REFILE FED TAX LIEN                    '   , 
pInput = 'REFORM SEC I'       =>        	'REFORMATION SEC INT                    '   , 
pInput = 'REG AUTH AGR'       =>        	'REGULATORY AUTH EXEC FRONTAGE IMP AGR  '   , 
pInput = 'REINSTATE D'       =>        	'REINSTATEMENT D T                      '     , 
pInput = 'REISSUANCE'       =>        	'REISSUANCE CERT TENT CAC AGR PRESERVE  '     , 
pInput = 'REJECT OFFER'       =>        	'REJECTION OFFER                        '   , 
pInput = 'REL'       =>        	'RELEASE                                '             , 
pInput = 'REL & EXPUNG'       =>        	'RELEASE & EXPUNGE WRIT ATTACH          '   , 
pInput = 'REL & REASGN'       =>        	'RELEASE & REASGN                       '   , 
pInput = 'REL & SAT'       =>        	'RELEASE & SAT                          '       , 
pInput = 'REL AGR'       =>        	'RELEASE AGR                            '         , 
pInput = 'REL ASGN'       =>        	'RELEASE ASSIGNMENT                     '       , 
pInput = 'REL ASGN D T'       =>        	'RELEASE ASGN D TR                      '   , 
pInput = 'REL ASMT LIE'       =>        	'RELEASE ASMT LIEN                      '   , 
pInput = 'REL ATT'       =>        	'RELEASE ATTACH                         '         , 
pInput = 'REL CHATL MT'       =>        	'RELEASE CHATL MTG                      '   , 
pInput = 'REL CONSENT'       =>        	'RELEASE CONSENT & WAIVER               '     , 
pInput = 'REL EQUITY'       =>        	'RELEASE EQUITY                         '     , 
pInput = 'REL EXPUNGE'       =>        	'RELEASE EXPUNGE EXON TEMP PROT OR & WRIT'    , 
pInput = 'REL FED LIEN'       =>        	'RELEASE OF LIEN (IRS)                  '   , 
pInput = 'REL GIFT TAX'       =>        	'RELEASE REAL PROP FROM GIFT TAX LIEN   '   , 
pInput = 'REL IN TX L'       =>        	'RELEASE INHERITANCE TAX LIEN           '     , 
pInput = 'REL INT R P'       =>        	'FULL REL INTEREST REAL PROPERTY        '     , 
pInput = 'REL INT R P'       =>        	'RELEASE INTEREST R P                   '     , 
pInput = 'REL JUDG'       =>        	'RELEASE JUDG                           '       , 
pInput = 'REL LEASE'       =>        	'RELEASE LEASE                          '       , 
pInput = 'REL LIEN'       =>        	'RELEASE OF LIEN                        '       , 
pInput = 'REL LIEN BON'       =>        	'RELEASE LIEN BOND                      '   , 
pInput = 'REL LIS PEN'       =>        	'RELEASE LIS PEN                        '     , 
pInput = 'REL MIN CLAI'       =>        	'RELEASE MINING CLAIM                   '   , 
pInput = 'REL MTG'       =>        	'RELEASE MORTGAGE                       '         , 
pInput = 'REL NON COMP'       =>        	'RELEASE CERT NON COMPLIANCE            '   , 
pInput = 'REL NT PEN'       =>        	'RELEASE NT PENDING ACTION              '     , 
pInput = 'REL R P AGR'       =>        	'RELEASE AGR NOT SALE ENCUMBER R P      '     , 
pInput = 'REL R P LIEN'       =>        	'RELEASE REAL PROP LIEN                 '   , 
pInput = 'REL REAL EST'       =>        	'RELEASE REAL EST                       '   , 
pInput = 'REL RT REDEM'       =>        	'RELEASE RIGHT REDEMP                   '   , 
pInput = 'REL TAX LIEN'       =>        	'RELEASE OF LIEN (STATE)                '   , 
pInput = 'REL TR D'       =>        	'RELEASE OBLIGATION UNDER DEED OF TRUST '       , 
pInput = 'REL VIOLATIO'       =>        	'RELEASE NT VIOLATION                   '   , 
pInput = 'REL WAIVER'       =>        	'RELEASE WAIVER                         '     , 
pInput = 'REL WATER'       =>        	'RELEASE OF LIABILITY FOR WATER PRESSURE'       , 
pInput = 'RELINQ HWY'       =>        	'RELINQUISHMENT HWY                     '     , 
pInput = 'RELINQ HWY M'       =>        	'RELINQUISHMENT HWY MAP                 '   , 
pInput = 'RELINQ HWY R'       =>        	'RELINQUISHMENT HWY RW                  '   , 
pInput = 'REMOVAL AGR'       =>        	'REMOVAL AGR TEMP MOBILE HOME APPLICATION'     , 
pInput = 'REMOVAL LIEN'       =>        	'Removal of Invalid Judgement Lien      '   , 
pInput = 'RENEW JUDG'       =>        	'APPLICATION RENEW JUDG                 '     , 
pInput = 'RENEWAL LIEN'       =>        	'RENEWAL LIEN CERT DELINQ               '   , 
pInput = 'REQ DISML'       =>        	'REQUEST DISMISSAL                      '       , 
pInput = 'REQ NT DEF'       =>        	'REQUEST NOTICE OF DEFAULT              '     , 
pInput = 'REQ NT DELNQ'       =>        	'Request for Notice of Delinquency      '   , 
pInput = 'REQ RESCIND'       =>        	'REQUEST TO RESCIND NOTICE etc.         '     , 
pInput = 'RES D RECON'       =>        	'Rescission of Deed of Reconveyance     '     , 
pInput = 'RES DECL CCR'       =>        	'RESCISSION OF DECLARATION OF CCR       '   , 
pInput = 'RES ETC'       =>        	'RESCISSION etc.                        '         , 
pInput = 'RES NT SELL'       =>        	'RESCISSION NT PWR SELL TAX DEFAULT PROP'     , 
pInput = 'RES TSTEE DE'       =>        	'RECESSION TRUSTEE DEED UPON SALE       '   , 
pInput = 'RES TX DEED'       =>        	'RESCISSION TX DEED PUR TX DEF PROP ERROR'     , 
pInput = 'RESIGN TR'       =>        	'RESIGNATION TRUSTEE                    '       , 
pInput = 'RESOL'       =>        	'RESOLUTION                             '           , 
pInput = 'RESOL ABD'       =>        	'RESOLUTION ABANDON                     '       , 
pInput = 'RESOL ACCEPT'       =>        	'RESOLUTION ACCEPTANCE                  '   , 
pInput = 'RESOL ANNEX'       =>        	'RESOLUTION ANNEX                       '     , 
pInput = 'RESOL VACATE'       =>        	'RESOLUTION VACATE                      '   , 
pInput = 'RESTR COV AG'       =>        	'RESTRICTIVE COVENANT AGR               '   , 
pInput = 'RESTR MOD'       =>        	'RESTRICTIVE COVENANT MODIFICATION      '       , 
pInput = 'REV DECL RES'       =>        	'REVOCATION DECLARATION RESTRICTIONS    '   , 
pInput = 'REV LIV TRUS'       =>        	'REVOCABLE LIVING TRUST                 '   , 
pInput = 'REV PWR ATTY'       =>        	'REVOCATION PWR ATTY                    '   , 
pInput = 'REV PWR ATTY'       =>        	'DECLARATION REGARD REV PWR ATTY DISLAIM'   , 
pInput = 'REV PWR ST'       =>        	'REVOCATION PWR ATTY CAL ST             '     , 
pInput = 'REV RECON'       =>        	'REVOCATION RECON                       '       , 
pInput = 'REV REL FED'       =>        	'REVOCATION CERT REL FED TAX LIEN       '     , 
pInput = 'REV TRUST'       =>        	'REVOCATION TRUST                       '       , 
pInput = 'REVOCATION'       =>        	'REVOCATION                             '     , 
pInput = 'RGHT ENTRY'       =>        	'RIGHT OF ENTRY                         '     , 
pInput = 'RIGHT REFUSA'       =>        	'RIGHT FIRST REFUSAL                    '   , 
pInput = 'RW'       =>        	'RIGHT OF WAY                           '             , 
pInput = 'SAT CHATL MT'       =>        	'SATISFACTION CHATL MTG                 '   , 
pInput = 'SAT JUDG'       =>        	'SATISFACTION JUDGEMENT                 '       , 
pInput = 'SAT MTG'       =>        	'SATISFACTION MTG                       '         , 
pInput = 'SATISFACTION'       =>        	'SATISFACTION                           '   , 
pInput = 'SEC AGR'       =>        	'SECURITY AGREEMENT                     '         , 
pInput = 'SEVER JT TEN'       =>        	'SEVERANCE JT TENANCY                   '   , 
pInput = 'SEWER CON AG'       =>        	'SEWER CONNECTION AGR                   '   , 
pInput = 'SHER CERT SA'       =>        	'SHERIFFS CERT SALE                     '   , 
pInput = 'SPECIAL PERM'       =>        	'SPECIAL USE PERMIT                     '   , 
pInput = 'STATE JT VEN'       =>        	'STATEMENT JT VEN                       '   , 
pInput = 'STATE PTN'       =>        	'STATEMENT PTN                          '       , 
pInput = 'STATEMENT'       =>        	'STATEMENT                              '       , 
pInput = 'STAY EXECUTE'       =>        	'MOTION STAY EXECUTION                  '   , 
pInput = 'STIP'       =>        	'STIPULATION                            '           , 
pInput = 'STIP & OR'       =>        	'STIPULATION & ORDER                    '       , 
pInput = 'SUB MAP'       =>        	'SUBDIVISION MAP                        '         , 
pInput = 'SUB TR'       =>        	'SUBSTITUTION OF TRUSTEE                '         , 
pInput = 'SUBOR'       =>        	'SUBORDINATION                          '           , 
pInput = 'SUBOR AGR'       =>        	'SUBORDINATION AGREEMENT                '       , 
pInput = 'SUBOR LEASE'       =>        	'SUBORDINATION LEASE                    '     , 
pInput = 'SUBOR LIEN'       =>        	'SUBORDINATION LIEN                     '     , 
pInput = 'SUBOR REL LN'       =>        	'CERTIFICATE REL SUBOR DEPTS LIEN LENDER'   , 
pInput = 'SUBOR TERM'       =>        	'SUBORDINATION TERMINATION              '     , 
pInput = 'SUBOR&CONSEN'       =>        	'SUBORDINATION & CONSENT                '   , 
pInput = 'SUPMNTAL ETC'       =>        	'Supplemental etc.                      '   , 
pInput = 'SURETY BOND'       =>        	'SURETY BOND                            '     , 
pInput = 'SURRENDER'       =>        	'SURRENDER                              '       , 
pInput = 'TAX COL CERT'       =>        	'TAX COL CERT                           '   , 
pInput = 'TAX DEED'       =>        	'TAX DEED TO PURCHASER OF TAX DEFAULTED '       , 
pInput = 'TAX LIEN'       =>        	'TAX LIEN (STATE)                       '       , 
pInput = 'TEMP PROT OR'       =>        	'TEMPORARY PROTECTIVE ORDER             '   , 
pInput = 'TEMP SERV AG'       =>        	'TEMPORARY SERV AGR                     '   , 
pInput = 'TERM LEASE'       =>        	'TERMINATION LEASE                      '     , 
pInput = 'TERMINATION'       =>        	'TERMINATION                            '     , 
pInput = 'TIMBER PERMI'       =>        	'TIMBERLAND PERMIT                      '   , 
pInput = 'TR CERT'       =>        	'TRUSTEES CERTIFICATE                   '         , 
pInput = 'TRN & ASGN'       =>        	'TRANSFER & ASSIGNMENT                  '     , 
pInput = 'TRN IMP'       =>        	'TRANSFER IMPROVEMENTS                  '         , 
pInput = 'TRN LIEN'       =>        	'TRANSFER LIEN                          '       , 
pInput = 'TRN WTR SERV'       =>        	'TRANSFERENCE WTR SERV                  '   , 
pInput = 'TRUST'       =>        	'MEMORANDUM OF TRUST OR TRUST           '           , 
pInput = 'TRUST AGR'       =>        	'TRUST AGR                              '       , 
pInput = 'TRUST DEED'       =>        	'DEED OF TRUST                          '     , 
pInput = 'TRUSTEE DEED'       =>        	'TRUSTEE DEED UPON SALE                 '   , 
pInput = 'UCC'       =>        	'UCC 1                                  '             , 
pInput = 'UCC AM'       =>        	'UCC AMENDMENT                          '         , 
pInput = 'UCC ASGN'       =>        	'UCC 2 ASSIGNMENT                       '       , 
pInput = 'UCC CONT'       =>        	'UCC CONTINUATION                       '       , 
pInput = 'UCC REL'       =>        	'UCC REL                                '         , 
pInput = 'UCC TERM'       =>        	'UCC 2 TERMINATION                      '       , 
pInput = 'VOL PETITION'       =>        	'VOLUNTARY PETITION                     '   , 
pInput = 'WAIVER'       =>        	'WAIVER                                 '         , 
pInput = 'WILLIAMSON A'       =>        	'WILLIAMSON ACT CONTR                   '   , 
pInput = 'WITHDRAWAL'       =>        	'WITHDRAWAL LIS PENDENS                 '     , 
pInput = 'WITHDRAWAL L'       =>        	'WITHDRAWAL LIEN                        '   , 
pInput = 'WRIT ATT'       =>        	'WRIT ATTACHMENT                        '       , 
pInput = 'WTR LICENSE'       =>        	'WATER LICENSE                          '     , 
pInput = 'WTR LICENSE'       =>        	'LICENSE DIVERSION & USE WATER          '     , 
pInput = 'WTR WELL ESM'       =>        	'CONTRACT ESMT WATER WELL USE           '   , 
'');