IMPORT doxie, doxie_raw, iesp;

EXPORT layout := MODULE

  EXPORT request := RECORD
    string firstname;
    string middlename;
    string lastname;
    string sex;
    string sex_use;
    string tag;
    string vin;
    string city;
    string state;
    string county;
    string zip5;
    string zipradius;
    string agehigh;
    string agehigher;
    string agelow;
    string agelower;
    string agerangestart_use;
    string agerangeend_use;
    string modelyearstart;
    string modelyearstart_use;
    string modelyearend;
    string modelyearend_use;
    string recordbydate;
    string recordstatus;
    string registerstate;
    string registrationtype;
    string regstate_use;
    string currentyear;
    string maxresults;
    string maxresultsthistime;
    string skiprecords;
    string lexidsourceoptout;
    string datarestrictionmask;
    string datapermissionmask; // not in the original input layout
    string dlmask;
    string dppapurpose;
    string glbpurpose;
    string industryclass;
    string ssnmask;
    string includecriminalindicators;
    string includenonregulatedvehiclesources;
    string containssearch;
    string allowall;
    string allowdppa;
    string allowglb;
    string keepoldssns;
    string includeminors;
    string usingkeepssns;
    string remoteoptimization;
    string usetagblur;
    string nofail;
    string raw;
    // DATASET(iesp.share.t_StringArrayItem) sortbytagtypes;
    // DATASET(iesp.share.t_StringArrayItem) body;
    // DATASET(iesp.share.t_StringArrayItem) body_use;
    // DATASET(iesp.share.t_StringArrayItem) majorcolor;
    // DATASET(iesp.share.t_StringArrayItem) majorcolor_use;
    // DATASET(iesp.share.t_StringArrayItem) make;
    // DATASET(iesp.share.t_StringArrayItem) make_use;
    // DATASET(iesp.share.t_StringArrayItem) model;
    // DATASET(iesp.share.t_StringArrayItem) model_use;
    // DATASET(iesp.share.t_StringArrayItem) state_use;
    // DATASET(iesp.share.t_StringArrayItem) zip;
    // DATASET(iesp.share.t_StringArrayItem) zip_use;
    set of string sortbytagtypes  {xpath('sortbytagtypes/item')};
    set of string body {xpath('body/item')};
    // set of string body_use {xpath('body_use/item')};
    set of string majorcolor {xpath('majorcolor/item')};
    // set of string majorcolor_use {xpath('majorcolor_use/item')};
    set of string make {xpath('make/item')};
    // set of string make_use {xpath('make_use/item')};
    set of string model {xpath('model/item')};
    // set of string model_use {xpath('model_use/item')};
    // set of string state_use {xpath('state_use/item')};
    set of string zip {xpath('zip/item')};
    // set of string zip_use {xpath('zip_use/item')};
  END;

  //as defined in VehicleV2_Services\Fn_Find.ecl
  out_layout := RECORD
    doxie_Raw.Layout_VehRawBatchInput.input_layout input;
    doxie.Layout_VehicleSearch_wCrimInd;
    //adding the plate type desc for the wildcard_search service
    STRING65 license_plate_desc := '';
  END;

  //as defined in doxie.Wildcard_Search
  x_layout := RECORD
    out_layout;   //result_return := doxie.Wildcard_Search_Records;
    string  best_title;
    string  best_fname;
    string  best_mname;
    string  best_lname;
    string  best_name_suffix;
    string  best_did;
    string  best_ssn;
    string  best_company_name;
    string  best_street_address;
    string  best_city;
    string  best_state;
    string  best_zip5_zip4_foreign_postal;
    string  best_apartment_number;
    string  best_zip5;
    string  best_county;
    string  best_county_name;
    string  best_dob;
    string  best_sex;
    string  best_driver_license_number;
    boolean best_hasCriminalConviction;
    boolean best_isSexualOffender;
  END;

  outf := x_layout;

  // "PrettyLayout" in doxie.Wildcard_Search
  EXPORT response := RECORD
    unsigned2 output_seq_no;
    outf.source;
    outf.vid;
    outf.dt_last_seen;
    outf.NonDMVSource;
    outf.history;
    outf.history_name;
    outf.make_description;
    outf.model_description;
    outf.series_description;
    outf.body_style_description;
    string30 major_color;// := outf.major_color_code;
    outf.major_color_name;
    string30 minor_color;// := outf.minor_color_code;
    outf.minor_color_name;
    outf.year_make;
    outf.body_code;
    outf.length_feet;
    outf.hull_material_type;
    outf.vessel_type;
    outf.orig_vin;
    outf.LICENSE_PLATE_NUMBERxBG4;
    outf.VEHICLE_NUMBERxBG1;
    outf.license_plate_code;
    outf.license_plate_desc;
    outf.orig_state;
    outf.orig_state_name;

    outf.own_1_title;
    outf.own_1_fname;
    outf.own_1_mname;
    outf.own_1_lname;
    outf.own_1_name_suffix;
    outf.own_1_did;
    outf.own_1_ssn;
    outf.own_1_company_name;
    outf.OWN_1_STREET_ADDRESS;
    outf.OWN_1_CITY;
    outf.OWN_1_STATE;
    outf.OWN_1_ZIP5_ZIP4_FOREIGN_POSTAL;
    outf.OWN_1_APARTMENT_NUMBER;
    outf.own_1_zip5;
    outf.own_1_county;
    outf.own_1_county_name;
    outf.own_1_dob;
    outf.own_1_sex;
    outf.OWN_1_DRIVER_LICENSE_NUMBER;
    outf.own_1_hasCriminalConviction;
    outf.own_1_isSexualOffender;
    outf.own_1_src_first_date;
    outf.own_1_src_last_date;

    outf.own_2_title;
    outf.own_2_fname;
    outf.own_2_mname;
    outf.own_2_lname;
    outf.own_2_name_suffix;
    outf.own_2_did;
    outf.own_2_ssn;
    outf.own_2_company_name;
    outf.own_2_STREET_ADDRESS;
    outf.own_2_CITY;
    outf.own_2_STATE;
    outf.own_2_ZIP5_ZIP4_FOREIGN_POSTAL;
    outf.own_2_APARTMENT_NUMBER;
    outf.own_2_zip5;
    outf.own_2_county;
    outf.own_2_county_name;
    outf.own_2_dob;
    outf.own_2_sex;
    outf.own_2_DRIVER_LICENSE_NUMBER;
    outf.own_2_hasCriminalConviction;
    outf.own_2_isSexualOffender;
    outf.own_2_src_first_date;
    outf.own_2_src_last_date;

    outf.reg_1_title;
    outf.reg_1_fname;
    outf.reg_1_mname;
    outf.reg_1_lname;
    outf.reg_1_name_suffix;
    outf.reg_1_did;
    outf.reg_1_ssn;
    outf.reg_1_company_name;
    outf.reg_1_STREET_ADDRESS;
    outf.reg_1_CITY;
    outf.reg_1_STATE;
    outf.reg_1_ZIP5_ZIP4_FOREIGN_POSTAL;
    outf.reg_1_APARTMENT_NUMBER;
    outf.reg_1_zip5;
    outf.reg_1_county;
    outf.reg_1_county_name;
    outf.reg_1_dob;
    outf.reg_1_sex;
    outf.reg_1_DRIVER_LICENSE_NUMBER;
    outf.reg_1_hasCriminalConviction;
    outf.reg_1_isSexualOffender;

    outf.reg_2_title;
    outf.reg_2_fname;
    outf.reg_2_mname;
    outf.reg_2_lname;
    outf.reg_2_name_suffix;
    outf.reg_2_did;
    outf.reg_2_ssn;
    outf.reg_2_company_name;
    outf.reg_2_STREET_ADDRESS;
    outf.reg_2_CITY;
    outf.reg_2_STATE;
    outf.reg_2_ZIP5_ZIP4_FOREIGN_POSTAL;
    outf.reg_2_APARTMENT_NUMBER;
    outf.reg_2_zip5;
    outf.reg_2_county;
    outf.reg_2_county_name;
    outf.reg_2_dob;
    outf.reg_2_sex;
    outf.reg_2_DRIVER_LICENSE_NUMBER;
    outf.reg_2_hasCriminalConviction;
    outf.reg_2_isSexualOffender;

    outf.best_title;
    outf.best_fname;
    outf.best_mname;
    outf.best_lname;
    outf.best_name_suffix;
    outf.best_did;
    outf.best_ssn;
    outf.best_company_name;
    outf.best_street_address;
    outf.best_city;
    outf.best_state;
    outf.best_zip5_zip4_foreign_postal;
    outf.best_apartment_number;
    outf.best_zip5;
    outf.best_county;
    outf.best_county_name;
    outf.best_dob;
    outf.best_sex;
    outf.best_driver_license_number;
    outf.best_hasCriminalConviction;
    outf.best_isSexualOffender;
  END;

END;
