Generated by SALT V3.11.6
Command line options: -MScrubs_Email_DataV2 -eC:\Users\LuceroSD\AppData\Local\Temp\TFR666E.tmp 
File being processed :-
OPTIONS:-gh
MODULE:Scrubs_Email_DataV2
FILENAME:Email_DataV2
 
SOURCEFIELD:email_src
 
FIELD:clean_email:TYPE(STRING200):0,0
FIELD:append_email_username:TYPE(STRING100):0,0
FIELD:append_domain:TYPE(STRING120):0,0
FIELD:append_domain_type:TYPE(STRING12):0,0
FIELD:append_domain_root:TYPE(STRING100):0,0
FIELD:append_domain_ext:TYPE(STRING20):0,0
FIELD:append_is_tld_state:TYPE(BOOLEAN1):0,0
FIELD:append_is_tld_generic:TYPE(BOOLEAN1):0,0
FIELD:append_is_tld_country:TYPE(BOOLEAN1):0,0
FIELD:append_is_valid_domain_ext:TYPE(BOOLEAN1):0,0
FIELD:email_rec_key:TYPE(UNSIGNED8):0,0
FIELD:email_src:TYPE(STRING2):0,0
FIELD:orig_pmghousehold_id:TYPE(STRING):0,0
FIELD:orig_pmgindividual_id:TYPE(STRING):0,0
FIELD:orig_first_name:TYPE(STRING):0,0
FIELD:orig_last_name:TYPE(STRING):0,0
FIELD:orig_middle_name:TYPE(STRING):0,0
FIELD:orig_name_suffix:TYPE(STRING):0,0
FIELD:orig_address:TYPE(STRING):0,0
FIELD:orig_city:TYPE(STRING):0,0
FIELD:orig_state:TYPE(STRING):0,0
FIELD:orig_zip:TYPE(STRING):0,0
FIELD:orig_zip4:TYPE(STRING):0,0
FIELD:orig_email:TYPE(STRING):0,0
FIELD:orig_ip:TYPE(STRING):0,0
FIELD:orig_login_date:TYPE(STRING):0,0
FIELD:orig_site:TYPE(STRING):0,0
FIELD:orig_e360_id:TYPE(STRING):0,0
FIELD:orig_teramedia_id:TYPE(STRING):0,0
FIELD:orig_phone:TYPE(STRING):0,0
FIELD:orig_ssn:TYPE(STRING):0,0
FIELD:orig_dob:TYPE(STRING):0,0
FIELD:did:TYPE(UNSIGNED6):0,0
FIELD:did_score:TYPE(UNSIGNED8):0,0
FIELD:did_type:TYPE(STRING10):0,0
FIELD:hhid:TYPE(UNSIGNED8):0,0
FIELD:title:TYPE(STRING5):0,0
FIELD:fname:TYPE(STRING20):0,0
FIELD:mname:TYPE(STRING20):0,0
FIELD:lname:TYPE(STRING20):0,0
FIELD:name_suffix:TYPE(STRING5):0,0
FIELD:name_score:TYPE(STRING3):0,0
FIELD:prim_range:TYPE(STRING10):0,0
FIELD:predir:TYPE(STRING2):0,0
FIELD:prim_name:TYPE(STRING28):0,0
FIELD:addr_suffix:TYPE(STRING4):0,0
FIELD:postdir:TYPE(STRING2):0,0
FIELD:unit_desig:TYPE(STRING10):0,0
FIELD:sec_range:TYPE(STRING8):0,0
FIELD:p_city_name:TYPE(STRING25):0,0
FIELD:v_city_name:TYPE(STRING25):0,0
FIELD:st:TYPE(STRING2):0,0
FIELD:zip:TYPE(STRING5):0,0
FIELD:zip4:TYPE(STRING4):0,0
FIELD:cart:TYPE(STRING4):0,0
FIELD:cr_sort_sz:TYPE(STRING1):0,0
FIELD:lot:TYPE(STRING4):0,0
FIELD:lot_order:TYPE(STRING1):0,0
FIELD:dbpc:TYPE(STRING2):0,0
FIELD:chk_digit:TYPE(STRING1):0,0
FIELD:rec_type:TYPE(STRING2):0,0
FIELD:county:TYPE(STRING5):0,0
FIELD:geo_lat:TYPE(STRING10):0,0
FIELD:geo_long:TYPE(STRING11):0,0
FIELD:msa:TYPE(STRING4):0,0
FIELD:geo_blk:TYPE(STRING7):0,0
FIELD:geo_match:TYPE(STRING1):0,0
FIELD:err_stat:TYPE(STRING4):0,0
FIELD:append_rawaid:TYPE(UNSIGNED8):0,0
FIELD:clean_phone:TYPE(STRING10):0,0
FIELD:clean_ssn:TYPE(STRING9):0,0
FIELD:clean_dob:TYPE(UNSIGNED4):0,0
FIELD:process_date:TYPE(STRING8):0,0
FIELD:activecode:TYPE(STRING1):0,0
FIELD:date_first_seen:TYPE(STRING8):0,0
FIELD:date_last_seen:TYPE(STRING8):0,0
FIELD:date_vendor_first_reported:TYPE(STRING8):0,0
FIELD:date_vendor_last_reported:TYPE(STRING8):0,0
FIELD:current_rec:TYPE(BOOLEAN1):0,0
FIELD:orig_companyname:TYPE(STRING):0,0
FIELD:cln_companyname:TYPE(STRING):0,0
FIELD:companytitle:TYPE(STRING):0,0
FIELD:rules:TYPE(UNSIGNED8):0,0
FIELD:dotid:TYPE(UNSIGNED6):0,0
FIELD:dotscore:TYPE(UNSIGNED2):0,0
FIELD:dotweight:TYPE(UNSIGNED2):0,0
FIELD:empid:TYPE(UNSIGNED6):0,0
FIELD:empscore:TYPE(UNSIGNED2):0,0
FIELD:empweight:TYPE(UNSIGNED2):0,0
FIELD:powid:TYPE(UNSIGNED6):0,0
FIELD:powscore:TYPE(UNSIGNED2):0,0
FIELD:powweight:TYPE(UNSIGNED2):0,0
FIELD:proxid:TYPE(UNSIGNED6):0,0
FIELD:proxscore:TYPE(UNSIGNED2):0,0
FIELD:proxweight:TYPE(UNSIGNED2):0,0
FIELD:seleid:TYPE(UNSIGNED6):0,0
FIELD:selescore:TYPE(UNSIGNED2):0,0
FIELD:seleweight:TYPE(UNSIGNED2):0,0
FIELD:orgid:TYPE(UNSIGNED6):0,0
FIELD:orgscore:TYPE(UNSIGNED2):0,0
FIELD:orgweight:TYPE(UNSIGNED2):0,0
FIELD:ultid:TYPE(UNSIGNED6):0,0
FIELD:ultscore:TYPE(UNSIGNED2):0,0
FIELD:ultweight:TYPE(UNSIGNED2):0,0
FIELD:global_sid:TYPE(UNSIGNED4):0,0
FIELD:record_sid:TYPE(UNSIGNED8):0,0
 
// CONCEPT statements should be used to group together interellated fields; such as address
// RELATIONSHIP is used to find non-obvious relationships between the clusters
// SOURCEFIELD is used if a field of the file denotes a source of the records in that file
// LINKPATH is used to define access paths for external linking
 
Total available specificity:0
Search Threshold set at -4
Use of PERSISTs in code set at:3
 
__Glossary__
Edit Distance: An edit distance of (say) one implies that one string can be converted into another by doing one of
  - Changing one character
  - Deleting one character
  - Transposing two characters
 
Forcing Criteria: In addition to the general 'best match' logic it is possible to insist that
one particular field must match to some degree or the whole record is considered a bad match.
The criterial applied to that one field is the forcing criteria.
 
Cascade: Best Type rules are applied in such a way that the rules are applied one by one UNTIL the first rule succeeds; subsequent rules are then skipped.
 
__General Notes__
How is it decided how much to subtract for a bad match?
SALT computes for each field the percentage likelihood that a valid cluster will have two or more values for a given field
this value (called the switch value in the SALT literature) is then used to produce the subtraction value from the match value.
The value in this document is the one typed into the SPC file; the code will use a value computed at run-time.
 
