rForeclosureCodes
 :=
  RECORD
	string8		code_type;
	string3		code;
	string40	code_desc;
  end
 ;

export File_Foreclosure_Codes
 :=
  dataset([
		{'land_use','000','TYPE UNKNOWN'},
		{'land_use','100','RESIDENTIAL (NEC)'},
		{'land_use','102','TOWNHOUSE/ROWHOUSE'},
		{'land_use','103','APARTMENT/HOTEL'},
		{'land_use','106','APARTMENT'},
		{'land_use','109','CABIN'},
		{'land_use','111','COOPERATIVE'},
		{'land_use','112','CONDOMINIUM'},
		{'land_use','113','CONDOMINIUM PROJECT'},
		{'land_use','114','COMMON AREA'},
		{'land_use','115','DUPLEX'},
		{'land_use','116','MID RISE CONDO'},
		{'land_use','117','HIGH RISE CONDO'},
		{'land_use','118','FRAT/SORORITY HOUSE'},
		{'land_use','119','RESIDENCE HALL/DORMITORIES'},
		{'land_use','127','HOTEL'},
		{'land_use','130','RESORT HOTEL'},
		{'land_use','131','MULTI FAMILY 10 UNITS PLUS'},
		{'land_use','132','MULTI FAMILY 10 UNITS LESS'},
		{'land_use','133','MULTI FAMILY DWELLING'},
		{'land_use','134','MIXED COMPLEX'},
		{'land_use','135','MOBILE HOME LOT'},
		{'land_use','136','MOBILE HOME PARK'},
		{'land_use','137','MOBILE HOME PP'},
		{'land_use','138','MOBILE HOME CO OP'},
		{'land_use','142','MOTEL'},
		{'land_use','148','PUD'},
		{'land_use','151','QUADRUPLEX'},
		{'land_use','155','GROUP QUARTERS'},
		{'land_use','156','ORPHANAGE'},
		{'land_use','157','NURSING HOME'},
		{'land_use','160','RURAL HOMESITE'},
		{'land_use','163','SFR'},
		{'land_use','164','TRANSIENT LODGING'},
		{'land_use','165','TRIPLEX'},
		{'land_use','167','TIME SHARE'},
		{'land_use','199','TIME SHARE CONDO'},
		{'land_use','200','COMMERCIAL (NEC)'},
		{'land_use','201','AIR RIGHTS'},
		{'land_use','202','MULTIPLE USES'},
		{'land_use','203','AUTO EQUIPMENT'},
		{'land_use','204','AUTO REPAIR'},
		{'land_use','205','AUTO SALES'},
		{'land_use','206','CONDOTEL'},
		{'land_use','207','SALVAGE IMPRV'},
		{'land_use','208','AUTO WRECKING'},
		{'land_use','209','BUSINESS PARK'},
		{'land_use','210','CARWASH'},
		{'land_use','211','COMMERCIAL BUILDING'},
		{'land_use','212','CEMETERY'},
		{'land_use','213','COMMERCIAL CONDOMINIUM'},
		{'land_use','214','CONVALESCENT HOSPITAL'},
		{'land_use','215','CONVENTION CENTER'},
		{'land_use','217','DEPARTMENT STORE'},
		{'land_use','218','FACILITIES'},
		{'land_use','220','STORE FRANCHISE'},
		{'land_use','221','FAST FOOD FRANCHISE'},
		{'land_use','222','FIN/INSURANCE/REAL ESTATE'},
		{'land_use','223','FINANCIAL BUILDING'},
		{'land_use','225','FUNERAL HOME'},
		{'land_use','226','GARAGE'},
		{'land_use','228','TYPE UNKNOWN'},
		{'land_use','229','GREENHOUSE'},
		{'land_use','230','HOSPITAL'},
		{'land_use','234','KENNEL'},
		{'land_use','235','ANIMAL HOSPITAL/VET'},
		{'land_use','236','LOFT BUILDING'},
		{'land_use','237','MEDICAL BUILDING'},
		{'land_use','238','MEDICAL CONDO'},
		{'land_use','239','LABORATORY'},
		{'land_use','240','LAUNDROMAT'},
		{'land_use','242','NIGHTCLUB'},
		{'land_use','243','BAR'},
		{'land_use','244','OFFICE BUILDING'},
		{'land_use','245','OFFICE & RESIDENTIAL'},
		{'land_use','246','OFFICE & SHOWROOM'},
		{'land_use','247','OFFICE CONDO'},
		{'land_use','248','CONVERTED RESIDENCE'},
		{'land_use','249','MISC IMPROVEMENTS'},
		{'land_use','250','PRE FABRICATED BLDG'},
		{'land_use','251','MISC BUILDING'},
		{'land_use','252','PARKING LOT'},
		{'land_use','255','PARKING STRUCTURE'},
		{'land_use','257','PRODUCE MARKET'},
		{'land_use','258','PUBLIC STORAGE'},
		{'land_use','261','RESTAURANT BUILDING'},
		{'land_use','262','RESTAURANT DRIVE IN'},
		{'land_use','266','SERVICE STATION'},
		{'land_use','268','SERVICE STATION/MARKET'},
		{'land_use','269','MISC COMMERCIAL SERVICES'},
		{'land_use','270','SHOPPING CENTER'},
		{'land_use','271','DEPARTMENT STORE'},
		{'land_use','273','STRIP COMMERCIAL CENTER'},
		{'land_use','276','APPAREL'},
		{'land_use','278','STORE BUILDING'},
		{'land_use','279','STORES & OFFICES'},
		{'land_use','281','STORES & RESIDENTIAL'},
		{'land_use','282','RETAIL TRADE'},
		{'land_use','283','SUPERMARKET'},
		{'land_use','284','FOOD STORES'},
		{'land_use','285','TAVERN'},
		{'land_use','286','WHOLESALE'},
		{'land_use','290','LEASED LAND/BLDG'},
		{'land_use','299','LEASED LAND/BLDG II'},
		{'land_use','300','INDUSTRIAL (NEC)'},
		{'land_use','301','COMMERCIAL/INDUSTRIAL'},
		{'land_use','302','BREWERY'},
		{'land_use','303','BULK PLANT'},
		{'land_use','304','CANNERY'},
		{'land_use','308','CHEMICAL'},
		{'land_use','309','TEXTILE/CLOTHES/CARPET INDUSTRY'},
		{'land_use','310','PAPER & ALLIED INDUSTRY'},
		{'land_use','311','DUMP SITE'},
		{'land_use','312','DURABLE GOODS'},
		{'land_use','313','NON DURABLE GOODS'},
		{'land_use','315','GRAIN ELEVATOR'},
		{'land_use','316','FOOD PROCESSING'},
		{'land_use','318','GRAIN ELEVATOR'},
		{'land_use','320','HEAVY INDUSTRIAL'},
		{'land_use','321','INDUSTRIAL CONDOMINIUM'},
		{'land_use','322','INDUSTRIAL PARK'},
		{'land_use','323','INDUSTRIAL PLANT'},
		{'land_use','324','LIGHT INDUSTRIAL'},
		{'land_use','326','LUMBER YARD'},
		{'land_use','328','LUMBER MILL'},
		{'land_use','331','METAL PRODUCT'},
		{'land_use','333','MINERAL RIGHTS'},
		{'land_use','334','MINERAL PROCESSING'},
		{'land_use','336','MINI WAREHOUSE'},
		{'land_use','338','MULTI TENANT INDUSTRIAL'},
		{'land_use','342','PACKING'},
		{'land_use','344','PETROLEUM'},
		{'land_use','349','MINE/QUARRY'},
		{'land_use','350','PAPER & ALLIED INDUSTRY'},
		{'land_use','352','R&D FACILITY'},
		{'land_use','353','TECHNOLOGICAL INDUSTRY'},
		{'land_use','354','SHIPYARD'},
		{'land_use','356','STOCKYARD'},
		{'land_use','358','STORAGE'},
		{'land_use','361','STORAGE TANKS'},
		{'land_use','364','WAREHOUSE'},
		{'land_use','366','WINERY'},
		{'land_use','399','WINERY II'},
		{'land_use','400','VACANT LAND (NEC)'},
		{'land_use','401','MARSHLAND'},
		{'land_use','410','BARREN LAND'},
		{'land_use','415','COMMERCIAL ACREAGE'},
		{'land_use','420','COMMERCIAL LOT'},
		{'land_use','421','COMMON LAND'},
		{'land_use','425','DESERT'},
		{'land_use','430','AGRICULTURAL LAND'},
		{'land_use','435','INDUSTRIAL ACREAGE'},
		{'land_use','440','INDUSTRIAL LOT'},
		{'land_use','445','MOUNTAINOUS LAND'},
		{'land_use','446','NATURAL RESOURCES'},
		{'land_use','450','MULTI FAMILY ACREAGE'},
		{'land_use','452','MULTI FAMILY LOT'},
		{'land_use','453','OPEN SPACE'},
		{'land_use','454','VACANT MOBILE HOME'},
		{'land_use','455','RECREATIONAL ACREAGE'},
		{'land_use','460','RESIDENTIAL ACREAGE'},
		{'land_use','465','RESIDENTIAL LOT'},
		{'land_use','472','GOLF COURSE'},
		{'land_use','480','WASTE LAND'},
		{'land_use','481','VACANT LMTD/NO DEV POTENTIAL'},
		{'land_use','490','WILDLIFE REFUGE'},
		{'land_use','499','WILDLIFE REFUGE II'},
		{'land_use','500','AGRICULTURAL (NEC)'},
		{'land_use','501','LIVESTOCK'},
		{'land_use','502','NURSERY/HORTICULTURE'},
		{'land_use','505','AGRICULTURAL PLANT'},
		{'land_use','509','RANCH'},
		{'land_use','510','ANIMAL FARM'},
		{'land_use','511','FARMS'},
		{'land_use','512','AVOCADO GROVE'},
		{'land_use','514','CITRUS GROVE'},
		{'land_use','515','DAIRY FARM'},
		{'land_use','520','FALLOW LAND'},
		{'land_use','530','FIELD & SEED'},
		{'land_use','533','FISHERIES'},
		{'land_use','540','FOREST'},
		{'land_use','542','GREENBELT'},
		{'land_use','550','ORCHARD'},
		{'land_use','560','PASTURE'},
		{'land_use','562','POULTRY RANCH'},
		{'land_use','570','TRUCK CROPS'},
		{'land_use','575','VINEYARD'},
		{'land_use','599','VINEYARD II'},
		{'land_use','600','PUBLIC (NEC)'},
		{'land_use','601','TAX EXEMPT'},
		{'land_use','602','STATE PROPERTY'},
		{'land_use','603','COUNTY PROPERTY'},
		{'land_use','604','MUNICIPAL PROPERTY'},
		{'land_use','605','POLICE/FIRE/CIVIL DEFENSE'},
		{'land_use','606','US POSTAL SERVICE'},
		{'land_use','607','EMBASSIES/CHANCERIES'},
		{'land_use','609','CORRECTIONAL FACILITY'},
		{'land_use','610','COMMUNITY CENTER'},
		{'land_use','611','HISTORICAL DISTRICT'},
		{'land_use','614','FEDERAL PROPERTY'},
		{'land_use','615','FEDERAL BUILDING'},
		{'land_use','618','INDIAN RESERVATION'},
		{'land_use','620','ART'},
		{'land_use','630','MILITARY BUILDING'},
		{'land_use','640','POSSESSORY INTEREST'},
		{'land_use','641','TAX ABATEMENT'},
		{'land_use','642','ENTERPRISE ZONE'},
		{'land_use','650','SCHOOL'},
		{'land_use','652','NURSERY SCHOOL'},
		{'land_use','654','HIGH SCHOOL'},
		{'land_use','655','PRIVATE SCHOOL'},
		{'land_use','656','VOCATIONAL/TRADE SCHOOL'},
		{'land_use','658','VOCATIONAL/TRADE SCHOOL'},
		{'land_use','660','EDUCATIONAL SERVICE'},
		{'land_use','664','SEC EDUCATIONAL SCHOOL'},
		{'land_use','665','PUBLIC SCHOOL'},
		{'land_use','670','PUBLIC SERVICE'},
		{'land_use','671','CHARITABLE ORGANIZATION'},
		{'land_use','675','RELIGIOUS'},
		{'land_use','680','UNIVERSITY'},
		{'land_use','684','RADIO FACILITY'},
		{'land_use','690','NATURE FACILITY'},
		{'land_use','699','ZOO'},
		{'land_use','700','RECREATIONAL (NEC)'},
		{'land_use','701','CASINO'},
		{'land_use','703','AMPHITHEATRE'},
		{'land_use','706','AMUSEMENT ARCADE'},
		{'land_use','709','AMUSEMENT PARK'},
		{'land_use','712','AUDITORIUM'},
		{'land_use','721','BOWLING ALLEY'},
		{'land_use','724','BILLIARD HALL'},
		{'land_use','725','CLUB'},
		{'land_use','727','COUNTRY CLUB'},
		{'land_use','728','HEALTH CLUB'},
		{'land_use','733','DANCE HALL'},
		{'land_use','742','GOLF COURSE'},
		{'land_use','745','GOLF RANGE'},
		{'land_use','750','GYMNASIUM'},
		{'land_use','754','LAKE/RIVER/BEACH'},
		{'land_use','755','MARINA FACILITY/RECREATIONAL'},
		{'land_use','757','PARK'},
		{'land_use','766','RACE TRACK'},
		{'land_use','769','RACQUET COURT'},
		{'land_use','770','TENNIS CLUB'},
		{'land_use','775','RV PARK'},
		{'land_use','780','SKATING RINK'},
		{'land_use','784','STADIUM'},
		{'land_use','787','STABLE'},
		{'land_use','790','SWIMMING POOL'},
		{'land_use','795','DRIVE IN THEATER'},
		{'land_use','796','THEATER'},
		{'land_use','797','TOURIST ATTRACTION/EXHIBITS'},
		{'land_use','798','LIBRARY/MUSEUM'},
		{'land_use','800','TRANSPORT (NEC)'},
		{'land_use','801','COMMUNICATION FACILITY'},
		{'land_use','806','AIRCRAFT FACILITY'},
		{'land_use','808','AIRPORT'},
		{'land_use','818','ELECTRICAL FACILITY'},
		{'land_use','830','GAS PRODUCTION'},
		{'land_use','839','MARINE FACILITY/COMMERCIAL'},
		{'land_use','850','PORT/HARBOR'},
		{'land_use','860','RAILROAD FACILITY'},
		{'land_use','863','RECORDING STUDIO'},
		{'land_use','864','RADIO FACILITY'},
		{'land_use','867','EASEMENT'},
		{'land_use','872','TELEPHONE FACILITY'},
		{'land_use','875','TV FACILITY'},
		{'land_use','877','TRANSPORT FACILITY'},
		{'land_use','879','TRUCK TERMINAL'},
		{'land_use','880','UTILITIES'},
		{'land_use','883','WASTE DISPOSAL'},
		{'land_use','885','WELL/WATER'},
		{'land_use','886','WELL/GAS/OIL'},
		{'land_use','899','WELL/GAS/OIL II'},
		{'land_use','998','REAL PROPERTY (NEC)'},
		{'land_use','999','TYPE UNKNOWN'},
		{'deed','D','Release of Mortgage/Deed of Trust'},
		{'deed','F','Final Judgement of Foreclosure'},
		{'deed','G','Grant Deed'},
		{'deed','J','Mechanic Liens / HOA Liens'},
		{'deed','L','Lis Pendens'},
		{'deed','N','Notice of Default'},
		{'deed','Q','Quitclaim'},
		{'deed','R','Release of Lis Pendens'},
		{'deed','S','Assignments and Subordinations'},
		{'deed','T','Deed of Trust'},
		{'deed','U','Foreclosure'},
		{'deed','X','Statistical Exclusion Loans'},
		{'etal','A','ETAL'},
		{'etal','C','ETCON'},
		{'etal','U','ETUX'},
		{'etal','V','ETVIR'},
		{'property','00','Miscellaneous'},
		{'property','10','Single Family Residence / Townhouse'},
		{'property','11','Condominium (residential)'},
		{'property','20','Commercial'},
		{'property','21','Duplex, Triplex, Quadplex'},
		{'property','22','Apartment'},
		{'property','23','Hotel, Motel'},
		{'property','24','Commercial (condominium)'},
		{'property','25','Retail'},
		{'property','26','Service (general public)'},
		{'property','27','Office Building'},
		{'property','28','Warehouse'},
		{'property','29','Financial Institution'},
		{'property','30','Hospital (medical complex, clinic)'},
		{'property','31','Parking'},
		{'property','32','Amusement-Recreation'},
		{'property','50','Industrial'},
		{'property','51','Industrial Light'},
		{'property','52','Industrial Heavy'},
		{'property','53','Transport'},
		{'property','54','Utilities'},
		{'property','70','Agricultural'},
		{'property','80','Vacant'},
		{'property','90','Exempt'},
		{'document','^','NOMINAL'},
		{'document','2','TRUST'},
		{'document','A','ASSIGNMENT DEED'},
		{'document','AA','ASSIGNMENT AND AGREEMENT OF SALE'},
		{'document','AD','ADMINISTRATOR\'S DEED'},
		{'document','AF','AFFIDAVIT'},
		{'document','AG','AGREEMENT OF SALE '},
		{'document','AI','ALL INCLUSIVE DEED OF TRUST'},
		{'document','AJ','ADMINISTRATOR JOINT TENANCY'},
		{'document','AL','ASSGNMT/ASSMPTN OF LEASE/SUBLS'},
		{'document','AM','Amended Mechanic Liens'},
		{'document','AN','ASSIGNMENT DEED'},
		{'document','AP','ASSUMPTION'},
		{'document','AS','ASSIGNMENT OF DEED OF TRUST'},
		{'document','AT','APARTMENT DEED'},
		{'document','AU','AUCTION'},
		{'document','B','BARGAIN & SALE DEED'},
		{'document','BA','BARGAIN & SALE DEED'},
		{'document','BS','BARGAIN & SALE DEED'},
		{'document','C','CONSTRUCTION DEED OF TRUST'},
		{'document','CA','COUNTY DEED'},
		{'document','CD','CORRECTION DEED'},
		{'document','CE','CONSOLIDATION OF MORTGAGE (NY COUNTIES ONLY)'},
		{'document','CL','CONSTRUCTION DEED OF TRUST'},
		{'document','CM','COMMISSIONER\'S DEDED'},
		{'document','CN','CONDOMINIUM DEED'},
		{'document','CO','COMMISSIONERS DEED'},
		{'document','CP','CERTIFICATE OF PURCHASE'},
		{'document','CQ','CORPORATION QUIT CLAIM DEED'},
		{'document','CR','CORPORATE DEED'},
		{'document','CS','CONTRACT OF SALE'},
		{'document','CT','COMMITTEE DEED'},
		{'document','CV','CONVEYANCE DEED'},
		{'document','D','DEED'},
		{'document','DA','DEED OF ASSUMPTION'},
		{'document','DC','CONVEYANCE DEED'},
		{'document','DD','DEED'},
		{'document','DE','DEED OF EXCHANGE'},
		{'document','DI','DEED OF DISTRIBUTION '},
		{'document','DL','DEED IN LIEU OF FORECLOSURE'},
		{'document','DP','DOWN PAYMENT ASSISTANCE LOAN (SC)'},
		{'document','DR','DEED OR RELEASE'},
		{'document','E','EXEMPTION DEED '},
		{'document','EJ','EXECUTOR JOINT TENANT'},
		{'document','EQ','EQUITY OR CREDIT LINE'},
		{'document','EX','EXECUTORS DEED'},
		{'document','F','TRUSTEE DEED'},
		{'document','FD','FORECLOSURE DEED'},
		{'document','FI','FIDUCIARY DEED'},
		{'document','FJ','FINAL JUDGMENT'},
		{'document','FR','FORFEITURE DEED'},
		{'document','FS','FEE SIMPLE DEED'},
		{'document','G','GRANT DEED'},
		{'document','GD','GRANT DEED'},
		{'document','GF','GIFT DEED'},
		{'document','GJ','GUARDIAN JOINT TENANT'},
		{'document','GU','GUARDIAN DEED'},
		{'document','GW','GENERAL WARRANTY DEED'},
		{'document','HR','RELEASE OF HOMEOWNERS ASSOCIATION LIEN (HOA)'},
		{'document','HX','HOMEOWNERS LIEN STATEMENT (HOA)'},
		{'document','I','ALL INCLUSIVE DEED OF TRUST'},
		{'document','IC','INTERCOMPANY DEED TRANSFER'},
		{'document','ID','INTERCOMPANY/INTERFAMILY DEED'},
		{'document','IF','INTERFAMILY DEED TRANSFER'},
		{'document','IM','INDEMNITY DEED OF TRUST'},
		{'document','IN','INSTITUTIONAL DEED'},
		{'document','IS','INTERSPOUSAL DEED TRANSFER'},
		{'document','IT','INTERSPOUSAL DEED TRANSFER'},
		{'document','IV','INDIVIDUAL GRANT DEED'},
		{'document','JD','JOINT TENANCY DEED'},
		{'document','JT','JOINT TENANCY DEED'},
		{'document','LA','LEASE AGREEMENT'},
		{'document','LH','LEASEHOLD DEED'},
		{'document','LM','LIMITED WARRANTY DEED'},
		{'document','LP','LIS PENDENS'},
		{'document','M','MORTGAGE'},
		{'document','MA','MARSHALLS DEED'},
		{'document','MD','MASTERS DEED (SC)'},
		{'document','MF','MORTGAGE FORECLOSURE DEED'},
		{'document','MG','MORTGAGE DEED'},
		{'document','ML','MECHANIC\'S LIEN CONTRACT'},
		{'document','MO','MORTGAGE MODIFICATION AGREEMENT'},
		{'document','MR','MECHANIC\'S LIEN RELEASE'},
		{'document','MX','MECHANICS LIEN'},
		{'document','N','NOTICE OF DEFAULT'},
		{'document','ND','NOTICE OF DEFAULT'},
		{'document','NF','NOTICE OF DEFAULT'},
		{'document','NS','NOTICE OF SHERIFF SALE'},
		{'document','OT','MISCELLANEOUS DOCUMENT'},
		{'document','PA','PUBLIC AUCTION DEED'},
		{'document','PB','PROBATE COURT DEED'},
		{'document','PD','PARTNERSHIP GRANT DEED'},
		{'document','PJ','PERSONAL REP JOINT TENANT'},
		{'document','PN','PATENT (LAND)'},
		{'document','PO','PAY OFF DEED'},
		{'document','PP','APPOINT OF SUBSTITUTE TRUSTEE'},
		{'document','PR','PERSONAL REP\'S DEED'},
		{'document','PT','PUBLIC TRUSTEES DEED'},
		{'document','PV','PRIVATE SALE'},
		{'document','Q','QUIT CLAIM DEED'},
		{'document','QC','QUIT CLAIM DEED'},
		{'document','QD','QUIT CLAIM DEED'},
		{'document','QJ','JOINT TENANT QUIT CLAIM DEED'},
		{'document','R','REVOLVING LINE OF CREDIT '},
		{'document','RC','RECEIVER\'S DEED'},
		{'document','RD','RERECORDED DEED'},
		{'document','RE','CERTIFICATE OF REDEMPTION'},
		{'document','RF','REFEREES DEED'},
		{'document','RL','RELEASE OF LIS PENDENS/NOTICE'},
		{'document','RV','REVOLVING LINE OF CREDIT'},
		{'document','S','ASSIGNMENT OF DEED OF TRUST '},
		{'document','SA','STATE DEED'},
		{'document','SB','SUBORDINATION AGREEMENTS'},
		{'document','SC','CERTIFICATE OF SALE - SHERIFF / MARSHALL'},
		{'document','SD','SHERIFF\'S DEED'},
		{'document','SE','SECURITY DEED'},
		{'document','SJ','SPECIAL WARRANTY DEED JOINT TENANT'},
		{'document','SL','SUB LEASE'},
		{'document','SO','SELLING OFFICER\'S DEED (IL)'},
		{'document','SR','STRAW DEED'},
		{'document','SS','SHERIFF\'S SALE'},
		{'document','ST','SETTLEMENT DEED'},
		{'document','SU','JOINT SURVIVORSHIP / RIGHT OF'},
		{'document','SW','SPECIAL WARRANTY DEED'},
		{'document','T','DEED OF TRUST'},
		{'document','TA','TRUST AGREEMENT'},
		{'document','TC','CERTIFICATE OF TITLE (FL)'},
		{'document','TD','TRUSTEE\'S DEED (FORECLOSURE)'},
		{'document','TE','TRUSTEES DEED'},
		{'document','TJ','TRUSTEES JOINT TENANT'},
		{'document','TL','TRUSTEE\'S JOINT TENANT'},
		{'document','TR','DEED OF TRUST'},
		{'document','TT','TORRENS DOCUMENT'},
		{'document','TU','TRUSTEE\'S DEED (TRANSFER)'},
		{'document','TX','TAX DEED'},
		{'document','U','FORECLOSURE DEED'},
		{'document','UD','UNIT DEED'},
		{'document','V','DEED'},
		{'document','W','WARRANTY DEED'},
		{'document','WD','WARRANTY DEED'},
		{'document','WJ','WARRANTY DEED JOINT TENANT'},
		{'document','X','MULTI-COUNTY/MULTI-STATE'},
		{'document','XD','EXCHANGE DEED'},
		{'document','XL','CANCELLATION OF LEASE IN HI'},
		{'document','XM','PARTIAL RELEASE OF MORTGAGE/DEED OF TRUST'},
		{'document','XP','EXEMPTION DEED'},
		{'document','XX','PARTIAL RELEASE OF MECHANIC\'S LIEN'},
		{'document','Z','NOMINAL'},
		{'document','Â¬','NOMINAL'},
		{'document','NT','NOTICE OF TRUSTEES SALE'}
		],rForeclosureCodes
);