ncf_request := record
	string AccountNumber;
	string Prefix;
	string last;
	string first;
	string Middle;
	string suffix;
	string dob_month;
	string dob_day;
	string dob_year;
	string age;
	string ssn;
	string HouseNumber;
	string StreetName;
	string AptNumber;
	string city;
	string state;
	string zip;
	string zip4;
end;

ncf_response := record
	string AccountNumber;
	string Classification;
	string NarrativeMessageCode_score;
	string RemarksLine1_score;
	string NarrativeMessageCode1;
	string RemarksLine11;
	string NarrativeMessageCode2;
	string RemarksLine12;
	string NarrativeMessageCode3;
	string RemarksLine13;
	string NarrativeMessageCode4;
	string RemarksLine14;
	string AccountNumber_repeated;
	string Prefix;
	string last;
	string first;
	string Middle;
	string suffix;
	string dob_month;
	string dob_day;
	string dob_year;
	string age;
	string ssn;
	string dod_month;
	string dod_day;
	string dod_year;
	string HouseNumber;
	string StreetName;
	string AptNumber;
	string city;
	string state;
	string zip;
	string zip4;
	string YearsAtAddress;
	string MthsAtAddress;
	string CurrentAddress__dtfirstseen__month;
	string CurrentAddress__dtfirstseen__day;
	string CurrentAddress__dtfirstseen__year;
	string CurrentAddress__dtlastseen__month;
	string CurrentAddress__dtlastseen__day;
	string CurrentAddress__dtlastseen__year;
end;

export layout_NCFInsurance := record
	STRING20 table_name;
	STRING10 model_name;
	ncf_request request;
	ncf_response response;
end;