/*** Not to be hand edited (changes will be lost on re-generation) ***/
/*** ECL Interface generated by esdl2ecl version 1.0 from addressattributesreport.xml. ***/
/*===================================================*/

export addressattributesreport := MODULE
			
export t_AddressAttributesReportSearchBy := record
	share.t_Address Address {xpath('Address')};
end;
		
export t_AddressAttributesReportOptions := record (share.t_BaseOption)
	dataset(share.t_StringArrayItem) RequestedAttributeGroups {xpath('RequestedAttributeGroups/Name'), MAXCOUNT(5)};
end;
		
export t_AARAttributes := record (share.t_NameValuePair)
	string3 ConfidenceFactor {xpath('ConfidenceFactor')};
end;
		
export t_AARAttribGroup := record
	string32 Name {xpath('Name')};
	dataset(t_AARAttributes) Attributes {xpath('Attributes/Attribute'), MAXCOUNT(iesp.constants.AddressShell.MaxCountAttributes)};
end;
		
export t_AddressAttributesReportResult := record
	t_AddressAttributesReportSearchBy InputEcho {xpath('InputEcho')};
	dataset(t_AARAttribGroup) AttributeGroups {xpath('AttributeGroups/AttributeGroup'), MAXCOUNT(5)};
end;
		
export t_AddressAttributesReportResponse := record
	share.t_ResponseHeader _Header {xpath('Header')};
	t_AddressAttributesReportResult Result {xpath('Result')};
end;
		
export t_AddressAttributesReportRequest := record (share.t_BaseRequest)
	t_AddressAttributesReportOptions Options {xpath('Options')};
	t_AddressAttributesReportSearchBy SearchBy {xpath('SearchBy')};
end;
		
export t_AddressAttributesReportResponseEx := record
	t_AddressAttributesReportResponse response {xpath('response')};
end;
		

end;

/*** Not to be hand edited (changes will be lost on re-generation) ***/
/*** ECL Interface generated by esdl2ecl version 1.0 from addressattributesreport.xml. ***/
/*===================================================*/

