/*** Not to be hand edited (changes will be lost on re-generation) ***/
/*** ECL Interface generated by esdl2ecl version 1.0 from adminanalytics.xml. ***/
/*===================================================*/

export adminanalytics := MODULE
			
export t_AnalyticsReportOption := record (share.t_BaseOption)
	string ReportNumber {xpath('ReportNumber')}; //values['1','2','3','4','5','6','7','8','9','10','11','12','13','14','15','16','17','18','']
	string SortSequence {xpath('SortSequence')};
	integer ReturnCount {xpath('ReturnCount')};
	integer StartingSequence {xpath('StartingSequence')};
end;
		
export t_AnalyticsReportBy := record
	string Agency {xpath('Agency')};
	string AgencyType {xpath('AgencyType')};
	share.t_Date StartDate {xpath('StartDate')};
	share.t_Date EndDate {xpath('EndDate')};
end;
		
export t_TimePeriod := record
	string DayOfWeek {xpath('DayOfWeek')};
	integer HourOfDay {xpath('HourOfDay')};
	integer MonthOfYear {xpath('MonthOfYear')};
end;
		
export t_SeverityCount := record
	integer Fatal {xpath('Fatal')};
	integer Injury {xpath('Injury')};
	integer PropertyDamage {xpath('PropertyDamage')};
end;
		
export t_TourCount := record
	integer First {xpath('First')};
	integer Second {xpath('Second')};
	integer Third {xpath('Third')};
	integer Unknown {xpath('Unknown')};
end;
		
export t_DayCount := record
	integer Monday {xpath('Monday')};
	integer Tuesday {xpath('Tuesday')};
	integer Wednesday {xpath('Wednesday')};
	integer Thursday {xpath('Thursday')};
	integer Friday {xpath('Friday')};
	integer Saturday {xpath('Saturday')};
	integer Sunday {xpath('Sunday')};
	integer Unknown {xpath('Unknown')};
end;
		
export t_CollisionTypeCount := record
	integer FrontRear {xpath('FrontRear')};
	integer FrontFront {xpath('FrontFront')};
	integer Angle {xpath('Angle')};
	integer SideSwipeSame {xpath('SideSwipeSame')};
	integer SideSwipeOpposite {xpath('SideSwipeOpposite')};
	integer RearSide {xpath('RearSide')};
	integer RearRear {xpath('RearRear')};
	integer Other {xpath('Other')};
	integer Unknown {xpath('Unknown')};
end;
		
export t_AccidentTypeCount := record
	integer Vehicle {xpath('Vehicle')};
	integer Pedestrian {xpath('Pedestrian')};
	integer Bicycle {xpath('Bicycle')};
	integer Motorcycle {xpath('Motorcycle')};
	integer Animal {xpath('Animal')};
	integer Train {xpath('Train')};
	integer Unknown {xpath('Unknown')};
end;
		
export t_AnalyticsRecord := record
	string Agency {xpath('Agency')};
	string Command {xpath('Command')};
	t_TimePeriod TimePeriod {xpath('TimePeriod')};
	string Intersection {xpath('Intersection')};
	integer AccidentCount {xpath('AccidentCount')};
	integer FatalCount {xpath('FatalCount')};
	integer InjuryCount {xpath('InjuryCount')};
	integer PropertyDamageCount {xpath('PropertyDamageCount')};
	integer UnknownSeverity {xpath('UnknownSeverity')};
	t_SeverityCount SeverityCount {xpath('SeverityCount')};
	t_TourCount TourCount {xpath('TourCount')};
	t_DayCount DayCount {xpath('DayCount')};
	t_CollisionTypeCount CollisionTypeCount {xpath('CollisionTypeCount')};
	t_AccidentTypeCount AccidentTypeCount {xpath('AccidentTypeCount')};
end;
		
export t_AdminAnalyticsTotalCounts := record
	integer TotalAccidentCount {xpath('TotalAccidentCount')};
	t_SeverityCount TotalSeverityCount {xpath('TotalSeverityCount')};
	t_TourCount TotalTourCount {xpath('TotalTourCount')};
	t_DayCount TotalDayCount {xpath('TotalDayCount')};
	t_CollisionTypeCount TotalCollisionTypeCount {xpath('TotalCollisionTypeCount')};
	t_AccidentTypeCount TotalAccidentTypeCount {xpath('TotalAccidentTypeCount')};
end;
		
export t_AdminAnalyticsReportResponse := record
	integer TotalCount {xpath('TotalCount')};
	integer ReturnCount {xpath('ReturnCount')};
	string ReportNumber {xpath('ReportNumber')};
	t_AdminAnalyticsTotalCounts TotalCounts {xpath('TotalCounts')};
	dataset(t_AnalyticsRecord) Records {xpath('Records/Record'), MAXCOUNT(iesp.Constants.eCrashMod.MaxAnalyticRecords)};
end;
		
export t_AdminAnalyticsReportRequest := record (share.t_BaseRequest)
	t_AnalyticsReportOption Options {xpath('Options')};
	t_AnalyticsReportBy ReportBy {xpath('ReportBy')};
end;
		
export t_AdminAnalyticsReportResponseEx := record
	t_AdminAnalyticsReportResponse response {xpath('response')};
end;
		

end;

/*** Not to be hand edited (changes will be lost on re-generation) ***/
/*** ECL Interface generated by esdl2ecl version 1.0 from adminanalytics.xml. ***/
/*===================================================*/

