/*** Not to be hand edited (changes will be lost on re-generation) ***/
/*** ECL Interface generated by esdl2ecl version 1.0 from americanmedicalservices.xml. ***/
/*===================================================*/

export americanmedicalservices := MODULE
			
export t_AmericanMedicalServicesProvider := record
	share.t_BusinessIdentity BusinessIds {xpath('BusinessIds')};
	string100 IdValue {xpath('IdValue')};
	string30 ProviderId {xpath('ProviderId')};
	string ProviderSrc {xpath('ProviderSrc')};
	string7 Sex {xpath('Sex')};
	dataset(share.t_StringArrayItem) UniqueIds {xpath('UniqueIds/UniqueId'), MAXCOUNT(iesp.constants.HPR.MAX_UNIQUEIDS)};
	dataset(share.t_Name) Names {xpath('Names/Name'), MAXCOUNT(iesp.constants.HPR.MAX_NAMES)};
	dataset(share.t_StringArrayItem) Languages {xpath('Languages/Language'), MAXCOUNT(iesp.constants.HPR.MAX_LANGUAGES)};
	dataset(share.t_Date) DOBs {xpath('DOBs/DOB'), MAXCOUNT(iesp.constants.HPR.MAX_DOBS)};
	dataset(share.t_StringArrayItem) TaxIds {xpath('TaxIds/TaxId'), MAXCOUNT(iesp.constants.HPR.MAX_TAXIDS)};
	dataset(share.t_StringArrayItem) UPINs {xpath('UPINs/UPIN'), MAXCOUNT(iesp.constants.HPR.MAX_UPINS)};
	dataset(share.t_StringArrayItem) Degrees {xpath('Degrees/Degree'), MAXCOUNT(iesp.constants.HPR.MAX_DEGREES)};
	dataset(share.t_StringArrayItem) NationalProviderIds {xpath('NationalProviderIds/NationalProviderId'), MAXCOUNT(iesp.constants.HPR.MAX_NPIS)};
	string9 NPPESVerified {xpath('NPPESVerified')};
	dataset(healthcare.t_ProviderRelatedEntity) GroupAffiliations {xpath('GroupAffiliations/GroupAffiliation'), MAXCOUNT(iesp.constants.HPR.MAX_GROUPAFFILIATIONS)};
	dataset(healthcare.t_ProviderRelatedEntity) HospitalAffiliations {xpath('HospitalAffiliations/HospitalAffiliation'), MAXCOUNT(iesp.constants.HPR.MAX_HOSPITALAFFILIATIONS)};
	dataset(healthcare.t_ProviderRelatedEntity) Residencies {xpath('Residencies/Residency'), MAXCOUNT(iesp.constants.HPR.MAX_RESIDENCIES)};
	dataset(healthcare.t_MedicalSchool) MedicalSchools {xpath('MedicalSchools/MedicalSchool'), MAXCOUNT(iesp.constants.HPR.MAX_MEDICALSCHOOLS)};
	dataset(healthcare.t_Specialty) Specialties {xpath('Specialties/Specialties'), MAXCOUNT(iesp.constants.HPR.MAX_SPECIALTIES)};
	dataset(healthcare.t_ProviderLicenseInfo) Licenses {xpath('Licenses/License'), MAXCOUNT(iesp.constants.HPR.MAX_LICENSES)};
	dataset(share.t_StringArrayItem) SSNs {xpath('SSNs/SSN'), MAXCOUNT(iesp.constants.HPR.MAX_SSNS)};
	dataset(share.t_StringArrayItem) FEINs {xpath('FEINs/FEIN'), MAXCOUNT(iesp.constants.HPR.MAX_FEINS)};
	dataset(healthcare.t_HealthCareBusinessAddress) BusinessAddresses {xpath('BusinessAddresses/BusinessAddress'), MAXCOUNT(iesp.constants.HPR.MAX_BUSINESSADDRESSES)};
end;
		

end;

/*** Not to be hand edited (changes will be lost on re-generation) ***/
/*** ECL Interface generated by esdl2ecl version 1.0 from americanmedicalservices.xml. ***/
/*===================================================*/

