/*** Not to be hand edited (changes will be lost on re-generation) ***/
/*** ECL Interface generated by esdl2ecl version 1.0 from bair_share.xml. ***/
/*===================================================*/

import iesp;

export bair_share := MODULE
			
export t_BAIRUser := record (iesp.share.t_User)
	string AgencyORI {xpath('AgencyORI')};
end;
		
export t_BAIRGeoBox := record
	string MinLongitude {xpath('MinLongitude')};
	string MaxLongitude {xpath('MaxLongitude')};
	string MinLatitude {xpath('MinLatitude')};
	string MaxLatitude {xpath('MaxLatitude')};
end;
		
export t_BAIRGeoLocation := record
	string Polygon {xpath('Polygon')};
	t_BAIRGeoBox Box {xpath('Box')};
	real4 Radius {xpath('Radius')};
	string Latitude {xpath('Latitude')};
	string Longitude {xpath('Longitude')};
	string PivotLatitude {xpath('PivotLatitude')};
	string PivotLongitude {xpath('PivotLongitude')};
end;
		
export t_BAIRAddressLocation := record
	string StreetAddress {xpath('StreetAddress')};
	string City {xpath('City')};
	string State {xpath('State')};
	string Zip {xpath('Zip')};
end;
		
export t_BAIRLocation := record (t_BAIRGeoLocation)
	t_BAIRAddressLocation Address {xpath('Address')};
end;
		
export t_BAIRNote := record
	string NoteType {xpath('NoteType')};
	string NoteText {xpath('NoteText')};
end;
		
export t_BAIRKeyWord := record
	string1 Option {xpath('Option')};
	string Expression {xpath('Expression')};
end;
		
export t_BAIRDataRelation := record
	boolean Primary {xpath('Primary')};
	boolean Secondary {xpath('Secondary')};
	boolean Relational {xpath('Relational')};
	boolean AllView {xpath('AllView')};
end;
		
export t_BAIRFieldFilter := record
	string Expression {xpath('Expression')};
end;
		
export t_BAIRBaseSearchBy := record
	t_BAIRLocation Location {xpath('Location')};
	iesp.share.t_TimeStamp StartDate {xpath('StartDate')};
	iesp.share.t_TimeStamp EndDate {xpath('EndDate')};
	t_BAIRKeyWord KeyWord {xpath('KeyWord')};
	dataset(iesp.share.t_StringArrayItem) EntityIDs {xpath('EntityIDs/EntityID'), MAXCOUNT(500)};
end;
		
export t_BAIRBaseModeSearchBy := record (t_BAIRBaseSearchBy)
	string Classification {xpath('Classification')};
	string SortingClause {xpath('SortingClause')};
	t_BAIRDataRelation DataRelation {xpath('DataRelation')};
	dataset(t_BAIRFieldFilter) Filters {xpath('Filters/Filter'), MAXCOUNT(iesp.bair_constants.MAX_FILTERS)};
end;
		
export t_BAIRModeContext := record
	string ID {xpath('ID')};
	string Classification {xpath('Classification')};
	string SortingClause {xpath('SortingClause')};
	t_BAIRDataRelation DataRelation {xpath('DataRelation')};
	dataset(t_BAIRFieldFilter) Filters {xpath('Filters/Filter'), MAXCOUNT(iesp.bair_constants.MAX_FILTERS)};
end;
		
export t_BAIRMultiModeSearchBy := record (t_BAIRBaseSearchBy)
	dataset(t_BAIRModeContext) ModeContext {xpath('ModeContext/Mode'), MAXCOUNT(iesp.bair_constants.MAX_MODE_CONTEXT)};
end;
		
export t_BAIRBaseReportBy := record
	dataset(iesp.share.t_StringArrayItem) EntityIDs {xpath('EntityIDs/EntityID'), MAXCOUNT(500)};
end;
		
export t_BAIRBaseOption := record
	boolean BlindLog {xpath('BlindLog')};
end;
		
export t_BAIRBaseSearchOption := record (t_BAIRBaseOption)
	integer ReturnCount {xpath('ReturnCount')};
	integer StartingRecord {xpath('StartingRecord')};
	integer MaxResults {xpath('MaxResults')};
	boolean ReturnAgencyDataOnly {xpath('ReturnAgencyDataOnly')};
end;
		
export t_BAIRBaseSearchResponse := record
	iesp.share.t_ResponseHeader _Header {xpath('Header')};
	integer MatchCount {xpath('MatchCount')};
	integer RecordCount {xpath('RecordCount')};
end;
		
export t_BAIRBaseReportOption := record (t_BAIRBaseOption)
	integer MaxResults {xpath('MaxResults')};
	boolean IncludeNotes {xpath('IncludeNotes')};
end;
		
export t_BAIRPermission := record
	string Key {xpath('Key')};
	string Value {xpath('Value')};
end;
		
export t_BAIRContext := record
	string TransactionId {xpath('TransactionId')};
end;
		
export t_BAIRFieldScore := record
	string Name {xpath('Name')};
	string Score {xpath('Score')};
	string Weight {xpath('Weight')};
end;
		
export t_BAIREIDRecord := record
	string EID {xpath('EID')};
	string _Type {xpath('Type')};
	string Weight {xpath('Weight')};//hidden[internal]
	string Score {xpath('Score')};//hidden[internal]
	dataset(t_BAIRFieldScore) Scores {xpath('Scores/Field'), MAXCOUNT(50)};//hidden[internal]
end;
		
export t_BAIRInputAddress := record
	string StreetAddress {xpath('StreetAddress')};
	string StreetNumber {xpath('StreetNumber')};
	string StreetPreDirection {xpath('StreetPreDirection')};
	string StreetName {xpath('StreetName')};
	string StreetSuffix {xpath('StreetSuffix')};
	string StreetPostDirection {xpath('StreetPostDirection')};
	string UnitDesignation {xpath('UnitDesignation')};
	string UnitNumber {xpath('UnitNumber')};
	string City {xpath('City')};
	string State {xpath('State')};
	string Zip {xpath('Zip')};
end;
		
export t_BAIRBasePSSearchOption := record (t_BAIRBaseSearchOption)
	boolean ReturnScores {xpath('ReturnScores')};//hidden[internal]
	boolean IncludeEvents {xpath('IncludeEvents')};
	boolean IncludeCFS {xpath('IncludeCFS')};
	boolean IncludeCrash {xpath('IncludeCrash')};
	boolean IncludeLPR {xpath('IncludeLPR')};
	boolean IncludeOffenders {xpath('IncludeOffenders')};
end;
		
export t_BAIRBasePSSearchBy := record
	string LexId {xpath('LexId')};
	iesp.share.t_Name Name {xpath('Name')};
	string CompanyName {xpath('CompanyName')};
	t_BAIRInputAddress Address {xpath('Address')};
	real4 Radius {xpath('Radius')}; // Xsd type: double
	string SSN {xpath('SSN')};
	iesp.share.t_Date DOB {xpath('DOB')};
	string DLNumber {xpath('DLNumber')};
	string DLState {xpath('DLState')};
	string VIN {xpath('VIN')};
	string Plate {xpath('Plate')};
	string PhoneNumber {xpath('PhoneNumber')};
	iesp.share.t_Date StartDate {xpath('StartDate')};
	iesp.share.t_Date EndDate {xpath('EndDate')};
end;
		
export t_BAIRAddressExt := record (iesp.share.t_AddressWithGeoLocation)
	string20 AddressType {xpath('AddressType')};
end;
		
export t_BAIRIncidentBase := record (iesp.share.t_GeoLocation)
	string EID {xpath('EID')};
	string ClassCode {xpath('ClassCode')};
	string Class {xpath('Class')};
end;
		
export t_BAIREventRecord := record (t_BAIRIncidentBase)
	string IRNumber {xpath('IRNumber')};
	string Crime {xpath('Crime')};
	iesp.share.t_Address Address {xpath('Address')};
	string Beat {xpath('Beat')};
	string District {xpath('District')};
	iesp.share.t_Date FirstDate {xpath('FirstDate')};
	string Agency {xpath('Agency')};
end;
		
export t_BAIRCFSRecord := record (t_BAIRIncidentBase)
	string EventNumber {xpath('EventNumber')};
	string InitialType {xpath('InitialType')};
	iesp.share.t_Address Address {xpath('Address')};
	iesp.share.t_Date DateReceived {xpath('DateReceived')};
	string Beat {xpath('Beat')};
	string District {xpath('District')};
	string Agency {xpath('Agency')};
end;
		
export t_BAIRLPRRecord := record (t_BAIRIncidentBase)
	string EventNumber {xpath('EventNumber')};
	string PlateNumber {xpath('PlateNumber')};
	iesp.share.t_Date CaptureDate {xpath('CaptureDate')};
	string Agency {xpath('Agency')};
end;
		
export t_BAIRCrashRecord := record (t_BAIRIncidentBase)
	string CaseNumber {xpath('CaseNumber')};
	iesp.share.t_Address Address {xpath('Address')};
	iesp.share.t_Date ReportDate {xpath('ReportDate')};
	string Agency {xpath('Agency')};
end;
		
export t_BAIROffenderRecord := record (t_BAIRIncidentBase)
	string OffenderID {xpath('OffenderID')};
	iesp.share.t_Address Address {xpath('Address')};
	string FirstName {xpath('FirstName')};
	string MiddleName {xpath('MiddleName')};
	string LastName {xpath('LastName')};
	string ChargeOffense {xpath('ChargeOffense')};
	iesp.share.t_Date ExpirationDate {xpath('ExpirationDate')};
	string Agency {xpath('Agency')};
	boolean ImageAvailable {xpath('ImageAvailable')};
end;
		

end;

/*** Not to be hand edited (changes will be lost on re-generation) ***/
/*** ECL Interface generated by esdl2ecl version 1.0 from bair_share.xml. ***/
/*===================================================*/

