/*** Not to be hand edited (changes will be lost on re-generation) ***/
/*** ECL Interface generated by esdl2ecl version 1.0 from bair_vehiclesearch.xml. ***/
/*===================================================*/

import iesp;

export bair_vehiclesearch := MODULE
			
export t_BAIRVehicleSearchOption := record (iesp.bair_share.t_BAIRBaseSearchOption)
	boolean WildcardSearch {xpath('WildcardSearch')};
	boolean DoContainsSearch {xpath('DoContainsSearch')};
	boolean UseTagBlur {xpath('UseTagBlur')};
	boolean ReturnScores {xpath('ReturnScores')};//hidden[internal]
	boolean IncludeEvents {xpath('IncludeEvents')};
	boolean IncludeCrash {xpath('IncludeCrash')};
	boolean IncludeLPR {xpath('IncludeLPR')};
	unsigned MaxVehicleParties {xpath('MaxVehicleParties')};
	unsigned MaxVehicles {xpath('MaxVehicles')};
end;
		
export t_BAIRVehicleSearchBy := record
	string VIN {xpath('VIN')};
	iesp.share.t_Name Name {xpath('Name')};
	string CompanyName {xpath('CompanyName')};
	iesp.bair_share.t_BAIRInputAddress Address {xpath('Address')};
	real4 Radius {xpath('Radius')}; // Xsd type: double
	string SSN {xpath('SSN')};
	string LexId {xpath('LexId')};
	string DLNumber {xpath('DLNumber')};
	string DLState {xpath('DLState')};
	string Plate {xpath('Plate')};
	string Gender {xpath('Gender')};
	iesp.share.t_IntRange Age {xpath('Age')};
	iesp.share.t_IntRange YearMake {xpath('YearMake')};
	dataset(iesp.share.t_StringArrayItem) Makes {xpath('Makes/Make'), MAXCOUNT(iesp.bair_constants.MAX_COUNT_MAKES)};
	dataset(iesp.share.t_StringArrayItem) Models {xpath('Models/Model'), MAXCOUNT(iesp.bair_constants.MAX_COUNT_MODELS)};
	dataset(iesp.share.t_StringArrayItem) Colors {xpath('Colors/Color'), MAXCOUNT(iesp.bair_constants.MAX_COUNT_COLORS)};
	dataset(iesp.share.t_StringArrayItem) MinorColors {xpath('MinorColors/MinorColor'), MAXCOUNT(iesp.bair_constants.MAX_COUNT_MINOR_COLORS)};
end;
		
export t_BAIRVehicleParty := record
	string LexId {xpath('LexId')};
	string MatchedParty {xpath('MatchedParty')};
	iesp.share.t_Name Name {xpath('Name')};
	string CompanyName {xpath('CompanyName')};
	string Gender {xpath('Gender')};
	string SubjectRelation {xpath('SubjectRelation')};
	iesp.share.t_Date DOB {xpath('DOB')};
	string PossibleSSN {xpath('PossibleSSN')};
	string Age {xpath('Age')};
	string LicenseNumber {xpath('LicenseNumber')};
	string LicenseState {xpath('LicenseState')};
	iesp.bair_share.t_BAIRAddressExt Address {xpath('Address')};
	string VehicleID {xpath('VehicleID')};
end;
		
export t_BAIRVehicleInfo := record
	string VehicleID {xpath('VehicleID')};
	string VIN {xpath('VIN')};
	string Plate {xpath('Plate')};
	string PlateState {xpath('PlateState')};
	string Year {xpath('Year')};
	string Make {xpath('Make')};
	string Model {xpath('Model')};
	string Color {xpath('Color')};
	string Style {xpath('Style')};
end;
		
export t_BAIROtherVehicle := record
	t_BAIRVehicleInfo VehicleInfo {xpath('VehicleInfo')};
	dataset(t_BAIRVehicleParty) VehicleParties {xpath('VehicleParties/VehicleParty'), MAXCOUNT(iesp.bair_constants.MAX_PARTIES_PER_INCIDENT)};
end;
		
export t_BAIRVehicleSearchRecord := record
	string EID {xpath('EID')};
	t_BAIRVehicleInfo VehicleInfo {xpath('VehicleInfo')};
	dataset(t_BAIRVehicleParty) VehicleParties {xpath('VehicleParties/VehicleParty'), MAXCOUNT(iesp.bair_constants.MAX_PARTIES_PER_INCIDENT)};
	dataset(t_BAIROtherVehicle) OtherVehicles {xpath('OtherVehicles/OtherVehicle'), MAXCOUNT(iesp.bair_constants.MAX_VEHICLES_PER_INCIDENT)};
	dataset(iesp.bair_share.t_BAIREventRecord) EventRecords {xpath('EventRecords/EventRecord'), MAXCOUNT(iesp.bair_constants.MAX_RECS_PER_MODE)};
	dataset(iesp.bair_share.t_BAIRCrashRecord) CrashRecords {xpath('CrashRecords/CrashRecord'), MAXCOUNT(iesp.bair_constants.MAX_RECS_PER_MODE)};
	dataset(iesp.bair_share.t_BAIRLPRRecord) LPRRecords {xpath('LPRRecords/LPRRecord'), MAXCOUNT(iesp.bair_constants.MAX_RECS_PER_MODE)};
	iesp.bair_share.t_BAIREIDRecord EIDInfo {xpath('EIDInfo')};
end;
		
export t_BAIRVehicleSearchResponse := record
	iesp.share.t_ResponseHeader _Header {xpath('Header')};
	integer RecordCount {xpath('RecordCount')};
	dataset(t_BAIRVehicleSearchRecord) Records {xpath('Records/Record'), MAXCOUNT(iesp.bair_constants.MAX_SEARCH_RECS)};
end;
		
export t_BAIRVehicleSearchRequest := record
	iesp.bair_share.t_BAIRUser User {xpath('User')};
	t_BAIRVehicleSearchOption Options {xpath('Options')};
	t_BAIRVehicleSearchBy SearchBy {xpath('SearchBy')};
	iesp.bair_share.t_BAIRContext BAIRContext {xpath('BAIRContext')};//hidden[ecl_only]
end;
		
export t_BAIRVehicleSearchResponseEx := record
	t_BAIRVehicleSearchResponse response {xpath('response')};
end;
		

end;

/*** Not to be hand edited (changes will be lost on re-generation) ***/
/*** ECL Interface generated by esdl2ecl version 1.0 from bair_vehiclesearch.xml. ***/
/*===================================================*/

