/*** Not to be hand edited (changes will be lost on re-generation) ***/
/*** ECL Interface generated by esdl2ecl version 1.0 from topbusinesssearch.xml. ***/
/*===================================================*/

import iesp;
export bcd_bizsearch := MODULE
				
export t_BizCreditBizSearchResponse := record
	iesp.share.t_ResponseHeader _Header {xpath('Header')};
	integer RecordCount {xpath('RecordCount')};
	dataset(iesp.TopBusinessSearch.t_TopBusinessSearchRecord) Records {xpath('Records/Record'), MAXCOUNT(iesp.Constants.TOPBUSINESS.MAX_COUNT_SEARCH_RESPONSE_RECORDS)};
end;
		
export t_BcdBusinessSearchRequest := record (iesp.share.t_BaseRequest)
	iesp.TopBusinessSearch.t_TopBusinessSearchBy SearchBy {xpath('SearchBy')};
	iesp.TopBusinessSearch.t_TopBusinessSearchOption Options {xpath('Options')};
end;
		
export t_BizCreditBizSearchResponseEx := record
	t_BizCreditBizSearchResponse response {xpath('response')};
end;
		

end;

/*** Not to be hand edited (changes will be lost on re-generation) ***/
/*** ECL Interface generated by esdl2ecl version 1.0 from topbusinesssearch.xml. ***/
/*===================================================*/

