/*** Not to be hand edited (changes will be lost on re-generation) ***/
/*** ECL Interface generated by esdl2ecl version 1.0 from bcdsmallbusinesscombinedreport.xml. ***/
/*===================================================*/

import iesp;

export bcdsmallbusinesscombinedreport := MODULE
			
export t_BcdSmallBusinessBipCombinedReportSearchBy := record (iesp.smallbusinessbipcombinedreport.t_SmallBusinessBipCombinedReportSearchBy)
end;
		
export t_BcdSmallBusinessAnalyticsIDsModelsAttributes := record (iesp.smallbusinessbipcombinedreport.t_SmallBusinessAnalyticsIDsModelsAttributes)
end;
		
export t_BcdBusinessCreditReportRecord := record (iesp.businesscreditreport.t_BusinessCreditReportRecord)
end;
		
export t_BcdSmallBusinessBipCombinedReportOption := record (iesp.smallbusinessbipcombinedreport.t_SmallBusinessBipCombinedReportOption)
end;
		
export t_BcdSmallBusinessCombinedReportResponse := record
	iesp.share.t_ResponseHeader _Header {xpath('Header')};
	unsigned1 BillingHit {xpath('BillingHit')};
	t_BcdSmallBusinessBipCombinedReportSearchBy InputEcho {xpath('InputEcho')};
	t_BcdSmallBusinessAnalyticsIDsModelsAttributes SmallBusinessAnalyticsResults {xpath('SmallBusinessAnalyticsResults')};
	dataset(t_BcdBusinessCreditReportRecord) CreditReportRecords {xpath('CreditReportRecords/Record'), MAXCOUNT(iesp.Constants.TOPBUSINESS.MAX_COUNT_REPORT_RESPONSE_RECORDS)};
end;
		
export t_BcdSmallBusinessCombinedReportRequest := record (iesp.share.t_BaseRequest)
	t_BcdSmallBusinessBipCombinedReportOption Options {xpath('Options')};
	t_BcdSmallBusinessBipCombinedReportSearchBy SearchBy {xpath('SearchBy')};
end;
		
export t_BcdSmallBusinessCombinedReportResponseEx := record
	t_BcdSmallBusinessCombinedReportResponse response {xpath('response')};
end;
		

end;

/*** Not to be hand edited (changes will be lost on re-generation) ***/
/*** ECL Interface generated by esdl2ecl version 1.0 from bcdsmallbusinesscombinedreport.xml. ***/
/*===================================================*/

