/*** Not to be hand edited (changes will be lost on re-generation) ***/
/*** ECL Interface generated by esdl2ecl version 1.0 from employment_verification.xml. ***/
/*===================================================*/

import iesp;

export employment_verification := MODULE
			
export t_VendorSignOnResellerParam := record
	string Customer {xpath('Customer')};
end;
		
export t_VendorSignOnParam := record
	string Language {xpath('Language')};
	string AppId {xpath('AppId')};
	string AppVersion {xpath('AppVersion')};
end;
		
export t_VendorSignOnReq := record
	iesp.share.t_TimeStamp DateClient {xpath('DateClient')};
	string EndUser {xpath('EndUser')};
	string Platform {xpath('Platform')};
	string Intermediary {xpath('Intermediary')};
	boolean IsLNFirstParty {xpath('IsLNFirstParty')};
	t_VendorSignOnResellerParam VendorSignOnResellerParam {xpath('VendorSignOnResellerParam')};
	t_VendorSignOnParam VendorSignOnParam {xpath('VendorSignOnParam')};
end;
		
export t_TransactionPurpose := record
	string Code {xpath('Code')};
	string Message {xpath('Message')};
end;
		
export t_TransactionReq := record
	string TransactionUID {xpath('TransactionUID')};
	t_TransactionPurpose TransactionPurpose {xpath('TransactionPurpose')};//hidden[internal]
end;
		
export t_VerificationOfEmploymentReportBy := record
	iesp.share.t_Name Name {xpath('Name')};
	iesp.share.t_Address Address {xpath('Address')};
	iesp.share.t_Date DOB {xpath('DOB')};
	string11 SSN {xpath('SSN')};
	string EmployerName {xpath('EmployerName')};
	string EmployerCode {xpath('EmployerCode')};
	string EmployeeStatusFilter {xpath('EmployeeStatusFilter')}; //values['A','I','B','']
end;
		
export t_VerificationOfEmploymentReportOption := record (iesp.share.t_BaseReportOption)
	boolean GeneratePDF {xpath('GeneratePDF')};
	boolean IncludeIncome {xpath('IncludeIncome')};
end;
		
export t_VerificationOfEmploymentStatus := record
	string Code {xpath('Code')};
	string Message {xpath('Message')};
end;
		
export t_VerificationOfEmploymentStatusEx := record (t_VerificationOfEmploymentStatus)
	string Severity {xpath('Severity')};
end;
		
export t_VendorSignOnResp := record
	t_VerificationOfEmploymentStatusEx Status {xpath('Status')};
	iesp.share.t_TimeStamp DateTimeServer {xpath('DateTimeServer')};
	string Language {xpath('Language')};
end;
		
export t_SpecialHandling := record
	string DemoHandling {xpath('DemoHandling')};
	string Complimentary {xpath('Complimentary')};
end;
		
export t_ItemizedDisclaimer := record
	string DisclaimerType {xpath('DisclaimerType')};
	string DisclaimerText {xpath('DisclaimerText')};
end;
		
export t_EmployerDisplayInfo := record
	string Language {xpath('Language')};
	string LogoFileName {xpath('LogoFileName')};
	string VoiceFileName {xpath('VoiceFileName')};
end;
		
export t_EmployerDisplay := record
	dataset(t_EmployerDisplayInfo) EmployerDisplayData {xpath('EmployerDisplayData/EmployerDisplayInfo'), MAXCOUNT(10)};
end;
		
export t_VerificationOfEmploymentEmployer := record
	string EmployerCode {xpath('EmployerCode')};
	string Name1 {xpath('Name1')};
	string Name2 {xpath('Name2')};
	iesp.share.t_Address EmployerAddress {xpath('EmployerAddress')};
	string ISOCountryCode {xpath('ISOCountryCode')};
	dataset(iesp.share.t_StringArrayItem) Subsidiaries {xpath('Subsidiaries/Subsidiary'), MAXCOUNT(20)};
	dataset(iesp.share.t_StringArrayItem) EmployerDisclaimers {xpath('EmployerDisclaimers/Disclaimer'), MAXCOUNT(20)};
	dataset(t_ItemizedDisclaimer) ItemizedDisclaimers {xpath('ItemizedDisclaimers/ItemizedDisclaimer'), MAXCOUNT(20)};
	t_EmployerDisplay EmployerDisplay {xpath('EmployerDisplay')};
end;
		
export t_VerificationOfEmploymentWorkLocation := record
	string FedIdNumber {xpath('FedIdNumber')};
	iesp.share.t_Address WorkAddress {xpath('WorkAddress')};
	string StateId {xpath('StateId')};
	string Region {xpath('Region')};
	string ISOCountryCode {xpath('ISOCountryCode')};
end;
		
export t_VerificationOfEmploymentEmployee := record
	string SSN {xpath('SSN')};
	string AlternateId {xpath('AlternateId')};
	iesp.share.t_Name EmployeeName {xpath('EmployeeName')};
	iesp.share.t_Address EmployeeAddress {xpath('EmployeeAddress')};
	string ISOCountryCode {xpath('ISOCountryCode')};
	string EmployeePhone {xpath('EmployeePhone')};
	iesp.share.t_Date DOB {xpath('DOB')};
	string PositionTitle {xpath('PositionTitle')};
	string DivisionCode {xpath('DivisionCode')};
	t_VerificationOfEmploymentWorkLocation WorkLocation {xpath('WorkLocation')};
	t_VerificationOfEmploymentStatus EmployeeStatus {xpath('EmployeeStatus')};
	iesp.share.t_Date DateInfoProvided {xpath('DateInfoProvided')};
	iesp.share.t_Date DateMostRecentHire {xpath('DateMostRecentHire')};
	iesp.share.t_Date DateOriginalHire {xpath('DateOriginalHire')};
	string TotalLengthOfSvc {xpath('TotalLengthOfSvc')};
	iesp.share.t_Date DateEndEmployment {xpath('DateEndEmployment')};
	t_VerificationOfEmploymentStatus TerminationReason {xpath('TerminationReason')};
	string UnionMember {xpath('UnionMember')};
	string UnionAffiliation {xpath('UnionAffiliation')};
	iesp.share.t_Date DateMostRecentPay {xpath('DateMostRecentPay')};
	dataset(iesp.share.t_StringArrayItem) EmployeeDisclaimers {xpath('EmployeeDisclaimers/Disclaimer'), MAXCOUNT(20)};
end;
		
export t_VerificationOfEmploymentBaseComp := record
	t_VerificationOfEmploymentStatus PayFrequency {xpath('PayFrequency')};
	string RateOfPay {xpath('RateOfPay')};
	string AvgHrsWorked {xpath('AvgHrsWorked')};
	t_VerificationOfEmploymentStatus PayPeriodFrequency {xpath('PayPeriodFrequency')};
end;
		
export t_VerificationOfEmploymentAnnualComp := record
	string EmploymentYear {xpath('EmploymentYear')};
	string BaseSalary {xpath('BaseSalary')};
	string Overtime {xpath('Overtime')};
	string Commission {xpath('Commission')};
	string Bonus {xpath('Bonus')};
	string OtherPayment {xpath('OtherPayment')};
	string TotalSalary {xpath('TotalSalary')};
	string RateOfPay {xpath('RateOfPay')};
	iesp.share.t_Date DateInfoProvided {xpath('DateInfoProvided')};
	t_VerificationOfEmploymentStatus PayFrequency {xpath('PayFrequency')};
	t_VerificationOfEmploymentStatus PayPeriodFrequency {xpath('PayPeriodFrequency')};
end;
		
export t_VerificationOfEmploymentCompAdj := record
	iesp.share.t_Date LastDate {xpath('LastDate')};
	string LastAmount {xpath('LastAmount')};
	iesp.share.t_Date NextDate {xpath('NextDate')};
	string NextAmount {xpath('NextAmount')};
end;
		
export t_VerificationOfEmploymentOffWork := record
	iesp.share.t_Date StartDate {xpath('StartDate')};
	iesp.share.t_Date EndDate {xpath('EndDate')};
end;
		
export t_DemoTransaction := record
	dataset(iesp.share.t_StringArrayItem) DemoTypeData {xpath('DemoTypeData/DemoType'), MAXCOUNT(1)};
end;
		
export t_FcraMoreInformation := record
	string Url {xpath('Url')};
	string PhoneNumber {xpath('PhoneNumber')};
end;
		
export t_FcraInfoDataItem := record
	string Code {xpath('Code')};
	string CodeValue {xpath('CodeValue')};
end;
		
export t_FcraActionDetail := record
	string FcraInfoId {xpath('FcraInfoId')};
	string FcraActionTypeCode {xpath('FcraActionTypeCode')};
	string Message {xpath('Message')};
	string ServiceMessage {xpath('ServiceMessage')};
	string ReportingEmployerCode {xpath('ReportingEmployerCode')};
	string TargetEmployerCode {xpath('TargetEmployerCode')};
	string IncidentNumber {xpath('IncidentNumber')};
	t_FcraMoreInformation FcraMoreInformation {xpath('FcraMoreInformation')};
	dataset(t_FcraInfoDataItem) FcraInfoDataItems {xpath('FcraInfoDataItems/FcraInfoDataItem'), MAXCOUNT(15)};
end;
		
export t_FcraStatusAuditInfo := record
	string UserId {xpath('UserId')};
	iesp.share.t_Name UserName {xpath('UserName')};
	string Email {xpath('Email')};
	string DayTimePhone {xpath('DayTimePhone')};
	string EveningPhone {xpath('EveningPhone')};
	iesp.share.t_Address UserAddress {xpath('UserAddress')};
	string ISOCountryCode {xpath('ISOCountryCode')};
	iesp.share.t_TimeStamp DateTimeStamp {xpath('DateTimeStamp')};
	string Comments {xpath('Comments')};
end;
		
export t_FcraInfoDetail := record
	t_FcraActionDetail FcraActionDetail {xpath('FcraActionDetail')};
	t_FcraStatusAuditInfo FcraActionCreated {xpath('FcraActionCreated')};
	t_FcraStatusAuditInfo FcraActionClosed {xpath('FcraActionClosed')};
end;
		
export t_FcraInfo := record
	dataset(t_FcraInfoDetail) FcraInfoDetails {xpath('FcraInfoDetails/FcraInfoDetail'), MAXCOUNT(15)};
end;
		
export t_VerificationOfEmploymentRecord := record
	iesp.share.t_TimeStamp TransactionDate {xpath('TransactionDate')};
	t_VerificationOfEmploymentEmployer Employer {xpath('Employer')};
	t_VerificationOfEmploymentEmployee Employee {xpath('Employee')};
	t_VerificationOfEmploymentBaseComp BaseCompensation {xpath('BaseCompensation')};
	dataset(t_VerificationOfEmploymentAnnualComp) AnnualCompData {xpath('AnnualCompData/VerificationOfEmploymentAnnualComp'), MAXCOUNT(15)};
	t_VerificationOfEmploymentCompAdj CompensationAdj {xpath('CompensationAdj')};
	t_VerificationOfEmploymentOffWork OffWorkPeriod {xpath('OffWorkPeriod')};
	string Completeness {xpath('Completeness')};
	string ServerRespId {xpath('ServerRespId')};
	t_DemoTransaction DemoTransaction {xpath('DemoTransaction')};
	t_FcraInfo FcraInfo {xpath('FcraInfo')};
end;
		
export t_VerificationOfEmploymentSelectRecord := record
	dataset(t_VerificationOfEmploymentRecord) VerificationOfEmploymentRecordData {xpath('VerificationOfEmploymentRecordData/VerificationOfEmploymentRecord'), MAXCOUNT(20)};
end;
		
export t_VerificationOfEmploymentResp := record
	string TransactionUID {xpath('TransactionUID')};
	t_VerificationOfEmploymentStatusEx Status {xpath('Status')};
	string MasterServerId {xpath('MasterServerId')};
	t_TransactionPurpose TransactionPurpose {xpath('TransactionPurpose')};
	t_SpecialHandling SpecialHandling {xpath('SpecialHandling')};
	t_VerificationOfEmploymentSelectRecord VerificationOfEmploymentSelectRecord {xpath('VerificationOfEmploymentSelectRecord')};
end;
		
export t_VerificationOfEmploymentReportRecord := record
	string12 UniqueId {xpath('UniqueId')};
	t_VendorSignOnResp SignonResp {xpath('SignonResp')};
	t_VerificationOfEmploymentResp VerificationOfEmploymentResp {xpath('VerificationOfEmploymentResp')};
	string Pdf {xpath('Pdf')};
end;
		

end;

/*** Not to be hand edited (changes will be lost on re-generation) ***/
/*** ECL Interface generated by esdl2ecl version 1.0 from employment_verification.xml. ***/
/*===================================================*/