/*** Not to be hand edited (changes will be lost on re-generation) ***/
/*** ECL Interface generated by esdl2ecl version 1.0 from equifax_sts.xml. ***/
/*===================================================*/

import iesp;

export equifax_sts := MODULE
			
export t_EquifaxSTSRequestOptions := record (iesp.share.t_BaseOption)
	boolean IncludeMLAInfo {xpath('IncludeMLAInfo')};
end;
		
export t_EqSTSAddress := record
	string HouseNumber {xpath('HouseNumber')};
	string Quadrant {xpath('Quadrant')};
	string StreetName {xpath('StreetName')};
	string StreetType {xpath('StreetType')};
	string ApartmentNumber {xpath('ApartmentNumber')};
	string City {xpath('City')};
	string2 State {xpath('State')};
	string9 Zip {xpath('Zip')};
end;
		
export t_EqSTSCredentials := record
	string CustomerNumber {xpath('CustomerNumber')};
	string CustomerCode {xpath('CustomerCode')};
	string SecurityCode {xpath('SecurityCode')};
end;
		
export t_EqSTSName := record
	string Prefix {xpath('Prefix')};
	string First {xpath('First')};
	string Middle {xpath('Middle')};
	string Last {xpath('Last')};
	string Suffix {xpath('Suffix')};
end;
		
export t_EqSTSEndUser := record
	string CompanyName {xpath('CompanyName')};
	string PermisablePurpose {xpath('PermisablePurpose')};
end;
		
export t_EqSTSModel := record
	string ModelNumber {xpath('ModelNumber')};
	string Field1 {xpath('Field1')};
	string Field2 {xpath('Field2')};
end;
		
export t_EquifaxSTSSearchBy := record
	t_EqSTSName Name {xpath('Name')};
	t_EqSTSAddress Address {xpath('Address')};
	string SSN {xpath('SSN')};
	iesp.share.t_Date2 DOB {xpath('DOB')};
	t_EqSTSEndUser EndUser {xpath('EndUser')};
	dataset(t_EqSTSModel) Models {xpath('Models/Model'), MAXCOUNT(1)};
end;
		
export t_EquifaxSTSRequest := record (iesp.share.t_BaseRequest)
	iesp.share.t_GatewayParams GatewayParams {xpath('GatewayParams')};
	t_EquifaxSTSRequestOptions Options {xpath('Options')};
	t_EqSTSCredentials EquifaxCredentials {xpath('EquifaxCredentials')};
	t_EquifaxSTSSearchBy SearchBy {xpath('SearchBy')};
end;
		
export t_EquifaxSTSResponseEx := record
	iesp.equifax_acrofile.t_EquifaxAcrofileResponse Response {xpath('Response')};
end;
		

end;

/*** Not to be hand edited (changes will be lost on re-generation) ***/
/*** ECL Interface generated by esdl2ecl version 1.0 from equifax_sts.xml. ***/
/*===================================================*/

