/*** Not to be hand edited (changes will be lost on re-generation) ***/
/*** ECL Interface generated by esdl2ecl version 1.0 from fcclicense.xml. ***/
/*===================================================*/

export fcclicense := MODULE
			
export t_FCCLicenseSearchBy := record (share.t_BaseSearchBy)
	share.t_Name Name {xpath('Name')};
	string CompanyName {xpath('CompanyName')};
	share.t_Address Address {xpath('Address')};
	string PhoneNumber {xpath('PhoneNumber')};
end;
		
export t_FCCLicenseSearchOption := record (share.t_BaseSearchOption)
	integer ReturnCount {xpath('ReturnCount')};
	integer StartingRecord {xpath('StartingRecord')};
	boolean UsePhonetics {xpath('UsePhonetics')};
	boolean UseNicknames {xpath('UseNicknames')};
	boolean IncludeAlsoFound {xpath('IncludeAlsoFound')};
end;
		
export t_FCCLicenseSearchRecord := record
	boolean AlsoFound {xpath('AlsoFound')};
	string UniqueId {xpath('UniqueId')};
	string BusinessId {xpath('BusinessId')};
	string FCCIdNumber {xpath('FCCIdNumber')};
	string LicenseeName {xpath('LicenseeName')};
	string DBAName {xpath('DBAName')};
	string LicenseesAttentionLine {xpath('LicenseesAttentionLine')};
	share.t_Address Address {xpath('Address')};
	share.t_Name NameAttention {xpath('NameAttention')};
	string255 ExternalKey {xpath('ExternalKey')};
end;
		
export t_FCCLicenseSearchResponse := record
	share.t_ResponseHeader _Header {xpath('Header')};
	integer RecordCount {xpath('RecordCount')};
	dataset(t_FCCLicenseSearchRecord) Records {xpath('Records/Record'), MAXCOUNT(1)};
end;
		
export t_FCCLicenseReportBy := record
	string FCCIdNumber {xpath('FCCIdNumber')};
	string UniqueId {xpath('UniqueId')};
	string CompanyId {xpath('CompanyId')};
end;
		
export t_FCCLicenseReportOption := record (share.t_BaseReportOption)
end;
		
export t_LicenseeInfo := record
	string Name {xpath('Name')};
	string Phone {xpath('Phone')};
	share.t_Address Address {xpath('Address')};
	share.t_Address ContactFirmAddress {xpath('ContactFirmAddress')};
	string ContactFirmPhone {xpath('ContactFirmPhone')};
	string ContactFirmFax {xpath('ContactFirmFax')};
	share.t_Name AttentionName {xpath('AttentionName')};
	string AttentionLine {xpath('AttentionLine')};
	string FirmPreparingApplication {xpath('FirmPreparingApplication')};
end;
		
export t_LicenseInfo := record
	string CallsignOfLicense {xpath('CallsignOfLicense')};
	string LicenseType {xpath('LicenseType')};
	string FileNumber {xpath('FileNumber')};
	string _Service {xpath('Service')};
	share.t_Date FCCLicenseReviedAppDate {xpath('FCCLicenseReviedAppDate')};
	share.t_Date LicenseIssuedDate {xpath('LicenseIssuedDate')};
	share.t_Date LicenseExpiredDate {xpath('LicenseExpiredDate')};
	share.t_Date LastChangeDate {xpath('LastChangeDate')};
	string LastChangeType {xpath('LastChangeType')};
	string PendingOrGranted {xpath('PendingOrGranted')};
	string PagingLicenseStatus {xpath('PagingLicenseStatus')};
end;
		
export t_AntenaSiteInfo := record
	share.t_Address Address {xpath('Address')};
	string TransmitrsAntenna_height {xpath('TransmitrsAntenna_height')};
	string TransmitrsHeightAbvAvgTerrain {xpath('TransmitrsHeightAbvAvgTerrain')};
	string TransmitrsheightAbvGrndLvl {xpath('TransmitrsheightAbvGrndLvl')};
	string ControlPointForTheSystem {xpath('ControlPointForTheSystem')};
	string Latitude {xpath('Latitude')};
	string Longitude {xpath('Longitude')};
end;
		
export t_FrequencyInfo := record
	string FrequencyMhz {xpath('FrequencyMhz')};
	string ClassOfStation {xpath('ClassOfStation')};
	string PowerOfFrequency {xpath('PowerOfFrequency')};
	string EmissionsCodes {xpath('EmissionsCodes')};
	string NmbrOfUnitsAuthorizedOnFreq {xpath('NmbrOfUnitsAuthorizedOnFreq')};
	string EffectiveRadiatedPower {xpath('EffectiveRadiatedPower')};
	string FrequencyCoordinationNumber {xpath('FrequencyCoordinationNumber')};
end;
		
export t_FCCLicenseReportRecord := record
	share.t_BusinessIdentity BusinessIds {xpath('BusinessIds')};
	string100 IdValue {xpath('IdValue')};
	string FCCIdNumber {xpath('FCCIdNumber')};
	t_LicenseeInfo LicenseeInfo {xpath('LicenseeInfo')};
	t_LicenseInfo LicenseInfo {xpath('LicenseInfo')};
	t_AntenaSiteInfo AntenaSiteInfo {xpath('AntenaSiteInfo')};
	t_FrequencyInfo FrequencyInfo {xpath('FrequencyInfo')};
end;
		
export t_FCCLicenseReportResponse := record
	share.t_ResponseHeader _Header {xpath('Header')};
	integer RecordCount {xpath('RecordCount')};
	dataset(t_FCCLicenseReportRecord) FCCLicenseReportRecords {xpath('FCCLicenseReportRecords/FCCLicenseReportRecord'), MAXCOUNT(1)};
end;
		
export t_FCCLicenseSearchRequest := record (share.t_BaseRequest)
	t_FCCLicenseSearchBy SearchBy {xpath('SearchBy')};
	t_FCCLicenseSearchOption Options {xpath('Options')};
end;
		
export t_FCCLicenseReportRequest := record (share.t_BaseRequest)
	t_FCCLicenseReportBy ReportBy {xpath('ReportBy')};
	t_FCCLicenseReportOption Options {xpath('Options')};
end;
		
export t_FCCLicenseSearchResponseEx := record
	t_FCCLicenseSearchResponse response {xpath('response')};
end;
		
export t_FCCLicenseReportResponseEx := record
	t_FCCLicenseReportResponse response {xpath('response')};
end;
		

end;

/*** Not to be hand edited (changes will be lost on re-generation) ***/
/*** ECL Interface generated by esdl2ecl version 1.0 from fcclicense.xml. ***/
/*===================================================*/

