/*** Not to be hand edited (changes will be lost on re-generation) ***/
/*** ECL Interface generated by esdl2ecl version 1.0 from franchise.xml. ***/
/*===================================================*/

export franchise := MODULE
			
export t_FranchiseRecord := record
	share.t_BusinessIdentity BusinessIds {xpath('BusinessIds')};
	string100 IdValue {xpath('IdValue')};
	string10 FranchiseeId {xpath('FranchiseeId')};
	string75 Franchise {xpath('Franchise')};
	string75 CompanyName {xpath('CompanyName')};
	string10 Phone {xpath('Phone')};
	string10 SecondaryPhone {xpath('SecondaryPhone')};
	string75 Email {xpath('Email')};
	string75 URL {xpath('URL')};
	string25 UnitExplanation {xpath('UnitExplanation')};
	string25 _Relationship {xpath('_Relationship')};
	integer NumberFranchises {xpath('NumberFranchises')};
	string30 Industry {xpath('Industry')};
	string30 IndustryType {xpath('IndustryType')};
	string35 Sector {xpath('Sector')};
	string4 SicCode {xpath('SicCode')};
	share.t_Address Address {xpath('Address')};
	share.t_Date FranchiseStartDate {xpath('FranchiseStartDate')};
	share.t_Date LastUpdate {xpath('LastUpdate')};
	dataset(share.t_Name) Executives {xpath('Executives/Name'), MAXCOUNT(iesp.Constants.FRANDX.MAX_EXECUTIVES)};
end;
		

end;

/*** Not to be hand edited (changes will be lost on re-generation) ***/
/*** ECL Interface generated by esdl2ecl version 1.0 from franchise.xml. ***/
/*===================================================*/

