/*** Not to be hand edited (changes will be lost on re-generation) ***/
/*** ECL Interface generated by esdl2ecl version 1.0 from gateway_news.xml. ***/
/*===================================================*/

export gateway_news := MODULE
			
export t_NewsOptions := record (share.t_BaseOption)
end;
		
export t_UserInformation := record
	string Locale {xpath('Locale')};
end;
		
export t_NewsAuthenticateResponse := record
	share.t_ResponseHeader _Header {xpath('Header')};
	string SecurityToken {xpath('SecurityToken')};
	string Expiration {xpath('Expiration')};
	t_UserInformation UserInfo {xpath('UserInfo')};
end;
		
export t_NewsSourceInfo := record
	dataset(share.t_StringArrayItem) SourceIdList {xpath('SourceIdList/SourceId'), MAXCOUNT(1)};
	string SecuredSourceId {xpath('SecuredSourceId')};
end;
		
export t_NewsDateRestriction := record
	string StartDate {xpath('StartDate')};
	string EndDate {xpath('EndDate')};
end;
		
export t_NewsSearchOptions := record
	t_NewsDateRestriction DateRestriction {xpath('DateRestriction')};
	string SearchMethod {xpath('SearchMethod')};
	string SortOrder {xpath('SortOrder')};
	boolean IgnoreCommonWords {xpath('IgnoreCommonWords')};
end;
		
export t_NewsDocumentRange := record
	integer Begin {xpath('Begin')};
	integer _End {xpath('End')}; // hand edited /end is not valid here ... esp will need updating.
end;
		
export t_NewsRetrievalOptions := record
	string DocumentView {xpath('DocumentView')};
	string DocumentMarkup {xpath('DocumentMarkup')};
	t_NewsDocumentRange DocumentRange {xpath('DocumentRange')};
end;
		
export t_NewsDocContainer := record
	string DocumentId {xpath('DocumentId')};
	string Document {xpath('Document')};
end;
		
export t_NewsSearchResponse := record
	share.t_ResponseHeader _Header {xpath('Header')};
	string SearchId {xpath('SearchId')};
	integer DocsFound {xpath('DocsFound')};
	dataset(t_NewsDocContainer) DocContainerList {xpath('DocContainerList/DocContainer'), MAXCOUNT(1)};
end;
		
export t_NewsGetDocsByRangeResponse := record
	share.t_ResponseHeader _Header {xpath('Header')};
	dataset(t_NewsDocContainer) DocContainerList {xpath('DocContainerList/DocContainer'), MAXCOUNT(1)};
end;
		
export t_NewsDocIdRetrievalOptions := record
	string DocumentView {xpath('DocumentView')};
	string DocumentMarkup {xpath('DocumentMarkup')};
	boolean IncludeExtendedOutput {xpath('IncludeExtendedOutput')};
end;
		
export t_NewsGetDocsByDocIdResponse := record
	share.t_ResponseHeader _Header {xpath('Header')};
	dataset(t_NewsDocContainer) DocContainerList {xpath('DocContainerList/DocContainer'), MAXCOUNT(1)};
end;
		
export t_NewsAuthenticateRequest := record (share.t_BaseRequest)
	t_NewsOptions Options {xpath('Options')};
end;
		
export t_NewsSearchRequest := record (share.t_BaseRequest)
	t_NewsOptions Options {xpath('Options')};
	t_NewsSourceInfo SourceInfo {xpath('SourceInfo')};
	string SecurityToken {xpath('SecurityToken')};
	string Query {xpath('Query')};
	string ProjectId {xpath('ProjectId')};
	t_NewsSearchOptions SearchOptions {xpath('SearchOptions')};
	t_NewsRetrievalOptions RetrievalOptions {xpath('RetrievalOptions')};
end;
		
export t_NewsGetDocsByRangeRequest := record (share.t_BaseRequest)
	t_NewsOptions Options {xpath('Options')};
	string SecurityToken {xpath('SecurityToken')};
	string SearchId {xpath('SearchId')};
	string ClassId {xpath('ClassId')};
	t_NewsRetrievalOptions RetrievalOptions {xpath('RetrievalOptions')};
end;
		
export t_NewsGetDocsByDocIdRequest := record (share.t_BaseRequest)
	t_NewsOptions Options {xpath('Options')};
	string SecurityToken {xpath('SecurityToken')};
	dataset(share.t_StringArrayItem) DocIdList {xpath('DocIdList/DocId'), MAXCOUNT(1)};
	t_NewsDocIdRetrievalOptions RetrievalOptions {xpath('RetrievalOptions')};
end;
		
export t_NewsAuthenticateResponseEx := record
	t_NewsAuthenticateResponse response {xpath('response')};
end;
		
export t_NewsSearchResponseEx := record
	t_NewsSearchResponse response {xpath('response')};
end;
		
export t_NewsGetDocsByRangeResponseEx := record
	t_NewsGetDocsByRangeResponse response {xpath('response')};
end;
		
export t_NewsGetDocsByDocIdResponseEx := record
	t_NewsGetDocsByDocIdResponse response {xpath('response')};
end;
		

end;

/*** Not to be hand edited (changes will be lost on re-generation) ***/
/*** ECL Interface generated by esdl2ecl version 1.0 from gateway_news.xml. ***/
/*===================================================*/

