/*** Not to be hand edited (changes will be lost on re-generation) ***/
/*** ECL Interface generated by esdl2ecl version 1.0 from healthcare_share.xml. ***/
/*===================================================*/


export healthcare_share := MODULE
			
export t_HCProfessionalName := record (share.t_Name)
	string15 ProfessionalSuffix {xpath('ProfessionalSuffix')};
end;
		
export t_HCExtendedAddress := record (share.t_Address)
	string60 AddressType {xpath('AddressType')};
	string20 Key {xpath('Key')};
	string2 RecordType {xpath('RecordType')};
	string9 POBox {xpath('POBox')};
	string9 RRNumber {xpath('RRNumber')};
	string10 NPSR {xpath('NPSR')};
	string6 ACEStatCode {xpath('ACEStatCode')};
	string6 ErrorCode {xpath('ErrorCode')};
	string5 FIPSCode {xpath('FIPSCode')};
	string10 CBSACode {xpath('CBSACode')};
	string10 CBSAType {xpath('CBSAType')};
	string1 RDI {xpath('RDI')};
	share.t_Date DateFirstSeen {xpath('DateFirstSeen')};
	share.t_Date DateLastSeen {xpath('DateLastSeen')};
end;
		
export t_HCExtendedAddressPhoneFax := record (t_HCExtendedAddress)
	string10 Phone {xpath('Phone')};
	string11 PhoneStatus {xpath('PhoneStatus')};
	string10 Fax {xpath('Fax')};
	string11 FaxStatus {xpath('FaxStatus')};
end;
		
export t_HCReferenceID := record
	string3 Qualifier {xpath('Qualifier')};
	string80 Identifier {xpath('Identifier')};
end;
		
export t_HCAmountInfo := record
	string3 Qualifier {xpath('Qualifier')};
	decimal14_2 Value {xpath('Value')}; // Xsd type: double
end;
		
export t_HCAdjustmentInfo := record
	string20 PayerEDIID {xpath('PayerEDIID')};
	string3 GroupCode {xpath('GroupCode')};
	string3 ReasonCode {xpath('ReasonCode')};
	decimal14_2 Amount {xpath('Amount')}; // Xsd type: double
end;
		
export t_HCDateInfo := record
	string3 Qualifier {xpath('Qualifier')};
	share.t_Date From {xpath('From')};
	share.t_Date To {xpath('To')};
end;
		
export t_HCPayerInfo := record
	string80 PayerName {xpath('PayerName')};
	string20 PayerEDIID {xpath('PayerEDIID')};
	string PayerOrder {xpath('PayerOrder')}; //values['P','S','T','']
	share.t_Address PayerAddress {xpath('PayerAddress')};
	dataset(t_HCReferenceID) RefIDs {xpath('RefIDs/RefID'), MAXCOUNT(iesp.constants.HC_ClaimsCleanse.Max_RefID_Cnt)};
end;
		
export t_HCNDCInfo := record
	string11 Code {xpath('Code')};
	decimal12_4 Quantity {xpath('Quantity')}; // Xsd type: double
	string2 UnitOfMeasurement {xpath('UnitOfMeasurement')};
end;
		
export t_HCDMEInfo := record
	decimal14_2 AmountRental {xpath('AmountRental')}; // Xsd type: double
	decimal14_2 AmountPurchase {xpath('AmountPurchase')}; // Xsd type: double
	integer LengthOfMedicalNecessity {xpath('LengthOfMedicalNecessity')};
	integer RentalUnitPriceIndicator {xpath('RentalUnitPriceIndicator')};
end;
		
export t_HCServiceInfo := record
	unsigned LineNumber {xpath('LineNumber')};
	string6 ProcedureCode {xpath('ProcedureCode')};
	string80 ProcedureDescription {xpath('ProcedureDescription')};
	string4 RevenueCode {xpath('RevenueCode')};
	dataset(share.t_StringArrayItem) Modifiers {xpath('Modifiers/Modifier'), MAXCOUNT(iesp.constants.HC_ClaimsCleanse.Max_Modifiers_Cnt)};
	integer UnitQuantity {xpath('UnitQuantity')};
	decimal14_2 AmountBilled {xpath('AmountBilled')}; // Xsd type: double
	decimal14_2 AmountNotCovered {xpath('AmountNotCovered')}; // Xsd type: double
	dataset(share.t_StringArrayItem) Diagnoses {xpath('Diagnoses/Diagnosis'), MAXCOUNT(iesp.constants.HC_ClaimsCleanse.Max_Diagnosis_Cnt)};
	share.t_Date ServiceFromDate {xpath('ServiceFromDate')};
	share.t_Date ServiceToDate {xpath('ServiceToDate')};
	t_HCNDCInfo NationalDrugCode {xpath('NationalDrugCode')};
	t_HCDMEInfo DurableMedicalEquipment {xpath('DurableMedicalEquipment')};
	dataset(t_HCAmountInfo) Amounts {xpath('Amounts/Amount'), MAXCOUNT(iesp.constants.HC_ClaimsCleanse.Max_Amount_Cnt)};
	dataset(t_HCAdjustmentInfo) Adjustments {xpath('Adjustments/Adjustment'), MAXCOUNT(iesp.constants.HC_ClaimsCleanse.Max_Adjustment_Cnt)};
	dataset(t_HCReferenceID) RefIDs {xpath('RefIDs/RefID'), MAXCOUNT(iesp.constants.HC_ClaimsCleanse.Max_RefID_Cnt)};
	dataset(t_HCDateInfo) Dates {xpath('Dates/Date'), MAXCOUNT(iesp.constants.HC_ClaimsCleanse.Max_Date_Cnt)};
end;
		
export t_HCClaimContact := record
	t_HCProfessionalName Name {xpath('Name')};
	string10 Phone {xpath('Phone')};
	string10 Fax {xpath('Fax')};
	string100 Email {xpath('Email')};
end;
		
export t_HCClaimInfo := record
	t_HCClaimContact BillingProviderContactPerson {xpath('BillingProviderContactPerson')};
	decimal14_2 TotalClaimChargeAmount {xpath('TotalClaimChargeAmount')}; // Xsd type: double
	string2 PlaceOfService {xpath('PlaceOfService')};
	string1 PlanParticipationCode {xpath('PlanParticipationCode')};
	share.t_Date AdmissionDate {xpath('AdmissionDate')};
	string2 AdmissionTimeHH {xpath('AdmissionTimeHH')};
	string10 AdmissionTypeCode {xpath('AdmissionTypeCode')};
	string10 AdmissionSourceCode {xpath('AdmissionSourceCode')};
	string10 PatientStatusCode {xpath('PatientStatusCode')};
	string80 ValueAddedNetworkTraceNumber {xpath('ValueAddedNetworkTraceNumber')};
	string10 AmbulanceTransportReasonCode {xpath('AmbulanceTransportReasonCode')};
	string10 PrincipalDiagnosisCode {xpath('PrincipalDiagnosisCode')};
	string10 AdmittingDiagnosisCode {xpath('AdmittingDiagnosisCode')};
	dataset(share.t_StringArrayItem) OtherDiagnosisCodes {xpath('OtherDiagnosisCodes/OtherDiagnosisCode'), MAXCOUNT(iesp.constants.HC_ClaimsCleanse.Max_ClmDiagnosis_Cnt)};
	dataset(share.t_StringArrayItem) VisitReasons {xpath('VisitReasons/VisitReason'), MAXCOUNT(iesp.constants.HC_ClaimsCleanse.Max_VisitReason_Cnt)};
	string10 PresentOnAdmissionIndicator {xpath('PresentOnAdmissionIndicator')};
	string10 DiagnosisRelatedGroupCode {xpath('DiagnosisRelatedGroupCode')};
	dataset(share.t_StringArrayItem) TreatmentCodes {xpath('TreatmentCodes/TreatmentCode'), MAXCOUNT(iesp.constants.HC_ClaimsCleanse.Max_TreatmentCode_Cnt)};
	t_HCPayerInfo Payer {xpath('Payer')};
	dataset(t_HCServiceInfo) Services {xpath('Services/Service'), MAXCOUNT(iesp.constants.HC_ClaimsCleanse.Max_Service_Cnt)};
	dataset(t_HCPayerInfo) OtherPayers {xpath('OtherPayers/OtherPayer'), MAXCOUNT(iesp.constants.HC_ClaimsCleanse.Max_OtherPayer_Cnt)};
	dataset(t_HCAmountInfo) Amounts {xpath('Amounts/Amount'), MAXCOUNT(iesp.constants.HC_ClaimsCleanse.Max_Amount_Cnt)};
	dataset(t_HCAdjustmentInfo) Adjustments {xpath('Adjustments/Adjustment'), MAXCOUNT(iesp.constants.HC_ClaimsCleanse.Max_Adjustment_Cnt)};
	dataset(t_HCReferenceID) RefIDs {xpath('RefIDs/RefID'), MAXCOUNT(iesp.constants.HC_ClaimsCleanse.Max_RefID_Cnt)};
	dataset(t_HCDateInfo) Dates {xpath('Dates/Date'), MAXCOUNT(iesp.constants.HC_ClaimsCleanse.Max_Date_Cnt)};
end;
		
export t_HCProviderInfo := record
	string _Type {xpath('Type')}; //values['','A','B','R','S','Q','O','T','P','']
	string120 Company {xpath('Company')};
	t_HCProfessionalName Name {xpath('Name')};
	share.t_Address Address {xpath('Address')};
	string10 Phone {xpath('Phone')};
	string10 Fax {xpath('Fax')};
	dataset(share.t_StringArrayItem) Taxonomies {xpath('Taxonomies/Taxonomy'), MAXCOUNT(5)};
	string10 NPINumber {xpath('NPINumber')};
	string6 UPIN {xpath('UPIN')};
	string12 LicenseNumber {xpath('LicenseNumber')};
	string2 LicenseState {xpath('LicenseState')};
	string5 LicenseType {xpath('LicenseType')};
	string11 FEIN {xpath('FEIN')};
	string9 SSN {xpath('SSN')};
	string15 CLIA {xpath('CLIA')};
	string12 LegacyID {xpath('LegacyID')};
end;
		
export t_HCDEASummary := record
	string9 RegistrationNumber {xpath('RegistrationNumber')};
	string16 DrugSchedules {xpath('DrugSchedules')};
	share.t_Date Effective {xpath('Effective')};
	share.t_Date Expiration {xpath('Expiration')};
end;
		
export t_HCDEAProfile := record
	string9 RegistrationNumber {xpath('RegistrationNumber')};
	string16 DrugSchedules {xpath('DrugSchedules')};
	share.t_Date Effective {xpath('Effective')};
	share.t_Date Expiration {xpath('Expiration')};
	boolean IsOrganization {xpath('IsOrganization')};
	string40 OrganizationName {xpath('OrganizationName')};
	t_HCProfessionalName Name {xpath('Name')};
	share.t_Address Address {xpath('Address')};
	string1 BusinessActivityCode {xpath('BusinessActivityCode')};
	string26 BusinessActivityCodeDesc {xpath('BusinessActivityCodeDesc')};
	string1 BusinessActivitySubCode {xpath('BusinessActivitySubCode')};
	string36 BusinessActivitySubCodeDesc {xpath('BusinessActivitySubCodeDesc')};
	boolean ActiveStatus {xpath('ActiveStatus')};
end;
		
export t_HCCLIASummary := record
	string15 CLIANumber {xpath('CLIANumber')};
	share.t_Date Expiration {xpath('Expiration')};
	string75 CertificateType {xpath('CertificateType')};
	string50 LaboratoryType {xpath('LaboratoryType')};
	string2 TerminationCode {xpath('TerminationCode')};
	string75 TerminationCodeDesc {xpath('TerminationCodeDesc')};
end;
		
export t_HCStateLicenseSummary := record
	string50 LicenseNumber {xpath('LicenseNumber')};
	string20 LicenseType {xpath('LicenseType')};
	string2 LicenseState {xpath('LicenseState')};
	string50 OriginalLicenseNumber {xpath('OriginalLicenseNumber')};
	string50 PreviousLicenseNumber {xpath('PreviousLicenseNumber')};
	string20 PreviousLicenseType {xpath('PreviousLicenseType')};
	string20 Status {xpath('Status')};
	share.t_Date IssuedOn {xpath('IssuedOn')};
	share.t_Date Expiration {xpath('Expiration')};
end;
		
export t_HCStateLicenseProfile := record
	string50 LicenseNumber {xpath('LicenseNumber')};
	string20 LicenseType {xpath('LicenseType')};
	string2 LicenseState {xpath('LicenseState')};
	string50 OriginalLicenseNumber {xpath('OriginalLicenseNumber')};
	string50 PreviousLicenseNumber {xpath('PreviousLicenseNumber')};
	string20 PreviousLicenseType {xpath('PreviousLicenseType')};
	string20 Status {xpath('Status')};
	share.t_Date IssuedOn {xpath('IssuedOn')};
	share.t_Date Expiration {xpath('Expiration')};
	t_HCProfessionalName Name {xpath('Name')};
	share.t_Address Address {xpath('Address')};
	share.t_Date DOB {xpath('DOB')};
	string100 Email {xpath('Email')};
	string1 Gender {xpath('Gender')};
	share.t_Date DateOfDeath {xpath('DateOfDeath')};
	string50 OrganizationName {xpath('OrganizationName')};
	string25 Specialty {xpath('Specialty')};
	string50 SpecialtyDescription {xpath('SpecialtyDescription')};
	string15 Phone {xpath('Phone')};
	string25 PhoneType {xpath('PhoneType')};
	string10 NPINumber {xpath('NPINumber')};
	string50 CSRNumber {xpath('CSRNumber')};
	string50 DEANumber {xpath('DEANumber')};
	string10 Taxonomy {xpath('Taxonomy')};
	string50 PractitionerType {xpath('PractitionerType')};
	t_HCExtendedAddress Practice {xpath('Practice')};
	t_HCExtendedAddress Billing {xpath('Billing')};
	string9 FileCode {xpath('FileCode')};
	string30 LNPID {xpath('LNPID')};
	string6 UPIN {xpath('UPIN')};
	string12 UniqueId {xpath('UniqueId')};
	unsigned2 UniqueIdScore {xpath('UniqueIdScore')};
	string12 LegacyBusinessId {xpath('LegacyBusinessId')};
	unsigned2 LegacyBusinessIdScore {xpath('LegacyBusinessIdScore')};
	unsigned6 LegacyLocationId {xpath('LegacyLocationId')};
	unsigned6 LegacyAggregateId {xpath('LegacyAggregateId')};
	string1 HomeOrBusinessAddress {xpath('HomeOrBusinessAddress')};
	share.t_Date DateFirstSeen {xpath('DateFirstSeen')};
	share.t_Date DateLastSeen {xpath('DateLastSeen')};
end;
		
export t_HCMedicareDetails := record
	string20 State {xpath('State')};
	string15 Number {xpath('Number')};
	string20 Status {xpath('Status')};
end;
		
export t_HCMedicaidDetails := record
	string20 State {xpath('State')};
	string15 Number {xpath('Number')};
	string20 Status {xpath('Status')};
end;
		
export t_HCTaxonomyDetails := record
	string10 Code {xpath('Code')};
	string50 _Type {xpath('Type')};
	string50 Classification {xpath('Classification')};
	string50 Specialization {xpath('Specialization')};
	string1 PrimaryIndicator {xpath('PrimaryIndicator')};
end;
		
export t_HCSpecialtyDetails := record
	string50 Specialty {xpath('Specialty')};
	string50 SubSpecialty {xpath('SubSpecialty')};
end;
		
export t_HCStateControlledSubstancesProfile := record
	string100 OrganizationName {xpath('OrganizationName')};
	t_HCProfessionalName Name {xpath('Name')};
	share.t_Date DOB {xpath('DOB')};
	string100 Email {xpath('Email')};
	string9 DEANumber {xpath('DEANumber')};
	t_HCExtendedAddress Address {xpath('Address')};
	t_HCExtendedAddressPhoneFax Practice {xpath('Practice')};
	t_HCExtendedAddressPhoneFax Billing {xpath('Billing')};
	string20 LicenseNumber {xpath('LicenseNumber')};
	string10 LicenceType {xpath('LicenceType')};
	string1 LicenseStatus {xpath('LicenseStatus')};
	share.t_Date BeginDate {xpath('BeginDate')};
	share.t_Date EndDate {xpath('EndDate')};
	string16 DrugSchedule {xpath('DrugSchedule')};
	string100 MedicalSchool {xpath('MedicalSchool')};
	string4 MedicalSchoolYear {xpath('MedicalSchoolYear')};
	string10 NPINumber {xpath('NPINumber')};
	string10 Taxonomy {xpath('Taxonomy')};
	string30 LNPID {xpath('LNPID')};
	string30 LNFID {xpath('LNFID')};
	string12 UniqueId {xpath('UniqueId')};
	string12 LegacyBusinessId {xpath('LegacyBusinessId')};
	unsigned6 LegacyLocationId {xpath('LegacyLocationId')};
	unsigned6 LegacyAggregateId {xpath('LegacyAggregateId')};
	string1 HomeOrBusinessAddress {xpath('HomeOrBusinessAddress')};
	share.t_BusinessIdentity BusinessIds {xpath('BusinessIds')};
end;
		
export t_HCCoreBasedStatisticalArea := record
	string120 Name {xpath('Name')};
	string7 _Type {xpath('Type')};
	string7 Code {xpath('Code')};
end;
		
export t_HCAHAProfile := record
	string10 AHAId {xpath('AHAId')};
	string1 RegionCode {xpath('RegionCode')};
	string1 StateCode {xpath('StateCode')};
	string5 HospitalNumber {xpath('HospitalNumber')};
	share.t_Date BeginDate {xpath('BeginDate')};
	share.t_Date EndDate {xpath('EndDate')};
	string4 DaysOpen {xpath('DaysOpen')};
	string2 FiscalYearPeriod {xpath('FiscalYearPeriod')};
	share.t_Date Fiscal {xpath('Fiscal')};
	string4 FiscalBeginYear {xpath('FiscalBeginYear')};
	string2 ControlCode {xpath('ControlCode')};
	string2 ServiceCode {xpath('ServiceCode')};
	string150 ServiceDescription {xpath('ServiceDescription')};
	string1 RestrictedToChildren {xpath('RestrictedToChildren')};
	string1 ShortLongCode {xpath('ShortLongCode')};
	string1 HospitalTypeCode {xpath('HospitalTypeCode')};
	string120 HospitalName {xpath('HospitalName')};
	t_HCProfessionalName ChiefAdministrator {xpath('ChiefAdministrator')};
	t_HCExtendedAddress Address {xpath('Address')};
	string10 Phone {xpath('Phone')};
	string1 CommunityHospitalCode {xpath('CommunityHospitalCode')};
	string2 BedSizeCode {xpath('BedSizeCode')};
	string1 SystemMember {xpath('SystemMember')};
	string1 SubsidaryOperated {xpath('SubsidaryOperated')};
	string10 NPINumber {xpath('NPINumber')};
	string1 AHAClusterCode {xpath('AHAClusterCode')};
	string1 CommunityFlag {xpath('CommunityFlag')};
	string15 MedicareProviderId {xpath('MedicareProviderId')};
	t_HCCoreBasedStatisticalArea CoreBasedStatisticalArea {xpath('CoreBasedStatisticalArea')};
	string3 CityRanking {xpath('CityRanking')};
	string1 Accreditation {xpath('Accreditation')};
	string1 CancerProgram {xpath('CancerProgram')};
	string1 ResidencyTraining {xpath('ResidencyTraining')};
	string1 MedicalSchoolAffiliation {xpath('MedicalSchoolAffiliation')};
	string1 AccreditationByCommission {xpath('AccreditationByCommission')};
	string1 MemberOfCouncil {xpath('MemberOfCouncil')};
	string1 AccreditationByHealthcare {xpath('AccreditationByHealthcare')};
	string1 InternshipApproved {xpath('InternshipApproved')};
	string1 ResidencyApproved {xpath('ResidencyApproved')};
	string1 ReligiousAffiliation {xpath('ReligiousAffiliation')};
	string1 CriticalAccessHospital {xpath('CriticalAccessHospital')};
	string1 RuralReferralCenter {xpath('RuralReferralCenter')};
	string1 SoleCommunityProvider {xpath('SoleCommunityProvider')};
	string15 Teach {xpath('Teach')};
	share.t_Date DateFirstSeen {xpath('DateFirstSeen')};
	share.t_Date DateLastSeen {xpath('DateLastSeen')};
	t_HCProfessionalName ContactName {xpath('ContactName')};
	string4 MetropolitanStatisticalArea {xpath('MetropolitanStatisticalArea')};
	string30 LNPID {xpath('LNPID')};
	string30 LNFID {xpath('LNFID')};
	string12 UniqueId {xpath('UniqueId')};
	string12 LegacyBusinessId {xpath('LegacyBusinessId')};
	unsigned6 LegacyLocationId {xpath('LegacyLocationId')};
	unsigned6 LegacyAggregateId {xpath('LegacyAggregateId')};
	string1 HomeOrBusinessAddress {xpath('HomeOrBusinessAddress')};
	share.t_BusinessIdentity BusinessIds {xpath('BusinessIds')};
end;
		
export t_HCOfficeHoursDaily := record
	string5 StartTime {xpath('StartTime')};
	string5 EndTime {xpath('EndTime')};
	string5 LunchTime {xpath('LunchTime')};
	string4 LunchDurationMinutes {xpath('LunchDurationMinutes')};
end;
		
export t_HCOfficeHours := record
	t_HCOfficeHoursDaily Sunday {xpath('Sunday')};
	t_HCOfficeHoursDaily Monday {xpath('Monday')};
	t_HCOfficeHoursDaily Tuesday {xpath('Tuesday')};
	t_HCOfficeHoursDaily Wednesday {xpath('Wednesday')};
	t_HCOfficeHoursDaily Thursday {xpath('Thursday')};
	t_HCOfficeHoursDaily Friday {xpath('Friday')};
	t_HCOfficeHoursDaily Saturday {xpath('Saturday')};
end;
		
export t_HCOfficeAttributesProfile := record
	t_HCExtendedAddress Practice {xpath('Practice')};
	t_HCOfficeHours OfficeHours {xpath('OfficeHours')};
	dataset(share.t_StringArrayItem) Languages {xpath('Languages/Language'), MAXCOUNT(1)};
	string4 ExamRooms {xpath('ExamRooms')};
	string1 MedicaidPart {xpath('MedicaidPart')};
	string1 MedicarePart {xpath('MedicarePart')};
	string1 NewPatients {xpath('NewPatients')};
end;
		
export t_HCFederallyQualifiedHealthCenter := record
	string50 Name {xpath('Name')};
	string10 Phone {xpath('Phone')};
	string10 ChildrensHospitalPhone {xpath('ChildrensHospitalPhone')};
	string10 RyanWhitePhone {xpath('RyanWhitePhone')};
	string10 TuberculousisClinicPhone {xpath('TuberculousisClinicPhone')};
	string10 STDClinicPhone {xpath('STDClinicPhone')};
end;
		
export t_HCNamedCommunityResource := record
	string144 Name {xpath('Name')};
	string50 Title {xpath('Title')};
	string10 Phone {xpath('Phone')};
end;
		
export t_HCCommunityResources := record
	string128 FacilityName {xpath('FacilityName')};
	string128 SiteName {xpath('SiteName')};
	string128 OrganizationName {xpath('OrganizationName')};
	string15 OrganizationEIN {xpath('OrganizationEIN')};
	unsigned6 CompositeType {xpath('CompositeType')};
	t_HCNamedCommunityResource PlanningProject {xpath('PlanningProject')};
	t_HCFederallyQualifiedHealthCenter FederallyQualifiedHealthCenter {xpath('FederallyQualifiedHealthCenter')};
	t_HCNamedCommunityResource OrganProcurementAgency {xpath('OrganProcurementAgency')};
	t_HCNamedCommunityResource IndianHealthService {xpath('IndianHealthService')};
	t_HCNamedCommunityResource BlackLung {xpath('BlackLung')};
	t_HCNamedCommunityResource Dental {xpath('Dental')};
end;
		
export t_HCContactPerson := record
	string33 _Type {xpath('Type')};
	t_HCProfessionalName Name {xpath('Name')};
	share.t_Address Address {xpath('Address')};
	string100 Title {xpath('Title')};
	string100 Email {xpath('Email')};
	string10 Phone {xpath('Phone')};
end;
		
export t_HCFacilityAttributes := record
	string15 PointOfServiceId {xpath('PointOfServiceId')};
	string15 GlobalLocationNumber {xpath('GlobalLocationNumber')};
	string10 GlobalLocationNumberStatus {xpath('GlobalLocationNumberStatus')};
	string15 ACOId {xpath('ACOId')};
	string15 AHAId {xpath('AHAId')};
	string10 DrugPricingProgram340BId {xpath('DrugPricingProgram340BId')};
	string120 OrganizationName {xpath('OrganizationName')};
	string5 FiscalYearEnd {xpath('FiscalYearEnd')};
	string4 YearCompanyStarted {xpath('YearCompanyStarted')};
	string1 PublicCorporation {xpath('PublicCorporation')};
	string1 ForProfit {xpath('ForProfit')};
	string4 StockSymbol {xpath('StockSymbol')};
	unsigned6 PatientPopulation {xpath('PatientPopulation')};
	string1 Payor {xpath('Payor')};
	string50 TeachingHospital {xpath('TeachingHospital')};
	string50 CMSTeachingHospital {xpath('CMSTeachingHospital')};
	string9 CMSTeachingTIN {xpath('CMSTeachingTIN')};
	string10 CoveredRecipientId {xpath('CoveredRecipientId')};
	string10 CommunityHospitalCode {xpath('CommunityHospitalCode')};
	string1 CriticalAccessHospital {xpath('CriticalAccessHospital')};
	unsigned1 CancerProgram {xpath('CancerProgram')};
	unsigned6 Admissions {xpath('Admissions')};
	unsigned6 ERVisits {xpath('ERVisits')};
	unsigned6 BurnCareBeds {xpath('BurnCareBeds')};
	unsigned6 HospitalTotalBeds {xpath('HospitalTotalBeds')};
	unsigned6 TotalBeds {xpath('TotalBeds')};
	unsigned6 TotalLicensedBeds {xpath('TotalLicensedBeds')};
	unsigned6 InpatientOperations {xpath('InpatientOperations')};
	unsigned6 GeneralAdultBeds {xpath('GeneralAdultBeds')};
	unsigned6 GeneralPediatricBeds {xpath('GeneralPediatricBeds')};
	unsigned6 ObstetricCareBeds {xpath('ObstetricCareBeds')};
	unsigned6 MedicalSurgeryIntesiveCareBeds {xpath('MedicalSurgeryIntesiveCareBeds')};
	unsigned6 CardiacIntensiveCareBeds {xpath('CardiacIntensiveCareBeds')};
	unsigned6 NeonatalIntensiveCareBeds {xpath('NeonatalIntensiveCareBeds')};
	unsigned6 NeonatalIntermediateCareBeds {xpath('NeonatalIntermediateCareBeds')};
	unsigned6 PediatricIntensiveCareBeds {xpath('PediatricIntensiveCareBeds')};
	unsigned6 OtherIntensiveCareBeds {xpath('OtherIntensiveCareBeds')};
	unsigned6 OtherSpecialCareBeds {xpath('OtherSpecialCareBeds')};
	unsigned6 PhysicalRehabilitationCareBeds {xpath('PhysicalRehabilitationCareBeds')};
	unsigned6 AlcoholInpatientCareBeds {xpath('AlcoholInpatientCareBeds')};
	unsigned6 PsychiatricCareBeds {xpath('PsychiatricCareBeds')};
	unsigned6 SkilledNursingCareBeds {xpath('SkilledNursingCareBeds')};
	unsigned6 IntermediateNursingCareBeds {xpath('IntermediateNursingCareBeds')};
	unsigned6 AcuteLongtermCareBeds {xpath('AcuteLongtermCareBeds')};
	unsigned6 OtherLongtermCareBeds {xpath('OtherLongtermCareBeds')};
	unsigned6 OtherCareBeds {xpath('OtherCareBeds')};
	unsigned6 HospitalStaffedBeds {xpath('HospitalStaffedBeds')};
	unsigned6 LicensedBedsTotalNHFacilityUnit {xpath('LicensedBedsTotalNHFacilityUnit')};
	unsigned6 NumberOperatingRooms {xpath('NumberOperatingRooms')};
	unsigned6 Births {xpath('Births')};
	unsigned6 OutpatientOperations {xpath('OutpatientOperations')};
	unsigned6 ContactParticipate {xpath('ContactParticipate')};
	unsigned1 HMO {xpath('HMO')};
	unsigned1 PPO {xpath('PPO')};
	unsigned1 CardiacIC {xpath('CardiacIC')};
	unsigned1 BurnCare {xpath('BurnCare')};
	unsigned1 EndoscopicUltrasound {xpath('EndoscopicUltrasound')};
	unsigned1 OncologyServices {xpath('OncologyServices')};
	unsigned1 ElectronBeam {xpath('ElectronBeam')};
	unsigned1 PositronEmissionTomography {xpath('PositronEmissionTomography')};
end;
		
export t_HCProviderAddress := record (share.t_Address)
	string10 AddressType {xpath('AddressType')};
	share.t_Date DateFirstSeen {xpath('DateFirstSeen')};
	share.t_Date DateLastSeen {xpath('DateLastSeen')};
	string3 ConfidenceScore {xpath('ConfidenceScore')};
end;
		
export t_HCProviderCorrection := record
	string3 ConfidenceScore {xpath('ConfidenceScore')};
	string20 PracticeAddressKey {xpath('PracticeAddressKey')};
	share.t_Address PracticeAddress {xpath('PracticeAddress')};
	string10 Phone {xpath('Phone')};
	string10 Fax {xpath('Fax')};
	share.t_Date LastUpdate {xpath('LastUpdate')};
	share.t_Date VSFLastUpdate {xpath('VSFLastUpdate')};
end;
		
export t_HCProviderCorrections := record
	string _Type {xpath('Type')}; //values['','A','B','R','S','Q','O','T','P','']
	string1 Gender {xpath('Gender')};
	t_HCProviderCorrection Practice {xpath('Practice')};
	t_HCProviderCorrection Billing {xpath('Billing')};
	string11 FEINCorrection {xpath('FEINCorrection')};
	string11 FEINCorrectionStatBits {xpath('FEINCorrectionStatBits')};
	string2 FEINCorrectionDistance {xpath('FEINCorrectionDistance')};
	string10 TaxonomyCorrection {xpath('TaxonomyCorrection')};
	string1 TaxonomyCorrectionPrimaryInd {xpath('TaxonomyCorrectionPrimaryInd')};
	string2 TaxonomyCorrectionDistance {xpath('TaxonomyCorrectionDistance')};
end;
		
export t_HCQuestionableCodes := record
	string4 Provider {xpath('Provider')};
	string4 Sanction {xpath('Sanction')};
	string4 Address {xpath('Address')};
	string4 License {xpath('License')};
	string4 NPI {xpath('NPI')};
	string4 Taxonomy {xpath('Taxonomy')};
end;
		
export t_HCBusinessName := record
	string80 Name {xpath('Name')};
	string10 NameType {xpath('NameType')};
end;
		
export t_HCBaseReportOption := record (share.t_BaseReportOption)
	string255 UserAgent {xpath('UserAgent')};//hidden[internal]
end;
		
export t_HCBaseSearchOptionEx := record (share.t_BaseSearchOptionEx)
	string255 UserAgent {xpath('UserAgent')};//hidden[internal]
end;
		
export t_HCADMCustomFieldNameValue := record
	string50 Name {xpath('Name')};
	string200 Value {xpath('Value')};
end;
		
export t_HCABMSEducationProfile := record
	string8 BiogNumber {xpath('BiogNumber')};
	unsigned6 OccurrenceNumber {xpath('OccurrenceNumber')};
	string150 Degree {xpath('Degree')};
	string5 SchoolCode {xpath('SchoolCode')};
	string150 School {xpath('School')};
	string75 Years {xpath('Years')};
	string25 City {xpath('City')};
	string67 State {xpath('State')};
	string40 Country {xpath('Country')};
end;
		
export t_HCABMSCertificationProfile := record
	string8 BiogNumber {xpath('BiogNumber')};
	string3 BiogCertificationId {xpath('BiogCertificationId')};
	string100 CertificationName {xpath('CertificationName')};
	string1 CertificationTypeIndicator {xpath('CertificationTypeIndicator')};
	string1 RecertificationIndicator {xpath('RecertificationIndicator')};
	string1 BoardCertified {xpath('BoardCertified')};
	share.t_Date Certification {xpath('Certification')};
	share.t_Date Experitation {xpath('Experitation')};
	share.t_Date Reverification {xpath('Reverification')};
	string2 DurationType {xpath('DurationType')};
	string100 BoardWebDescription {xpath('BoardWebDescription')};
	string8 CertificationId {xpath('CertificationId')};
	string8 MOCPathwayId {xpath('MOCPathwayId')};
	string200 MOCPathwayName {xpath('MOCPathwayName')};
end;
		
export t_HCABMSCareerProfile := record
	string8 BiogNumber {xpath('BiogNumber')};
	unsigned6 OccurrenceNumber {xpath('OccurrenceNumber')};
	string100 Specialty {xpath('Specialty')};
	string150 Position {xpath('Position')};
	string230 Organization {xpath('Organization')};
	string70 City {xpath('City')};
	string70 State {xpath('State')};
	string70 Country {xpath('Country')};
	string4 FromYear {xpath('FromYear')};
	string4 ToYear {xpath('ToYear')};
	string3 CareerType {xpath('CareerType')};
end;
		
export t_HCABMSMembershipProfile := record
	string8 BiogNumber {xpath('BiogNumber')};
	string125 MemberOf {xpath('MemberOf')};
	string125 PositionHeldYears {xpath('PositionHeldYears')};
end;
		
export t_HCABMSBirthLocationProfile := record
	string70 City {xpath('City')};
	string70 State {xpath('State')};
	string70 Country {xpath('Country')};
end;
		
export t_HCABMSProfile := record
	string8 BiogNumber {xpath('BiogNumber')};
	share.t_Date DOB {xpath('DOB')};
	boolean DOBSupressed {xpath('DOBSupressed')};
	t_HCABMSBirthLocationProfile BirthLocation {xpath('BirthLocation')};
	boolean BirthLocationSupressed {xpath('BirthLocationSupressed')};
	t_HCProfessionalName Name {xpath('Name')};
	string60 OrganizationName {xpath('OrganizationName')};
	string1 Gender {xpath('Gender')};
	string4 PlacementCertification {xpath('PlacementCertification')};
	string100 PlacementCity {xpath('PlacementCity')};
	string2 PlacementState {xpath('PlacementState')};
	string1 BoardCertified {xpath('BoardCertified')};
	string10 NPINumber {xpath('NPINumber')};
	share.t_Date DOD {xpath('DOD')};
	boolean DeceasedIndicator {xpath('DeceasedIndicator')};
	string4 BoardCode {xpath('BoardCode')};
	string100 BoardName {xpath('BoardName')};
	string1 Participation {xpath('Participation')};
	string8 MOCCertificationId {xpath('MOCCertificationId')};
	string100 MOCCertificationName {xpath('MOCCertificationName')};
	string6 ContactType {xpath('ContactType')};
	string250 Description {xpath('Description')};
	string10 Phone {xpath('Phone')};
	string40 AdditionalOrganizationText {xpath('AdditionalOrganizationText')};
	string255 WebSite {xpath('WebSite')};
	t_HCExtendedAddress Address {xpath('Address')};
	boolean AddressSupressed {xpath('AddressSupressed')};
	string3 NameScore {xpath('NameScore')};
	string30 LNPID {xpath('LNPID')};
	string30 LNFID {xpath('LNFID')};
	string12 UniqueId {xpath('UniqueId')};
	string12 LegacyBusinessId {xpath('LegacyBusinessId')};
	unsigned6 LegacyLocationId {xpath('LegacyLocationId')};
	unsigned6 LegacyAggregateId {xpath('LegacyAggregateId')};
	string1 HomeOrBusinessAddress {xpath('HomeOrBusinessAddress')};
	share.t_BusinessIdentity BusinessIds {xpath('BusinessIds')};
	string60 TypeOfPractice {xpath('TypeOfPractice')};
	dataset(t_HCABMSCertificationProfile) Certifications {xpath('Certifications/Certification'), MAXCOUNT(1)};
	dataset(t_HCABMSCareerProfile) Careers {xpath('Careers/Career'), MAXCOUNT(1)};
	dataset(t_HCABMSEducationProfile) Educations {xpath('Educations/Education'), MAXCOUNT(1)};
	dataset(t_HCABMSMembershipProfile) Memberships {xpath('Memberships/Membership'), MAXCOUNT(1)};
end;
		
export t_HCRosterProfile := record
	t_HCProfessionalName ProviderName {xpath('ProviderName')};
	string100 OrganizationName {xpath('OrganizationName')};
	t_HCExtendedAddressPhoneFax Practice {xpath('Practice')};
	string512 WebSite {xpath('WebSite')};
	string10 Taxonomy {xpath('Taxonomy')};
	string30 LNPID {xpath('LNPID')};
	string30 LNFID {xpath('LNFID')};
	string12 UniqueId {xpath('UniqueId')};
	string12 LegacyBusinessId {xpath('LegacyBusinessId')};
	unsigned6 LegacyLocationId {xpath('LegacyLocationId')};
	unsigned6 LegacyAggregateId {xpath('LegacyAggregateId')};
	string1 HomeOrBusinessAddress {xpath('HomeOrBusinessAddress')};
	share.t_BusinessIdentity BusinessIds {xpath('BusinessIds')};
end;
		
export t_HCSurescriptsAltPhone := record
	string10 Phone {xpath('Phone')};
	string3 Qualifier {xpath('Qualifier')};
end;
		
export t_HCSurescriptsProfile := record
	string13 SurescriptsProviderId {xpath('SurescriptsProviderId')};
	string25 DEANumber {xpath('DEANumber')};
	string25 StateLicenseNumber {xpath('StateLicenseNumber')};
	string3 PrimarySpecialtyCode {xpath('PrimarySpecialtyCode')};
	t_HCProfessionalName ProviderName {xpath('ProviderName')};
	string100 OrganizationName {xpath('OrganizationName')};
	t_HCExtendedAddressPhoneFax Practice {xpath('Practice')};
	string100 Email {xpath('Email')};
	string10 Taxonomy {xpath('Taxonomy')};
	string30 LNPID {xpath('LNPID')};
	string30 LNFID {xpath('LNFID')};
	string12 UniqueId {xpath('UniqueId')};
	string12 LegacyBusinessId {xpath('LegacyBusinessId')};
	unsigned6 LegacyLocationId {xpath('LegacyLocationId')};
	unsigned6 LegacyAggregateId {xpath('LegacyAggregateId')};
	string1 HomeOrBusinessAddress {xpath('HomeOrBusinessAddress')};
	share.t_BusinessIdentity BusinessIds {xpath('BusinessIds')};
	dataset(t_HCSurescriptsAltPhone) AltPhones {xpath('AltPhones/AltPhone'), MAXCOUNT(5)};
	string10 NPINumber {xpath('NPINumber')};
	string13 NPILocation {xpath('NPILocation')};
	dataset(share.t_StringArrayItem) SpecialtyTypes {xpath('SpecialtyTypes/SpecialtyType'), MAXCOUNT(4)};
	string35 MedicareNumber {xpath('MedicareNumber')};
	string35 MedicaidNumber {xpath('MedicaidNumber')};
	string35 DentistLicenseNumber {xpath('DentistLicenseNumber')};
	string6 UPIN {xpath('UPIN')};
	string35 PPONumber {xpath('PPONumber')};
	string35 PriorAuthorization {xpath('PriorAuthorization')};
	string9 BestSSN {xpath('BestSSN')};
	string10 SpecialtyCode {xpath('SpecialtyCode')};
	string50 SpecialtyDescription {xpath('SpecialtyDescription')};
	string10 ActivityCode {xpath('ActivityCode')};
	string5 PracticeTypeCode {xpath('PracticeTypeCode')};
	string50 PracticeTypeDescription {xpath('PracticeTypeDescription')};
end;
		
export t_HCUPINDetails := record
	t_HCProfessionalName ProviderName {xpath('ProviderName')};
	string100 OrganizationName {xpath('OrganizationName')};
	t_HCExtendedAddressPhoneFax Practice {xpath('Practice')};
	t_HCExtendedAddressPhoneFax Billing {xpath('Billing')};
	string1 Gender {xpath('Gender')};
	string6 UPIN {xpath('UPIN')};
	string9 DEANumber {xpath('DEANumber')};
	string10 NPINumber {xpath('NPINumber')};
	share.t_Date LastUpdate {xpath('LastUpdate')};
	share.t_Date NPIDeactivated {xpath('NPIDeactivated')};
	string3 Specialty {xpath('Specialty')};
	string30 LNPID {xpath('LNPID')};
	string30 LNFID {xpath('LNFID')};
	string12 UniqueId {xpath('UniqueId')};
	string12 LegacyBusinessId {xpath('LegacyBusinessId')};
	unsigned6 LegacyLocationId {xpath('LegacyLocationId')};
	unsigned6 LegacyAggregateId {xpath('LegacyAggregateId')};
	string1 HomeOrBusinessAddress {xpath('HomeOrBusinessAddress')};
	share.t_BusinessIdentity BusinessIds {xpath('BusinessIds')};
end;
		

end;

/*** Not to be hand edited (changes will be lost on re-generation) ***/
/*** ECL Interface generated by esdl2ecl version 1.0 from healthcare_share.xml. ***/
/*===================================================*/

