/*** Not to be hand edited (changes will be lost on re-generation) ***/
/*** ECL Interface generated by esdl2ecl version 1.0 from healthcaresubrogationsearch.xml. ***/
/*===================================================*/

export healthcaresubrogationsearch := MODULE
			
export t_HealthcareSubrogationSubject := record
	string12 DID {xpath('UniqueId')};
	string12 BDID {xpath('BDID')};
	share.t_Name Name {xpath('Name')};
	share.t_Address Address {xpath('Address')};
	string9 SSN {xpath('SSN')};
	share.t_Date DOB {xpath('DOB')};
end;
		
export t_HealthcareSubrogationSearchBy := record
	share.t_Name Name {xpath('Name')};
	share.t_Address Address {xpath('Address')};
	string9 SSN {xpath('SSN')};
	share.t_Date DOB {xpath('DOB')};
	string25 VIN {xpath('VIN')};
	share.t_Date DateOfService {xpath('DateOfService')};
	integer SearchDaysBeforeDateOfService {xpath('SearchDaysBeforeDateOfService')};
	integer SearchDaysAfterDateOfService {xpath('SearchDaysAfterDateOfService')};
end;
		
export t_HealthcareSubrogationSearchOption := record (share.t_BaseSearchOption)
	integer ReturnCount {xpath('ReturnCount')};
	integer StartingRecord {xpath('StartingRecord')};
end;
		
export t_HealthcareSubrogationSearchIncident := record
	string AccidentNumber {xpath('AccidentNumber')};
	boolean IsDirectHit {xpath('IsDirectHit')};
	string LossType {xpath('LossType')};
	share.t_Date DateOfLoss {xpath('DateOfLoss')};
	string25 City {xpath('City')};
	string2 State {xpath('State')};
end;
		
export t_HealthcareSubrogationSearchPolicy := record
	string Number {xpath('Number')};
	share.t_Date EffectiveDate {xpath('EffectiveDate')};
	share.t_Date ExpirationDate {xpath('ExpirationDate')};
end;
		
export t_HealthcareSubrogationSearchVehicle := record
	string VIN {xpath('VIN')};
	string Year {xpath('Year')};
	string Make {xpath('Make')};
	string Model {xpath('Model')};
	string OtherVIN {xpath('OtherVIN')};
	string OtherYear {xpath('OtherYear')};
	string OtherMake {xpath('OtherMake')};
	string OtherModel {xpath('OtherModel')};
	string Carrier {xpath('Carrier')};
	t_HealthcareSubrogationSearchPolicy Policy {xpath('Policy')};
end;
		
export t_HealthcareSubrogationSearchRespData := record
	string DataSource {xpath('DataSource')};
	t_HealthcareSubrogationSearchIncident Incident {xpath('Incident')};
	t_HealthcareSubrogationSearchVehicle Vehicle {xpath('Vehicle')};
	t_HealthcareSubrogationSubject Driver {xpath('Driver')};
	t_HealthcareSubrogationSubject Owner {xpath('Owner')};
	dataset(t_HealthcareSubrogationSubject) Passengers {xpath('Passengers/Passenger'), MAXCOUNT(iesp.Constants.HC_Subrogation.MaxPassengers)};
	dataset(t_HealthcareSubrogationSubject) OtherParties {xpath('OtherParties/OtherParties'), MAXCOUNT(iesp.Constants.HC_Subrogation.MaxOtherParties)};
end;
		
export t_HealthcareSubrogationSearchResponse := record
	share.t_ResponseHeader _Header {xpath('Header')};
	integer RecordCount {xpath('RecordCount')};
	t_HealthcareSubrogationSearchBy InputEcho {xpath('InputEcho')};
	string LegalDisclaimer {xpath('LegalDisclaimer')};
	dataset(t_HealthcareSubrogationSearchRespData) Records {xpath('Records/Record'), MAXCOUNT(iesp.Constants.HC_Subrogation.MaxRecords)};
end;
		
export t_HealthcareSubrogationSearchRequest := record (share.t_BaseRequest)
	t_HealthcareSubrogationSearchOption Options {xpath('Options')};
	t_HealthcareSubrogationSearchBy SearchBy {xpath('SearchBy')};
end;
		
export t_HealthcareSubrogationSearchResponseEx := record
	t_HealthcareSubrogationSearchResponse response {xpath('response')};
end;
		

end;

/*** Not to be hand edited (changes will be lost on re-generation) ***/
/*** ECL Interface generated by esdl2ecl version 1.0 from healthcaresubrogationsearch.xml. ***/
/*===================================================*/

