/*** Not to be hand edited (changes will be lost on re-generation) ***/
/*** ECL Interface generated by esdl2ecl version 1.0 from identitysearch.xml. ***/
/*===================================================*/

import iesp;

export identitysearch := MODULE
			
export t_RINIdentitySearchBy := record
	string20 HouseholdId {xpath('HouseholdId')};
	string20 CustomerPersonId {xpath('CustomerPersonId')};
	iesp.share.t_Date TransactionStartDate {xpath('TransactionStartDate')};
	iesp.share.t_Date TransactionEndDate {xpath('TransactionEndDate')};
	iesp.share.t_Name Name {xpath('Name')};
	iesp.share.t_Address Address {xpath('Address')};
	iesp.share.t_Date DOB {xpath('DOB')};
	string11 SSN {xpath('SSN')};
	string15 Phone10 {xpath('Phone10')};
	string50 EmailAddress {xpath('EmailAddress')};
	iesp.rin_share.t_RINDriverLicense DriverLicense {xpath('DriverLicense')};
	iesp.rin_share.t_RINBankInformation BankInformation {xpath('BankInformation')};
	string12 AmountMin {xpath('AmountMin')};
	string12 AmountMax {xpath('AmountMax')};
	string75 ISPName {xpath('ISPName')};
	string25 IpAddress {xpath('IpAddress')};
	string25 MACAddress {xpath('MACAddress')};
	string50 DeviceId {xpath('DeviceId')};
	string20 DeviceSerialNumber {xpath('DeviceSerialNumber')};
	string12 UniqueId {xpath('UniqueId')};
	string10 ProgramCode {xpath('ProgramCode')};
	iesp.share.t_GeoLocation GeoLocation {xpath('GeoLocation')};
end;
		
export t_RINIdentitySearchOption := record (iesp.share.t_BaseOption)
	boolean IsOnline {xpath('IsOnline')};
	string Platform {xpath('Platform')};
	unsigned3 DIDScoreThreshold {xpath('DIDScoreThreshold')};
end;
		
export t_RINIdentitySearchProfileInformation := record
	string12 UniqueId {xpath('UniqueId')};
	iesp.share.t_Name Name {xpath('Name')};
	string11 SSN {xpath('SSN')};
	iesp.share.t_Date DOB {xpath('DOB')};
	iesp.share.t_Address Address {xpath('Address')};
	string25 IpAddress {xpath('IpAddress')};
	string75 ISPName {xpath('ISPName')};
	string100 Country {xpath('Country')};
	string15 Phone10 {xpath('Phone10')};
	string50 EmailAddress {xpath('EmailAddress')};
	iesp.rin_share.t_RINDriverLicense DriverLicense {xpath('DriverLicense')};
	iesp.rin_share.t_RINBankInformation BankInformation {xpath('BankInformation')};
	string50 DeviceId {xpath('DeviceId')};
	dataset(iesp.share.t_NameValuePair) NVPs {xpath('NVPs/NVP'), MAXCOUNT(iesp.Constants.RIN.MAX_COUNT_NVP)};
end;
		
export t_RINIdentitySearchRecord := record
	string30 RecordSource {xpath('RecordSource')};
	string10 RecordType {xpath('RecordType')};
	string60 ElementType {xpath('ElementType')};
	string100 ElementValue {xpath('ElementValue')};
	string70 AnalyticsRecordId {xpath('AnalyticsRecordId')};
	string10 RiskLevel {xpath('RiskLevel')};
	t_RINIdentitySearchProfileInformation ProfileInformation {xpath('ProfileInformation')};
	string12 CaseId {xpath('CaseId')};
	iesp.share.t_Date RecentActivityDate {xpath('RecentActivityDate')};
	integer NoOfIdentities {xpath('NoOfIdentities')};
	integer NoOfActivitiesLast30Days {xpath('NoOfActivitiesLast30Days')};
	integer TotalNoOfActivities {xpath('TotalNoOfActivities')};
	boolean IsKnownRisk {xpath('IsKnownRisk')};
	dataset(iesp.share.t_NameValuePair) NVPs {xpath('NVPs/NVP'), MAXCOUNT(iesp.Constants.RIN.MAX_COUNT_NVP)};
end;
		
export t_IdentitySearchResponse := record
	iesp.share.t_ResponseHeader _Header {xpath('Header')};
	t_RINIdentitySearchBy InputEcho {xpath('InputEcho')};
	unsigned2 RecordCount {xpath('RecordCount')};
	dataset(t_RINIdentitySearchRecord) Records {xpath('Records/Record'), MAXCOUNT(iesp.Constants.RIN.MAX_COUNT_SEARCH_RECORDS)};
end;
		
export t_IdentitySearchRequest := record (iesp.rin_share.t_RINBaseRequest)
	t_RINIdentitySearchBy SearchBy {xpath('SearchBy')};
	t_RINIdentitySearchOption Options {xpath('Options')};
end;
		
export t_IdentitySearchResponseEx := record
	t_IdentitySearchResponse response {xpath('response')};
end;
		

end;

/*** Not to be hand edited (changes will be lost on re-generation) ***/
/*** ECL Interface generated by esdl2ecl version 1.0 from identitysearch.xml. ***/
/*===================================================*/

