/*** Not to be hand edited (changes will be lost on re-generation) ***/
/*** ECL Interface generated by esdl2ecl version 1.0 from idmsearch.xml. ***/
/*===================================================*/

export idmsearch := MODULE
			
export t_IdmSSNInfo := record
	string32 IssuedLocation {xpath('IssuedLocation')};
	share.t_Date IssuedStartDate {xpath('IssuedStartDate')};
	share.t_Date IssuedEndDate {xpath('IssuedEndDate')};
end;
		
export t_IdmIdentity := record
	string12 UniqueId {xpath('UniqueId')};
	share.t_Name Name {xpath('Name')};
	share.t_Date DOB {xpath('DOB')};
	integer Age {xpath('Age')};
end;
		
export t_IdmAddressInfo := record
	share.t_Date DateFirstSeen {xpath('DateFirstSeen')};
	share.t_Date DateLastSeen {xpath('DateLastSeen')};
	share.t_Address Address {xpath('Address')};
end;
		
export t_IdmPersonRecord := record
	share.t_Name Name {xpath('Name')};
	t_IdmSSNInfo SSNInfo {xpath('SSNInfo')};
	share.t_Date DOB {xpath('DOB')};
	dataset(t_IdmAddressInfo) Addresses {xpath('Addresses/Address'), MAXCOUNT(iesp.Constants.IDM.MaxAddress)};
end;
		
export t_IdmWaterCraftReport2Description := record
	string30 HullNumber {xpath('HullNumber')};
	string20 VesselType {xpath('VesselType')};
	string20 VesselName {xpath('VesselName')};
	string20 HullType {xpath('HullType')};
	integer ModelYear {xpath('ModelYear')};
	string30 Make {xpath('Make')};
	string30 Model {xpath('Model')};
	string7 Length {xpath('Length')};
end;
		
export t_IdmWaterCraftReport2Title := record
	string2 State {xpath('State')};
	share.t_Date IssueDate {xpath('IssueDate')};
end;
		
export t_IdmWaterCraftDetail := record
	string30 WaterCraftKey {xpath('WaterCraftKey')};
	share.t_Date PurchaseDate {xpath('PurchaseDate')};
	t_IdmWaterCraftReport2Description Description {xpath('Description')};
	t_IdmWaterCraftReport2Title Title {xpath('Title')};
end;
		
export t_IdmWaterCraftRecord := record
	t_IdmWaterCraftDetail Watercraft {xpath('Watercraft')};
end;
		
export t_IdmReportAddressSlim := record
	share.t_Date DateFirstSeen {xpath('DateFirstSeen')};
	share.t_Date DateLastSeen {xpath('DateLastSeen')};
	share.t_Address Address {xpath('Address')};
	boolean _Shared {xpath('_Shared')};
end;
		
export t_IdmReportRNASlim := record
	t_IdmIdentity Identity {xpath('Identity')};
	string1 Deceased {xpath('Deceased')};
	integer NumberOfCohabits {xpath('NumberOfCohabits')};
	dataset(t_IdmReportAddressSlim) Addresses {xpath('Addresses/Address'), MAXCOUNT(iesp.Constants.IDM.MaxRNA_Address)};
end;
		
export t_IdmRNARecord := record
	dataset(t_IdmReportRNASlim) Relatives {xpath('Relatives/Relative'), MAXCOUNT(iesp.Constants.IDM.MaxRelatives)};
	dataset(t_IdmReportRNASlim) Associates {xpath('Associates/Associate'), MAXCOUNT(iesp.Constants.IDM.MaxAssociates)};
end;
		
export t_IdmHistPhonesRecord := record
	string12 UniqueId {xpath('UniqueId')};
	share.t_Address Address {xpath('Address')};
	string10 Phone10 {xpath('Phone10')};
	share.t_Date DateFirstSeen {xpath('DateFirstSeen')};
	share.t_Date DateLastSeen {xpath('DateLastSeen')};
end;
		
export t_IdmPropertyMortgageInfo := record
	string60 LenderName {xpath('LenderName')};
	string60 MortgageLenderName {xpath('MortgageLenderName')};
	string11 MortgageAmount {xpath('MortgageAmount')};
	string MortgageLoanType {xpath('MortgageLoanType')};
	share.t_Date MortgageDueDate {xpath('MortgageDueDate')};
end;
		
export t_IdmPropertyDeed := record
	string1 DataSource {xpath('DataSource')};
	string2 State {xpath('State')};
	string18 CountyName {xpath('CountyName')};
	string11 SalesPrice {xpath('SalesPrice')};
	t_IdmPropertyMortgageInfo MortgageInfo {xpath('MortgageInfo')};
	share.t_Date ContractDate {xpath('ContractDate')};
	share.t_Date RecordingDate {xpath('RecordingDate')};
	string3 DocumentTypeCode {xpath('DocumentTypeCode')};
	string DocumentTypeDescription {xpath('DocumentTypeDescription')};
end;
		
export t_IdmPropertyInfo := record
	string40 Subdivision {xpath('Subdivision')};
	string LivingSquareFeet {xpath('LivingSquareFeet')};
	string30 BuildingAreaMain {xpath('BuildingAreaMain')};
	string30 BuildingArea1 {xpath('BuildingArea1')};
	string30 BuildingArea2 {xpath('BuildingArea2')};
	string30 BuildingArea3 {xpath('BuildingArea3')};
	string30 BuildingArea4 {xpath('BuildingArea4')};
	string30 BuildingArea5 {xpath('BuildingArea5')};
	string30 BuildingArea6 {xpath('BuildingArea6')};
	string30 BuildingArea7 {xpath('BuildingArea7')};
	string30 BuildingAreaMainDesc {xpath('BuildingAreaMainDesc')};
	string30 BuildingArea1Desc {xpath('BuildingArea1Desc')};
	string30 BuildingArea2Desc {xpath('BuildingArea2Desc')};
	string30 BuildingArea3Desc {xpath('BuildingArea3Desc')};
	string30 BuildingArea4Desc {xpath('BuildingArea4Desc')};
	string30 BuildingArea5Desc {xpath('BuildingArea5Desc')};
	string30 BuildingArea6Desc {xpath('BuildingArea6Desc')};
	string30 BuildingArea7Desc {xpath('BuildingArea7Desc')};
	string4 YearBuilt {xpath('YearBuilt')};
	string AirConditioning {xpath('AirConditioning')};
	string2 NumberOfBedrooms {xpath('NumberOfBedrooms')};
	string2 NumberOfStories {xpath('NumberOfStories')};
end;
		
export t_IdmPropertyAssess := record
	string1 DataSource {xpath('DataSource')};
	string18 CountyName {xpath('CountyName')};
	share.t_Date SaleDate {xpath('SaleDate')};
	share.t_Date RecordingDate {xpath('RecordingDate')};
	string11 SalesPrice {xpath('SalesPrice')};
	string4 TaxYear {xpath('TaxYear')};
	string13 TaxAmount {xpath('TaxAmount')};
	t_IdmPropertyInfo PropertyInfo {xpath('PropertyInfo')};
end;
		
export t_IdmEntity := record
	string12 UniqueId {xpath('UniqueId')};
	share.t_Name Name {xpath('Name')};
end;
		
export t_IdmPropertyParty := record
	string2 PartyType {xpath('PartyType')};
	string8 PartyTypeName {xpath('PartyTypeName')};
	share.t_Address Address {xpath('Address')};
	dataset(t_IdmEntity) Entities {xpath('Entities/Entity'), MAXCOUNT(iesp.Constants.IDM.MaxPropertyEntities)};
end;
		
export t_IdmPropertyMatchedParty := record
	string12 UniqueId {xpath('UniqueId')};
	string2 PartyType {xpath('PartyType')};
	string8 PartyTypeName {xpath('PartyTypeName')};
end;
		
export t_IdmPropertyRecordDetails := record
	string1 RecordType {xpath('RecordType')};
	t_IdmPropertyAssess Assessment {xpath('Assessment')};
	t_IdmPropertyDeed Deed {xpath('Deed')};
	dataset(t_IdmPropertyParty) Parties {xpath('Parties/Party'), MAXCOUNT(iesp.Constants.IDM.MaxPropertyParties)};
	t_IdmPropertyMatchedParty MatchedParty {xpath('MatchedParty')};
end;
		
export t_IdmPropertyRecord := record
	string ApnaOrPinNumber {xpath('ApnaOrPinNumber')};
	share.t_Address PropertyAddress {xpath('PropertyAddress')};
	dataset(t_IdmPropertyRecordDetails) PropertyRecords {xpath('PropertyRecords/PropertyRecord'), MAXCOUNT(iesp.Constants.IDM.MaxPropertyRecords)};
end;
		
export t_IdmDriverLicenseRecord := record
	string12 UniqueId {xpath('UniqueId')};
	string3 Height {xpath('Height')};
	string15 HairColor {xpath('HairColor')};
	string15 EyeColor {xpath('EyeColor')};
end;
		
export t_IdmMVehicleRegistrationInfo := record
	share.t_Date FirstDate {xpath('FirstDate')};
	share.t_Date ExpirationDate {xpath('ExpirationDate')};
	share.t_Address Address {xpath('Address')};
end;
		
export t_IdmMVehicleSpecification := record
	string30 MajorColor {xpath('MajorColor')};
	string25 BodyType {xpath('BodyType')};
end;
		
export t_IdmMVehicleDetail := record
	integer ModelYear {xpath('ModelYear')};
	string36 Make {xpath('Make')};
	string36 Model {xpath('Model')};
	t_IdmMVehicleSpecification VehicleSpecification {xpath('VehicleSpecification')};
	share.t_Date TitleIssueDate {xpath('TitleIssueDate')};
	dataset(t_IdmMVehicleRegistrationInfo) Registrations {xpath('Registrations/Registration'), MAXCOUNT(iesp.Constants.MV.MaxCountRegistrants)};
end;
		
export t_IdmMVehicleRecord := record
	string VIN {xpath('VIN')};
	dataset(t_IdmMVehicleDetail) VehicleDetails {xpath('VehicleDetails/VehicleDetail'), MAXCOUNT(iesp.Constants.IDM.MaxVehicleDetails)};
end;
		
export t_IdmStudentCollege := record
	string50 CollegeName {xpath('CollegeName')};
	string50 CollegeMajor {xpath('CollegeMajor')};
	string25 CollegeLevel {xpath('CollegeLevel')};
	string30 CollegeType {xpath('CollegeType')};
	share.t_Address AddressAtCollege {xpath('AddressAtCollege')};
	string10 PhoneAtCollege {xpath('PhoneAtCollege')};
end;
		
export t_IdmStudentRecord := record
	string12 UniqueId {xpath('UniqueId')};
	string4 HighSchoolGradYear {xpath('HighSchoolGradYear')};
	dataset(t_IdmStudentCollege) Colleges {xpath('Colleges/College'), MAXCOUNT(iesp.Constants.IDM.MaxStudentColleges)};
end;
		
export t_IDMSearchOption := record (share.t_BaseSearchOption)
	boolean IncludePersonReport {xpath('IncludePersonReport')};
	boolean IncludeDriversLicenses {xpath('IncludeDriversLicenses')};
	boolean IncludeMotorVehicles {xpath('IncludeMotorVehicles')};
	boolean IncludeHistoricalPhones {xpath('IncludeHistoricalPhones')};
	boolean IncludeProperties {xpath('IncludeProperties')};
	boolean IncludeRNA {xpath('IncludeRNA')};
	boolean IncludeStudentRecords {xpath('IncludeStudentRecords')};
	boolean IncludeWatercrafts {xpath('IncludeWatercrafts')};
end;
		
export t_IDMSearchBy := record
	share.t_Name Name {xpath('Name')};
	share.t_Address Address {xpath('Address')};
	string12 UniqueId {xpath('UniqueId')};
	string9 SSN {xpath('SSN')};
	share.t_Date DOB {xpath('DOB')};
end;
		
export t_IDMSearchIndividual := record
	string12 UniqueId {xpath('UniqueId')};
	t_IdmPersonRecord PersonRecord {xpath('PersonRecord')};
	dataset(t_IdmPropertyRecord) Properties {xpath('Properties/Property'), MAXCOUNT(iesp.Constants.IDM.MaxProperties)};
	dataset(t_IdmHistPhonesRecord) HistoricalPhones {xpath('HistoricalPhones/HistoricalPhone'), MAXCOUNT(iesp.Constants.IDM.MaxHistoricalPhones)};
	dataset(t_IdmMVehicleRecord) Vehicles {xpath('Vehicles/Vehicle'), MAXCOUNT(iesp.Constants.IDM.MaxVehicles)};
	dataset(t_IdmWaterCraftRecord) WaterCrafts {xpath('WaterCrafts/WaterCraft'), MAXCOUNT(iesp.Constants.IDM.MaxWatercrafts)};
	dataset(t_IdmRNARecord) RNAs {xpath('RNAs/RNA'), MAXCOUNT(iesp.Constants.IDM.MaxRNA)};
	t_IdmStudentRecord StudentRecord {xpath('StudentRecord')};
	t_IdmDriverLicenseRecord DriverLicense {xpath('DriverLicense')};
end;
		
export t_IDMSearchResponse := record
	share.t_ResponseHeader _Header {xpath('Header')};
	t_IDMSearchIndividual Individual {xpath('Individual')};
end;
		
export t_IDMSearchRequest := record (share.t_BaseRequest)
	t_IDMSearchOption Options {xpath('Options')};
	t_IDMSearchBy SearchBy {xpath('SearchBy')};
end;
		
export t_IDMSearchResponseEx := record
	t_IDMSearchResponse response {xpath('response')};
end;
		

end;

/*** Not to be hand edited (changes will be lost on re-generation) ***/
/*** ECL Interface generated by esdl2ecl version 1.0 from idmsearch.xml. ***/
/*===================================================*/

