/*** Not to be hand edited (changes will be lost on re-generation) ***/
/*** ECL Interface generated by esdl2ecl version 1.0 from laboraction_ebsa.xml. ***/
/*===================================================*/

export laboraction_ebsa := MODULE
			
export t_LaborAction_EBSASearchBy := record
	share.t_NameAndCompany Name {xpath('Name')};
  share.t_DateRange ClosingDateRange {xpath('ClosingDateRange')};
end;
		
export t_LaborAction_EBSAOption := record (share.t_BaseSearchOptionEx)
	integer ReturnCount {xpath('ReturnCount')};
	integer StartingRecord {xpath('StartingRecord')};
end;
		
export t_LaborAction_EBSA_Plan := record
	string10 EIN {xpath('EIN')};
	string3 Number {xpath('Number')};
	string10 Year {xpath('Year')};
	string150 Name {xpath('Name')};
	string150 Administrator {xpath('Administrator')};
end;
		
export t_LaborAction_EBSA_Admin := record
	string30 State {xpath('State')};
	string5 Zip5 {xpath('Zip5')};
	string4 Zip4 {xpath('Zip4')};
end;
		
export t_LaborAction_EBSARecord := record
	string20 CaseType {xpath('CaseType')};
	string50 Website {xpath('Website')};
	string2 State {xpath('State')};
	string30 ClosingReason {xpath('ClosingReason')};
	share.t_Date ClosingDate {xpath('ClosingDate')};
	string20 PenaltyAmount {xpath('PenaltyAmount')};
	t_LaborAction_EBSA_Plan Plan {xpath('Plan')};
	t_LaborAction_EBSA_Admin Admin {xpath('Admin')};
end;
		
export t_LaborAction_EBSASearchResponse := record
	share.t_ResponseHeader _Header {xpath('Header')};
	integer RecordCount {xpath('RecordCount')};
	dataset(t_LaborAction_EBSARecord) Records {xpath('Records/Record'), MAXCOUNT(iesp.Constants.LABOR_ACTION_EBSA.MaxSearchRecords)};
end;
		
export t_LaborAction_EBSASearchRequest := record (share.t_BaseRequest)
	t_LaborAction_EBSASearchBy SearchBy {xpath('SearchBy')};
	t_LaborAction_EBSAOption Options {xpath('Options')};
end;
		
export t_LaborAction_EBSASearchResponseEx := record
	t_LaborAction_EBSASearchResponse response {xpath('response')};
end;
		

end;

/*** Not to be hand edited (changes will be lost on re-generation) ***/
/*** ECL Interface generated by esdl2ecl version 1.0 from laboraction_ebsa.xml. ***/
/*===================================================*/

