/*** Not to be hand edited (changes will be lost on re-generation) ***/
/*** ECL Interface generated by esdl2ecl version 1.0 from national_accident.xml. ***/
/*===================================================*/

export national_accident := MODULE
			
export t_NationalAccidentReportBy := record
	string25 VIN {xpath('VIN')};
	share.t_Name Name {xpath('Name')};//hidden[internal]
	share.t_Address Address {xpath('Address')};//hidden[internal]
	share.t_Date DOB {xpath('DOB')};//hidden[internal]
	string9 SSN {xpath('SSN')};//hidden[internal]
	string25 DriverLicenseNumber {xpath('DriverLicenseNumber')};//hidden[internal]
	string2 DriverLicenseState {xpath('DriverLicenseState')};//hidden[internal]
	string22 UniqueId {xpath('UniqueId')};//hidden[internal]
	share.t_Date AccidentDate {xpath('AccidentDate')};//hidden[internal]
end;
		
export t_NationalAccidentReportOption := record (share.t_BaseReportOption)
	string10 ReportType {xpath('ReportType')};
	boolean EnableExtraAccidents {xpath('EnableExtraAccidents')};
end;
		
export t_NationalAccidentReportVehicle := record
	integer2 Year {xpath('Year')};
	string20 Make {xpath('Make')};
	string25 Model {xpath('Model')};
	string22 VIN {xpath('VIN')};
	string30 DamageLocation {xpath('DamageLocation')};
	string80 InsuranceCompanyName {xpath('InsuranceCompanyName')};
end;
		
export t_NationalAccidentReportLocation := record
	string25 City {xpath('City')};
	string2 State {xpath('State')};
end;
		
export t_NationalAccidentReportAccident := record
	string65 ReportDescription {xpath('ReportDescription')};
	string40 AccidentId {xpath('AccidentId')};
	share.t_Date AccidentDate {xpath('AccidentDate')};
	t_NationalAccidentReportLocation Location {xpath('Location')};
	dataset(t_NationalAccidentReportVehicle) Vehicles {xpath('Vehicles/Vehicle'), MAXCOUNT(iesp.constants.NATIONAL_ACCIDENTS_MAX_COUNT_VEHICLE)};
end;
		
export t_NationalAccidentReportResponse := record
	share.t_ResponseHeader _Header {xpath('Header')};
	string22 QueriedVIN {xpath('QueriedVIN')};
	boolean HitIndicator {xpath('HitIndicator')};
	dataset(t_NationalAccidentReportAccident) Accidents {xpath('Accidents/Accident'), MAXCOUNT(iesp.constants.NATIONAL_ACCIDENTS_MAX_COUNT_ACCIDENT)};
end;
		
export t_NationalAccidentReportRequest := record (share.t_BaseRequest)
	t_NationalAccidentReportOption Options {xpath('Options')};
	t_NationalAccidentReportBy ReportBy {xpath('ReportBy')};
end;
		
export t_NationalAccidentReportResponseEx := record
	t_NationalAccidentReportResponse response {xpath('response')};
end;
		

end;

/*** Not to be hand edited (changes will be lost on re-generation) ***/
/*** ECL Interface generated by esdl2ecl version 1.0 from national_accident.xml. ***/
/*===================================================*/

