/*** Not to be hand edited (changes will be lost on re-generation) ***/
/*** ECL Interface generated by esdl2ecl version 1.0 from person_picklist.xml. ***/
/*===================================================*/

export person_picklist := MODULE
			
export t_PersonPickListOption := record (share.t_BaseSearchOption)
	integer ReturnCount {xpath('ReturnCount')};
	integer StartingRecord {xpath('StartingRecord')};
	boolean UsePhonetics {xpath('UsePhonetics')};
	boolean CheckNameVariants {xpath('CheckNameVariants')};
	boolean UseNicknames {xpath('UseNicknames')};
	boolean UsePartialSSNMatch {xpath('UsePartialSSNMatch')};
	boolean ReturnUniqueIdsOnly {xpath('ReturnUniqueIdsOnly')};//hidden[internal]
  boolean IncludeAllUniqueIdRecords {xpath('IncludeAllUniqueIdRecords')};

  boolean SkipFCRARestriction_RhodeIsland;
  boolean SortByBankruptcy {xpath('SortByBankruptcy')};
end;
		
export t_PersonPickListBy := record
	string11 SSN {xpath('SSN')};
	string4 SSNLast4 {xpath('SSNLast4')};
	string5 SSNFirst5 {xpath('SSNFirst5')};
	string10 Phone10 {xpath('Phone10')};
	string12 UniqueId {xpath('UniqueId')};
	integer Radius {xpath('Radius')};
	share.t_Name Name {xpath('Name')};
	share.t_Address Address {xpath('Address')};
	share.t_Date DOB {xpath('DOB')};
end;
		
export t_PersonPickListRecord := record
	string12 UniqueId {xpath('UniqueId')};
	integer _Penalty {xpath('Penalty')};//hidden[ecldev]
	dataset(share.t_Name) Names {xpath('Names/Name'), MAXCOUNT(iesp.Constants.BPS.ROLLUP_MAX_COUNT_NAMES)};
	dataset(share.t_Address) Addresses {xpath('Addresses/Address'), MAXCOUNT(50)};
	dataset(share.t_MaskableDate) DOBs {xpath('DOBs/DOB'), MAXCOUNT(50)};
	dataset(share.t_StringArrayItem) SSNs {xpath('SSNs/SSN'), MAXCOUNT(iesp.Constants.BPS.ROLLUP_MAX_COUNT_SSNS)};
end;
		
export t_PersonPickListResponse := record
	share.t_ResponseHeader _Header {xpath('Header')}; // exceptions
	integer SubjectTotalCount {xpath('SubjectTotalCount')};
	dataset(share.t_CodeMap) Messages {xpath('Messages/Message'), MAXCOUNT(5)};
	dataset(t_PersonPickListRecord) Records {xpath('Records/Record'), MAXCOUNT(iesp.Constants.BPS.ROLLUP_MAX_COUNT_RESPONSE_RECORDS)};
end;
		
export t_PersonPickListRequest := record (share.t_BaseRequest)
	t_PersonPickListOption Options {xpath('Options')};
	t_PersonPickListBy SearchBy {xpath('SearchBy')};
end;
		
export t_PersonPickListResponseEx := record
	t_PersonPickListResponse response {xpath('response')};
end;
		

end;

/*** Not to be hand edited (changes will be lost on re-generation) ***/
/*** ECL Interface generated by esdl2ecl version 1.0 from person_picklist.xml. ***/
/*===================================================*/

