/*** Not to be hand edited (changes will be lost on re-generation) ***/
/*** ECL Interface generated by esdl2ecl version 1.0 from premiseassociation.xml. ***/
/*===================================================*/

export premiseassociation := MODULE
			
export t_PARSearchBy := record
	string30 Seq {xpath('Seq')};//hidden[ecldev]
	string12 UniqueId {xpath('UniqueId')};
	share.t_Name Name {xpath('Name')};
	share.t_Address Address {xpath('Address')};
	string10 Phone {xpath('Phone')};
	share.t_Date DOB {xpath('DOB')};
	string11 SSN {xpath('SSN')};
	share.t_Date AsOf {xpath('AsOf')};
end;
		
export t_PAROptions := record (share.t_BaseOption)
	string32 AttributesVersionRequest {xpath('AttributesVersionRequest')};
	boolean IncludeModel {xpath('IncludeModel')};
	boolean IncludeReport {xpath('IncludeReport')};
end;
		
export t_PARAttributesGroup := record
	string32 Name {xpath('Name')};
	dataset(share.t_NameValuePair) Attributes {xpath('Attributes/Attribute'), MAXCOUNT(iesp.Constants.PAR.MaxAttributes)};
end;
		
export t_PARAddress := record
	share.t_Address Address {xpath('Address')};
	string32 ResidentialOrBusiness {xpath('ResidentialOrBusiness')};
	string32 _Type {xpath('Type')};
	string128 MixedUse {xpath('MixedUse')};
	dataset(share.t_RiskIndicator) HighRiskIndicators {xpath('HighRiskIndicators/HighRiskIndicator'), MAXCOUNT(iesp.Constants.PAR.MaxSummaryHRI)};
end;
		
export t_PARAddressTarget := record (t_PARAddress)
	string32 PropertyType {xpath('PropertyType')};
	string32 PropertyCharacteristics {xpath('PropertyCharacteristics')};
end;
		
export t_PAREmail := record
	string128 address {xpath('address')};
end;
		
export t_PARSummary := record
	string12 UniqueId {xpath('UniqueId')};
	share.t_Name Name {xpath('Name')};
	t_PARAddress CurrentAddress {xpath('CurrentAddress')};
	share.t_SSNInfoEx SSN {xpath('SSN')};
	dataset(dirassistwireless.t_DirAssistWirelessSearchRecord) Phones {xpath('Phones/Phone'), MAXCOUNT(iesp.Constants.PAR.MaxSummaryPhones)};
	share.t_Date DOB {xpath('DOB')};
	string3 Age {xpath('Age')};
	dataset(t_PAREmail) Emails {xpath('Emails/Email'), MAXCOUNT(iesp.Constants.PAR.MaxSummaryEmails)};
end;
		
export t_PARConfirmingSource := record
	string32 Source {xpath('Source')};
	share.t_Date From {xpath('From')};
	share.t_Date To {xpath('To')};
	integer2 Count {xpath('Count')};
end;
		
export t_PAROtherAssociatedAddress := record
	share.t_Address Address {xpath('Address')};
	share.t_DateRange DateRange {xpath('DateRange')};
	string16 Status {xpath('Status')};
end;
		
export t_PARTargetRecord := record
	string16 ServiceType {xpath('ServiceType')};
	share.t_Name Name {xpath('Name')};
	share.t_Date From {xpath('From')};
	share.t_Date To {xpath('To')};
	string12 UniqueId {xpath('UniqueId')};
end;
		
export t_PARSubjectRecord := record
	string16 ServiceType {xpath('ServiceType')};
	share.t_Address Address {xpath('Address')};
	share.t_Date From {xpath('From')};
	share.t_Date To {xpath('To')};
end;
		
export t_PARPhoneAndUtility := record
	dataset(t_PARTargetRecord) TargetRecords {xpath('TargetRecords/TargetRecord'), MAXCOUNT(iesp.Constants.PAR.MaxSupport)};
	dataset(t_PARSubjectRecord) SubjectRecords {xpath('SubjectRecords/SubjectRecord'), MAXCOUNT(iesp.Constants.PAR.MaxSupport)};
end;
		
export t_PARIdentity := record
	string12 UniqueId {xpath('UniqueId')};
	share.t_Name Name {xpath('Name')};
	share.t_Date From {xpath('From')};
	share.t_Date To {xpath('To')};
	string32 Association {xpath('Association')};
end;
		
export t_PremiseAssociationReport := record
	t_PARSummary Summary {xpath('Summary')};
	t_PARAddressTarget TargetSummary {xpath('TargetSummary')};
	dataset(t_PARConfirmingSource) Sources {xpath('Sources/Source'), MAXCOUNT(iesp.Constants.PAR.MaxSupport)};
	dataset(t_PAROtherAssociatedAddress) AssociatedAddresses {xpath('AssociatedAddresses/AssociatedAddress'), MAXCOUNT(iesp.Constants.PAR.MaxSupport)};
	dataset(t_PAROtherAssociatedAddress) AssociatedAddressesAsOf {xpath('AssociatedAddressesAsOf/AssociatedAddressAsOf'), MAXCOUNT(iesp.Constants.PAR.MaxSupport)};
	t_PARPhoneAndUtility PhoneAndUtility {xpath('PhoneAndUtility')};
	dataset(t_PARIdentity) AssociatedIdentities {xpath('AssociatedIdentities/AssociatedIdentity'), MAXCOUNT(iesp.Constants.PAR.MaxSupport)};
end;
		
export t_PremiseAssociationResult := record
	t_PARSearchBy InputEcho {xpath('InputEcho')};
	string12 UniqueId {xpath('UniqueId')};
	t_PARAttributesGroup AttributeGroup {xpath('AttributeGroup')};
	t_PremiseAssociationReport Report {xpath('Report')};
end;
		
export t_PremiseAssociationResponse := record
	share.t_ResponseHeader _Header {xpath('Header')};
	t_PremiseAssociationResult Result {xpath('Result')};
end;
		
export t_PremiseAssociationRequest := record (share.t_BaseRequest)
	t_PAROptions Options {xpath('Options')};
	t_PARSearchBy SearchBy {xpath('SearchBy')};
end;
		
export t_PremiseAssociationResponseEx := record
	t_PremiseAssociationResponse response {xpath('response')};
end;
		

end;

/*** Not to be hand edited (changes will be lost on re-generation) ***/
/*** ECL Interface generated by esdl2ecl version 1.0 from premiseassociation.xml. ***/
/*===================================================*/

