/*** Not to be hand edited (changes will be lost on re-generation) ***/
/*** ECL Interface generated by esdl2ecl version 1.0 from profileboosterattributes.xml. ***/
/*===================================================*/

export profileboosterattributes := MODULE
			
export t_ProfileBoosterSearchBy := record
	string30 Seq {xpath('Seq')};//hidden[ecldev]
	string12 UniqueId {xpath('UniqueId')};
	share.t_Name Name {xpath('Name')};
	share.t_Address Address {xpath('Address')};
	string10 Phone {xpath('Phone')};
	string9 SSN {xpath('SSN')};
	share.t_Date DOB {xpath('DOB')};
end;
		
export t_ProfileBoosterModels := record
	dataset(share.t_StringArrayItem) Names {xpath('Names/Name'), MAXCOUNT(iesp.constants.ProfileBooster.MaxModelCount)};
end;
		
export t_ProfileBoosterOptions := record (share.t_BaseOption)
	string6 HistoryDateYYYYMM {xpath('HistoryDateYYYYMM')};
	string64 AttributesVersionRequest {xpath('AttributesVersionRequest')};
	t_ProfileBoosterModels IncludeModels {xpath('IncludeModels')};
end;
		
export t_ProfileBoosterRiskIndicator := record
	integer Sequence {xpath('Sequence')};
	string4 ReasonCode {xpath('ReasonCode')};
	string150 Description {xpath('Description')};
end;
		
export t_ProfileBoosterScoreHRI := record
	string64 _Type {xpath('Type')};
	integer Value {xpath('Value')};
	dataset(t_ProfileBoosterRiskIndicator) ScoreReasons {xpath('ScoreReasons/ScoreReason'), MAXCOUNT(iesp.constants.ProfileBooster.MaxHRICount)};
end;
		
export t_ProfileBoosterModelHRI := record
	string64 Name {xpath('Name')};
	dataset(t_ProfileBoosterScoreHRI) Scores {xpath('Scores/Score'), MAXCOUNT(iesp.constants.ProfileBooster.MaxModelScoreCount)};
end;
		
export t_ProfileBoosterGroup := record
	string64 Name {xpath('Name')};
	dataset(share.t_NameValuePair) Attributes {xpath('Attributes/Attribute'), MAXCOUNT(iesp.constants.ProfileBooster.MaxAttributes)};
end;
		
export t_ProfileBoosterResponse := record
	share.t_ResponseHeader _Header {xpath('Header')};
	t_ProfileBoosterSearchBy InputEcho {xpath('InputEcho')};
	string12 UniqueId {xpath('UniqueId')};
	t_ProfileBoosterGroup AttributesGroup {xpath('AttributesGroup')};
	dataset(t_ProfileBoosterModelHRI) Models {xpath('Models/Model'), MAXCOUNT(iesp.constants.ProfileBooster.MaxModelCount)};
end;
		
export t_ProfileBoosterRequest := record (share.t_BaseRequest)
	t_ProfileBoosterOptions Options {xpath('Options')};
	t_ProfileBoosterSearchBy SearchBy {xpath('SearchBy')};
end;
		
export t_ProfileBoosterResponseEx := record
	t_ProfileBoosterResponse response {xpath('response')};
end;
		

end;

/*** Not to be hand edited (changes will be lost on re-generation) ***/
/*** ECL Interface generated by esdl2ecl version 1.0 from profileboosterattributes.xml. ***/
/*===================================================*/

