/*** Not to be hand edited (changes will be lost on re-generation) ***/
/*** ECL Interface generated by esdl2ecl version 1.0 from property_value_report.xml. ***/
/*===================================================*/

export property_value_report := MODULE
			
export t_PropertyAddressIn := record
	string FirstName {xpath('FirstName')};
	string LastName {xpath('LastName')};
	string Street {xpath('Street')};
	string City {xpath('City')};
	string State {xpath('State')};
	string Zip {xpath('Zip')};
	string County {xpath('County')};
	string CensusTract {xpath('CensusTract')};
end;
		
export t_PropertyDataSources := record
	string LivingArea {xpath('LivingArea')};
	string Stories {xpath('Stories')};
	string Bedrooms {xpath('Bedrooms')};
	string Bathrooms {xpath('Bathrooms')};
	string Fireplaces {xpath('Fireplaces')};
	string Pool {xpath('Pool')};
	string AC {xpath('AC')};
	string Age {xpath('Age')};
end;
		
export t_PropertyAttributes := record
	integer LivingArea {xpath('LivingArea')};
	real8 Stories {xpath('Stories')};
	integer Bedrooms {xpath('Bedrooms')};
	real8 Bathrooms {xpath('Bathrooms')};
	integer Fireplaces {xpath('Fireplaces')};
	boolean Pool {xpath('Pool')};
	boolean AC {xpath('AC')};
	integer Age {xpath('Age')};
	string Quality {xpath('Quality')};
	string Slope {xpath('Slope')};
end;
		
export t_PropertyAddition := record
	string Description {xpath('Description')};
	real4 Value {xpath('Value')};
end;
		
export t_StructureAttribute := record
	string Category {xpath('Category')};
	string Material {xpath('Material')};
	real8 Value {xpath('Value')};
	string Quality {xpath('Quality')};
	string Condition {xpath('Condition')};
	integer Age {xpath('Age')};
end;
		
export t_DetachedGarage := record
	string Description {xpath('Description')};
	dataset(t_StructureAttribute) StructureAttributes {xpath('StructureAttributes/StructureAttribute'), MAXCOUNT(85)};
end;
		
export t_PropertyIn := record
	string Reference {xpath('Reference')};
	integer PropertyId {xpath('PropertyId')};
	integer CoverageA {xpath('CoverageA')};
	t_PropertyAddressIn NameAddress {xpath('NameAddress')};
	t_PropertyAttributes PropertyAttributes {xpath('PropertyAttributes')};
	t_PropertyDataSources PropertyDataSources {xpath('PropertyDataSources')};
	dataset(t_PropertyAddition) PropertyAdditions {xpath('PropertyAdditions/PropertyAddition'), MAXCOUNT(250)};
	dataset(t_StructureAttribute) StructureAttributes {xpath('StructureAttributes/StructureAttribute'), MAXCOUNT(85)};
	dataset(t_DetachedGarage) DetachedGarages {xpath('DetachedGarages/DetachedGarage'), MAXCOUNT(20)};
end;
		
export t_PropertyReportIn := record
	boolean UsePublicData {xpath('UsePublicData')};
	boolean IncludeAttachment {xpath('IncludeAttachment')};
end;
		
export t_PropertyInfoIn := record
	dataset(t_PropertyIn) Properties {xpath('Properties/Property'), MAXCOUNT(1)};
	t_PropertyReportIn Report {xpath('Report')};
end;
		
export t_PropertyDocument := record
	t_PropertyInfoIn PropertyInfo {xpath('PropertyInfo')};
end;
		
export t_PropertyValueReportOptions := record (share.t_BaseOption)
end;
		
export t_ERCResponseInfo := record
	string Status {xpath('Status')};
	string ErrorCode {xpath('ErrorCode')};
	string ErrorDescription {xpath('ErrorDescription')};
end;
		
export t_PolicyInformation := record
	string OwnerName {xpath('OwnerName')};
	string PolicyReference {xpath('PolicyReference')};
	integer PolicyValue {xpath('PolicyValue')};
end;
		
export t_ERCSummary := record
	string ERC {xpath('ERC')};
	string Score {xpath('Score')};
	string Profit {xpath('Profit')};
	string Architect {xpath('Architect')};
	string IncludesTax {xpath('IncludesTax')};
	string ITV {xpath('ITV')};
	string Debris {xpath('Debris')};
	string ACV {xpath('ACV')};
	string ACVScore {xpath('ACVScore')};
	string Overhead {xpath('Overhead')};
end;
		
export t_PropertyCharacteristics := record
	string Residence {xpath('Residence')};
	integer Bedrooms {xpath('Bedrooms')};
	real8 Bathrooms {xpath('Bathrooms')};
	real8 Stories {xpath('Stories')};
	integer LivingArea {xpath('LivingArea')};
	integer Fireplaces {xpath('Fireplaces')};
	string Pool {xpath('Pool')};
	integer YearBuilt {xpath('YearBuilt')};
	string AC {xpath('AC')};
	string Quality {xpath('Quality')};
end;
		
export t_PropertyDetail := record
	string Structure {xpath('Structure')};
	string AttributeType {xpath('AttributeType')};
	string Material {xpath('Material')};
	string Description {xpath('Description')};
	string Quality {xpath('Quality')};
	string Condition {xpath('Condition')};
	string Value {xpath('Value')};
	string ERCValue {xpath('ERCValue')};
end;
		
export t_PropertyAddressOut := record
	string Street {xpath('Street')};
	string City {xpath('City')};
	string State {xpath('State')};
	string Zip {xpath('Zip')};
end;
		
export t_PropertyOut := record
	string PropertyId {xpath('PropertyId')};
	t_ERCResponseInfo Response {xpath('Response')};
	t_PropertyAddressOut Address {xpath('Address')};
	t_PolicyInformation PolicyInformation {xpath('PolicyInformation')};
	t_ERCSummary Summary {xpath('Summary')};
	t_PropertyCharacteristics PropertyCharacteristics {xpath('PropertyCharacteristics')};
	dataset(t_PropertyDetail) PropertyDetails {xpath('PropertyDetails/PropertyDetail'), MAXCOUNT(85)};
	string Attachment {xpath('Attachment')};
end;
		
export t_PropertyReportOut := record
	dataset(t_PropertyOut) Properties {xpath('Properties/Property'), MAXCOUNT(1)};
end;
		
export t_PropertyValueOut := record
	t_PropertyReportOut Report {xpath('Report')};
end;
		
export t_PropertyValueReportResponse := record
	share.t_ResponseHeader _Header {xpath('Header')};
	t_PropertyValueOut Result {xpath('Result')};
end;
		
export t_PropertyValueReportRequest := record (share.t_BaseRequest)
	t_PropertyValueReportOptions Options {xpath('Options')};
	t_PropertyDocument PropertyDocument {xpath('PropertyDocument')};
	integer PolicyId {xpath('PolicyId')};
end;
		
export t_PropertyValueReportResponseEx := record
	t_PropertyValueReportResponse response {xpath('response')};
end;
		

end;

/*** Not to be hand edited (changes will be lost on re-generation) ***/
/*** ECL Interface generated by esdl2ecl version 1.0 from property_value_report.xml. ***/
/*===================================================*/

