/*** Not to be hand edited (changes will be lost on re-generation) ***/
/*** ECL Interface generated by esdl2ecl version 1.0 from riskview.xml. ***/
/*===================================================*/

import iesp;

export riskview := MODULE
			
export t_Score := record
	string _Type {xpath('Type')};
	integer Value {xpath('Value')};
	dataset(iesp.share.t_RiskIndicator) RiskIndicators {xpath('RiskIndicators/RiskIndicator'), MAXCOUNT(1)};
end;
		
export t_ScoreHRI := record
	string _Type {xpath('Type')};
	integer Value {xpath('Value')};
	dataset(iesp.share.t_RiskIndicator) HighRiskIndicators {xpath('HighRiskIndicators/HighRiskIndicator'), MAXCOUNT(1)};
	dataset(iesp.share.t_SequencedRiskIndicator) SequencedHighRiskIndicators {xpath('HighRiskIndicators/HighRiskIndicator'), MAXCOUNT(1)};
end;
		
export t_Model := record
	string Name {xpath('Name')};
	dataset(t_Score) Scores {xpath('Scores/Score'), MAXCOUNT(1)};
end;
		
export t_ModelHRI := record
	string Name {xpath('Name')};
	dataset(t_ScoreHRI) Scores {xpath('Scores/Score'), MAXCOUNT(1)};
end;
		
export t_RiskViewOptions := record (iesp.share.t_BaseOption)
	iesp.riskview_share.t_RiskViewModels IncludeModels {xpath('IncludeModels')};
	string IntendedPurpose {xpath('IntendedPurpose')}; //values['Application','Prescreening','Portfolio Review','Insurance Application','Insurance Portfolio Review','Disclosure','Government','Collections','Tenant Screening','Healthcare Credit Transaction','Healthcare Legitimate Business Need','Rental Car Loss Damage Waiver','Employee or Volunteer Screening','Written Consent Prequalification','Rental Car','Written Consent','Child Support','Demand Deposit','Written Consent Direct to Consumer','Credit Application','']
	string DaytonRiskViewSubscriptionNumber {xpath('DaytonRiskViewSubscriptionNumber')};//hidden[internal]
end;
		
export t_RiskViewSearchBy := record
	iesp.share.t_Name Name {xpath('Name')};
	iesp.share.t_Address Address {xpath('Address')};
	iesp.share.t_Date DOB {xpath('DOB')};
	integer Age {xpath('Age')};
	string SSN {xpath('SSN')};
	string SSNLast4 {xpath('SSNLast4')};
	string DriverLicenseNumber {xpath('DriverLicenseNumber')};
	string2 DriverLicenseState {xpath('DriverLicenseState')};
	string IPAddress {xpath('IPAddress')};
	string HomePhone {xpath('HomePhone')};
	string WorkPhone {xpath('WorkPhone')};
	boolean UseDOBFilter {xpath('UseDOBFilter')};
	integer DOBRadius {xpath('DOBRadius')};
end;
		
export t_RiskViewResult := record
	t_RiskViewSearchBy InputEcho {xpath('InputEcho')};
	dataset(t_Model) Models {xpath('Models/Model'), MAXCOUNT(1)};
	dataset(t_ModelHRI) ModelsWithHRI {xpath('Models/Model'), MAXCOUNT(1)};
	iesp.share_fcra.t_FcraConsumer Consumer {xpath('Consumer')};//hidden[ecl_only]
end;
		
export t_RiskViewResponse := record
	iesp.share.t_ResponseHeader _Header {xpath('Header')};
	t_RiskViewResult Result {xpath('Result')};
end;
		
export t_RiskViewAttribModels := record (iesp.riskview_share.t_RiskViewModels)
	boolean Attributes {xpath('Attributes')};
end;
		
export t_RiskViewAttribOptions := record (iesp.share.t_BaseOption)
	t_RiskViewAttribModels IncludeModels {xpath('IncludeModels')};
	dataset(iesp.share.t_StringArrayItem) RequestedAttributeGroups {xpath('RequestedAttributeGroups/Name'), MAXCOUNT(1)};
	string AttributesVersionRequest {xpath('AttributesVersionRequest')};
	boolean AddressAppend {xpath('AddressAppend')};
	string IntendedPurpose {xpath('IntendedPurpose')}; //values['Application','Prescreening','Portfolio Review','Insurance Application','Insurance Portfolio Review','Disclosure','Government','Collections','Tenant Screening','Healthcare Credit Transaction','Healthcare Legitimate Business Need','Rental Car Loss Damage Waiver','Employee or Volunteer Screening','Written Consent Prequalification','Rental Car','Written Consent','Child Support','Demand Deposit','Written Consent Direct to Consumer','Credit Application','']
end;
		
export t_RiskViewAttribResult := record (t_RiskViewResult)
	dataset(iesp.share.t_AttributeGroup) AttributeGroups {xpath('AttributeGroups/AttributeGroup'), MAXCOUNT(1)};
	dataset(iesp.share.t_NameValuePair) Attributes {xpath('Attributes/Attribute'), MAXCOUNT(1)};
	iesp.share_fcra.t_FcraConsumer Consumer {xpath('Consumer')};//hidden[ecl_only]
end;
		
export t_RiskViewAttribResponse := record
	iesp.share.t_ResponseHeader _Header {xpath('Header')};
	t_RiskViewAttribResult Result {xpath('Result')};
end;
		
export t_RiskViewPropSearchBy := record
	iesp.share.t_Address Address {xpath('Address')};
end;
		
export t_RiskViewPropRptOptions := record (iesp.share.t_BaseOption)
end;
		
export t_AVMInfo := record
	integer AutomatedValuation {xpath('AutomatedValuation')};
	integer Score {xpath('Score')};
end;
		
export t_RiskViewPropertyInfo := record
	string CountyName {xpath('CountyName')};
	string AlternateParcelNumber {xpath('AlternateParcelNumber')};
	string LegalDescription {xpath('LegalDescription')};
	string LegalCityMunicipalityTownship {xpath('LegalCityMunicipalityTownship')};
	string LegalSubdivisionName {xpath('LegalSubdivisionName')};
	string LandUse {xpath('LandUse')};
	boolean OwnerOccupied {xpath('OwnerOccupied')};
	iesp.share.t_Date SaleDate {xpath('SaleDate')};
	string SalePrice {xpath('SalePrice')};
	string AssessedLandValue {xpath('AssessedLandValue')};
	string AssessedImprovementValue {xpath('AssessedImprovementValue')};
	string AssessedTotalValue {xpath('AssessedTotalValue')};
	integer AssessedValueYear {xpath('AssessedValueYear')};
	string MarketLandValue {xpath('MarketLandValue')};
	string MarketImprovementValue {xpath('MarketImprovementValue')};
	string MarketTotalValue {xpath('MarketTotalValue')};
	integer MarketValueYear {xpath('MarketValueYear')};
	string TaxAmount {xpath('TaxAmount')};
	integer TaxYear {xpath('TaxYear')};
	string LandAcres {xpath('LandAcres')};
	string LandSquareFootage {xpath('LandSquareFootage')};
	string LandDimensions {xpath('LandDimensions')};
	string BuildingArea {xpath('BuildingArea')};
	string BuildingAreaDescription {xpath('BuildingAreaDescription')};
	integer YearBuilt {xpath('YearBuilt')};
	string NoOfBuildings {xpath('NoOfBuildings')};
	string NoOfStories {xpath('NoOfStories')};
	string NoOfUnits {xpath('NoOfUnits')};
	string NoOfRooms {xpath('NoOfRooms')};
	string NoOfBedrooms {xpath('NoOfBedrooms')};
	string NoOfBaths {xpath('NoOfBaths')};
	string ParkingNoOfCars {xpath('ParkingNoOfCars')};
	string GarageDescription {xpath('GarageDescription')};
	string PoolDescription {xpath('PoolDescription')};
	string StyleDescription {xpath('StyleDescription')};
	string TypeConstructionDescription {xpath('TypeConstructionDescription')};
	string ExteriorWallsDescription {xpath('ExteriorWallsDescription')};
	string FoundationDescription {xpath('FoundationDescription')};
	string RoofCoverDescription {xpath('RoofCoverDescription')};
	string RoofTypeDescription {xpath('RoofTypeDescription')};
	string HeatingDescription {xpath('HeatingDescription')};
	string HeatingFuelTypeDescription {xpath('HeatingFuelTypeDescription')};
	string AirConditioningDescription {xpath('AirConditioningDescription')};
	string BasementDescription {xpath('BasementDescription')};
	string FireplaceIndicator {xpath('FireplaceIndicator')};
end;
		
export t_RiskViewPropertyResult := record
	t_RiskViewPropSearchBy InputEcho {xpath('InputEcho')};
	t_AVMInfo AvmInformation {xpath('AvmInformation')};
	t_RiskViewPropertyInfo PropertyInformation {xpath('PropertyInformation')};
end;
		
export t_RiskViewPropRptResponse := record
	iesp.share.t_ResponseHeader _Header {xpath('Header')};
	t_RiskViewPropertyResult Result {xpath('Result')};
end;
		
export t_FCRAPhoneHistoryOptions := record (iesp.share.t_BaseOption)
end;
		
export t_FCRAPhoneHistorySearchBy := record
	string UniqueId {xpath('UniqueId')};
	iesp.share.t_Name Name {xpath('Name')};
	iesp.share.t_Address Address {xpath('Address')};
	string SSN {xpath('SSN')};
	iesp.share.t_Date DOB {xpath('DOB')};
	string Phone10 {xpath('Phone10')};
end;
		
export t_PhoneHistory := record
	iesp.share.t_Name Name {xpath('Name')};
	iesp.share.t_Address Address {xpath('Address')};
	iesp.share.t_Date DateLastSeen {xpath('DateLastSeen')};
	iesp.share.t_Date DateFirstSeen {xpath('DateFirstSeen')};
	string UniqueId {xpath('UniqueId')};
	string HouseholdId {xpath('HouseholdId')};
	string Phone10 {xpath('Phone10')};
	string OmitAddress {xpath('OmitAddress')};
	string OmitPhone {xpath('OmitPhone')};
	string OmitLocality {xpath('OmitLocality')};
	dataset(iesp.share.t_StringArrayItem) ListingTypes {xpath('ListingTypes/ListingType'), MAXCOUNT(1)};
	string PublishCode {xpath('PublishCode')};
end;
		
export t_FCRAPhoneHistoryResult := record
	t_FCRAPhoneHistorySearchBy InputEcho {xpath('InputEcho')};
	dataset(t_PhoneHistory) PhoneHistories {xpath('PhoneHistories/PhoneHistory'), MAXCOUNT(1)};
end;
		
export t_FCRAPhoneHistoryResponse := record
	iesp.share.t_ResponseHeader _Header {xpath('Header')};
	t_FCRAPhoneHistoryResult Result {xpath('Result')};
end;
		
export t_LienJudgmentBankruptcyOptions := record (iesp.share.t_BaseOption)
end;
		
export t_LienJudgmentBankruptcySearchBy := record
	iesp.share.t_Name Name {xpath('Name')};
	iesp.share.t_Address Address {xpath('Address')};
	string SSN {xpath('SSN')};
	iesp.share.t_Date DOB {xpath('DOB')};
	string Phone10 {xpath('Phone10')};
end;
		
export t_FilingInfo := record
	iesp.share.t_Date OriginalDate {xpath('OriginalDate')};
	string Number {xpath('Number')};
	string OriginalNumber {xpath('OriginalNumber')};
	string _Type {xpath('Type')};
	string Book {xpath('Book')};
	string Page {xpath('Page')};
	string Status {xpath('Status')};
	string StatusDescription {xpath('StatusDescription')};
	string Jurisdiction {xpath('Jurisdiction')};
	string JurisdictionName {xpath('JurisdictionName')};
	string County {xpath('County')};
	string State {xpath('State')};
end;
		
export t_DebtorInfo := record
	iesp.share.t_Name Name {xpath('Name')};
	iesp.share.t_Address Address {xpath('Address')};
	string SSN {xpath('SSN')};
end;
		
export t_LienJudgment := record
	t_FilingInfo Filing {xpath('Filing')};
	t_DebtorInfo Debtor {xpath('Debtor')};
	integer Amount {xpath('Amount')};
	string CaseNumber {xpath('CaseNumber')};
end;
		
export t_RvBankruptcy := record
	string FilerType {xpath('FilerType')};
	string FilingStatus {xpath('FilingStatus')};
	iesp.share.t_Date FilingDate {xpath('FilingDate')};
	iesp.share.t_Date OriginalFilingDate {xpath('OriginalFilingDate')};
	t_DebtorInfo Debtor {xpath('Debtor')};
	string CaseNumber {xpath('CaseNumber')};
	string CourtCode {xpath('CourtCode')};
	string CourtName {xpath('CourtName')};
	string CourtLocation {xpath('CourtLocation')};
	string CourtState {xpath('CourtState')};
	string Chapter {xpath('Chapter')};
	string Disposition {xpath('Disposition')};
	iesp.share.t_Date ClosedDate {xpath('ClosedDate')};
	iesp.share.t_Date ConvertedDate {xpath('ConvertedDate')};
	string CorpFlag {xpath('CorpFlag')};
end;
		
export t_LienJudgmentBankruptcyResult := record
	t_LienJudgmentBankruptcySearchBy InputEcho {xpath('InputEcho')};
	boolean HasBankruptcy {xpath('HasBankruptcy')};
	boolean HasFederalTaxLien {xpath('HasFederalTaxLien')};
	integer FederalTaxLienAmount {xpath('FederalTaxLienAmount')};
	boolean HasStateTaxLien {xpath('HasStateTaxLien')};
	integer StateTaxLienAmount {xpath('StateTaxLienAmount')};
	boolean HasCountyTaxLien {xpath('HasCountyTaxLien')};
	integer CountyTaxLienAmount {xpath('CountyTaxLienAmount')};
	boolean HasChildSupport {xpath('HasChildSupport')};
	integer ChildSupportAmount {xpath('ChildSupportAmount')};
	dataset(t_RvBankruptcy) Bankruptcies {xpath('Bankruptcies/Bankruptcy'), MAXCOUNT(1)};
	dataset(t_LienJudgment) LiensJudgments {xpath('LiensJudgments/LienJudgment'), MAXCOUNT(1)};
	boolean Hit {xpath('Hit')};
end;
		
export t_RiskViewLienJudgmentBankruptcyReportResponse := record
	iesp.share.t_ResponseHeader _Header {xpath('Header')};
	t_LienJudgmentBankruptcyResult Result {xpath('Result')};
end;
		
export t_RiskViewRequest := record (iesp.share.t_BaseRequest)
	t_RiskViewOptions Options {xpath('Options')};
	t_RiskViewSearchBy SearchBy {xpath('SearchBy')};
end;
		
export t_RiskViewAttribRequest := record (iesp.share.t_BaseRequest)
	t_RiskViewAttribOptions Options {xpath('Options')};
	t_RiskViewSearchBy SearchBy {xpath('SearchBy')};
end;
		
export t_RiskViewPropRptRequest := record (iesp.share.t_BaseRequest)
	t_RiskViewPropRptOptions Options {xpath('Options')};
	t_RiskViewPropSearchBy SearchBy {xpath('SearchBy')};
end;
		
export t_FCRAPhoneHistoryReportRequest := record (iesp.share.t_BaseRequest)
	t_FCRAPhoneHistoryOptions Options {xpath('Options')};
	t_FCRAPhoneHistorySearchBy SearchBy {xpath('SearchBy')};
end;
		
export t_RiskViewLienJudgmentBankruptcyReportRequest := record (iesp.share.t_BaseRequest)
	t_LienJudgmentBankruptcyOptions Options {xpath('Options')};
	t_LienJudgmentBankruptcySearchBy SearchBy {xpath('SearchBy')};
end;
		
export t_RiskViewResponseEx := record
	t_RiskViewResponse response {xpath('response')};
end;
		
export t_RiskViewAttribResponseEx := record
	t_RiskViewAttribResponse response {xpath('response')};
end;
		
export t_RiskViewPropRptResponseEx := record
	t_RiskViewPropRptResponse response {xpath('response')};
end;
		
export t_FCRAPhoneHistoryReportResponseEx := record
	t_FCRAPhoneHistoryResponse response {xpath('response')};
end;
		
export t_RiskViewLienJudgmentBankruptcyReportResponseEx := record
	t_RiskViewLienJudgmentBankruptcyReportResponse response {xpath('response')};
end;
		

end;

/*** Not to be hand edited (changes will be lost on re-generation) ***/
/*** ECL Interface generated by esdl2ecl version 1.0 from riskview.xml. ***/
/*===================================================*/

