/*** Not to be hand edited (changes will be lost on re-generation) ***/
/*** ECL Interface generated by esdl2ecl version 1.0 from ws_credit_share.xml. ***/
/*===================================================*/

import iesp;
export ws_credit_share := MODULE
			
export t_EclErrorStruct := record
	string50 FailCode {xpath('FailCode')};
	string500 FailMessage1 {xpath('FailMessage1')};
	string500 FailMessage2 {xpath('FailMessage2')};
end;
		

end;

/*** Not to be hand edited (changes will be lost on re-generation) ***/
/*** ECL Interface generated by esdl2ecl version 1.0 from ws_credit_share.xml. ***/
/*===================================================*/

