IMPORT Insurance_Certification,address,AID,bipv2;

EXPORT layouts_certification := MODULE

	SHARED max_size := _Dataset().max_record_size;

	EXPORT Input := RECORD,MAXLENGTH(40000)
			STRING	DartID;
			UNSIGNED8 DateAdded;
			UNSIGNED8 DateUpdated;
			STRING	Website;
			STRING	State;
			UNSIGNED8	LNInsCertRecordID;
			STRING	ProfileLastUpdated;
			STRING	SIID;
			STRING	SIPStatusCode;
			STRING	WCBEmpNumber;
			STRING	UBINumber;
			STRING	CofANumber;
			STRING	USDOTNumber;
			STRING	BusinessName;   /* normalize */
			STRING	DBA;            /* normalize */
			STRING	AddressLine1;		 
			STRING	AddressLine2;		 
			STRING	AddressCity;		 
			STRING	AddressState;		 
			STRING	AddressZip;			 
			STRING	Zip4;						
			STRING	Phone1;
			STRING	Phone2;
			STRING	Phone3;
			STRING	Fax1;
			STRING	Fax2;
			STRING	Email1;
			STRING	Email2;
			STRING	BusinessType;
			STRING	NameFirst;			/* normalize */
			STRING	NameMiddle;			 
			STRING	NameLast;				 
			STRING	NameSuffix;			 
			STRING	NameTitle;
			STRING	MailingAddress1; 			 
			STRING	MailingAddress2;			 
			STRING	MailingAddressCity;		 
			STRING	MailingAddressState;	 
			STRING	MailingAddressZip;		 
			STRING	MailingAddressZip4;		 
			STRING	ContactNameFirst;			/* normalize */
			STRING	ContactNameMiddle;		 
			STRING	ContactNameLast;			 
			STRING	ContactNameSuffix;		 
			STRING	ContactBusinessName;	/* normalize */
			STRING	ContactAddressLine1;	 
			STRING	ContactAddressLine2;	 
			STRING	ContactCity;					 
			STRING	ContactState;					 
			STRING	ContactZip;						 
			STRING	ContactZip4;					 
			STRING	ContactPhone;					
			STRING	ContactFax;
			STRING	ContactEmail;
			STRING	PolicyHolderNameFirst;
			STRING	PolicyHolderNameMiddle;
			STRING	PolicyHolderNameLast;
			STRING	PolicyHolderNameSuffix;
			STRING	StatePolicyFileNumber;
			STRING	CoverageInjuryIllnessDate;
			STRING	SelfInsuranceGroup;
			STRING	SelfInsuranceGroupPhone;
			STRING	SelfInsuranceGroupID;
			STRING	NumberofEmployees;
			STRING	LicensedContractor;
			STRING	MCOName;
			STRING	MCONumber;
			STRING	MCOAddressLine1;
			STRING	MCOAddressLine2;
			STRING	MCOCity;
			STRING	MCOState;
			STRING	MCOZip;
			STRING	MCOZip4;
			STRING	MCOPhone;
			STRING	GoverningClassCode;
			STRING	LicenseNumber;
			STRING	Class;
			STRING	ClassificationDescription;
			STRING	LicenseStatus;
			STRING	LicenseAdditionalInfo;
			STRING	LicenseIssueDate;
			STRING	LicenseExpirationDate;
			STRING	NAICSCode;
			STRING	OfficerExemptFirstName1;
			STRING	OfficerExemptLastName1;
			STRING	OfficerExemptMiddleName1;
			STRING	OfficerExemptTitle1;
			STRING	OfficerExemptEffectiveDate1;
			STRING	OfficerExemptTerminationDate1;
			STRING	OfficerExemptType1;
			STRING	OfficerExemptBusinessActivities1;
			STRING	OfficerExemptFirstName2;
			STRING	OfficerExemptLastName2;
			STRING	OfficerExemptMiddleName2;
			STRING	OfficerExemptTitle2;
			STRING	OfficerExemptEffectiveDate2;
			STRING	OfficerExemptTerminationDate2;
			STRING	OfficerExemptType2;
			STRING	OfficerExemptBusinessActivities2;
			STRING	OfficerExemptFirstName3;
			STRING	OfficerExemptLastName3;
			STRING	OfficerExemptMiddleName3;
			STRING	OfficerExemptTitle3;
			STRING	OfficerExemptEffectiveDate3;
			STRING	OfficerExemptTerminationDate3;
			STRING	OfficerExemptType3;
			STRING	OfficerExemptBusinessActivities3;
			STRING	OfficerExemptFirstName4;
			STRING	OfficerExemptLastName4;
			STRING	OfficerExemptMiddleName4;
			STRING	OfficerExemptTitle4;
			STRING	OfficerExemptEffectiveDate4;
			STRING	OfficerExemptTerminationDate4;
			STRING	OfficerExemptType4;
			STRING	OfficerExemptBusinessActivities4;
			STRING	OfficerExemptFirstName5;
			STRING	OfficerExemptLastName5;
			STRING	OfficerExemptMiddleName5;
			STRING	OfficerExemptTitle5;
			STRING	OfficerExemptEffectiveDate5;
			STRING	OfficerExemptTerminationDate5;
			STRING	OfficerExemptType5;
			STRING	OfficerExemptBusinessActivities5;
			STRING	DBA1;
			STRING	DBADateFrom1;
			STRING	DBADateTo1;
			STRING	DBAType1;
			STRING	DBA2;
			STRING	DBADateFrom2;
			STRING	DBADateTo2;
			STRING	DBAType2;
			STRING	DBA3;
			STRING	DBADateFrom3;
			STRING	DBADateTo3;
			STRING	DBAType3;
			STRING	DBA4;
			STRING	DBADateFrom4;
			STRING	DBADateTo4;
			STRING	DBAType4;
			STRING	DBA5;
			STRING	DBADateFrom5;
			STRING	DBADateTo5;
			STRING	DBAType5;
			STRING	SubsidiaryName1;
			STRING	SubsidiaryStartDate1;
			STRING	SubsidiaryName2;
			STRING	SubsidiaryStartDate2;
			STRING	SubsidiaryName3;
			STRING	SubsidiaryStartDate3;
			STRING	SubsidiaryName4;
			STRING	SubsidiaryStartDate4;
			STRING	SubsidiaryName5;
			STRING	SubsidiaryStartDate5;
			STRING	SubsidiaryName6;
			STRING	SubsidiaryStartDate6;
			STRING	SubsidiaryName7;
			STRING	SubsidiaryStartDate7;
			STRING	SubsidiaryName8;				
			STRING	SubsidiaryStartDate8;
			STRING	SubsidiaryName9;				
			STRING	SubsidiaryStartDate9;
			STRING	SubsidiaryName10;				
			STRING	SubsidiaryStartDate10;
	END;

	EXPORT TempRec := RECORD
		unsigned8	unique_id;
		Input;
	END;
	
  EXPORT NormRec	:=	RECORD 
	/* Normalize the records to split records into one for each type of name/address */
		  UNSIGNED8	unique_id;
			STRING1		Norm_Type;           /* 'B' for Business or 'C' for Contact or 'D' for DBA */
			STRING205 Norm_BusinessName;   
			STRING30  Norm_FirstName;       
			STRING1		Norm_Middle;
			STRING30	Norm_Last;
			STRING10	Norm_Suffix;
			STRING75  Norm_Address1;
			STRING75  Norm_Address2;
			STRING50  Norm_City;
			STRING2   Norm_State;
			STRING5   Norm_Zip;
			STRING5   Norm_Zip4;
			STRING15  Norm_Phone;
			STRING15	DartID;
			UNSIGNED8 DateAdded;
			UNSIGNED8 DateUpdated;
			STRING80	Website;
			STRING2		State;
			UNSIGNED8	LNInsCertRecordID;
			STRING8		ProfileLastUpdated;
			STRING10	SIID;
			STRING15	SIPStatusCode;
			STRING15	WCBEmpNumber;
			STRING15	UBINumber;
			STRING25	CofANumber;
			STRING15	USDOTNumber;
			STRING15	Phone2;
			STRING15	Phone3;
			STRING15	Fax1;
			STRING15	Fax2;
			STRING50	Email1;
			STRING50	Email2;
			STRING40	BusinessType;
			STRING35	NameTitle;
			STRING75	MailingAddress1;
			STRING75	MailingAddress2;
			STRING50	MailingAddressCity;
			STRING2		MailingAddressState;
			STRING5		MailingAddressZip;
			STRING4		MailingAddressZip4;
			STRING15	ContactFax;
			STRING50	ContactEmail;
			STRING20	PolicyHolderNameFirst;
			STRING1		PolicyHolderNameMiddle;
			STRING30	PolicyHolderNameLast;
			STRING10	PolicyHolderNameSuffix;
			STRING30	StatePolicyFileNumber;
			STRING8		CoverageInjuryIllnessDate;
			STRING80	SelfInsuranceGroup;
			STRING15	SelfInsuranceGroupPhone;
			STRING25	SelfInsuranceGroupID;
			STRING60	NumberofEmployees;
			STRING10	LicensedContractor;
			STRING50	MCOName;
			STRING10	MCONumber;
			STRING75	MCOAddressLine1;
			STRING75	MCOAddressLine2;
			STRING50	MCOCity;
			STRING2		MCOState;
			STRING5		MCOZip;
			STRING4		MCOZip4;
			STRING15 	MCOPhone;
			STRING8		GoverningClassCode;
			STRING8		LicenseNumber;
			STRING8		Class;
			STRING8		ClassificationDescription;
			STRING8		LicenseStatus;
			STRING8		LicenseAdditionalInfo;
			STRING8		LicenseIssueDate;
			STRING8		LicenseExpirationDate;
			STRING8		NAICSCode;
			STRING8		OfficerExemptFirstName1;
			STRING8		OfficerExemptLastName1;
			STRING8		OfficerExemptMiddleName1;
			STRING8		OfficerExemptTitle1;
			STRING8		OfficerExemptEffectiveDate1;
			STRING8		OfficerExemptTerminationDate1;
			STRING8		OfficerExemptType1;
			STRING8		OfficerExemptBusinessActivities1;
			STRING8		OfficerExemptFirstName2;
			STRING8		OfficerExemptLastName2;
			STRING8		OfficerExemptMiddleName2;
			STRING8		OfficerExemptTitle2;
			STRING8		OfficerExemptEffectiveDate2;
			STRING8 	OfficerExemptTerminationDate2;
			STRING8		OfficerExemptType2;
			STRING8		OfficerExemptBusinessActivities2;
			STRING8		OfficerExemptFirstName3;
			STRING8		OfficerExemptLastName3;
			STRING8		OfficerExemptMiddleName3;
			STRING8		OfficerExemptTitle3;
			STRING8		OfficerExemptEffectiveDate3;
			STRING8		OfficerExemptTerminationDate3;
			STRING8		OfficerExemptType3;
			STRING8		OfficerExemptBusinessActivities3;
			STRING8		OfficerExemptFirstName4;
			STRING8		OfficerExemptLastName4;
			STRING8		OfficerExemptMiddleName4;
			STRING8		OfficerExemptTitle4;
			STRING8		OfficerExemptEffectiveDate4;
			STRING8		OfficerExemptTerminationDate4;
			STRING8		OfficerExemptType4;
			STRING8		OfficerExemptBusinessActivities4;
			STRING8		OfficerExemptFirstName5;
			STRING8		OfficerExemptLastName5;
			STRING8		OfficerExemptMiddleName5;
			STRING8		OfficerExemptTitle5;
			STRING8		OfficerExemptEffectiveDate5;
			STRING8		OfficerExemptTerminationDate5;
			STRING8		OfficerExemptType5;
			STRING8		OfficerExemptBusinessActivities5;
			STRING8		DBA1;
			STRING8		DBADateFrom1;
			STRING8		DBADateTo1;
			STRING8		DBAType1;
			STRING8		DBA2;
			STRING8		DBADateFrom2;
			STRING8		DBADateTo2;
			STRING8		DBAType2;
			STRING8		DBA3;
			STRING8		DBADateFrom3;
			STRING8		DBADateTo3;
			STRING8		DBAType3;
			STRING8		DBA4;
			STRING8		DBADateFrom4;
			STRING8		DBADateTo4;
			STRING8		DBAType4;
			STRING8		DBA5;
			STRING8		DBADateFrom5;
			STRING8		DBADateTo5;
			STRING8		DBAType5;
			STRING50 	SubsidiaryName1;
			STRING8		SubsidiaryStartDate1;
			STRING50	SubsidiaryName2;
			STRING8		SubsidiaryStartDate2;
			STRING50	SubsidiaryName3;
			STRING8		SubsidiaryStartDate3;
			STRING50	SubsidiaryName4;
			STRING8		SubsidiaryStartDate4;
			STRING50	SubsidiaryName5;
			STRING8		SubsidiaryStartDate5;
			STRING50	SubsidiaryName6;
			STRING8		SubsidiaryStartDate6;
			STRING50	SubsidiaryName7;
			STRING8		SubsidiaryStartDate7;
			STRING50	SubsidiaryName8;
			STRING8		SubsidiaryStartDate8;
			STRING50	SubsidiaryName9;
			STRING8		SubsidiaryStartDate9;
			STRING50	SubsidiaryName10;
			STRING8		SubsidiaryStartDate10;
	END;
	
  EXPORT Temp2	:=	RECORD /* Add append mail address fields */
			NormRec;
			STRING100		Append_MailAddress1;
			STRING50		Append_MailAddressLast;
			AID.Common.xAID		Append_MailRawAID;		
			AID.Common.xAID   Append_MailACEAID;   
	END;

	EXPORT Base := RECORD,MAXLENGTH(40000)
			UNSIGNED8 Date_FirstSeen;
			UNSIGNED8 Date_LastSeen;
			UNSIGNED6 bdid 	:= 0;
			UNSIGNED6 did   := 0;
			BIPV2.IDlayouts.l_xlink_ids;	
			Temp2;
	END;
	
	EXPORT	KeyBuild := RECORD
			Base;
			STRING10	m_prim_range; 
			STRING2		m_predir;	
			STRING28	m_prim_name;	
			STRING4		m_addr_suffix; 
			STRING2		m_postdir;	
			STRING10	m_unit_desig;	
			STRING8		m_sec_range;	
			STRING25	m_p_city_name;	
			STRING25	m_v_city_name; 
			STRING2		m_st;	
			STRING5		m_zip;	
			STRING4		m_zip4;	
			STRING4		m_cart;	
			STRING1		m_cr_sort_sz;	
			STRING4		m_lot;	
			STRING1		m_lot_order;	
			STRING2		m_dbpc;	
			STRING1		m_chk_digit;	
			STRING2		m_rec_type;	
			STRING2		m_fips_state;	
			STRING3		m_fips_county;	
			STRING10	m_geo_lat;	
			STRING11	m_geo_long;	
			STRING4		m_msa;	
			STRING7		m_geo_blk;	
			STRING1		m_geo_match;	
			STRING4		m_err_stat;		
	END;
	
	EXPORT UniqueId := RECORD,MAXLENGTH(max_size)
			UNSIGNED8	BH_Unique_id;
			KeyBuild;
	END;
	
END;
