//This is the code to execute in a builder window
#OPTION('multiplePersistInstances', FALSE);
#workunit('name','Scrubs_Phonesplus_v2_Base.BWR_Hygiene - Hygiene & Stats - SALT V3.0 A21');
IMPORT Scrubs_Phonesplus_v2_Base,SALT30;
// First create an instantiated hygiene module
  infile := Scrubs_Phonesplus_v2_Base.In_File_phonesplus_Base;
  h := Scrubs_Phonesplus_v2_Base.Hygiene(infile);
  p := h.AllProfiles; // Detailed profile of every field
  OUTPUT(h.Summary('SummaryReport'),ALL);
  OUTPUT(h.SourceCounts,ALL,NAMED('SourceCounts'));
  OUTPUT(h.CrossLinkingPotential,ALL,NAMED('CrossLinkingPotential'));
  OUTPUT(h.invSummary,NAMED('InvertedSummary'),ALL);
  OUTPUT(p,NAMED('AllProfiles'),ALL); // Detailed profile of every field
  OUTPUT(h.Correlations,NAMED('Correlations'),ALL); // Which fields are related to which other fields
  OUTPUT(h.ValidityErrors,NAMED('ValidityErrors'),ALL); // Violations of FieldType statements
  OUTPUT(SALT30.MAC_Character_Counts.EclRecord(p,'Layout_File_phonesplus_Base'),NAMED('OptimizedLayout'));// File layout suggested by data
  // Produces field types that match the most common 99.9% of your data. Change to 100 to match all your data
  OUTPUT(SALT30.MAC_Character_Counts.FieldTypes(p,99.9),NAMED('Types'));
  // ****** Cross Tabs *******
  // It is possible to create a cross table between any two fields, see documentation on SALT30.MAC_CrossTab
  // These commented out lines will create crosstabs from the sourcefield to each individual field
  // IF you find yourself using ALL of these a LOT - let me know, I can make the 'all' case faster
   Examples := 10;
  //  OUTPUT(SALT30.MAC_CrossTab(infile,vendor,in_flag,Examples),NAMED('in_flagByvendor'));
  //  OUTPUT(SALT30.MAC_CrossTab(infile,vendor,confidencescore,Examples),NAMED('confidencescoreByvendor'));
  //  OUTPUT(SALT30.MAC_CrossTab(infile,vendor,rules,Examples),NAMED('rulesByvendor'));
  //  OUTPUT(SALT30.MAC_CrossTab(infile,vendor,npa,Examples),NAMED('npaByvendor'));
  //  OUTPUT(SALT30.MAC_CrossTab(infile,vendor,phone7,Examples),NAMED('phone7Byvendor'));
  //  OUTPUT(SALT30.MAC_CrossTab(infile,vendor,cellphone,Examples),NAMED('cellphoneByvendor'));
  //  OUTPUT(SALT30.MAC_CrossTab(infile,vendor,cellphoneidkey,Examples),NAMED('cellphoneidkeyByvendor'));
  //  OUTPUT(SALT30.MAC_CrossTab(infile,vendor,phone7_did_key,Examples),NAMED('phone7_did_keyByvendor'));
  //  OUTPUT(SALT30.MAC_CrossTab(infile,vendor,pdid,Examples),NAMED('pdidByvendor'));
  //  OUTPUT(SALT30.MAC_CrossTab(infile,vendor,did,Examples),NAMED('didByvendor'));
  //  OUTPUT(SALT30.MAC_CrossTab(infile,vendor,did_score,Examples),NAMED('did_scoreByvendor'));
  //  OUTPUT(SALT30.MAC_CrossTab(infile,vendor,datefirstseen,Examples),NAMED('datefirstseenByvendor'));
  //  OUTPUT(SALT30.MAC_CrossTab(infile,vendor,datelastseen,Examples),NAMED('datelastseenByvendor'));
  //  OUTPUT(SALT30.MAC_CrossTab(infile,vendor,datevendorlastreported,Examples),NAMED('datevendorlastreportedByvendor'));
  //  OUTPUT(SALT30.MAC_CrossTab(infile,vendor,datevendorfirstreported,Examples),NAMED('datevendorfirstreportedByvendor'));
  //  OUTPUT(SALT30.MAC_CrossTab(infile,vendor,dt_nonglb_last_seen,Examples),NAMED('dt_nonglb_last_seenByvendor'));
  //  OUTPUT(SALT30.MAC_CrossTab(infile,vendor,glb_dppa_flag,Examples),NAMED('glb_dppa_flagByvendor'));
  //  OUTPUT(SALT30.MAC_CrossTab(infile,vendor,glb_dppa_all,Examples),NAMED('glb_dppa_allByvendor'));
  //  OUTPUT(SALT30.MAC_CrossTab(infile,vendor,vendor,Examples),NAMED('vendorByvendor'));
  //  OUTPUT(SALT30.MAC_CrossTab(infile,vendor,src,Examples),NAMED('srcByvendor'));
  //  OUTPUT(SALT30.MAC_CrossTab(infile,vendor,src_all,Examples),NAMED('src_allByvendor'));
  //  OUTPUT(SALT30.MAC_CrossTab(infile,vendor,src_cnt,Examples),NAMED('src_cntByvendor'));
  //  OUTPUT(SALT30.MAC_CrossTab(infile,vendor,src_rule,Examples),NAMED('src_ruleByvendor'));
  //  OUTPUT(SALT30.MAC_CrossTab(infile,vendor,append_avg_source_conf,Examples),NAMED('append_avg_source_confByvendor'));
  //  OUTPUT(SALT30.MAC_CrossTab(infile,vendor,append_max_source_conf,Examples),NAMED('append_max_source_confByvendor'));
  //  OUTPUT(SALT30.MAC_CrossTab(infile,vendor,append_min_source_conf,Examples),NAMED('append_min_source_confByvendor'));
  //  OUTPUT(SALT30.MAC_CrossTab(infile,vendor,append_total_source_conf,Examples),NAMED('append_total_source_confByvendor'));
  //  OUTPUT(SALT30.MAC_CrossTab(infile,vendor,orig_dt_last_seen,Examples),NAMED('orig_dt_last_seenByvendor'));
  //  OUTPUT(SALT30.MAC_CrossTab(infile,vendor,did_type,Examples),NAMED('did_typeByvendor'));
  //  OUTPUT(SALT30.MAC_CrossTab(infile,vendor,origname,Examples),NAMED('orignameByvendor'));
  //  OUTPUT(SALT30.MAC_CrossTab(infile,vendor,address1,Examples),NAMED('address1Byvendor'));
  //  OUTPUT(SALT30.MAC_CrossTab(infile,vendor,address2,Examples),NAMED('address2Byvendor'));
  //  OUTPUT(SALT30.MAC_CrossTab(infile,vendor,address3,Examples),NAMED('address3Byvendor'));
  //  OUTPUT(SALT30.MAC_CrossTab(infile,vendor,origcity,Examples),NAMED('origcityByvendor'));
  //  OUTPUT(SALT30.MAC_CrossTab(infile,vendor,origstate,Examples),NAMED('origstateByvendor'));
  //  OUTPUT(SALT30.MAC_CrossTab(infile,vendor,origzip,Examples),NAMED('origzipByvendor'));
  //  OUTPUT(SALT30.MAC_CrossTab(infile,vendor,orig_phone,Examples),NAMED('orig_phoneByvendor'));
  //  OUTPUT(SALT30.MAC_CrossTab(infile,vendor,dob,Examples),NAMED('dobByvendor'));
  //  OUTPUT(SALT30.MAC_CrossTab(infile,vendor,agegroup,Examples),NAMED('agegroupByvendor'));
  //  OUTPUT(SALT30.MAC_CrossTab(infile,vendor,gender,Examples),NAMED('genderByvendor'));
  //  OUTPUT(SALT30.MAC_CrossTab(infile,vendor,email,Examples),NAMED('emailByvendor'));
  //  OUTPUT(SALT30.MAC_CrossTab(infile,vendor,orig_listing_type,Examples),NAMED('orig_listing_typeByvendor'));
  //  OUTPUT(SALT30.MAC_CrossTab(infile,vendor,listingtype,Examples),NAMED('listingtypeByvendor'));
  //  OUTPUT(SALT30.MAC_CrossTab(infile,vendor,orig_publish_code,Examples),NAMED('orig_publish_codeByvendor'));
  //  OUTPUT(SALT30.MAC_CrossTab(infile,vendor,orig_phone_type,Examples),NAMED('orig_phone_typeByvendor'));
  //  OUTPUT(SALT30.MAC_CrossTab(infile,vendor,orig_phone_usage,Examples),NAMED('orig_phone_usageByvendor'));
  //  OUTPUT(SALT30.MAC_CrossTab(infile,vendor,company,Examples),NAMED('companyByvendor'));
  //  OUTPUT(SALT30.MAC_CrossTab(infile,vendor,orig_phone_reg_dt,Examples),NAMED('orig_phone_reg_dtByvendor'));
  //  OUTPUT(SALT30.MAC_CrossTab(infile,vendor,orig_carrier_code,Examples),NAMED('orig_carrier_codeByvendor'));
  //  OUTPUT(SALT30.MAC_CrossTab(infile,vendor,orig_carrier_name,Examples),NAMED('orig_carrier_nameByvendor'));
  //  OUTPUT(SALT30.MAC_CrossTab(infile,vendor,orig_conf_score,Examples),NAMED('orig_conf_scoreByvendor'));
  //  OUTPUT(SALT30.MAC_CrossTab(infile,vendor,orig_rec_type,Examples),NAMED('orig_rec_typeByvendor'));
  //  OUTPUT(SALT30.MAC_CrossTab(infile,vendor,clean_company,Examples),NAMED('clean_companyByvendor'));
  //  OUTPUT(SALT30.MAC_CrossTab(infile,vendor,prim_range,Examples),NAMED('prim_rangeByvendor'));
  //  OUTPUT(SALT30.MAC_CrossTab(infile,vendor,predir,Examples),NAMED('predirByvendor'));
  //  OUTPUT(SALT30.MAC_CrossTab(infile,vendor,prim_name,Examples),NAMED('prim_nameByvendor'));
  //  OUTPUT(SALT30.MAC_CrossTab(infile,vendor,addr_suffix,Examples),NAMED('addr_suffixByvendor'));
  //  OUTPUT(SALT30.MAC_CrossTab(infile,vendor,postdir,Examples),NAMED('postdirByvendor'));
  //  OUTPUT(SALT30.MAC_CrossTab(infile,vendor,unit_desig,Examples),NAMED('unit_desigByvendor'));
  //  OUTPUT(SALT30.MAC_CrossTab(infile,vendor,sec_range,Examples),NAMED('sec_rangeByvendor'));
  //  OUTPUT(SALT30.MAC_CrossTab(infile,vendor,p_city_name,Examples),NAMED('p_city_nameByvendor'));
  //  OUTPUT(SALT30.MAC_CrossTab(infile,vendor,v_city_name,Examples),NAMED('v_city_nameByvendor'));
  //  OUTPUT(SALT30.MAC_CrossTab(infile,vendor,state,Examples),NAMED('stateByvendor'));
  //  OUTPUT(SALT30.MAC_CrossTab(infile,vendor,zip5,Examples),NAMED('zip5Byvendor'));
  //  OUTPUT(SALT30.MAC_CrossTab(infile,vendor,zip4,Examples),NAMED('zip4Byvendor'));
  //  OUTPUT(SALT30.MAC_CrossTab(infile,vendor,cart,Examples),NAMED('cartByvendor'));
  //  OUTPUT(SALT30.MAC_CrossTab(infile,vendor,cr_sort_sz,Examples),NAMED('cr_sort_szByvendor'));
  //  OUTPUT(SALT30.MAC_CrossTab(infile,vendor,lot,Examples),NAMED('lotByvendor'));
  //  OUTPUT(SALT30.MAC_CrossTab(infile,vendor,lot_order,Examples),NAMED('lot_orderByvendor'));
  //  OUTPUT(SALT30.MAC_CrossTab(infile,vendor,dpbc,Examples),NAMED('dpbcByvendor'));
  //  OUTPUT(SALT30.MAC_CrossTab(infile,vendor,chk_digit,Examples),NAMED('chk_digitByvendor'));
  //  OUTPUT(SALT30.MAC_CrossTab(infile,vendor,rec_type,Examples),NAMED('rec_typeByvendor'));
  //  OUTPUT(SALT30.MAC_CrossTab(infile,vendor,ace_fips_st,Examples),NAMED('ace_fips_stByvendor'));
  //  OUTPUT(SALT30.MAC_CrossTab(infile,vendor,ace_fips_county,Examples),NAMED('ace_fips_countyByvendor'));
  //  OUTPUT(SALT30.MAC_CrossTab(infile,vendor,geo_lat,Examples),NAMED('geo_latByvendor'));
  //  OUTPUT(SALT30.MAC_CrossTab(infile,vendor,geo_long,Examples),NAMED('geo_longByvendor'));
  //  OUTPUT(SALT30.MAC_CrossTab(infile,vendor,msa,Examples),NAMED('msaByvendor'));
  //  OUTPUT(SALT30.MAC_CrossTab(infile,vendor,geo_blk,Examples),NAMED('geo_blkByvendor'));
  //  OUTPUT(SALT30.MAC_CrossTab(infile,vendor,geo_match,Examples),NAMED('geo_matchByvendor'));
  //  OUTPUT(SALT30.MAC_CrossTab(infile,vendor,err_stat,Examples),NAMED('err_statByvendor'));
  //  OUTPUT(SALT30.MAC_CrossTab(infile,vendor,title,Examples),NAMED('titleByvendor'));
  //  OUTPUT(SALT30.MAC_CrossTab(infile,vendor,fname,Examples),NAMED('fnameByvendor'));
  //  OUTPUT(SALT30.MAC_CrossTab(infile,vendor,mname,Examples),NAMED('mnameByvendor'));
  //  OUTPUT(SALT30.MAC_CrossTab(infile,vendor,lname,Examples),NAMED('lnameByvendor'));
  //  OUTPUT(SALT30.MAC_CrossTab(infile,vendor,name_suffix,Examples),NAMED('name_suffixByvendor'));
  //  OUTPUT(SALT30.MAC_CrossTab(infile,vendor,name_score,Examples),NAMED('name_scoreByvendor'));
  //  OUTPUT(SALT30.MAC_CrossTab(infile,vendor,bdid,Examples),NAMED('bdidByvendor'));
  //  OUTPUT(SALT30.MAC_CrossTab(infile,vendor,bdid_score,Examples),NAMED('bdid_scoreByvendor'));
  //  OUTPUT(SALT30.MAC_CrossTab(infile,vendor,append_npa_effective_dt,Examples),NAMED('append_npa_effective_dtByvendor'));
  //  OUTPUT(SALT30.MAC_CrossTab(infile,vendor,append_npa_last_change_dt,Examples),NAMED('append_npa_last_change_dtByvendor'));
  //  OUTPUT(SALT30.MAC_CrossTab(infile,vendor,append_dialable_ind,Examples),NAMED('append_dialable_indByvendor'));
  //  OUTPUT(SALT30.MAC_CrossTab(infile,vendor,append_place_name,Examples),NAMED('append_place_nameByvendor'));
  //  OUTPUT(SALT30.MAC_CrossTab(infile,vendor,append_portability_indicator,Examples),NAMED('append_portability_indicatorByvendor'));
  //  OUTPUT(SALT30.MAC_CrossTab(infile,vendor,append_prior_area_code,Examples),NAMED('append_prior_area_codeByvendor'));
  //  OUTPUT(SALT30.MAC_CrossTab(infile,vendor,append_nonpublished_match,Examples),NAMED('append_nonpublished_matchByvendor'));
  //  OUTPUT(SALT30.MAC_CrossTab(infile,vendor,append_ocn,Examples),NAMED('append_ocnByvendor'));
  //  OUTPUT(SALT30.MAC_CrossTab(infile,vendor,append_time_zone,Examples),NAMED('append_time_zoneByvendor'));
  //  OUTPUT(SALT30.MAC_CrossTab(infile,vendor,append_nxx_type,Examples),NAMED('append_nxx_typeByvendor'));
  //  OUTPUT(SALT30.MAC_CrossTab(infile,vendor,append_coctype,Examples),NAMED('append_coctypeByvendor'));
  //  OUTPUT(SALT30.MAC_CrossTab(infile,vendor,append_scc,Examples),NAMED('append_sccByvendor'));
  //  OUTPUT(SALT30.MAC_CrossTab(infile,vendor,append_phone_type,Examples),NAMED('append_phone_typeByvendor'));
  //  OUTPUT(SALT30.MAC_CrossTab(infile,vendor,append_company_type,Examples),NAMED('append_company_typeByvendor'));
  //  OUTPUT(SALT30.MAC_CrossTab(infile,vendor,append_phone_use,Examples),NAMED('append_phone_useByvendor'));
  //  OUTPUT(SALT30.MAC_CrossTab(infile,vendor,agreg_listing_type,Examples),NAMED('agreg_listing_typeByvendor'));
  //  OUTPUT(SALT30.MAC_CrossTab(infile,vendor,max_orig_conf_score,Examples),NAMED('max_orig_conf_scoreByvendor'));
  //  OUTPUT(SALT30.MAC_CrossTab(infile,vendor,min_orig_conf_score,Examples),NAMED('min_orig_conf_scoreByvendor'));
  //  OUTPUT(SALT30.MAC_CrossTab(infile,vendor,cur_orig_conf_score,Examples),NAMED('cur_orig_conf_scoreByvendor'));
  //  OUTPUT(SALT30.MAC_CrossTab(infile,vendor,activeflag,Examples),NAMED('activeflagByvendor'));
  //  OUTPUT(SALT30.MAC_CrossTab(infile,vendor,eda_active_flag,Examples),NAMED('eda_active_flagByvendor'));
  //  OUTPUT(SALT30.MAC_CrossTab(infile,vendor,eda_match,Examples),NAMED('eda_matchByvendor'));
  //  OUTPUT(SALT30.MAC_CrossTab(infile,vendor,eda_phone_dt,Examples),NAMED('eda_phone_dtByvendor'));
  //  OUTPUT(SALT30.MAC_CrossTab(infile,vendor,eda_did_dt,Examples),NAMED('eda_did_dtByvendor'));
  //  OUTPUT(SALT30.MAC_CrossTab(infile,vendor,eda_nm_addr_dt,Examples),NAMED('eda_nm_addr_dtByvendor'));
  //  OUTPUT(SALT30.MAC_CrossTab(infile,vendor,eda_hist_match,Examples),NAMED('eda_hist_matchByvendor'));
  //  OUTPUT(SALT30.MAC_CrossTab(infile,vendor,eda_hist_phone_dt,Examples),NAMED('eda_hist_phone_dtByvendor'));
  //  OUTPUT(SALT30.MAC_CrossTab(infile,vendor,eda_hist_did_dt,Examples),NAMED('eda_hist_did_dtByvendor'));
  //  OUTPUT(SALT30.MAC_CrossTab(infile,vendor,eda_hist_nm_addr_dt,Examples),NAMED('eda_hist_nm_addr_dtByvendor'));
  //  OUTPUT(SALT30.MAC_CrossTab(infile,vendor,append_feedback_phone,Examples),NAMED('append_feedback_phoneByvendor'));
  //  OUTPUT(SALT30.MAC_CrossTab(infile,vendor,append_feedback_phone_dt,Examples),NAMED('append_feedback_phone_dtByvendor'));
  //  OUTPUT(SALT30.MAC_CrossTab(infile,vendor,append_feedback_phone7_did,Examples),NAMED('append_feedback_phone7_didByvendor'));
  //  OUTPUT(SALT30.MAC_CrossTab(infile,vendor,append_feedback_phone7_did_dt,Examples),NAMED('append_feedback_phone7_did_dtByvendor'));
  //  OUTPUT(SALT30.MAC_CrossTab(infile,vendor,append_feedback_phone7_nm_addr,Examples),NAMED('append_feedback_phone7_nm_addrByvendor'));
  //  OUTPUT(SALT30.MAC_CrossTab(infile,vendor,append_feedback_phone7_nm_addr_dt,Examples),NAMED('append_feedback_phone7_nm_addr_dtByvendor'));
  //  OUTPUT(SALT30.MAC_CrossTab(infile,vendor,append_ported_match,Examples),NAMED('append_ported_matchByvendor'));
  //  OUTPUT(SALT30.MAC_CrossTab(infile,vendor,append_seen_once_ind,Examples),NAMED('append_seen_once_indByvendor'));
  //  OUTPUT(SALT30.MAC_CrossTab(infile,vendor,append_indiv_phone_cnt,Examples),NAMED('append_indiv_phone_cntByvendor'));
  //  OUTPUT(SALT30.MAC_CrossTab(infile,vendor,append_indiv_has_active_eda_phone_flag,Examples),NAMED('append_indiv_has_active_eda_phone_flagByvendor'));
  //  OUTPUT(SALT30.MAC_CrossTab(infile,vendor,append_latest_phone_owner_flag,Examples),NAMED('append_latest_phone_owner_flagByvendor'));
  //  OUTPUT(SALT30.MAC_CrossTab(infile,vendor,hhid,Examples),NAMED('hhidByvendor'));
  //  OUTPUT(SALT30.MAC_CrossTab(infile,vendor,hhid_score,Examples),NAMED('hhid_scoreByvendor'));
  //  OUTPUT(SALT30.MAC_CrossTab(infile,vendor,phone7_hhid_key,Examples),NAMED('phone7_hhid_keyByvendor'));
  //  OUTPUT(SALT30.MAC_CrossTab(infile,vendor,append_best_addr_match_flag,Examples),NAMED('append_best_addr_match_flagByvendor'));
  //  OUTPUT(SALT30.MAC_CrossTab(infile,vendor,append_best_nm_match_flag,Examples),NAMED('append_best_nm_match_flagByvendor'));
  //  OUTPUT(SALT30.MAC_CrossTab(infile,vendor,rawaid,Examples),NAMED('rawaidByvendor'));
  //  OUTPUT(SALT30.MAC_CrossTab(infile,vendor,cleanaid,Examples),NAMED('cleanaidByvendor'));
  //  OUTPUT(SALT30.MAC_CrossTab(infile,vendor,current_rec,Examples),NAMED('current_recByvendor'));
  //  OUTPUT(SALT30.MAC_CrossTab(infile,vendor,first_build_date,Examples),NAMED('first_build_dateByvendor'));
  //  OUTPUT(SALT30.MAC_CrossTab(infile,vendor,last_build_date,Examples),NAMED('last_build_dateByvendor'));
