Import Healthcare_Cleaners;
EXPORT Constants := MODULE
	Export useProd := true;
	Export NonMedicalSchool := 8000;
	Export nameSet := ['MR','MRS','MS','MISS','DR','DOCTOR'];
	Export drSet := ['DOCTOR'];
	Export oddFirstNamesSet := ['SAT '];
	Export possibleLastNameSet := ['PA','DO'];
	Export possibleLastNameTitleSet := ['COOK'];
	Export possibleLastNameProfSuffixSet := ['MEDICINE','BACHELOR','BACH.'];
	Export possibleSuffixSet := ['JR','SR','I','II','III','IV'];
	Export BusinessWordsDS := dataset([{'CORPORATION'},{'INC'},{'ASSOC'},{'CORP'},{'LLC'},{'LTD'},{'LLP'},{'INCORPORATION'},{'INCORPORATED'},{'MED'},{'LABORATORY'},{'AUTHORITY'}],Healthcare_Cleaners.Layouts.splitRec);
	Export strDr := 'Dr';
	Export strFullDr := 'DOCTOR';
	Export FilterWithSpace := 'ABCDEFGHIJKLMNOPQRSTUVWXYZ ';
	Export SpaceVal := ' ';
	Export EmptyVal := '';
	Export PeriodVal := '.';
	Export CommaVal := ',';
	Export masterLength := 15;
	Export stateList := ['ALABAMA','ALASKA','ARKANSAS','SAMOA','ARIZONA','CALIFORNIA','COLORADO','CONNECTICUT','DELAWARE','FLORIDA','GEORGIA','GUAM','HAWAII','IOWA','IDAHO','ILLINOIS','INDIANA','KANSAS','KENTUCKY','LOUISIANA','MASSACHUSETTS','MARYLAND','MAINE','MICHIGAN','MINNESOTA','MISSOURI','MISSISSIPPI','MONTANA','NORTH CAROLINA','NORTH DAKOTA','NEBRASKA','NEW HAMPSHIRE','NEW JERSEY','NEW MEXICO','NEVADA','NEW YORK','OHIO','OKLAHOMA','OREGON','PENNSYLVANIA','PUERTO RICO','RHODE ISLAND','SOUTH CAROLINA','SOUTH DAKOTA','TENNESSEE','TEXAS','UTAH','VIRGINIA','VIRGIN ISLANDS','VERMONT','WASHINGTON','WISCONSIN','WEST VIRGINIA','WYOMING'];
End;