Generated by SALT V3.6.1
Command line options: -MScrubs_Property_Foreclosures -eC:\Users\dittda01\AppData\Local\Temp\TFR9B80.tmp 
File being processed :-
OPTIONS:-gh
MODULE:Scrubs_Property_Foreclosures
FILENAME:property_foreclosures
//Uncomment up to NINES for internal or external adl
//IDFIELD:EXISTS:<NameOfIDField>
//RIDFIELD:<NameOfRidField>
//RECORDS:<NumberOfRecordsInDataFile>
//POPULATION:<ExpectedNumberOfEntitiesInDataFile>
//NINES:<Precision required 3 = 99.9, 2 = 99 4.129372e+254tc>
//Uncomment Process if doing external adl
//PROCESS:<ProcessName>
//SOURCEFIELD:state
//FIELDTYPE:alpha:ALLOW(ABCDEFGHIJKLMNOPQRSTUVWXYZ):
FIELDTYPE:invalid_number:ALLOW(0123456789):
FIELDTYPE:invalid_alpha:ALLOW(ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789'):SPACES( <>{}[]-^=!+&,./#()):
FIELDTYPE:invalid_apn:ALLOW(ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789'):SPACES( -./:):
FIELDTYPE:invalid_zip:ALLOW(0123456789):LENGTHS(0,5,9)
FIELDTYPE:invalid_year:ALLOW(0123456789):LENGTHS(0,4)
FIELDTYPE:invalid_date:ALLOW(0123456789):LENGTHS(0,4,6,8,10)
FIELDTYPE:invalid_phone:ALLOW(0123456789):LENGTHS(0,7,10)
FIELDTYPE:invalid_amount:ALLOW(0123456789):
FIELDTYPE:invalid_deed_code:CUSTOM(Scrubs_Property_Foreclosures.fn_valid_codes > 0,'deed') 
FIELDTYPE:invalid_document_code:CUSTOM(Scrubs_Property_Foreclosures.fn_valid_codes > 0,'document') 
FIELDTYPE:invalid_etal_code:CUSTOM(Scrubs_Property_Foreclosures.fn_valid_codes > 0,'etal') 
FIELDTYPE:invalid_property_code:CUSTOM(Scrubs_Property_Foreclosures.fn_valid_codes > 0,'property') 
FIELDTYPE:invalid_land_use_code:CUSTOM(Scrubs_Property_Foreclosures.fn_valid_codes > 0,'land_use') 
FIELDTYPE:invalid_address_indicator:ENUM(S|M|U|):
FIELDTYPE:invalid_case:ALLOW(ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789'):SPACES( {}-&,./#():):
FIELDTYPE:invalid_name:ALLOW(ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789'):SPACES( -,.()):LENGTHS(0,3..) 
FIELD:foreclosure_id:TYPE(STRING70):0,0
FIELD:process_date:LIKE(invalid_date):0,0
FIELD:state:TYPE(STRING2):0,0
FIELD:county:TYPE(STRING3):0,0
FIELD:batch_date_and_seq_nbr:TYPE(STRING18):0,0
FIELD:deed_category:LIKE(invalid_deed_code):0,0
FIELD:document_type:LIKE(invalid_document_code):0,0
FIELD:recording_date:LIKE(invalid_date):0,0
FIELD:document_year:LIKE(invalid_year):0,0
FIELD:document_nbr:LIKE(invalid_apn):TYPE(STRING12):0,0
FIELD:document_book:TYPE(STRING6):0,0
FIELD:document_pages:TYPE(STRING6):0,0
FIELD:title_company_code:TYPE(STRING5):0,0
FIELD:title_company_name:TYPE(STRING60):0,0
FIELD:attorney_name:TYPE(STRING60):0,0
FIELD:attorney_phone_nbr:LIKE(invalid_phone):TYPE(STRING10):0,0
FIELD:first_defendant_borrower_owner_first_name:TYPE(STRING30):0,0
FIELD:first_defendant_borrower_owner_last_name:LIKE(invalid_name):TYPE(STRING30):0,0
FIELD:first_defendant_borrower_company_name:TYPE(STRING30):0,0
FIELD:second_defendant_borrower_owner_first_name:TYPE(STRING30):0,0
FIELD:second_defendant_borrower_owner_last_name:TYPE(STRING30):0,0
FIELD:second_defendant_borrower_company_name:TYPE(STRING30):0,0
FIELD:third_defendant_borrower_owner_first_name:TYPE(STRING30):0,0
FIELD:third_defendant_borrower_owner_last_name:TYPE(STRING30):0,0
FIELD:third_defendant_borrower_company_name:TYPE(STRING30):0,0
FIELD:fourth_defendant_borrower_owner_first_name:TYPE(STRING30):0,0
FIELD:fourth_defendant_borrower_owner_last_name:TYPE(STRING30):0,0
FIELD:fourth_defendant_borrower_company_name:TYPE(STRING30):0,0
FIELD:defendant_borrower_owner_et_al_indicator:LIKE(invalid_etal_code):0,0
FIELD:filler1:0,0
FIELD:date_of_default:LIKE(invalid_date):TYPE(STRING10):0,0
FIELD:amount_of_default:LIKE(invalid_amount):TYPE(STRING11):0,0
FIELD:filler2:0,0
FIELD:filing_date:LIKE(invalid_date):TYPE(STRING10):0,0
FIELD:court_case_nbr:LIKE(invalid_case):TYPE(STRING20):0,0
FIELD:lis_pendens_type:TYPE(STRING1):0,0
FIELD:plaintiff_1:TYPE(STRING30):0,0
FIELD:plaintiff_2:TYPE(STRING30):0,0
FIELD:final_judgment_amount:LIKE(invalid_amount):TYPE(STRING11):0,0
FIELD:filler_3:0,0
FIELD:auction_date:LIKE(invalid_date):TYPE(STRING10):0,0
FIELD:auction_time:TYPE(STRING10):0,0
FIELD:street_address_of_auction_call:TYPE(STRING30):0,0
FIELD:city_of_auction_call:TYPE(STRING25):0,0
FIELD:state_of_auction_call:TYPE(STRING2):0,0
FIELD:opening_bid:TYPE(STRING11):0,0
FIELD:tax_year:LIKE(invalid_year):TYPE(STRING4):0,0
FIELD:filler4:0,0
FIELD:sales_price:LIKE(invalid_amount):TYPE(STRING11):0,0
FIELD:situs_address_indicator_1:LIKE(invalid_address_indicator):TYPE(STRING1):0,0
FIELD:situs_house_number_prefix_1:TYPE(STRING5):0,0
FIELD:situs_house_number_1:TYPE(STRING10):0,0
FIELD:situs_house_number_suffix_1:TYPE(STRING10):0,0
FIELD:situs_street_name_1:TYPE(STRING30):0,0
FIELD:situs_mode_1:TYPE(STRING5):0,0
FIELD:situs_direction_1:TYPE(STRING2):0,0
FIELD:situs_quadrant_1:TYPE(STRING2):0,0
FIELD:apartment_unit:TYPE(STRING6):0,0
FIELD:property_city_1:LIKE(invalid_alpha):TYPE(STRING40):0,0
FIELD:property_state_1:LIKE(invalid_alpha):TYPE(STRING2):0,0
FIELD:property_address_zip_code_1:LIKE(invalid_zip):TYPE(STRING9):0,0
FIELD:carrier_code:TYPE(STRING4):0,0
FIELD:full_site_address_unparsed_1:LIKE(invalid_alpha):TYPE(STRING60):0,0
FIELD:lender_beneficiary_first_name:TYPE(STRING30):0,0
FIELD:lender_beneficiary_last_name:TYPE(STRING30):0,0
FIELD:lender_beneficiary_company_name:TYPE(STRING30):0,0
FIELD:lender_beneficiary_mailing_address:TYPE(STRING60):0,0
FIELD:lender_beneficiary_city:LIKE(invalid_alpha):TYPE(STRING40):0,0
FIELD:lender_beneficiary_state:LIKE(invalid_alpha):TYPE(STRING2):0,0
FIELD:lender_beneficiary_zip:LIKE(invalid_zip):TYPE(STRING9):0,0
FIELD:lender_phone:LIKE(invalid_phone):TYPE(STRING10):0,0
FIELD:filler_5:0,0
FIELD:trustee_name:TYPE(STRING30):0,0
FIELD:trustee_mailing_address:TYPE(STRING60):0,0
FIELD:trustee_city:TYPE(STRING40):0,0
FIELD:trustee_state:TYPE(STRING2):0,0
FIELD:trustee_zip:TYPE(STRING9):0,0
FIELD:trustee_phone:LIKE(invalid_phone):TYPE(STRING10):0,0
FIELD:trustee_sale_number:LIKE(invalid_apn):TYPE(STRING11):0,0
FIELD:filler_6:0,0
FIELD:original_loan_date:LIKE(invalid_date):TYPE(STRING8):0,0
FIELD:original_loan_recording_date:LIKE(invalid_date):TYPE(STRING8):0,0
FIELD:original_loan_amount:LIKE(invalid_amount):TYPE(STRIN11):0,0
FIELD:original_document_number:LIKE(invalid_apn):TYPE(STRING12):0,0
FIELD:original_recording_book:TYPE(STRING6):0,0
FIELD:original_recording_page:TYPE(STRING6):0,0
FIELD:filler_7:0,0
FIELD:parcel_number_parcel_id:LIKE(invalid_apn):TYPE(STRING45):0,0
FIELD:parcel_number_unmatched_id:TYPE(STRING45):0,0
FIELD:last_full_sale_transfer_date:LIKE(invalid_date):TYPE(STRING8):0,0
FIELD:transfer_value:LIKE(invalid_amount):TYPE(STRING11):0,0
FIELD:situs_address_indicator_2:LIKE(invalid_address_indicator):TYPE(STRING1):0,0
FIELD:situs_house_number_prefix_2:TYPE(STRING5):0,0
FIELD:situs_house_number_2:TYPE(STRING10):0,0
FIELD:situs_house_number_suffix_2:TYPE(STRING10):0,0
FIELD:situs_street_name_2:TYPE(STRING30):0,0
FIELD:situs_mode_2:TYPE(STRING5):0,0
FIELD:situs_direction_2:TYPE(STRING2):0,0
FIELD:situs_quadrant_2:TYPE(STRING2):0,0
FIELD:apartment_unit_2:TYPE(STRING6):0,0
FIELD:property_city_2:LIKE(invalid_alpha):TYPE(STRING40):0,0
FIELD:property_state_2:LIKE(invalid_alpha):TYPE(STRING2):0,0
FIELD:property_address_zip_code_2:LIKE(invalid_zip):TYPE(STRING9):0,0
FIELD:carrier_code_2:TYPE(STRING4):0,0
FIELD:full_site_address_unparsed_2:LIKE(invalid_alpha):TYPE(STRING60):0,0
FIELD:property_indicator:LIKE(invalid_property_code):0,0
FIELD:use_code:LIKE(invalid_land_use_code):0,0
FIELD:number_of_units:TYPE(STRING5):0,0
FIELD:living_area_square_feet:TYPE(STRING9):0,0
FIELD:number_of_bedrooms:TYPE(STRING5):0,0
FIELD:number_of_bathrooms:TYPE(STRING5):0,0
FIELD:number_of_garages:TYPE(STRING3):0,0
FIELD:zoning_code:TYPE(STRING10):0,0
FIELD:lot_size:TYPE(STRING9):0,0
FIELD:year_built:LIKE(invalid_year):TYPE(STRING4):0,0
FIELD:current_land_value:LIKE(invalid_amount):TYPE(STRING11):0,0
FIELD:current_improvement_value:LIKE(invalid_amount):TYPE(STRING11):0,0
FIELD:filler_8:0,0
FIELD:section:TYPE(STRING3):0,0
FIELD:township:TYPE(STRING3):0,0
FIELD:range:TYPE(STRING3):0,0
FIELD:lot:TYPE(STRING5):0,0
FIELD:block:TYPE(STRING5):0,0
FIELD:tract_subdivision_name:TYPE(STRING30):0,0
FIELD:map_book:TYPE(STRING6):0,0
FIELD:map_page:TYPE(STRING6):0,0
FIELD:unit_nbr:TYPE(STRING5):0,0
FIELD:expanded_legal:TYPE(STRING250):0,0
FIELD:legal_2:TYPE(STRING250):0,0
FIELD:legal_3:TYPE(STRING250):0,0
FIELD:legal_4:TYPE(STRING250):0,0
FIELD:crlf:TYPE(STRING2):0,0
FIELD:deed_desc:0,0
FIELD:document_desc:0,0
FIELD:et_al_desc:0,0
FIELD:property_desc:0,0
FIELD:use_desc:0,0
 
Total available specificity:0
Search Threshold set at -4
Use of PERSISTs in code set at:3
 
__Glossary__
Edit Distance: An edit distance of (say) one implies that one string can be converted into another by doing one of
  - Changing one character
  - Deleting one character
  - Transposing two characters
 
Forcing Criteria: In addition to the general 'best match' logic it is possible to insist that
one particular field must match to some degree or the whole record is considered a bad match.
The criterial applied to that one field is the forcing criteria.
 
Cascade: Best Type rules are applied in such a way that the rules are applied one by one UNTIL the first rule succeeds; subsequent rules are then skipped.
 
__General Notes__
How is it decided how much to subtract for a bad match?
SALT computes for each field the percentage likelihood that a valid cluster will have two or more values for a given field
this value (called the switch value in the SALT literature) is then used to produce the subtraction value from the match value.
The value in this document is the one typed into the SPC file; the code will use a value computed at run-time.
 
