export File_In_Subcategory_Premium := dataset([
	{'20','Non-PEP','','3'},
	{'1','PEP International Organization','','3'},
	{'2','PEP International Organization - Immediate Relative','','3'},
	{'3','PEP International Organization - Close Associate','','3'},
	{'4','PEP Regional Organization','','3'},
	{'5','PEP Regional Organization - Immediate Relative','','3'},
	{'6','PEP Regional Organization - Close Associate','','3'},
	{'7','PEP National Government','','3'},
	{'8','PEP National Government - Immediate Relative','','3'},
	{'9','PEP National Government - Close Associate','','3'},
	{'10','PEP Sub-National Government','','3'},
	{'11','PEP Sub-National Government - Immediate Relative','','3'},
	{'12','PEP Sub-National Government - Close Associate','','3'},
	{'13','PEP Local Government','','3'},
	{'14','PEP Local Government - Immediate Relative','','3'},
	{'15','PEP Local Government - Close Associate','','3'},
	{'16','PEP Non-Government','','3'},
	{'17','PEP Non-Government - Immediate Relative','','3'},
	{'18','PEP Non-Government - Close Associate','','3'},
	{'19','PEP State Owned Entity','','3'},
	{'21','PEP State Invested Enterprise','','3'},
	{'22','PEP Instrumentality of State','','3'}],
	Layout_Subcategory);