//HPCC Systems KEL Compiler Version 0.11.6
IMPORT KEL011 AS KEL;
IMPORT B_Bankruptcy_6,CFG_Compile,E_Bankruptcy,FN_Compile FROM PublicRecords_KEL;
IMPORT * FROM KEL011.Null;
EXPORT B_Bankruptcy_5(CFG_Compile.FDCDataset __in = CFG_Compile.FDCDefault, CFG_Compile __cfg = CFG_Compile) := MODULE
  SHARED VIRTUAL TYPEOF(B_Bankruptcy_6(__in,__cfg).__ENH_Bankruptcy_6) __ENH_Bankruptcy_6 := B_Bankruptcy_6(__in,__cfg).__ENH_Bankruptcy_6;
  SHARED __EE83600 := __ENH_Bankruptcy_6;
  EXPORT __ST70290_Layout := RECORD
    KEL.typ.nstr Source_Description_;
    KEL.typ.nstr Original_Chapter_;
    KEL.typ.nstr Filing_Type_;
    KEL.typ.nstr Business_Flag_;
    KEL.typ.nstr Corporate_Flag_;
    KEL.typ.nkdate Discharged_Date_;
    KEL.typ.nstr Disposition_;
    KEL.typ.nstr Debtor_Type_;
    KEL.typ.nint Debtor_Sequence_;
    KEL.typ.nint Disposition_Type_;
    KEL.typ.nint Disposition_Reason_;
    KEL.typ.nstr Disposition_Type_Description_;
    KEL.typ.nstr Name_Type_;
    KEL.typ.nstr Screen_Description_;
    KEL.typ.nstr Decoded_Description_;
    KEL.typ.nkdate Date_Filed_;
    KEL.typ.nkdate Date_Vendor_First_Reported_;
    KEL.typ.nkdate Date_Vendor_Last_Reported_;
    KEL.typ.nstr Record_Type_;
    KEL.typ.nkdate Last_Status_Update_;
    KEL.typ.nkdate Bankruptcy_Date_;
    KEL.typ.nstr Case_Number_;
    KEL.typ.nint Filing_Age_In_Days_;
    KEL.typ.nbool Is_Bankruptcy_;
    KEL.typ.nbool Is_Debtor_;
    KEL.typ.epoch Date_First_Seen_ := 0;
    KEL.typ.epoch Date_Last_Seen_ := 0;
    KEL.typ.int __RecordCount := 0;
  END;
  EXPORT __ST70283_Layout := RECORD
    KEL.typ.nuid UID;
    KEL.typ.nstr T_M_S_I_D_;
    KEL.typ.nstr Court_Code_;
    KEL.typ.nstr Case_Number_;
    KEL.typ.nstr Original_Case_Number_;
    KEL.typ.ndataset(__ST70290_Layout) Records_;
    KEL.typ.ndataset(E_Bankruptcy(__in,__cfg).Deadlines_Layout) Deadlines_;
    KEL.typ.ndataset(E_Bankruptcy(__in,__cfg).Case_Details_Layout) Case_Details_;
    KEL.typ.ndataset(E_Bankruptcy(__in,__cfg).Data_Sources_Layout) Data_Sources_;
    KEL.typ.nkdate Current_Date_;
    KEL.typ.nbool Has_Case_Number_;
    KEL.typ.epoch Date_First_Seen_ := 0;
    KEL.typ.epoch Date_Last_Seen_ := 0;
    KEL.typ.int __RecordCount := 0;
  END;
  SHARED __ST70283_Layout __ND83563__Project(B_Bankruptcy_6(__in,__cfg).__ST71123_Layout __PP82554) := TRANSFORM
    __EE83548 := __PP82554.Records_;
    __EE83545 := __PP82554.Case_Details_;
    __ST83019_Layout := RECORD
      KEL.typ.nstr Source_Description_;
      KEL.typ.nstr Original_Chapter_;
      KEL.typ.nstr Filing_Type_;
      KEL.typ.nstr Business_Flag_;
      KEL.typ.nstr Corporate_Flag_;
      KEL.typ.nkdate Discharged_Date_;
      KEL.typ.nstr Disposition_;
      KEL.typ.nstr Debtor_Type_;
      KEL.typ.nint Debtor_Sequence_;
      KEL.typ.nint Disposition_Type_;
      KEL.typ.nint Disposition_Reason_;
      KEL.typ.nstr Disposition_Type_Description_;
      KEL.typ.nstr Name_Type_;
      KEL.typ.nstr Screen_Description_;
      KEL.typ.nstr Decoded_Description_;
      KEL.typ.nkdate Date_Filed_;
      KEL.typ.nkdate Date_Vendor_First_Reported_;
      KEL.typ.nkdate Date_Vendor_Last_Reported_;
      KEL.typ.nstr Record_Type_;
      KEL.typ.nkdate Last_Status_Update_;
      KEL.typ.nkdate Bankruptcy_Date_;
      KEL.typ.nstr Case_Number_;
      KEL.typ.nbool Is_Debtor_;
      KEL.typ.nint Case_I_D_;
      KEL.typ.nint Defendant_I_D_;
      KEL.typ.nkdate Date_Vendor_First_Reported__1_;
      KEL.typ.nkdate Date_Vendor_Last_Reported__1_;
      KEL.typ.epoch Date_First_Seen_ := 0;
      KEL.typ.epoch Date_Last_Seen_ := 0;
      KEL.typ.int __RecordCount := 0;
    END;
    __JC83553(B_Bankruptcy_6(__in,__cfg).__ST71130_Layout __EE83548, E_Bankruptcy(__in,__cfg).Case_Details_Layout __EE83545) := TRUE;
    __ST83019_Layout __JT83553(B_Bankruptcy_6(__in,__cfg).__ST71130_Layout __l, E_Bankruptcy(__in,__cfg).Case_Details_Layout __r) := TRANSFORM
      SELF.Date_Vendor_First_Reported__1_ := __r.Date_Vendor_First_Reported_;
      SELF.Date_Vendor_Last_Reported__1_ := __r.Date_Vendor_Last_Reported_;
      SELF := __l;
      SELF := __r;
    END;
    __EE83554 := JOIN(__T(__EE83548),__T(__EE83545),__JC83553(LEFT,RIGHT),__JT83553(LEFT,RIGHT),INNER,ALL);
    __EE83561 := IF(TRUE AND TRUE,__EE83554,DATASET([],__ST83019_Layout));
    __ST70290_Layout __ND83489__Project(__ST83019_Layout __PP83433) := TRANSFORM
      SELF.Filing_Age_In_Days_ := FN_Compile.FN_A_B_S_D_A_Y_S_B_E_T_W_E_E_N(__ECAST(KEL.typ.nkdate,__PP83433.Bankruptcy_Date_),__ECAST(KEL.typ.nkdate,__PP82554.Current_Date_));
      SELF.Is_Bankruptcy_ := __AND(__AND(__PP82554.Has_Case_Number_,__PP83433.Is_Debtor_),__OP2(__CAST(KEL.typ.str,__PP83433.Case_I_D_),<>,__CN('')));
      SELF := __PP83433;
    END;
    SELF.Records_ := __FILTER(__CN(PROJECT(__EE83561,__ND83489__Project(LEFT))),__NN(Source_Description_) OR __NN(Original_Chapter_) OR __NN(Filing_Type_) OR __NN(Business_Flag_) OR __NN(Corporate_Flag_) OR __NN(Discharged_Date_) OR __NN(Disposition_) OR __NN(Debtor_Type_) OR __NN(Debtor_Sequence_) OR __NN(Disposition_Type_) OR __NN(Disposition_Reason_) OR __NN(Disposition_Type_Description_) OR __NN(Name_Type_) OR __NN(Screen_Description_) OR __NN(Decoded_Description_) OR __NN(Date_Filed_) OR __NN(Date_Vendor_First_Reported_) OR __NN(Date_Vendor_Last_Reported_) OR __NN(Record_Type_) OR __NN(Last_Status_Update_) OR __NN(Bankruptcy_Date_) OR __NN(Case_Number_) OR __NN(Filing_Age_In_Days_) OR __NN(Is_Bankruptcy_) OR __NN(Is_Debtor_));
    SELF := __PP82554;
  END;
  EXPORT __ENH_Bankruptcy_5 := PROJECT(__EE83600,__ND83563__Project(LEFT));
END;
