//HPCC Systems KEL Compiler Version 1.1.0beta2
IMPORT KEL11 AS KEL;
IMPORT B_Business_Prox_1,B_Business_Sele_1,CFG_Compile,E_Address,E_Business_Org,E_Business_Prox,E_Business_Sele,E_Business_Ult,E_Phone,E_Prox_Address,E_Prox_Phone_Number,E_Prox_T_I_N,E_T_I_N,E_Zip_Code FROM PublicRecords_KEL;
IMPORT * FROM KEL11.Null;
EXPORT B_Business_Prox(CFG_Compile.FDCDataset __in = CFG_Compile.FDCDefault, CFG_Compile __cfg = CFG_Compile) := MODULE
  SHARED VIRTUAL TYPEOF(B_Business_Prox_1(__in,__cfg).__ENH_Business_Prox_1) __ENH_Business_Prox_1 := B_Business_Prox_1(__in,__cfg).__ENH_Business_Prox_1;
  SHARED VIRTUAL TYPEOF(B_Business_Sele_1(__in,__cfg).__ENH_Business_Sele_1) __ENH_Business_Sele_1 := B_Business_Sele_1(__in,__cfg).__ENH_Business_Sele_1;
  SHARED VIRTUAL TYPEOF(E_Prox_Phone_Number(__in,__cfg).__Result) __E_Prox_Phone_Number := E_Prox_Phone_Number(__in,__cfg).__Result;
  SHARED VIRTUAL TYPEOF(E_Prox_T_I_N(__in,__cfg).__Result) __E_Prox_T_I_N := E_Prox_T_I_N(__in,__cfg).__Result;
  SHARED __EE67640 := __ENH_Business_Prox_1;
  SHARED __EE67842 := __EE67640;
  SHARED __EE67864 := __E_Prox_T_I_N;
  SHARED __EE67871 := __EE67864(__NN(__EE67864.Site_));
  SHARED __ST57539_Layout := RECORD
    KEL.typ.ntyp(E_Business_Prox().Typ) ____grp___U_I_D_;
    KEL.typ.ntyp(E_Business_Prox().Typ) Site_;
    KEL.typ.ntyp(E_T_I_N().Typ) Tax_I_D_;
    KEL.typ.nint Ult_I_D_;
    KEL.typ.nint Org_I_D_;
    KEL.typ.nint Sele_I_D_;
    KEL.typ.nint Prox_I_D_;
    KEL.typ.nint Best_T_I_N_;
    KEL.typ.nint Best_T_I_N_Rank_;
    KEL.typ.ndataset(E_Prox_T_I_N(__in,__cfg).Data_Sources_Layout) Data_Sources_;
    KEL.typ.epoch Date_First_Seen_ := 0;
    KEL.typ.epoch Date_Last_Seen_ := 0;
  END;
  SHARED __EE67921 := PROJECT(__EE67871,TRANSFORM(__ST57539_Layout,SELF.____grp___U_I_D_ := LEFT.Site_,SELF := LEFT));
  SHARED __EE67862 := GROUP(KEL.Routines.SortChildren(__EE67921,'Data_Sources_'),____grp___U_I_D_,ALL);
  SHARED __EE67925 := TOPN(__EE67862(__NN(__EE67862.Best_T_I_N_Rank_)),1,__T(__EE67862.Best_T_I_N_Rank_),__T(____grp___U_I_D_),__T(Tax_I_D_),__T(Ult_I_D_),__T(Org_I_D_),__T(Sele_I_D_),__T(Prox_I_D_),__T(Best_T_I_N_));
  SHARED __ST58367_Layout := RECORD
    KEL.typ.nuid UID;
    KEL.typ.nint Ult_I_D_;
    KEL.typ.nint Org_I_D_;
    KEL.typ.nint Sele_I_D_;
    KEL.typ.nint Prox_I_D_;
    KEL.typ.ntyp(E_Business_Sele().Typ) Prox_Sele_;
    KEL.typ.nint Parent_Prox_I_D_;
    KEL.typ.nint Sele_Prox_I_D_;
    KEL.typ.nint Org_Prox_I_D_;
    KEL.typ.nint Ult_Prox_I_D_;
    KEL.typ.nint Levels_From_Top_;
    KEL.typ.nint Nodes_Below_;
    KEL.typ.nstr Prox_Segment_;
    KEL.typ.nstr Store_Number_;
    KEL.typ.nstr Active_Duns_Number_;
    KEL.typ.nstr Hist_Duns_Number_;
    KEL.typ.nstr Duns_Number_;
    KEL.typ.nint Equifax_I_D_;
    KEL.typ.ndataset(E_Business_Prox(__in,__cfg).Cortera_Layout) Cortera_;
    KEL.typ.ndataset(E_Business_Prox(__in,__cfg).Deleted_I_D_Numbers_Layout) Deleted_I_D_Numbers_;
    KEL.typ.ndataset(E_Business_Prox(__in,__cfg).Best_Company_Names_Layout) Best_Company_Names_;
    KEL.typ.ndataset(E_Business_Prox(__in,__cfg).Best_S_I_C_Codes_Layout) Best_S_I_C_Codes_;
    KEL.typ.ndataset(E_Business_Prox(__in,__cfg).Best_N_A_I_C_S_Codes_Layout) Best_N_A_I_C_S_Codes_;
    KEL.typ.ndataset(E_Business_Prox(__in,__cfg).O_S_H_A_Inspection_Layout) O_S_H_A_Inspection_;
    KEL.typ.ndataset(E_Business_Prox(__in,__cfg).O_S_H_A_Violations_Layout) O_S_H_A_Violations_;
    KEL.typ.ndataset(E_Business_Prox(__in,__cfg).O_S_H_A_Business_Information_Layout) O_S_H_A_Business_Information_;
    KEL.typ.ndataset(E_Business_Prox(__in,__cfg).Vendor_Dates_Layout) Vendor_Dates_;
    KEL.typ.ndataset(E_Business_Prox(__in,__cfg).Associated_Address_Type_Layout) Associated_Address_Type_;
    KEL.typ.ndataset(E_Business_Prox(__in,__cfg).Business_Characteristics_Layout) Business_Characteristics_;
    KEL.typ.ndataset(E_Business_Prox(__in,__cfg).Location_Status_Layout) Location_Status_;
    KEL.typ.ndataset(E_Business_Prox(__in,__cfg).Marketability_Layout) Marketability_;
    KEL.typ.ndataset(E_Business_Prox(__in,__cfg).Business_Owned_Characteristics_Layout) Business_Owned_Characteristics_;
    KEL.typ.ndataset(E_Business_Prox(__in,__cfg).Contacts_Layout) Contacts_;
    KEL.typ.ndataset(E_Business_Prox(__in,__cfg).Data_Sources_Layout) Data_Sources_;
    KEL.typ.ndataset(E_Prox_Address(__in,__cfg).Best_Addresses_Layout) Best_Prox_Address_;
    KEL.typ.nuid ____grp___U_I_D_;
    KEL.typ.ntyp(E_Business_Prox().Typ) Site_;
    KEL.typ.ntyp(E_T_I_N().Typ) Tax_I_D_;
    KEL.typ.nint Ult_I_D__1_;
    KEL.typ.nint Org_I_D__1_;
    KEL.typ.nint Sele_I_D__1_;
    KEL.typ.nint Prox_I_D__1_;
    KEL.typ.nint Best_T_I_N_;
    KEL.typ.nint Best_T_I_N_Rank_;
    KEL.typ.ndataset(E_Prox_T_I_N(__in,__cfg).Data_Sources_Layout) Data_Sources__1_;
    KEL.typ.epoch Date_First_Seen_ := 0;
    KEL.typ.epoch Date_Last_Seen_ := 0;
    KEL.typ.int __RecordCount := 0;
  END;
  __JC69042(B_Business_Prox_1(__in,__cfg).__ST25980_Layout __EE67842, __ST57539_Layout __EE67925) := __EEQP(__EE67842.UID,__EE67925.____grp___U_I_D_);
  __ST58367_Layout __JT69042(B_Business_Prox_1(__in,__cfg).__ST25980_Layout __l, __ST57539_Layout __r) := TRANSFORM
    SELF.Ult_I_D__1_ := __r.Ult_I_D_;
    SELF.Org_I_D__1_ := __r.Org_I_D_;
    SELF.Sele_I_D__1_ := __r.Sele_I_D_;
    SELF.Prox_I_D__1_ := __r.Prox_I_D_;
    SELF.Data_Sources__1_ := __r.Data_Sources_;
    SELF := __l;
    SELF := __r;
  END;
  SHARED __EE69043 := JOIN(__EE67842,__EE67925,__JC69042(LEFT,RIGHT),__JT69042(LEFT,RIGHT),INNER,MANY LOOKUP);
  SHARED __ST57146_Layout := RECORD
    KEL.typ.nuid UID;
    KEL.typ.ntyp(E_Business_Prox().Typ) Site_;
    KEL.typ.ntyp(E_T_I_N().Typ) Tax_I_D_;
    KEL.typ.nint Ult_I_D_;
    KEL.typ.nint Org_I_D_;
    KEL.typ.nint Sele_I_D_;
    KEL.typ.nint Prox_I_D_;
    KEL.typ.nint Best_T_I_N_;
    KEL.typ.nint Best_T_I_N_Rank_;
    KEL.typ.ndataset(E_Prox_T_I_N(__in,__cfg).Data_Sources_Layout) Data_Sources_;
  END;
  SHARED __ST57146_Layout __ND68150__Project(__ST58367_Layout __PP68146) := TRANSFORM
    SELF.Ult_I_D_ := __PP68146.Ult_I_D__1_;
    SELF.Org_I_D_ := __PP68146.Org_I_D__1_;
    SELF.Sele_I_D_ := __PP68146.Sele_I_D__1_;
    SELF.Prox_I_D_ := __PP68146.Prox_I_D__1_;
    SELF.Data_Sources_ := __PP68146.Data_Sources__1_;
    SELF := __PP68146;
  END;
  SHARED __EE68195 := PROJECT(__EE69043,__ND68150__Project(LEFT));
  SHARED __ST57184_Layout := RECORD
    KEL.typ.nuid UID;
    KEL.typ.nint Best_T_I_N_;
    KEL.typ.epoch Date_First_Seen_ := 0;
    KEL.typ.epoch Date_Last_Seen_ := 0;
  END;
  SHARED __EE67670 := PROJECT(__EE68195,__ST57184_Layout);
  SHARED __ST57213_Layout := RECORD
    KEL.typ.nuid UID;
    KEL.typ.nint O_N_L_Y___Best_T_I_N_;
    KEL.typ.epoch Date_First_Seen_ := 0;
    KEL.typ.epoch Date_Last_Seen_ := 0;
  END;
  SHARED __EE68209 := PROJECT(__EE67670,TRANSFORM(__ST57213_Layout,SELF.O_N_L_Y___Best_T_I_N_ := LEFT.Best_T_I_N_,SELF := LEFT));
  SHARED __ST58673_Layout := RECORD
    KEL.typ.nuid UID;
    KEL.typ.nint Ult_I_D_;
    KEL.typ.nint Org_I_D_;
    KEL.typ.nint Sele_I_D_;
    KEL.typ.nint Prox_I_D_;
    KEL.typ.ntyp(E_Business_Sele().Typ) Prox_Sele_;
    KEL.typ.nint Parent_Prox_I_D_;
    KEL.typ.nint Sele_Prox_I_D_;
    KEL.typ.nint Org_Prox_I_D_;
    KEL.typ.nint Ult_Prox_I_D_;
    KEL.typ.nint Levels_From_Top_;
    KEL.typ.nint Nodes_Below_;
    KEL.typ.nstr Prox_Segment_;
    KEL.typ.nstr Store_Number_;
    KEL.typ.nstr Active_Duns_Number_;
    KEL.typ.nstr Hist_Duns_Number_;
    KEL.typ.nstr Duns_Number_;
    KEL.typ.nint Equifax_I_D_;
    KEL.typ.ndataset(E_Business_Prox(__in,__cfg).Cortera_Layout) Cortera_;
    KEL.typ.ndataset(E_Business_Prox(__in,__cfg).Deleted_I_D_Numbers_Layout) Deleted_I_D_Numbers_;
    KEL.typ.ndataset(E_Business_Prox(__in,__cfg).Best_Company_Names_Layout) Best_Company_Names_;
    KEL.typ.ndataset(E_Business_Prox(__in,__cfg).Best_S_I_C_Codes_Layout) Best_S_I_C_Codes_;
    KEL.typ.ndataset(E_Business_Prox(__in,__cfg).Best_N_A_I_C_S_Codes_Layout) Best_N_A_I_C_S_Codes_;
    KEL.typ.ndataset(E_Business_Prox(__in,__cfg).O_S_H_A_Inspection_Layout) O_S_H_A_Inspection_;
    KEL.typ.ndataset(E_Business_Prox(__in,__cfg).O_S_H_A_Violations_Layout) O_S_H_A_Violations_;
    KEL.typ.ndataset(E_Business_Prox(__in,__cfg).O_S_H_A_Business_Information_Layout) O_S_H_A_Business_Information_;
    KEL.typ.ndataset(E_Business_Prox(__in,__cfg).Vendor_Dates_Layout) Vendor_Dates_;
    KEL.typ.ndataset(E_Business_Prox(__in,__cfg).Associated_Address_Type_Layout) Associated_Address_Type_;
    KEL.typ.ndataset(E_Business_Prox(__in,__cfg).Business_Characteristics_Layout) Business_Characteristics_;
    KEL.typ.ndataset(E_Business_Prox(__in,__cfg).Location_Status_Layout) Location_Status_;
    KEL.typ.ndataset(E_Business_Prox(__in,__cfg).Marketability_Layout) Marketability_;
    KEL.typ.ndataset(E_Business_Prox(__in,__cfg).Business_Owned_Characteristics_Layout) Business_Owned_Characteristics_;
    KEL.typ.ndataset(E_Business_Prox(__in,__cfg).Contacts_Layout) Contacts_;
    KEL.typ.ndataset(E_Business_Prox(__in,__cfg).Data_Sources_Layout) Data_Sources_;
    KEL.typ.ndataset(E_Prox_Address(__in,__cfg).Best_Addresses_Layout) Best_Prox_Address_;
    KEL.typ.nuid U_I_D__1_;
    KEL.typ.nint O_N_L_Y___Best_T_I_N_;
    KEL.typ.epoch Date_First_Seen_ := 0;
    KEL.typ.epoch Date_Last_Seen_ := 0;
    KEL.typ.int __RecordCount := 0;
  END;
  __JC69044(B_Business_Prox_1(__in,__cfg).__ST25980_Layout __EE67640, __ST57213_Layout __EE68209) := __EEQP(__EE67640.UID,__EE68209.UID);
  __ST58673_Layout __JT69044(B_Business_Prox_1(__in,__cfg).__ST25980_Layout __l, __ST57213_Layout __r) := TRANSFORM
    SELF.U_I_D__1_ := __r.UID;
    SELF := __l;
    SELF := __r;
  END;
  SHARED __EE69045 := JOIN(__EE67640,__EE68209,__JC69044(LEFT,RIGHT),__JT69044(LEFT,RIGHT),LEFT OUTER,MANY LOOKUP,KEEP(1));
  SHARED __EE67694 := __E_Prox_Phone_Number;
  SHARED __EE67701 := __EE67694(__NN(__EE67694.Site_));
  SHARED __ST56580_Layout := RECORD
    KEL.typ.ntyp(E_Business_Prox().Typ) ____grp___U_I_D_;
    KEL.typ.ntyp(E_Business_Prox().Typ) Site_;
    KEL.typ.ntyp(E_Phone().Typ) Phone_Number_;
    KEL.typ.nstr Best_Phone_;
    KEL.typ.nint Best_Phone_Rank_;
    KEL.typ.ndataset(E_Prox_Phone_Number(__in,__cfg).S_I_C_Codes_Layout) S_I_C_Codes_;
    KEL.typ.ndataset(E_Prox_Phone_Number(__in,__cfg).N_A_I_C_S_Codes_Layout) N_A_I_C_S_Codes_;
    KEL.typ.ndataset(E_Prox_Phone_Number(__in,__cfg).Data_Sources_Layout) Data_Sources_;
    KEL.typ.epoch Date_First_Seen_ := 0;
    KEL.typ.epoch Date_Last_Seen_ := 0;
    KEL.typ.int __RecordCount := 0;
  END;
  SHARED __EE70049 := PROJECT(__EE67701,TRANSFORM(__ST56580_Layout,SELF.____grp___U_I_D_ := LEFT.Site_,SELF := LEFT));
  SHARED __EE70075 := GROUP(KEL.Routines.SortChildren(__EE70049,'S_I_C_Codes_,N_A_I_C_S_Codes_,Data_Sources_'),____grp___U_I_D_,ALL);
  SHARED __EE70084 := TOPN(__EE70075(__NN(__EE70075.Best_Phone_Rank_)),1,__T(__EE70075.Best_Phone_Rank_),__T(____grp___U_I_D_),__T(Phone_Number_),__T(Best_Phone_));
  SHARED __EE67672 := __EE67640;
  __JC70090(__ST56580_Layout __EE70084, B_Business_Prox_1(__in,__cfg).__ST25980_Layout __EE67672) := __EEQP(__EE67672.UID,__EE70084.____grp___U_I_D_);
  SHARED __EE70108 := JOIN(__EE70084,__EE67672,__JC70090(LEFT,RIGHT),TRANSFORM(__ST56580_Layout,SELF:=LEFT),HASH,KEEP(1));
  SHARED __ST56176_Layout := RECORD
    KEL.typ.nuid UID;
    KEL.typ.ntyp(E_Business_Prox().Typ) Site_;
    KEL.typ.ntyp(E_Phone().Typ) Phone_Number_;
    KEL.typ.nstr Best_Phone_;
    KEL.typ.nint Best_Phone_Rank_;
    KEL.typ.ndataset(E_Prox_Phone_Number(__in,__cfg).S_I_C_Codes_Layout) S_I_C_Codes_;
    KEL.typ.ndataset(E_Prox_Phone_Number(__in,__cfg).N_A_I_C_S_Codes_Layout) N_A_I_C_S_Codes_;
    KEL.typ.ndataset(E_Prox_Phone_Number(__in,__cfg).Data_Sources_Layout) Data_Sources_;
  END;
  SHARED __EE70179 := PROJECT(__EE70108,TRANSFORM(__ST56176_Layout,SELF.UID := LEFT.____grp___U_I_D_,SELF := LEFT));
  SHARED __ST56224_Layout := RECORD
    KEL.typ.nuid UID;
    KEL.typ.nstr Best_Phone_;
    KEL.typ.epoch Date_First_Seen_ := 0;
    KEL.typ.epoch Date_Last_Seen_ := 0;
  END;
  SHARED __EE70193 := PROJECT(__EE70179,__ST56224_Layout);
  SHARED __ST56253_Layout := RECORD
    KEL.typ.nuid UID;
    KEL.typ.nstr O_N_L_Y___Best_Phone_;
    KEL.typ.epoch Date_First_Seen_ := 0;
    KEL.typ.epoch Date_Last_Seen_ := 0;
  END;
  SHARED __EE70207 := PROJECT(__EE70193,TRANSFORM(__ST56253_Layout,SELF.O_N_L_Y___Best_Phone_ := LEFT.Best_Phone_,SELF := LEFT));
  SHARED __ST59704_Layout := RECORD
    KEL.typ.nuid UID;
    KEL.typ.nint Ult_I_D_;
    KEL.typ.nint Org_I_D_;
    KEL.typ.nint Sele_I_D_;
    KEL.typ.nint Prox_I_D_;
    KEL.typ.ntyp(E_Business_Sele().Typ) Prox_Sele_;
    KEL.typ.nint Parent_Prox_I_D_;
    KEL.typ.nint Sele_Prox_I_D_;
    KEL.typ.nint Org_Prox_I_D_;
    KEL.typ.nint Ult_Prox_I_D_;
    KEL.typ.nint Levels_From_Top_;
    KEL.typ.nint Nodes_Below_;
    KEL.typ.nstr Prox_Segment_;
    KEL.typ.nstr Store_Number_;
    KEL.typ.nstr Active_Duns_Number_;
    KEL.typ.nstr Hist_Duns_Number_;
    KEL.typ.nstr Duns_Number_;
    KEL.typ.nint Equifax_I_D_;
    KEL.typ.ndataset(E_Business_Prox(__in,__cfg).Cortera_Layout) Cortera_;
    KEL.typ.ndataset(E_Business_Prox(__in,__cfg).Deleted_I_D_Numbers_Layout) Deleted_I_D_Numbers_;
    KEL.typ.ndataset(E_Business_Prox(__in,__cfg).Best_Company_Names_Layout) Best_Company_Names_;
    KEL.typ.ndataset(E_Business_Prox(__in,__cfg).Best_S_I_C_Codes_Layout) Best_S_I_C_Codes_;
    KEL.typ.ndataset(E_Business_Prox(__in,__cfg).Best_N_A_I_C_S_Codes_Layout) Best_N_A_I_C_S_Codes_;
    KEL.typ.ndataset(E_Business_Prox(__in,__cfg).O_S_H_A_Inspection_Layout) O_S_H_A_Inspection_;
    KEL.typ.ndataset(E_Business_Prox(__in,__cfg).O_S_H_A_Violations_Layout) O_S_H_A_Violations_;
    KEL.typ.ndataset(E_Business_Prox(__in,__cfg).O_S_H_A_Business_Information_Layout) O_S_H_A_Business_Information_;
    KEL.typ.ndataset(E_Business_Prox(__in,__cfg).Vendor_Dates_Layout) Vendor_Dates_;
    KEL.typ.ndataset(E_Business_Prox(__in,__cfg).Associated_Address_Type_Layout) Associated_Address_Type_;
    KEL.typ.ndataset(E_Business_Prox(__in,__cfg).Business_Characteristics_Layout) Business_Characteristics_;
    KEL.typ.ndataset(E_Business_Prox(__in,__cfg).Location_Status_Layout) Location_Status_;
    KEL.typ.ndataset(E_Business_Prox(__in,__cfg).Marketability_Layout) Marketability_;
    KEL.typ.ndataset(E_Business_Prox(__in,__cfg).Business_Owned_Characteristics_Layout) Business_Owned_Characteristics_;
    KEL.typ.ndataset(E_Business_Prox(__in,__cfg).Contacts_Layout) Contacts_;
    KEL.typ.ndataset(E_Business_Prox(__in,__cfg).Data_Sources_Layout) Data_Sources_;
    KEL.typ.ndataset(E_Prox_Address(__in,__cfg).Best_Addresses_Layout) Best_Prox_Address_;
    KEL.typ.nuid U_I_D__1_;
    KEL.typ.nint O_N_L_Y___Best_T_I_N_;
    KEL.typ.nuid U_I_D__2_;
    KEL.typ.nstr O_N_L_Y___Best_Phone_;
    KEL.typ.epoch Date_First_Seen_ := 0;
    KEL.typ.epoch Date_Last_Seen_ := 0;
    KEL.typ.int __RecordCount := 0;
  END;
  __JC70213(__ST58673_Layout __EE69045, __ST56253_Layout __EE70207) := __EEQP(__EE69045.UID,__EE70207.UID);
  __ST59704_Layout __JT70213(__ST58673_Layout __l, __ST56253_Layout __r) := TRANSFORM
    SELF.U_I_D__2_ := __r.UID;
    SELF := __l;
    SELF := __r;
  END;
  SHARED __EE70408 := JOIN(__EE69045,__EE70207,__JC70213(LEFT,RIGHT),__JT70213(LEFT,RIGHT),LEFT OUTER,MANY LOOKUP,KEEP(1));
  SHARED __EE67642 := __ENH_Business_Sele_1;
  SHARED __ST60734_Layout := RECORD
    KEL.typ.nuid UID;
    KEL.typ.nint Ult_I_D_;
    KEL.typ.nint Org_I_D_;
    KEL.typ.nint Sele_I_D_;
    KEL.typ.nint Prox_I_D_;
    KEL.typ.ntyp(E_Business_Sele().Typ) Prox_Sele_;
    KEL.typ.nint Parent_Prox_I_D_;
    KEL.typ.nint Sele_Prox_I_D_;
    KEL.typ.nint Org_Prox_I_D_;
    KEL.typ.nint Ult_Prox_I_D_;
    KEL.typ.nint Levels_From_Top_;
    KEL.typ.nint Nodes_Below_;
    KEL.typ.nstr Prox_Segment_;
    KEL.typ.nstr Store_Number_;
    KEL.typ.nstr Active_Duns_Number_;
    KEL.typ.nstr Hist_Duns_Number_;
    KEL.typ.nstr Duns_Number_;
    KEL.typ.nint Equifax_I_D_;
    KEL.typ.ndataset(E_Business_Prox(__in,__cfg).Cortera_Layout) Cortera_;
    KEL.typ.ndataset(E_Business_Prox(__in,__cfg).Deleted_I_D_Numbers_Layout) Deleted_I_D_Numbers_;
    KEL.typ.ndataset(E_Business_Prox(__in,__cfg).Best_Company_Names_Layout) Best_Company_Names_;
    KEL.typ.ndataset(E_Business_Prox(__in,__cfg).Best_S_I_C_Codes_Layout) Best_S_I_C_Codes_;
    KEL.typ.ndataset(E_Business_Prox(__in,__cfg).Best_N_A_I_C_S_Codes_Layout) Best_N_A_I_C_S_Codes_;
    KEL.typ.ndataset(E_Business_Prox(__in,__cfg).O_S_H_A_Inspection_Layout) O_S_H_A_Inspection_;
    KEL.typ.ndataset(E_Business_Prox(__in,__cfg).O_S_H_A_Violations_Layout) O_S_H_A_Violations_;
    KEL.typ.ndataset(E_Business_Prox(__in,__cfg).O_S_H_A_Business_Information_Layout) O_S_H_A_Business_Information_;
    KEL.typ.ndataset(E_Business_Prox(__in,__cfg).Vendor_Dates_Layout) Vendor_Dates_;
    KEL.typ.ndataset(E_Business_Prox(__in,__cfg).Associated_Address_Type_Layout) Associated_Address_Type_;
    KEL.typ.ndataset(E_Business_Prox(__in,__cfg).Business_Characteristics_Layout) Business_Characteristics_;
    KEL.typ.ndataset(E_Business_Prox(__in,__cfg).Location_Status_Layout) Location_Status_;
    KEL.typ.ndataset(E_Business_Prox(__in,__cfg).Marketability_Layout) Marketability_;
    KEL.typ.ndataset(E_Business_Prox(__in,__cfg).Business_Owned_Characteristics_Layout) Business_Owned_Characteristics_;
    KEL.typ.ndataset(E_Business_Prox(__in,__cfg).Contacts_Layout) Contacts_;
    KEL.typ.ndataset(E_Business_Prox(__in,__cfg).Data_Sources_Layout) Data_Sources_;
    KEL.typ.ndataset(E_Prox_Address(__in,__cfg).Best_Addresses_Layout) Best_Prox_Address_;
    KEL.typ.nuid U_I_D__1_;
    KEL.typ.nint O_N_L_Y___Best_T_I_N_;
    KEL.typ.nuid U_I_D__2_;
    KEL.typ.nstr O_N_L_Y___Best_Phone_;
    KEL.typ.nuid U_I_D__3_;
    KEL.typ.nint Ult_I_D__1_;
    KEL.typ.nint Org_I_D__1_;
    KEL.typ.nint Sele_I_D__1_;
    KEL.typ.ntyp(E_Business_Org().Typ) Sele_Org_;
    KEL.typ.nbool Sele_Gold_;
    KEL.typ.nbool Is_Sele_Level_;
    KEL.typ.nbool Is_Org_Level_;
    KEL.typ.nbool Is_Ult_Level_;
    KEL.typ.nstr Sele_Segment_;
    KEL.typ.nbool Is_Corporation_;
    KEL.typ.ndataset(E_Business_Sele(__in,__cfg).Business_Structure_Layout) Business_Structure_;
    KEL.typ.ndataset(E_Business_Sele(__in,__cfg).Ownership_Layout) Ownership_;
    KEL.typ.ndataset(E_Business_Sele(__in,__cfg).Industry_Layout) Industry_;
    KEL.typ.ndataset(E_Business_Sele(__in,__cfg).Company_Statuses_Layout) Company_Statuses_;
    KEL.typ.ndataset(E_Business_Sele(__in,__cfg).Age_Layout) Age_;
    KEL.typ.ndataset(E_Business_Sele(__in,__cfg).Reported_Names_Layout) Reported_Names_;
    KEL.typ.ndataset(E_Business_Sele(__in,__cfg).Stock_Tickers_Layout) Stock_Tickers_;
    KEL.typ.ndataset(E_Business_Sele(__in,__cfg).U_R_Ls_Layout) U_R_Ls_;
    KEL.typ.ndataset(E_Business_Sele(__in,__cfg).Vendor_Identification_Layout) Vendor_Identification_;
    KEL.typ.ndataset(E_Business_Sele(__in,__cfg).S_I_C_Codes_Layout) S_I_C_Codes_;
    KEL.typ.ndataset(E_Business_Sele(__in,__cfg).N_A_I_C_S_Codes_Layout) N_A_I_C_S_Codes_;
    KEL.typ.ndataset(E_Business_Sele(__in,__cfg).Employee_Counts_Layout) Employee_Counts_;
    KEL.typ.ndataset(E_Business_Sele(__in,__cfg).Sale_Amounts_Layout) Sale_Amounts_;
    KEL.typ.ndataset(E_Business_Sele(__in,__cfg).Earning_Amounts_Layout) Earning_Amounts_;
    KEL.typ.ndataset(E_Business_Sele(__in,__cfg).Asset_Amounts_Layout) Asset_Amounts_;
    KEL.typ.nkdate B_B_B_Member_Since_;
    KEL.typ.ndataset(E_Business_Sele(__in,__cfg).B_B_B_Categories_Layout) B_B_B_Categories_;
    KEL.typ.nbool For_Profit_Indicator_;
    KEL.typ.nstr Public_Or_Private_Indicator_;
    KEL.typ.ndataset(E_Business_Sele(__in,__cfg).S_O_S_Company_Types_Layout) S_O_S_Company_Types_;
    KEL.typ.ndataset(E_Business_Sele(__in,__cfg).S_O_S_Registered_Agents_Layout) S_O_S_Registered_Agents_;
    KEL.typ.ndataset(E_Business_Sele(__in,__cfg).S_O_S_Statuses_Layout) S_O_S_Statuses_;
    KEL.typ.ndataset(E_Business_Sele(__in,__cfg).S_O_S_Incorporation_Layout) S_O_S_Incorporation_;
    KEL.typ.ndataset(E_Business_Sele(__in,__cfg).S_O_S_Foreign_Information_Layout) S_O_S_Foreign_Information_;
    KEL.typ.ndataset(E_Business_Sele(__in,__cfg).S_O_S_Charter_Numbers_Layout) S_O_S_Charter_Numbers_;
    KEL.typ.ndataset(E_Business_Sele(__in,__cfg).S_O_S_Term_Exist_Codes_Layout) S_O_S_Term_Exist_Codes_;
    KEL.typ.ndataset(E_Business_Sele(__in,__cfg).Government_Debarred_Layout) Government_Debarred_;
    KEL.typ.ndataset(E_Business_Sele(__in,__cfg).Non_Profit_Layout) Non_Profit_;
    KEL.typ.ndataset(E_Business_Sele(__in,__cfg).Retirement_Plan_Information_Layout) Retirement_Plan_Information_;
    KEL.typ.ndataset(E_Business_Sele(__in,__cfg).Processing_Dates_Layout) Processing_Dates_;
    KEL.typ.ndataset(E_Business_Sele(__in,__cfg).Best_Company_Names_Layout) Best_Company_Names__1_;
    KEL.typ.ndataset(E_Business_Sele(__in,__cfg).Best_S_I_C_Codes_Layout) Best_S_I_C_Codes__1_;
    KEL.typ.ndataset(E_Business_Sele(__in,__cfg).Best_N_A_I_C_S_Codes_Layout) Best_N_A_I_C_S_Codes__1_;
    KEL.typ.ndataset(E_Business_Sele(__in,__cfg).Vendor_Dates_Layout) Vendor_Dates__1_;
    KEL.typ.ndataset(E_Business_Sele(__in,__cfg).Data_Sources_Layout) Data_Sources__1_;
    KEL.typ.nstr Best_Sele_Company_Name_;
    KEL.typ.nint Best_Sele_N_A_I_C_S_Code_;
    KEL.typ.nstr Best_Sele_Phone_;
    KEL.typ.nstr Best_Sele_Postal_City_;
    KEL.typ.nstr Best_Sele_Postdirectional_;
    KEL.typ.nstr Best_Sele_Predirectional_;
    KEL.typ.nstr Best_Sele_Primary_Name_;
    KEL.typ.nstr Best_Sele_Primary_Range_;
    KEL.typ.nint Best_Sele_S_I_C_Code_;
    KEL.typ.nstr Best_Sele_Secondary_Range_;
    KEL.typ.nstr Best_Sele_State_;
    KEL.typ.nstr Best_Sele_Suffix_;
    KEL.typ.nint Best_Sele_T_I_N_;
    KEL.typ.nstr Best_Sele_Unit_Designation_;
    KEL.typ.nstr Best_Sele_Vanity_City_;
    KEL.typ.nint Best_Sele_Zip4_;
    KEL.typ.ntyp(E_Zip_Code().Typ) Best_Sele_Zip5_;
    KEL.typ.epoch Date_First_Seen_ := 0;
    KEL.typ.epoch Date_Last_Seen_ := 0;
    KEL.typ.int __RecordCount := 0;
  END;
  __JC70608(__ST59704_Layout __EE70408, B_Business_Sele_1(__in,__cfg).__ST12298_Layout __EE67642) := __EEQP(__EE70408.Prox_Sele_,__EE67642.UID);
  __ST60734_Layout __JT70608(__ST59704_Layout __l, B_Business_Sele_1(__in,__cfg).__ST12298_Layout __r) := TRANSFORM
    SELF.U_I_D__3_ := __r.UID;
    SELF.Ult_I_D__1_ := __r.Ult_I_D_;
    SELF.Org_I_D__1_ := __r.Org_I_D_;
    SELF.Sele_I_D__1_ := __r.Sele_I_D_;
    SELF.Best_Company_Names__1_ := __r.Best_Company_Names_;
    SELF.Best_S_I_C_Codes__1_ := __r.Best_S_I_C_Codes_;
    SELF.Best_N_A_I_C_S_Codes__1_ := __r.Best_N_A_I_C_S_Codes_;
    SELF.Vendor_Dates__1_ := __r.Vendor_Dates_;
    SELF.Data_Sources__1_ := __r.Data_Sources_;
    SELF := __l;
    SELF := __r;
  END;
  SHARED __EE71010 := JOIN(__EE70408,__EE67642,__JC70608(LEFT,RIGHT),__JT70608(LEFT,RIGHT),LEFT OUTER,HASH);
  EXPORT __ST11730_Layout := RECORD
    KEL.typ.nuid UID;
    KEL.typ.nint Ult_I_D_;
    KEL.typ.nint Org_I_D_;
    KEL.typ.nint Sele_I_D_;
    KEL.typ.nint Prox_I_D_;
    KEL.typ.ntyp(E_Business_Sele().Typ) Prox_Sele_;
    KEL.typ.nint Parent_Prox_I_D_;
    KEL.typ.nint Sele_Prox_I_D_;
    KEL.typ.nint Org_Prox_I_D_;
    KEL.typ.nint Ult_Prox_I_D_;
    KEL.typ.nint Levels_From_Top_;
    KEL.typ.nint Nodes_Below_;
    KEL.typ.nstr Prox_Segment_;
    KEL.typ.nstr Store_Number_;
    KEL.typ.nstr Active_Duns_Number_;
    KEL.typ.nstr Hist_Duns_Number_;
    KEL.typ.nstr Duns_Number_;
    KEL.typ.nint Equifax_I_D_;
    KEL.typ.ndataset(E_Business_Prox(__in,__cfg).Cortera_Layout) Cortera_;
    KEL.typ.ndataset(E_Business_Prox(__in,__cfg).Deleted_I_D_Numbers_Layout) Deleted_I_D_Numbers_;
    KEL.typ.ndataset(E_Business_Prox(__in,__cfg).Best_Company_Names_Layout) Best_Company_Names_;
    KEL.typ.ndataset(E_Business_Prox(__in,__cfg).Best_S_I_C_Codes_Layout) Best_S_I_C_Codes_;
    KEL.typ.ndataset(E_Business_Prox(__in,__cfg).Best_N_A_I_C_S_Codes_Layout) Best_N_A_I_C_S_Codes_;
    KEL.typ.ndataset(E_Business_Prox(__in,__cfg).O_S_H_A_Inspection_Layout) O_S_H_A_Inspection_;
    KEL.typ.ndataset(E_Business_Prox(__in,__cfg).O_S_H_A_Violations_Layout) O_S_H_A_Violations_;
    KEL.typ.ndataset(E_Business_Prox(__in,__cfg).O_S_H_A_Business_Information_Layout) O_S_H_A_Business_Information_;
    KEL.typ.ndataset(E_Business_Prox(__in,__cfg).Vendor_Dates_Layout) Vendor_Dates_;
    KEL.typ.ndataset(E_Business_Prox(__in,__cfg).Associated_Address_Type_Layout) Associated_Address_Type_;
    KEL.typ.ndataset(E_Business_Prox(__in,__cfg).Business_Characteristics_Layout) Business_Characteristics_;
    KEL.typ.ndataset(E_Business_Prox(__in,__cfg).Location_Status_Layout) Location_Status_;
    KEL.typ.ndataset(E_Business_Prox(__in,__cfg).Marketability_Layout) Marketability_;
    KEL.typ.ndataset(E_Business_Prox(__in,__cfg).Business_Owned_Characteristics_Layout) Business_Owned_Characteristics_;
    KEL.typ.ndataset(E_Business_Prox(__in,__cfg).Contacts_Layout) Contacts_;
    KEL.typ.ndataset(E_Business_Prox(__in,__cfg).Data_Sources_Layout) Data_Sources_;
    KEL.typ.nstr Best_Prox_Company_Name_;
    KEL.typ.nint Best_Prox_N_A_I_C_S_Code_;
    KEL.typ.nstr Best_Prox_Phone_;
    KEL.typ.nstr Best_Prox_Postal_City_;
    KEL.typ.nstr Best_Prox_Postdirectional_;
    KEL.typ.nstr Best_Prox_Predirectional_;
    KEL.typ.nstr Best_Prox_Primary_Name_;
    KEL.typ.nstr Best_Prox_Primary_Range_;
    KEL.typ.nint Best_Prox_S_I_C_Code_;
    KEL.typ.nstr Best_Prox_Secondary_Range_;
    KEL.typ.nstr Best_Prox_State_;
    KEL.typ.nstr Best_Prox_Suffix_;
    KEL.typ.nint Best_Prox_T_I_N_;
    KEL.typ.nstr Best_Prox_Unit_Designation_;
    KEL.typ.nstr Best_Prox_Vanity_City_;
    KEL.typ.nint Best_Prox_Zip4_;
    KEL.typ.ntyp(E_Zip_Code().Typ) Best_Prox_Zip5_;
    KEL.typ.nstr Best_Sele_Company_Name_;
    KEL.typ.nint Best_Sele_N_A_I_C_S_Code_;
    KEL.typ.nstr Best_Sele_Phone_;
    KEL.typ.nstr Best_Sele_Postal_City_;
    KEL.typ.nstr Best_Sele_Postdirectional_;
    KEL.typ.nstr Best_Sele_Predirectional_;
    KEL.typ.nstr Best_Sele_Primary_Name_;
    KEL.typ.nstr Best_Sele_Primary_Range_;
    KEL.typ.nint Best_Sele_S_I_C_Code_;
    KEL.typ.nstr Best_Sele_Secondary_Range_;
    KEL.typ.nstr Best_Sele_State_;
    KEL.typ.nstr Best_Sele_Suffix_;
    KEL.typ.nint Best_Sele_T_I_N_;
    KEL.typ.nstr Best_Sele_Unit_Designation_;
    KEL.typ.nstr Best_Sele_Vanity_City_;
    KEL.typ.nint Best_Sele_Zip4_;
    KEL.typ.ntyp(E_Zip_Code().Typ) Best_Sele_Zip5_;
    KEL.typ.epoch Date_First_Seen_ := 0;
    KEL.typ.epoch Date_Last_Seen_ := 0;
    KEL.typ.int __RecordCount := 0;
  END;
  SHARED __ST11730_Layout __ND72140__Project(__ST60734_Layout __PP71011) := TRANSFORM
    __EE71691 := __PP71011.Best_Company_Names_;
    __BS71695 := __T(__EE71691);
    __EE71702 := __BN(TOPN(__BS71695(__NN(__T(__EE71691).Best_Company_Name_Rank_)),1,__T(__T(__EE71691).Best_Company_Name_Rank_),__T(Best_Company_Name_)),__NL(__EE71691));
    SELF.Best_Prox_Company_Name_ := (__T(__EE71702))[1].Best_Company_Name_;
    __EE71711 := __PP71011.Best_N_A_I_C_S_Codes_;
    __BS71715 := __T(__EE71711);
    __EE71722 := __BN(TOPN(__BS71715(__NN(__T(__EE71711).Best_N_A_I_C_S_Code_Rank_)),1,__T(__T(__EE71711).Best_N_A_I_C_S_Code_Rank_),__T(Best_N_A_I_C_S_Code_)),__NL(__EE71711));
    SELF.Best_Prox_N_A_I_C_S_Code_ := (__T(__EE71722))[1].Best_N_A_I_C_S_Code_;
    SELF.Best_Prox_Phone_ := __PP71011.O_N_L_Y___Best_Phone_;
    __EE71733 := __PP71011.Best_Prox_Address_;
    SELF.Best_Prox_Postal_City_ := (__T(__EE71733))[1].Best_Postal_City_;
    __EE71745 := __PP71011.Best_Prox_Address_;
    SELF.Best_Prox_Postdirectional_ := (__T(__EE71745))[1].Best_Postdirectional_;
    __EE71757 := __PP71011.Best_Prox_Address_;
    SELF.Best_Prox_Predirectional_ := (__T(__EE71757))[1].Best_Predirectional_;
    __EE71769 := __PP71011.Best_Prox_Address_;
    SELF.Best_Prox_Primary_Name_ := (__T(__EE71769))[1].Best_Primary_Name_;
    __EE71781 := __PP71011.Best_Prox_Address_;
    SELF.Best_Prox_Primary_Range_ := (__T(__EE71781))[1].Best_Primary_Range_;
    __EE71793 := __PP71011.Best_S_I_C_Codes_;
    __BS71797 := __T(__EE71793);
    __EE71804 := __BN(TOPN(__BS71797(__NN(__T(__EE71793).Best_S_I_C_Code_Rank_)),1,__T(__T(__EE71793).Best_S_I_C_Code_Rank_),__T(Best_S_I_C_Code_)),__NL(__EE71793));
    SELF.Best_Prox_S_I_C_Code_ := (__T(__EE71804))[1].Best_S_I_C_Code_;
    __EE71813 := __PP71011.Best_Prox_Address_;
    SELF.Best_Prox_Secondary_Range_ := (__T(__EE71813))[1].Best_Secondary_Range_;
    __EE71825 := __PP71011.Best_Prox_Address_;
    SELF.Best_Prox_State_ := (__T(__EE71825))[1].Best_State_;
    __EE71837 := __PP71011.Best_Prox_Address_;
    SELF.Best_Prox_Suffix_ := (__T(__EE71837))[1].Best_Suffix_;
    SELF.Best_Prox_T_I_N_ := __PP71011.O_N_L_Y___Best_T_I_N_;
    __EE71851 := __PP71011.Best_Prox_Address_;
    SELF.Best_Prox_Unit_Designation_ := (__T(__EE71851))[1].Best_Unit_Designation_;
    __EE71863 := __PP71011.Best_Prox_Address_;
    SELF.Best_Prox_Vanity_City_ := (__T(__EE71863))[1].Best_Vanity_City_;
    __EE71875 := __PP71011.Best_Prox_Address_;
    SELF.Best_Prox_Zip4_ := (__T(__EE71875))[1].Best_Zip4_;
    __EE71887 := __PP71011.Best_Prox_Address_;
    SELF.Best_Prox_Zip5_ := (__T(__EE71887))[1].Best_Zip5_;
    SELF := __PP71011;
  END;
  EXPORT __ENH_Business_Prox := PROJECT(__EE71010,__ND72140__Project(LEFT));
END;
