//HPCC Systems KEL Compiler Version 1.5.0rc1
IMPORT KEL15 AS KEL;
IMPORT B_Person_10,B_Person_6,B_Person_Accident_8,B_Person_S_S_N_6,CFG_Compile,E_Accident,E_Address,E_Email,E_Geo_Link,E_Input_P_I_I,E_Person,E_Person_Accident,E_Person_S_S_N,E_Phone,E_Property,E_Social_Security_Number,E_Surname,E_Zip_Code,FN_Compile FROM PublicRecords_KEL;
IMPORT * FROM KEL15.Null;
EXPORT B_Person_5(CFG_Compile __cfg = CFG_Compile) := MODULE
  SHARED VIRTUAL TYPEOF(B_Person_6(__cfg).__ENH_Person_6) __ENH_Person_6 := B_Person_6(__cfg).__ENH_Person_6;
  SHARED VIRTUAL TYPEOF(B_Person_S_S_N_6(__cfg).__ENH_Person_S_S_N_6) __ENH_Person_S_S_N_6 := B_Person_S_S_N_6(__cfg).__ENH_Person_S_S_N_6;
  SHARED __EE5378920 := __ENH_Person_6;
  SHARED __EE5378922 := __ENH_Person_S_S_N_6;
  SHARED __EE5382293 := __EE5378922(__T(__AND(__EE5378922.Input_S_S_N_Match_,__CN(__NN(__EE5378922.Subject_)))));
  SHARED __ST557395_Layout := RECORD
    KEL.typ.ntyp(E_Person().Typ) Subject_;
    KEL.typ.ntyp(E_Social_Security_Number().Typ) Social_;
    KEL.typ.ndataset(E_Person_S_S_N(__cfg).Valid_S_S_N_Layout) Valid_S_S_N_;
    KEL.typ.ndataset(B_Person_S_S_N_6(__cfg).__ST254615_Layout) Data_Sources_;
    KEL.typ.nbool Input_S_S_N_Match_;
    KEL.typ.nstr Source_;
    KEL.typ.nbool Header_Hit_Flag_;
    KEL.typ.nbool F_D_N_Indicator_;
    KEL.typ.nbool Death_Master_Flag_;
    KEL.typ.nkdate My_Date_First_Seen_;
    KEL.typ.nkdate My_Date_Last_Seen_;
    KEL.typ.nstr Translated_Source_;
    KEL.typ.epoch Archive___Date_ := 0;
    KEL.typ.epoch Date_First_Seen_ := 0;
    KEL.typ.epoch Date_Last_Seen_ := 0;
    KEL.typ.epoch Hybrid_Archive_Date_ := 0;
    KEL.typ.epoch Vault_Date_Last_Seen_ := 0;
    KEL.typ.int __RecordCount := 0;
  END;
  __JC5382310(B_Person_S_S_N_6(__cfg).__ST254607_Layout __EE5382293, B_Person_S_S_N_6(__cfg).__ST254615_Layout __EE5382296) := __T(__EE5382296.Header_Hit_Flag_);
  __ST557395_Layout __JT5382310(B_Person_S_S_N_6(__cfg).__ST254607_Layout __l, B_Person_S_S_N_6(__cfg).__ST254615_Layout __r) := TRANSFORM, SKIP(NOT(__JC5382310(__l,__r)))
    SELF.Archive___Date_ := __r.Archive___Date_;
    SELF.Date_First_Seen_ := __r.Date_First_Seen_;
    SELF.Date_Last_Seen_ := __r.Date_Last_Seen_;
    SELF.Hybrid_Archive_Date_ := __r.Hybrid_Archive_Date_;
    SELF.Vault_Date_Last_Seen_ := __r.Vault_Date_Last_Seen_;
    SELF.__RecordCount := __r.__RecordCount;
    SELF := __l;
    SELF := __r;
  END;
  SHARED __EE5382311 := NORMALIZE(__EE5382293,__T(LEFT.Data_Sources_),__JT5382310(LEFT,RIGHT));
  SHARED __ST555218_Layout := RECORD
    KEL.typ.ntyp(E_Person().Typ) Subject_;
    KEL.typ.ntyp(E_Social_Security_Number().Typ) Social_;
    KEL.typ.ndataset(E_Person_S_S_N(__cfg).Valid_S_S_N_Layout) Valid_S_S_N_;
    KEL.typ.ndataset(B_Person_S_S_N_6(__cfg).__ST254615_Layout) Data_Sources_;
    KEL.typ.nbool Input_S_S_N_Match_;
    KEL.typ.nstr Source_;
    KEL.typ.nbool Header_Hit_Flag_;
    KEL.typ.nbool F_D_N_Indicator_;
    KEL.typ.nbool Death_Master_Flag_;
    KEL.typ.nkdate My_Date_First_Seen_;
    KEL.typ.nkdate My_Date_Last_Seen_;
    KEL.typ.nstr Translated_Source_;
    KEL.typ.ntyp(E_Person().Typ) UID;
    KEL.typ.epoch Archive___Date_ := 0;
    KEL.typ.epoch Date_First_Seen_ := 0;
    KEL.typ.epoch Date_Last_Seen_ := 0;
    KEL.typ.epoch Hybrid_Archive_Date_ := 0;
    KEL.typ.epoch Vault_Date_Last_Seen_ := 0;
    KEL.typ.int __RecordCount := 0;
  END;
  SHARED __EE5382412 := PROJECT(__EE5382311,TRANSFORM(__ST555218_Layout,SELF.UID := LEFT.Subject_,SELF := LEFT));
  SHARED __ST556260_Layout := RECORD
    KEL.typ.nstr Translated_Source_;
    KEL.typ.ntyp(E_Person().Typ) UID;
    KEL.typ.nkdate My_Date_First_Seen_;
    KEL.typ.nkdate My_Date_Last_Seen_;
    KEL.typ.epoch Archive___Date_ := 0;
    KEL.typ.epoch Date_First_Seen_ := 0;
    KEL.typ.epoch Date_Last_Seen_ := 0;
    KEL.typ.epoch Hybrid_Archive_Date_ := 0;
    KEL.typ.epoch Vault_Date_Last_Seen_ := 0;
    KEL.typ.int __RecordCount := 0;
  END;
  SHARED __EE5382434 := PROJECT(__EE5382412,__ST556260_Layout);
  SHARED __ST556284_Layout := RECORD
    KEL.typ.nkdate M_I_N___My_Date_First_Seen_;
    KEL.typ.nkdate M_A_X___My_Date_Last_Seen_;
    KEL.typ.nstr Translated_Source_;
    KEL.typ.ntyp(E_Person().Typ) UID;
    KEL.typ.epoch Archive___Date_ := 0;
    KEL.typ.epoch Date_First_Seen_ := 0;
    KEL.typ.epoch Date_Last_Seen_ := 0;
    KEL.typ.epoch Hybrid_Archive_Date_ := 0;
    KEL.typ.epoch Vault_Date_Last_Seen_ := 0;
    KEL.typ.int __RecordCount := 0;
  END;
  SHARED __EE5382459 := PROJECT(__CLEANANDDO(__EE5382434,TABLE(__EE5382434,{KEL.typ.int __RecordCount := SUM(GROUP,__RecordCount),KEL.typ.epoch Archive___Date_ := KEL.era.SimpleRoll(GROUP,Archive___Date_,MIN,FALSE),KEL.typ.epoch Date_First_Seen_ := KEL.era.SimpleRoll(GROUP,Date_First_Seen_,MIN,FALSE),KEL.typ.epoch Date_Last_Seen_ := KEL.era.SimpleRoll(GROUP,Date_Last_Seen_,MAX,FALSE),KEL.typ.epoch Hybrid_Archive_Date_ := KEL.era.SimpleRoll(GROUP,Hybrid_Archive_Date_,MIN,FALSE),KEL.typ.epoch Vault_Date_Last_Seen_ := KEL.era.SimpleRoll(GROUP,Vault_Date_Last_Seen_,MAX,NMAX),KEL.Aggregates.MinNG(__EE5382434.My_Date_First_Seen_) M_I_N___My_Date_First_Seen_,KEL.Aggregates.MaxNG(__EE5382434.My_Date_Last_Seen_) M_A_X___My_Date_Last_Seen_,Translated_Source_,UID},Translated_Source_,UID,MERGE)),__ST556284_Layout);
  SHARED __ST566913_Layout := RECORD
    KEL.typ.nuid UID;
    KEL.typ.nstr Gender_;
    KEL.typ.nstr Lex_I_D_Segment_;
    KEL.typ.nstr Lex_I_D_Segment2_;
    KEL.typ.ndataset(B_Person_6(__cfg).__ST281141_Layout) Full_Name_;
    KEL.typ.ndataset(B_Person_6(__cfg).__ST281156_Layout) Reported_Dates_Of_Birth_;
    KEL.typ.ndataset(E_Person(__cfg).Reported_Dates_Of_Death_Layout) Reported_Dates_Of_Death_;
    KEL.typ.nstr Race_;
    KEL.typ.nstr Race_Description_;
    KEL.typ.ndataset(B_Person_6(__cfg).__ST281170_Layout) Data_Sources_;
    KEL.typ.ndataset(E_Person(__cfg).Dunn_Data_Layout) Dunn_Data_;
    KEL.typ.ndataset(E_Person(__cfg).Conceal_Carry_Layout) Conceal_Carry_;
    KEL.typ.ndataset(E_Person(__cfg).Hunt_Fish_Layout) Hunt_Fish_;
    KEL.typ.ndataset(E_Person(__cfg).Consumer_Statement_Flags_Layout) Consumer_Statement_Flags_;
    KEL.typ.ndataset(E_Person(__cfg).Thrive_Layout) Thrive_;
    KEL.typ.ndataset(B_Person_Accident_8(__cfg).__ST260733_Layout) Accident_Recs_;
    KEL.typ.ndataset(B_Person_6(__cfg).__ST99323_Layout) Accident_Recs_Formatted_;
    KEL.typ.ndataset(B_Person_10(__cfg).__ST89792_Layout) Address_Hierarchy_Set_;
    KEL.typ.ndataset(B_Person_6(__cfg).__ST466257_Layout) All_Lien_Data_;
    KEL.typ.nkdate B_U_I_L_D___D_A_T_E_;
    KEL.typ.nstr Curr_Addr_Full_;
    KEL.typ.ndataset(B_Person_10(__cfg).__ST89792_Layout) Curr_Addr_Full_Set_;
    KEL.typ.ndataset(B_Person_6(__cfg).__ST92331_Layout) Edu_Rec_Ver_Source_List_Pre_;
    KEL.typ.nstr Ln_J7_Y_Old_Date_;
    KEL.typ.ntyp(E_Input_P_I_I().Typ) P_I_I_;
    KEL.typ.int P_L___Drg_Ln_J_Cnt7_Y_ := 0;
    KEL.typ.nstr P___Inp_Cln_Name_First_Raw_;
    KEL.typ.nstr P___Inp_Cln_Name_Last_Raw_;
    KEL.typ.nstr P___Inp_Cln_S_S_N_;
    KEL.typ.str P___Lex_I_D_Seen_Flag_ := '';
    KEL.typ.ndataset(B_Person_10(__cfg).__ST89792_Layout) Prev_Addr_Full_Set_;
    KEL.typ.ndataset(B_Person_10(__cfg).__ST89792_Layout) Recent_Addr_Full_Set_;
    KEL.typ.ndataset(B_Person_6(__cfg).__ST98867_Layout) Translated_Sources_;
    KEL.typ.ndataset(B_Person_6(__cfg).__ST99901_Layout) Verified_First_Name_Sources_;
    KEL.typ.ndataset(B_Person_6(__cfg).__ST100063_Layout) Verified_Last_Name_Sources_;
    KEL.typ.ndataset(__ST556284_Layout) Exp1_;
    KEL.typ.epoch Archive___Date_ := 0;
    KEL.typ.epoch Date_First_Seen_ := 0;
    KEL.typ.epoch Date_Last_Seen_ := 0;
    KEL.typ.epoch Hybrid_Archive_Date_ := 0;
    KEL.typ.epoch Vault_Date_Last_Seen_ := 0;
    KEL.typ.int __RecordCount := 0;
  END;
  __JC5382465(B_Person_6(__cfg).__ST281135_Layout __EE5378920, __ST556284_Layout __EE5382459) := __EEQP(__EE5378920.UID,__EE5382459.UID);
  __ST566913_Layout __Join__ST566913_Layout(B_Person_6(__cfg).__ST281135_Layout __r, DATASET(__ST556284_Layout) __recs) := TRANSFORM
    SELF := __r;
    SELF.Exp1_ := __CN(__recs);
  END;
  SHARED __EE5382752 := DENORMALIZE(DISTRIBUTE(__EE5378920,HASH(UID)),DISTRIBUTE(__EE5382459,HASH(UID)),__JC5382465(LEFT,RIGHT),GROUP,__Join__ST566913_Layout(LEFT,ROWS(RIGHT)),LOCAL);
  EXPORT __ST299549_Layout := RECORD
    KEL.typ.nstr Title_;
    KEL.typ.nstr First_Name_;
    KEL.typ.nstr Middle_Name_;
    KEL.typ.nstr Last_Name_;
    KEL.typ.nstr Name_Suffix_;
    KEL.typ.nstr Name_Score_;
    KEL.typ.nbool Header_Hit_Flag_;
    KEL.typ.nbool Best_;
    KEL.typ.nstr Source_;
    KEL.typ.nstr Translated_Source_Code_;
    KEL.typ.bool Verified_First_Name_ := FALSE;
    KEL.typ.bool Verified_Last_Name_ := FALSE;
    KEL.typ.epoch Archive___Date_ := 0;
    KEL.typ.epoch Date_First_Seen_ := 0;
    KEL.typ.epoch Date_Last_Seen_ := 0;
    KEL.typ.epoch Hybrid_Archive_Date_ := 0;
    KEL.typ.epoch Vault_Date_Last_Seen_ := 0;
    KEL.typ.int __RecordCount := 0;
  END;
  EXPORT __ST299564_Layout := RECORD
    KEL.typ.nkdate Date_Of_Birth_;
    KEL.typ.nbool Header_Hit_Flag_;
    KEL.typ.nbool Best_;
    KEL.typ.nbool Best_D_O_B_Rec_;
    KEL.typ.nbool D_O_B_Best_Not_Null_;
    KEL.typ.epoch Archive___Date_ := 0;
    KEL.typ.epoch Date_First_Seen_ := 0;
    KEL.typ.epoch Date_Last_Seen_ := 0;
    KEL.typ.epoch Hybrid_Archive_Date_ := 0;
    KEL.typ.epoch Vault_Date_Last_Seen_ := 0;
    KEL.typ.int __RecordCount := 0;
  END;
  EXPORT __ST299579_Layout := RECORD
    KEL.typ.nstr Source_;
    KEL.typ.nbool Header_Hit_Flag_;
    KEL.typ.nbool F_D_N_Indicator_;
    KEL.typ.nstr Translated_Source_Code_;
    KEL.typ.epoch Archive___Date_ := 0;
    KEL.typ.epoch Date_First_Seen_ := 0;
    KEL.typ.epoch Date_Last_Seen_ := 0;
    KEL.typ.epoch Hybrid_Archive_Date_ := 0;
    KEL.typ.epoch Vault_Date_Last_Seen_ := 0;
    KEL.typ.int __RecordCount := 0;
  END;
  EXPORT __ST92358_Layout := RECORD
    KEL.typ.nstr File_Type_;
    KEL.typ.nstr Source_Date_First_Seen_;
    KEL.typ.nstr Source_Date_Last_Seen_;
    KEL.typ.epoch Archive___Date_ := 0;
    KEL.typ.epoch Date_First_Seen_ := 0;
    KEL.typ.epoch Date_Last_Seen_ := 0;
    KEL.typ.epoch Hybrid_Archive_Date_ := 0;
    KEL.typ.epoch Vault_Date_Last_Seen_ := 0;
    KEL.typ.int __RecordCount := 0;
  END;
  EXPORT __ST100241_Layout := RECORD
    KEL.typ.nstr Translated_Source_;
    KEL.typ.nkdate My_Date_First_Seen_;
    KEL.typ.nkdate My_Date_Last_Seen_;
    KEL.typ.epoch Archive___Date_ := 0;
    KEL.typ.epoch Date_First_Seen_ := 0;
    KEL.typ.epoch Date_Last_Seen_ := 0;
    KEL.typ.epoch Hybrid_Archive_Date_ := 0;
    KEL.typ.epoch Vault_Date_Last_Seen_ := 0;
    KEL.typ.int __RecordCount := 0;
  END;
  EXPORT __ST551805_Layout := RECORD
    KEL.typ.nstr Translated_Source_Code_;
    KEL.typ.nint Age_In_Days_;
    KEL.typ.epoch Archive___Date_ := 0;
    KEL.typ.epoch Date_First_Seen_ := 0;
    KEL.typ.epoch Date_Last_Seen_ := 0;
    KEL.typ.epoch Hybrid_Archive_Date_ := 0;
    KEL.typ.epoch Vault_Date_Last_Seen_ := 0;
    KEL.typ.int __RecordCount := 0;
  END;
  EXPORT __ST99963_Layout := RECORD
    KEL.typ.nstr Translated_Source_Code_;
    KEL.typ.nstr Source_Date_First_Seen_;
    KEL.typ.nstr First_Seen_Date_;
    KEL.typ.nstr Source_Date_Last_Seen_;
    KEL.typ.nint Age_In_Days_;
    KEL.typ.epoch Archive___Date_ := 0;
    KEL.typ.epoch Date_First_Seen_ := 0;
    KEL.typ.epoch Date_Last_Seen_ := 0;
    KEL.typ.epoch Hybrid_Archive_Date_ := 0;
    KEL.typ.epoch Vault_Date_Last_Seen_ := 0;
    KEL.typ.int __RecordCount := 0;
  END;
  EXPORT __ST100125_Layout := RECORD
    KEL.typ.nstr Translated_Source_Code_;
    KEL.typ.nstr Source_Date_First_Seen_;
    KEL.typ.nstr First_Seen_Date_;
    KEL.typ.nstr Source_Date_Last_Seen_;
    KEL.typ.nint Age_In_Days_;
    KEL.typ.epoch Archive___Date_ := 0;
    KEL.typ.epoch Date_First_Seen_ := 0;
    KEL.typ.epoch Date_Last_Seen_ := 0;
    KEL.typ.epoch Hybrid_Archive_Date_ := 0;
    KEL.typ.epoch Vault_Date_Last_Seen_ := 0;
    KEL.typ.int __RecordCount := 0;
  END;
  EXPORT __ST299543_Layout := RECORD
    KEL.typ.nuid UID;
    KEL.typ.nstr Gender_;
    KEL.typ.nstr Lex_I_D_Segment_;
    KEL.typ.nstr Lex_I_D_Segment2_;
    KEL.typ.ndataset(__ST299549_Layout) Full_Name_;
    KEL.typ.ndataset(__ST299564_Layout) Reported_Dates_Of_Birth_;
    KEL.typ.ndataset(E_Person(__cfg).Reported_Dates_Of_Death_Layout) Reported_Dates_Of_Death_;
    KEL.typ.nstr Race_;
    KEL.typ.nstr Race_Description_;
    KEL.typ.ndataset(__ST299579_Layout) Data_Sources_;
    KEL.typ.ndataset(E_Person(__cfg).Dunn_Data_Layout) Dunn_Data_;
    KEL.typ.ndataset(E_Person(__cfg).Conceal_Carry_Layout) Conceal_Carry_;
    KEL.typ.ndataset(E_Person(__cfg).Hunt_Fish_Layout) Hunt_Fish_;
    KEL.typ.ndataset(E_Person(__cfg).Consumer_Statement_Flags_Layout) Consumer_Statement_Flags_;
    KEL.typ.ndataset(E_Person(__cfg).Thrive_Layout) Thrive_;
    KEL.typ.ndataset(B_Person_Accident_8(__cfg).__ST260733_Layout) Accident_Recs_;
    KEL.typ.ndataset(B_Person_6(__cfg).__ST99323_Layout) Accident_Recs_Formatted_;
    KEL.typ.ndataset(B_Person_6(__cfg).__ST99323_Layout) Accident_Recs_Formatted_Dedup_;
    KEL.typ.ndataset(B_Person_10(__cfg).__ST89792_Layout) Address_Hierarchy_Set_;
    KEL.typ.ndataset(B_Person_6(__cfg).__ST466257_Layout) All_Lien_Data_;
    KEL.typ.nkdate B_U_I_L_D___D_A_T_E_;
    KEL.typ.nkdate Best_D_O_B_;
    KEL.typ.nstr Curr_Addr_Full_;
    KEL.typ.ndataset(B_Person_10(__cfg).__ST89792_Layout) Curr_Addr_Full_Set_;
    B_Person_10(__cfg).__ST89792_Layout Current_;
    KEL.typ.ndataset(__ST92358_Layout) Edu_Rec_Ver_Source_List_;
    KEL.typ.ndataset(B_Person_6(__cfg).__ST92331_Layout) Edu_Rec_Ver_Source_List_Pre_;
    KEL.typ.nstr L_T_D7_Y_New_Date_;
    KEL.typ.nstr L_T_D7_Y_Old_Date_;
    KEL.typ.nstr Ln_J7_Y_New_Date_;
    KEL.typ.nstr Ln_J7_Y_Old_Date_;
    KEL.typ.ntyp(E_Input_P_I_I().Typ) P_I_I_;
    KEL.typ.int P_L___Drg_L_T_D_Cnt7_Y_ := 0;
    KEL.typ.int P_L___Drg_Ln_J_Cnt7_Y_ := 0;
    KEL.typ.nstr P_L___Drg_Ln_J_Old_Dt7_Y_;
    KEL.typ.nstr P___Inp_Cln_Name_First_Raw_;
    KEL.typ.nstr P___Inp_Cln_Name_Last_Raw_;
    KEL.typ.nstr P___Inp_Cln_S_S_N_;
    KEL.typ.str P___Lex_I_D_Seen_Flag_ := '';
    KEL.typ.ndataset(__ST100241_Layout) Person_S_S_N_Match_Sources_Pre_;
    KEL.typ.ndataset(B_Person_10(__cfg).__ST89792_Layout) Prev_Addr_Full_Set_;
    B_Person_10(__cfg).__ST89792_Layout Previous_;
    KEL.typ.ndataset(B_Person_10(__cfg).__ST89792_Layout) Recent_Addr_Full_Set_;
    KEL.typ.ndataset(__ST551805_Layout) Translated_Sources_;
    KEL.typ.ndataset(B_Person_6(__cfg).__ST99901_Layout) Verified_First_Name_Sources_;
    KEL.typ.ndataset(__ST99963_Layout) Verified_First_Name_Sources_With_Dates_;
    KEL.typ.ndataset(B_Person_6(__cfg).__ST100063_Layout) Verified_Last_Name_Sources_;
    KEL.typ.ndataset(__ST100125_Layout) Verified_Last_Name_Sources_With_Dates_;
    KEL.typ.epoch Archive___Date_ := 0;
    KEL.typ.epoch Date_First_Seen_ := 0;
    KEL.typ.epoch Date_Last_Seen_ := 0;
    KEL.typ.epoch Hybrid_Archive_Date_ := 0;
    KEL.typ.epoch Vault_Date_Last_Seen_ := 0;
    KEL.typ.int __RecordCount := 0;
  END;
  SHARED __ST299543_Layout __ND5382789__Project(__ST566913_Layout __PP5382785) := TRANSFORM
    __EE5382755 := __PP5382785.Full_Name_;
    SELF.Full_Name_ := __BN(PROJECT(__T(__EE5382755),__ST299549_Layout),__NL(__EE5382755));
    __EE5382759 := __PP5382785.Reported_Dates_Of_Birth_;
    __ST299564_Layout __ND5383130__Project(B_Person_6(__cfg).__ST281156_Layout __PP5383126) := TRANSFORM
      SELF.D_O_B_Best_Not_Null_ := __AND(__OP2(__PP5383126.Best_,=,__CN(TRUE)),__NOT(__NT(__PP5383126.Date_Of_Birth_)));
      SELF := __PP5383126;
    END;
    SELF.Reported_Dates_Of_Birth_ := __PROJECT(__EE5382759,__ND5383130__Project(LEFT));
    __EE5382763 := __PP5382785.Data_Sources_;
    SELF.Data_Sources_ := __BN(PROJECT(__T(__EE5382763),__ST299579_Layout),__NL(__EE5382763));
    __EE5383203 := __PP5382785.Accident_Recs_Formatted_;
    __EE5383217 := __BN(PROJECT(DEDUP(SORT(__T(__EE5383203),__T(__T(__EE5383203).Date_Of_Accident_), -__T(__T(__EE5383203).Estimated_Vehicle_Damage_),__T(Accident_Age_In_Days_),__T(Formatted_Date_)),__T(__OP2(LEFT.Date_Of_Accident_,=,RIGHT.Date_Of_Accident_))),B_Person_6(__cfg).__ST99323_Layout),__NL(__PP5382785.Accident_Recs_Formatted_));
    SELF.Accident_Recs_Formatted_Dedup_ := __EE5383217;
    __EE5383228 := __PP5382785.Reported_Dates_Of_Birth_;
    __BS5383232 := __T(__EE5383228);
    __EE5383237 := __BS5383232(__T(__T(__EE5383228).Best_D_O_B_Rec_));
    SELF.Best_D_O_B_ := (__EE5383237)[1].Date_Of_Birth_;
    __EE5383250 := __PP5382785.Curr_Addr_Full_Set_;
    SELF.Current_ := (__T(__EE5383250))[1];
    __EE5382767 := __PP5382785.Edu_Rec_Ver_Source_List_Pre_;
    __ST92358_Layout __ND5383258__Project(B_Person_6(__cfg).__ST92331_Layout __PP5383254) := TRANSFORM
      __CC15110 := '-99997';
      SELF.Source_Date_First_Seen_ := IF(__T(__FN1(KEL.Routines.IsValidDate,__PP5383254.Date_First_Seen_Min_)),__ECAST(KEL.typ.nstr,__FN2(KEL.Routines.DateToString,__PP5383254.Date_First_Seen_Min_,__CN('%Y%m%d'))),__ECAST(KEL.typ.nstr,__CN(__CC15110)));
      SELF.Source_Date_Last_Seen_ := IF(__T(__FN1(KEL.Routines.IsValidDate,__PP5383254.Date_Last_Seen_Max_)),__ECAST(KEL.typ.nstr,__FN2(KEL.Routines.DateToString,KEL.Routines.MinN(__PP5383254.Date_Last_Seen_Max_,__PP5382785.B_U_I_L_D___D_A_T_E_),__CN('%Y%m%d'))),__ECAST(KEL.typ.nstr,__CN(__CC15110)));
      SELF := __PP5383254;
    END;
    SELF.Edu_Rec_Ver_Source_List_ := __PROJECT(__EE5382767,__ND5383258__Project(LEFT));
    __EE5382783 := __PP5382785.All_Lien_Data_;
    __BS5383292 := __T(__EE5382783);
    __EE5383300 := __BS5383292(__T(__AND(__T(__EE5382783).Seen___In___Seven___Years_,__T(__EE5382783).Is_Landlord_Tenant_Dispute_)));
    __CC15042 := '-99997';
    SELF.L_T_D7_Y_New_Date_ := FN_Compile(__cfg).FN_Is_Blank(__ECAST(KEL.typ.nstr,__ECAST(KEL.typ.nstr,KEL.Aggregates.MaxN(__EE5383300,__EE5383300.Original_Filing_Date_))),__ECAST(KEL.typ.nstr,__CN(__CC15042)));
    __EE5383322 := __EE5383300;
    SELF.L_T_D7_Y_Old_Date_ := FN_Compile(__cfg).FN_Is_Blank(__ECAST(KEL.typ.nstr,__ECAST(KEL.typ.nstr,KEL.Aggregates.MinN(__EE5383322,__EE5383322.Original_Filing_Date_))),__ECAST(KEL.typ.nstr,__CN(__CC15042)));
    __EE5383335 := __PP5382785.All_Lien_Data_;
    __BS5383339 := __T(__EE5383335);
    __EE5383347 := __BS5383339(__T(__AND(__T(__EE5383335).Seen___In___Seven___Years_,__T(__EE5383335).Is_Over_All_Lien_Judgment_)));
    SELF.Ln_J7_Y_New_Date_ := FN_Compile(__cfg).FN_Is_Blank(__ECAST(KEL.typ.nstr,__ECAST(KEL.typ.nstr,KEL.Aggregates.MaxN(__EE5383347,__EE5383347.Original_Filing_Date_))),__ECAST(KEL.typ.nstr,__CN(__CC15042)));
    __CC15035 := -99999;
    __BS5383367 := __T(__PP5382785.All_Lien_Data_);
    SELF.P_L___Drg_L_T_D_Cnt7_Y_ := IF(__PP5382785.P___Lex_I_D_Seen_Flag_ = '0',__CC15035,KEL.Routines.BoundsFold(COUNT(__BS5383367(__T(__AND(__T(__PP5382785.All_Lien_Data_).Seen___In___Seven___Years_,__OP2(__T(__PP5382785.All_Lien_Data_).Is_Landlord_Tenant_Dispute_,=,__CN(TRUE)))))),0,999));
    __CC15032 := '-99999';
    __CC15037 := '-99998';
    __BS5383393 := __T(__PP5382785.All_Lien_Data_);
    SELF.P_L___Drg_Ln_J_Old_Dt7_Y_ := MAP(__PP5382785.P___Lex_I_D_Seen_Flag_ = '0'=>__ECAST(KEL.typ.nstr,__CN(__CC15032)),__PP5382785.P_L___Drg_Ln_J_Cnt7_Y_ < 1=>__ECAST(KEL.typ.nstr,__CN(__CC15037)), NOT EXISTS(__BS5383393(__T(__AND(__NOT(__OP2(__ECAST(KEL.typ.nstr,__T(__PP5382785.All_Lien_Data_).Original_Filing_Date_),=,__CN(__CC15042))),__AND(__T(__PP5382785.All_Lien_Data_).Seen___In___Seven___Years_,__T(__PP5382785.All_Lien_Data_).Is_Over_All_Lien_Judgment_)))))=>__ECAST(KEL.typ.nstr,__CN(__CC15042)),__ECAST(KEL.typ.nstr,__PP5382785.Ln_J7_Y_Old_Date_));
    __EE5382779 := __PP5382785.Exp1_;
    __ST100241_Layout __ND5383431__Project(__ST556284_Layout __PP5383427) := TRANSFORM
      SELF.My_Date_First_Seen_ := __PP5383427.M_I_N___My_Date_First_Seen_;
      SELF.My_Date_Last_Seen_ := __PP5383427.M_A_X___My_Date_Last_Seen_;
      SELF := __PP5383427;
    END;
    SELF.Person_S_S_N_Match_Sources_Pre_ := __PROJECT(__EE5382779,__ND5383431__Project(LEFT));
    __EE5383447 := __PP5382785.Prev_Addr_Full_Set_;
    SELF.Previous_ := (__T(__EE5383447))[1];
    __EE5383453 := __PP5382785.Translated_Sources_;
    __ST551805_Layout __ND5383461__Project(B_Person_6(__cfg).__ST98867_Layout __PP5383457) := TRANSFORM
      __CC14434 := KEL.Routines.MinN(FN_Compile(__cfg).FN_G_E_T_B_U_I_L_D_D_A_T_E(__ECAST(KEL.typ.nstr,__CN('header_build_version'))),__CN(__cfg.CurrentDate));
      SELF.Age_In_Days_ := FN_Compile(__cfg).FN_A_B_S_D_A_Y_S_B_E_T_W_E_E_N(__ECAST(KEL.typ.nkdate,KEL.era.ToDate(__PP5383457.Date_Last_Seen_)),__ECAST(KEL.typ.nkdate,__CC14434));
      SELF := __PP5383457;
    END;
    SELF.Translated_Sources_ := __PROJECT(__EE5383453,__ND5383461__Project(LEFT));
    __EE5382771 := __PP5382785.Verified_First_Name_Sources_;
    __ST99963_Layout __ND5383481__Project(B_Person_6(__cfg).__ST99901_Layout __PP5383477) := TRANSFORM
      __CC14434 := KEL.Routines.MinN(FN_Compile(__cfg).FN_G_E_T_B_U_I_L_D_D_A_T_E(__ECAST(KEL.typ.nstr,__CN('header_build_version'))),__CN(__cfg.CurrentDate));
      __CC15072 := '-99997';
      SELF.Source_Date_First_Seen_ := IF(__T(__FN1(KEL.Routines.IsValidDate,KEL.era.ToDate(__PP5383477.Date_First_Seen_))),__ECAST(KEL.typ.nstr,__FN2(KEL.Routines.DateToString,KEL.Routines.MinN(KEL.era.ToDate(__PP5383477.Date_First_Seen_),__CC14434),__CN('%Y%m%d'))),__ECAST(KEL.typ.nstr,__CN(__CC15072)));
      __CC66565 := '99999999';
      SELF.First_Seen_Date_ := IF(__T(__FN1(KEL.Routines.IsValidDate,KEL.era.ToDate(__PP5383477.Date_First_Seen_))),__ECAST(KEL.typ.nstr,__FN2(KEL.Routines.DateToString,KEL.Routines.MinN(KEL.era.ToDate(__PP5383477.Date_First_Seen_),__CC14434),__CN('%Y%m%d'))),__ECAST(KEL.typ.nstr,__CN(__CC66565)));
      SELF.Source_Date_Last_Seen_ := IF(__T(__FN1(KEL.Routines.IsValidDate,KEL.era.ToDate(__PP5383477.Date_Last_Seen_))),__ECAST(KEL.typ.nstr,__FN2(KEL.Routines.DateToString,KEL.Routines.MinN(KEL.era.ToDate(__PP5383477.Date_Last_Seen_),__CC14434),__CN('%Y%m%d'))),__ECAST(KEL.typ.nstr,__CN(__CC15072)));
      SELF.Age_In_Days_ := FN_Compile(__cfg).FN_A_B_S_D_A_Y_S_B_E_T_W_E_E_N(__ECAST(KEL.typ.nkdate,KEL.era.ToDate(__PP5383477.Date_Last_Seen_)),__ECAST(KEL.typ.nkdate,__CC14434));
      SELF := __PP5383477;
    END;
    SELF.Verified_First_Name_Sources_With_Dates_ := __PROJECT(__EE5382771,__ND5383481__Project(LEFT));
    __EE5382775 := __PP5382785.Verified_Last_Name_Sources_;
    __ST100125_Layout __ND5383542__Project(B_Person_6(__cfg).__ST100063_Layout __PP5383538) := TRANSFORM
      __CC14434 := KEL.Routines.MinN(FN_Compile(__cfg).FN_G_E_T_B_U_I_L_D_D_A_T_E(__ECAST(KEL.typ.nstr,__CN('header_build_version'))),__CN(__cfg.CurrentDate));
      __CC15072 := '-99997';
      SELF.Source_Date_First_Seen_ := IF(__T(__FN1(KEL.Routines.IsValidDate,KEL.era.ToDate(__PP5383538.Date_First_Seen_))),__ECAST(KEL.typ.nstr,__FN2(KEL.Routines.DateToString,KEL.Routines.MinN(KEL.era.ToDate(__PP5383538.Date_First_Seen_),__CC14434),__CN('%Y%m%d'))),__ECAST(KEL.typ.nstr,__CN(__CC15072)));
      __CC66565 := '99999999';
      SELF.First_Seen_Date_ := IF(__T(__FN1(KEL.Routines.IsValidDate,KEL.era.ToDate(__PP5383538.Date_First_Seen_))),__ECAST(KEL.typ.nstr,__FN2(KEL.Routines.DateToString,KEL.Routines.MinN(KEL.era.ToDate(__PP5383538.Date_First_Seen_),__CC14434),__CN('%Y%m%d'))),__ECAST(KEL.typ.nstr,__CN(__CC66565)));
      SELF.Source_Date_Last_Seen_ := IF(__T(__FN1(KEL.Routines.IsValidDate,KEL.era.ToDate(__PP5383538.Date_Last_Seen_))),__ECAST(KEL.typ.nstr,__FN2(KEL.Routines.DateToString,KEL.Routines.MinN(KEL.era.ToDate(__PP5383538.Date_Last_Seen_),__CC14434),__CN('%Y%m%d'))),__ECAST(KEL.typ.nstr,__CN(__CC15072)));
      SELF.Age_In_Days_ := FN_Compile(__cfg).FN_A_B_S_D_A_Y_S_B_E_T_W_E_E_N(__ECAST(KEL.typ.nkdate,KEL.era.ToDate(__PP5383538.Date_Last_Seen_)),__ECAST(KEL.typ.nkdate,__CC14434));
      SELF := __PP5383538;
    END;
    SELF.Verified_Last_Name_Sources_With_Dates_ := __PROJECT(__EE5382775,__ND5383542__Project(LEFT));
    SELF := __PP5382785;
  END;
  EXPORT __ENH_Person_5 := PROJECT(__EE5382752,__ND5382789__Project(LEFT));
END;
