//HPCC Systems KEL Compiler Version 1.5.0rc1
IMPORT KEL15 AS KEL;
IMPORT B_Sele_U_C_C_9,B_U_C_C_10,B_U_C_C_11,B_U_C_C_9,CFG_Compile,E_Business_Org,E_Business_Sele,E_Business_Sele_Overflow,E_Business_Ult,E_Sele_U_C_C,E_U_C_C FROM PublicRecords_KEL;
IMPORT * FROM KEL15.Null;
EXPORT B_Sele_U_C_C_8(CFG_Compile.FDCDataset __in = CFG_Compile.FDCDefault, CFG_Compile __cfg = CFG_Compile) := MODULE
  SHARED VIRTUAL TYPEOF(B_Sele_U_C_C_9(__in,__cfg).__ENH_Sele_U_C_C_9) __ENH_Sele_U_C_C_9 := B_Sele_U_C_C_9(__in,__cfg).__ENH_Sele_U_C_C_9;
  SHARED VIRTUAL TYPEOF(B_U_C_C_9(__in,__cfg).__ENH_U_C_C_9) __ENH_U_C_C_9 := B_U_C_C_9(__in,__cfg).__ENH_U_C_C_9;
  SHARED __EE4816633 := __ENH_Sele_U_C_C_9;
  SHARED __EE4816646 := __EE4816633;
  SHARED __EE4816653 := __EE4816646(__NN(__EE4816646.Filing_));
  SHARED __EE4816644 := __ENH_U_C_C_9;
  SHARED __ST352792_Layout := RECORD
    KEL.typ.ntyp(E_Business_Sele().Typ) Legal_;
    KEL.typ.nstr T_M_S_I_D_;
    KEL.typ.ntyp(E_U_C_C().Typ) Filing_;
    KEL.typ.nint Ult_I_D_;
    KEL.typ.nint Org_I_D_;
    KEL.typ.nint Sele_I_D_;
    KEL.typ.ndataset(B_Sele_U_C_C_9(__in,__cfg).__ST254579_Layout) Sub_Filing_;
    KEL.typ.ndataset(E_Sele_U_C_C(__in,__cfg).Data_Sources_Layout) Data_Sources_;
    KEL.typ.nuid UID;
    KEL.typ.nstr T_M_S_I_D__1_;
    KEL.typ.ndataset(B_U_C_C_9(__in,__cfg).__ST254788_Layout) Sub_Filing__1_;
    KEL.typ.ndataset(E_U_C_C(__in,__cfg).Collateral_Layout) Collateral_;
    KEL.typ.ndataset(E_U_C_C(__in,__cfg).Data_Sources_Layout) Data_Sources__1_;
    KEL.typ.nstr Best_Child_R_M_S_I_D_;
    KEL.typ.ndataset(B_U_C_C_10(__in,__cfg).__ST112717_Layout) Best_U_C_C_Child_Record_;
    KEL.typ.epoch Archive___Date_ := 0;
    KEL.typ.epoch Date_First_Seen_ := 0;
    KEL.typ.epoch Date_Last_Seen_ := 0;
    KEL.typ.epoch Hybrid_Archive_Date_ := 0;
    KEL.typ.epoch Vault_Date_Last_Seen_ := 0;
    KEL.typ.int __RecordCount := 0;
  END;
  __JC4816662(B_Sele_U_C_C_9(__in,__cfg).__ST254571_Layout __EE4816653, B_U_C_C_9(__in,__cfg).__ST254784_Layout __EE4816644) := __EEQP(__EE4816653.Filing_,__EE4816644.UID);
  __ST352792_Layout __JT4816662(B_Sele_U_C_C_9(__in,__cfg).__ST254571_Layout __l, B_U_C_C_9(__in,__cfg).__ST254784_Layout __r) := TRANSFORM
    SELF.T_M_S_I_D__1_ := __r.T_M_S_I_D_;
    SELF.Sub_Filing__1_ := __r.Sub_Filing_;
    SELF.Data_Sources__1_ := __r.Data_Sources_;
    SELF := __l;
    SELF := __r;
  END;
  SHARED __EE4816737 := JOIN(__EE4816653,__EE4816644,__JC4816662(LEFT,RIGHT),__JT4816662(LEFT,RIGHT),INNER,HASH);
  SHARED __ST352955_Layout := RECORD
    KEL.typ.ntyp(E_Business_Sele().Typ) Legal_;
    KEL.typ.nstr T_M_S_I_D_;
    KEL.typ.ntyp(E_U_C_C().Typ) Filing_;
    KEL.typ.nint Ult_I_D_;
    KEL.typ.nint Org_I_D_;
    KEL.typ.nint Sele_I_D_;
    KEL.typ.ndataset(B_Sele_U_C_C_9(__in,__cfg).__ST254579_Layout) Sub_Filing_;
    KEL.typ.ndataset(E_Sele_U_C_C(__in,__cfg).Data_Sources_Layout) Data_Sources_;
    KEL.typ.nuid UID;
    KEL.typ.nstr T_M_S_I_D__1_;
    KEL.typ.ndataset(B_U_C_C_9(__in,__cfg).__ST254788_Layout) Sub_Filing__1_;
    KEL.typ.ndataset(E_U_C_C(__in,__cfg).Collateral_Layout) Collateral_;
    KEL.typ.ndataset(E_U_C_C(__in,__cfg).Data_Sources_Layout) Data_Sources__1_;
    KEL.typ.nstr Best_Child_R_M_S_I_D_;
    KEL.typ.ndataset(B_U_C_C_10(__in,__cfg).__ST112717_Layout) Best_U_C_C_Child_Record_;
    KEL.typ.nstr R_M_S_I_D_;
    KEL.typ.nstr Party_Type_;
    KEL.typ.int Party_Sort_List_ := 0;
    KEL.typ.epoch Archive___Date_ := 0;
    KEL.typ.epoch Date_First_Seen_ := 0;
    KEL.typ.epoch Date_Last_Seen_ := 0;
    KEL.typ.epoch Hybrid_Archive_Date_ := 0;
    KEL.typ.epoch Vault_Date_Last_Seen_ := 0;
    KEL.typ.int __RecordCount := 0;
  END;
  __JC4816754(__ST352792_Layout __EE4816737, B_Sele_U_C_C_9(__in,__cfg).__ST254579_Layout __EE4816740) := __T(__OP2(__EE4816740.R_M_S_I_D_,=,__EE4816737.Best_Child_R_M_S_I_D_));
  __ST352955_Layout __JT4816754(__ST352792_Layout __l, B_Sele_U_C_C_9(__in,__cfg).__ST254579_Layout __r) := TRANSFORM, SKIP(NOT(__JC4816754(__l,__r)))
    SELF.Archive___Date_ := __r.Archive___Date_;
    SELF.Date_First_Seen_ := __r.Date_First_Seen_;
    SELF.Date_Last_Seen_ := __r.Date_Last_Seen_;
    SELF.Hybrid_Archive_Date_ := __r.Hybrid_Archive_Date_;
    SELF.Vault_Date_Last_Seen_ := __r.Vault_Date_Last_Seen_;
    SELF.__RecordCount := __r.__RecordCount;
    SELF := __l;
    SELF := __r;
  END;
  SHARED __EE4816826 := NORMALIZE(__EE4816737,__T(LEFT.Sub_Filing_),__JT4816754(LEFT,RIGHT));
  SHARED __ST352571_Layout := RECORD
    KEL.typ.ntyp(E_U_C_C().Typ) ____grp___Filing_;
    KEL.typ.nstr ____grp___T_M_S_I_D_;
    KEL.typ.ntyp(E_Business_Sele().Typ) ____grp___Legal_;
    KEL.typ.ndataset(B_Sele_U_C_C_9(__in,__cfg).__ST254579_Layout) ____grp___Sub_Filing_;
    KEL.typ.nint ____grp___Org_I_D_;
    KEL.typ.nint ____grp___Sele_I_D_;
    KEL.typ.ndataset(E_Sele_U_C_C(__in,__cfg).Data_Sources_Layout) ____grp___Data_Sources_;
    KEL.typ.nint ____grp___Ult_I_D_;
    KEL.typ.nstr R_M_S_I_D_;
    KEL.typ.nstr Party_Type_;
    KEL.typ.int Party_Sort_List_ := 0;
    KEL.typ.epoch Archive___Date_ := 0;
    KEL.typ.epoch Date_First_Seen_ := 0;
    KEL.typ.epoch Date_Last_Seen_ := 0;
    KEL.typ.epoch Hybrid_Archive_Date_ := 0;
    KEL.typ.epoch Vault_Date_Last_Seen_ := 0;
    KEL.typ.int __RecordCount := 0;
  END;
  SHARED __ST352571_Layout __ND4816831__Project(__ST352955_Layout __PP4816827) := TRANSFORM
    SELF.____grp___Filing_ := __PP4816827.Filing_;
    SELF.____grp___T_M_S_I_D_ := __PP4816827.T_M_S_I_D_;
    SELF.____grp___Legal_ := __PP4816827.Legal_;
    SELF.____grp___Sub_Filing_ := __PP4816827.Sub_Filing_;
    SELF.____grp___Org_I_D_ := __PP4816827.Org_I_D_;
    SELF.____grp___Sele_I_D_ := __PP4816827.Sele_I_D_;
    SELF.____grp___Data_Sources_ := __PP4816827.Data_Sources_;
    SELF.____grp___Ult_I_D_ := __PP4816827.Ult_I_D_;
    SELF := __PP4816827;
  END;
  SHARED __EE4816888 := PROJECT(__EE4816826,__ND4816831__Project(LEFT));
  SHARED __EE4816913 := GROUP(KEL.Routines.SortChildren(__EE4816888,'____grp___Sub_Filing_,____grp___Data_Sources_'),____grp___Filing_,____grp___T_M_S_I_D_,____grp___Legal_,____grp___Sub_Filing_,____grp___Org_I_D_,____grp___Sele_I_D_,____grp___Data_Sources_,____grp___Ult_I_D_,ALL);
  SHARED __EE4816917 := UNGROUP(TOPN(__EE4816913,1,__EE4816913.Party_Sort_List_,__T(____grp___Legal_),__T(____grp___T_M_S_I_D_),__T(____grp___Filing_),__T(____grp___Ult_I_D_),__T(____grp___Org_I_D_),__T(____grp___Sele_I_D_),__T(Party_Type_)));
  SHARED __ST353338_Layout := RECORD
    KEL.typ.ntyp(E_Business_Sele().Typ) Legal_;
    KEL.typ.nstr T_M_S_I_D_;
    KEL.typ.ntyp(E_U_C_C().Typ) Filing_;
    KEL.typ.nint Ult_I_D_;
    KEL.typ.nint Org_I_D_;
    KEL.typ.nint Sele_I_D_;
    KEL.typ.ndataset(B_Sele_U_C_C_9(__in,__cfg).__ST254579_Layout) Sub_Filing_;
    KEL.typ.ndataset(E_Sele_U_C_C(__in,__cfg).Data_Sources_Layout) Data_Sources_;
    KEL.typ.ndataset(__ST352571_Layout) Exp1_;
    KEL.typ.epoch Archive___Date_ := 0;
    KEL.typ.epoch Date_First_Seen_ := 0;
    KEL.typ.epoch Date_Last_Seen_ := 0;
    KEL.typ.epoch Hybrid_Archive_Date_ := 0;
    KEL.typ.epoch Vault_Date_Last_Seen_ := 0;
    KEL.typ.int __RecordCount := 0;
  END;
  __JC4816968(B_Sele_U_C_C_9(__in,__cfg).__ST254571_Layout __EE4816633, __ST352571_Layout __EE4816917) := __EEQP(__EE4816633.Ult_I_D_,__EE4816917.____grp___Ult_I_D_) AND __EEQP(__EE4816633.T_M_S_I_D_,__EE4816917.____grp___T_M_S_I_D_) AND __EEQP(__EE4816633.Sub_Filing_,__EE4816917.____grp___Sub_Filing_) AND __EEQP(__EE4816633.Sele_I_D_,__EE4816917.____grp___Sele_I_D_) AND __EEQP(__EE4816633.Org_I_D_,__EE4816917.____grp___Org_I_D_) AND __EEQP(__EE4816633.Legal_,__EE4816917.____grp___Legal_) AND __EEQP(__EE4816633.Filing_,__EE4816917.____grp___Filing_) AND __EEQP(__EE4816633.Data_Sources_,__EE4816917.____grp___Data_Sources_);
  __ST353338_Layout __Join__ST353338_Layout(B_Sele_U_C_C_9(__in,__cfg).__ST254571_Layout __r, DATASET(__ST352571_Layout) __recs) := TRANSFORM
    SELF := __r;
    SELF.Exp1_ := __CN(__recs);
  END;
  SHARED __EE4817003 := DENORMALIZE(DISTRIBUTE(__EE4816633,HASH(Legal_)),DISTRIBUTE(__EE4816917,HASH(____grp___Legal_)),__JC4816968(LEFT,RIGHT),GROUP,__Join__ST353338_Layout(LEFT,ROWS(RIGHT)),LOCAL);
  EXPORT __ST252708_Layout := RECORD
    KEL.typ.nstr R_M_S_I_D_;
    KEL.typ.nstr Party_Type_;
    KEL.typ.int Party_Sort_List_ := 0;
    KEL.typ.epoch Archive___Date_ := 0;
    KEL.typ.epoch Date_First_Seen_ := 0;
    KEL.typ.epoch Date_Last_Seen_ := 0;
    KEL.typ.epoch Hybrid_Archive_Date_ := 0;
    KEL.typ.epoch Vault_Date_Last_Seen_ := 0;
    KEL.typ.int __RecordCount := 0;
  END;
  SHARED __ST252700_Layout := RECORD
    KEL.typ.ntyp(E_Business_Sele().Typ) Legal_;
    KEL.typ.nstr T_M_S_I_D_;
    KEL.typ.ntyp(E_U_C_C().Typ) Filing_;
    KEL.typ.nint Ult_I_D_;
    KEL.typ.nint Org_I_D_;
    KEL.typ.nint Sele_I_D_;
    KEL.typ.ndataset(__ST252708_Layout) Sub_Filing_;
    KEL.typ.ndataset(E_Sele_U_C_C(__in,__cfg).Data_Sources_Layout) Data_Sources_;
    KEL.typ.ndataset(__ST352571_Layout) Best_Party_Types_;
    KEL.typ.epoch Archive___Date_ := 0;
    KEL.typ.epoch Date_First_Seen_ := 0;
    KEL.typ.epoch Date_Last_Seen_ := 0;
    KEL.typ.epoch Hybrid_Archive_Date_ := 0;
    KEL.typ.epoch Vault_Date_Last_Seen_ := 0;
    KEL.typ.int __RecordCount := 0;
  END;
  SHARED __ST252700_Layout __ND4817014__Project(__ST353338_Layout __PP4817010) := TRANSFORM
    __EE4817006 := __PP4817010.Sub_Filing_;
    SELF.Sub_Filing_ := __BN(PROJECT(__T(__EE4817006),__ST252708_Layout),__NL(__EE4817006));
    __EE4817009 := __PP4817010.Exp1_;
    SELF.Best_Party_Types_ := __EE4817009;
    SELF := __PP4817010;
  END;
  SHARED __EE4817105 := PROJECT(__EE4817003,__ND4817014__Project(LEFT));
  EXPORT __ST352493_Layout := RECORD
    KEL.typ.ntyp(E_Business_Sele().Typ) Legal_;
    KEL.typ.nstr T_M_S_I_D_;
    KEL.typ.ntyp(E_U_C_C().Typ) Filing_;
    KEL.typ.nint Ult_I_D_;
    KEL.typ.nint Org_I_D_;
    KEL.typ.nint Sele_I_D_;
    KEL.typ.ndataset(__ST252708_Layout) Sub_Filing_;
    KEL.typ.ndataset(E_Sele_U_C_C(__in,__cfg).Data_Sources_Layout) Data_Sources_;
    KEL.typ.ndataset(B_Sele_U_C_C_9(__in,__cfg).__ST254579_Layout) Best_Party_Types_;
    KEL.typ.epoch Archive___Date_ := 0;
    KEL.typ.epoch Date_First_Seen_ := 0;
    KEL.typ.epoch Date_Last_Seen_ := 0;
    KEL.typ.epoch Hybrid_Archive_Date_ := 0;
    KEL.typ.epoch Vault_Date_Last_Seen_ := 0;
    KEL.typ.int __RecordCount := 0;
  END;
  SHARED __ST352493_Layout __ND4816565__Project(__ST252700_Layout __PP4816561) := TRANSFORM
    __EE4817108 := __PP4816561.Best_Party_Types_;
    SELF.Best_Party_Types_ := __PROJECT(__EE4817108,B_Sele_U_C_C_9(__in,__cfg).__ST254579_Layout);
    SELF := __PP4816561;
  END;
  EXPORT __ENH_Sele_U_C_C_8 := PROJECT(__EE4817105,__ND4816565__Project(LEFT));
END;
