//HPCC Systems KEL Compiler Version 0.11.6
IMPORT KEL011 AS KEL;
IMPORT CFG_Compile,E_Person FROM PublicRecords_KEL;
IMPORT * FROM KEL011.Null;
EXPORT E_Input_P_I_I(CFG_Compile.FDCDataset __in = CFG_Compile.FDCDefault, CFG_Compile __cfg = CFG_Compile) := MODULE
  EXPORT Typ := KEL.typ.uid;
  EXPORT InLayout := RECORD
    KEL.typ.nuid UID;
    KEL.typ.ntyp(E_Person().Typ) Subject_;
    KEL.typ.nstr Input_Account_Echo_;
    KEL.typ.nint Input_Lex_I_D_Echo_;
    KEL.typ.nstr Input_First_Name_Echo_;
    KEL.typ.nstr Input_Middle_Name_Echo_;
    KEL.typ.nstr Input_Last_Name_Echo_;
    KEL.typ.nstr Input_Address_Echo_;
    KEL.typ.nstr Input_City_Echo_;
    KEL.typ.nstr Input_State_Echo_;
    KEL.typ.nstr Input_Zip_Echo_;
    KEL.typ.nstr Input_Home_Phone_Echo_;
    KEL.typ.nstr Input_S_S_N_Echo_;
    KEL.typ.nstr Input_D_O_B_Echo_;
    KEL.typ.nstr Input_Work_Phone_Echo_;
    KEL.typ.nstr Input_Income_Echo_;
    KEL.typ.nstr Input_D_L_Number_Echo_;
    KEL.typ.nstr Input_D_L_State_Echo_;
    KEL.typ.nstr Input_Balance_Echo_;
    KEL.typ.nstr Input_Charge_Offd_Echo_;
    KEL.typ.nstr Input_Former_Name_Echo_;
    KEL.typ.nstr Input_Email_Echo_;
    KEL.typ.nstr Input_Employment_Echo_;
    KEL.typ.nstr Input_Archive_Date_Echo_;
    KEL.typ.nint Appended_Lex_I_D_;
    KEL.typ.nint Appended_Lex_I_D_Score_;
    KEL.typ.nstr Input_Prefix_Clean_;
    KEL.typ.nstr Input_First_Name_Clean_;
    KEL.typ.nstr Input_Middle_Name_Clean_;
    KEL.typ.nstr Input_Last_Name_Clean_;
    KEL.typ.nstr Input_Suffix_Clean_;
    KEL.typ.nstr Input_Primary_Range_Clean_;
    KEL.typ.nstr Input_Pre_Direction_Clean_;
    KEL.typ.nstr Input_Primary_Name_Clean_;
    KEL.typ.nstr Input_Address_Suffix_Clean_;
    KEL.typ.nstr Input_Post_Direction_Clean_;
    KEL.typ.nstr Input_Unit_Desig_Clean_;
    KEL.typ.nstr Input_Secondary_Range_Clean_;
    KEL.typ.nstr Input_City_Name_Clean_;
    KEL.typ.nstr Input_State_Clean_;
    KEL.typ.nstr Input_Zip5_Clean_;
    KEL.typ.nstr Input_Zip4_Clean_;
    KEL.typ.nstr Input_Latitude_Clean_;
    KEL.typ.nstr Input_Longitude_Clean_;
    KEL.typ.nstr Input_County_Clean_;
    KEL.typ.nstr Input_Geoblock_Clean_;
    KEL.typ.nstr Input_Address_Type_Clean_;
    KEL.typ.nstr Input_Address_Status_Clean_;
    KEL.typ.nstr Input_E_Mail_Clean_;
    KEL.typ.nstr Input_Home_Phone_Clean_;
    KEL.typ.nstr Input_Work_Phone_Clean_;
    KEL.typ.nstr Input_D_L_Number_Clean_;
    KEL.typ.nstr Input_D_L_State_Clean_;
    KEL.typ.nkdate Input_D_O_B_Clean_;
    KEL.typ.nstr Input_S_S_N_Clean_;
    KEL.typ.nstr Input_Archive_Date_Clean_;
    KEL.typ.nint Rep_Number_;
    KEL.typ.epoch Date_First_Seen_ := 0;
    KEL.typ.epoch Date_Last_Seen_ := 0;
    UNSIGNED1 __Permits;
  END;
  SHARED VIRTUAL __SourceFilter(DATASET(InLayout) __ds) := __ds;
  SHARED VIRTUAL __GroupedFilter(GROUPED DATASET(InLayout) __ds) := __ds;
  SHARED __Mapping := 'inputuidappend(UID),subject(Subject_:0),inputaccountecho(Input_Account_Echo_:\'\'),inputlexidecho(Input_Lex_I_D_Echo_:0),inputfirstnameecho(Input_First_Name_Echo_:\'\'),inputmiddlenameecho(Input_Middle_Name_Echo_:\'\'),inputlastnameecho(Input_Last_Name_Echo_:\'\'),inputaddressecho(Input_Address_Echo_:\'\'),inputcityecho(Input_City_Echo_:\'\'),inputstateecho(Input_State_Echo_:\'\'),inputzipecho(Input_Zip_Echo_:\'\'),inputhomephoneecho(Input_Home_Phone_Echo_:\'\'),inputssnecho(Input_S_S_N_Echo_:\'\'),inputdobecho(Input_D_O_B_Echo_:\'\'),inputworkphoneecho(Input_Work_Phone_Echo_:\'\'),inputincomeecho(Input_Income_Echo_:\'\'),inputdlnumberecho(Input_D_L_Number_Echo_:\'\'),inputdlstateecho(Input_D_L_State_Echo_:\'\'),inputbalanceecho(Input_Balance_Echo_:\'\'),inputchargeoffdecho(Input_Charge_Offd_Echo_:\'\'),inputformernameecho(Input_Former_Name_Echo_:\'\'),inputemailecho(Input_Email_Echo_:\'\'),inputemploymentecho(Input_Employment_Echo_:\'\'),inputarchivedateecho(Input_Archive_Date_Echo_:\'\'),appendedlexid(Appended_Lex_I_D_:0),appendedlexidscore(Appended_Lex_I_D_Score_:0),inputprefixclean(Input_Prefix_Clean_:\'\'),inputfirstnameclean(Input_First_Name_Clean_:\'\'),inputmiddlenameclean(Input_Middle_Name_Clean_:\'\'),inputlastnameclean(Input_Last_Name_Clean_:\'\'),inputsuffixclean(Input_Suffix_Clean_:\'\'),inputprimaryrangeclean(Input_Primary_Range_Clean_:\'\'),inputpredirectionclean(Input_Pre_Direction_Clean_:\'\'),inputprimarynameclean(Input_Primary_Name_Clean_:\'\'),inputaddresssuffixclean(Input_Address_Suffix_Clean_:\'\'),inputpostdirectionclean(Input_Post_Direction_Clean_:\'\'),inputunitdesigclean(Input_Unit_Desig_Clean_:\'\'),inputsecondaryrangeclean(Input_Secondary_Range_Clean_:\'\'),inputcitynameclean(Input_City_Name_Clean_:\'\'),inputstateclean(Input_State_Clean_:\'\'),inputzip5clean(Input_Zip5_Clean_:\'\'),inputzip4clean(Input_Zip4_Clean_:\'\'),inputlatitudeclean(Input_Latitude_Clean_:\'\'),inputlongitudeclean(Input_Longitude_Clean_:\'\'),inputcountyclean(Input_County_Clean_:\'\'),inputgeoblockclean(Input_Geoblock_Clean_:\'\'),inputaddresstypeclean(Input_Address_Type_Clean_:\'\'),inputaddressstatusclean(Input_Address_Status_Clean_:\'\'),inputemailclean(Input_E_Mail_Clean_:\'\'),inputhomephoneclean(Input_Home_Phone_Clean_:\'\'),inputworkphoneclean(Input_Work_Phone_Clean_:\'\'),inputdlnumberclean(Input_D_L_Number_Clean_:\'\'),inputdlstateclean(Input_D_L_State_Clean_:\'\'),inputdobclean(Input_D_O_B_Clean_:DATE),inputssnclean(Input_S_S_N_Clean_:\'\'),inputarchivedateclean(Input_Archive_Date_Clean_:\'\'),repnumber(Rep_Number_:0),datefirstseen(Date_First_Seen_:EPOCH),datelastseen(Date_Last_Seen_:EPOCH)';
  EXPORT VIRTUAL DATASET(InLayout) InData := DATASET([],InLayout);
  EXPORT Layout := RECORD
    KEL.typ.nuid UID;
    KEL.typ.ntyp(E_Person().Typ) Subject_;
    KEL.typ.nstr Input_Account_Echo_;
    KEL.typ.nint Input_Lex_I_D_Echo_;
    KEL.typ.nstr Input_First_Name_Echo_;
    KEL.typ.nstr Input_Middle_Name_Echo_;
    KEL.typ.nstr Input_Last_Name_Echo_;
    KEL.typ.nstr Input_Address_Echo_;
    KEL.typ.nstr Input_City_Echo_;
    KEL.typ.nstr Input_State_Echo_;
    KEL.typ.nstr Input_Zip_Echo_;
    KEL.typ.nstr Input_Home_Phone_Echo_;
    KEL.typ.nstr Input_S_S_N_Echo_;
    KEL.typ.nstr Input_D_O_B_Echo_;
    KEL.typ.nstr Input_Work_Phone_Echo_;
    KEL.typ.nstr Input_Income_Echo_;
    KEL.typ.nstr Input_D_L_Number_Echo_;
    KEL.typ.nstr Input_D_L_State_Echo_;
    KEL.typ.nstr Input_Balance_Echo_;
    KEL.typ.nstr Input_Charge_Offd_Echo_;
    KEL.typ.nstr Input_Former_Name_Echo_;
    KEL.typ.nstr Input_Email_Echo_;
    KEL.typ.nstr Input_Employment_Echo_;
    KEL.typ.nstr Input_Archive_Date_Echo_;
    KEL.typ.nint Appended_Lex_I_D_;
    KEL.typ.nint Appended_Lex_I_D_Score_;
    KEL.typ.nstr Input_Prefix_Clean_;
    KEL.typ.nstr Input_First_Name_Clean_;
    KEL.typ.nstr Input_Middle_Name_Clean_;
    KEL.typ.nstr Input_Last_Name_Clean_;
    KEL.typ.nstr Input_Suffix_Clean_;
    KEL.typ.nstr Input_Primary_Range_Clean_;
    KEL.typ.nstr Input_Pre_Direction_Clean_;
    KEL.typ.nstr Input_Primary_Name_Clean_;
    KEL.typ.nstr Input_Address_Suffix_Clean_;
    KEL.typ.nstr Input_Post_Direction_Clean_;
    KEL.typ.nstr Input_Unit_Desig_Clean_;
    KEL.typ.nstr Input_Secondary_Range_Clean_;
    KEL.typ.nstr Input_City_Name_Clean_;
    KEL.typ.nstr Input_State_Clean_;
    KEL.typ.nstr Input_Zip5_Clean_;
    KEL.typ.nstr Input_Zip4_Clean_;
    KEL.typ.nstr Input_Latitude_Clean_;
    KEL.typ.nstr Input_Longitude_Clean_;
    KEL.typ.nstr Input_County_Clean_;
    KEL.typ.nstr Input_Geoblock_Clean_;
    KEL.typ.nstr Input_Address_Type_Clean_;
    KEL.typ.nstr Input_Address_Status_Clean_;
    KEL.typ.nstr Input_E_Mail_Clean_;
    KEL.typ.nstr Input_Home_Phone_Clean_;
    KEL.typ.nstr Input_Work_Phone_Clean_;
    KEL.typ.nstr Input_D_L_Number_Clean_;
    KEL.typ.nstr Input_D_L_State_Clean_;
    KEL.typ.nkdate Input_D_O_B_Clean_;
    KEL.typ.nstr Input_S_S_N_Clean_;
    KEL.typ.nstr Input_Archive_Date_Clean_;
    KEL.typ.nint Rep_Number_;
    KEL.typ.epoch Date_First_Seen_ := 0;
    KEL.typ.epoch Date_Last_Seen_ := 0;
    KEL.typ.int __RecordCount := 0;
  END;
  EXPORT __PostFilter := __GroupedFilter(GROUP(DISTRIBUTE(InData,HASH(UID)),UID,LOCAL,ALL));
  Input_P_I_I_Group := __PostFilter;
  Layout Input_P_I_I__Rollup(InLayout __r, DATASET(InLayout) __recs) := TRANSFORM
    SELF.Subject_ := KEL.Intake.SingleValue(__recs,Subject_);
    SELF.Input_Account_Echo_ := KEL.Intake.SingleValue(__recs,Input_Account_Echo_);
    SELF.Input_Lex_I_D_Echo_ := KEL.Intake.SingleValue(__recs,Input_Lex_I_D_Echo_);
    SELF.Input_First_Name_Echo_ := KEL.Intake.SingleValue(__recs,Input_First_Name_Echo_);
    SELF.Input_Middle_Name_Echo_ := KEL.Intake.SingleValue(__recs,Input_Middle_Name_Echo_);
    SELF.Input_Last_Name_Echo_ := KEL.Intake.SingleValue(__recs,Input_Last_Name_Echo_);
    SELF.Input_Address_Echo_ := KEL.Intake.SingleValue(__recs,Input_Address_Echo_);
    SELF.Input_City_Echo_ := KEL.Intake.SingleValue(__recs,Input_City_Echo_);
    SELF.Input_State_Echo_ := KEL.Intake.SingleValue(__recs,Input_State_Echo_);
    SELF.Input_Zip_Echo_ := KEL.Intake.SingleValue(__recs,Input_Zip_Echo_);
    SELF.Input_Home_Phone_Echo_ := KEL.Intake.SingleValue(__recs,Input_Home_Phone_Echo_);
    SELF.Input_S_S_N_Echo_ := KEL.Intake.SingleValue(__recs,Input_S_S_N_Echo_);
    SELF.Input_D_O_B_Echo_ := KEL.Intake.SingleValue(__recs,Input_D_O_B_Echo_);
    SELF.Input_Work_Phone_Echo_ := KEL.Intake.SingleValue(__recs,Input_Work_Phone_Echo_);
    SELF.Input_Income_Echo_ := KEL.Intake.SingleValue(__recs,Input_Income_Echo_);
    SELF.Input_D_L_Number_Echo_ := KEL.Intake.SingleValue(__recs,Input_D_L_Number_Echo_);
    SELF.Input_D_L_State_Echo_ := KEL.Intake.SingleValue(__recs,Input_D_L_State_Echo_);
    SELF.Input_Balance_Echo_ := KEL.Intake.SingleValue(__recs,Input_Balance_Echo_);
    SELF.Input_Charge_Offd_Echo_ := KEL.Intake.SingleValue(__recs,Input_Charge_Offd_Echo_);
    SELF.Input_Former_Name_Echo_ := KEL.Intake.SingleValue(__recs,Input_Former_Name_Echo_);
    SELF.Input_Email_Echo_ := KEL.Intake.SingleValue(__recs,Input_Email_Echo_);
    SELF.Input_Employment_Echo_ := KEL.Intake.SingleValue(__recs,Input_Employment_Echo_);
    SELF.Input_Archive_Date_Echo_ := KEL.Intake.SingleValue(__recs,Input_Archive_Date_Echo_);
    SELF.Appended_Lex_I_D_ := KEL.Intake.SingleValue(__recs,Appended_Lex_I_D_);
    SELF.Appended_Lex_I_D_Score_ := KEL.Intake.SingleValue(__recs,Appended_Lex_I_D_Score_);
    SELF.Input_Prefix_Clean_ := KEL.Intake.SingleValue(__recs,Input_Prefix_Clean_);
    SELF.Input_First_Name_Clean_ := KEL.Intake.SingleValue(__recs,Input_First_Name_Clean_);
    SELF.Input_Middle_Name_Clean_ := KEL.Intake.SingleValue(__recs,Input_Middle_Name_Clean_);
    SELF.Input_Last_Name_Clean_ := KEL.Intake.SingleValue(__recs,Input_Last_Name_Clean_);
    SELF.Input_Suffix_Clean_ := KEL.Intake.SingleValue(__recs,Input_Suffix_Clean_);
    SELF.Input_Primary_Range_Clean_ := KEL.Intake.SingleValue(__recs,Input_Primary_Range_Clean_);
    SELF.Input_Pre_Direction_Clean_ := KEL.Intake.SingleValue(__recs,Input_Pre_Direction_Clean_);
    SELF.Input_Primary_Name_Clean_ := KEL.Intake.SingleValue(__recs,Input_Primary_Name_Clean_);
    SELF.Input_Address_Suffix_Clean_ := KEL.Intake.SingleValue(__recs,Input_Address_Suffix_Clean_);
    SELF.Input_Post_Direction_Clean_ := KEL.Intake.SingleValue(__recs,Input_Post_Direction_Clean_);
    SELF.Input_Unit_Desig_Clean_ := KEL.Intake.SingleValue(__recs,Input_Unit_Desig_Clean_);
    SELF.Input_Secondary_Range_Clean_ := KEL.Intake.SingleValue(__recs,Input_Secondary_Range_Clean_);
    SELF.Input_City_Name_Clean_ := KEL.Intake.SingleValue(__recs,Input_City_Name_Clean_);
    SELF.Input_State_Clean_ := KEL.Intake.SingleValue(__recs,Input_State_Clean_);
    SELF.Input_Zip5_Clean_ := KEL.Intake.SingleValue(__recs,Input_Zip5_Clean_);
    SELF.Input_Zip4_Clean_ := KEL.Intake.SingleValue(__recs,Input_Zip4_Clean_);
    SELF.Input_Latitude_Clean_ := KEL.Intake.SingleValue(__recs,Input_Latitude_Clean_);
    SELF.Input_Longitude_Clean_ := KEL.Intake.SingleValue(__recs,Input_Longitude_Clean_);
    SELF.Input_County_Clean_ := KEL.Intake.SingleValue(__recs,Input_County_Clean_);
    SELF.Input_Geoblock_Clean_ := KEL.Intake.SingleValue(__recs,Input_Geoblock_Clean_);
    SELF.Input_Address_Type_Clean_ := KEL.Intake.SingleValue(__recs,Input_Address_Type_Clean_);
    SELF.Input_Address_Status_Clean_ := KEL.Intake.SingleValue(__recs,Input_Address_Status_Clean_);
    SELF.Input_E_Mail_Clean_ := KEL.Intake.SingleValue(__recs,Input_E_Mail_Clean_);
    SELF.Input_Home_Phone_Clean_ := KEL.Intake.SingleValue(__recs,Input_Home_Phone_Clean_);
    SELF.Input_Work_Phone_Clean_ := KEL.Intake.SingleValue(__recs,Input_Work_Phone_Clean_);
    SELF.Input_D_L_Number_Clean_ := KEL.Intake.SingleValue(__recs,Input_D_L_Number_Clean_);
    SELF.Input_D_L_State_Clean_ := KEL.Intake.SingleValue(__recs,Input_D_L_State_Clean_);
    SELF.Input_D_O_B_Clean_ := KEL.Intake.SingleValue(__recs,Input_D_O_B_Clean_);
    SELF.Input_S_S_N_Clean_ := KEL.Intake.SingleValue(__recs,Input_S_S_N_Clean_);
    SELF.Input_Archive_Date_Clean_ := KEL.Intake.SingleValue(__recs,Input_Archive_Date_Clean_);
    SELF.Rep_Number_ := KEL.Intake.SingleValue(__recs,Rep_Number_);
    SELF.__RecordCount := COUNT(__recs);
    SELF.Date_First_Seen_ := KEL.era.SimpleRoll(__recs,Date_First_Seen_,MIN,TRUE);
    SELF.Date_Last_Seen_ := KEL.era.SimpleRoll(__recs,Date_Last_Seen_,MAX,FALSE);
    SELF := __r;
  END;
  Layout Input_P_I_I__Single_Rollup(InLayout __r) := TRANSFORM
    SELF.__RecordCount := 1;
    SELF := __r;
  END;
  EXPORT __PreResult := ROLLUP(HAVING(Input_P_I_I_Group,COUNT(ROWS(LEFT))=1),GROUP,Input_P_I_I__Single_Rollup(LEFT)) + ROLLUP(HAVING(Input_P_I_I_Group,COUNT(ROWS(LEFT))>1),GROUP,Input_P_I_I__Rollup(LEFT, ROWS(LEFT)));
  EXPORT __Result := __CLEARFLAGS(__PreResult);
  EXPORT Result := __UNWRAP(__Result);
  EXPORT Subject__SingleValue_Invalid := KEL.Intake.DetectMultipleValues(__PreResult,Subject_);
  EXPORT Input_Account_Echo__SingleValue_Invalid := KEL.Intake.DetectMultipleValues(__PreResult,Input_Account_Echo_);
  EXPORT Input_Lex_I_D_Echo__SingleValue_Invalid := KEL.Intake.DetectMultipleValues(__PreResult,Input_Lex_I_D_Echo_);
  EXPORT Input_First_Name_Echo__SingleValue_Invalid := KEL.Intake.DetectMultipleValues(__PreResult,Input_First_Name_Echo_);
  EXPORT Input_Middle_Name_Echo__SingleValue_Invalid := KEL.Intake.DetectMultipleValues(__PreResult,Input_Middle_Name_Echo_);
  EXPORT Input_Last_Name_Echo__SingleValue_Invalid := KEL.Intake.DetectMultipleValues(__PreResult,Input_Last_Name_Echo_);
  EXPORT Input_Address_Echo__SingleValue_Invalid := KEL.Intake.DetectMultipleValues(__PreResult,Input_Address_Echo_);
  EXPORT Input_City_Echo__SingleValue_Invalid := KEL.Intake.DetectMultipleValues(__PreResult,Input_City_Echo_);
  EXPORT Input_State_Echo__SingleValue_Invalid := KEL.Intake.DetectMultipleValues(__PreResult,Input_State_Echo_);
  EXPORT Input_Zip_Echo__SingleValue_Invalid := KEL.Intake.DetectMultipleValues(__PreResult,Input_Zip_Echo_);
  EXPORT Input_Home_Phone_Echo__SingleValue_Invalid := KEL.Intake.DetectMultipleValues(__PreResult,Input_Home_Phone_Echo_);
  EXPORT Input_S_S_N_Echo__SingleValue_Invalid := KEL.Intake.DetectMultipleValues(__PreResult,Input_S_S_N_Echo_);
  EXPORT Input_D_O_B_Echo__SingleValue_Invalid := KEL.Intake.DetectMultipleValues(__PreResult,Input_D_O_B_Echo_);
  EXPORT Input_Work_Phone_Echo__SingleValue_Invalid := KEL.Intake.DetectMultipleValues(__PreResult,Input_Work_Phone_Echo_);
  EXPORT Input_Income_Echo__SingleValue_Invalid := KEL.Intake.DetectMultipleValues(__PreResult,Input_Income_Echo_);
  EXPORT Input_D_L_Number_Echo__SingleValue_Invalid := KEL.Intake.DetectMultipleValues(__PreResult,Input_D_L_Number_Echo_);
  EXPORT Input_D_L_State_Echo__SingleValue_Invalid := KEL.Intake.DetectMultipleValues(__PreResult,Input_D_L_State_Echo_);
  EXPORT Input_Balance_Echo__SingleValue_Invalid := KEL.Intake.DetectMultipleValues(__PreResult,Input_Balance_Echo_);
  EXPORT Input_Charge_Offd_Echo__SingleValue_Invalid := KEL.Intake.DetectMultipleValues(__PreResult,Input_Charge_Offd_Echo_);
  EXPORT Input_Former_Name_Echo__SingleValue_Invalid := KEL.Intake.DetectMultipleValues(__PreResult,Input_Former_Name_Echo_);
  EXPORT Input_Email_Echo__SingleValue_Invalid := KEL.Intake.DetectMultipleValues(__PreResult,Input_Email_Echo_);
  EXPORT Input_Employment_Echo__SingleValue_Invalid := KEL.Intake.DetectMultipleValues(__PreResult,Input_Employment_Echo_);
  EXPORT Input_Archive_Date_Echo__SingleValue_Invalid := KEL.Intake.DetectMultipleValues(__PreResult,Input_Archive_Date_Echo_);
  EXPORT Appended_Lex_I_D__SingleValue_Invalid := KEL.Intake.DetectMultipleValues(__PreResult,Appended_Lex_I_D_);
  EXPORT Appended_Lex_I_D_Score__SingleValue_Invalid := KEL.Intake.DetectMultipleValues(__PreResult,Appended_Lex_I_D_Score_);
  EXPORT Input_Prefix_Clean__SingleValue_Invalid := KEL.Intake.DetectMultipleValues(__PreResult,Input_Prefix_Clean_);
  EXPORT Input_First_Name_Clean__SingleValue_Invalid := KEL.Intake.DetectMultipleValues(__PreResult,Input_First_Name_Clean_);
  EXPORT Input_Middle_Name_Clean__SingleValue_Invalid := KEL.Intake.DetectMultipleValues(__PreResult,Input_Middle_Name_Clean_);
  EXPORT Input_Last_Name_Clean__SingleValue_Invalid := KEL.Intake.DetectMultipleValues(__PreResult,Input_Last_Name_Clean_);
  EXPORT Input_Suffix_Clean__SingleValue_Invalid := KEL.Intake.DetectMultipleValues(__PreResult,Input_Suffix_Clean_);
  EXPORT Input_Primary_Range_Clean__SingleValue_Invalid := KEL.Intake.DetectMultipleValues(__PreResult,Input_Primary_Range_Clean_);
  EXPORT Input_Pre_Direction_Clean__SingleValue_Invalid := KEL.Intake.DetectMultipleValues(__PreResult,Input_Pre_Direction_Clean_);
  EXPORT Input_Primary_Name_Clean__SingleValue_Invalid := KEL.Intake.DetectMultipleValues(__PreResult,Input_Primary_Name_Clean_);
  EXPORT Input_Address_Suffix_Clean__SingleValue_Invalid := KEL.Intake.DetectMultipleValues(__PreResult,Input_Address_Suffix_Clean_);
  EXPORT Input_Post_Direction_Clean__SingleValue_Invalid := KEL.Intake.DetectMultipleValues(__PreResult,Input_Post_Direction_Clean_);
  EXPORT Input_Unit_Desig_Clean__SingleValue_Invalid := KEL.Intake.DetectMultipleValues(__PreResult,Input_Unit_Desig_Clean_);
  EXPORT Input_Secondary_Range_Clean__SingleValue_Invalid := KEL.Intake.DetectMultipleValues(__PreResult,Input_Secondary_Range_Clean_);
  EXPORT Input_City_Name_Clean__SingleValue_Invalid := KEL.Intake.DetectMultipleValues(__PreResult,Input_City_Name_Clean_);
  EXPORT Input_State_Clean__SingleValue_Invalid := KEL.Intake.DetectMultipleValues(__PreResult,Input_State_Clean_);
  EXPORT Input_Zip5_Clean__SingleValue_Invalid := KEL.Intake.DetectMultipleValues(__PreResult,Input_Zip5_Clean_);
  EXPORT Input_Zip4_Clean__SingleValue_Invalid := KEL.Intake.DetectMultipleValues(__PreResult,Input_Zip4_Clean_);
  EXPORT Input_Latitude_Clean__SingleValue_Invalid := KEL.Intake.DetectMultipleValues(__PreResult,Input_Latitude_Clean_);
  EXPORT Input_Longitude_Clean__SingleValue_Invalid := KEL.Intake.DetectMultipleValues(__PreResult,Input_Longitude_Clean_);
  EXPORT Input_County_Clean__SingleValue_Invalid := KEL.Intake.DetectMultipleValues(__PreResult,Input_County_Clean_);
  EXPORT Input_Geoblock_Clean__SingleValue_Invalid := KEL.Intake.DetectMultipleValues(__PreResult,Input_Geoblock_Clean_);
  EXPORT Input_Address_Type_Clean__SingleValue_Invalid := KEL.Intake.DetectMultipleValues(__PreResult,Input_Address_Type_Clean_);
  EXPORT Input_Address_Status_Clean__SingleValue_Invalid := KEL.Intake.DetectMultipleValues(__PreResult,Input_Address_Status_Clean_);
  EXPORT Input_E_Mail_Clean__SingleValue_Invalid := KEL.Intake.DetectMultipleValues(__PreResult,Input_E_Mail_Clean_);
  EXPORT Input_Home_Phone_Clean__SingleValue_Invalid := KEL.Intake.DetectMultipleValues(__PreResult,Input_Home_Phone_Clean_);
  EXPORT Input_Work_Phone_Clean__SingleValue_Invalid := KEL.Intake.DetectMultipleValues(__PreResult,Input_Work_Phone_Clean_);
  EXPORT Input_D_L_Number_Clean__SingleValue_Invalid := KEL.Intake.DetectMultipleValues(__PreResult,Input_D_L_Number_Clean_);
  EXPORT Input_D_L_State_Clean__SingleValue_Invalid := KEL.Intake.DetectMultipleValues(__PreResult,Input_D_L_State_Clean_);
  EXPORT Input_D_O_B_Clean__SingleValue_Invalid := KEL.Intake.DetectMultipleValues(__PreResult,Input_D_O_B_Clean_);
  EXPORT Input_S_S_N_Clean__SingleValue_Invalid := KEL.Intake.DetectMultipleValues(__PreResult,Input_S_S_N_Clean_);
  EXPORT Input_Archive_Date_Clean__SingleValue_Invalid := KEL.Intake.DetectMultipleValues(__PreResult,Input_Archive_Date_Clean_);
  EXPORT Rep_Number__SingleValue_Invalid := KEL.Intake.DetectMultipleValues(__PreResult,Rep_Number_);
  EXPORT Subject__Orphan := JOIN(InData(__NN(Subject_)),E_Person(__in,__cfg).__Result,__EEQP(LEFT.Subject_, RIGHT.UID),TRANSFORM(InLayout,SELF := LEFT,SELF:=[]),LEFT ONLY, HASH);
  EXPORT SanityCheck := DATASET([{COUNT(Subject__Orphan),COUNT(Subject__SingleValue_Invalid),COUNT(Input_Account_Echo__SingleValue_Invalid),COUNT(Input_Lex_I_D_Echo__SingleValue_Invalid),COUNT(Input_First_Name_Echo__SingleValue_Invalid),COUNT(Input_Middle_Name_Echo__SingleValue_Invalid),COUNT(Input_Last_Name_Echo__SingleValue_Invalid),COUNT(Input_Address_Echo__SingleValue_Invalid),COUNT(Input_City_Echo__SingleValue_Invalid),COUNT(Input_State_Echo__SingleValue_Invalid),COUNT(Input_Zip_Echo__SingleValue_Invalid),COUNT(Input_Home_Phone_Echo__SingleValue_Invalid),COUNT(Input_S_S_N_Echo__SingleValue_Invalid),COUNT(Input_D_O_B_Echo__SingleValue_Invalid),COUNT(Input_Work_Phone_Echo__SingleValue_Invalid),COUNT(Input_Income_Echo__SingleValue_Invalid),COUNT(Input_D_L_Number_Echo__SingleValue_Invalid),COUNT(Input_D_L_State_Echo__SingleValue_Invalid),COUNT(Input_Balance_Echo__SingleValue_Invalid),COUNT(Input_Charge_Offd_Echo__SingleValue_Invalid),COUNT(Input_Former_Name_Echo__SingleValue_Invalid),COUNT(Input_Email_Echo__SingleValue_Invalid),COUNT(Input_Employment_Echo__SingleValue_Invalid),COUNT(Input_Archive_Date_Echo__SingleValue_Invalid),COUNT(Appended_Lex_I_D__SingleValue_Invalid),COUNT(Appended_Lex_I_D_Score__SingleValue_Invalid),COUNT(Input_Prefix_Clean__SingleValue_Invalid),COUNT(Input_First_Name_Clean__SingleValue_Invalid),COUNT(Input_Middle_Name_Clean__SingleValue_Invalid),COUNT(Input_Last_Name_Clean__SingleValue_Invalid),COUNT(Input_Suffix_Clean__SingleValue_Invalid),COUNT(Input_Primary_Range_Clean__SingleValue_Invalid),COUNT(Input_Pre_Direction_Clean__SingleValue_Invalid),COUNT(Input_Primary_Name_Clean__SingleValue_Invalid),COUNT(Input_Address_Suffix_Clean__SingleValue_Invalid),COUNT(Input_Post_Direction_Clean__SingleValue_Invalid),COUNT(Input_Unit_Desig_Clean__SingleValue_Invalid),COUNT(Input_Secondary_Range_Clean__SingleValue_Invalid),COUNT(Input_City_Name_Clean__SingleValue_Invalid),COUNT(Input_State_Clean__SingleValue_Invalid),COUNT(Input_Zip5_Clean__SingleValue_Invalid),COUNT(Input_Zip4_Clean__SingleValue_Invalid),COUNT(Input_Latitude_Clean__SingleValue_Invalid),COUNT(Input_Longitude_Clean__SingleValue_Invalid),COUNT(Input_County_Clean__SingleValue_Invalid),COUNT(Input_Geoblock_Clean__SingleValue_Invalid),COUNT(Input_Address_Type_Clean__SingleValue_Invalid),COUNT(Input_Address_Status_Clean__SingleValue_Invalid),COUNT(Input_E_Mail_Clean__SingleValue_Invalid),COUNT(Input_Home_Phone_Clean__SingleValue_Invalid),COUNT(Input_Work_Phone_Clean__SingleValue_Invalid),COUNT(Input_D_L_Number_Clean__SingleValue_Invalid),COUNT(Input_D_L_State_Clean__SingleValue_Invalid),COUNT(Input_D_O_B_Clean__SingleValue_Invalid),COUNT(Input_S_S_N_Clean__SingleValue_Invalid),COUNT(Input_Archive_Date_Clean__SingleValue_Invalid),COUNT(Rep_Number__SingleValue_Invalid)}],{KEL.typ.int Subject__Orphan,KEL.typ.int Subject__SingleValue_Invalid,KEL.typ.int Input_Account_Echo__SingleValue_Invalid,KEL.typ.int Input_Lex_I_D_Echo__SingleValue_Invalid,KEL.typ.int Input_First_Name_Echo__SingleValue_Invalid,KEL.typ.int Input_Middle_Name_Echo__SingleValue_Invalid,KEL.typ.int Input_Last_Name_Echo__SingleValue_Invalid,KEL.typ.int Input_Address_Echo__SingleValue_Invalid,KEL.typ.int Input_City_Echo__SingleValue_Invalid,KEL.typ.int Input_State_Echo__SingleValue_Invalid,KEL.typ.int Input_Zip_Echo__SingleValue_Invalid,KEL.typ.int Input_Home_Phone_Echo__SingleValue_Invalid,KEL.typ.int Input_S_S_N_Echo__SingleValue_Invalid,KEL.typ.int Input_D_O_B_Echo__SingleValue_Invalid,KEL.typ.int Input_Work_Phone_Echo__SingleValue_Invalid,KEL.typ.int Input_Income_Echo__SingleValue_Invalid,KEL.typ.int Input_D_L_Number_Echo__SingleValue_Invalid,KEL.typ.int Input_D_L_State_Echo__SingleValue_Invalid,KEL.typ.int Input_Balance_Echo__SingleValue_Invalid,KEL.typ.int Input_Charge_Offd_Echo__SingleValue_Invalid,KEL.typ.int Input_Former_Name_Echo__SingleValue_Invalid,KEL.typ.int Input_Email_Echo__SingleValue_Invalid,KEL.typ.int Input_Employment_Echo__SingleValue_Invalid,KEL.typ.int Input_Archive_Date_Echo__SingleValue_Invalid,KEL.typ.int Appended_Lex_I_D__SingleValue_Invalid,KEL.typ.int Appended_Lex_I_D_Score__SingleValue_Invalid,KEL.typ.int Input_Prefix_Clean__SingleValue_Invalid,KEL.typ.int Input_First_Name_Clean__SingleValue_Invalid,KEL.typ.int Input_Middle_Name_Clean__SingleValue_Invalid,KEL.typ.int Input_Last_Name_Clean__SingleValue_Invalid,KEL.typ.int Input_Suffix_Clean__SingleValue_Invalid,KEL.typ.int Input_Primary_Range_Clean__SingleValue_Invalid,KEL.typ.int Input_Pre_Direction_Clean__SingleValue_Invalid,KEL.typ.int Input_Primary_Name_Clean__SingleValue_Invalid,KEL.typ.int Input_Address_Suffix_Clean__SingleValue_Invalid,KEL.typ.int Input_Post_Direction_Clean__SingleValue_Invalid,KEL.typ.int Input_Unit_Desig_Clean__SingleValue_Invalid,KEL.typ.int Input_Secondary_Range_Clean__SingleValue_Invalid,KEL.typ.int Input_City_Name_Clean__SingleValue_Invalid,KEL.typ.int Input_State_Clean__SingleValue_Invalid,KEL.typ.int Input_Zip5_Clean__SingleValue_Invalid,KEL.typ.int Input_Zip4_Clean__SingleValue_Invalid,KEL.typ.int Input_Latitude_Clean__SingleValue_Invalid,KEL.typ.int Input_Longitude_Clean__SingleValue_Invalid,KEL.typ.int Input_County_Clean__SingleValue_Invalid,KEL.typ.int Input_Geoblock_Clean__SingleValue_Invalid,KEL.typ.int Input_Address_Type_Clean__SingleValue_Invalid,KEL.typ.int Input_Address_Status_Clean__SingleValue_Invalid,KEL.typ.int Input_E_Mail_Clean__SingleValue_Invalid,KEL.typ.int Input_Home_Phone_Clean__SingleValue_Invalid,KEL.typ.int Input_Work_Phone_Clean__SingleValue_Invalid,KEL.typ.int Input_D_L_Number_Clean__SingleValue_Invalid,KEL.typ.int Input_D_L_State_Clean__SingleValue_Invalid,KEL.typ.int Input_D_O_B_Clean__SingleValue_Invalid,KEL.typ.int Input_S_S_N_Clean__SingleValue_Invalid,KEL.typ.int Input_Archive_Date_Clean__SingleValue_Invalid,KEL.typ.int Rep_Number__SingleValue_Invalid});
  EXPORT NullCounts := DATASET([
    ]
  ,{KEL.typ.str entity,KEL.typ.str fileName,KEL.typ.str fieldName,KEL.typ.int nullCount,KEL.typ.int notNullCount});
END;
