//HPCC Systems KEL Compiler Version 0.11.6
IMPORT KEL011 AS KEL;
IMPORT CFG_Compile,E_Criminal_Details,E_Criminal_Offender,E_Criminal_Offense,E_Criminal_Punishment,E_Person,E_Person_Offender FROM PublicRecords_KEL;
IMPORT * FROM KEL011.Null;
EXPORT Q_Criminal_Punishment_Search(KEL.typ.uid __PLexID, UNSIGNED1 __PDPM, CFG_Compile.FDCDataset __in = CFG_Compile.FDCDefault) := MODULE
  SHARED E_Person_Filtered_3(CFG_Compile.FDCDataset __in = CFG_Compile.FDCDefault) := MODULE(E_Person(__in))
    SHARED __UsingFitler(DATASET(InLayout) __ds) := __ds((__ds.__Permits & __PDPM) = __ds.__Permits);
    SHARED __GroupTest(DATASET(InLayout) __g) := EXISTS(__g(__T(__OP2(__g.UID,=,__CN(__PLexID)))));
    SHARED __SourceFilter(DATASET(InLayout) __ds) := __UsingFitler(__ds);
    SHARED __GroupedFilter(GROUPED DATASET(InLayout) __ds) := HAVING(__ds,__GroupTest(ROWS(LEFT)));
  END;
  SHARED E_Person_Offender_Filtered_2(CFG_Compile.FDCDataset __in = CFG_Compile.FDCDefault) := MODULE(E_Person_Offender(__in))
    SHARED __UsingFitler(DATASET(InLayout) __ds) := __ds((__ds.__Permits & __PDPM) = __ds.__Permits);
    SHARED __SourceFilter(DATASET(InLayout) __ds) := __UsingFitler(__ds);
    SHARED __GroupedFilter(GROUPED DATASET(InLayout) __ds) := JOIN(__ds,E_Person_Filtered_3(__in).__PostFilter,__EEQP(LEFT.Subject_,RIGHT.UID),TRANSFORM(InLayout,SELF:=LEFT),HASH,GROUPED,KEEP(1));
  END;
  SHARED E_Criminal_Details_Filtered_1(CFG_Compile.FDCDataset __in = CFG_Compile.FDCDefault) := MODULE(E_Criminal_Details(__in))
    SHARED __UsingFitler(DATASET(InLayout) __ds) := __ds((__ds.__Permits & __PDPM) = __ds.__Permits);
    SHARED __SourceFilter(DATASET(InLayout) __ds) := __UsingFitler(__ds);
    SHARED __GroupedFilter(GROUPED DATASET(InLayout) __ds) := JOIN(__ds,E_Person_Offender_Filtered_2(__in).__PostFilter,__EEQP(LEFT.Offender_,RIGHT.Offender_),TRANSFORM(InLayout,SELF:=LEFT),HASH,GROUPED,KEEP(1));
  END;
  SHARED E_Criminal_Punishment_Filtered(CFG_Compile.FDCDataset __in = CFG_Compile.FDCDefault) := MODULE(E_Criminal_Punishment(__in))
    SHARED __UsingFitler(DATASET(InLayout) __ds) := __ds((__ds.__Permits & __PDPM) = __ds.__Permits);
    SHARED __SourceFilter(DATASET(InLayout) __ds) := __UsingFitler(__ds);
    SHARED __GroupedFilter(GROUPED DATASET(InLayout) __ds) := JOIN(__ds,E_Criminal_Details_Filtered_1(__in).__PostFilter,__EEQP(LEFT.UID,RIGHT.Punishment_),TRANSFORM(InLayout,SELF:=LEFT),HASH,GROUPED,KEEP(1));
  END;
  SHARED E_Criminal_Details_Filtered := E_Criminal_Details_Filtered_1;
  SHARED E_Person_Filtered := E_Person_Filtered_3;
  SHARED E_Person_Offender_Filtered := E_Person_Offender_Filtered_2;
  SHARED TYPEOF(E_Criminal_Details(__in).__Result) __E_Criminal_Details := E_Criminal_Details_Filtered(__in).__Result;
  SHARED TYPEOF(E_Criminal_Punishment(__in).__Result) __E_Criminal_Punishment := E_Criminal_Punishment_Filtered(__in).__Result;
  SHARED TYPEOF(E_Person(__in).__Result) __E_Person := E_Person_Filtered(__in).__Result;
  SHARED TYPEOF(E_Person_Offender(__in).__Result) __E_Person_Offender := E_Person_Offender_Filtered(__in).__Result;
  SHARED __EE15759 := __E_Person;
  SHARED __EE18148 := __EE15759(__T(__OP2(__EE15759.UID,=,__CN(__PLexID))));
  SHARED __EE15762 := __E_Criminal_Punishment;
  SHARED __EE15761 := __E_Criminal_Details;
  SHARED __EE17143 := __EE15761(__NN(__EE15761.Offender_) AND __NN(__EE15761.Punishment_));
  SHARED __EE15760 := __E_Person_Offender;
  SHARED __EE17173 := __EE15760(__NN(__EE15760.Subject_) AND __NN(__EE15760.Offender_));
  __JC18157(E_Person_Offender(__in).Layout __EE17173, E_Person(__in).Layout __EE18148) := __EEQP(__EE18148.UID,__EE17173.Subject_);
  SHARED __EE18158 := JOIN(__EE17173,__EE18148,__JC18157(LEFT,RIGHT),TRANSFORM(E_Person_Offender(__in).Layout,SELF:=LEFT),MANY LOOKUP,KEEP(1));
  SHARED __ST14988_Layout := RECORD
    KEL.typ.ntyp(E_Criminal_Offender().Typ) Offender_;
    KEL.typ.ntyp(E_Criminal_Offense().Typ) Offense_;
    KEL.typ.ntyp(E_Criminal_Punishment().Typ) Punishment_;
    KEL.typ.ndataset(E_Criminal_Details(__in).Data_Sources_Layout) Data_Sources_;
    KEL.typ.ntyp(E_Person().Typ) Subject_;
    KEL.typ.ntyp(E_Criminal_Offender().Typ) Offender__1_;
    KEL.typ.ndataset(E_Person_Offender(__in).Data_Sources_Layout) Data_Sources__1_;
    KEL.typ.epoch Date_First_Seen_ := 0;
    KEL.typ.epoch Date_Last_Seen_ := 0;
    KEL.typ.int __RecordCount := 0;
  END;
  __JC18167(E_Criminal_Details(__in).Layout __EE17143, E_Person_Offender(__in).Layout __EE18158) := __EEQP(__EE18158.Offender_,__EE17143.Offender_);
  __ST14988_Layout __JT18167(E_Criminal_Details(__in).Layout __l, E_Person_Offender(__in).Layout __r) := TRANSFORM
    SELF.Offender__1_ := __r.Offender_;
    SELF.Data_Sources__1_ := __r.Data_Sources_;
    SELF := __l;
    SELF := __r;
  END;
  SHARED __EE18168 := JOIN(__EE17143,__EE18158,__JC18167(LEFT,RIGHT),__JT18167(LEFT,RIGHT),INNER,MANY LOOKUP);
  SHARED __ST15022_Layout := RECORD
    KEL.typ.nuid UID;
    KEL.typ.ndataset(E_Criminal_Punishment(__in).Sources_Layout) Sources_;
    KEL.typ.ndataset(E_Criminal_Punishment(__in).Reported_Punishment_Persistent_I_Ds_Layout) Reported_Punishment_Persistent_I_Ds_;
    KEL.typ.ndataset(E_Criminal_Punishment(__in).Reported_Punishment_Layout) Reported_Punishment_;
    KEL.typ.nstr Punishment_Type_;
    KEL.typ.nstr Source_State_;
    KEL.typ.nstr Current_Known_Inmate_Status_;
    KEL.typ.nstr Sentence_County_;
    KEL.typ.nstr Current_Location_Of_Inmate_;
    KEL.typ.nstr Current_Location_Security_;
    KEL.typ.nstr Offender_Key_;
    KEL.typ.nstr Current_Status_;
    KEL.typ.nstr Probation_Time_Period_;
    KEL.typ.nstr Consecutive_And_Concurrent_Information_;
    KEL.typ.nstr Instituiton_Name_;
    KEL.typ.nfloat Restitution_;
    KEL.typ.nstr Community_Service_;
    KEL.typ.ndataset(E_Criminal_Punishment(__in).Data_Sources_Layout) Data_Sources_;
    KEL.typ.ntyp(E_Criminal_Offender().Typ) Offender_;
    KEL.typ.ntyp(E_Criminal_Offense().Typ) Offense_;
    KEL.typ.ntyp(E_Criminal_Punishment().Typ) Punishment_;
    KEL.typ.ndataset(E_Criminal_Details(__in).Data_Sources_Layout) Data_Sources__1_;
    KEL.typ.ntyp(E_Person().Typ) Subject_;
    KEL.typ.ntyp(E_Criminal_Offender().Typ) Offender__1_;
    KEL.typ.ndataset(E_Person_Offender(__in).Data_Sources_Layout) Data_Sources__2_;
    KEL.typ.epoch Date_First_Seen_ := 0;
    KEL.typ.epoch Date_Last_Seen_ := 0;
    KEL.typ.int __RecordCount := 0;
  END;
  __JC18177(E_Criminal_Punishment(__in).Layout __EE15762, __ST14988_Layout __EE18168) := __EEQP(__EE18168.Punishment_,__EE15762.UID);
  __ST15022_Layout __JT18177(E_Criminal_Punishment(__in).Layout __l, __ST14988_Layout __r) := TRANSFORM
    SELF.Data_Sources__1_ := __r.Data_Sources_;
    SELF.Data_Sources__2_ := __r.Data_Sources__1_;
    SELF := __l;
    SELF := __r;
  END;
  SHARED __EE18178 := JOIN(__EE15762,__EE18168,__JC18177(LEFT,RIGHT),__JT18177(LEFT,RIGHT),INNER,MANY LOOKUP);
  SHARED __ST15578_Layout := RECORD
    KEL.typ.nuid UID;
    KEL.typ.nstr Gender_;
    KEL.typ.nstr Lex_I_D_Segment_;
    KEL.typ.ndataset(E_Person(__in).Full_Name_Layout) Full_Name_;
    KEL.typ.ndataset(E_Person(__in).Reported_Dates_Of_Birth_Layout) Reported_Dates_Of_Birth_;
    KEL.typ.ndataset(E_Person(__in).Reported_Dates_Of_Death_Layout) Reported_Dates_Of_Death_;
    KEL.typ.nstr Race_;
    KEL.typ.nstr Race_Description_;
    KEL.typ.ndataset(E_Person(__in).Data_Sources_Layout) Data_Sources_;
    KEL.typ.ndataset(__ST15022_Layout) Punishment_;
    KEL.typ.epoch Date_First_Seen_ := 0;
    KEL.typ.epoch Date_Last_Seen_ := 0;
    KEL.typ.int __RecordCount := 0;
  END;
  __JC18187(E_Person(__in).Layout __EE18148, __ST15022_Layout __EE18178) := __EEQP(__EE18148.UID,__EE18178.Subject_);
  __ST15578_Layout __Join__ST15578_Layout(E_Person(__in).Layout __r, DATASET(__ST15022_Layout) __recs) := TRANSFORM
    SELF := __r;
    SELF.Punishment_ := __CN(__recs);
  END;
  SHARED __EE18188 := DENORMALIZE(DISTRIBUTE(__EE18148,HASH(UID)),DISTRIBUTE(__EE18178,HASH(Subject_)),__JC18187(LEFT,RIGHT),GROUP,__Join__ST15578_Layout(LEFT,ROWS(RIGHT)),LOCAL,MANY LOOKUP);
  SHARED __ST3144_Layout := RECORD
    KEL.typ.nstr Source_File_;
    KEL.typ.epoch Date_First_Seen_ := 0;
    KEL.typ.epoch Date_Last_Seen_ := 0;
    KEL.typ.int __RecordCount := 0;
  END;
  SHARED __ST3149_Layout := RECORD
    KEL.typ.nstr Punishment_Persistent_I_D_;
    KEL.typ.epoch Date_First_Seen_ := 0;
    KEL.typ.epoch Date_Last_Seen_ := 0;
    KEL.typ.int __RecordCount := 0;
  END;
  SHARED __ST3154_Layout := RECORD
    KEL.typ.nint Sentence_Length_;
    KEL.typ.nstr Sentence_Description_;
    KEL.typ.nstr Sentence_Length_Description_;
    KEL.typ.nstr Sentence_Type_;
    KEL.typ.nkdate Date_Of_Sentence_;
    KEL.typ.nkdate Incarceration_Admission_Date_;
    KEL.typ.nkdate Scheduled_Release_Date_;
    KEL.typ.nkdate Actual_Release_Date_;
    KEL.typ.nkdate Control_Release_Date_;
    KEL.typ.nkdate Presumptive_Parole_Release_Date_;
    KEL.typ.nint Parole_Current_Status_;
    KEL.typ.nstr Parole_Current_Status_Description_;
    KEL.typ.nkdate Parole_Start_Date_;
    KEL.typ.nkdate Parole_Scheduled_Release_Date_;
    KEL.typ.nkdate Parole_Actual_Release_Date_;
    KEL.typ.nstr Parole_County_;
    KEL.typ.nkdate Probation_Start_Date_;
    KEL.typ.nkdate Probation_End_Date_;
    KEL.typ.nstr Probation_Status_;
    KEL.typ.nstr Additional_Provision1_;
    KEL.typ.nstr Additional_Provision2_;
    KEL.typ.nstr Additional_Sentence_Dates_;
    KEL.typ.nstr Probation_Description_;
    KEL.typ.nint Minimum_Term_;
    KEL.typ.nstr Minimum_Term_Description_;
    KEL.typ.nint Maximum_Term_;
    KEL.typ.nstr Maximum_Term_Description_;
    KEL.typ.epoch Date_First_Seen_ := 0;
    KEL.typ.epoch Date_Last_Seen_ := 0;
    KEL.typ.int __RecordCount := 0;
  END;
  SHARED __ST3185_Layout := RECORD
    KEL.typ.nstr Source_;
    KEL.typ.epoch Date_First_Seen_ := 0;
    KEL.typ.epoch Date_Last_Seen_ := 0;
    KEL.typ.int __RecordCount := 0;
  END;
  SHARED __ST3188_Layout := RECORD
    KEL.typ.ndataset(__ST3144_Layout) Sources_;
    KEL.typ.ndataset(__ST3149_Layout) Reported_Punishment_Persistent_I_Ds_;
    KEL.typ.ndataset(__ST3154_Layout) Reported_Punishment_;
    KEL.typ.nstr Punishment_Type_;
    KEL.typ.nstr Source_State_;
    KEL.typ.nstr Current_Known_Inmate_Status_;
    KEL.typ.nstr Sentence_County_;
    KEL.typ.nstr Current_Location_Of_Inmate_;
    KEL.typ.nstr Current_Location_Security_;
    KEL.typ.nstr Offender_Key_;
    KEL.typ.nstr Current_Status_;
    KEL.typ.nstr Probation_Time_Period_;
    KEL.typ.nstr Consecutive_And_Concurrent_Information_;
    KEL.typ.nstr Instituiton_Name_;
    KEL.typ.nfloat Restitution_;
    KEL.typ.nstr Community_Service_;
    KEL.typ.ndataset(__ST3185_Layout) Data_Sources_;
    KEL.typ.epoch Date_First_Seen_ := 0;
    KEL.typ.epoch Date_Last_Seen_ := 0;
    KEL.typ.int __RecordCount := 0;
  END;
  SHARED __ST3207_Layout := RECORD
    KEL.typ.nuid UID;
    KEL.typ.ndataset(__ST3188_Layout) Punishment_;
    KEL.typ.epoch Date_First_Seen_ := 0;
    KEL.typ.epoch Date_Last_Seen_ := 0;
    KEL.typ.int __RecordCount := 0;
  END;
  SHARED __ST3207_Layout __ND17901__Project(__ST15578_Layout __PP17897) := TRANSFORM
    __EE18191 := __PP17897.Punishment_;
    __ST3188_Layout __ND17936__Project(__ST15022_Layout __PP17923) := TRANSFORM
      __EE18194 := __PP17923.Sources_;
      SELF.Sources_ := __BN(PROJECT(TABLE(PROJECT(__T(__EE18194),__ST3144_Layout),{KEL.typ.int __RecordCount := SUM(GROUP,__RecordCount),KEL.typ.epoch Date_First_Seen_ := KEL.era.SimpleRoll(GROUP,Date_First_Seen_,MIN,TRUE),KEL.typ.epoch Date_Last_Seen_ := KEL.era.SimpleRoll(GROUP,Date_Last_Seen_,MAX,FALSE),Source_File_},Source_File_,MERGE),__ST3144_Layout),__NL(__EE18194));
      __EE18203 := __PP17923.Reported_Punishment_Persistent_I_Ds_;
      SELF.Reported_Punishment_Persistent_I_Ds_ := __BN(PROJECT(TABLE(PROJECT(__T(__EE18203),__ST3149_Layout),{KEL.typ.int __RecordCount := SUM(GROUP,__RecordCount),KEL.typ.epoch Date_First_Seen_ := KEL.era.SimpleRoll(GROUP,Date_First_Seen_,MIN,TRUE),KEL.typ.epoch Date_Last_Seen_ := KEL.era.SimpleRoll(GROUP,Date_Last_Seen_,MAX,FALSE),Punishment_Persistent_I_D_},Punishment_Persistent_I_D_,MERGE),__ST3149_Layout),__NL(__EE18203));
      __EE18197 := __PP17923.Reported_Punishment_;
      SELF.Reported_Punishment_ := __BN(PROJECT(TABLE(PROJECT(__T(__EE18197),__ST3154_Layout),{KEL.typ.int __RecordCount := SUM(GROUP,__RecordCount),KEL.typ.epoch Date_First_Seen_ := KEL.era.SimpleRoll(GROUP,Date_First_Seen_,MIN,TRUE),KEL.typ.epoch Date_Last_Seen_ := KEL.era.SimpleRoll(GROUP,Date_Last_Seen_,MAX,FALSE),Sentence_Length_,Sentence_Description_,Sentence_Length_Description_,Sentence_Type_,Date_Of_Sentence_,Incarceration_Admission_Date_,Scheduled_Release_Date_,Actual_Release_Date_,Control_Release_Date_,Presumptive_Parole_Release_Date_,Parole_Current_Status_,Parole_Current_Status_Description_,Parole_Start_Date_,Parole_Scheduled_Release_Date_,Parole_Actual_Release_Date_,Parole_County_,Probation_Start_Date_,Probation_End_Date_,Probation_Status_,Additional_Provision1_,Additional_Provision2_,Additional_Sentence_Dates_,Probation_Description_,Minimum_Term_,Minimum_Term_Description_,Maximum_Term_,Maximum_Term_Description_},Sentence_Length_,Sentence_Description_,Sentence_Length_Description_,Sentence_Type_,Date_Of_Sentence_,Incarceration_Admission_Date_,Scheduled_Release_Date_,Actual_Release_Date_,Control_Release_Date_,Presumptive_Parole_Release_Date_,Parole_Current_Status_,Parole_Current_Status_Description_,Parole_Start_Date_,Parole_Scheduled_Release_Date_,Parole_Actual_Release_Date_,Parole_County_,Probation_Start_Date_,Probation_End_Date_,Probation_Status_,Additional_Provision1_,Additional_Provision2_,Additional_Sentence_Dates_,Probation_Description_,Minimum_Term_,Minimum_Term_Description_,Maximum_Term_,Maximum_Term_Description_,MERGE),__ST3154_Layout),__NL(__EE18197));
      __EE18200 := __PP17923.Data_Sources_;
      SELF.Data_Sources_ := __BN(PROJECT(TABLE(PROJECT(__T(__EE18200),__ST3185_Layout),{KEL.typ.int __RecordCount := SUM(GROUP,__RecordCount),KEL.typ.epoch Date_First_Seen_ := KEL.era.SimpleRoll(GROUP,Date_First_Seen_,MIN,TRUE),KEL.typ.epoch Date_Last_Seen_ := KEL.era.SimpleRoll(GROUP,Date_Last_Seen_,MAX,FALSE),Source_},Source_,MERGE),__ST3185_Layout),__NL(__EE18200));
      SELF := __PP17923;
    END;
    __ST3188_Layout __ND17936__Rollup(__ST3188_Layout __r, DATASET(__ST3188_Layout) __recs) := TRANSFORM
      __recs_Sources_ := NORMALIZE(__recs,__T(LEFT.Sources_),TRANSFORM(__ST3144_Layout,SELF:=RIGHT));
      __recs_Sources__allnull := NOT EXISTS(__recs(__NN(Sources_)));
      SELF.Sources_ := __BN(PROJECT(TABLE(__recs_Sources_,{KEL.typ.int __RecordCount := SUM(GROUP,__RecordCount),KEL.typ.epoch Date_First_Seen_ := KEL.era.SimpleRoll(GROUP,Date_First_Seen_,MIN,TRUE),KEL.typ.epoch Date_Last_Seen_ := KEL.era.SimpleRoll(GROUP,Date_Last_Seen_,MAX,FALSE),Source_File_},Source_File_),__ST3144_Layout),__recs_Sources__allnull);
      __recs_Reported_Punishment_Persistent_I_Ds_ := NORMALIZE(__recs,__T(LEFT.Reported_Punishment_Persistent_I_Ds_),TRANSFORM(__ST3149_Layout,SELF:=RIGHT));
      __recs_Reported_Punishment_Persistent_I_Ds__allnull := NOT EXISTS(__recs(__NN(Reported_Punishment_Persistent_I_Ds_)));
      SELF.Reported_Punishment_Persistent_I_Ds_ := __BN(PROJECT(TABLE(__recs_Reported_Punishment_Persistent_I_Ds_,{KEL.typ.int __RecordCount := SUM(GROUP,__RecordCount),KEL.typ.epoch Date_First_Seen_ := KEL.era.SimpleRoll(GROUP,Date_First_Seen_,MIN,TRUE),KEL.typ.epoch Date_Last_Seen_ := KEL.era.SimpleRoll(GROUP,Date_Last_Seen_,MAX,FALSE),Punishment_Persistent_I_D_},Punishment_Persistent_I_D_),__ST3149_Layout),__recs_Reported_Punishment_Persistent_I_Ds__allnull);
      __recs_Reported_Punishment_ := NORMALIZE(__recs,__T(LEFT.Reported_Punishment_),TRANSFORM(__ST3154_Layout,SELF:=RIGHT));
      __recs_Reported_Punishment__allnull := NOT EXISTS(__recs(__NN(Reported_Punishment_)));
      SELF.Reported_Punishment_ := __BN(PROJECT(TABLE(__recs_Reported_Punishment_,{KEL.typ.int __RecordCount := SUM(GROUP,__RecordCount),KEL.typ.epoch Date_First_Seen_ := KEL.era.SimpleRoll(GROUP,Date_First_Seen_,MIN,TRUE),KEL.typ.epoch Date_Last_Seen_ := KEL.era.SimpleRoll(GROUP,Date_Last_Seen_,MAX,FALSE),Sentence_Length_,Sentence_Description_,Sentence_Length_Description_,Sentence_Type_,Date_Of_Sentence_,Incarceration_Admission_Date_,Scheduled_Release_Date_,Actual_Release_Date_,Control_Release_Date_,Presumptive_Parole_Release_Date_,Parole_Current_Status_,Parole_Current_Status_Description_,Parole_Start_Date_,Parole_Scheduled_Release_Date_,Parole_Actual_Release_Date_,Parole_County_,Probation_Start_Date_,Probation_End_Date_,Probation_Status_,Additional_Provision1_,Additional_Provision2_,Additional_Sentence_Dates_,Probation_Description_,Minimum_Term_,Minimum_Term_Description_,Maximum_Term_,Maximum_Term_Description_},Sentence_Length_,Sentence_Description_,Sentence_Length_Description_,Sentence_Type_,Date_Of_Sentence_,Incarceration_Admission_Date_,Scheduled_Release_Date_,Actual_Release_Date_,Control_Release_Date_,Presumptive_Parole_Release_Date_,Parole_Current_Status_,Parole_Current_Status_Description_,Parole_Start_Date_,Parole_Scheduled_Release_Date_,Parole_Actual_Release_Date_,Parole_County_,Probation_Start_Date_,Probation_End_Date_,Probation_Status_,Additional_Provision1_,Additional_Provision2_,Additional_Sentence_Dates_,Probation_Description_,Minimum_Term_,Minimum_Term_Description_,Maximum_Term_,Maximum_Term_Description_),__ST3154_Layout),__recs_Reported_Punishment__allnull);
      __recs_Data_Sources_ := NORMALIZE(__recs,__T(LEFT.Data_Sources_),TRANSFORM(__ST3185_Layout,SELF:=RIGHT));
      __recs_Data_Sources__allnull := NOT EXISTS(__recs(__NN(Data_Sources_)));
      SELF.Data_Sources_ := __BN(PROJECT(TABLE(__recs_Data_Sources_,{KEL.typ.int __RecordCount := SUM(GROUP,__RecordCount),KEL.typ.epoch Date_First_Seen_ := KEL.era.SimpleRoll(GROUP,Date_First_Seen_,MIN,TRUE),KEL.typ.epoch Date_Last_Seen_ := KEL.era.SimpleRoll(GROUP,Date_Last_Seen_,MAX,FALSE),Source_},Source_),__ST3185_Layout),__recs_Data_Sources__allnull);
      SELF.__RecordCount := SUM(__recs,__RecordCount);
      SELF.Date_First_Seen_ := KEL.era.SimpleRoll(__recs,Date_First_Seen_,MIN,TRUE);
      SELF.Date_Last_Seen_ := KEL.era.SimpleRoll(__recs,Date_Last_Seen_,MAX,FALSE);
      SELF := __r;
    END;
    SELF.Punishment_ := __BN(ROLLUP(GROUP(KEL.Routines.SortAndAppendFilteredChildren(PROJECT(__T(__EE18191),__ND17936__Project(LEFT))(__NN(Sources_) OR __NN(Reported_Punishment_Persistent_I_Ds_) OR __NN(Reported_Punishment_) OR __NN(Punishment_Type_) OR __NN(Source_State_) OR __NN(Current_Known_Inmate_Status_) OR __NN(Sentence_County_) OR __NN(Current_Location_Of_Inmate_) OR __NN(Current_Location_Security_) OR __NN(Offender_Key_) OR __NN(Current_Status_) OR __NN(Probation_Time_Period_) OR __NN(Consecutive_And_Concurrent_Information_) OR __NN(Instituiton_Name_) OR __NN(Restitution_) OR __NN(Community_Service_) OR __NN(Data_Sources_)),'Sources_,Reported_Punishment_Persistent_I_Ds_,Reported_Punishment_,Data_Sources_','sources_,reported_punishment_persistent_i_ds_,reported_punishment_,data_sources_','clean','__recordcount,date_first_seen_,date_last_seen_'),Sources_Clean,Reported_Punishment_Persistent_I_Ds_Clean,Reported_Punishment_Clean,Punishment_Type_,Source_State_,Current_Known_Inmate_Status_,Sentence_County_,Current_Location_Of_Inmate_,Current_Location_Security_,Offender_Key_,Current_Status_,Probation_Time_Period_,Consecutive_And_Concurrent_Information_,Instituiton_Name_,Restitution_,Community_Service_,Data_Sources_Clean,ALL),GROUP,__ND17936__Rollup(ROW(LEFT,__ST3188_Layout), PROJECT(ROWS(LEFT),__ST3188_Layout))),__NL(__EE18191));
    SELF := __PP17897;
  END;
  EXPORT Res0 := __UNWRAP(PROJECT(PROJECT(__EE18188,__ND17901__Project(LEFT)),__ST3207_Layout));
END;
